### ISSUE TITLE
Refunding causes order.isPaid to return false

### ISSUE THREAD

**Issue by cliveportman** [craftcms/commerce#1000]
### Description
Making a partial refund (or maybe even a complete one) causes {{ order.isPaid }} to return false.

### Steps to reproduce

1. Make a refund.
2. View a template looking for {{ order.isPaid }}.

### Additional info

- Craft version: 3.3.1.2
- PHP version: 7.2.4
- Commerce version: 2.1.13

**Comment by lukeholder** [comment]
If you refund the order even partially, how could isPaid be true logically?

**Comment by lukeholder** [comment]
Going to close this, but if you can explain a bit more of what you're trying to do maybe I can point you in a better direction. Thanks.

**Comment by cliveportman** [comment]
I guess it depends what you mean by an order being paid, but we're using it as a proxy for identifying whether a payment has been captured or not. I assume this is what it's for? If not, what is it for?

And if it is for indicating whether an order has been paid for, whether a refund has since been issued has nothing to do with it. The order has still been paid/captured.

**Comment by lukeholder** [comment]
@cliveportman isPaid is a reflection of the current paid status.

Are you looking for a `wasPaid`?

**Comment by cliveportman** [comment]
wasPaid would be perfect!
