### ISSUE TITLE
carts.mergedCarts issue when Allowed Qty or Qty is not high enough

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#1001]
### Description
There seems to be an issue when using mergedCarts.  I tried to replicate it as precisely as possible and I hope that this will work on your end to reproduce it

### Steps to reproduce
1- Have a product with a qty of 1, or a allowed qty with a max of 1
2- Start by using the normal `set cart = craft.commerce.carts.mergedCart` object in your template.
3- Login and add the item in your cart.
4- Open a new browser or incognito tab, login and add that same item
5- You should now have 2 carts in the backend for the same user and with the same item.
6- Now, change your template to use `set cart = craft.commerce.carts.mergedCart`
7- Open a new browser and login to that account
8- You should  now see a cart with the 1 item (x2), with an error on qty
9- Look in the backend again.  The 2 carts are still there, not merged.
10- If I replace the item, or change the available quantity, the merge happened without any issues and it deleted the extra carts.

It seems that if there's an error on the cart, the real merge and the deletion of the other carts doesn't happen.  

I think that the merge should still happen, but with the errors set on the cart, like it would normally happen if someone tries to adds an item that he can't.

If not possible, what is your solution for this?  Right now, my template is in a continuous loop of telling the user that there's carts to merge because it actually never happens for real.

### Additional info

- Craft version: Craft Pro 3.3.1.2
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins & versions:
Commerce 2.1.13

**Comment by echantigny** [comment]
This seems to also be some kind of an issue with the cart as a whole, isn't it?

If I add things to my cart, and then go in the CP and reduce the qty of that item to 0 to simulate another user buying it, I don't get any `cart.errors` or lineItem `hasErrors()`.

The only way to actually see that there's an error is to try to update it again by adding other items or addresses, etc...

Any way to get around that one?  Seems like both are pretty much the same issue.

**Comment by lukeholder** [comment]
Thanks eric looking into this now.

**Comment by lukeholder** [comment]
Going to refactor this in 3.0 and move merging to it's own method, and out of getCart

**Comment by eric-chantigny** [comment]
@lukeholder So now we are stuck to what 2.1.11 brought in?  No way to go back to what it was in 2.1.10 with the automated merging the way it worked then?

I'm ok with that, and can try to make it work, but there's a lot of work to be done around the errors that can come up on the merging to avoid an infinite loop of trying to merge.

**Comment by lukeholder** [comment]
Auto cart merging has been removed in Commerce 3.

Let you customers restore the items themselves: https://docs.craftcms.com/commerce/v3/adding-to-and-updating-the-cart.html#restoring-previous-cart-contents

The previous cart will be restored if the current cart is empty.
