### ISSUE TITLE
Option to return order custom field data in AJAX response

### ISSUE THREAD

**Issue by elivz** [craftcms/commerce#1002]
### Description

Currently, the JSON representation of a cart (either in the response to an AJAX call or via `craft.commerce.orders.cartArray(craft.commerce.carts.cart)` does not include any Order Fields that have been set up. I assume this is for performance reasons, but there are a lot of cases where one might want/need that data. For example, I am creating an AJAX-powered cart, and need to be able to retrieve and save custom field data. Saving works fine (via the `commerce/cart/update-cart` action, but there appears to be no way to get that data back out, short of creating a custom endpoint. Am I missing something?

If you prefer not to include that data by default, maybe you could add an event to modify the cart data, similar to how we can use `EVENT_AFTER_CAPTURE_PRODUCT_SNAPSHOT` to add data to the line item snapshot?

**Comment by bossanova808** [comment]
For context, you might want to read the various recent issues on this:
https://github.com/craftcms/commerce/issues?utf8=%E2%9C%93&q=is%3Aissue+snapshot+data

And this is, I think, the even you can use to force particular custom fields to be added:
https://docs.craftcms.com/commerce/api/v2/craft-commerce-events-customizeproductsnapshotfieldsevent.html#public-properties

**Comment by elivz** [comment]
I believe those links only apply to retrieving *product* custom fields. What I am looking for is a similar system to include *order* custom field data in the AJAX response.

**Comment by bossanova808** [comment]
Right you are!  Silly me, read that too quickly, sorry for the noise. 

A similar approach would make sense here...

**Comment by jlapan** [comment]
Hey @elivz , I found this issue and I have a similar use case. I am wondering how you structured your ajax post call to get it to return custom order field data?

**Comment by elivz** [comment]
I didn't. Looks like @lukeholder added a new `EVENT_MODIFY_CART_INFO` event for the purpose in Commerce 3, but the project I needed this for is still on v2, so I haven't had a chance to play around with it yet.

**Comment by jlapan** [comment]
Ok great. No problem. I figured out another solution in the meantime. Thanks!
