### ISSUE TITLE
Custom Order Status Description Field

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce#1004]
It would be really nice to have a field on custom order statuses to be able to set a brief description of the status.

This would be really useful for showing on the frontend, in account areas and whilst managing orders.

Coming from other systems which have this ability, even just a basic text field added to the status model would be very helpful.

**Comment by lukeholder** [comment]
May just add the description field for now.

**Comment by andrewhawkes** [comment]
@lukeholder would be really useful. Saves having to have additional template logic to show a message.

**Comment by nfourtythree** [comment]
Have just pushed up code for this. Will be included in `2.2`
