### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by MarcelWeidum** [craftcms/commerce#1005]
### Description
Error when opening an order. ERR_EMPTY_RESPONSE

### Additional info

- Craft version: 3.1.33
- PHP version: 7.2
- Database driver & version: -
- Plugins & versions: commerce 2.1.10

### Reproduce
Craft commerce local in MAMP.

**Comment by MarcelWeidum** [comment]
I found where it goes wrong.

https://github.com/craftcms/commerce/blob/develop/src/templates/orders/_edit.html#L12

**Comment by lukeholder** [comment]
Can you please reproduce and send your logs to support@craftcms.com thanks.

**Comment by lukeholder** [comment]
Can't see your email to support. Please submit with this ticket number and we can look to re-open.
