### ISSUE TITLE
Discount code with 100% discount and free shipping does not remove shipping tax

### ISSUE THREAD

**Issue by ragnarfrosti** [craftcms/commerce#1007]
### Description

I think there might be a problem with the discounts in Craft Commerce 2 while using a 100% discount code with free shipping.
Running the latest versions of both Craft CMS and Commerce and using discounts with 100% discount and "Remove all shipping costs from the order" checked it removes all costs except the VAT for the shipping, which feels strange…

I can reproduce the bug using a clean install of Commerce and the default templates. Using an address that matches the shipping rule below, a single product in the cart and the coupon code below we get the following: The total price of the cart will be $1, instead of the expected $0.

### Commerce settings for reproducing this error

=== TAX ===

**Tax Zones**
- Sweden

**Tax Categories**
- General

**Tax rates**
- For products
- Taxable Subject: Line item price
- Rate: 12%
- Tax Zone: Sweden
- Tax Category: General
- For Shipping
- Order total shipping cost
- Rate 25%
- Tax zone: Sweden
- Tax category: General

=== SHIPPING ===

**Shipping zones**
- Sweden

**Shipping Categories**
- General
- Available for Product Types: Clothing

**Shipping Methods**
- Shipping Sweden
- Shipping Rules:
- Shipping Sweden rule
- Shipping Zone: Sweden
- Maximum Total shipping cost: 4
- Item Rates - Per Item Rate: 4

=== DISCOUNTS ===
- Test Discount
- Coupon Code: TEST123
- Percent Discount: 100%
- Check "Remove all shipping costs from the order"

### Additional info

- Craft version: 3.3.0.1
- Commerce version: 2.1.12.1
- PHP version: 7.2

**Comment by nfourtythree** [comment]
Have just pushed some code to fix this which will be included the next released
