### ISSUE TITLE
Apply discount to full retail price, not sale price

### ISSUE THREAD

**Issue by ciceronepress** [craftcms/commerce#1008]
My client is using the site-wide **Promotions > Sales** option to run a near-permanent 10% off products.

They also have quite a few permanent discount codes available that offer a fixed percentage of the retail price.

For example, an item is £10.00, with the site wide sale it is available to all customers for £9. For a user with a 20% discount code, they should be able to buy the item for £8. If they enter their code at checkout, it incorrectly prices the item at £7.20 (20% off the £9).

Ideally there needs to be a way to configure a Sale or Discount to cater for this.

**Comment by sjcallender** [comment]
@ciceronepress For the 20% off sale, are you checking the "Ignore previous matching sales if this sale matches" setting?

<img width="717" alt="Screen Shot on 2019-09-22 at 09 38 49" src="https://user-images.githubusercontent.com/984311/65388769-48ff6d00-dd1d-11e9-88f6-d4be066a59c4.png">

**Comment by jrrdnx** [comment]
@ciceronepress What version of Craft Commerce do you have installed? On 2.1.13, I have an option to apply the discount to the original item price instead of the discounted price. Is this what you're looking for?

![Screen Shot 2019-10-03 at 16 43 43](https://user-images.githubusercontent.com/4584671/66162866-231b7780-e5fd-11e9-9d97-e192ce7dab47.png)

**Comment by nfourtythree** [comment]
Hi All, this is something that we are aware of and we are looking into a solution for this. Hopefully to get it into the next significant release.

**Comment by lukeholder** [comment]
Should be fixed by PR #1040

**Comment by ciceronepress** [comment]
@sjcallender and @jrrdnx - I tried all combinations of these settings, but they don't provide the required option.

Many thanks @nfourtythree and @lukeholder for the fix, look forward to 2.2
