### ISSUE TITLE
PDF Filename using incorrect order id

### ISSUE THREAD

**Issue by nickcobley** [craftcms/commerce#1010]
### Description

I just noticed on a few sites, when the Order ID is added to the PDF filename, it is using the next order ID not the order ID for the current order.

For example, I generate my order id using this format:

{{object.dateCompleted|date('y')}}-{{ seq(object.dateCompleted|date('y'), 4) }}

I have the same for both the Order Reference Number Format and Order PDF Filename Format fields. 

Let's say the correct order ID in this instance is 19-0101, when my emails come out, in all cases the order ID is correct other than the ID of the filename is set to 19-0102, ie incremented by 1 and not an existing valid order ID.

### Additional info

- Craft version: 3.2.6
- PHP version: 7.3
- Plugins & versions: 2.1.12.1

**Comment by nfourtythree** [comment]
Hi @nickcobley 

This is because you will need to reference `{number}` in your **Order PDF Filename Format** as if you use the same code the sequencer is called again and therefore the sequence number is updated.

Hope this helps!
