### ISSUE TITLE
16 sec SQL query

### ISSUE THREAD

**Issue by playengineio** [craftcms/commerce#1012]
### Description
I have created a product model in Craft Commerce that contains various tags as product attributes for colors, materials, sizes ect. The basic idea is that i want my craft commerce frontend to have various search product filters for my users to be able to narrow down on the products they want to purchase. 
My main problem is that when i apply some of the filters in the SQL criteria in the craft commerce query, the SQL joins cause MySQL to halt completly for 16-20 sec before a result is retrieved.   
The outcome is that i can't use Craft commerce in production, since i don't expect any user will be waiting this long before the page reloads, and we will likely not sell any items to these customer.

### Steps to reproduce
Here is my twig template query. The problem is really the part "relatedTo: criteria" where the SQL joins mess up MYSQL performance completely.

{# Getting filters params from url #}
{% if craft.app.request.get('materials')|length >=1 %}
    {% set selectedFilterMaterial = craft.app.request.getParam('materials')|split(",") %}
{% else %}
    {%  set selectedFilterMaterial = [] %}
{% endif %}

{% if craft.app.request.get('colors')|length >=1 %}
    {% set selectedFilterColor = craft.app.request.get('colors')|split(",") %}
{% else %}
    {%  set selectedFilterColor = [] %}
{% endif %}

{% if craft.app.request.get('gems')|length >=1 %}
    {% set selectedFilterGem = craft.app.request.get('gems')|split(",") %}
{% else %}
    {%  set selectedFilterGem = [] %}
{% endif %}

{% if craft.app.request.get('sizes')|length >=1 %}
    {% set selectedFilterSize = craft.app.request.get('sizes')|split(",") %}
{% else %}
    {%  set selectedFilterSize = [] %}
{% endif %}

{# Getting product attributes as filters #}
{% set filterMaterials = craft.tags.group('productAttributesMaterials').all() %}
{% set filterColors = craft.tags.group('productAttributesColors').all() %}
{% set filterGems = craft.tags.group('productAttributesGems').all() %}
{% set filterSizes = craft.tags.group('productAttributesSizes').all() %}

{# Getting selected filters as tags #}
{% set selectedMaterialsTags = [] %}
{% for slug in selectedFilterMaterial %}
    {%  set selectedMaterialsTags = selectedMaterialsTags|merge([craft.tags.slug(slug)]) %}
{% endfor %}

{% set selectedColorsTags = [] %}
{% for slug in selectedFilterColor %}
    {%  set selectedColorsTags = selectedColorsTags|merge([craft.tags.slug(slug)]) %}
{% endfor %}

{% set selectedGemsTags = [] %}
{% for slug in selectedFilterGem %}
    {%  set selectedGemsTags = selectedGemsTags|merge([craft.tags.slug(slug)]) %}
{% endfor %}

{% set selectedSizesTags = [] %}
{% for slug in selectedFilterSize %}
    {%  set selectedSizesTags = selectedSizesTags|merge([craft.tags.slug(slug)]) %}
{% endfor %}

{# Preparing the filter query #}
{% set criteria = ['and', {element: entry}] %}

{% if selectedMaterialsTags|length >=1 %}
    {% set criteria = criteria|merge([{targetElement: selectedMaterialsTags, field: 'productAttributesMaterials'}]) %}
{% endif %}

{% if selectedColorsTags|length >=1 %}
    {% set criteria = criteria|merge([{targetElement: selectedColorsTags, field: 'productAttributesColors'}]) %}
{% endif %}

{% if selectedGemsTags|length >=1 %}
    {% set criteria = criteria|merge([{targetElement: selectedGemsTags, field: 'productAttributesGems'}]) %}
{% endif %}

{% if selectedSizesTags|length >=1 %}
    {% set criteria = criteria|merge([{targetElement: selectedSizesTags, field: 'productAttributesSizes'}]) %}
{% endif %}

{% set queryParams =
    {
        with: [
            'productAttributesMaterials',
            'productAttributesColors',
            'productAttributesGems',
            'productAttributesSizes',
            'productAttributesKeywords',
            'productPhotos',
            'variants',
            'brand'],
        relatedTo: criteria,
        limit: 50,
        orderBy: 'postDate'
    }
%}

{% set productResult = craft.products(queryParams) %}

### Additional info

- Craft version: Latest
- Craft commerce: 2.1.13
- PHP version: PHP 7.3.9
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
Amazon S3 1.2.5 
Craft Commerce 2.1.13 
Dumper 2.0.0  
Feed Me 4.1.2 
Jason 1.0.2 
Read-only Field 1.0.1 
Redactor 2.3.3.2 
Relations 1.2.1 
Similar 1.0.6 
Stripe for Craft Commerce 2.1.2 
Tags 1.0.5

**Comment by lukeholder** [comment]
Can you please email support@craftcms.com and attached your DB dump/backup. The limit is 20Gb in the email, so use a dropbox/hosted type link to share the file. Sending the above template in a working HTML file would also help.

We will then take a look and try and reproduce, and see if there is any performance improvements we can see.

**Comment by playengineio** [comment]
hi @lukeholder 
Thank you for your fast reply, i have sent an email to above support email including the blade template and the database dump.

**Comment by lukeholder** [comment]
I tried to reproduce locally and did not find the query taking more than 1-2 seconds:

Video of me reproducing:

https://jmp.sh/LkcUFsx

Could you hosting environment have low specs or be misconfigured? Are other queries for example, listing products in the CP also slow?

**Comment by lukeholder** [comment]
Will re-open if with if more information comes to light in the support request.
