### ISSUE TITLE
Don't renew forgotten Carts

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1016]
### Description

Sometimes I want a User to forget a Cart so I use your function "forgetCart" but you included a function that automatically fetches the last cart of a user that is not trashed and not completed. I have an off-site payment gateway and after the User is redirected to that Gateway the Cart **must** be forgotten in order to disable the ability to change data (lineitems, discounts, the price in general). Thus I removed the session key. But the Order is not completed yet, nor is it deleted.... it is pending.

Your logic breaks my entire workflow now and I need to create a custom behavior that doesn't find those Carts by default because of that.. The other workaround would be to create a new Order by myself

Could you please implement a setting if the user really should not forget a forgotten cart?

### Steps to reproduce

1. Call forget Cart to let a User drop a cart
2. Call getCart and see it has the same cart again, but I would like to have the new one

### Additional info

- Craft version: 3.3.X
- Plugins & versions: Commerce 2.1.13

**Comment by lukeholder** [comment]
I think the best way to do this would be to allow the user to 'commit to pay' which will turn the cart into an unpaid order. What do you think?

**Comment by Anubarak** [comment]
Is that an existing function or do you mean to implement such a thing. Because I never found that.
But yeah, that's basically exaclty what I need.

**Comment by lukeholder** [comment]
In your templates you can do `cart.markAsComplete()` if you want to complete the order and give it a default order status. It will return true or false if the order was marked as complete, you could then redirect them.

Thanks.
