### ISSUE TITLE
Logged in user address pre-populated

### ISSUE THREAD

**Issue by cole007** [craftcms/commerce#1019]
### Description

Odd issue where if login as part of checkout is redirected to address page the address is not initially filled in but on refresh of the page/template it is. Have managed to fix via a module but not sure if there is a problem in the core with how this is made available.

Also not sure if this is because we are defaulting to the shipping address (with form using the `billingAddressSameAsShipping` flag). 

Solution:

```
Event::on(
  User::class, 
  User::EVENT_AFTER_LOGIN, 
  function (Event $e) {
      // get logged in user
      $user = $e->identity;
      $userId = $user->id;
      // get customer Record
      $customer = Commerce::getInstance()->getCustomers()->getCustomerByUserId($userId);
      // get customer primary shipping address
      $shippingId = $customer->primaryShippingAddressId;
      $address = Commerce::getInstance()->getAddresses()->getAddressByIdAndCustomerId($shippingId, $customer->id);
      // get cart
      $order = Commerce::getInstance()->getCarts()->getCart(true);
      // set cart address with primary shipping address (or billing address if used)
      $order->setShippingAddress($address);
  }        	
);
```

### Steps to reproduce

1. set login template to redirect to address form
2. fetch address in form via `{% set addresses = craft.commerce.customers.customer.addresses %}` and prepopulate form accordingly 
3. on login default/primary address not shown
3. on template/page refresh default/primary address is shown

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.1.30
- Database driver & version: MySQL 5.7.26
- Commerce: 2.1.13

**Comment by lukeholder** [comment]
@cole007 Did you end up upgrading to Commerce 3?

**Comment by lukeholder** [comment]
Haven't heard from you on this.

Commerce 2 support has finished sorry. Please upgrade to the latest release.

https://craftcms.com/knowledge-base/supported-versions
