### ISSUE TITLE
Orders - Show date ordered full timestamp, or just including time. Potentially for all other dates

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1020]
Something that's been bothering us for a while is that the date values in the CP when editing an order only show the date, not the time. It'd be great if this could be a full timestamp, in the same way Date Created and Date Updated are shown for various elements across Craft.

This covers Order Date and Paid date specifically.

![image](https://user-images.githubusercontent.com/1221575/65844196-91033d00-e378-11e9-87f1-eecaaed614df.png)

Is there a way this can be configurable?

**Comment by gojira32** [comment]
This is something very basic that needs to be added for Commerce.

Due to things like order cut-off / dispatch times, it is important to be able to easily see the exact time an order was placed as opposed to just being able to see the date.

**Comment by bossanova808** [comment]
Yep, this would be a good improvement to see for sure.

**Comment by lukeholder** [comment]
Will fix. For now, If you hover you should see the time.

**Comment by nfourtythree** [comment]
Hey all

I have updated the order view in the CP with **Order Time**, **Paid Time** and **Last Updated Time**.

This will be included in the next release.

Thanks!

**Comment by engram-design** [comment]
Thanks @nfourtythree !
