### ISSUE TITLE
Making an order and creating a account resets primaryBillingAddress

### ISSUE THREAD

**Issue by MarcelWeidum** [craftcms/commerce#1021]
### Description
When I create an order and make a customer account it saves the primaryBillingAddressId and shippingAddressId.

If you after your first order log in and try to make a second order but now loggedin it sets the primaryBillingAddressId and shippingAddressId to NULL.

### Additional info

- Craft version: 3.3.6
- PHP version: 7.3.7
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Craft Commerce 2.1.13

**Comment by lukeholder** [comment]
Hi sorry, I am not understanding what you mean, could you expand?

`primaryBillingAddressId` is a customer fields and `shippingAddressId` is an order field.

**Comment by MarcelWeidum** [comment]
@lukeholder when I create an order and make a customer account it saves the `primaryBillingAddressId` and `primaryShippingAddressId` in the `commerce_customers` table.

As soon as I login I can see the correct address information of my account. Then when I start to make another order (i think when it creates a cart when loggedin) the `primaryBillingAddressId` and `primaryShippingAddressId` of my commerce_customer account is set too `NULL`.

**Comment by lukeholder** [comment]
This should be fixed in Craft Commerce 3.0. Let us know if the issue continues.
