### ISSUE TITLE
Add ability to limit discounts to specific product variants/categories

### ISSUE THREAD

**Issue by jrrdnx** [craftcms/commerce#1029]
Feature Request:

Currently the 'Conditions' tab allows the owner to limit discounts/coupons to specific product variants and/or categories, but the 'Amounts' are then applied to the cart as a whole or to every product in the cart.

Adding the ability to limit the discount amounts applied to specific product variants/categories would enable the owner to set up 'Buy X Get Y' and 'Buy A, B, and/or C and Get X or Y' type discounts. (If this is currently possible, let me know as I'm just not seeing how to set it up this way).

We may have capacity to implement this functionality on an upcoming project, so we'd be happy to create a pull request and would appreciate any advice you could provide on what files/classes may need touched. Thank you!

**Comment by nfourtythree** [comment]
Hey @jrrdnx 

We are looking to move the discounts to a condition builder, we have an enhancement issue for this: https://github.com/craftcms/commerce/issues/80

I am going to close this issue as you stated it is not currently possible. Please head over and give it a thumbs up.

Thanks!
