### ISSUE TITLE
Order `datePaid` prepped for DB insertion too early

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#1030]
### Description

I think this is a bug! I discovered it while troubleshooting an unrelated error—basically, when `datePaid` is set on Order elements via `$order->updateOrderPaidInformation()`, it preps the value for the database unnecessarily.

I believe this is the offending line:
https://github.com/craftcms/commerce/blob/develop/src/elements/Order.php#L575

Removing the call to `Db::prepareDateForDb(…)` and just using the bare `new DateTime` seems to resolve the error while still inserting the correct time into the database.

Let me know if this tracks?

### Steps to reproduce

This is what I'm a little shaky on…

1. Pay for an order, but produce an unrelated error that prevents `redirectToPostedUrl(…)` from being called (Maybe?);
2. Use the `order` route param/value on the resulting template;
3. Call `order.datePaid.format(…)` and observe an error, or `{{ dump(order.datePaid) }}` and see that it's a `string` instead of a `DateTime`.

❤️ 

### Additional info

- Craft version: Craft Pro 3.3.0.1
- PHP version: 7.2.18
- Database driver & version: PostgreSQL 10.9
- Plugins & versions: Commerce 2.1.12.1 (and some others, one of which is custom, and was producing the error in the first step, above)

**Comment by lukeholder** [comment]
Are you marking as complete in the templates?

**Comment by AugustMiller** [comment]
Nah, sorry, this was just via a normal checkout process (`commerce/payments/pay` controller/action). I included the method just to help describe where I thought the issue might originate, but it's getting called organically by Craft.
