### ISSUE TITLE
Shipping costs calculation product type per Order

### ISSUE THREAD

**Issue by MaximilianSchwarz** [craftcms/commerce#1039]
Is there an option to calculate the shipping cost per product?

**For example:**
We have 3 Product types.
- Clothes
- Shoes
- Accessoires

**Usage:**
Clothes cost 10€ per item
Shoes cost 10€ per item
Accessoires cost 6.90€ per order.

The customer buy 2 clothes, 3 shoes and 5 accessoires.
Currently we have 84,50€ shipping costs, because craft calculate the shipping costs per item.

Now we only want for clothes, shoes the calculation per item and for accessoires per order 
Now we have shipping costs 56.90€

is that possible?

**Comment by nfourtythree** [comment]
Hi @MaximilianSchwarz 

This is possible, I replicated your situation locally and put together a little screencast of how the Shipping Method and Rules need to be set up for this to work.

https://share.getcloudapp.com/wbueebgG

Thanks!
