### ISSUE TITLE
Pricing Catalog Tables

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#1041]
- [ ] Allowed the orderby of  products/variants by salePrice (#1604)

**Comment by TomDeSmet** [comment]
Will this allow us to query on `salePrice` also?

Eg.: I have a price slider to filter products. So I do this in my elementApi:
`$criteria['hasVariant']['price'] = ['and', '>= ' . $priceMin, '<= ' . $priceMax];` 
but I'd like to use the `salePrice` as those will not be filtered correctly now.
