### ISSUE TITLE
Question: Dynamic Products

### ISSUE THREAD

**Issue by internetztube** [craftcms/commerce#1047]
### Question 

Is there a possibility to define a product in such a way that one defines a basis unit from which the price results?
So I have the product wood plate with 1cm thickness and want to let the customer choose length and width. I just want to define the price for one square centimeter.

I could hammer the logic into a custom module, which then dynamically creates a product for e.g. a 100 cm x 200 cm panel. This would have the consequence that after a while I would have a lot of useless products flying around.

What would be your solution? I' d like to avoid manipulating the shopping cart directly.

**Comment by lukeholder** [comment]
This will eventually be solved with #1042 

Check out this event: https://docs.craftcms.com/commerce/v2/events.html#the-populatelineitem-event 

And take a look at how we use it to check the line item options for a custom donationAmount in Core Commerce: 

https://github.com/craftcms/commerce/blob/develop/src/elements/Donation.php#L156-L162

**Comment by internetztube** [comment]
Thanks!
