### ISSUE TITLE
Include variant data in export

### ISSUE THREAD

**Issue by alexjcollins** [craftcms/commerce#1049]
### Description
Feature request to include variant data in the Export functionality; ideally using columns for the variant field data.

---

Right now a number of our clients are maintaining two product databases, one on Craft, the other on a spreadsheet. They'd like to be able to export all the data for reference and their stock reordering process.

**Comment by nfourtythree** [comment]
Hi @alexjcollins 

This is a similar request to #976 .

We are looking at improving the way that exports work. This will rely on an extension of Craft core which you can follow along here craftcms/cms#5090

**Comment by alexjcollins** [comment]
Hey @nfourtythree 

Thanks for pointing that out. Looking forward to seeing where you all go with that 👍 

Would you like this issue closed?

**Comment by lukeholder** [comment]
See #976
