### ISSUE TITLE
Can't use plan.getInformation() in template

### ISSUE THREAD

**Issue by cholawo** [craftcms/commerce#1053]
### Description
Looking at subscriptions in the [example templates](https://github.com/craftcms/commerce/blob/develop/templates/shop/services/index.html#L11) see a line that gets the related entry to a subscription `set information = plan.getInformation()` but the template doesn't use it.

I made a subscription with a related entry, and then attempted to output something from that entry eg its title but I get `Impossible to access an attribute ("title") on a null variable.`  When I just dump it out `dump(information)` I do see the entry model which looks identical to if I dump a single entry with `dump(craft.entries.one()`.

Also if I just replicate the getInformation method in twig and do `set information = craft.entries.id(plan.planInformationId).one()` then I can output things the entry!

### Steps to reproduce

1.  Create a subscription plan and add an entry to the "Description" field
2. Attempt to output any of the entry's attributes in a template

### Additional info

[getInformation() method](https://docs.craftcms.com/commerce/api/v2/craft-commerce-base-plan.html#method-getinformation)

- Craft version: 3.3.9
- PHP version: 7.2.20
- Database driver & version: mysql 5.7.26
- Plugins & versions: commerce 2.1.13

**Comment by nfourtythree** [comment]
Hi @cholawo 

Here are the two ways to return the plan information entry from a user's subscription or from the subscription plan.

From a user's subscription:

```twig
    {% set information = subscription.plan.getInformation() ?? null %}
    {% if information %}
        <div>
            <h4>{{ 'Plan Information Entry'|t('commerce') }}</h4>
            <ul>
                <li>{{ 'ID'|t }}: {{ information.id }}</li>
                <li>{{ 'Title'|t }}: {{ information.title }}</li>
            </ul>
            <br>
        </div>
    {% endif %}
```

From a subscription plan:
```twig
          {% set information = plan.getInformation() ?? null %}
          {% if information %}
            <div>
              <h4>{{ 'Plan Information Entry'|t('commerce') }}</h4>
              <ul>
                <li>{{ 'ID'|t }}: {{ information.id }}</li>
                <li>{{ 'Title'|t }}: {{ information.title }}</li>
              </ul>
              <br>
            </div>
          {% endif %}
```

I will get the example templates updated to reflect this.

Thanks!
