### ISSUE TITLE
Payment gateway can't be disabled via .env without `allCustomerEnabledGateways` workaround

### ISSUE THREAD

**Issue by wuhhh** [craftcms/commerce#1054]
### Description

Payment gateways disabled via `commerce-gateways.php` and `.env` are incorrectly included in the `allCustomerEnabledGateways` property of the `Gateways` class. 

### Steps to reproduce for the dummy gateway

1. Create an .env file with the line `DUMMY_IS_FRONTEND_ENABLED=0`
2. Create `config/commerce-gateways.php` and pull in the variable we set in .env:
```
<?php
return [
  'dummy' => [
    'isFrontendEnabled' => getenv('DUMMY_IS_FRONTEND_ENABLED') === "1" ? true : false,
  ],
];
```
3. Inspect `{{ dump(craft.commerce.gateways.allCustomerEnabledGateways) }}` - the dummy gateway will be present in the array despite its `isFrontendEnabled` property showing false.

### Additional info

- Craft version: 3.3.3
- PHP version: 7.3.10
- Database driver & version: MySQL Ver 14.14 Distrib 5.7.27
- Plugins & versions: Craft Commerce 2.1.13

**Comment by nfourtythree** [comment]
Hey @wuhhh 

Thanks for highlighting this. Have pushed up some code to fix the issue.

This will be included in the `2.2` release
