### ISSUE TITLE
Order Status History message & order/lineitem notes should be visible/open by default

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1061]
### Description

The order status history message is basically not very very useful as it currently stands - you need to hover your mouse over the tiny `i` symbol (if you happen to notice it at all!) to see the message.  This is cumbersome and slow, and error prone - staff miss the notes.

If there is a message there, it should be displayed by default (or at  least the first 80 characters or whatever...)

This is also true for data on lineitems, and order notes...all should be open and visible by default.

**Comment by lukeholder** [comment]
Fixed for 2.2

![image](https://user-images.githubusercontent.com/133571/67258118-f613f500-f443-11e9-9d87-0aaf299afa0f.png)

**Comment by lukeholder** [comment]
Line item notes should be fixed in 3.0 alpha
