### ISSUE TITLE
Move order complete processes to job queue

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1063]
- [x] Email sending should be moved to queue
- [x] Consolidate guest orders to customer should happen at order completion and be moved to queue

Original Request:

> Its rather noticeable that payment in checkout is a bit slow. Sure, there's some verification that needs to happen with payment gateways, but its still noticeable, and in certain circumstances, **very** noticeable. Its a big factor in conversion and UX - we would hate for customers to bail because something takes a while.

> I think one of the big factors here is the emails triggered on the after-checkout event, slowing things down. These, and all other "after payment" events should be fired in a queue job.

**Comment by timeverts** [comment]
Good call! I'd love to see this change too. Particularly in relation to moving the emai sending to the queue, cause if there's some connection issues with the email adaptor endpoint, at least that won't postpone order completion.

**Comment by keyurshah** [comment]
Yes this is crucial.  Anything to make the order completion process finish as quickly as possible. Thanks!

**Comment by engram-design** [comment]
Also refer to tentative PR - https://github.com/craftcms/commerce/pull/1065

**Comment by nfourtythree** [comment]
The major points were completed in 3.0.

**Comment by j-greig** [comment]
Just looking at https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms, why do I have to add/code additional functionality to handle queued tasks - isn't it possible for critical stuff like Commerce orders to be sent on regular basis by default?

**Comment by engram-design** [comment]
@j-greig I guess that's getting into the more core Craft side of things. I think having these processes moved to a queue is far more important than not. We were seeing some extreme performance issues otherwise, which directly leads to loss of sales.

In terms of this being "hands-off", I suppose Craft might need to step in and provide a mechanism for scheduling. Unlike Wordpress et al, there's no in-built cron or similar service, and you're required to hook things up yourself. Even if Commerce provided an endpoint for this sort of thing to be "sent on a regular basis" you'd still be required to setup a cron job on your host.

My original suggestion was to make this configurable via a config setting, but there's no way to opt-out of this.
