### ISSUE TITLE
Duplicate email notifications being sent

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/commerce#1064]
### Description

When completing an order, the email notification we have set up is being fired multiple times. This is a fresh install of Commerce, so no plugins are interacting with it or firing notifications themselves in the background. I receive only two notifications when I do the checkout process (so one 'empty' notification, and then one with the correct order info), but when my colleague does the process I get sent many (see screenshot).

![Screenshot_2019-10-22_at_10 11 40](https://user-images.githubusercontent.com/1694957/67274132-bedf2b80-f4b7-11e9-815b-3165f42737eb.png)

Notification:

![Screenshot_2019-10-22_at_10 12 51](https://user-images.githubusercontent.com/1694957/67274146-c6063980-f4b7-11e9-99c7-db5c4413e7df.png)

Status: 

![Screenshot_2019-10-22_at_10 13 05](https://user-images.githubusercontent.com/1694957/67274163-cdc5de00-f4b7-11e9-9dca-50897a7ffcaf.png)

Completing the checkout process as guest, not logged into Craft admin.

### Additional info

- Craft version: Pro 3.3.6
- PHP version: 7.1.32
- Database driver & version: MySQL 5.6.45
- Plugins & versions: Commerce 2.1.13, Stripe for Commerce 2.1.2

**Comment by lukeholder** [comment]
Which gateway are you using? @joshua-martin

**Comment by joshua-martin** [comment]
Stripe, using Stripe Payment Intents option

**Comment by joshua-martin** [comment]
@lukeholder It's sending the empty email when I'm updating the cart on the cart page.

**Comment by joshua-martin** [comment]
Dear oh dear, do excuse me mate I had this tucked away on my cart template as I was debugging the email that gets sent when an order is made..

```
{% set order = craft.commerce.orders.getOrderById(8393) %}
{% set orderHistory = order.getHistories()|first %}
{% do craft.commerce.emails.sendEmail(email,order,orderHistory) %}
```

Which I forgot to remove, hence the duplicate emails.
