### ISSUE TITLE
Shipping Zones allow rules by zip/postcode

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce#1066]
It would be great if shipping zones could be set up so you could include or exclude a zip/postcode.

In the UK, most delivery services do not use states/counties for calculating shipping.
Most use postcode areas, for example, postcodes starting in `ZE` may have a higher shipping rate than those starting in `BA`. 

I can't see any way of setting these up currently.

**Comment by andrewhawkes** [comment]
Ignore me, looks like this may cover it https://github.com/craftcms/commerce/issues/204

**Comment by nfourtythree** [comment]
Hey @andrewhawkes 

As you spotted this is coming in `2.2`.

**Comment by andrewhawkes** [comment]
@nfourtythree I had searched in issues prior, but obviously didn't look hard enough!
It will be super useful for a project I'm working on. Is there a rough ETA for 2.2?

**Comment by andrewhawkes** [comment]
This is now live and seems to be working as hoped :)

![Annotation 2019-10-25 161414](https://user-images.githubusercontent.com/4975742/67583028-af274780-f742-11e9-9da1-510474a8ad07.jpg)
