### ISSUE TITLE
Can't upgrade from Lite to Pro

### ISSUE THREAD

**Issue by icreatestuff** [craftcms/commerce#1067]
### Description
We purchased a 'Lite' license and now need access to some of the features within the 'Pro' license. When we click to view the commerce plugin in the plugin store we can see that the 'Pro' license has been reduced by $199 (the cost of Lite) to $800. There's an option to 'Trial' Pro, but no option to actually buy it. 

When we click 'Trial' we then just get a red licensing issue warning at the top of the admin panel pages indicating we're using pro but only have a Lite licence, but with no means to pay to update.
On the /settings/plugins page there's a red button labelled 'switch' but all this seems to do is revert us back to using the 'Lite' version again.

Please take my money!
Thanks

- Craft version: 3.3.1.2
- PHP version: 7.2.20
- Plugins & versions: 2.1.13

**Comment by angrybrad** [comment]
What's the domain you're attempting to do this from? Do you have `allowAdminChanges` set to `false` on this install?

**Comment by icreatestuff** [comment]
Hi Brad it's https://yoyopop.com and we have `'allowAdminChanges' => true` set.

Thanks

**Comment by angrybrad** [comment]
Huh... any chance we could get some Craft CP and (s)FTP/SSH access to poke around a bit?  If so, can you send them over to support@craftcm.scom?

**Comment by icreatestuff** [comment]
Sure thing I've sent them to the support email.

**Comment by angrybrad** [comment]
Solved by setting the `allowUpdates`config setting to `true`.
