### ISSUE TITLE
Creating address via `/actions/commerce/customer-addresses/save` always pushes to billing and shipping

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1069]
Not sure if this is required functionality, or supposed to happen, but If I submit a request to this controller, it'll set _both_ the billing and shipping address for the customer. Is this correct?

In our instance, customers want to be able to control their billing and shipping addresses independently. The customers set their shipping address first (during cart), then much later set their billing address. Due to this behaviour, the shipping address is pushed on to the billing address, which we don't want.

Pretty much these lines -https://github.com/craftcms/commerce/blob/develop/src/controllers/CustomerAddressesController.php#L103-L111 assume that if one of the addresses isn't set, push it onto that.

Expected behaviour? I would've though the `billingAddressSameAsShipping`/`shippingAddressSameAsBilling` or `autoSetNewCartAddresses` config settings might have been in use here.

**Comment by nfourtythree** [comment]
Have pushed a fix for this that will be included in `3.0`.
