### ISSUE TITLE
zipCode Condition Formula breaks if left empty

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/commerce#1073]
### Description
The new `zipCodeConditionFormula` feature for both shipping and tax doesn't work when no condition is defined as the function that calls this expects a `string`.

### Steps to reproduce

1. Update to version Commerce 2.2
2. add a product to the cart
3. an error will occur if no zip code condition is set for both shipping and tax.

### Additional info

- Craft version: 3.3.13 + Commerce 2.2.1
- PHP version: 7.3

**Comment by lukeholder** [comment]
Thanks, just released 2.2.2
