### ISSUE TITLE
Calling unknown method: craft\commerce\elements\Order::getTotalShipping()

### ISSUE THREAD

**Issue by PopaWeb** [craftcms/commerce#1079]
### Description
Everything worked find in Commerce 2.1.13 before the update.

Calling unknown method: craft\commerce\elements\Order::getTotalShipping()
1. in /Users/me/Sites/mySite/vendor/yiisoft/yii2/base/Component.php
public function __call($name, $params)
    {
        if (strncmp($name, 'isFieldEmpty:', 13) === 0) {
            return $this->isFieldEmpty(substr($name, 13));
        }
 
        return parent::__call($name, $params);
    }

Since i've updated from Commerce 2.1.13 to 2.2.3, i got this error everywhere that Commerce want to get the elements\Order. Front end and in the CP all invoices and in users that have invoices.

### Steps to reproduce

1. Products already entered and have invoices in Commerce 2.1.13
2. Update to Commerce 2.2.3

### Additional info

- Craft version: Pro 3.3.13
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.26
- Plugins & versions:
Commerce 2.2.3
CP Field Inspect 1.0.7
Control Panel CSS 2.2.0
Express Forms [Lite] 1.0.4
Image Resizer 2.0.6
Importable 1.0.1
Navigation 1.1.13
PayPal for Craft Commerce 2.1.0.1
Redactor 2.4.0
Retcon 2.0.12
Stretch 1.0.5
Stripe for Craft Commerce 2.2.0
Super Table 2.3.0
Wordsmith 3.1.1

**Comment by nfourtythree** [comment]
Hi

This is fixed in the `2.2.4` release which is now available.

Fix commit: 10bf3c2851028168939af25f33cbe6c6f79e9e19
