### ISSUE TITLE
OrderStatus query fails with Project Config enabled

### ISSUE THREAD

**Issue by abryrath** [craftcms/commerce#1082]
### Description

The src/helpers/ProjectConfigData.php class erroneously adds the 'isArchived' column in a where clause for OrderStatus.
```php
        $statusRows = (new Query())
            ->select([
                'id',
                'uid',
                'name',
                'handle',
                'color',
                'sortOrder',
                'default',
            ])
            ->where(['isArchived' => false])
            ->indexBy('id')
            ->orderBy('sortOrder')
            ->from([Table::ORDERSTATUSES])
            ->all();
```

The `isArchived` column was removed in migration `m191007_184911_orderStatus_from_archived_to_deleted`:
```php
public function safeUp()
    {
        $this->renameColumn('{{%commerce_orderstatuses}}', 'dateArchived', 'dateDeleted');
        $this->dropColumn('{{%commerce_orderstatuses}}', 'isArchived');
    }
```

Additionally, it seems that the `dateDeleted` column is being populated, even if the OrderStatus has not been deleted. Because the `dateDeleted` is populated erroneously, I don't see any way to determine which OrderStatus records are valid.

```
[yii\db\Exception] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'isArchived' in 'where clause'
The SQL being executed was: SELECT `id`, `uid`, `name`, `handle`, `color`, `sortOrder`, `default`
FROM `commerce_orderstatuses`
WHERE `isArchived`=FALSE
ORDER BY `sortOrder`
```

### Steps to reproduce

1. Enable Project Config
2. Enable Craft Commerce 2.2.5

### Additional info

- Craft version: 3.3.1
- PHP version: 7.3.10
- Database driver & version: MariaDB 15.1 (macOS 10.15 Catalina)
- Plugins & versions: Commerce 2.2.5

**Comment by lukeholder** [comment]
Fixed in #1083
