### ISSUE TITLE
estimatedShippingAddress not returned when using `commerce/cart/update-cart` (JSON)

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce#1084]
### Description
I'm using the recently added shipping estimator functionality added in 2.2.
When updating the `estimatedShippingAddress` it all works as expected and you are returned shipping methods.

I am doing this over AJAX but the value of `estimatedShippingAddress` is not returned in the cart JSON response. It would be very useful to have this as it would be good to show to the user what the shipping methods are based on.

### Additional info

- Craft version: 3.3.13
- Plugins & versions: Commerce 2.2.5

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.

**Comment by andrewhawkes** [comment]
@lukeholder cheers for the speedy fix!
