### ISSUE TITLE
Revenue Graph Issues

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#1090]
### Description
I love the revenue graph but it's a little goofy. 

Right now, it looks like it's only view specific (which I would expect, for example NEW or Shipped) and for the date(s) specified.

In additional, the total revenue is always off in some spots, for example:

![Screen Shot 2019-10-29 at 1 33 30 PM](https://user-images.githubusercontent.com/3707869/67798022-cd49bc00-fa50-11e9-8a9f-a00ee023597b.png)

There's 3 NEW orders today, yet the graph is only showing me $239. 

If you also  filter by a search, I would expect that search to also affect the revenue graph too. That would allow us to see how much a customer is worth (eg when they call in), especially in the all orders view.

### Additional info

- Craft version: 3.3.7 /
- PHP version: 7+
- Plugins & versions: Commerce 2.1.13

**Comment by lukeholder** [comment]
See #42

**Comment by lukeholder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reporting Stats](https://trello.com/c/q0q7qadb/4-reporting-stats)
