### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by nitech** [craftcms/commerce#1092]
I need to be able to CRUD products in Craft Commerce via an API. Either REST or GraphQL. Are there any plans for implementing this? 

I see Craft CMS has an issue https://github.com/craftcms/cms/issues/4835 at the 4.0 milestone. I hope that also includes mutations on Craft Commerce.

**Comment by lukeholder** [comment]
Yes, plans to have support for GraphQL in Commerce in 3.0 this year - mutation support coming to the GraphQL API after that.

**Comment by lukeholder** [comment]
- [ ] Products
- [ ] Variants
- [ ] Orders

**Comment by nitech** [comment]
Great work guys. So if I understand this correctly, Craft Commerce 3.0 has GraphQL read-only support for all Commerce-entities? 

If then, do you have any plans for when mutations will come? 

Keep up the good work!

**Comment by lukeholder** [comment]
@nitech Read only support for products. Will extend that to variants and orders very soon.

**Comment by timkelty** [comment]
@lukeholder any update on variants/orders?

**Comment by lukeholder** [comment]
@timkelty Variant support coming in 3.1, orders after that.

**Comment by dnplkndll** [comment]
we need to know how to load the products and update the order status. Was hoping that the mutation support would be possible to add the product/variants and update the orders from the erp. 
Is this in the works?

**Comment by lukeholder** [comment]
Mutations just landed in craft core in 3.5 last week. Will first add mutation support for Products and Variants.

Then when Craft's core GraphQL supports gets per-session/user permissions we will look to add Order support.

**Comment by oadslug** [comment]
+1 for GraphQL support for orders. Would love to try and integrate this with clients accounting system to pull received orders, update order status. Our current system is a bit clumsy.

**Comment by tomduncalf** [comment]
Is there an expected timeline on Products mutations? I'd love to be able to use Craft for an upcoming project but need some way to automate managing products. There's no REST API is there?

**Comment by ohbiko** [comment]
That's a really nice feature!

2 questions:

- how to we query Commerce products?  Any examples/documentation online?
- when can we expect CUD for products at least?
