### ISSUE TITLE
Eagerloading assets on a variant with a limit doesn't work

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce#1094]
### Description
When eager loading with a limit it doesn't work on variant fields. I have confirmed that assets are on both an multiple variants:

```
# This produces an empty array of sliderImageSets (assets)
        Craft::$app->getElements()->eagerLoadElements(
            Variant::class,
            $variants,
            [
                ['sliderImageSets', ['limit' => 2]],
                'featuredImage'
            ]
        );
```

```
            # This produces an array of 2 sliderImageSets (assets)
            Craft::$app->getElements()->eagerLoadElements(
                Product::class,
                [$variant->product],
                [
                    'brand',
                    'featuredImage',
                    ['sliderImageSets', ['limit' => 2]],
                ]
            );
```

### Steps to reproduce

1. Create a product with variants that share an asset field. By share I just mean are related to the same asset field.
2. Add assets to both fields
3. Try to eager load (with a limit) that asset field on the variant
4. You should notice it returning an array of 0 elements when it should be the limit you set

### Additional info

- Craft version: 3.2
- PHP version: 7.3
- Database driver & version: Mysql 5.7
- Plugins & versions: Commerce 2.1

**Comment by lukeholder** [comment]
As of Craft 3.3.1 this should be possible. Please upgrade and try again.

Thanks.
