### ISSUE TITLE
cart/update-cart is no longer work in Craft@3.3.14

### ISSUE THREAD

**Issue by max8hine** [craftcms/commerce#1099]
### Description
The action of `/commerce/cart/update-cart` via Ajax is no longer work in **craftcms/cms: "3.3.14**,, even with the latest CraftCommerce

Working in **craftcms/cms: "3.3.7**

### Steps to reproduce

```
await axios.post("", {
	action: "/commerce/cart/update-cart",
    [csrfName]: csrfToken,
    purchasables: {}
})

// Before updated CraftCMS, Ajax returns cart object
// After updated CtaftCMS, Ajax returns the html of requesting page.
// Both response status code is 200
```

### Additional info

- Craft version: 3.3.14
- PHP version: 7.0.31
- Database driver & version: MySql
- Plugins & versions:
  *  "craftcms/commerce": "2.2.7",

**Comment by max8hine** [comment]
Updates:

I am using [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData) API to mimic the actual form submit in Ajax and it works.

But, **AxiosJs** by default, serialize JavaScript objects to `JSON` which is not work in new CraftCMS version.

I am happy to close it and it is not related to the CraftCMS/Commerce.
Also, is the bug for CraftCMS/guest-entries too

**Comment by nfourtythree** [comment]
Hi @max8hine 

How you tried setting the  `x-www-form-urlencoded` header?

For example:

```js
headers: {
	'Content-Type': 'application/x-www-form-urlencoded'
}
```

**Comment by max8hine** [comment]
Hi @nfourtythree,
I haven't found time to try to add headers in Ajax call, but It makes sense to me and will give it a try this week and get back on this issue.

Thanks for the idea, it's kind of just right on the point.

**Comment by lukeholder** [comment]
Please let us know if you have any issues. Closing for now.

**Comment by max8hine** [comment]
Updates here for others:

set `application/x-www-form-urlencoded` header work for me.
