### ISSUE TITLE
Products can no longer be sorted in the CP by "Promotable".

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce#1101]
Description
The products list in the control panel can no longer be sorted by "Promotable" or "Date Updated".
Promotable was working for me a couple of weeks ago. I swear "Date Updated" was an option too but not 100% sure. 

Additional info
Craft version: 3.3.13
Plugins & versions: Commerce 2.2.5

**Comment by nfourtythree** [comment]
Hi @andrewhawkes 

It was likely that you were able to do this previously how it was an unintended side effect of a bug that was causing errors. That [bug was fixed](https://github.com/craftcms/commerce/commit/8082a58cdd9c72ad9411659d87543f3f1d5aeea8), however, I have now made this possible: 0cc55a0.

This will be included in the next release.

Thanks!

**Comment by andrewhawkes** [comment]
@nfourtythree that's great thanks. I think in general it's just good to have option to sort by whatever is available in the list if it's possible logically.
