### ISSUE TITLE
Ability to duplicate products

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1107]
Aware that you can use "Save as a new product", but it'd be great to be able to quickly duplicate products, in much the same way entries have this functionality.

See https://github.com/craftcms/cms/issues/923

cc @gojira32

**Comment by bossanova808** [comment]
Agree and have just noted on the 'parent' issue some thoughts in general on the UI of 'save as new entry' which is probably the most error prone operation in all of craft, as far as I can tell from our sample of editors anyway!

**Comment by brandonkelly** [comment]
This was added in Commerce 3.1.4.
