### ISSUE TITLE
Customer Address not appearing on Customer Info tab

### ISSUE THREAD

**Issue by hegrobler** [craftcms/commerce#1110]
### Description
I'm using the user registration form to create a new user account.
The user is auto logged in & asked to fill out their address details. 
I'm using the customer address form ( which posts to commerce/customer-addresses/save ) to capture the Address details.
I can see the Address details on the users profile on the Front end but the address does not appear on the Customer Info tab in the Back End.

### Steps to reproduce

1. Register user via user registration form
2. Complete customer address form
3. Check Customer Info tab in backend

### Additional info

- Craft version: 3.3.14
- PHP version:7.2
- Database driver & version:MySQL 5.5.5
- Plugins & versions:
Calendar	2.0.25
Commerce Admin Orders	2.5.4
Craft Commerce	2.2.7
Feed Me	4.1.2
Imager	v2.3.0
Redactor	2.4.0
Site Switcher	2.1.0
Snaptcha	2.2.0
Sprout Email	4.0.5
Sprout Forms	3.5.1
Video Embedder	1.1.4

**Comment by jmauzyk** [comment]
Do you by any chance still have the Customer Info field enabled for users? I noticed similar behavior where addresses were not showing, but once I removed the Customer Info field I was able to see addresses in the Customer Info tab.

**Comment by lukeholder** [comment]
Please remove the customer info field as the tab now replaces this feature.
