### ISSUE TITLE
promotionCategories group is set to id, not uuid (upgrading from craft 2)

### ISSUE THREAD

**Issue by timkelty** [craftcms/commerce#1112]
I'm assuming this is because I am upgrading from craft 2, but after all the migrations, the `promotionCategories` that Commerce creates has an invalid ID source (`group:42`), instead of the UUID.

**Comment by lukeholder** [comment]
So was your update successful? But you are getting the error on the category element listing screen when clicking the new promotionCategories source?

**Comment by timkelty** [comment]
Other than that, the update was successful.

I'm not even sure I got an error, I just happened to notice it in `project.yaml`.

To double-checke that it was incorrect, went to the field setting screen, and source selection wasn't set (or defaulting to the first category in the list).

I changed it to use the uuid of the new group and it updated successfully.

**Comment by lukeholder** [comment]
Fixed in b8ac65ab9ff86d
