### ISSUE TITLE
Available for purchase doesn't save anymore

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1113]
Can't seem to get the available to purchase tickbox to save? Seems to be because of https://github.com/craftcms/commerce/blob/develop/src/elements/db/ProductQuery.php#L519-L520 as uncommenting this works as expected.

The checkbox is always checked, even if the value in the products db table is zero. This is seemingly a recent thing though?

Craft Commerce 2.2.7

**Comment by nfourtythree** [comment]
@engram-design this is a strange one as this seems to work for me?

See video: https://x.n43.me/yAu4Jd1w

**Comment by engram-design** [comment]
@nfourtythree How is the value being populated on the element if that's commented out though? Unless I'm missing something.

See video (sorry its cropped) - https://d.pr/free/v/O5Kilu

**Comment by engram-design** [comment]
Aha, I see the issue. I'm using `dev-develop as 2.2.99` and it doesn't like that in the version_compare function.

**Comment by nfourtythree** [comment]
Yea will make a note to tidy up for `3.0`.
