### ISSUE TITLE
Fix Attempted Payments query speed

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1115]
When viewing the Attempted Payments for orders on a production environment (x4 CPU, 8GB RAM), Craft basically crashes, making the front-end hang and become unavailable.

All other sources on the sidebar are fine, including active/inactive carts.

I feel like there's a query join to grab all the transactions related to the order, that's probably unavoidable, but there must be something pretty wrong going on here to make things take _that_ long?

Available on Discord at any time to provide access or additional info.

Commerce 2.2.7
PHP 7.1.32
MySQL 5.5.5
Craft Pro 3.3.14

**Comment by lukeholder** [comment]
This should be fixed with the recent release of 3.2
