### ISSUE TITLE
No order Adjustment exists with the ID “X”

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1116]
### Description
We're getting this error on a multi-site when paying with PayPal, on the non-primary site. We are using a custom integration to make the user land on a "review" page rather than capturing immediately with PayPal.

On this review step, we're not doing anything special other than having a form to the `payments/complete-payment` controller.

```
<form method="POST">
<input type="hidden" name="action" value="commerce/payments/complete-payment">
<input type="hidden" name="redirect" value="d9a7c5b8038763bcbd60af05439d5c9faebac1335a2b7abda6bc1e04271a82d9/shop/success">
<input type="hidden" name="CRAFT_CSRF_TOKEN" value="NDXa-jiQJEH_clvSDdXGm1LEy9KhOkwOnOPIfPvW5FWCH0zBhVegsG1Tj6wM_EomyyE65TWQod4em_iH7UIFbeWI8Tq-l5I382kHlbY15IM=">
<input type="hidden" name="commerceTransactionId" value="67723">
<input type="hidden" name="commerceTransactionHash" value="c384cfb0da808950620b7324ce3a4013">
<input type="submit" value="Pay Securely Now">
</form>
```

However, when we trigger this, the customer gets the above error (No order Adjustment exists with the ID “X”). We have two sites, AU and NZ. This occurs on the NZ site only. We have a Tax adjuster setup for "GST included" that has a Tax Zone set to "Everywhere". This is because the tax is included in the taxable subject, despite not charging GST for NZ (yet). 

If I completely delete the Tax Rate from the system, this issue disappears.

This seemed to work pre-2.2 as well, so something might've changed. Any ideas on where to start debugging? 

The only thing I can notice is that if I'm on the review page on the NZ site and refresh the page, the `commerce_orderadjustments` keeps adding (and removing) new tax adjustments each time I refresh the page, despite not touching the cart's contents or updating the cart. I can confirm this doesn't happen on the AU site.

For example, there's a row in `commerce_orderadjustments` with an ID 359097 for the order in question. As I refresh the page, I madly refresh the database table, and can see a new row is created, and subsequently deleted for 359098, 359099, and finally stopped with 359100. I would say this mass-regeneration of order adjustments is the cause of the error?

### Additional info

- Craft version: 3.3
- PHP version: 7.1.32
- Plugins & versions: Commerce 2.2.7

**Comment by engram-design** [comment]
Looks to be related to how I'm handling currencies, where I'm forcing `order->currency` to be `NZD`, instead of just using `paymentCurrency`. This force-changing it causing the order to re-calculate at the review step, because its detecting the order currency changing.

**Comment by yoannisj** [comment]
After updating Craft from v3.5.19 to v3.6.9 and Craft Commerce from v3.2.14 to v3.2.17, I am seeing the same error when submitting a form to `commerce/payments/pay` without setting the order's currency and with any of the following gateways:
- [Stripe](https://plugins.craftcms.com/commerce-stripe) Payment Intents gateway (v2.3.2.1)
- [Paypal Checkout](https://github.com/craftcms/commerce-paypal-checkout) Paypal Checkout (v1.2.0)
- Manual Gateway (Authorize Only, Capture manually)

Every time I re-submit the form, the ID in the error message is bumped up a few numbers, which I assume indicates that Commerce is trying to (re-)save a new OrderAdjustment in that request.

Here is the full stack-trace (with Manual payment gateway):

```
2021-03-08 18:40:24 [-][-][3qlnbf3b4t1troja675bbalmjv][error][yii\base\Exception] yii\base\Exception: No order Adjustment exists with the ID “319846” in /var/www/html/vendor/craftcms/commerce/src/services/OrderAdjustments.php:178
Stack trace:
#0 /var/www/html/vendor/craftcms/commerce/src/elements/Order.php(3104): craft\commerce\services\OrderAdjustments->saveOrderAdjustment()
#1 /var/www/html/vendor/craftcms/commerce/src/elements/Order.php(1961): craft\commerce\elements\Order->_saveAdjustments()
#2 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2482): craft\commerce\elements\Order->afterSave()
#3 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal()
#4 /var/www/html/vendor/craftcms/commerce/src/elements/Order.php(1456): craft\services\Elements->saveElement()
#5 /var/www/html/vendor/craftcms/commerce/src/services/Payments.php(256): craft\commerce\elements\Order->updateOrderPaidInformation()
#6 /var/www/html/vendor/craftcms/commerce/src/controllers/PaymentsController.php(410): craft\commerce\services\Payments->processPayment()
#7 [internal function]: craft\commerce\controllers\PaymentsController->actionPay()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#10 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#16 /var/www/html/web/index.php(27): yii\base\Application->run()
#17 {main}
2021-03-08 18:40:23 [-][-][3qlnbf3b4t1troja675bbalmjv][info][application] $_GET = []
$_POST = [
    'action' => 'commerce/payments/pay'
    'redirect' => '96eab38797a9fbb38dfef99557103419d2c45b35174f08a5f6e5866d4c0f352dhttps://localhost/en/checkout/confirmation?number=ba20c15fa12c68345ceee9a400b8981a'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'gatewayId' => '2'
    'orderEmail' => 'mail@yoannis.com'
    'cancelUrl' => '67823c691970f71ea29b62cec5ae5e8b37d80fba62ae975772c112b07c1a5d76https://localhost/en/checkout/payment'
]
```

Craft version: 3.6.9
Craft Commerce version: 3.2.17
