### ISSUE TITLE
Don't send Discount Name to gateways

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1117]
At the moment, when sending orders (with PayPal, but probably others - anything using https://github.com/craftcms/commerce-omnipay), if the order includes a discount, it uses both the name and description in the order details.

This is fine, but the field instructions in the CP clearly state that the name is what its referred to the CP, which is kind of inferring that its not shown to customers. As such, our clients are using this to store non-customer facing info, but its being shown regardless.

See https://d.pr/free/i/kaA1XE

Note I've tweaked the instruction text on the second field for clarity for this client.

Unsure if it a change in https://github.com/craftcms/commerce-omnipay/blob/master/src/base/Gateway.php#L704-L705 or clarifying the field instructions?

**Comment by gojira32** [comment]
@lukeholder Any update on this?

**Comment by lukeholder** [comment]
https://linear.app/craftcms/issue/COM-35/fix-field-descriptions-on-all-namedescription-fields-for-discounts

**Comment by lukeholder** [comment]
Fixed in https://github.com/craftcms/commerce-omnipay/commit/68cda50d852f9cdd99d3d24af8152edcd504556e
