### ISSUE TITLE
Duplicating shipping cost

### ISSUE THREAD

**Issue by JustJarethB** [craftcms/commerce#1126]
### Description
We have a shipping logic, cart under £5.00 is free shipping, over is £2.50. When adding 2 single quantity items under the price it sets the shipping price to £5.00. Calling update cart returns price to expected (but this is not good for the user).

From what I see, this is not the same functionality as our `2.1.10` old setup 

### Steps to reproduce

1. Free shipping rule:
- Max Value: 4.99
- All categories "Allow"
2. Flat rate rule:
- Min Value: 5
- All categories "Allow"
3. Create 2 products price `4`
4. Add one item, note shipping of `0`
5. Add other item, note shipping of `5`
6. Update cart, note shipping of `2.5`

### Additional info

- Craft version: Craft Pro 3.3.15
- PHP version: 7.3.10
- Database driver & version: MySQL 5.6.44
- Commerce version: 2.2.7

**Comment by nfourtythree** [comment]
Hi @JustJarethB 

I have just tried to replicate this issue locally and using the example templates and everything seems to work as expected.

Here is what I had.

- One shipping method that has two rules
	- First rule: Max value 14.99, Price: 5.00
	- Second rule: Min Value 15.00, Price: 2.50
- Product one, Price: 10.00
- Product two, Price: 10.00
- Added Product one to cart
- Shipping shows as 5.00
- Added Product Two to cart
- Shipping shows as 2.50

Could you try your shipping method set-up on a fresh install of Commerce and using the example templates and let me know if you are still having an issue.

Thanks!

**Comment by lukeholder** [comment]
Closing this as we have had no response. Please send more info and we can look to re-open the ticket.
