### ISSUE TITLE
Add LineItem dateUpdated attribute

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1132]
### Description
Could you please add the `dateUpdated` attribute to the `LineItem` model? Otherwise I need to fetch it again for every one. I need that attribute for one of my endpoints to check an `if-unmodified-since` header correctly.

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#fb2e4758eb492f69705f915acb097395101e45bc as 3.1.12",
  "...": "..."
}
```

Then run `composer update`.
