### ISSUE TITLE
Changing country names in CP aren't reflected in Project Config

### ISSUE THREAD

**Issue by zackspear** [craftcms/commerce#1136]
### Description

Changes in the Craft Commerce Store Settings for Countries (`/admin/commerce/store-settings/countries`) aren't reflected in project config. Not sure if this is by design or not.

We recently ran into an issue where [certain country names weren't working with our payment gateway plugin (Braintree)](https://github.com/KuriousAgency/commerce-braintree/issues/19). This prompted us to find the differences in countries our payment gateway was expecting and what Craft Commerce had set as the default.

Upon updating a few locally I checked to see if the project.yaml file was updating and it wasn't. Meaning I'll need to make the country name changes in multiple envs. Not a huge deal, but having this as part of the project config would be great.

Thanks in advance.

### Steps to reproduce

1. Go to `/admin/commerce/store-settings/countries`
2. Go into a specific country
3. run `git status` within project directory to see that `config/project.yaml` was not updated

### Additional info

- Craft version: Craft Pro 3.3.15
- PHP version: 7.3.4
- Database driver & version: MySQL 5.5.5

**Comment by lukeholder** [comment]
Leaving in the database for now

**Comment by lukeholder** [comment]
They are related to tax zones, which can be edited by a store admin.
