### ISSUE TITLE
Update the Edit Product page to support drafts and new draft-based live preview

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1137]
That's basically it, please add different preview targets as they exist for sections for products as well, so they can be previewed in headless mode.

**Comment by lukeholder** [comment]
Need to switch over the to the new element page for this to happen.

**Comment by RitterKnightCreative** [comment]
@lukeholder looks like this didn't make it to the 3.1 milestone, perhaps 3.2?

**Comment by RitterKnightCreative** [comment]
BTW: this was marked as a duplicate as early as #291 as well.

**Comment by jsunsawyer** [comment]
We just ran into a weird issue where having revision history would have been super beneficial to troubleshooting things. Chiming in in hopes that this issue gets some love. :)

Also, looks like anything related to product revisions is marked as a duplicate, eventually pointing to this issue, even though it doesn't specifically mention revisions.

**Comment by huelabs** [comment]
Agree with @jsunsawyer. We have thousands of products and this is such a pain point for us. Who edited a product and what did they change? It's anyone's guess without revision history.

**Comment by CMeldgaard** [comment]
Is there a timeline for this feature ?
