### ISSUE TITLE
Shipping zones Zip Code Condition: Data too long

### ISSUE THREAD

**Issue by rbrv** [craftcms/commerce#1138]
### Description
The length of the Zip Code Condition Formula is limited to `varchar(255)`, triggering an SQL error when adding a longer string:

```
Database Exception – yii\db\Exception

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'zipCodeConditionFormula' at row 1
```

### Workaround
Manually alter the column type of `commerce_shippingzones.zipCodeConditionFormula` to `TEXT`

### Additional info

- Craft version: 3.3
- Craft Commerce: 2.2.7
- Database driver & version: MySQL 5.5.5

**Comment by nfourtythree** [comment]
Hey @rbrv 

Have pushed an update for this it will be included in the next release.

Thanks.
