### ISSUE TITLE
Promotions - discounts "Remove all shipping costs from the order" option ignores user group settings

### ISSUE THREAD

**Issue by MichaelWheldon** [craftcms/commerce#1144]
### Description

There seems to be a bug in Promotions - discounts where the "Remove all shipping costs from the order" option ignores any user groups setup for the discount, and thus applies free shipping site wide.

### Steps to reproduce

1. Create a new discount
2. Make no changes to products or prices
3. Select a user group to apply this discount to
4. Check "Remove all shipping costs from the order" situated towards the bottom inside the last tab

If we're using this checkbox incorrectly, we'd love to know how to apply free shipping to specific user groups, if that is supported at all out of the box, or if we need to create something custom.

### Additional info

- using Element API
- Craft version: 3.3.15
- PHP version: 7.0
- Commerce version: 2.2.8

**Comment by nfourtythree** [comment]
Hey @MichaelWheldon 

Thank you for bringing this to our attention. We will look into it and get back to you.

Thanks!

**Comment by brettburwell** [comment]
Hi there @nfourtythree. I believe I bumped into a similar issue, but in my case I wasn't using user groups in conjunction with the _Remove all shipping costs from the order_ option. 

Instead, I was trying to apply free shipping if/when a minimum _Purchase Total_ condition was set. But regardless of the cart totals I was testing free shipping was always being applied. 

It looks like #1155 may address this situation too, but I wanted to double check just to be sure. Any info you can pass along would be much appreciated! 

**Steps to reproduce**
1. Create a new discount
2. Under _Conditions_ set _Purchase Total_ to 50
3. Under _Amounts_ select _Remove all shipping costs from the order_

**Additional info**
1. Craft version: 3.3.16.1
2. PHP version: 7.2.20
3. Commerce version: 2.2.8

**Comment by nfourtythree** [comment]
Hi @brettburwell 

Yes this should sort the issue you mentioned as well.

Thanks.

**Comment by brettburwell** [comment]
Awesome. Thanks for confirming @nfourtythree!

**Comment by engram-design** [comment]
Just noticed this too, glad there's a fix on the way

**Comment by oddnavy** [comment]
We still seem to be seeing this issue on Craft Commerce 2.2.13.

A free shipping discount is applied to all users and seems to ignore minimum purchase total

Discount configuration:
![image](https://user-images.githubusercontent.com/1872727/71610279-bb68ce80-2be3-11ea-968d-f3477ef4211c.png)
![image](https://user-images.githubusercontent.com/1872727/71610311-fec33d00-2be3-11ea-8324-5f768dc8e424.png)

**Comment by moldedjelly** [comment]
@oddnavy I've just come accross this issue too. I have the exact same config as your screenshot there - members who purchase above $100 should receive free shipping yet it appears to ignore the Purchase Total field value in the condtions.
