### ISSUE TITLE
Address data "div" in "Customer Info" tab stays hidden.

### ISSUE THREAD

**Issue by johnwbaxter** [craftcms/commerce#1146]
### Description

On a users account in the CP, if you look at the "Customer Info" tab to see a users address, the address html has the class "hidden" so although the data is there, it never shows. I'm guessing something is meant to fire that removes this class and it just isn't doing it for me? If i unhide that div, in the inspector, I can see what I would expect to see if there wasn't an issue.

https://github.com/craftcms/commerce/blob/develop/src/templates/customers/_editUserTab.html#L100

### Steps to reproduce

1. User registers adding address
2. Look at "Customer info" tab to view address

### Additional info

- Craft version: 3.3.16.1
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions: Craft Commerce 2.2.8

**Comment by nfourtythree** [comment]
Hi @johnwbaxter 

I have just had a look at this and everything seems to be working correctly at this end.

Can you check to see if you have removed any custom Customer field types that might have been added to the user field layout?

If there are any could you try removing them and seeing if this issue persists?

Thanks.

**Comment by johnwbaxter** [comment]
Ahhhhhhh, I had the customer info fieldtype on there in another tab, they must have been clashing.

Thanks Nathan!!
