### ISSUE TITLE
FR: configuration setting for offsite query paramater "commerceTransactionHash"

### ISSUE THREAD

**Issue by moldedjelly** [craftcms/commerce#1150]
### Description
In the offsite gateway I'm working with, the payment success URL is hardcoded on the payment gateway side so we have it set to "[HOST]/actions/commerce/payments/complete-payment" - note the missing param "commerceTransactionHash". It would be great to have Craft Commerce read a different query string variable other than "commerceTransactionHash". This payment gateway redirects back to the payment complete URL with a certain set of variables and I can put the transaction hash in one of them. Could a configuration setting be introduced to specify a different parameter?

**Comment by nfourtythree** [comment]
Hi @moldedjelly 

I think the best thing to do in this instance would be to create your own custom controller that you can have as your success URL.

This controller could extend the payments controller. You could even extend the complete payment action so you can manipulate the `commerceTransactionHash` get variable.

Or alternatively, you could take the code from the complete payment action and call it yourself.

At this moment in time, I don't think the feature you requested will be added into Commerce. However we will definitely keep it in mind.

Hope this helps!

**Comment by moldedjelly** [comment]
OK thanks very much for the suggestion. 
That makes sense.
