### ISSUE TITLE
Addresses on Customer Info tab are present, but visually hidden

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1151]
### Description

The address data is actually present, but there is a class 'hidden' on on the box....looking at the code, it should be getting toggled, but...it's (sometimes?) not.

![image](https://user-images.githubusercontent.com/731309/69691419-275aa180-1123-11ea-9ae4-b280aea95730.png)

If I manually clear the hidden attribute, the address appears.

### Additional info
Commerce 2.2.8
Firefox latest on Win10 64

![image](https://user-images.githubusercontent.com/731309/69691441-3c373500-1123-11ea-8c72-e7d8b89426f8.png)

**Comment by bossanova808** [comment]
Just changing the code like this seems to work:
```
        //this.$addressBox.toggleClass('hidden');
        this.$addressBox.removeClass('hidden');
```

**Comment by nfourtythree** [comment]
Hey @bossanova808 

I believe this will be the same issue as #1146 

Have you removed the Customer Info fieldtype from the customer field layout?

**Comment by bossanova808** [comment]
Hmm, thought I had but looks like I did so in dev, not production, then re-synced my DB after that.  Sorry for the noise (and for not finding the previous issue!).
