### ISSUE TITLE
totalShpping property typo

### ISSUE THREAD

**Issue by nicgordon** [craftcms/commerce#1153]
### Description
Just noticed this looking at the commit history for the last release

https://github.com/craftcms/commerce/blob/1097afff3d4ba7406c7d9182e7c015bd39782987/src/services/Reports.php#L84

I believe `totalShpping` should be `totalShipping`

If I get a chance I'll create a PR soon, in the meantime I thought I'd post this here in case someone else wants to pick it up.

**Comment by nfourtythree** [comment]
Hey @nicgordon 

Thanks for bringing this to our attention. Have pushed a fix for this that should be included in the next release.

Thanks!

**Comment by nicgordon** [comment]
No worries. Thanks for fixing!
