### ISSUE TITLE
Ability to send quotes to customers

### ISSUE THREAD

**Issue by nitech** [craftcms/commerce#1156]
I would like the ability for an admin to create a quote and send it to a customer for review. 

# Scenario
I am talking to a customer on the phone. He wants a price on a specific product/configuration. I add the desired products to the customer's basket, save it as a price offer/quote. I am allowed to adjust prices. I send the quote to the user. The user can access the quote and easily accept or reject it. Craft Commerce can save multiple quotes - and the customer can also create his own lists/quotes and promote them to a shopping cart whenever he wants to purchase whatever is in the list/quote. 

# Possible features
This could be viewed as "Support for lists that can be modified by admin with specific prices/discounts"

Some features could be: 

- Let admin impersonate user (already exists in Craft 3.2) so he can create quotes and lists for user.
- Support multiple list/quotes
- Let user create his own quotes - but labeled as "lists" (wish lists, shopping lists etc)
- Let user add products from lists to shopping cart (one by one, via checkboxes or "add all")
- Let admin give discounts on items. 
    - If customer adds those items to basket, he must not be able to modify their price. 
    - Also user must not be able to increase or decrease quantity of each item (unless this has been specifically granted by admin)
    - If user adds another item of same type already discounted, add as separate line with default price so we don't mix with the discounted items
- Let admin send quote on email with link. 
    - Link leads to view of specified list
    - User can add products in list to cart
- Batch maintenance of products in list
    - "Type Ahead" kind of searching by product name or number
    - Add multiple products by comma separating product numbers (productId,quantity\n)
    - Import list of product numbers and quantities from Excel/CSV
    - Export list as Excel/CSV

**Comment by bossanova808** [comment]
This would be a very useful addition to Commerce for sure....allows for all sorts of promotional possibilities, but also helps with accessibility type issues.

**Comment by keyurshah** [comment]
Is there a chance of this being in commerce 3? Trying to plan if i should write a temporary plugin until then. Thanks

**Comment by nfourtythree** [comment]
Hi All

With the release of `3` and subsequently `3.1` you now have the ability to create and edit carts/orders along with the ability to [pay an outstanding balance on a cart/completed order](https://docs.craftcms.com/commerce/v3/making-payments.html#paying-outstanding-balance-on-a-cart-or-completed-order) or [load a cart into the current session](https://docs.craftcms.com/commerce/v3/loading-a-cart.html).

This gives a good core set of tools to be able to achieve most of the things mentioned above.

There are a couple of things that are not addressed from the list but I will close this issue in favour of creating some more specific issues related to the current state of Commerce.

Thanks for all of the input!
