### ISSUE TITLE
Attempted payments cause PHP error when "Status" column is selected

### ISSUE THREAD

**Issue by sclander** [craftcms/commerce#1160]
### Description

When "Status" is selected for one of the table columns on the "Attempted Payments" dashboard section, Craft throws a flash message with "An unknown error occurred" and none of the attempted payment records get loaded.

Looking at the logs, the issue is here: `Error: Call to a member function getLabelHtml() on null in /home/captioncall/captioncall_craft/vendor/craftcms/commerce/src/elements/Order.php:1916`

Not very experienced with Craft Commerce, but from what I can tell, carts that have not become orders are _supposed_ to have a null status. It seems to me that the `getLabelHtml()` method should be modified to allow null, or that the option for columns that can throw a null value should be removed from the UI.

### Steps to reproduce

1. Submit an order/orders with a failed transaction
2. Add "Status" to the list of displayed columns
3. Reload the tab, you should see the error at the top, and no records should be loaded

### Additional info

- Craft version: 3.3.15
- Commerce version: 2.2.7

**Comment by nfourtythree** [comment]
Hey @sclander 

Thanks for pointing this out. Have pushed a fix and it will be included in the next release.
