### ISSUE TITLE
Best pratice to translate emails and other content for a paid order

### ISSUE THREAD

**Issue by stenvdb** [craftcms/commerce#1164]
I want to translate the mails I send to customers when they've ordered something. My client needs to be able to edit this content in the cp as well. So I have some global sets with where they can fill in content for the emails etc.

When an order is submitted we don't have a siteId (well, [actually we have](https://docs.craftcms.com/commerce/api/v2/craft-commerce-elements-order.html#public-properties) but it always defaults to the default site in my case, is this correct?). We only have the `{{ order.orderLanguage }}` property. 

What I'm doing at the moment to get the proper translated fields in the global set (to use in emails for example) is this:

```
{% set siteId = craft.app.sites.getAllSites()|filter(site => site.language == order.orderLanguage)|first.id|default(1) %}
{{ craft.app.getGlobals().getSetByHandle('mails', siteId).mailOrderComplete }}
```

Is this the best way to do this, or are there some cleaner ways?

**Comment by lukeholder** [comment]
When an email is configured to be sent to "Send to the customer"


![image](https://user-images.githubusercontent.com/133571/74066217-8ce0cf00-49ab-11ea-8d23-7e5560a7a566.png)


it will render the email with the language set to the same language as the order.

If the recipient is to "custom recipients" it will use the current language.

If you want to change what global field value to use you can always look at the language the order was made in with `{{ order.orderLanguage }}`

**Comment by lukeholder** [comment]
Sorry missed you issue about getting the global field by siteId.

> Is this the best way to do this, or are there some cleaner ways?

That is what you would need to do sorry. When we move to multi-store we could look to improve this.

Also I thought there was a `|firstWhere` filter in twig that would help, but it doesn't look like we have one, so you might need to get the first result from your filter since there could be more than one site for a language.

**Comment by stenvdb** [comment]
Gotcha, thanks for getting back to me. Looks a bit dirty currently, but it works :+1:
