### ISSUE TITLE
Mark as complete error

### ISSUE THREAD

**Issue by totov** [craftcms/commerce#1166]
Getting the following error when using `Mark as complete` in Commerce 2:

```
TypeError: DateTime::__construct() expects parameter 1 to be string, object given in /home/gonorth/vendor/craftcms/commerce/src/controllers/OrdersController.php:330
Stack trace:
#0 /home/gonorth/vendor/craftcms/commerce/src/controllers/OrdersController.php(330): DateTime->__construct(Object(DateTime))
#1 [internal function]: craft\commerce\controllers\OrdersController->actionCompleteOrder()
#2 /home/gonorth/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /home/gonorth/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /home/gonorth/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('complete-order', Array)
```

The error references the following line, which does seem to be passing an object (`DateTime $order->dateOrdered`) to the constructor of `DateTime`:

https://github.com/craftcms/commerce/blob/7e45150bd3e0079346e9e07cc1fa58f910096b96/src/controllers/OrdersController.php#L330

Happens when I go through the order process on the front-end and then hit the `Mark as complete` button in the CMS to complete the order.

Seems to be the same issue as https://github.com/craftcms/commerce/pull/1017

**Comment by nfourtythree** [comment]
Hi @totov 

Thanks for bringing this to our attention. I have pushed up a fix for this and it will be included in the next release.

Thanks!
