### ISSUE TITLE
Close transaction via console request

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1169]
### Description
I have an offsite payment gateway that does not respond if the user does not interact with the system, so after I redirect there is no real way to tell if they close the window or don't do anything. If the window is closed for whatever reason I can't really proceed because it is for a booking system that relies on free/limited slots and they should be freed again. They should not be able to open several different transactions too because of certain reasons. 

So my plan is to mark the transaction as closed after a certain amount of time automatically to have no pending/running transactions. 

Now my question is: how can I close a transaction via console request without rewriting everything from scratch?

My goal was to trigger 
```PHP
Plugin::getInstance()->getPayments()->completePayment($transaction, $customError);
```

But that will throw several exceptions due to (in my opinion) insecure usage of components
[Transactions](https://github.com/craftcms/commerce/blob/develop/src/services/Transactions.php#L202)
```php
$user = Craft::$app->getUser()->getIdentity();
```
There is no session so this won't work. I don't want to overwrite the component just for this little line either.

Maybe there is a much easier way to close a transaction that I have not found yet. So that's what it's basically about. Do I have to overwrite your component or how can I do it or would you eventually check if there is a session for it? You could maybe use the orders user in this case and not the current user if there is no session or leave it blank

**Comment by nfourtythree** [comment]
Hi @Anubarak 

I think I follow this. 

Is the goal here to mark the order as complete or to remove the order?

Thanks

**Comment by Anubarak** [comment]
I just want to mark the transcation as failed, so people can retry it.
I changed the way Commerce works by itself a little bit to fit our needs/requirements.

As said it's for a booking system, so you choose your options and click on the "pay" button. When this happens I remove the current cart from the session so users won't be able to change the order anymore while they are in the offsite payment gateway.

The issue  is: when they just close that window the payment gateway does not send a response to us (they said they can't do that) but they have an internal timer of 15 minutes, after that they won't proceed the payment anymore. When there is no response during those 15 minutes I would like to mark the transaction as "failed".

When there is no pending transaction for an order and it's not paid I show an "payment failed, retry" button in the users order history. 

But I can't find a "simple" way to mark the transaction as "failed" without larger modifications of your services or rewriting them during a console request without a valid "CurrentUser" and without a "http Session"

**Comment by Anubarak** [comment]
I know this is just a hint to the correct way but how can I bypass https://github.com/craftcms/commerce/blob/develop/src/services/Transactions.php#L359 without modifying too much.

Of course I could as well write a custom sql statement in this case but I would actually like to trigger all events that would be fired if the payment gateway would had send a response. 

So to keep it simple: there is no easy way to call the function `Plugin::getInstance()->getPayments()->completePayment` in a console request to close a transaction manually.

Seems like I'll write the functionality on my own.

**Comment by lukeholder** [comment]
Closing this for now, please submit a ticket with a cleat feature request or bug report. Thanks.
