### ISSUE TITLE
Allow multiple types of PDF files/templates to be downloaded/printed for orders

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce#1170]
### Description
Many e-commerce systems allow you to download/print different items for orders such as invoices, packing slips and shipping labels.

If there isn't a way to do it now, it would be nice if you could specify a name and a template path for these downloads. It would then be good to have these easily accessible on an order with something like this:

![invoice](https://user-images.githubusercontent.com/4975742/70527727-77366100-1b44-11ea-9b0f-77947c7a5e28.jpg)

It would be really convenient for store owners to have this functionality. Plus it would allow you to make custom documents which can contain whatever the store owners need.

A bonus would be an option to render these templates in a way so they can be printed straight away. 

The current order PDF isn't very well documented at the moment either, so I apologise if something like this is already possible.

**Comment by andrewhawkes** [comment]
Just wondering if this will be considered at all please?

**Comment by lukeholder** [comment]
@andrewhawkes Yes, this will be in the next release of Commerce. Keep an eye on this ticket.

**Comment by andrewhawkes** [comment]
@lukeholder I've noticed in 3.0.11 the UI is now there with a dropdown:

![Annotation 2020-03-03 154449](https://user-images.githubusercontent.com/4975742/75792609-1fd01780-5d66-11ea-841f-c6a717af0d4e.jpg)

I'm just wondering if it's possible to create different PDF types yet?

**Comment by lukeholder** [comment]
This is now possible since 3.2.0
