### ISSUE TITLE
Payments::EVENT_AFTER_PAYMENT_TRANSACTION Event never called

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/commerce#1173]
### Description

I have been trying to attach event code to this event with no success - my code never gets called. When using EVENT_AFTER_PROCESS_PAYMENT it does in fact get called. This is not the exact case I am after though.

Looking thought the code, the event is defined in `craft\commerce\services\Payments` (but cannot find any calls / triggers for this event.

The event is documented here:

https://docs.craftcms.com/commerce/v2/events.html#the-afterpaymenttransaction-event

### Steps to reproduce

1. Attach and event as described in above documentation in module or plugin based code
2. Notice it does not get called.

### Additional info

- Craft version:  3.3.17
- PHP version: 7.2.24
- Database driver & version: N/A
- Commerce (Pro) v 2.2.8

**Comment by rob-baker-ar** [comment]
Discussion in Discord suggested this might be a gateway specific event - if so, needs to be documented as such.

**Comment by lukeholder** [comment]
@rob-baker-ar It gets triggered here:

https://github.com/craftcms/commerce/blob/0f892df31055ebed2ad6653187089ebb14e34d01/src/services/Payments.php#L229-L231

Are you sure you are attaching your event handler correctly?

**Comment by rob-baker-ar** [comment]
That's the `EVENT_AFTER_PROCESS_PAYMENT` event. I use the example of that event working above.

This issue is regarding the `EVENT_AFTER_PAYMENT_TRANSACTION` event.

**Comment by rob-baker-ar** [comment]
Re-open?
