### ISSUE TITLE
perItemDiscount is different depending on user language setting

### ISSUE THREAD

**Issue by stevenvandemoortele** [craftcms/commerce#1174]
### Description
Decimal numbers in Per Item Discount are rendered differently in commerce depending on the logged in users language settings.
A discount set to for example 0.75 will render as 0 in dutch

### Steps to reproduce

1. Create a discount with the Per Item Discount set to a decimal number, for example 0.75
2. Switch user language to "nederlands"
3. Go back to the discount, Per Item Discount will be shown as 0 instead of 0.75

### Additional info

- Craft version: 3.3.16.3
- PHP version: 7.2.25
- Database driver & version: MySQL 5.7.27
- Plugins & versions: Commerce 2.2.8

Discount with user language set to English (United Kingdom)
![per-item-discount-EN](https://user-images.githubusercontent.com/2240463/70717025-d08dc400-1ced-11ea-83b1-5df571235377.png)

Discount with user language set to Nederlands
![per-item-discount-NL](https://user-images.githubusercontent.com/2240463/70717168-19457d00-1cee-11ea-92cc-8ac3677df763.png)

**Comment by nfourtythree** [comment]
Hi @stevenvandemoortele 

Thank you for bringing this to our attention.

This has been fixed and will be included in the upcoming `3.1` update.

Thanks.
