### ISSUE TITLE
getLastTransaction might not be the final transaction

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/commerce#1178]
I have a site that includes an automated order refund function. We check if the refund is allowed based on the status of the last transaction using `order.getLastTransaction()` and some other checks. We're also using a redirect gateway.

We've had a few customers unable to request their refund due to previously abandoned transactions timing out AFTER their final successful transaction. Here's an example:

![Screen Shot 2019-12-13 at 10 19 15](https://user-images.githubusercontent.com/1082223/70813803-18692580-1d98-11ea-9d02-9d04c8a84443.png)

The transaction highlighted in red timed out 20 mins after the successful payment leaving the Failed transaction as the last transaction.

I realise it's hard to guess user intent and I'm sure there are exceptions but it seems to me for a redirect gateway at least: 
1. Where the value of a successful transaction covers the whole value of the order, previous incomplete attempts should automatically be cancelled or marked as superseded somehow.
2. If a successful transaction exists within the last _parent_ transaction `getLastTransaction` should return that, rather than any subsequent timeouts that are children of older transactions.

I may be wrong here but otherwise how can we be sure the get the last meaningful transaction that actually represents the state of the order?

**Comment by lukeholder** [comment]
You should probably loop over all transactions for the order that have no parentId (top level), and then call `transaction.getRefundableAmount()`, and if there is an amount there, show the refund button. Hope that helps.
