### ISSUE TITLE
Don't show short-hand date/time for dates in orders index

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1179]
This might be more of a Craft core thing, but its applicable more for Commerce. Currently, dates are shown in a short-hand format, often showing `Yesterday` instead of a date-time stamp.

Could this be changed to always show the full timestamp? This is probably breaking away from core behaviour as mentioned, so happy to hear thoughts.

https://d.pr/free/i/xXxNbH

**Comment by gojira32** [comment]
> This is probably breaking away from core behaviour as mentioned, so happy to hear thoughts.

@engram-design Totally understand that this is breaking away from Craft core behaviour, but from the perspective of being CS rep having to dig into the order index multiple times a day to check on order statuses etc. the way this is currently handled is really poor.

**Comment by bossanova808** [comment]
I agree that relative dates require more mental agility than just showing the actual date/time and would prefer the latter.  The recent orders widget presents it well...it's just a lot clearer on a quick read.  And having 'yesterday' doesn't give you the time, which is often relevant in order processing.

![image](https://user-images.githubusercontent.com/731309/70870534-9e7bab00-1fe8-11ea-8a6d-5e6fb868a3d5.png)

**Comment by lukeholder** [comment]
Decided to revert the setting in the PR, and to let developers modify the output of this using the `EVENT_SET_TABLE_ATTRIBUTE_HTML` event.
