### ISSUE TITLE
A way to query orders by user id

### ISSUE THREAD

**Issue by peirix** [craftcms/commerce#1183]
### Description
It'd be nice if `userId` was a public property of the `OrderQuery` so we could query orders based on user id instead of customer id when fetching from PHP code. This is possible today using twig using the `user()` method, but that isn't possible using the element api.

**Comment by nfourtythree** [comment]
Hi @peirix 

This is already possible in both PHP and Twig. The user param on the `OrderQuery` excepts a user ID.

So in Twig you are able to do the following

```twig
{% set orders = craft.orders.user(1).all() %}

<ul>
  {% for order in orders %}
      <li>{{ order.reference }}</li>
  {% endfor %}
</ul>
```

Or in PHP you are able to do:

```PHP
$query = Order::find();
$query->user(1);
$orders = $query->all();
```

Hope this helps!

**Comment by peirix** [comment]
Sorry. I should have specified more, then, as I was trying this using the element API.

**Comment by nfourtythree** [comment]
HI @peirix 

This is still possible although a little more awkward as the isn't a `users` param.

But you can get the same result with the following in your `element-api.php`:

```php
<?php

use craft\base\Element;
use craft\commerce\elements\Order;
use craft\commerce\elements\Product;

return [
    'endpoints' => [
        'orders-by-user.json' => function() {
            $userId = Craft::$app->request->getParam('userId');

            $query = Order::find();
            $query->user($userId);
			$query->limit(null);
            $ids = $query->ids();

            return [
                'elementType' => Order::class,
                'criteria' => [
                  'id' => $ids
                ],
                'transformer' => function($order) {
                    return [
                        'reference' => $order->reference
                    ];
                }
            ];
        },
	]
];
```

One thing I would note is to be really careful with this. It is not recommended with passing the `userId` as an integer in the URL as this could cause potential security issues.

The above is code is only for demonstration purposes as to how it would be possible.

**Comment by peirix** [comment]
Yeah, I managed to get around it now using this:

```
$currentUser = Craft::$app->user->getIdentity();
$customer = craft\commerce\Plugin::getInstance()->getCustomers()->getCustomerByUserId($currentUser->id);
return [
    'elementType' => Order::class,
    'criteria' => [
        'customerId' => $customer->id,
        'orderStatusId' => '2'
    ],
    'transformer' => function(Order $order) {
        return [
            'reference' => $order->reference
        ];
    }
];
```

Just thought I'd let you know in case the missing `user` param was a slip-up, as that would be a lot cleaner than this.
