### ISSUE TITLE
After update PHP Warning

### ISSUE THREAD

**Issue by BramBeekman** [craftcms/commerce#1189]
### Description

yii\base\ErrorException: Invalid argument supplied for foreach() in 
C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\yiisoft\yii2\i18n\Formatter.php:1764

### Steps to reproduce

1. Revome vendor & reinstall

**Comment by BramBeekman** [comment]
![screenshot](https://user-images.githubusercontent.com/37911406/71308828-6e297780-2401-11ea-8fe1-618c8ff524fa.png)

**Comment by nfourtythree** [comment]
Hi @BramBeekman 

Could you clarify whether this is in the front end or the control panel for this site?

Thanks

**Comment by BramBeekman** [comment]
> Hi @BramBeekman
> 
> Could you clarify whether this is in the front end or the control panel for this site?
> 
> Thanks

Hi @nfourtythree 

This is on the front page (where i load the products)

**Comment by nfourtythree** [comment]
Hi @BramBeekman 

Thanks for your response. I can't seem to replicate this with the example Commerce templates and a fresh install of Commerce.

Could this be something in your templates?

**Comment by lukeholder** [comment]
Please let us know if you have more info on reproducing this.
