### ISSUE TITLE
commerce/cart/get-cart saves empty carts

### ISSUE THREAD

**Issue by scopesampling** [craftcms/commerce#1190]
This is similar to https://github.com/craftcms/commerce/issues/403, emtpy carts are being saved when calling get-cart on the ajax controller, which causes empty active carts to be created for each visitor of the website.

It looks like this bug has been introduced in https://github.com/craftcms/commerce/commit/afa285a11934c7c37231bfb3abf96e74f59d9d68.

**Comment by oddnavy** [comment]
We've been able to replicate this which is causing our get cart requests to timeout

**Comment by lukeholder** [comment]
Thanks for reporting, fixed for the next release.
