### ISSUE TITLE
Translation not working with notification of order status/address update.

### ISSUE THREAD

**Issue by watarutmnh** [craftcms/commerce#1195]
Seems not working translate func at below lines:

vendor/craftcms/commerce/src/web/assets/commercecp/dist/js/commercecp.js
Line:208
Craft.cp.displayNotice(Craft.t('commerce', 'Address Updated.'));
Line:569
Craft.cp.displayNotice(Craft.t('commerce', 'Status Updated.'));

vendor/craftcms/commerce/src/web/assets/commercecp/src/js/CommerceOrderEdit.js
Line:110
Craft.cp.displayNotice(Craft.t('commerce', 'Status Updated.'));

Those are notification for order's status or address updated.

- Craft version: 3.3.19
- PHP version: 7.3.6
- Database driver & version: MySQL 5.7.26
- Commerce version: 2.2.13

**Comment by nfourtythree** [comment]
Hi @watarutmnh 

Thanks for bringing this to our attention, we have pushed an update that rectifies this.

Thank you again for your ongoing work on translations.
