### ISSUE TITLE
Erroneous "minorUnits" attribute on PaymentCurrency model

### ISSUE THREAD

**Issue by yoannisj** [craftcms/commerce#1200]
### Description

The `craft\commerce\models\PaymentCurrency` model defines a [`minorUnits` attribute](https://github.com/craftcms/commerce/blob/master/src/models/PaymentCurrency.php#L83) which throws a "trying to access unknown property" error when calling the model's `toArray()` method.

My guess is that this is a typo, and that it should actually define a `minorUnit` attribute (without the trailing "s"), which can be accessed via the model's [`getMinorUnit()` method](https://github.com/craftcms/commerce/blob/master/src/models/PaymentCurrency.php#L130).

### Steps to reproduce

1. Run the following code somewhere:

```
$currencies = CraftCommercePlugin::getInstance()
    ->getPaymentCurrencies()->getAllPaymentCurrencies();

$data = array_map(function($currency) {
    $currency->toArray();
}, $currencies);
```

### Additional info

- Craft version: 3.3.17
- PHP version: PHP-FPM 7.3
- Database driver & version: Maria DB 10.4 
- Plugins & versions: Commerce 2.2.8 (seems to apply to 2.2.13 as well)

**Comment by nfourtythree** [comment]
Hi @yoannisj 

Thanks for letting us know, have pushed up a fix for this that will be included in the next release.

**Comment by yoannisj** [comment]
@nfourtythree great! thanks for the quick resolution :)

**Comment by yoannisj** [comment]
@nfourtythree great! thumbs up for the quick resolution :)
