### ISSUE TITLE
Typo in "Billing detail update URL" placeholder text

### ISSUE THREAD

**Issue by vonscriptor** [craftcms/commerce#1201]
### Description
_System Settings > General Settings > Subscription Settings > Billing detail update URL_

Placeholder text: "_//example.com/subscriptions/udpateBillingDetails_"

"**udpateBillingDetails**"

### Additional info

- Craft version: 3.3.13
- Plugins & versions: Commerce Lite 2.2.13

**Comment by lukeholder** [comment]
Thanks, fixed for next release.
