### ISSUE TITLE
Merged Commerce Cart Issue

### ISSUE THREAD

**Issue by leigeber** [craftcms/commerce#1203]
### Description

Hello, shot off a couple emails to support over the last month but haven't heard back so posting here. It seems that although the docs explain that mergedCart should work the same as cart, aside from the merging, it creates an empty cart when getting the count for instance.

{{ craft.commerce.carts.mergedCart.getTotalQty() }} - creates a blank cart
{{ craft.commerce.carts.cart.getTotalQty() }} - doesn't create cart

Is this a bug or expected behavior?

Also, there are some template typos in https://docs.craftcms.com/commerce/v2/adding-to-and-updating-the-cart.html#cart-merging, cart vs carts, commetce vs commerce

### Additional info

- Craft version: Craft Pro 3.3.15
- PHP version: 7.3.12
- Database driver & version: PostgreSQL 12.1
- Plugins & versions: Commerce 2.2.8

**Comment by lukeholder** [comment]
Replied on support
