### ISSUE TITLE
Adding a product to a site propagates to all sites

### ISSUE THREAD

**Issue by pdaleramirez** [craftcms/commerce#1212]
### Description
Whenever i add a product and choose a site to add it to. It will propagate to all sites. The product is added to all site. I expected it to be added on specific site only.

### Steps to reproduce

1. Add new product
2. Select a site on the site Dropdown 
3. Save the product
4. Check on product index page, the product is added to all sites.

### Additional info

- Craft version: v3.3.15
- Plugins & versions: Commerce v2.1.13

**Comment by lukeholder** [comment]
At the moment this is how it works. When we introduce full multi-site/multi-store support we will address this.

Please refer to https://github.com/craftcms/commerce/issues/37
