### ISSUE TITLE
Template error when viewing customer in the cp

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1216]
### Description

<img width="1558" alt="Screenshot 2020-01-15 at 10 01 26" src="https://user-images.githubusercontent.com/1846063/72424503-0820dd80-377e-11ea-9bc1-898e4e3ca2ff.png">

### Additional info

- Craft version: 3.4.0-RC1
- PHP version: 3.0.0-RC1

**Comment by nfourtythree** [comment]
Hey @samhibberd 

This was fixed with 485b9b2bcafd22a85a99f7179981514d703192cc

It will be included in the next release, for now if you update your `composer.json` with the following this should get things working.

```
"require": {
  "craftcms/commerce": "3.0.x-dev#485b9b2bcafd22a85a99f7179981514d703192cc as 3.0.0-RC1",
  "...": "..."
}
```

Thanks!
