### ISSUE TITLE
Order Status count badge

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#1217]
### Description

A small point! In the CP, when moving orders around via order status, the count badge only reports the correct number of orders in it once the page has been refreshed manually, even though the orders get moved between statuses instantly.

### Steps to reproduce

1. In orders, click into an order status with orders in it
2. Tick the checkbox of an order, click on the cog icon at the top and select "Update Order Status"
3. Move the order into another order status
4. Orders are moved instantly, but the count badge reports an incorrect number until you refresh the page manually

### Additional info

- Craft version: 3.4.0-RC1.1
- PHP version: 7.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Craft Commerce 3.0.0-RC1

**Comment by jonleverrier** [comment]
@lukeholder Do you think this enhancement will be worked on in the next release? 

As small as it seems, I have a client i'm moving across to Commerce and I know it's something they're going to mention.

Certainly not a deal breaker, but would be good to set their expectation.

**Comment by nfourtythree** [comment]
Hi,

This has been updated in 3df9a68bcfe4b772b056a2aea0b09434bd318529

It will be included in the next release.

Thanks.

**Comment by jonleverrier** [comment]
@nfourtythree Thank you for looking at this!
