### ISSUE TITLE
3.0-RC1 Live Preview and Share buttons not positioned correctly?

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#1219]
### Description

It looks like the `Live Preview` and `Share` buttons are in the wrong place and missing icons when you compare them to Craft 3.4.0-RC1.1.

**Commerce 3.0.0-RC1**
![Screen Shot 2020-01-16 at 11 05 50](https://user-images.githubusercontent.com/2373940/72515547-63bb9b80-3850-11ea-961c-86a68a056271.png)

**Craft 3.4.0-RC1.1**
![Screen Shot 2020-01-16 at 11 06 29](https://user-images.githubusercontent.com/2373940/72515625-82219700-3850-11ea-9f36-845573cb39f6.png)

### Additional info

- Craft version: 3.4.0-RC1.1
- PHP version: 7.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Craft Commerce 3.0.0-RC1

**Comment by nfourtythree** [comment]
Hey @jonleverrier 

Thanks for letting us know about this. It has been fixed in: eead2e3cd0b50bd28fbea2fc1273fd82f1bb8554 and will be included in the next release.

Thanks!
