### ISSUE TITLE
No events for Customers or Customer Addresses

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/commerce#1220]
Unless I’m mistaken, there’s currently no way to hook into Customer or Customer Address changes.

There’s scenarios where we want to sync these with other services. That’s even mentioned in the docs, however, it’s not possible to determine the Customer for an Address.

We *could* pull the current User/Customer, however, I’m guessing that Commerce 3 means that could be a User editing the Address via the CP. Queries could also work but aren’t a clean/DRY solution.

**Comment by lukeholder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing](https://trello.com/c/UW9Jx9Rn/2-testing)

**Comment by joshuabaker** [comment]
Working with this code right now. _Really_ inelegant.

```php
$address = $event->address;

$request = Craft::$app->getRequest();

if ($request->isCpRequest && preg_match('~/users/([0-9]+)$~', $request->getReferrer(), $matches)) {
    $user = Craft::$app->getUsers()->getUserById($matches[1]);

    if (!$user) {
        return;
    }
} else {
    $user = Craft::$app->getUser()->getIdentity();
}
```

Sharing here for posterity.

**Comment by lukeholder** [comment]
Add before and after save customer address (in customers service)

While you are in the customers service add before and after save customer. (not cancellable)
