### ISSUE TITLE
Stripe billing in wrong currency

### ISSUE THREAD

**Issue by Coalescent** [craftcms/commerce#1225]
### Description

We have 2 Stripe gateways configured - one for USD and one for CAD. When we submit an order from the front end for the USD gateway, for some reason, it appears that Craft requests the billing to be in CAD - not USD.

In the CP it shows the order having used the USD gateway but the Payment Currency is in CAD (we've confirmed the Payment Currency is correctly set to USD before submitting the order).

If I look at the Stripe logs, I see this Request POST for `payments_methods` (non-critical data edited out for brevity):

```
{
  "type": "card",
  "billing_details": {
    "name": " ",
    "email": "some@email.com",
    "address": {
      "line1": "9241 13th Ave SW",
      "city": "Seattle",
      "postal_code": "98106",
      "country": "US"
    }
  },
  "card": {
    "number": "************4242",
    etc...
  },
    etc...
  "key": "******************" (it is the correct key for the USD gateway)
}
```
Then the response body is sent back:

```
{
  "id": "pm_1G3XCGAlW9Q1oYFOHwR3Bmxp",
  "object": "payment_method",
  "billing_details": {
    "address": {
      "city": "Seattle",
      "country": "US",
      "line1": "9241 13th Ave SW",
      "line2": null,
      "postal_code": "98106",
      "state": null
    },
    "email": "some@email.com",
    "name": " ",
    "phone": null
  },
  "card": {
    "brand": "visa",
    "checks": {
      "address_line1_check": null,
      "address_postal_code_check": null,
      "cvc_check": null
    },
    "country": "US",
    "exp_month": 12,
    "exp_year": 2021,
    "funding": "credit",
    "generated_from": null,
    "last4": "4242",
    "three_d_secure_usage": {
      "supported": true
    },
    "wallet": null
  },
  "created": 1579653353,
  "customer": null,
  "livemode": false,
  "metadata": {
  },
  "type": "card"
}
```

And then the Request POST for `payment_intents`:

```
{
  "amount": "20010",
  "currency": "CAD",
  "description": "Order #13695",
  "metadata": {
    "order_id": "13695",
    "order_number": "0dce62853a0a16f325935e80a8182456",
    "transaction_reference": "503429abae05caad293e03b2171f1707",
    "client_ip": "::1"
  },
  "payment_method": "pm_1G3XCGAlW9Q1oYFOHwR3Bmxp",
  "capture_method": "automatic",
  "confirmation_method": "manual",
  "confirm": "false"
}
```
So, I am puzzled as to why the currency is now set to CAD?

I am using this form to submit the order:

```
<form method="post" id="paymentForm">
  <input type="hidden" name="action" value="commerce/payments/pay">
  <input type="hidden" name="cancelUrl" value="{{ '/shop/checkout/payment'|hash }}"/>
  <input type="hidden" name="orderEmail" value="{{ cart.email }}"/>
  <input type="hidden" name="gatewayId" value="{{ cart.gatewayId }}"/>
  {{ redirectInput('checkout/thankyou?number='~cart.number) }}
  {{ csrfInput() }}

  {{ cart.gateway.getPaymentFormHtml({})|raw }}

  <button type="submit">Place Order</button>
</form>
```

### Steps to reproduce

1. Configure a CAD and USD gateway for Stripe
2. Place an order with the USD gateway

### Additional info

- Craft version: Craft Pro 3.3.20.1
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26
- Plugins & versions:
Commerce 2.2.14
Stripe for Craft Commerce: 2.2.3

**Comment by Coalescent** [comment]
Looking at this further, here's what I've found...

I am setting the `gatewayId` and `paymentCurrency` via:

```
{% do craft.commerce.carts.cart.setGatewayId(2) %}
{% do craft.commerce.carts.cart.setPaymentCurrency('CAD') %}
```
When dumping the cart object, I can confirm that those two items appear set correctly. However, when submitting payment, as per the original issue, the Payment Currency reverts to CAD.

If I include this:

`<input type="hidden" name="paymentCurrency" value="{{ cart.paymentCurrency }}"/>`

in my `commerce/payments/pay` POST, then the currency is set correctly.

So, my question, is this expected behaviour or a bug? Can I not set the `gatewayId` and `paymentCurrency` like that? (I'm doing that in twig based on what country the user is in, returned from a geolocation plugin).

If I set those by actually posting them to `commerce/cart/update-cart` then I do not have to include that hidden field in the `commerce/payments/pay` POST - but I'd prefer to not have to POST those via a hidden ajax POST.

**Comment by lukeholder** [comment]
```
{% do craft.commerce.carts.cart.setGatewayId(2) %}
{% do craft.commerce.carts.cart.setPaymentCurrency('CAD') %}
```
Setting those things on the cart doesn't save the cart, it just sets them in memory on the order object.

Either submit those values in the update cart controller action, or call save cart from twig:

```
{% do craft.app.elements.saveElement(commerce.carts.cart, false) %}
```

**Comment by Coalescent** [comment]
Ah, ok... thanks Luke.
