### ISSUE TITLE
Large number of discounts (tens, hundreds of thousands) make the plugin unusable

### ISSUE THREAD

**Issue by klemenb** [craftcms/commerce#1226]
### Description

Craft Commerce doesn't handle cases where you have a lot of discounts as it tries to load all of them at once on multiple occasions.

We already had a workaround for the old 2.1.x series, but now the 2.2 changes made everything even worse as even more code loads all of the discounts (https://github.com/craftcms/commerce/commit/c9127ec8b03f597f81a78bcea4bc0d6e114b8620, https://github.com/craftcms/commerce/commit/0af0e743ebd2f06787fb8023e67534df5cbadd59, ...). 

Also, the more discount codes you have, the slower some site operations get. 

An example use case for that many discount codes is a promotional campaign that gives out 1-time vouchers to a large group of users.

### Steps to reproduce

1. Create ~500.000 (probably ~100.000 is enough) discount codes.
2. Try to load a page with products, add to cart, edit an item via the admin panel or anything that has to load all the discounts during the request.
3. Wait until the script reaches "memory_limit" and observe a "memory exhausted" error.

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3.x
- Database driver & version: MySQL 8
- Plugins & versions: Craft Commerce 2.2.14

**Comment by lukeholder** [comment]
This has been improved in 0af0e743ebd2f06787fb8023e67534df5cbadd59 & ae20c54ec18dc8652110fda91472724be47fcdcc which are set to be released in the next 2.x release.

**Comment by lukeholder** [comment]
In Commerce 3.x we will be splitting coupon codes from being managed seperate from the discounts.

**Comment by rickmerkelbach** [comment]
I seem to be running into the exact same issue with Commerce 3 in two separate projects, they have about 40.000 to 100.000 unique discount codes.

When a coupon is applied to a cart, every request to update the user's cart causes a huge increase in memory usage. It seems Commerce's Discounts Service loops through every discount until it matches the coupon code. This starts to become an issue after about 30.000 discount codes (the further down the array the code is, the longer it takes).

### Additional info
Craft version: 3.5.17.1
PHP version: 7.3.22
Database driver & version: MySQL 5.7.32
Plugins & versions: Craft Commerce 3.2.13.2
