### ISSUE TITLE
Commerce RC1 updateCart lineIten id error

### ISSUE THREAD

**Issue by Mathias-Syversen** [craftcms/commerce#1228]
When trying to push new line items to the cart I ran into an error:
"LineItem not found".

Upon closer inspection i can see that you have changed $lineItemId to be $key (index) in the controller.
This line fails:

`$lineItem = Plugin::getInstance()->getLineItems()->getLineItemById($lineItemId);`
line 174 in CartController.php

If I change this to use $lineItem['id'] instead, it works as usual.

`$lineItem = Plugin::getInstance()->getLineItems()->getLineItemById($lineItem['id']);`

**Comment by lukeholder** [comment]
Hi Mathias,

Nothing has changed with that code, when submitting the line items for update, they must be keyed by the line item ID:

```twig
<input type="text" placeholder="My Note" 
name="lineItems[{{ item.id }}][note]" value="{{ item.note }}">
```

Let me know if I have missed something.
