### ISSUE TITLE
No Sales Data with Ignore Sales Discount

### ISSUE THREAD

**Issue by JustJarethB** [craftcms/commerce#1229]
### Description
 I've updated commerce from `2.2.7 => 2.2.14` and now sales aren't showing on our checkout (but they are still showing on other pages). I tracked the error to between `2.2.9 => 2.2.11` as I had the errors fixed in .10 and .11. 

It seems that line items no longer registers the sale, so `item.onSale` is false and `item.subtotal` and `item.salePrice` return the default price. I can get the correct value with item.purchasable.subtotal but it's on the whole checkout process. Even the CP does not honour the sales.
From testing, it seems to be that having a promotion with `ignoreSales` in existence, means commerce literally ignores the sales, even if the discount is not being used / does not match. I deleted the discounts and then the sales came through again.

### Steps to reproduce

1. Create event and attach to sale
2. Create discount with `ignoreSales` set
3. Add product to cart
4. Check active cart in CP

### Additional info

- Craft version: Craft Pro 3.3.19
- PHP version: 7.3.3
- Database driver & version: MySQL 5.7.25
- Plugins & versions:

Abandoned Cart for Craft Commerce 2	1.3.6
Architect	2.3.1
Asset Usage	2.0.1
Audit	1.0.4
Batch PDF Export	1.0.3
Blitz	2.3.5
CKEditor	1.0.0-beta.2
Craft Commerce	2.2.11
DigitalOcean Spaces Volume	1.1.2
Element API	2.6.0
Empty Coalesce	1.0.6
Freeform	3.5.9
Imager	v2.3.1
Imager Storage Driver for DigitalOcean Spaces	1.0.0
Inventory	2.0.3
Link Vault	3.0.5.4
Maps	3.7.7
MJML	1.0.2
Password Policy	1.0.4
Position Fieldtype	1.0.14
Purchase Patterns	1.1.4
Redactor	2.4.0
Route Map	1.1.6
SEOMate	1.1.1
Sprout Redirects	1.2.4.1
Stripe for Craft Commerce	2.2.3
Webperf	1.0.17

**Comment by JustJarethB** [comment]
Duplicate, will reference there https://github.com/craftcms/commerce/issues/1206

**Comment by lukeholder** [comment]
This is now fixed in Commerce 2.2.15
