### ISSUE TITLE
Could not update orders address

### ISSUE THREAD

**Issue by MaximilianSchwarz** [craftcms/commerce#1238]
### Description
We create a new order via control panel and if we want to add some shipping or payment address we got the following error message:

Could not update orders address

### Steps to reproduce

1. Click button "New order"
2. Click "Create your first line item" and add one or more.
3. Choose your shipping method e.g "none" or "Free shipping"
4. Type in the customer email address
5. Add shipping address or payment address and click save

Now i got the following error: "Could not update orders address"

### Additional info
- Craft version: 3.4.0.2
- PHP version: 7.3
- Database driver & version: MYSQL
- Plugins & versions: Commerce 3..0.0

**Comment by lukeholder** [comment]
This should be fixed in 3.0.1 out now. Thanks.

**Comment by MaximilianSchwarz** [comment]
@lukeholder Thanks now it's working. But now the customer creation not working :(

If you create a new order and typ a new email address there is the following error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'orderId' in 'where clause' The SQL being executed was: SELECT `id` FROM `commerce_orders` WHERE (NOT (`orderId`='42')) AND ((`shippingAddress`='31') OR (`billingAddress`='31'))`
