### ISSUE TITLE
mistake in use declaration for ConsolidateGuestOrders

### ISSUE THREAD

**Issue by moldedjelly** [craftcms/commerce#1239]
### Description
Just a simple mistake in use declaration in:
/src/services/Customers.php
am thinking line 17 should be:
use craft\commerce\queue\jobs\ConsolidateGuestOrders;
it's currently:
use craft\commerce\queue\ConsolidateGuestOrders;
and causing an error when checking out.

### Steps to reproduce
1. Checkout with a offsite gateway

### Additional info
- Craft version: 3.4.0.2
- PHP version: 
- Database driver & version:
- Plugins & versions:

**Comment by nfourtythree** [comment]
Hey @moldedjelly 

Thanks for pointing this out. We have pushed up a fix and it will be included in the next release.
