### ISSUE TITLE
EVENT_AFTER_COMPLETE_ORDER and EVENT_AFTER_ORDER_PAID not triggering anymore

### ISSUE THREAD

**Issue by remcoov** [craftcms/commerce#1240]
### Description
Hi,

Since updating to Commerce 3.0 my event listeners inside my custom plugin aren't triggering anymore. 

This is for both `EVENT_AFTER_COMPLETE_ORDER` and `EVENT_AFTER_ORDER_PAID`. When changing this to `EVENT_BEFORE_COMPLETE_ORDER` for example (to test if the code is even working), the code works. So it seems like the AFTER events aren't triggering anymore. I am logging inside these events, which are also not triggered.

My code is very basic and it's even from the Craft Commerce docs:

```
use craft\commerce\elements\Order;
use yii\base\Event;

Event::on(Order::class, Order::EVENT_AFTER_COMPLETE_ORDER, function(Event $e) {
    // @var Order $order
    $order = $e->sender;
    // ...
});
```

### Steps to reproduce

1. Add the EVENT_AFTER_COMPLETE_ORDER or EVENT_AFTER_ORDER_PAID trigger in a custom plugin
2. Create and pay an order

### Additional info

- Craft version: 3.4.0.2
- PHP version: 7.3.10
- Database driver & version: MySQL 5.5.62
- Plugins & versions: 
AsyncQueue 2.0.0
Craft Commerce 3.0.0
Mollie for Craft Commerce 2.1.0.1
Redactor 2.5.0

**Comment by nfourtythree** [comment]
Hi @remcoov 

I believe this is actually related to another issue #1239 that was causing an error on order complete.

A fix has been a pushed for this and will be included in the next release.

Please reopen the issue if the problem persists.

Thanks!
