### ISSUE TITLE
How to require shipping tracking code when changing order status to shipped

### ISSUE THREAD

**Issue by moldedjelly** [craftcms/commerce#1244]
### Description
I'm trying to use the orderStatusChange event to detect when changing the order status to shipped, to then check if a shipping code has been supplied

This is my code:
        Event::on(OrderHistories::class, OrderHistories::EVENT_ORDER_STATUS_CHANGE, function(OrderStatusEvent $e) {
           $order = $e->order;
            if (empty($order->trackingCode)) {
                $e->isValid = false;
                // would be nice to also show an error with feedback?
            }
        });

Looking at the OrderStatusEvent class, it appears to extend CancelableEvent so should be able to do this?

How might I also provide some feedback too?

**Comment by lukeholder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [this](https://trello.com/c/MDjVBcRJ/14-this)

**Comment by moldedjelly** [comment]
@lukeholder that trello link is telling me that the card is not found

**Comment by lukeholder** [comment]
Sorry @moldedjelly we were testing an integration.

The order status change should not be cancellable, that is a bug, sorry about that. Will be fixed in the next release.

In commerce 3, you should hook into the beforeValidate order event and add a validation error to the order if they are trying to save the order with a different status ID (and they have no trackingCode present). You would need to do a query of the order from the DB to get the current status ID and compare it to the new status ID.

**Comment by moldedjelly** [comment]
so I updated my code as below which seems to work and gives a very general error at top of CP order edit page: "The order is not valid". The only thing is, it doesn't present the error on the trackingCode field - but it does show at base of "Order Details" tab as red JSON - should it be showing the error on the field?
```
        Event::on(Order::class, Order::EVENT_BEFORE_VALIDATE, function (Event $event) {
            $order = $event->sender;
            if ($order->orderStatusId == 2 && empty($order->trackingCode) && $order->shippingCompany->value != 'noTracking') {
                $order->addError('trackingCode', Craft::t('app', 'Need a tracking code'));
                $event->handled = true;
            }
        });
```

**Comment by lukeholder** [comment]
Hi @moldedjelly 

You would use `$order->addError('field:trackingCode',`

**Comment by moldedjelly** [comment]
@lukeholder thanks for the help on this. I updated my code as you suggested. It still doesn't present the error on the field though - it presents the error at base of Order Details tab [screenshot here](https://www.inkahoots.com.au/screenshots/uqp/tracking-code-feedback.png)
Is that intended behaviour?

**Comment by nfourtythree** [comment]
Hi @moldedjelly 

We are currently working on updates to the Order Edit screen for `3.1` and this is something we are taking into consideration.

Thanks.
