### ISSUE TITLE
Changing Ordered Date after update order from control panel

### ISSUE THREAD

**Issue by swordinthestone** [craftcms/commerce#1246]
### Description
There is a potential bug for updating orders from control panel for Craft Commerce.
The dateOrdered for completed orders or paid orders will increase 23hours by itself after clicking "Update Order" button if I don't change "Date Ordered" input.
It works fine if I change the ordered date or time.

I tested on Chrome and Firefox, and same problem occur.

### Steps to reproduce

1. Click on one order;
2. Click on "Edit" button;
3. Click on "Update Order" button without any changes.

### Additional info

- Craft version: 3.4.1 Commerce: 3.0.3
- PHP version: 7.2.18 (WAMP server)
- Database driver & version: MySQL 5.7.26
- Plugins & versions:
Amazon S3 1.2.7
Contact Form 2.26
Contact Form Extensions  1.2.0
Craft Commerce 3.0.3
Field Manager 2.1.1
Freeform 3.6.1
Redactor 2.5.0
Stripe for Craft Commerce 2.2.3
Super Table 2.4.1

**Comment by nfourtythree** [comment]
Hi @swordinthestone 

Thanks for reporting this. We have pushed up a fix.

It will be included in the next release, if you would like to get the update early you can do that by updating your Commerce requirement in your `composer.json`

```
"require": {
  "craftcms/commerce": "dev-develop#16399b3e000dfe9416eaa6f9a2542e3ecfd2235a as 3.0.3",
  "...": "..."
}```

Followed by running `composer update`.

Thanks!

**Comment by lukeholder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add to the thing](https://trello.com/c/7NDmxHsv/16-add-to-the-thing)
