### ISSUE TITLE
Change prices, add adjuster and add transaction before order complete.

### ISSUE THREAD

**Issue by MaximilianSchwarz** [craftcms/commerce#1249]
### Description
We are currently extensively testing the new function "Create order via the control panel". We have complicated products and often customers call us for advice and we create their order directly via the control panel. Currently it is only possible to add payment method, price changes and adjusters if the order is set to complete.

### Steps to reproduce

**We have noticed the following logic error:**
1. If we create a new order via the control panel, we select selected products, enter the customer's email address and assign the shipping and billing address and click on Save Order.
2. Now we have an active shopping cart.
3. So that we can now change the prices of the articles individually and also deposit a payment method we have to set the order to complete. 
4. This will automatically set the order to the default status "New", whereby the order confirmation email will be sent directly to the customer.

**Correct logic:**
1. We create the order via the control panel, select selected products, change the price of the products and add adjusters. We select a shipping and billing address and click on save order.
2. If we also select a payment option, the order is automatically set to "complete".
3. So the status of the order will be "New" and the customer will automatically receive the order confirmation email with the changed prices, adjusters, etc.

### Additional info

- Craft version: 3.4.1
- PHP version: 7.3
- Database driver & version: MYSQL
- Plugins & versions: Craft Commerce 3.0.3

**Comment by lukeholder** [comment]
We have plans to improve this for 3.1.

Right now the order acts like a cart (auto recalc everything) when the order is not completed.

We have plans to improve the UI for order editing and this includes being able to edit the order without any auto recalc when it is a cart, as well as a button to recalc the adjustments only.

thanks for the feedback and stay tuned.

**Comment by nfourtythree** [comment]
Hi

We are splitting these into separate issues as they might be improved/added/updated at different times.

Prices: #1355 
Adjustments: #992 

Thanks.
