### ISSUE TITLE
Filterable dropdown caret should show the pointer icon

### ISSUE THREAD

**Issue by Mosnar** [craftcms/commerce#1250]
### Description
I know it's small and irrational, but it drives me crazy. Hovering over the caret in these dropdowns currently shows the "selection" icon, but I think it would make more sense to display the "pointer" icon.
![image](https://user-images.githubusercontent.com/3810939/73451863-94163600-4336-11ea-8974-fb46465586ae.png)

### Additional info

- Craft version: 3.4.x
- Craft Commerce: 3.0.3
- PHP version: 7.3
- Database driver & version: MySQL 8
- Plugins & versions: N/A

**Comment by nfourtythree** [comment]
Hi @Mosnar 

Thanks for this, it has now been updated and will be included in the next release!
