### ISSUE TITLE
Missing german translations despite localization file contains required string

### ISSUE THREAD

**Issue by MisterMike** [craftcms/commerce#1254]
### Description

In /vendor/craftcms/commerce/src/templates/settings/producttypes/index.html the following two columns to get translated to german:

- "Available Shipping Categories"
- "Available Tax Categories"

In the german commerce.php translation file, the appropriate language strings are present.

### Steps to reproduce

1. Navigate to Commerce > Settings > Producttypes
2. In German, the columns

### Additional info

- Craft version: 3.4.1
- PHP version: 7.2

**Comment by nfourtythree** [comment]
Hi @MisterMike 

Thanks for pointing this out. Looks like it was an issue with a typo.

This has been fixed in f534f985749164bc96f5a74b7d85731baf21d4b7 and will be included in the next release.

Thanks!

**Comment by MisterMike** [comment]
Thanks! Albeit in my Commerce 3.0.3 version I cannot copy that. No typos but still no translation. If you wish I can check with the next release.

My german commerce.php:

```
    'Automatic SKU Format' => 'Automatisches Format für die Bestandseinheit (SKU)',
    'Available Shipping Categories' => 'Verfügbare Versandkategorien',
    'Available Tax Categories' => 'Verfügbare Steuerkategorien',
    'Base' => 'Basis',
```

and the index.html in producttypes:

```
        { name: 'shipping', title: Craft.t('commerce', 'Available Shipping Categories'),
            callback: function(value) {
                return value;
            }
        },
        { name: 'tax', title: Craft.t('commerce', 'Available Tax Categories'),
            callback: function(value) {
                return value;
            }
        }
```

**Comment by nfourtythree** [comment]
Using the latest files, this is what I am seeing on the product type settings page.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/rRuLeJgD/Screenshot+2020-01-31+at+11.28.19.png?v=5f9169bfae5f1d70528042ff812791ab)

The typo in the file is at the top of the page in the twig function `view.registerTranslations`.

Hope this helps!
