### ISSUE TITLE
Refund button does not appear for non-admins

### ISSUE THREAD

**Issue by martinleveille** [craftcms/commerce#1259]
### Description

Refund button does not appear even with the "Refund payment" permission activated for a non-admin user.

### Steps to reproduce

Even if the user has all the Commerce permissions activated, the button does not appear.

### Additional info

- Craft version: Craft Pro 3.4.1
- PHP version: 7.3.13
- Database driver & version: MySQL 5.7.29
- Plugins & versions: Commerce Pro 3.0.3

**Comment by nfourtythree** [comment]
Hi @martinleveille 

Thank you for pointing this out. We have pushed a fix for this and it will be included in the next release.

If you would like to get this change early, you can do that by updating your Commerce requirement in `composer.json` and running `composer update`.

```
"require": {
  "craftcms/commerce": "dev-develop#ae601cd9a6855105b4561e01d65e9a81daa0c6a6 as 3.0.5",
  "...": "..."
}
```

Thanks!
