### ISSUE TITLE
Commerce 3: Order emails do not send without a text template

### ISSUE THREAD

**Issue by Coalescent** [craftcms/commerce#1260]
### Description

Order emails fail if no text template path is supplied (this is optional in the CP). The Queue Manager error is:

```
Argument 1 passed to craft\web\View::renderString() must be of the type string, null given,
called in ... craft/vendor/craftcms/commerce/src/services/Emails.php on line 540
```

### Steps to reproduce

1. Place an order with no text template path defined in the CP.

### Additional info

- Craft version: 3.4.1
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26
- Commerce: 3.0.3

**Comment by Coalescent** [comment]
Probably a duplicate of #1257 (which I somehow missed before posting this) but will let someone at Commerce confirm.

**Comment by nfourtythree** [comment]
Hi @Coalescent 

If you upgrade to 3.0.5 you should find that this is fixed.

Thanks!
