### ISSUE TITLE
500 Error deleting tax 'general' category

### ISSUE THREAD

**Issue by ryanmwc** [craftcms/commerce#1261]
### Description

I'm getting an error when trying to delete the default general tax category. I've created two other categories that I'm using and clicked the X to delete "general" but get this error:

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mwc`.`commerce_products`, CONSTRAINT `commerce_products_taxCategoryId_fk` FOREIGN KEY (`taxCategoryId`) REFERENCES `commerce_taxcategories` (`id`)) in /Users/me/Sites/MWC/vendor/yiisoft/yii2/db/Command.php:1290
```

### Steps to reproduce

1. Install Craft Commerce
2. Go to Tax > Tax Category and create another tax category
3. Delete the existing "General" tax category from the overview page

### Additional info

- Craft version: 3.4.2
- Commerce version: 3.0.5
- PHP version: 7.3.8
- Database driver & version: MySQL 8.0.16

**Comment by nfourtythree** [comment]
Hi @ryanmwc 

If you have set the default category to a different category as well. Could you trying resaving the products, you can do this via the command line with:

```
./craft resave/products
```

And then try deleting the General category and let me know how you get on.

Thanks!

**Comment by lukeholder** [comment]
Closing this issue, can re-open if you can follow the above suggestion and the issue persists.

**Comment by benface** [comment]
I am also experiencing this. I tried running `./craft resave/products` first, but the error still occurs. I am sending a dump of my DB as well as `composer.json`, `composer.lock`, and project config files over to support@craftcms.com as I imagine that will help debugging the issue.

**Comment by pdaleramirez** [comment]
This is a bug and a fix will be released for this bug on this PR (https://github.com/craftcms/commerce/pull/1915)
