### ISSUE TITLE
PHP 7.1 syntax for array destructuring doesn't work on PHP 7.0

### ISSUE THREAD

**Issue by aNickzz** [craftcms/commerce#1262]
### Description
The new syntax for array destructuring is used here https://github.com/craftcms/commerce/blob/7ae6334ab33dbd6fb5417294fc6ae2aa8e3d893b/src/controllers/OrdersController.php#L332

However this requires PHP >= 7.1 and is an unexpected breaking change. I guess this was an unintentional change due to php-cs-fixer based on the commit message https://github.com/craftcms/commerce/commit/9a8c556c898dcdce1d3fa24f0a5814b31d33d3fa

> Fix usage for htmlspecialchars

The minimum required version of PHP should be specified in the `composer.json` so we don't accidentally install an incompatible version.

### Steps to reproduce

1. Install craft commerce 3.0.5 on a PHP 7.0 server
2. Navigate to the commerce tab in th eCP

### Additional info

- Craft version: 3.4.2
- PHP version: 7.0.33
- Database driver & version: N/A
- Plugins & versions: Commerce 3.0.5

**Comment by aNickzz** [comment]
This happens in all versions >= 3

```bash
$ git tag --contains 9a8c556c898dcdce1d3fa24f0a5814b31d33d3fa
3.0.0
3.0.0-RC1
3.0.1
3.0.2
3.0.3
3.0.4
3.0.5
```

**Comment by nfourtythree** [comment]
Hi @aNickzz 

Thanks for pointing this out. A fixed has been pushed and will be included in the next release.

Thanks!
