### ISSUE TITLE
"Save and return to all orders" link doesn't take you back to all orders

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#1266]
### Description

When editing an order, if you click on the cog and click the "Save and return to all orders" link, it doesn't take you back to the all orders view.

It might be my interpretation of the text, but I was expecting to be redirected to `/admin/commerce/orders`. 

![Screen Shot 2020-02-04 at 14 17 44](https://user-images.githubusercontent.com/2373940/73748452-cae6b480-4759-11ea-830b-fa7a8e122e3f.png)

### Steps to reproduce

1. Edit an order
2. Click on the cog (top right) and click on the "Save and return to all orders" link
3. The page is saved, but you're not redirected to "all orders"

### Additional info

- Craft version: 3.4.2
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.0.5

**Comment by nfourtythree** [comment]
Hi @jonleverrier 

Thank you for bringing this to our attention, this has now been fixed and will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#cbdce1eff222fb9179a2cd9ec8ff8f3e8a88eb30 as 3.0.5",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
