### ISSUE TITLE
First-party tax rates.

### ISSUE THREAD

**Issue by Mosnar** [craftcms/commerce#1267]
### Description
Now that more US states are taxing online sales, it's become standard for most ecommerce solutions to provide at least some level of tax rating out of the box.

For example:
- [Shopify provides default rates that are kept up to date](https://help.shopify.com/en/manual/taxes)
- [Woocommerce](https://woocommerce.com/products/tax/)
- [3dcart](https://support.3dcart.com/knowledgebase/article/View/102/2/how-do-i-add-tax-to-my-3dcart-store)
- [Magento](https://magento.com/blog/best-practices/anatomy-sales-tax-rate)

At this point we have the Avatax plugin; however, compatibility has not yet been updated for Commerce 3.

### Additional info

- Craft Commerce: 3.x

**Comment by lukeholder** [comment]
A taxjar plugin will be released soon. Will keep those interested updated here when it is released.

**Comment by lukeholder** [comment]
Taxjar plugin is on the plugin store: https://plugins.craftcms.com/commerce-taxjar
