### ISSUE TITLE
Transactions tab is turned off when opening an active cart page

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#1268]
### Description
Some  customers find it hard to order, so we create the order for them from the control panel. Now we can't complete it because the transaction tab is turned off after we updated commerce to 3.0.5

- Craft version: 3.4.4

**Comment by lukeholder** [comment]
We are revising the order edit screen in Commerce 3.1 and hope to address this soon.

**Comment by nfourtythree** [comment]
Hey @Sam-Black-0013 

This has been updated and will be included in the next release.

Thanks!

**Comment by Sam-Black-0013** [comment]
Thank you very much!!
