### ISSUE TITLE
Add a way to hook into the Vue Orders Admin interface

### ISSUE THREAD

**Issue by BenParizek** [craftcms/commerce#1269]
I'm posting this issue after a discussion with a few folks on how the updated Vue-driven Orders UI changes the way plugins can hook into the Order page interface. The simple request here is that we have some way to do something similar with the Vue admin as we did with template hooks:

```
{% hook "cp.commerce.order.edit.main-pane" %}
```

The following is just one example to consider in how developers might be using this feature. 

In our case, we have a Conference website that integrates with a custom Form at checkout. A user purchases a ticket to the conference and fills out a form that was created for that particular conference as part of their checkout process. As the Form is a separate entity in the database, in Commerce 2, we hooked into the Order UI to output a link to the submitted form and a summary of the submitted questions so admins could easily see the relationship between the Ticket Holder and the responses to their questions. We have other methods that they can see this data as well, such as by pulling a report, so the ability to update the Order Page UI was a nice to have if an admin happened to be interacting with a user based on a particular order and wanted to see those Form questions without having to go find them in a separate part of the interface.

**Comment by lukeholder** [comment]
FYI hooks like `{% hook "cp.commerce.order.edit.main-pane" %}` are still available but you would need to insert into the DOM outside of areas controlled by vue.

**Comment by lukeholder** [comment]
Added the `cp.commerce.order.content` template hooks to the Edit Order page.

This lets you add content to the page outside the scope of the tab switcher (would show on every page).

OR, it could be used to make tab content, and when we add the ability to register tabs in https://github.com/craftcms/commerce/issues/1904 the tabs can show and hide this content.
