### ISSUE TITLE
Variants of disabled products showing in query

### ISSUE THREAD

**Issue by BramBeekman** [craftcms/commerce#1270]
### Description

Variants of disabled products showing in query

` 
$allIdsVariant = \craft\commerce\elements\Variant::find()
            ->limit(null)
            ->status('enabled')
            ->ids();
`

**Comment by lukeholder** [comment]
Yeah that is not supported at the moment, you would have to do:

```php
$productQuery = \craft\commerce\elements\Product::find()->limit(null)->status('enabled');

\craft\commerce\elements\Variant::find()->limit(null)->status('enabled') ->hasProduct($productQuery)->ids();
```
