### ISSUE TITLE
syntax error, unexpected '?' on AverageOrderTotal widget

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce#1277]
### Description

I'm getting a `syntax error, unexpected '?'` error on the `AverageOrderTotal.php` widget (Even when i've not got it enabled it seems!) 

<img width="2040" alt="Screenshot 2020-02-12 at 15 34 07" src="https://user-images.githubusercontent.com/522877/74350494-b5066e80-4dad-11ea-8315-a9b83ada08b9.png">

### Additional info

- Craft version: 3.4.5
- PHP version: 7.0
- Database driver & version: MySQL 5.7
- Plugins & versions: Commerce 3.0.6

**Comment by nfourtythree** [comment]
Hi @bymayo 

Can you check you are definitely on `3.0.6` as this was fixed in that release.

Thanks.

**Comment by bymayo** [comment]
@nfourtythree Your correct, I'd not deployed! Argh. Running 3.0.5 (Issue) on staging, 3.0.6 local (No issue)! 

I thought it was something to do with PHP versions initially.

Sorry about that.
