### ISSUE TITLE
AJAX Currency Formatting

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1278]
There looks to be some inconsistency between the format of amounts with currency returned via the ajax cart request and the Commerce currency filter, where the value is 0 or has no minor value:

`{{ 0|commerceCurrency }}` returns `£0.00`
`{{ 24|commerceCurrency }}` returns `£24.00`

Where as `response.cart.totalPriceAsCurrency` returns `0` and `£24` respectively.

It would be great if it was consistent for both, preferably returning `£0.00` and `£24.00` for the above examples.

Same applies to all the ...AsCurrency properties defined in [currencyAttributes](https://github.com/craftcms/commerce/blob/9b8a7641fb754ee4918df62512e42dcd8a3896d2/src/elements/Order.php#L1058)

Running Commerce 3.0.6

**Comment by lukeholder** [comment]
thanks, fixed for the next release.

**Comment by samhibberd** [comment]
Hey @lukeholder 

Just picking this up again, we are still getting an inconsistancy between the behaviour of the`commerceCurrency` filter and the values returned by the `update-cart` controller.

`{{ 24|commerceCurrency }} = £24.00`
and
`cart.totalPriceAsCurrency = £24`

To correct the behaviour we are currently fixing this in our custom controller, but it would be ideal if the value returned was zero padded `£24.00` in all scenarios, see:

https://github.com/craftcms/commerce/blob/ac8723495f14bf1e0af67f47da32d99d0a7c8972/src/elements/Order.php#L1116

Just needs to pass `false` to the `$stripZeros` param of the currency formatter:

`return Craft::$app->getFormatter()->asCurrency($amount, $this->currency, [], [], false);`

**Comment by samhibberd** [comment]
Hi @lukeholder, but be great to get this inconsistency cleaned up.
