### ISSUE TITLE
Update order status mark all adjustments included and order get overpaid

### ISSUE THREAD

**Issue by martinleveille** [craftcms/commerce#1280]
### Description

When you change the status of an order, all adjustment get checked and if you save the order, the order get the overpaid status.

### Steps to reproduce

Video : https://www.youtube.com/watch?v=w8qDKHU09EI

1) With a fresh Craft 3.4.5 Pro and Commerce 3.0.6 Pro install, create some taxes, promotion, order statuses and shipping rules.

2) Create a new order using the Commerce provided "shop" templates.

3) Go to the control panel and change the status of the order.

4) All adjustments get included (checked) and the order is overpaid.

### Additional info

- Craft version: 3.4.5 Pro
- PHP version: 7.3.14
- Database driver & version: MySQL 5.7
- Plugins & versions: Commerce Pro 3.0.6

**Comment by lukeholder** [comment]
This is fixed and will be released today
