### ISSUE TITLE
Products that have been deleted in the CP are still available as Line items in the Cart

### ISSUE THREAD

**Issue by NixonGit** [craftcms/commerce#1286]
### Description
Hello,

When I have deleted a product from the CP and that product has resided in my cart, the product (line item) is still available. So when I check for cart.lineItems|length it passes but the logic after that fails.

### Error Message
impossible to access an attribute ("product") on a null variable. craft

### Steps to reproduce

1. Creat test product
2. Add product to cart on the front-end
3. Delete product in the CP
4. Refresh cart

### Additional info

- Craft version: 3.4.5
- PHP version: 7.3
- Database driver & version: MySQL 5.7

A concise interpretation of what I'm doing in the template

```
{% if cart.lineItems|length %}
<div class="l-basket u-mb-section">
	{% for item in cart.lineItems %}
		<div class="c-basket__row js-basket-rows" role="row">
			<div class="c-basket__cell" role="cell">
				<div class="c-basket__thumbnail">
					{% for image in item.purchasable.product.teaserImage %}
						{{ macros.image(image, { ratio: 1 }) }}
					{% endfor %}
				</div>
			</div>
		</div>
{% endif %}
```

**Comment by nfourtythree** [comment]
Hi @NixonGit 

This is expected behaviour. Line items are not products as line items exist on orders and are a record of a purchase.

For example if you were looking through old orders you would still want to see all the items purchased even if the product was deleted.

It is also worth noting that not all purchasables will have a product if you have some custom purchasable or purchasables that are added by a plugin.

Hope this helps!

Thanks.

**Comment by NixonGit** [comment]
Thanks @nfourtythree 

How would this affect the live cart though? 

My cart.lineItems|length check is failing because I have lineItems, even though my cart is empty.

What would be a more effective condition in this instance?

**Comment by nfourtythree** [comment]
Hi @NixonGit 

I am a bit confused here. If you have line items in your cart then your cart is not empty?

It might be worth running some custom logic in a module to check to see if there is a cart in the session and remove any line items that do not have a product.

Thanks.

**Comment by NixonGit** [comment]
Hi @nfourtythree 

That's where I'm confused too. I have emptied my cart by removing all items / posting to commerce/cart/update-cart with 
`
<form method="post">
    {{ csrfInput() }}
    {{ redirectInput('shop/basket') }}
    {{ hiddenInput('action', 'commerce/cart/update-cart') }}                                         	
    {{ hiddenInput("lineItems[#{item.id}][remove]", 1) }}
    <button class="link">Remove</button>
</form>
`
but when the page reloads I see the error above. I then investigated with {% dd cart.lineItems %} and found there to be a product that I have deleted from the CP. Which is why I raised the issue. Seems a bit odd.

Thanks for your advice on the module. I will look into that too.

**Comment by lukeholder** [comment]
If a product has been deleted, the next time the cart is updated and recalculated, any line item that contained that product will automatically be removed from the cart.

See video of this in action: https://jmp.sh/ETlqEpw

The form you pasted does not remove all line items, it just tries to remove the line item `{{ hiddenInput("lineItems[#{item.id}][remove]", 1) }}` that is returned with `{item.id}`

If you want to remove all line items you would do it with:

```
<form method="post">
    {{ csrfInput() }}
    {{ redirectInput('shop/basket') }}
    {{ hiddenInput('action', 'commerce/cart/update-cart') }}        
{% for item in cart.lineItems %}                                 	
    {{ hiddenInput("lineItems[#{item.id}][remove]", 1) }}
{% endfor %}
    <button class="link">Remove All</button>
</form>
```

**Comment by NixonGit** [comment]
Ignoring the form for now, does Craft automatically recalculate the Cart when a product is deleted? Or does the recalc only happen via a user action such as adding a new product or chaining quantity?

What we are trying to guard against is if a user were to add a product to their cart and take no further action. In the meantime we delete that product, the user then comes back and the only action they take is to to go to their cart. Basically what is the best practice to handle product removal during the time between a user adding a product and later navigating to cart.

**Comment by lukeholder** [comment]
@NixonGit correct, if you want it to happen to all carts immediately, then you would need to write a module.

The module would do something like this:

```php
        Event::on(Variant::class, Element::EVENT_AFTER_DELETE, static function(\yii\base\Event $event){
            $variant = $event->sender;
            $carts = Order::find()->hasPurchasables($variant)->isCompleted(false)->all();
            foreach ($carts as $cart){
                $cart->recalculate();
                Craft::$app->getElements()->saveElement($cart, false);
            }
        });
```

I haven't tested the above, but something like that should work.
