### ISSUE TITLE
Cannot edit existing products with multiple variants

### ISSUE THREAD

**Issue by stolat** [craftcms/commerce#1288]
### Description
Existing products with multiple variants cannot be edited.  When Save save is clicked stock fields are blank and "Error saving variants", "Stock cannot be blank" is thrown.

### Steps to reproduce

1.  Create product with multiple variants.  Click save.  No problem.
2. Edit the product just created.  Change title or any other field.  Click save.  
3. Error message pops, all stock fields are blank.

### Additional info

- Craft version: 3.4.6.1
- PHP version: 7.1.32
- Database driver & version: MySQL 5.7.16
- Plugins & versions:  Commerce 3.0.9

**Comment by nfourtythree** [comment]
Hi @stolat 

I have just tried to replicate this issue ([see video](https://x.n43.me/lluyZX4A)) and I am unable to get the same issue as you.

The only time this error would occur is if the stock field is blank and the unlimited checkbox is unchecked.

Are there any further details that you could point me to that might give me the ability to replicate the issue?

Thanks.

**Comment by stolat** [comment]
Try multiple variants, unlimited unchecked, and enter a qty in Stock.

See video<https://kevinkopec.com/videos/editproduct.mp4>

On Feb 20, 2020, at 9:47 AM, Nathaniel Hammond <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @stolat<https://github.com/stolat>

I have just tried to replicate this issue (see video<https://x.n43.me/lluyZX4A>) and I am unable to get the same issue as you.

The only time this error would occur is if the stock field is blank and the unlimited checkbox is unchecked.

Are there any further details that you could point me to that might give me the ability to replicate the issue?

Thanks.

**Comment by nfourtythree** [comment]
Hi @stolat 

Thanks for the extra information it was helpful in getting this sorted.

We have just pushed an update that should fix this. It will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#3fe35f9697c6f44882519133b268260216e1dc2e as 3.0.10",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
