### ISSUE TITLE
Not getting custom field errors on request to update-cart

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1292]
Calling the update-cart controller via Ajax, does not return any field errors. Includes both matrix and standard custom fields, standard fields look to save ok (if valid), not got matrix fields playing ball yet, so must be failing validation somewhere. Validation when saving in the cp is working. 

Update 24/02/20:

- Updating any required plain text field (standalone or in an existing matrix bock rows field) incorrectly passes validation when passing an empty string (supplying a value correctly updates the value)
- Saving a new matrix block row fails but with no validation errors and a cart success response returned.
- Updating an existing matrix block row works and returns validation errors if incorrect data is supplied (unless it's a plain text field as above) like invalid email to an email field.

Craft 3.4.6.1
Commerce 3.0.10

**Comment by nfourtythree** [comment]
Hey @samhibberd 

We have just added the ability to pass `validateCustomFields` in an update cart request.

This will give you errors (if applicable).

The update will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#bcf386211cede1f3e042433dad62c6349400b1f8 as 3.0.11",
  "...": "..."
}
```

Then run `composer update`.

The following is the information that will be going in the docs with this feature.

----

## Validating custom fields

By default, when updating the cart, custom fields are not validated. 

This is to avoid showing the user errors for unrelated fields when taking an action such as adding to cart.

If you want to allow custom fields to be validated on an update cart request, you can do so by adding the following field to the form:

```twig
<input type="hidden" name="validateCustomFields" value="1">
```

**Comment by samhibberd** [comment]
Thanks for getting this working. 

After a talking through with @nfourtythree, I raised if it would potentially be better to determine if the `fields[]` param is set and only validate is set, I could be wrong I can't see a scenario where you would pass custom field data without wanting it validated? With this implementation, although unlikely, someone could disable validation.

**Comment by samhibberd** [comment]
Hi @nfourtythree assuming this falls under the this issue, but addresses (with custom rules defined) are also not validating when saving via `commerce/cart/update-cart`, correctly validate when saved via `commerce/customer-addresses/save`.

Would there be an equivalent `validateAddressFields` input or an alternative solution?

Preference would still be validate any `fields[]` supplied for custom fields and validate addresses if there are custom rules defined.

**Comment by nfourtythree** [comment]
Hi @samhibberd 

I have just tested with the following custom validation and I was able to retrieve the error posting to `commerce/cart/update-cart`.

```php

        Event::on(Address::class, Address::EVENT_DEFINE_RULES, function($event) {
            if (!empty($event->rules)) {
                $event->rules[] = [['firstName'], function($attribute, $params, Validator $validator) use ($event) {
                    if ($event->sender->firstName && $event->sender->firstName != 'Testing') {
                        $validator->addError($event->sender, $attribute, Craft::t('site', 'First name is not "Testing".'));
                    }
                }];
            }
        });
```

**Comment by samhibberd** [comment]
My bad, I was using a custom controller which was pre-filing the firstName and lastName, values, adding some additional rules in the defineRules handler worked a dream:

``` php
public static function defineRules(DefineRulesEvent $e)
{
    $e->rules[] = [[ 'firstName', 'lastName', 'address1', 'city', 'zipCode', 'countryId' ], 'required'];
}
```

Regards custom fields, is this being considered:

> After a talking through with @nfourtythree, I raised if it would potentially be better to determine if the fields[] param is set and only validate is set, I could be wrong I can't see a scenario where you would pass custom field data without wanting it validated? With this implementation, although unlikely, someone could disable validation.

**Comment by nfourtythree** [comment]
At the moment we are sticking with the extra `validateCustomFields` param, as this way gives the option of doing both which you wouldn't get with the `fields[]` implementation.

It is definitely a valid point about someone being able to disable it. But as a developer, you will undoubtedly have checks to stop the customer from progressing any further if you do not have the data you require based on the stage they are at in the checkout.

**Comment by lukeholder** [comment]
@samhibberd We has to reverse the `validateCustomFields` idea. And moved to a config setting `validateCartCustomFieldsOnSubmission`.

This defaults to false, but if set to true, it will validate any custom field that is submitted in a cart update request. It will not validate any custom field when set to false (default). It will not validate a custom field that is not submitted when set to true.

**Comment by lukeholder** [comment]
In 3.0.12

**Comment by samhibberd** [comment]
Brilliant, thanks team, exactly what we were hoping for. 🎉
