### ISSUE TITLE
Assigning a customer in the CP to a manual order doesn't update the shipping/billing address

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#1295]
### Description

If you create a new order and assign a customer with a known shipping/billing address, the shipping/billing address panels remain blank.

Also, if you edit a manual order and change the customer from one to another. The existing customers address information remains.

### Steps to reproduce

1. Create a manual order
2. Assign a customer with a known shipping and billing address
3. Note how the shipping/billing panels remain blank and do not update

Or

1. Edit an existing order
2. Assign the order to a different customer
3. Note how the shipping and billing address panels do not update and it's also possible to save

### Additional info

- Craft version: 3.4.7.2
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.0.10

**Comment by nfourtythree** [comment]
Hi @jonleverrier 

We are making improvements to customer selection in `3.1`, which will include updates on this topic.

Thanks.

**Comment by nfourtythree** [comment]
With the release of `3.1` this is now possible.
