### ISSUE TITLE
Commerce Suggestions

### ISSUE THREAD

**Issue by dannylewin** [craftcms/commerce#1300]
Hey,

Just some suggestions for Commerce.

In the new function to create an order in the CP:

- The ability to set the payment currency
- If selecting a customer, their addresses should become available for selection in shipping and billing

- Craft version: 3.4.8
- PHP version: 7.4

**Comment by lukeholder** [comment]
> If selecting a customer, their addresses should become available for selection in shipping and billing 

this will be in Commerce 3.1

Added #1301 as a seperate ticket
