### ISSUE TITLE
Variant stock errors on save directly after successful upgrade from Craft 2 to Craft 3

### ISSUE THREAD

**Issue by robmcfadden** [craftcms/commerce#1306]
### Description

Variant stock errors on save directly after successful upgrade from Craft 2 to Craft 3. It looks like this is because the stock input fields have `disabled="0"` on them. Which means they are disabled.

### Steps to reproduce

1. Upgrade from Craft 2 to Craft 3
2. Save a Commerce Product
3. Should get the errors "Error saving variants." and "Stock cannot be blank."

### Additional info

- Craft version: Craft Pro 3.4.6.1
- PHP version: 7.3.11
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Craft Commerce | 2.2.17

**Comment by nfourtythree** [comment]
Hi @robmcfadden 

Thank you for highlighting this. It was fixed in Commerce 3, we will backport this fix to Commerce 2.

We will update this issue when it has been fixed.

Thanks.

**Comment by timkelty** [comment]
@nfourtythree can we please get a release with this?
