### ISSUE TITLE
Products not listed in New Order page

### ISSUE THREAD

**Issue by cliveportman** [craftcms/commerce#1307]
### Description
When adding a line item to an order created in the control panel, no products are returned. Either by searching or using the dropdown.

### Steps to reproduce

1. Create a new order from scratch (in the control panel) and go to add a line item. 
2. All searches return nothing unless I install the Gift Vouchers plugin, and then only gift vouchers appear.

### Additional info

- Craft version: 3.4.8
- PHP version: 
- Database driver & version:
- Plugins & versions: Commerce 3.0.11

**Comment by nfourtythree** [comment]
Hi @cliveportman 

Can you check you Product Types to see if they have an Order Description Format set?

Thanks!

**Comment by cliveportman** [comment]
No they don't. I've now set them to {product.title} but it seems you need to re-save each product for them to appear. Then, when I do select one it only displays the contents of a custom date field as the line item title.

**Comment by nfourtythree** [comment]
Hi @cliveportman 

I have no idea where that date would be coming from (especially as it is a custom field), do you have a custom module that is doing something with the populate line item event?

Thanks.

**Comment by cliveportman** [comment]
No. I thought it might be the Gift Vouchers plugin but after disabling it, the date is still there.

**Comment by cliveportman** [comment]
![image](https://user-images.githubusercontent.com/1431682/75366541-ce7fde00-58b6-11ea-81ce-47373e850459.png)

![image](https://user-images.githubusercontent.com/1431682/75366596-dfc8ea80-58b6-11ea-90c0-63fafc3f5968.png)

![image](https://user-images.githubusercontent.com/1431682/75366639-f1aa8d80-58b6-11ea-8b3c-05a20295c4d8.png)

**Comment by nfourtythree** [comment]
Hi @cliveportman 

What is the SKU of the product in the screenshots you sent across?

Thanks.

**Comment by cliveportman** [comment]
Ah, looks like client is manually entering the date as the SKU, so that's it. I think that's fine in images 1 and 3, but image 2 should show the description rather than the SKU? Or both.

**Comment by nfourtythree** [comment]
Hi @cliveportman 

We have updated the product/purchasable search in `3.1` so this should make things clearer.

Glad this is all sorted.

Thanks.
