### ISSUE TITLE
RFC - Custom actions on orders

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/commerce#1311]
Hi There,

As far as I can tell, this was phased out on Commerce 2.0 
commerce_addOrderActions

Can we re-introduce such a functionality again? Need it for an export order action.

**Comment by nfourtythree** [comment]
Hi @lenvanessen 

You can still register actions on element indexes please see the Craft documentation on this: https://docs.craftcms.com/v3/extend/element-action-types.html#registering-custom-element-action-types

Thanks.

**Comment by lenvanessen** [comment]
Hi @nfourtythree,

Currently it's only showing up on the overview, can we show the action in the list on the single order page as well?

Overview:
![Schermafbeelding 2020-03-03 om 12 17 56](https://user-images.githubusercontent.com/23024452/75770879-23a17100-5d49-11ea-948f-054255c85851.png)

Single order:
![Schermafbeelding 2020-03-03 om 12 18 01](https://user-images.githubusercontent.com/23024452/75770897-2ac87f00-5d49-11ea-932c-8b35e3ecc53e.png)
