### ISSUE TITLE
FR: Add field for store email to Store Location Settings

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#1313]
Super low priority...

While it's possible to set store name, address, tax ID etc in the Commerce Store Location settings, there is no dedicated field for an email address. 

While it's possible to use one of the custom fields for this, it seems like a bit of an omission.

**Comment by nfourtythree** [comment]
Hi @fantasticmachine 

Thank you for your request.

The store location is based on an address model which has no concept of an email address.

There are a number of places that an email address can exist (Craft settings, Commerce settings etc) so it would seem a little redundant to add it in here as well.

Thanks.
