### ISSUE TITLE
Disabling all countries in settings makes it impossible to access settings page

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#1314]
It's possible to disable all countries in the store settings.
If this is done (nice one client!) then it becomes impossible to access the admin/commerce/store-settings from the CP.

### Steps to reproduce

1. Disable all countries in store-settings/countries
2. Try to visit admin/commerce/store-settings

### Additional info

- Craft version: 3.4.8
- Commerce version: 3.0.10

**Comment by Adamascroft** [comment]
Same issue here:

Craft version: 3.4.9
Commerce version: 3.0.11

**Comment by nfourtythree** [comment]
Hi all

We have just pushed an update that fixes this issue.

It will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#6deea991b99305c80b4923aabf49b4879844c0b1 as 3.0.11",
  "...": "..."
}
```

Then run `composer update`.

Thanks.
