### ISSUE TITLE
Default setting for sale

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1317]
### Description
When creating a new sale, if you don't choose a product variant or category, the sale applies to the entire store.

This might lead someone to inadvertently apply a discount without knowing.

It would be better if the default setting said, "Apply to no products" and "Apply to no categories". 

And then have another option that says "Apply to all products", etc...

Thanks.

**Comment by nfourtythree** [comment]
Hi @keyurshah 

Thank you for submitting this.

This is something that we will be looking to address alongside the condition builder feature (#80).

Please follow along with that issue for updates.

Thanks!
