### ISSUE TITLE
Item being added to cart from previous cart when empty

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1319]
### Description
When the last item from the cart is deleted, the items from a previously unfinished order are added to the cart.

This seems like a bug to the user as they were not expecting that item to be added to the cart at that time.

If we had a better way to control that situation.

At the least, a notifiation alert that we can display to the user, indicating what just happened and why there is an item in the cart now.

Open to other ideas as well in how to manage that.

Thanks!

### Steps to reproduce

1. Add items to cart
2. Register as a user
3. Delete cookies
4. Add items to cart
5. Login as same user
6. Delete items from cart
7. The previous item from the first cart now shows in the current cart without any notification.

### Additional info

- Craft version: 3.4
- Craft Commerce: 3

**Comment by chrisrowe** [comment]
+1 on this

**Comment by nfourtythree** [comment]
Hi All

We have pushed up a fix for this that will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#8ecec2a4c3c2f8f704ddb0985d5e7cb840961331 as 3.0.11",
  "...": "..."
}
```

Then run `composer update`.

Thanks.
