### ISSUE TITLE
type error when saving new products

### ISSUE THREAD

**Issue by oddnavy** [craftcms/commerce#1320]
### Description
Commerce throws a type error when saving new products which have an auto-generated Variant Title Format.

Example: 
```twig
{product.title}
```

### Steps to reproduce

1. Create a new product with a title
2. You get the following type error caused by title returning null rather than an empty string

![image](https://user-images.githubusercontent.com/1872727/76581056-2c066280-6526-11ea-8695-287f22480c24.png)

### Additional info

- Craft version: Craft Pro 3.4.9
- PHP version: 7.4.3
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

![image](https://user-images.githubusercontent.com/1872727/76581022-12651b00-6526-11ea-8591-a4d8a3f74b89.png)

**Comment by nfourtythree** [comment]
Hi @oddnavy 

Unfortunately, I am unable to replicate this.

Could you verify if this is still any issue?

Thanks!

**Comment by oddnavy** [comment]
Pretty sure this is related to this issue: https://github.com/craftcms/commerce/issues/1333

We've stopped using the description field and it is no longer an issue

**Comment by lukeholder** [comment]
Yeah `description` is a reserved word for purchasables, we are looking into a way of making that more evident when setting up custom fields.
