### ISSUE TITLE
Discount - Purchase Total seems to be ignored

### ISSUE THREAD

**Issue by moldedjelly** [craftcms/commerce#1321]
### Description
Wanting to setup a discount so that members who have over $100 in cart get free shipping. When I set this up as per screenshot, it seems to apply the discount even if the order is under $100. Should this also be showing as a discount item in the order adjustments?

This might be related to issue #1144 

### Screenshot
https://inkahoots.com.au/screenshots/uqp/100_discount.png

### Additional info
- Craft version: 3.4.8
- Commerce version: 3.0.10

**Comment by moldedjelly** [comment]
Also, can this be achieved through a Shipping rule? Could the same condition system from Discounts (particularly User Groups matching) be available in the Shipping Rules too?

**Comment by nfourtythree** [comment]
Hi @moldedjelly 

Thank you for bringing this to our attention. We have pushed an update that should resolve this issue and it will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#c9541ca53a37f3299e3c18c4970d505e0d6e8e88 as 3.0.11",
  "...": "..."
}
```

Then run `composer update`.

Thanks.
