### ISSUE TITLE
Project Config throws `Invalid field layout ID:` when installing 

### ISSUE THREAD

**Issue by adampatpattison** [craftcms/commerce#1322]
### Description
I've recently built and set up a commerce site on an existing install which uses the project config for updates.

I've gone to deploy it on our staging env and run `migrate/all` and `project-config/sync` on the CLI as part of our post build deployment. 

This is throwing the error `Invalid field layout ID: 95`.

I've traced it back and this coming from the Exception thrown in `saveLayout()` in `vendor/craftcms/cms/src/services/Fields.php` on line `1258` which is called by `vendor/craftcms/commerce/src/services/ProductTypes.php` on line `435` 

I believe what is happening is it's creating the object from config and by setting the ID it is then looking this up in the `FieldLayoutRecord` but because this hasn't been saved before that row doesn't exist. 

I've got round this by writing a migration to manually INSERT the field types I need.

### Steps to reproduce

1. Install Commerce on a site using project config
2. Set up some product Types with fields
3. Rollback DB to before Commerce was installed
4. Run `project-config/sync` 

### Additional info

- Craft version: 3.4.9
- PHP version: 7.3.15
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
	- AsyncQueue	2.0.0
 	- Craft Commerce	3.0.11
 	- Environment Label	3.2.0
	- Google Cloud Storage	1.3.0
	- Mailgun	1.4.2
	- Minify	1.2.9
	- Redactor	2.6.0.1
	- SEOMatic	3.2.47
	- Super Table	2.4.6
	- Typogrify	1.1.18

**Comment by nfourtythree** [comment]
Hi @adampatpattison 

There have been a number of updates to Commerce and Project Config since this issue was raised.

If you update to the latest versions of Craft and Commerce and let us know if you are still having issues.

If so please send an email to support@craftcms.com.

Thanks!
