### ISSUE TITLE
Create address from Edit Customer page and Customer Info tab

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1324]
Would be great if it were possible to create addresses from the Edit Customer pages and Customer Info tab on Edit User pages. We offer wholesale pricing to industry professionals, but restrict shipments to addresses we have verified as part of our approval process. Being able to add these addresses from the CP would be much easier.

**Comment by lukeholder** [comment]
Will take a look to add this for the next release. Stay tuned! Thanks!
