### ISSUE TITLE
Wrong siteId stored in order

### ISSUE THREAD

**Issue by gijsstegehuis** [craftcms/commerce#1327]
### Description
When placing an order on (for example) the german site, it's saving the primary site's id in the order's siteId field instead of the german siteId.

### Additional info

- Craft version: 3.4.9
- PHP version: 7.4.3

**Comment by nfourtythree** [comment]
Hi @gijsstegehuis 

Currently, Commerce is not fully multi-site compatible and this relates to orders. Therefore all orders will only ever relate to the primary site ID.

There are future developments in the works to bring multi-store (#37) features to Commerce.

In the meantime, you could add a custom field to the order that gets populated with the site name when checking out.

This field can then be shown on the orders list in the control panel to help identify which site the order originated from.

Thanks.

**Comment by ryanmwc** [comment]
@nfourtythree is there any ETA on multi store?  Or at least when orders' content can be saved in different sites' languages?

**Comment by pixelmachine** [comment]
@nfourtythree @lukeholder 

As this is a known issue why does the [class reference](https://docs.craftcms.com/commerce/api/v3/craft-commerce-elements-order.html#ordersite) not specify this? Would have saved me a lot of wasted time.

**Comment by lukeholder** [comment]
I'm not sure that answer above was correct. 

The site the cart was last updated on is stored on the orderSiteId property of the order - anytime you use the cart controller actions. 

It should not be storing the primary site ID only, and if it is, it's a bug.

**Comment by pixelmachine** [comment]
For me @lukeholder `orderSiteId` and `orderSite` were returning the Primary site always. I started to use the siteId from a purchasable instead.

```php
Event::on(
  Order::class,
  Order::EVENT_AFTER_COMPLETE_ORDER,
  function (Event $event) {
      
    $order  = $event->sender;

    // Always returns Primary site id
    $siteId = $order->orderSiteId; 
    // Always returns Primary site
    $siteEl = $order->orderSite;
    // Always returns correct site id
    // $siteId = $order->lineItems[0]->purchasable->siteId; 

    if ($siteId === 1) 
    {
      $order->orderStatusId = 1; // Processing Site 1
      $message = "Status set to Processing Site 1";
      $order->message = $message;
    }

    if ($siteId === 2) 
    {
      $order->orderStatusId = 2; // Processing Site 2
      $message = "Status set to Processing Site 2";
      $order->message = $message;
    }

    Craft::$app->getElements()->saveElement($order, false);
  }
);
```

In this case if the primary site is 1 then the status will always be set to 1 and if the primary site is 2 then the status will always be 2.

This is Craft 3.4.18

**Comment by pixelmachine** [comment]
@nfourtythree @lukeholder want me to make a new issue? Or do you want to re-open this since the answer was incorrect?

**Comment by lukeholder** [comment]
@pixelmachine make a new issue, as I just realized this original issue was for `siteId` (which is always primary) and not `orderSiteId`. @nfourtythree original response was correct to the OP.
