### ISSUE TITLE
Subscription Active No Payment History

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/commerce#133]
Testing Stripe subscriptions in Commerce 2 (Test Mode for Stripe if that matters).

Subscriptions are active and correctly paid in Stripe dashboard but there is no payment history for the first successful payment.

Craft 3 RC14
Commerce 2 Alpha

<img width="850" alt="screen shot 2018-03-19 at 8 33 42 am" src="https://user-images.githubusercontent.com/8887839/37598507-62796c66-2b50-11e8-9781-90c89ac30657.png">

<img width="1105" alt="screen shot 2018-03-19 at 8 33 49 am" src="https://user-images.githubusercontent.com/8887839/37598509-64df1410-2b50-11e8-8f4f-95da9a5c6fbf.png">

**Comment by andris-sevcenko** [comment]
Have you set up webhooks for the gateway? If you haven't, there's no way for Commerce to know about the payments. (https://github.com/craftcms/commerce-stripe/blob/master/README.md#for-subscriptions)

**Comment by theskyfloor** [comment]
Yep!

**Comment by andris-sevcenko** [comment]
Can you make sure that you're receiving them on Commerce end? The Stripe Dashboard screenshot indicates that you have two pending webhooks, meaning they haven't reached Commerce.

**Comment by theskyfloor** [comment]
I get the response of 'ok' when I ping the webhook URL directly in the browser but you are right when I send a test webhook Stripe is returning an error.

I configured Commerce on a staging domain but am using a publicly accessible URL to test subscriptions could that have anything to do with it? My Site URL is set to the publicly accessible domain.

**Comment by andris-sevcenko** [comment]
* What error are you getting when you send the test webhook?
* Maybe there's something in the logs? 
* Maybe those are CSRF issues? What happens if you disable CSRF for the site?

**Comment by theskyfloor** [comment]
Oh! I am an idiot. I read the warning about CSRF but I forgot when it came time to actually configure. I will test and get back to this thread. That is probably it.

**Comment by theskyfloor** [comment]
Disabled CSRF and it's back - so the only way to disable this for just the Stripe API is to write a custom class in a module or plug-in? Otherwise I have to turn off CSRF wholesale until it is fixed in a future release?

**Comment by andris-sevcenko** [comment]
It's [mentioned in the docs](https://github.com/craftcms/commerce-stripe#disabling-csrf-for-webhooks) along with [a clean solution](https://craftcms.stackexchange.com/questions/4553/whats-the-best-way-to-skip-csrf-for-plugin-controllers/20301#20301) to disable CSRF for select controller actions.  

The two actions I personally disable for Commerce builds are

- `actions/commerce/webhooks/process-webhook`
- `actions/commerce/payments/complete-payment`

I'll close this, then. If any issues still show up, feel free to re-open.

**Comment by theskyfloor** [comment]
Can I dump that function right into config.php?

**Comment by andris-sevcenko** [comment]
Yessir!
