### ISSUE TITLE
Adding shipping rule with comma-value: "A non well formed numeric value encountered"

### ISSUE THREAD

**Issue by olsp** [craftcms/commerce#1332]
### Description
When I add a shipping rule and set a numerical value with a comma as a seperator (10,5 for example) for the Minimum Order Total Value, I get an error "A non well formed numeric value encountered". The shipping rule is added though and the numbers after the comma cut off.
I think Commerce should replace the comma with a period automatically.

### Additional info

- Craft version: 3.4.10.1
- Craft Commerce version: 3.0.12

**Comment by nfourtythree** [comment]
Hi @olsp 

This has been fixed and will be included in the upcoming `3.1` release.

Thanks
