### ISSUE TITLE
PHP error in PaymentsController when $currentUser is null

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1335]
Hitting the following PHP error when making a payment as a guest on Commerce 3.0.12.

`Call to a member function can() on null`

https://github.com/craftcms/commerce/blob/0b28dbca9b9887ce567c47c3920f5b2660ddf5b5/src/controllers/PaymentsController.php#L93

**Comment by nfourtythree** [comment]
Hi @samhibberd 

Thanks for pointing this out, this is currently being looked at. We will keep you updated on the progress.

Thanks.

**Comment by nfourtythree** [comment]
This [has been updated](https://github.com/craftcms/commerce/blob/5964f6f149ed283b46418617ea266418dc4a0907/src/controllers/PaymentsController.php#L96-L101) and will be included in the upcoming `3.1` release.

Thanks.
