### ISSUE TITLE
Cannot search for numeric-only SKUs from CP order edit page

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1337]
### Description

When editing an order in the control panel, we're unable to search for and find SKUs that contain only numeric characters.  Assuming we have two different products with SKUs *1077* and *1077R*, searching for *1077* will return nothing, but searching *1077R* will return the appropriate product.

### Steps to reproduce

1. From an order edit page in the control panel, click *Add a line item*
2. Search for an existing product with an SKU that contains only numeric characters — no results show
3. Search for an existing product with an SKU that contains alphanumeric characters — successfully finds product

### Additional info

- Craft version: 3.4.10.1
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.0.12

**Comment by lukeholder** [comment]
I just tried replicating on Commerce 3.1, due out this week. So upgrading to 3.1 should solve the problem.

![image](https://user-images.githubusercontent.com/133571/78130833-97b85d00-744c-11ea-881b-0d242d15cc46.png)
