### ISSUE TITLE
Optimize purchasable sales queries to mitigate an N+1 issue

### ISSUE THREAD

**Issue by taylordaughtry** [craftcms/commerce#1338]
### Description
This is likely related to #758 — we have a few thousand variants, and the JS is currently fetching sales for each one, which (as you can imagine) doesn't bode well for the DB availability and stability of the Product detail page.

Specifically, the JS [here](https://github.com/craftcms/commerce/blob/d83401386efe5463ad7cf1c21ea8d9870e2d7ca4/src/web/assets/editproduct/dist/js/CommerceProductEdit.js#L70) is the source. But from what I've read in other issues, this is a known problem, and isn't easy to solve.

Thoughts:
1. Would it be possible to update the Sales service `getSalesRelatedToPurchasable()` method to accept an array of purchasables, and do a single query for all matching sales? It doesn't appear to be used _too_ heavily across the front/backend, but it's very possible I'm missing context.
2. If that's not doable, what about **allowing the 'Variants' tab to be hidden/disabled** on the Product Detail page? For those of us with a significant number of variants, the end-user's obviously not expected to maintain that list, so it's extraneous in that particular use-case. (This assumes that there wouldn't be a need to query for sales, if the Variants aren't displayed.)

### Steps to reproduce

(Generally speaking)
1. Add a few thousand variants to a product
2. Open the product's detail page, and pop open DevTools (or similar in other browsers)
3. Check out the network tab: it's querying sales for each variant

### Additional info

- Craft version: 3.4.9
- PHP version: 7.2.17
- Database driver & version: MySQL 5.7.27
- Plugins & versions:

**Comment by lukeholder** [comment]
@taylordaughtry could you email us your database at support@craftcms.com so we could take a look? Reference this ticket. Thanks.

**Comment by lukeholder** [comment]
This has been fixed for the next release. Both sales and discounts now do not block the page from loading, and do all sale and discount loading over Ajax. This should give you a smoother experience. Look out for the next release in the next week or so.
