### ISSUE TITLE
Order recalculation happening before new custom field values are available?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1346]
It looks like the order recalculation is happening before any new custom field values are available when calling `commerce/carts/update-cart`?

We are using a custom adjuster to apply discounts only when certain conditions are met in our custom fields. On save the recalculation is happening based on the custom field values stored before save. 
Manually updating the order recalculates things correctly.

Craft CMS 3.4.11
Craft Commerce 3.0.12

**Comment by lukeholder** [comment]
Recalculation can happen at various times. If adding to a cart or updating it with data for the first time, the cart will be saved to the database first, which will cause recalculation, but after the item is added to the cart/updated the recalculation happens again before saving the order the final time.

Adjusters should be able to function the same no matter what, so as long as the adjuster can skip adding it's adjustments the first time around and then picks up the custom field information the second time it recalculates everything should be fine. Since the cart recalculates multiple times within the same request, the customer will only see the resulting cart, so it shouldn't confuse them.

Let me know if you have any questions.

**Comment by samhibberd** [comment]
Thanks for the detail @lukeholder, in this case the recalculation doesn’t look to be happening after the new custom field values have been saved. Are you saying that it should before the final save?

**Comment by samhibberd** [comment]
@lukeholder sorry to pick this up again but i can't get my head around why my custom adjuster is not saving on calling `update-cart`. Local testing shows that it is getting picked up by the adjuster logic, and is only applied when certain criteria are met. Resaving in the cp works. The data i am using to determine whether the adjustment is applied comes from a matrix block stored against the order. Will that have been saved before I need to access it in the update-cart logic and the final recalculate that is called?

Is it possibly related to a similar issue that i'm running into with saving carts via the `update-cart` controller. #1377 

It feels like i'm missing something really obvious, or running into a bug, any help would be greatly appreciated.

**Comment by lukeholder** [comment]
Can you share your adjuster code?

**Comment by samhibberd** [comment]
Sure, I have attached the adjuster and a custom order behavior which shows the logic behind the custom methods it provides to the order element. Everything sorts out on the subsequent `update-cart` so i'm assuming that I must not be cloning a query that I should be, or maybe running into a bug (maybe similar to #1377 which has just been fixed by @nfourtythree).

[Adjuster.zip](https://github.com/craftcms/commerce/files/4480069/Adjuster.zip)

**Comment by samhibberd** [comment]
@lukeholder Sorry to raise this again, but I have run a load more debugging and just can't get my head around it. Afaict the adjuster is not being passed the updated order and new custom field values. From my logging the adjuster is only run once during the `update-cart` process, along with the action i am only passing updated matrix block values and the orderNumber to the `update-cart` controller:

```
orderNumber: xxxxxxxxx
fields[participants][sortOrder][]: 93098
fields[participants][blocks][93098][type]: participant
fields[participants][blocks][93098][fields][race][]: 25313
fields[participants][blocks][93098][fields][firstName]: Sam
fields[participants][blocks][93098][fields][lastName]: Hibberd
fields[participants][blocks][93098][fields][affiliation][id]: 33
fields[participants][blocks][93098][fields][affiliation][number]: 123456789
```

And it is this new matrix block data that, although being saved ok, is not being populated in the `$order` used in my adjuster? Resulting in the adjustments not being added to the order on that save. If subsequently saved unchanged they get added. :(

Bit stumped, any help would be greatly appreciated.

**Comment by samhibberd** [comment]
@lukeholder have you had any chance to look at this, really stumped and just don't know if this is a code issue or a potential bug! Just say if there is anything further that I can provide.
