### ISSUE TITLE
Order History Template fails to load "customer" record

### ISSUE THREAD

**Issue by mposborne** [craftcms/commerce#1347]
### Description
Loading an order appears to fail when trying to access the "customer" record, and subsequent customer.user, in some cases (not all).

It appears that this line is wrong in src/templates/orders/_history.html:

`35                            {% if orderHistory.customer.user %}`

It seems that the following works, but I could be mistaken:

`35                            {% if orderHistory.order.customer.user %}`

### Additional info

- Craft version: Craft Pro 3.4.12
- PHP version: 7.3.16
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.0.12

**Comment by lukeholder** [comment]
Fixed in 4b2547097a2b17095020a75de0f3474556963eb8 which will be out this week in Commerce 3.1

**Comment by mposborne** [comment]
That's awesome Luke - thank you!
