### ISSUE TITLE
FR: Update shipping address when post contains shippingAddressId on updateCart()

### ISSUE THREAD

**Issue by Mathias-Syversen** [craftcms/commerce#1349]
I would like the updateCart controller to update the shippingAddress if both shippingAddressId and shippingAddress is present in the post data. Or at least have an event before the shipping address is added to the cart so I can do this myself with a plugin.

The current commerce site Im working on has only one page for checkout, with a form for "contact information". Most of the users are guests, guests cant update their addresses with the usual address form. A guest is related to a "customer" i can get this customers addresses, but not update them.

Right now I just supply shippingAddressId = 0 for each "updateCart" on this page, so the address gets updated. This results in an increasing number of addresses, used by no one. If I keep the ID, craft will create a new address each time, but keep the first one who matches the ID.

Also, the config "autoSetNewCartAddresses" seems to set the primary shipping address, not the last one used.

**Comment by lukeholder** [comment]
If I am reading you right you are wanting to update the shipping address on the order.

You should be able to do that right now:

```twig
{% set cart = craft.commerce.carts.cart %}

    {% set flashNotice = craft.app.session.getFlash('notice') %}

    {% if flashNotice %}
        <div class="bg-blue-500 text-white">
            <div class="flash container mx-auto px-6 py-4">
                {{ flashNotice }}
            </div>
        </div>
    {% endif %}

{% set flashError = craft.app.session.getFlash('error') %}

{% if flashError %}
<div class="bg-red-500 text-white">
  <div class="flash container mx-auto px-6 py-4">
    {{ flashError }}
  </div>
</div>
{% endif %}

{{ cart.number }}<br>

Shipping Address ID: {{ cart.shippingAddressId }}

<form method="post">
  <input type="hidden" name="action" value="commerce/cart/update-cart"/>
  <input type="hidden" name="cartUpdatedNotice" value="The address was updated.">
  {{ redirectInput('shop/address') }}
  {{ csrfInput() }}

  <!-- THIS IS WHAT WILL UPDATE THE ADDRESS VS ADDING A NEW ONE -->
  {% if cart.shippingAddress.id %}
  <input type="hidden" name="shippingAddress[id]" value="{{cart.shippingAddress.id}}"/>
  {% endif %}

  First Name:
  <input name="shippingAddress[firstName]" value="{{cart.shippingAddress.firstName ?? ''}}"/>

  <button type="submit">Update</button>
</form>
```

As above, using an input with `name="shippingAddress[id]"` with the address ID will update the address submitted with that ID on the `commerce/cart/update-cart` controller action just fine.

You would only use ``name="shippingAddressID"` if you wanted to select an existing one.

**Comment by lukeholder** [comment]
`autoSetNewCartAddresses` always uses the primary choice since commerce 2, it would need to be a seperate FR if you want us to add making that option set the last used. I will update the docs on that.
