### ISSUE TITLE
Unknown column 'discounts.orderConditionFormula' in 'field list'

### ISSUE THREAD

**Issue by malinky** [craftcms/commerce#1351]
### Description

I've installed craftcms and commerce and in the admin section I try and click on the one of the default products that have been added to the database and I get a Database Exception. There isn't an orderConditionFormula in my database.

`Column not found: 1054 Unknown column 'discounts.orderConditionFormula' in 'field list'`

### Steps to reproduce

1. composer create-project craftcms/craft
2. ./craft setup
3. composer require craftcms/commerce
4. ./craft install/plugin commerce
5. Open admin, click commerce -> products and try and view one of the default products (The Last Knee-High for example) and the Database Exception is shown.

### Additional info

- Craft version: 3.4.13
- PHP version: 7.35
- Database driver & version: mysql 8.0.12
- Plugins & versions: Commerce 3.10

**Comment by nfourtythree** [comment]
Hi @malinky 

Thank you for bringing this to our attention. We have pushed up a fix that will be included in the next release (that we look to get out asap).

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#6217bc5f7b1c75e27b4c8ce94f45bdbd56ba8d10 as 3.1.0",
  "...": "..."
}
```

Then run `composer update`.

Thanks.

**Comment by malinky** [comment]
No problem. Thanks for the quick fix.
