### ISSUE TITLE
Class 'NumberFormatter' not found

### ISSUE THREAD

**Issue by WonkoSVE** [craftcms/commerce#1353]
### Description

I updated to the latest version of CraftCommerce (3.1.0.1) and CraftCMS (3.4.13). I rely on currencies for this site. When visiting any page with a price the Class 'NumberFormatter' not found error is shown.

In **vendor/craftcms/commerce/src/web/twig/Extension.php**

     ```
 // return input if no currency passed, and both convert and format are false.
        if (!$convert && !$format) {
            return $amount;
        }

        if ($convert) {
            $amount = Plugin::getInstance()->getPaymentCurrencies()->convert($amount, $currency);
        }

        if ($format) {
            $options[\NumberFormatter::ROUNDING_MODE] = \NumberFormatter::ROUND_HALFUP;
            $amount = Craft::$app->getFormatter()->asCurrency($amount, $currency, $options, [], $stripZeros);
        }

        return $amount;
    }
```

### Steps to reproduce

1. Visit any page that uses a currency.

### Additional info

- Craft version: 3.4.13
- PHP version: 7.2.27
- Database driver & version: MySQL 5.7.27

### Plug ins

Craft Commerce | 3.1.0.1
Instant Analytics 1.1.5
Redactor 2.6.1
Retour 3.1.37
SEOmatic 3.2.49
Site Switcher 2.1.0
Stripe for Craft Commerce 2.2.3
Translations 2.0.3
Videos 2.0.10
Wordsmith 3.1.2

**Comment by lukeholder** [comment]
Thanks fixed for the next release due out later today.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#73a4c047a2714e2e3c36fed85568ce7ab223794b as 3.1.0.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by WonkoSVE** [comment]
Thanks Luke! It happened in a test environment so no terrible rush. In 
the meantime, I'll get the host to enable the Intl extension. I imagine 
that will also fix the issue.

Luke Holder wrote:

**Comment by lukeholder** [comment]
> host to enable the Intl extension

correct that will also fix the issue. Thanks.

**Comment by brandonkelly** [comment]
Commerce 3.1.1 is out now with the fix for this.

**Comment by WonkoSVE** [comment]
Thanks for the heads up.

Brandon Kelly wrote:
