### ISSUE TITLE
No possibility to setup a shipping or billing address

### ISSUE THREAD

**Issue by Maximilian-Schwarz** [craftcms/commerce#1354]
### Description
If you want to create a new order and create a new customer you are not able to setup shipping and billing address.

If you select an exisiting user shipping and billing address fills automatically. But if you want to create a new user you have no possibility to setup.

### Steps to reproduce

1. Click "Create new Order"
2. In customer type a new email address. For example test@domain.com an click on "Create "test@domain.com". Now the customer is created but the customer don't have a shipping or billing address. And i can't see anything to setup the address.

### Additional info

- Craft version: 3.4.13
- Craft Commerce: 3.1.0.1
- PHP version: 7.2
- Database driver & version: MYSQL

**Comment by nfourtythree** [comment]
Hi @Maximilian-Schwarz 

Thank you for pointing this out. It is actually possible, however, this is more of a UX bug.

We have pushed an update for this which will be included in the next release.

For the moment it is possible, although clunky. After creating the new customer if you click the "edit" link in the top right of the customer panel:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/lluyqw7X/Image%202020-04-03%20at%2010.43.05%20am.png?v=e159e73319c87dfe5685a6e011b54b01)

This will give you access to the billing and shipping address actions.

Thanks.

**Comment by brandonkelly** [comment]
Commerce 3.1.1 is out now with the fix for this.
