### ISSUE TITLE
Variants query hasStock(true) not working

### ISSUE THREAD

**Issue by gijsstegehuis** [craftcms/commerce#1356]
### Description
Using `hasStock(true)` on a variant query causes an SQL error:
```
SQLSTATE[42703]: Undefined column: 7 ERROR: column commerce_variants.hasunlimitedstock does not exist
LINE 8: WHERE (((commerce_variants.stock > 0 AND commerce_variants.h...
```

Workaround:
```
.where('stock > 0 or [[hasUnlimitedStock]]')
```

### Additional info

- Craft version: 3.4.13
- Commerce version: 3.1.0.1
- PHP version: 7.4.4
- Database driver & version: PostgreSQL 11.7

**Comment by brandonkelly** [comment]
Thanks for reporting that, @gijsstegehuis! We just released Commerce 3.1.1 with a fix for this.
