### ISSUE TITLE
Email required to make payments on a completed order.

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1357]
Running into the following error when trying to make a payment as a logged out user on a guest checkout, with email and all addresses set:

`Email required to make payments on a completed order.`

Let me know if / what additional information you require to help debug.

Craft 3.4.13
Commerce 3.1.0.1

**Comment by nfourtythree** [comment]
Hi @samhibberd 

You need to supply the email in the form submission as well, see: https://docs.craftcms.com/commerce/v3/making-payments.html#paying-outstanding-balance-on-a-cart-or-completed-order

Thanks!

**Comment by samhibberd** [comment]
Ah, is this new?

**Comment by keyurshah** [comment]
It would be nice to have an option of placing an order without an email address, especially for POS type transactions.

**Comment by nfourtythree** [comment]
> Ah, is this new?

Official support for paying the outstanding balance on a cart or a completed order was added in `3.1` yes.

> It would be nice to have an option of placing an order without an email address, especially for POS type transactions.

@keyurshah This is a separate thing in which we would need to allow orders to be completed without and email or customer.

If this is something you would like to see, please submit a feature request issue.

Thanks!

**Comment by jmauzyk** [comment]
Hey @nfourtythree, I'm getting this error when trying to make payments from CP order edit pages. The error occurs regardless of whether the order has been marked complete or not. Also, the Last Name field appears to be out of its intended grid:
<img width="387" alt="Screen Shot 2020-04-03 at 7 05 23 PM" src="https://user-images.githubusercontent.com/21298596/78413786-a0409d00-75de-11ea-816e-7551aaa7b00c.png">

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

The payment error was fixed as part of #1362 

Thanks.
