### ISSUE TITLE
Ability to filter out multiple email addresses in an order query

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#1361]
As per Craft Stack Exchange post
https://craftcms.stackexchange.com/questions/35045/how-to-exclude-multiple-email-addresses-from-an-order-query (quoted below)

The email() criteria only seems to accept a string value making it impossible to use it to omit more than one email address from an order query. 

Could it be changed to also accept an array of addresses? 

> When doing an order query I want to omit results for 2 particular email addresses.
> 
> It's easy enough to omit results for one address;
> 
> $order = Order::find()
>     ->isCompleted(true)
>     ->email('not email1@somedomain.com')
>     ->all();
> But how do I omit more than one email? If I pass an array using ['not', 'email1@somdomain.com', 'email2@otherdomain.com'] then an error is returned stating that email expects a string. For example, this doesn't work
> 
> $order = Order::find()
>         ->isCompleted(true)
>         ->email(['not', 'email1@somedomain.com', 'email2@otherdomain.com'])
>         ->all();
> Nor does passing in an array of addresses within the array
> 
> $order = Order::find()
>         ->isCompleted(true)
>         ->email(['not', ['email1@somedomain.com', 'email2@otherdomain.com']])
>         ->all();
> If I pass in 2 email criteria then only the latter is applied.

**Comment by lukeholder** [comment]
Thank you for bringing this to our attention.

A fix has been pushed and will be included in the next release.

To get this early, change your craftcms/commerce requirement in composer.json to:

"require": {
  "craftcms/commerce": "dev-develop#240102fefe8f2c2c2beac9299311cfdfd678e09b as 3.1.1",
  "...": "..."
}
Then run composer update.

Thanks.
