### ISSUE TITLE
Unable to take payment in Control Panel Orders (Commerce 3)

### ISSUE THREAD

**Issue by isjackwild** [craftcms/commerce#1362]
### Description
I'm trying out Craft Commerce 3 for the first time, and experimenting with the new create orders from the Control Panel feature.

When I try to take a payment from an order (using the manual gateway for now, but also tested with Dummy gateway) I receive an error message: _Email required to make payments on a completed order._ and payment fails.

I'm unsure as to what this error message refers. I have set up new order emails and the mailing adaptor, and checked it's working, and my customer has an email address added (which displays below the customer name in the Order Details tab)

### Steps to reproduce

1. Create order in back end
2. Add a user
3. Complete order
4. Attempt to take order payment

### Additional info

- Craft version: PRO 3.4.13
- PHP version: 7.3.10
- Database driver & version: MySQL 8.0.17
- Plugins & versions: Commerce  3.1.1
--

**Comment by lukeholder** [comment]
Do you have a customer set on the order?

**Comment by isjackwild** [comment]
Yes I do, and there’s an email address. It shows as a name with an email address below it on the first tab.

**Comment by nfourtythree** [comment]
Hi @isjackwild 

Thank you for bringing this to our attention.

A fix has been pushed and will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#3af8cacfcdf9a28797fcf2ef5e20d73a612001ef as 3.1.1",
  "...": "..."
}
```

Then run `composer update`.

Thanks.

**Comment by isjackwild** [comment]
Thanks mate — God you're quick! At the moment I was just playing around
with Commerce 3, so don't need an immediate update.

Have a nice day,
Jack.
