### ISSUE TITLE
Customer orders revealed through URL change

### ISSUE THREAD

**Issue by WonkoSVE** [craftcms/commerce#1364]
### Description

When testing my receipt, it was faster to load the template in browser and refresh. I noticed, though, that doing this would reveal previous orders in the system.

### Steps to reproduce

1. Create some orders.
2. Visit the URL for your receipt template.
3. Refresh the page to view a different completed order.

### Additional info

- Craft version: 3.4.13
- Commerce version: 3.1.1
- PHP version: PHP/7.2.27
- Database driver & version: mysqlnd 5.0.12

**Comment by nfourtythree** [comment]
Hi @WonkoSVE 

I am not sure I follow what the issue is here? Could you please elaborate on this?

It sounds like you are making a public template, which would be fine for testing. But you should make it a private template when using it as a PDF or email template.

Thanks

**Comment by WonkoSVE** [comment]
Ah, yes. My mistake. I have made it private and all is well.

Sorry for the trouble.
