### ISSUE TITLE
URL doesn't change after selecting All Orders from CP orders index

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1367]
### Description

While the URL is changed when selecting specific statuses from the orders index page, it is not changed when selecting All Orders, resulting in unexpected behavior when navigating between the orders index and order edit pages.

### Steps to reproduce

1. From orders index, select a specific order status, e.g. Shipped. URL changes to site.com/admin/commerce/orders/shipped.
2. Select All Orders. Note URL does not change back to site.com/admin/commerce/orders.
3. Click an order number to go to order edit page.
4. Navigate back in browser. Returns to site.com/admin/commerce/orders/shipped because that was the last URL navigated to, even though All Orders was the last selection being viewed.

### Additional info

- Craft version: 3.4.13
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.1.1

**Comment by lukeholder** [comment]
Confirmed not working for me too. Looking into a fix.

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for bringing this to our attention, we have pushed a fix that will be included in the next release.

Thanks.
