### ISSUE TITLE
Edit address form redirect not working

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1368]
### Description

Edit address form does not redirect to CP edit user page when accesses from the Customer Info tab.

### Steps to reproduce

1. From Customer Info tab on edit user page, click an address.
2. Edit address page opens with the edit user page URL in the redirect query param. Click Save.
3. Address saves and redirects to customer page instead of edit user page.

### Additional info

- Craft version: 3.4.13
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.1.1

**Comment by lukeholder** [comment]
Thank you for bringing this to our attention.

A fix has been pushed and will be included in the next release.

To get this early, change your craftcms/commerce requirement in composer.json to:

"require": {
  "craftcms/commerce": "dev-develop#eee0645336e273aef4f476214e67e17c975af8a8 as 3.1.1",
  "...": "..."
}
Then run composer update.

Thanks.
