### ISSUE TITLE
Potential bug with Coupon Code / Discounts

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#1372]
### Description
Coupon code in the JSON response is removed/deleted/nulled on page refresh. When I submit a coupon code via AJAX I get a response back with success true and I get couponcode name and discount amount etc. All is working there. But as mentioned it's cleared on refresh.

I have narrowed it down to happening if I got additional products in my basket which is not part of the product variants https://share.getcloudapp.com/L1u7GgRQ

### Steps to reproduce

1. Add 2 products to cart. 1 which is applicable and 1 which is not.
2. Submit coupon code via Ajax. See that it works 100%
3. Refresh browser with "CMD + R" and see that coupon is cleared and discount etc is gone

### Additional info

- Craft version: 3.4.15
- PHP version: 7.2
- Database driver & version:postgres
- Plugins & versions: Commerce 3.1.1

**Comment by nfourtythree** [comment]
Hi @philipboomy 

I have just tried this with a fresh install and the example templates and I was unable to reproduce this issue.

Following your steps, I got the correct ajax response and then when I refreshed the discount was there and was applied to the correct product.

Could there be anything else at play here? Custom code, other discounts conditions etc?

Thanks.

**Comment by philipboomy** [comment]
I can't replicate it now either. I thought I had found the issue due to the 2 different product yesterday but I tried that today but its working. Sorry if I wasted your time. I will close it for now.
