### ISSUE TITLE
In Commerce V2 I got the Shipping Method name back - Could you add in V3?

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#1373]
In V2 I managed to get Shipping Method name via an object I believe. Now I only get "shippingMethodHandle" back. Is it on purpose you removed that? Is it possible for you to add it back in?

I use it to show what shipping method has been chosen in a "overview" before paying.

Thanks

**Comment by keyurshah** [comment]
There’s an issue going on with postie as well, possibly related to this since postie code hasn’t changed

verbb/postie#27

**Comment by lukeholder** [comment]
@philipboomy Can you explain more about what you are calling and what you expect? Is this over ajax or in twig? We recently added `availableShippingMethodOptions` to the ajax JSON response if that helps.

**Comment by philipboomy** [comment]
@lukeholder Sure - I am calling cart/update-cart and I used to get in JSON the **selected** shippingMethodName back where as now I am only getting "shippingMethodHandle" back. This is unfortunate as I like to show to the visitor in a review summary (meaning outside off the radio buttons where visitor selects shipping method) what shipping method he/she chose earlier in "human readable format" e.g. Standard 2-3 Days" and not in code format e.g. "standard23Days".

Yes thanks about the "availableShippingMethodOptions" as I also use that. By the way is it on purpose that we also get "availableShippingMethods" back? "availableShippingMethodOptions" contains everything that "availableShippingMethods" contains but with the useful "price" as well.

**Comment by lukeholder** [comment]
You can get the shipping method name in the `availableShippingMethodOptions` 

`availableShippingMethods` is there for backwards compatibility we will remove it in future updates.

**Comment by philipboomy** [comment]
I would like to get back from I had before which was selected shippingMethodName. I only get selected shippingMethodHandle. It used to work. I am just wondering why remove it when it was there the first time. I have to adjust my code and loop through available shipping methods to see which one is equal to the selected shipping method handle and then get the selected shipping method name.

**Comment by keyurshah** [comment]
Agreed. It would be nice to save more data than just the shippingMethodHandle. 

As a bonus, It would be nice to save all the shipping method information into the snapshot as well so that information is available as well.
