### ISSUE TITLE
Issues with Edit button for order adjustments 

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1374]
### Description

The Edit button for order adjustments at the bottom of the main pane doesn't work before order is marked complete. When clicked the button disappears, but does not provide form to edit order adjustments. The Edit button is also visible when there are no order level adjustments.   

### Steps to reproduce

1. Create a new order. Add a line item, select combination of shipping and taxes that doesn't produce any adjustments at the order level, then update cart.
2. Note Edit button at bottom of main pane is visible even though there are no order adjustments.
3. Select shipping/tax that creates order adjustments, then update cart.
4. Click Edit button at bottom of main pane. Button disappears but does not create form to edit order adjustments.

### Additional info

- Craft version: 3.4.15
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.1.1

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for bringing this to our attention.

An update has been pushed to address this issue and will be included in the next release.

Thanks!
