### ISSUE TITLE
Busy class persists after cancelling Update Order Status action

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1375]
### Description

After cancelling an Update Order Status action, the table does not have the `busy` class removed and as a result user cannot access orders in table.

### Steps to reproduce

1. From order index page, select an order and click the Update Order Status action button.
2. Once modal appears, click Cancel button.
3. Table remains grayed out with spinner visible.

### Additional info

- Craft version: 3.4.15
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.1.1

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for this.

An update has been pushed and will be included in the next release.

Thanks.
