### ISSUE TITLE
hook "cp.commerce.product.edit.details" is rendered in the wrong place

### ISSUE THREAD

**Issue by khalwat** [craftcms/commerce#1376]
I was left this issue:

https://github.com/nystudio107/craft-seomatic/issues/599

The problem is actually in Commerce 3.1 here:

https://github.com/craftcms/commerce/blob/develop/src/templates/products/_edit.html#L236

Currently the code is:

```twig
    {% hook "cp.commerce.product.edit.details" %}
  </div>
```

The `hook` should appear _after_ the `</div>`:

```twig
  </div>
  {% hook "cp.commerce.product.edit.details" %}
```

Making this change caused the sidebar added by plugins to render properly.

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.

**Comment by aarmitage** [comment]
Are you able to revisit this please @lukeholder? Thanks!
