### ISSUE TITLE
Adding content and tabs to order view from a plugin

### ISSUE THREAD

**Issue by sjelfull** [craftcms/commerce#138]
It would be great if we could get additional control of the order details view.

Please consider the following:

- Template hooks for adding content to either start or end of any of the 3 tabs (Order Details, Transactions, Status History)
- Template hooks for adding content to either start or end of the sidebar
- Template hook for adding content beside the Save button
- Template hook for adding actions to the Save button context menu
- Event to add new tabs and tab content
- Event to access the HTML of the view, incase we want to do more advanced manipulation

**Comment by lukeholder** [comment]
After the order editing feature is released in 3.0 we can revisit this. Thanks.

**Comment by lukeholder** [comment]
Fixed for the next release:

Added the `cp.commerce.order.edit.order-actions`. and `cp.commerce.order.edit.order-secondary-actions` template hooks to the Edit Order page.

Added the ability to do most of what you are asking for custom tabs in https://github.com/craftcms/commerce/issues/1904#issuecomment-737066070
