### ISSUE TITLE
JQuery dependency for payment scripts

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1382]
### Description
It seems to me that javascript for third party payment libraries are injected into the payment templates upon loading.

For performance reasons, I am loading jquery at the end of my pages, so this results in the error below:

```
paymentForm.js?v=1586901159:5 Uncaught ReferenceError: $ is not defined
    at initPaypalCheckout 
```

The payment scripts are loading before jquery has loaded on my page.

Currently the example shop templates all load jquery at the top of the page, which is not ideal for performance.

It would be great if there was an option to load the javascript file myself.  (I am using loadjs to manage script loading and would prefer to load payment scripts after jquery has loaded).  

Any other ideas would be welcome.  

Currently it seems that all the shop template scripts require jquery, perhaps in the future, they can be vanilla javascript without any dependencies.

Thanks!

Craft Commerce 3.1.1

**Comment by lukeholder** [comment]
We are currently working on new example templates that do not require jQuery.

As for the `gateway.paymentFormHtml()` function this was designed for use in the control panel, but we allow people to use it on the front-end if it meets developers needs.

Developers are free to not use the function, and build their own payment HTML and  javascript. There is no requirement to use it -  thus there is no jQuery requirement from Craft Commerce that your front-end must use jQuery.

For most gateways, the html returned from this function (and javascript) is inspectable in the rendered page, and you are free to copy it, modify it, and use it in your templates. Having said that we should do a better job of documenting the output of this function in each gateway plugin's documentation so developers can do so more easily.
