### ISSUE TITLE
Unable to search by full name if fullName not set

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1385]
### Description

When searching orders from the order index page, any search for a full name will return nothing if the order addresses don't explicitly have `fullName` set. We use individual `firstName` and `lastName` fields for address creation, so searching for "Will" returns any name that contains Will, and "Smith" any name with Smith, but searching "Will Smith" returns nothing. Is it possible to bring back a computed value for `fullName` only when it is not set? Or would you recommend we run a `beforeSaveAddress` event to explicitly set `fullName` attribute? I understand that explicitly setting `fullName` is more reliable, but it was nice to have the flexibility of a fallback for things like searching and displaying Billing Full Name and Shipping Full Name in the orders index when `fullName` is not set.

### Additional info

- Craft version: Craft Pro 3.4.15
- PHP version: 7.4.4
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 3.1.1

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Unfortunately, there are some inherent problems with "computing" a full name. Things like know which order the names go in etc.

The best bet would be like you say to run code on before save to compute the full name field how you would like it.

Thanks.
