### ISSUE TITLE
3.0.11 to 3.0.12 upgrade breaks min/max qty discounts

### ISSUE THREAD

**Issue by timkelty** [craftcms/commerce#1389]
We have a "Buy 2, Get 1 Free", category based discount that was working fine until we upgraded to 3.1.

**UPDATE:**  I rolled back versions locally and actually figured out it seems to have been 3.0.12 that breaks things. 3.0.11 works fine, but bumping to 3.0.12 breaks it.

Immediately following the upgrade to 3.1, we are now seeing the following behavior:
- If you add 3 of the same shirt, the discount is applied appropriately
- In all other cases, the discount no longer works, including:
  - 3 of the same shirt, plus ANYTHING else in the cart (doesn't have to be a "shirt" category)
  - 2 of one shirt, 1 one of other, etc.

<img width="679" alt="Screen Shot 2020-04-17 at 7 40 13 AM" src="https://user-images.githubusercontent.com/18329/79565431-b6d70180-807e-11ea-8267-65ec414529e3.png">

<img width="803" alt="Screen Shot 2020-04-16 at 3 54 57 PM" src="https://user-images.githubusercontent.com/18329/79500898-33280100-7ffb-11ea-80b3-e0c9ec275947.png">

### Additional info

- Craft version: 3.4.15
- Commerce: 3.1.1

**Comment by nfourtythree** [comment]
Hi @timkelty 

Could you please provide the conditions that you are using on this discount

Thanks!

**Comment by timkelty** [comment]
@nfourtythree sorry, uploaded the wrong screenshot originally. Updated.

**Comment by timkelty** [comment]
@nfourtythree any update here? This has frozen us as 3.0.11 and were counting on things from 3.1.

**Comment by nfourtythree** [comment]
Hi @timkelty 

Thanks for the update, we have pushed a fix for this that will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#9d31bbf73ea1aacc1f4148f63a944a24bc575f81 as 3.1.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks.

**Comment by timkelty** [comment]
Running Commerce 3.1.3 this is _again_ happening!

As soon as I add any not matching the category from my min/max discounts, it removes the discount.

To reproduce:

- Add 3 of these to your cart: https://paddling-dev.fusionary.io/store/kayak-compass-tee/
- View the cart, see that the discount is applied: https://paddling-dev.fusionary.io/store/cart
- add anything not categorized shirt to your cart, like https://paddling-dev.fusionary.io/store/yakgrips/
- View the cart, see your discount is gone.

(╯°□°）╯︵ ┻━┻

**Comment by nfourtythree** [comment]
Hi @timkelty 

We have just pushed an update that should fix this issue.

This update will be included in the next release

To get this early, change your `craftcms/commerce` requirement in you project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#e15f51365a0afc44f19ef9422c22ebbeed505dd6 as 3.1.5",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by timkelty** [comment]
@nfourtythree 

Good news: the update fixes this issue

Bad news: Presumably, now that more discounts are matching, https://github.com/craftcms/commerce/issues/1323 is exacerbated and now adding to cart is slower than ever :(
