### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#139]
**MySQL 5.7.21**

When saving a product type with `Show the Dimensions and Weight fields for products of this type` unchecked, I get the following error.

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'hasDimensions' cannot be null The SQL being executed was: UPDATE craft_commerce_producttypes SET fieldLayoutId=642, variantFieldLayoutId=643, hasDimensions=NULL, hasVariants=1, hasVariantTitleField=NULL, dateUpdated='2018-03-23 18:36:18' WHERE id=2
```

If I check that checkbox, and then try to save the same product type, I get the following error:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'hasVariantTitleField' cannot be null The SQL being executed was: UPDATE craft_commerce_producttypes SET fieldLayoutId=642, variantFieldLayoutId=643, hasDimensions=1, hasVariants=1, hasVariantTitleField=NULL, dateUpdated='2018-03-23 18:37:37' WHERE id=2
```

Note that this error does not occur with **MySQL 5.6.38**

**Comment by lukeholder** [comment]
@davist11 Please do a `composer update` and let me know if the issue persists. Thanks.

**Comment by davist11** [comment]
If I uncheck the `Show the Title field for variants` checkbox, I still get 

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'hasVariantTitleField' cannot be null The SQL being executed was: UPDATE craft_commerce_producttypes SET fieldLayoutId=642, variantFieldLayoutId=643, hasDimensions=0, hasVariants=1, hasVariantTitleField=NULL, dateUpdated='2018-03-26 14:40:26' WHERE id=2
```

This is a product with multiple variants. Maybe related, but variant fields don't show up anymore

![screen shot 2018-03-26 at 10 41 09 am](https://user-images.githubusercontent.com/199985/37913158-3b63dc0a-30e2-11e8-9742-7fd76a52dbda.png)
![screen shot 2018-03-26 at 10 41 14 am](https://user-images.githubusercontent.com/199985/37913159-3b93fc82-30e2-11e8-8a47-38f2fb6a6543.png)

**Comment by davist11** [comment]
Seeing that same `Integrity constraint violation` error in lots of other places. When saving a product, if promotable isn't checked:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'promotable' cannot be null The SQL being executed was: UPDATE craft_commerce_products SET typeId=2, taxCategoryId=1, shippingCategoryId=1, promotable=NULL, freeShipping=NULL, defaultPrice='56', defaultHeight='0', defaultLength='0', defaultWidth='0', defaultWeight='0', dateUpdated='2018-03-26 15:28:15' WHERE id=1343
```

If I check promotable, then it complains about free shipping:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'freeShipping' cannot be null The SQL being executed was: UPDATE craft_commerce_products SET typeId=2, taxCategoryId=1, shippingCategoryId=1, promotable=1, freeShipping=NULL, defaultPrice='56', defaultHeight='0', defaultLength='0', defaultWidth='0', defaultWeight='0', dateUpdated='2018-03-26 15:29:04' WHERE id=1343
```

If I check free shipping and add a second variant (manually removing the hidden class that is referenced in #136):

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'isDefault' cannot be null The SQL being executed was: INSERT INTO craft_commerce_variants (id, productId, sku, price, width, height, length, weight, minQty, maxQty, stock, isDefault, sortOrder, hasUnlimitedStock, dateCreated, uid, dateUpdated) VALUES (1346, 1343, 'CAL86200', '226', '0', '0', '0', '0', NULL, NULL, 0, NULL, 1, 1, '2018-03-26 15:30:05', '68be0b94-47a9-403f-995b-3b9184197076', '2018-03-26 15:30:05')
```

**Comment by davist11** [comment]
Hey Luke, any update on this?

**Comment by lukeholder** [comment]
Hi @davist11 In the future can you make a new issue.

Can you `composer update` and see if they persist. What DB version are you using?

**Comment by davist11** [comment]
> In the future can you make a new issue.

Sure, sorry about that.

> Can you composer update and see if they persist. What DB version are you using?

Looks like the `promotable`, `freeShipping`, and `isDefault` errors are gone, but I'm still getting the error on `hasVariantTitleField` when editing a product type:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'hasVariantTitleField' cannot be null The SQL being executed was: UPDATE craft_commerce_producttypes SET fieldLayoutId=642, variantFieldLayoutId=643, hasDimensions=0, hasVariants=1, hasVariantTitleField=NULL, dateUpdated='2018-03-28 17:52:45' WHERE id=2
```

Using **MySQL 5.7.21**

**Comment by lukeholder** [comment]
OK `composer update` and see if that last one goes. Thanks.

**Comment by davist11** [comment]
Yup, that did it. Thanks
