### ISSUE TITLE
Adding a new site breaks product types project config sync

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#1390]
### Description

See error here, after having added a new site to the project: https://sentry.io/share/issue/1fa328ade9b64608aaf03396296c7bdf/

### Steps to reproduce

1. Add a new site to an existing project
2. Sync

### Additional info

- Craft version: 3.4.15
- PHP version: 7.4.4
- Database driver & version: PostgreSQL 11.7
- Plugins & versions: Commerce 3.1.2

**Comment by andris-sevcenko** [comment]
@boboldehampsink, of course, I forgot to tag this issue in the relevant commit.

Anyway, this has been resolved in 80240f4b434f71fb057be507f44110e9d3b7b1bd!

**Comment by boboldehampsink** [comment]
Thanks!
