### ISSUE TITLE
Available for Purchase doesn't save value

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1391]
### Description
When editing a product in the admin, disabling "Available to Purchase" does not change anything. 

Seems similar to this past issue: https://github.com/craftcms/commerce/issues/1113

I am using a custom branch due to a pending bug fix that hasn't been released yet

```
        "craftcms/commerce": "dev-develop#09f66725e201f28bb2b59c65afc374329c1c0952 as 3.1.1",
```

Is it due to the lines: 
https://github.com/craftcms/commerce/blob/b7671dd655eecebcd32940714243f43927b54a0a/src/elements/db/ProductQuery.php#L529-L535

Thanks.

### Steps to reproduce

1. Change commerce branch to a custom dev-develop branch
2. Change Available to Purchae setting of item in admin and save

**Comment by keyurshah** [comment]
When looking in the database values, it seems to save the setting, but does not change the front end display in the admin. It shows 0 for availableForPurchase in the database but shows enabled (green) in the admin.

**Comment by boboldehampsink** [comment]
That is because composer doesn't set the right version, even though you're using an alias.

**Comment by lukeholder** [comment]
@keyurshah please update to 3.1.2 proper and this should fix the issue. Thanks.
