### ISSUE TITLE
Link to customer from order edit page

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1397]
### Enhancement

In the new order edit page layout, it would be nice if the customer email address at the top of the main pane linked to either the CP customer page or user page, depending on whether they have created an account or not. Currently does not link to anywhere and would be nice to have a way to quickly reference a customer's other orders.

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for your suggestion. We have pushed an update for this that will be included in the next release.

Thanks!
