### ISSUE TITLE
Shipping Adjustment (and likely others) fail on `included` NULL constraint

### ISSUE THREAD

**Issue by efatsi** [craftcms/commerce#140]
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'included' cannot be null
The SQL being executed was: INSERT INTO `craft_commerce_orderadjustments` (`name`, `type`, `description`, `amount`, `included`, `orderId`, `lineItemId`, `sourceSnapshot`, `dateCreated`, `uid`, `dateUpdated`) VALUES ('FedEx Ground', 'shipping', '', '0', NULL, ....
```

Looks like the `included` attribute is defaulting app-side to NULL (bummer it doesn't pull from DB default). Setting `$adjustment->included = false;` in [Shipping::_createAdjustment](https://github.com/craftcms/commerce/blob/develop/src/adjusters/Shipping.php#L133-L145) seems to do the trick.

**Comment by efatsi** [comment]
Huh, scanned through the migrations directory here, doesn't look like there's anything that explicitly defines a NOT NULL constraint on `included`. Perhaps this is a holdover from upgrading from Craft 2?

Happy to throw a PR together if you're alright with adding `->included = false` to all Adjustment instantiations. Not sure if you'd rather have a default value set in the Adjustment model class though.

**Comment by lukeholder** [comment]
Thanks for reporting, I have set included to false by default on all new order adjustment models. Let me know if that fixes it for you.

**Comment by efatsi** [comment]
Looks great, thanks!
