### ISSUE TITLE
Allow decimal in Flat Amount offer

### ISSUE THREAD

**Issue by RichardJong** [craftcms/commerce#1400]
### Description
Allow decimals in Flat amount offer (baseDiscount)

### Steps to reproduce
1. Add new discount
2. Go to tab 'Actions'
3. Enter 3,5 (or 3.5) in baseDiscount field
4. View your newly added discount
5. Discount is 35 instead of 3,5

### Fix
Make baseDiscount field type "text" instead of "number"

**Comment by nfourtythree** [comment]
Hi @nfourtythree 

Thank you for pointing this out.

We have pushed a fix for this that will be included in the next release.

Thanks.
