### ISSUE TITLE
Validate Date/Time field on an Order

### ISSUE THREAD

**Issue by malinky** [craftcms/commerce#1404]
### Description

I'm trying to validate a custom date/time field on an order. The validator runs but throws the following error.

`DateTime::createFromFormat() expects parameter 2 to be string, object given` in `validators/DateValidator.php` the `parseDateValuePHP($value, $format)` method.

Instead of the $value property being the $date property from DateTime object the whole object is being passed.

The data is submitted from the form using the following input.

`<input type="hidden" name="fields[orderDeliveryDate]" value="2020-04-23">`

This is my code to add the validation rule to the order model.

```
Event::on(
    Order::class,
    Order::EVENT_DEFINE_RULES,
    function(DefineRulesEvent $event) {
        $event->rules[] = [['orderDeliveryDate'], 'date', 'format' => 'php:Y-m-d'];
    }
);
```

I'm not sure if I'm missing something in how I've set things up. I have other custom fields validating correctly just not the Date/Time.

### Additional info

- Craft version: 3.4.13
- PHP version: 7.35
- Database driver & version: mysql 8.0.12
- Plugins & versions: Commerce 3.10

**Comment by lukeholder** [comment]
Is `orderDeliveryDate` a date field on the order or just a plain text field?

**Comment by malinky** [comment]
Yes it's set up as a date / time field from the control panel and the field is saved in a datetime column on the content table.

**Comment by lukeholder** [comment]
So what are you trying to do with your validator?

**Comment by malinky** [comment]
My checkout has a calendar to select the delivery date and I wanted to ensure the date was valid and in the correct format.

**Comment by lukeholder** [comment]
Ah on the front-end.

`$event->rules[] = [['orderDeliveryDate'], \craft\validators\DateTimeValidator::class];`

This will take intro account if it is a date object already or a string date being passed in.

**Comment by lukeholder** [comment]
Also see: https://docs.craftcms.com/v3/date-time-fields.html#templating

**Comment by malinky** [comment]
Thanks very much Luke. That's also pointed me in the right direction for a custom validator I'll need for blocking off certain delivery dates.
