### ISSUE TITLE
"Total" columns broken after 3.0.11 -> 3.1 upgrade

### ISSUE THREAD

**Issue by timkelty** [craftcms/commerce#1405]
3.0.11 (shows totals for items, discounts, shipping and total price):
![image](https://user-images.githubusercontent.com/18329/80107573-3c5c2500-8549-11ea-8776-05b56f22d4b8.png)

3.1.3:
Only item total shows up (green box). When other columns are added, they are all $0.00
![image (1)](https://user-images.githubusercontent.com/18329/80107629-5269e580-8549-11ea-89a9-6d50fe67fd76.png)

Note that the data all appears to be valid…the csv export as the correct data.

**Comment by timkelty** [comment]
Just deployed 3.1.3 and the Totals column seems to be back as it was 🤷‍♀️

**Comment by lukeholder** [comment]
Yeah I couldn't reproduce, but glad it is working for you now.
