### ISSUE TITLE
Copy Shipping/Billing address button on edit address

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#1412]
I don't know if this is a bug or not but it would be great to be able to select the billing address the same as the just added shipping address. Currently once i've added a new shipping address, the select billing address modal is empty.

**Comment by nfourtythree** [comment]
Hi @samuelbirch 

When you add a new address on the Order edit screen it is not saved until the order is updated. This is done to avoid saving a lot of potential "junk" data.

Will update this issue to be a feature request to add a "Copy Billing/Shipping address" in the respective address dropdowns. As I think that would be useful.

Thanks!

**Comment by nfourtythree** [comment]
Hi @samuelbirch 

We have just pushed an update for this which will be included in the next release.

Thanks!

**Comment by samuelbirch** [comment]
Thanks @nfourtythree
