### ISSUE TITLE
Products not showing up in the CP Add Line Item list.

### ISSUE THREAD

**Issue by smockensturm** [craftcms/commerce#1413]
### Description
Products created and added by a module do not show up in the CP Add Line Item list. The item count shows many more than are visible. Searching for an invisible line item will display them though.

### Steps to reproduce

1. Create / Add a product like so:

https://craftcms.stackexchange.com/a/29743/4097

2. Try to add it to an order in the CP

### Additional info

- Craft version: Craft Pro 3.4.15
- PHP version: 7.1.33
- Database driver & version: MariaDB 10.2.30 / mySQL 5.5.5
- Plugins & versions: Commerce 3.1.3 [TRIAL]

<img width="402" alt="Screen Shot 2020-04-26 at 7 30 09 PM" src="https://user-images.githubusercontent.com/6586518/80322827-86693300-87f5-11ea-9f74-adfab1551027.png">

<img width="350" alt="Screen Shot 2020-04-26 at 7 30 27 PM" src="https://user-images.githubusercontent.com/6586518/80322829-8701c980-87f5-11ea-8daf-f1d8a8de4899.png">

**Comment by nfourtythree** [comment]
Hi @smockensturm 

I have just tried this and I am unable to replicate your issue.

Here is the code I used

![](https://p191.p3.n0.cdn.getcloudapp.com/items/jkulD7GB/Screenshot%202020-04-27%20at%2007.37.45.png?v=58a0476728e0af57a59b3d38b80396ab)

And [here is a video](https://x.n43.me/BluZ1g8D) showing me navigating to the newly created product.

Could you check that you have set up an "Order description format" for your product type?

Thanks.

**Comment by smockensturm** [comment]
The product type is **Clothing**.  It is the example type created by Commerce installation There was no "Order description format". So I add one. No difference.

The table `commerce_variants` is probably full of trash. What are the consequences of deleting rows from that table marked `deletedWithProduct`?

**Comment by smockensturm** [comment]
Hey. This is sorted. As suspected, table rows got a little screwy in development. Keeping those proper is key, no doubt. Thanks for your time.
