### ISSUE TITLE
Shipping Methods changes order on save

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#1420]
### Description
When I save a shipping method (if changed) then it changes the order which changes the order returned in the API.

https://share.getcloudapp.com/wbu0wdoN

### Steps to reproduce

1. Change the first/top shipping method
2. Save
3. See that its no longer first/top

### Additional info

- Craft version: 3.4.17.1
- Craft Commerce version: 3.1.3

**Comment by nfourtythree** [comment]
Hi @philipboomy 

I was unable to replicate this issue: [see video](https://x.n43.me/Jrubnvrd)

Do you happen to have any custom code running in a module or plugin?

In theory, they are just returned in `id` order, so as long as the `id` isn't changing they should stay in the same order.

Thanks.

**Comment by nfourtythree** [comment]
Hi

I am closing this issue as we are unable to replicate it and haven't received any further information.

If there are further notes please reply to this issue and we can look into it.

Thanks.
