### ISSUE TITLE
User group not visible after updating primary billing / shipping address

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1421]
### Description

After updating a customer's primary billing or shipping address from their CP edit user page, their user group is no longer selected under the Permissions tab.

### Steps to reproduce

1. From CP edit user page, select the *Customer Info* tab.
2. Select an address and click *Set as Primary Billing* from the actions menu.
3. Select the *Permissions* tab. All user group checkboxes are blank. Reloading the page shows the groups selected for that user.

### Additional info

- Craft version: Pro 3.4.17.1
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce Pro 3.1.3

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for bringing this to our attention. We have pushed up a fix to solve this and it will be included in the next release.

To get this early, change your `craftcms/commmerce` requirement in you project's `composer.json` to:

```json
"require": {
  "craftcms/commmerce": "dev-develop#a272781cc244b5dd311c6853e168c19e6a0a3c9e as 3.1.3",
  "...": "..."
}
```

Then run `composer update`.

Thanks.
