### ISSUE TITLE
Consolidate customer orders on user activation

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1423]
### Description

Seeing an issue pop up where customers are placing an order, then deciding to create an account after the fact. However, after they activate and log in they are unable to view their previous orders because they haven't been consolidated. Would be nice to run order consolidation for a new user's email on successful activation.

### Additional info

- Craft version: Pro 3.4.17.1
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce Pro 3.1.3

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for pointing this out, we have pushed an update to address this.

It will be included in the next release.

Thanks!
