### ISSUE TITLE
CP Create/Edit order permission

### ISSUE THREAD

**Issue by Floriswijgergangs** [craftcms/commerce#1424]
Currently it's only possible to create orders with products when user is to admin. Would be nice if there is a permission setting to let customer-support create a new order from the CP. If they click 'new order' they can't select products.

![image](https://user-images.githubusercontent.com/8255580/80786829-0d673400-8b85-11ea-95da-aad46b56ba20.png)

### Additional info

- Craft version: 3.4 / 3.1.3
- PHP version: 7.3
- Database driver & version: Mysql 5.7

**Comment by nfourtythree** [comment]
Hi @Floriswijgergangs 

Thank you for highlighting this, it was a bug with the the "Edit Order" permission.

A fix has been pushed for this and will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#a377045b7623a8e07cf0f35deb793d45e8be1281 as 3.1.3",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
