### ISSUE TITLE
Emoji in address notes breaks

### ISSUE THREAD

**Issue by sjelfull** [craftcms/commerce#1426]
### Description

A fair amount of customers adds emojis to their notes, breaking anywhere a address is being saved.

As an aside, would it be a good idea to add a new behaviour so that you can make the emoji cleanup universal for model attributes where users are likely to add emojis?

```sql
General error: 1366 Incorrect string value: '\xF0\x9F\x98\x89' for column 'notes' at row 1 The SQL being executed was: UPDATE `craft_commerce_addresses` SET `firstName`='xx', `lastName`='xx', `address1`='xx', 
```

### Steps to reproduce

1. Add emoji to customer notes when saving a address/updating a card
2. Profit

**Comment by sjelfull** [comment]
@lukeholder Is this an easy fix? I'm seeing a fair amount of customers every day trying this, and my experience from other sites is the same: people like their emojis.

**Comment by lukeholder** [comment]
We will be invalidating an address field that has an emoji submitted, and in the case of the address note, we will support converting emojis to shortcodes like we do for lines item notes. Will be in the release out early next week.

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
