### ISSUE TITLE
Admin Panel hangs when viewing Orders

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1428]
### Description
Hello,

When I click on Orders, and the admin panel tries to load `All Orders` the page will sometimes load in 2-3 seconds and usually it just hangs and nothing loads at all. But rarely does it load right away.

![image](https://user-images.githubusercontent.com/744385/80818168-90898980-8b87-11ea-9352-6edfc1208c63.png)

I don't get that issue when browsing Categories or Active Carts. 

I don't see any console errors and the database is not running at full capacity at the time.

Thanks.

### Steps to reproduce

1. Login to Admin
2. View `All Orders` in Orders Page

### Additional info

- Craft Commerce: 3.1.3

**Comment by lukeholder** [comment]
Do you have many orders or columns enabled? Sounds like a performance issue - or do you get an error eventually?

**Comment by keyurshah** [comment]
I have about 400 orders  and customers in the database but around 100,000 users

The columns are

* Order Number
* Date Ordered
* Email
* Total
* Shipping Method

Thank You

**Comment by keyurshah** [comment]
I tested with the columns displayed and it seems it works fine until I display the column `Shipping Method`. Then the slowdown occurs.

**Comment by nfourtythree** [comment]
Hi @keyurshah 

Thank you for your response. We believe this is fixed in the latest version of Commerce.

Happy to re-open if you are stilling having issues.

Thanks!
