### ISSUE TITLE
Updating existing address during update-cart does not work

### ISSUE THREAD

**Issue by Mosnar** [craftcms/commerce#1429]
### Description
During my checkout flow, the customer enters an address and it's saved via update-cart. If the customer returns to that step later and attempts to change this address, the address will not be saved. There are no validation errors or errors otherwise; it simply will not save.

My code is roughly this:

```twig
<form method="post">
    {{ actionInput('commerce/cart/update-cart') }}
    {{ csrfInput() }}
    {% set address = cart.shippingAddress %}
    {% if address and address.id %}
        {{ hiddenInput('shippingAddress[id]', address.id) }}
    {% endif %}
    {% include 'store/_partials/addressFields.twig' with {
        modelName: 'shippingAddress',
        address: address,
        showEmail: true
    } %}
    {{ redirectInput('store/checkout/billing') }}
     <button type="submit">Submit</button>
</form>
```

I've stepped through the code and verified that the updated address model does indeed get stored on the _cart; however, at some point, it's reverted back to the original. My hunch is it has something to do with the initial call to _getCart the updateCart action makes. This call forces the cart to save, during which the original addresses are also resaved.

`CartController.php:79`
```php
$this->_cart = $this->_getCart(true);
```

### Additional info

- Craft version: 3.4.17.1 Pro
- Commerce version: 3.1.3 Pro
- PHP version: 7.3.13
- Database driver & version: MySQL 8.0.19
- Plugins & versions:
  - Postie 2.1.4
  - Avatax 2.1.0

### Related
https://github.com/craftcms/commerce/issues/1349#issuecomment-607666948

**Comment by nfourtythree** [comment]
Hi @Mosnar 

My guess here is that the addresses in the cart have the same ID. 

When that is the case the billing address takes precedence in terms of updating. This means that the code you have will unfortunately not update the shipping address as the billing is overriding it.

If you update the code to the following you could get this working:

```twig
{% set address = cart.shippingAddress %}
{% set model = cart.shippingAddress.id == cart.billingAddress.id ? 'billingAddress' : 'shippingAddress' %}

<form method="post">
  {{ actionInput('commerce/cart/update-cart') }}
  {{ csrfInput() }}
  {% if address and address.id %}
    {{ hiddenInput(model ~ '[id]', address.id) }}
  {% endif %}
  {% include 'store/_partials/addressFields.twig' with {
    modelName: model,
    address: address,
    showEmail: true
  } %}
  {{ redirectInput('store/checkout/billing') }}
  <button type="submit">Submit</button>
</form>
```

Going to get the docs updated to make sure this is clearer for people.

Hope this helps.

Thanks

**Comment by Mosnar** [comment]
@nfourtythree Works! thanks!
