### ISSUE TITLE
Support ENV variables in Commerce Emails->Recipient

### ISSUE THREAD

**Issue by circa1977** [craftcms/commerce#1430]
### Description

We have a Sales Notification email for every order that comes in, and we use project config. I cannot change the Recipient field for this email without it changing project.yaml. I'd like to specify a different set of email recipients in my dev environment.

**Comment by lukeholder** [comment]
Since this field supports twig, you can do: 

```twig
{{ parseEnv('MY_ENV_VAR_NAME_HERE') }}
```

https://docs.craftcms.com/v3/dev/functions.html#parseenv

**Comment by circa1977** [comment]
I see the following in queue.log when I use that:

```
2020-05-04 10:53:36 [-][1][-][error][craft\commerce\services\Emails::sendEmail] Email template parse error for custom email “Sales Notification” in “To:”. Order: “8ee2442”. Template error: “Address in mailbox given [SALES_EMAIL_NOTIFY] does not comply with RFC 2822, 3.6.2.”
```

I have the following in my .env:

```
SALES_EMAIL_NOTIFY="user@email.com"
```

**Comment by circa1977** [comment]
I attempted to work around that error by setting the Custom Recipient field to an address that should get the emails in all environments, and setting the twig `parseEnv` tag in the CC field.* This also resulted in the same error.

* This is not ideal, as the live website should be emailing my client's address as the recipient, not a CC. What I need is:

1. LIVE: The full set of email recipients
2. STAGING: The subset of email recipients that might be testing on staging
3. DEV: Just my email address, so I'm not bombarding everyone's inbox every time I work on something

If I update the field in the CP to just use my address in dev, it updates `project.yaml` and that goes live if I don't remember to set it back, breaking the email workflow for new orders.

**Comment by nfourtythree** [comment]
Hi @circa1977 

Our apologies there was a typo in the example, it should have been

`{{ parseEnv('$MY_ENV_VAR_NAME_HERE') }}` notice the `$`.

Have now updated the original comment too.

Thanks.

**Comment by joepagan** [comment]
Is it possible for Commerce to just be consistent with Craft's email settings fields in a future release which does use env vars? 

Don't the Craft email setting fields suggest to use env variables directly on those field's descriptions? so it would be reasonable to expect Commerce to behave the same? 

Seems silly for everyone to try that and end up here "why the heck isn't my env var working"

Appreciate the description suggests twig is possible but that doesn't mean an env var wouldn't necessarily work too.
