### ISSUE TITLE
No Update Order Status option

### ISSUE THREAD

**Issue by circa1977** [craftcms/commerce#1433]
### Description

I do not see the documented Update Order Status action on my edit Order screen or the Orders screen.

### Additional info

- Craft version: 3.4.17.1
- PHP version:
- Database driver & version:
- Plugins & versions:
Commerce: 3.1.3

**Comment by nfourtythree** [comment]
Hi @circa1977 

Order Statuses only show on the edit order page for completed orders.

Is it a completed order you are looking at?

Thanks.

**Comment by circa1977** [comment]
Hi, @nfourtythree!

OK, I do see the action in the Orders list now. I don't know why I didn't see that before.

![Screen Shot 2020-05-07 at 10 22 09 AM](https://user-images.githubusercontent.com/49657/81305830-caa5d000-904c-11ea-9a3d-7845437ae006.png)

> Order Statuses only show on the edit order page for completed orders.

> Is it a completed order you are looking at?

Isn't completed just an out of the box status?

From the docs:

> An order’s status can be changed on the Edit Order Page in the control panel. Choosing “Update Order Status” will present you with a modal window that allows the selection of the new status and a message associated with the change.

The docs imply that I can move an order through a sequence of statuses, with Completed as the final step.

> For example you may use default status of “Received”, set when the order is completed. Once you’ve packaged the order for shipment, you might update to “Packed” status. Or if you’re waiting to receive product stock you might use a “Pending Stock” status. When you’ve shipped the order you might set the status to “Completed”. Every year you might change all “Completed” orders to an “Archived” status.

Shouldn't I be able to do that on the edit order page? That's my context when reviewing the order, capturing payment, getting a delivery address, etc.

![Screen Shot 2020-05-07 at 10 26 11 AM](https://user-images.githubusercontent.com/49657/81306735-cfb74f00-904d-11ea-9cd8-48afd6cda097.png)

I've never seen Update Order Status on the edit order page because we've never used Status:Completed. But it seems that we should be able to update the status when working with an individual order. In our case, we only authorize payments and then we capture payments after reviewing the order. That means we have the order open in edit mode. At that point, we'd like to update the order status to Paid. (Ideally I'd like to hook into Capture to update the order status. See https://github.com/craftcms/commerce-stripe/issues/109)

**Comment by nfourtythree** [comment]
Hi

Sorry my question about completed order was meant to be phrase more a: you can’t change the order status on a cart. 

In the screenshot you sent. If you click edit that will put the order in edit mode and you will be able change the status you see in the sidebar. 

Hope this helps

**Comment by circa1977** [comment]
OK, that makes sense. I was looking for something that explicitly said “Update Order Status” on the Edit Order page, rather than activating edit mode for the order. I've updated order statuses as you've described. Thanks!
