### ISSUE TITLE
Updating order/cart from CP duplicates saved addresses

### ISSUE THREAD

**Issue by ryanmwc** [craftcms/commerce#1435]
### Description

I have an active cart with a billing and shipping address already saved to it. If I navigate to the order in the CP and click "Update Order" (regardless of whether I change any values or not), the two addresses get re-added to my customer account.

### Steps to reproduce

1) Create an active cart and attach your user account to it as the customer.  Make sure you have some addresses saved already and attach those as the billing and shipping addresses.  Press "Update Cart".

<img width="1214" alt="cart" src="https://user-images.githubusercontent.com/59359516/81055360-d1a3d580-8ec8-11ea-9ea2-6cd3d2506f15.png">

2) Go to your account and view your addresses. You should see the addresses you already had saved get recreated and added.

<img width="1205" alt="customer-addresses" src="https://user-images.githubusercontent.com/59359516/81055595-50990e00-8ec9-11ea-876e-18755106e69e.png">

### Additional info

- Craft version: 3.4.16
- Commerce version: 3.1.3
- PHP version: 7.3.9

**Comment by nfourtythree** [comment]
Hi @ryanmwc 

Thank you for bringing this to our attention.

We have pushed an update that should fix this issue, it will be included in the next release.

Thanks.
