### ISSUE TITLE
"Remove Address" in active cart via CP doesn't work

### ISSUE THREAD

**Issue by ryanmwc** [craftcms/commerce#1436]
### Description

In an active cart, if I click "Remove address" from either the billing or the shipping address's dropdown, nothing happens.

<img width="1212" alt="remove-address" src="https://user-images.githubusercontent.com/59359516/81056511-f13bfd80-8eca-11ea-8c95-f7197ed88208.png">

### Steps to reproduce

1. Create a cart.
2. Add addresses to the cart and save.
3. Refresh the page and try to remove the addresses from the cart in the CP.

### Additional info

- Craft version: 3.4.16
- Commerce version: 3.1.3
- PHP version: 7.3.9

**Comment by nfourtythree** [comment]
Hi @ryanmwc 

Thank you for bringing this to our attention. We have pushed an update to fix this issue.

The update will be included in the next release.

Thanks!
