### ISSUE TITLE
Product title missing from edit order when clicking Add line item in cpanel

### ISSUE THREAD

**Issue by celexus** [craftcms/commerce#1437]
### Description
While editing an existing order, clicking on Add a line item shows a list of products in the product catalog but the titles of the products are not included in the list, so using the Search facility to try and locate the product by name doesn't return anything

### Steps to reproduce

1. Click on an existing order from the list under Commerce > Orders in the Cpanel 
2. Click on the Edit link in the bottom left hand corner 
3. Click on the Add a line item button 

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.2.30
- Database driver & version: MySQL 5.5.5
- Craft Commerce: 3.1.3

**Comment by nfourtythree** [comment]
Hi @celexus 

This sounds like a duplication of #1307 

Could you please try the things outlined in [this comment](https://github.com/craftcms/commerce/issues/1307#issuecomment-591508559)

Thanks!

**Comment by lukeholder** [comment]
Running `./craft resave/products` will fix this.
