### ISSUE TITLE
Order status badge counts seem incorrect - possibly including deleted orders

### ISSUE THREAD

**Issue by mposborne** [craftcms/commerce#1438]
### Description
Our order status badge counts are not correct, mainly just the "new" status.

See below our 'new' badge count is 36 but only 10 orders are shown:
<img width="517" alt="Screen Shot 2020-05-06 at 1 57 57 PM" src="https://user-images.githubusercontent.com/1559892/81132265-e3a57700-8fa1-11ea-9f2a-6dabfbdc1faf.png">

Looking at our web.log I can see that the query to get the badge counts has a LEFT JOIN between commerce_orders table and elements table. So this means that any orders previously deleted will still get counted. If I change the join to an INNER JOIN then the counts are correct.

I have searched and only found this issue from a year ago which seems similar, but says it was fixed at the time: https://github.com/craftcms/commerce/issues/852

### Steps to reproduce
Haven't tested this process myself but I assume:

1. Delete an order under "new" status
2. See if badge count remains the same, i.e. still includes the deleted order, or not

### Additional info
PHP version 7.3.17
MySQL 5.5.5
Craft Pro 3.4.12
Craft Commerce 3.1.3

**Comment by nfourtythree** [comment]
Hi @mposborne 

I have just tried this locally and I can't seem to replicate the issue you raised.

Here is a video of what happens for me: https://x.n43.me/eDu6XeG5

The code checks that `dateDeleted` is `null` to avoid showing it in the count: https://github.com/craftcms/commerce/blob/develop/src/services/OrderStatuses.php#L180-L187

It seems like there might be something else going on here. Could you send your `composer.json`, `composer.lock` and a DB backup to support@craftcms.com and we can look into it.

Thanks.

**Comment by mposborne** [comment]
Hi, thanks for the response! Actually, i've done some more digging now and have another theory on what's happened.

Currently I have 2 orders with a status of "new". But the badge count is 28.

If I run the query 
```
SELECT o.id, o.reference, e.dateDeleted, e.uid
FROM commerce_orders o 
LEFT JOIN elements e ON o.id = e.id
WHERE o.isCompleted = true AND e.dateDeleted IS NULL AND o.orderStatusId = 1
```
I get 28 records returned:
```
127.0.0.1/rawessentials/commerce_orders/		http://db.dev.96black.co.nz/tbl_sql.php?db=rawessentials&table=commerce_orders&sql_query=SELECT+o.id%2C+o.reference%2C+e.dateDeleted%2C+e.uid%0D%0AFROM+commerce_orders+o+%0D%0ALEFT+JOIN+elements+e+ON+o.id+%3D+e.id%0D%0AWHERE+o.isCompleted+%3D+true+AND+e.dateDeleted+IS+NULL+AND+o.orderStatusId+%3D+1&show_query=1#querybox

    
                
        
        
        Your browser has phpMyAdmin configuration for this domain. Would you like to import it for current session?        
        Yes
        / No
        / Delete settings 
    


 Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available. 

 Showing rows 0 - 27 (28 total, Query took 0.0007 seconds.)

SELECT o.id, o.reference, e.dateDeleted, e.uid
FROM commerce_orders o 
LEFT JOIN elements e ON o.id = e.id
WHERE o.isCompleted = true AND e.dateDeleted IS NULL AND o.orderStatusId = 1


id	reference	dateDeleted	uid	
381	566fd93	NULL	NULL	
385	95a374b	NULL	NULL	
423	c124978	NULL	NULL	
492	9acdcdd	NULL	NULL	
4456	31fa41d	NULL	NULL	
5719	3663649	NULL	NULL	
5731	e573d81	NULL	NULL	
6150	0463bbf	NULL	NULL	
6153	269cce1	NULL	NULL	
6155	4cf837c	NULL	NULL	
6207	bbcc906	NULL	NULL	
6209	9df01e4	NULL	NULL	
6210	a2a24c8	NULL	NULL	
6213	e44e146	NULL	NULL	
6214	e1ddf76	NULL	NULL	
6215	399a240	NULL	NULL	
6216	9f9b751	NULL	NULL	
6217	9a3143d	NULL	NULL	
6218	a69443a	NULL	NULL	
6219	605d20a	NULL	NULL	
6220	4af6533	NULL	NULL	
6222	99c52bd	NULL	NULL	
6224	9724662	NULL	NULL	
6226	991553a	NULL	NULL	
6424	1deaab5	NULL	NULL	
6472	a485ac4	NULL	NULL	
12284	6b64cb9	NULL	593d47b9-1c41-4695-859e-f83f358ff59f	
12422	987a09d	NULL	0470fe1d-10b5-4c56-821c-58bd09a60200	
```

Note only the last 2 actually have UID's. The other 26 do NOT have element records that exist.

I note also that the 26 orders without element records are all orders from over 1 month ago. I believe i've seen it somewhere that soft deletes get removed from Craft after 30 days. Is that right? And therefore, is the problem that order elements are being removed after 30 days, but not the associated orders? That would explain why we haven't noticed this issue until now as we only launched our store approximately 30 days ago.

**Comment by nfourtythree** [comment]
Hi @mposborne 

I have just tested the deletion and garbage collection and everything seems to be working correctly.

We can get the query updated, however, it seems you are facing a data integrity issue here. 

I am unsure how these orphaned records have come to be. If they do not have corresponding records in the `elements` or `content` table you are safe to remove them.

Hope this helps.

Thanks!
