### ISSUE TITLE
Download PDF in admin not working

### ISSUE THREAD

**Issue by kevadamson** [craftcms/commerce#1439]
### Description

Download PDF on an order page in admin not working. Nothing happens on click.
The button HTML is just `<a target="_blank" class="btn">Download PDF</a>` and also `<a target="_blank" role="option" tabindex="-1" id="null-option-0">Download PDF</a>`

### Steps to reproduce

1. /admin/commerce/orders/xxxxxx

### Additional info

- Craft version: Craft Pro 3.4.18
- PHP version: 7.1.21
- Database driver & version: MySQL 5.5.55
- Plugins & versions:

Analytics 4.0.10
Control Panel Body Classes 2.2.0
Control Panel CSS 2.2.1
Craft Commerce 3.1.3
Feed Me 4.2.2
Field Manager 2.1.5
Guest Entries 2.3.0
Hero to Craft3 Migrator 1.0.1
Instant Analytics 1.1.7
Logs 3.0.3
PayPal for Craft Commerce 2.1.0.1
Redactor 2.6.1
Room volume calculator 1.0.0
Sage Pay for Craft Commerce  2.1.0.3
SEOMate 1.1.4
Super Table 2.4.9
Tags 1.0.7
Trending Posts 1.0.1
Typogrify 1.1.18
Wheel Form 2.4.2

**Comment by nfourtythree** [comment]
Hi @kevadamson 

Do you get any JavaScript errors on that page?

Could you check your "Order PDF Template" settings in `Commerce > System Settings > General Settings`

![](https://p191.p3.n0.cdn.getcloudapp.com/items/v1uDOnxb/Image%202020-05-07%20at%201.10.20%20pm.png?v=41e6c9e248d9de4d88f2509a480c1f59)

One reason that it might not be showing is that the setting isn't filled out or that the template does not exist.

Thanks.

**Comment by kevadamson** [comment]
Will check. Seemed to stop working when updated Craft/Commerce.

**Comment by kevadamson** [comment]
Strange. Was set as pdf and not pdfs in the path. Not sure how / why it got changed, but hay-ho :)

**Comment by nfourtythree** [comment]
Glad it is sorted!
