### ISSUE TITLE
Unknown column error on trying to select products from a promotion entry

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/commerce#144]
On trying to add a new sale, and selecting a product to limit the sale to, no products load. On inspection of the request, it occurs that there's a SQL error:

`{"error":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'commerce_products.typeId' in 'where clause'\nThe SQL being executed was: SELECT 'elements'.'id', 'elements'.'fieldLayoutId', 'elements'.'uid', 'elements'.'enabled', 'elements'.'archived', 'elements'.'dateCreated', 'elements'.'dateUpdated', 'elements_sites'.'slug', 'elements_sites'.'uri', 'elements_sites'.'enabled' AS 'enabledForSite', 'commerce_variants'.'id', 'commerce_variants'.'productId', 'commerce_variants'.'isDefault', 'commerce_variants'.'sku', 'commerce_variants'.'price', 'commerce_variants'.'sortOrder', 'commerce_variants'.'width', 'commerce_variants'.'height', 'commerce_variants'.'length', 'commerce_variants'.'weight', 'commerce_variants'.'stock', 'commerce_variants'.'hasUnlimitedStock', 'commerce_variants'.'minQty', 'commerce_variants'.'maxQty', 'content'.'id' AS 'contentId', 'content'.'title', 'content'.'field_shortDescription', 'content'.'field_extendedDescription'\nFROM (SELECT 'elements'.'id' AS 'elementsId', 'elements_sites'.'id' AS 'elementsSitesId', 'content'.'id' AS 'contentId'\nFROM 'craft_elements' 'elements'\nINNER JOIN 'craft_commerce_variants' 'commerce_variants' ON 'commerce_variants'.'id' = 'elements'.'id'\nINNER JOIN 'craft_elements_sites' 'elements_sites' ON 'elements_sites'.'elementId' = 'elements'.'id'\nINNER JOIN 'craft_content' 'content' ON 'content'.'elementId' = 'elements'.'id'\nWHERE ('commerce_products'.'typeId' = '2') AND ('elements_sites'.'siteId'='2') AND ('content'.'siteId'='2') AND ('elements'.'archived'=FALSE) AND ('elements_sites'.'enabled'=TRUE)\nORDER BY 'title'\nLIMIT 50) 'subquery'\nINNER JOIN 'craft_commerce_variants' 'commerce_variants' ON 'commerce_variants'.'id' = 'subquery'.'elementsId'\nINNER JOIN 'craft_elements' 'elements' ON 'elements'.'id' = 'subquery'.'elementsId'\nINNER JOIN 'craft_elements_sites' 'elements_sites' ON 'elements_sites'.'id' = 'subquery'.'elementsSitesId'\nINNER JOIN 'craft_content' 'content' ON 'content'.'id' = 'subquery'.'contentId'\nORDER BY 'title'"}`

**Comment by lukeholder** [comment]
Thanks for reporting, please `composer update` to pull in the fixes.
