### ISSUE TITLE
Stripe based make a payment form is cut off

### ISSUE THREAD

**Issue by keithmancuso** [craftcms/commerce#1441]
### Description
When you create an order in the backend in and go to make a payment the stripe fields take a few second to initialize but when they do they are cut off in the view and you can even scroll to access them. 

The temporary workaround is to dismiss the modal and then click make a payment again and it loads fine

When you first click it
![CleanShot 2020-05-06 at 10 25 50@2x](https://user-images.githubusercontent.com/275913/81188980-045ed400-8f84-11ea-9b36-c54422750522.png)

On the second click
![CleanShot 2020-05-06 at 10 25 17@2x](https://user-images.githubusercontent.com/275913/81188893-ed1fe680-8f83-11ea-9739-289f64f57655.png)

### Steps to reproduce

1. Start a new order in the backend
2. add a customer and product to it
3. go to the transactions tab and click make a payment and see cut off form
4. dismiss the modal and click make a payment again to see the full form

### Additional info

- Craft version: 3.4.17.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by nfourtythree** [comment]
Hi @keithmancuso 

Thank you for bringing this to our attention.

We have pushed a fix for this that will be included in the next release.

Thanks!
