### ISSUE TITLE
Add form builder (JSON form schema) for line item options

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#1448]
Add the ability to define a JSON form schema for products to allow the easy generation of forms, both on the front-end and in the control panel.

**Comment by AugustMiller** [comment]
This would be brilliant!

In the interim, being able to enter JSON in the LineItem options modal would be super helpful… I see that it's detected automatically from values created via other means (front-end / custom modules), but new data entered via the modal is only interpreted as a string.

**Comment by lukeholder** [comment]
Closing this in favour of doing this: https://github.com/craftcms/commerce/issues/1448

It can then be up to the purchasable to allow extending the options attribute definitions.

**Comment by joshangell** [comment]
@lukeholder I’m guessing you mean #1805 ?

**Comment by lukeholder** [comment]
Oops thanks.
