### ISSUE TITLE
Feature Request: Standardize on variants interface

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#145]
Even if a product type doesn't have multiple variants, it feels weird to have the standard variant fields (SKU, Price, Stock, Allowed Qty) in the sidebar instead of the variants tab. To me, it makes sense to still be able to add variant fields to a product type without multiple variants, you just wouldn't be able to add more than one.

**Comment by lukeholder** [comment]
Thank you for the request. 

We feel to leave things as they are at the moment for the following reasons:

1) Having a 'Variants' or 'Variant' tab doesn't really make sense for customers as the word 'variant' itself implies more than one.

2) We plan to make more customizable field layouts at the Craft core level in the future which Commerce can make use of. This would include positioning 'non-custom' element attribute like variants.

We hope to migrate all feature requests from uservoice (https://craftcms.uservoice.com/forums/295386-commerce/filters/top) into github, so encourage you to vote there now before we migrate.

I will go ahead and close this issue. Thanks.
