### ISSUE TITLE
Double printing of name in addresses is confusing / slows order scanning

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1458]
**Description**

If the fullname matches the firstname + lastname, it would be tidier/more compact - and ease of reading is very important in order processing - if the name was just printed once:

![image](https://user-images.githubusercontent.com/731309/82518900-b6d98e00-9b63-11ea-9f46-a0d35f57bf8b.png)

(Happens for both billing and shipping)

**Comment by nfourtythree** [comment]
Hi @bossanova808 

As you pointed out this is due to you having data in `firstName` + `lastName` fields and the `fullName` field.

We are looking to introduce an "address format" setting #1305 that will allow you to have greater control over how this is displayed in the future.

Thanks.
