### ISSUE TITLE
Custom shipping methods can not be chosing when creating a new order

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1459]
**Description**

We have a (quite complex) custom shipping calculator.  In Commerce 1, our shipping methods came up in the control panel etc.  This went away in Commerce 2.

Now that we're at Commerce 3 and can create orders, this presents a pretty big problem/lack - because we're unable to select a shipping method, or calculate a shipping cost, when entering orders in the control panel.

All we get is:

![image](https://user-images.githubusercontent.com/731309/82519488-2ac86600-9b65-11ea-8b7d-bdf9fa690492.png)

..and that means we pretty much can't use the new create orders interface, which is a huge shame.

Would love to see a solution here as having this would really help us!

**Comment by nfourtythree** [comment]
Hey @bossanova808 

I have just tried to replicate this with a custom shipping method and I can get it to show.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/jkuQ2WOb/Screenshot%202020-06-01%20at%2017.13.08.png?v=b577eaaecc50e27722c9a4057d3051b1)

Could you send an example of your shipping method class to support@craftcms.com so we can have a look to see what might be going on.

Thanks!

**Comment by bossanova808** [comment]
Thanks, have just sent it.  (Needed to use a file sending service cause your helpdesk thing is a little strict - won't accept .js etc - kinda funny for a helpdesk for a CMA ;) !

**Comment by nfourtythree** [comment]
Tidying this up. 

Was an issue caused by something in the custom shipping module.
