### ISSUE TITLE
CP Order consistent currency formatting

### ISSUE THREAD

**Issue by rbrv** [craftcms/commerce#1463]
**Description**
Inconsistent currency formatting in the control panel, mixing a format without decimals and one with 4(!) decimals.

**To Reproduce**
How, and what happened?
1. In the CP, go to an order detail, to the `Transactions` tab
2.Currencies in columns `Amount` and `Payment amount` are formatted differently, which is quite confusing.

**Additional context**
In the order overview, order amount are displayed in yet another format (2 decimals).

![Screenshot 2020-05-23 at 15 55 35](https://user-images.githubusercontent.com/43676281/82732541-28554000-9d0e-11ea-91b4-1a3371d77504.png)

![Screenshot 2020-05-23 at 15 58 25](https://user-images.githubusercontent.com/43676281/82732565-491d9580-9d0e-11ea-8900-929a6bebc3c0.png)

**Comment by lukeholder** [comment]
Thanks this has been fixed for the next release.
