### ISSUE TITLE
Before & After Events added to update cart

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/commerce#1464]
**What are you trying to do?**
There's currently know way to make updates to as cart after an update has happened. It looks like the only event that is triggered once a cart has been updated is `EVENT_POPULATE_LINE_ITEM`

**What's your proposed solution?**
Adding 2 events to the cart controller e.g. Before and After would allow further tweaks to a cart after an update has happened.

**Additional context**
What I need this for is grouped promotions. E.g. if someone buys 3 items from a specific range they get those items for a set price and each cart item is discounted accordingly.

**Comment by ryanmwc** [comment]
@mediabeastnz Maybe I'm misunderstanding something, but couldn't you use the `EVENT_BEFORE_SAVE` and `EVENT_AFTER_SAVE` events since a cart is really an incomplete `Order` element, and all elements have before and after save events?

```
use craft\events\ModelEvent;
use craft\commerce\elements\Order;
use craft\helpers\ElementHelper;
use yii\base\Event;

Event::on(
    Order::class,
    Order::EVENT_BEFORE_SAVE,
    function(ModelEvent $event) {
        // the element is not new if it's just a draft
        if (ElementHelper::isDraftOrRevision($event->sender)) {
            return;
        }

        /* @var $order Order */
        $order = $event->sender;
        $isNew = $event->isNew;

        if ($order->isCompleted) {
            return;
        }

        // do something to the cart
    }
);

**Comment by mediabeastnz** [comment]
Yeah you're probably right @ryanmwc, I actually ended up using a custom Adjuster for my particular use case anyways.

I just thought there's a lot going on in that Update cart function that it might benefit from a few hooks.

**Comment by lukeholder** [comment]
If you can give some good use-cases for these events, I will re-open the ticket.
