### ISSUE TITLE
Transaction detail shows "undefined" many times.

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/commerce#1467]
**Description**

When viewing the rows on the "Transactions" tab of a specific order and upon clicking the "i" icon for more info, the popup shows "undefined" many times.

![image](https://user-images.githubusercontent.com/39988088/82894679-dea56900-9f4a-11ea-8c17-4278b1068638.png)

**To Reproduce**

Unknown: Orders in the past have been OK and shown details, I have not seen this before in other environments or in live.

**Expected behavior**

Detail of interactions with payment gateway shown.

**Additional info**
- Craft version: 3.4.18
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.30
- Plugins & versions: 

Amazon S3	1.2.7
Asset Rev	6.0.2
CP Field Inspect	1.1.3
Craft Commerce	3.1.3
Digital Download	2.1.5
Digital Products	2.4.0
Dumper	2.0.0
Imager	v2.4.0
Inlin	2.1.1
Logs	3.0.3
Minify	1.2.10
Navigation	1.3.14
PayPal for Craft Commerce	2.1.0.1
Redactor	2.6.1
SEOmatic	3.3.2
Stripe for Craft Commerce	2.3.0
Template Select	2.0.2
Wordsmith	3.2.0
Worldpay for Craft Commerce	2.1.0.2

**Additional context**

This occurred in a live environment when using the Pixel & Tonic Stripe Payment gateway. Checking the order within the Stripe control panel shows it worked but in this case, only after the first card submitted was declined due to insufficient funds. The subsequent attempt worked. 

When clicking the icon for either of the transactions, they both show as the screen shot.

No errors logged to the browser console, nothing obvious in the log files.

**Comment by rob-baker-ar** [comment]
To add a little more, I cannot include it here as it contains sensitive information (as this is a live transaction) but checking the response JSON in the commerce_transactions table for this order looks no different to orders that are showing their history detail correctly.

**Comment by lukeholder** [comment]
> checking the response JSON in the commerce_transactions table for this order looks no different to orders that are showing their history detail correctly.

Not sure what you mean by that, can you email the JSON to support@craftcms.com ?

**Comment by rob-baker-ar** [comment]
The JSON response from Stripe is kept in the commerce_transactions table in the `response` column. Structurally speaking, it looks no different to other responses on other rows from other transactions. Looking at the content of JSON, it **seems** this is where the data comes from that should be showing in the screen shot above.

I will pull the relevant responses out, redact sensitive stuff and send on today. Thank you.

**Comment by nfourtythree** [comment]
Hi @rob-baker-ar 

Thank you for sending the data to support it was really helpful in tracking this issue down.

We have just pushed a fix for this that will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in you project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#16947ec2e6863296af957633895fa92e7b8d0ea2 as 3.1.5",
  "...": "..."
}
```

Then run `composer update`.

Thanks.
