### ISSUE TITLE
Custom twig method in zip code condition not running

### ISSUE THREAD

**Issue by Tam** [craftcms/commerce#1468]
**Description**
I'm trying to use a custom twig method (i.e. `craft.b.checkPostcode(zipCode)`) in the zip code condition to make it easier for us to manage what zip codes can access the shipping method. The function returns either a PHP boolean true or false. However, when testing I can't get the method to even fire (by adding an info log in the method) and the testing request always fails (no errors returned or in the log / debug view). I've tested the method outside of the condition box and it is working as expected.

**To Reproduce**
1. Create a shipping method with a Zip Code Condition Formula that uses a custom twig method.
2. Test the zip code condition.

**Expected behavior**
The test should return successful on certain zip codes.

**Additional info**
- Craft version: Craft Pro 3.4.20
- Commerce version: 3.1.4
- PHP version: 7.3.9
- Database driver & version: MySQL 5.5.5

**Comment by lukeholder** [comment]
@tam the zipCode condition formula does not support normal twig code that would run in the templates, it only supports a subset of twig code that is designed to be used in an expression. This means the `craft` variable is not available, only the `zipCode` string to match against.

What logic is in your checkPostCode method?

**Comment by Tam** [comment]
@lukeholder we’ve got some custom logic that allows us to define local delivery slot times to certain postcodes. checkPostcode just checks the delivery address postcode against the available local delivery slot postcodes (so we only show the local delivery method if they’re in the catchment area).

**Comment by lukeholder** [comment]
Sorry, for now we are not allowing custom PHP logic in this condition formula. It is simply for matching a `zipCode` string. In the future we have plans for a more advanced condition builder than can be extended by plugins (PHP) and could be used in shipping zones. You can track this here: https://github.com/craftcms/commerce/issues/80
