### ISSUE TITLE
Shipping and billing addresses not set in Order returned by getCart() if it didn't already exist in the DB

### ISSUE THREAD

**Issue by benface** [craftcms/commerce#1476]
**Description**
I am logged in and the Commerce customer associated with my Craft user has a primary shipping address as well as a primary billing address. So, when I call `Commerce::getInstance()->getCarts()->getCart()`, I expect the returned Order to have the `shippingAddressId` and `billingAddressId` properties set to those addresses. However, if I don't already have an Order saved in the DB (empty `commerce_orders` table), the Order's `shippingAddressId` and `billingAddressId` properties are `null`, and even saved in the DB as `null` if I pass `true` to `getCart()`. Only when the Order is already saved in the DB does `getCart()` return an Order with the expected `shippingAddressId` and `billingAddressId`.

**To Reproduce**
1. Ensure you are logged in as a customer that has a primary shipping address and a primary billing address.
2. Truncate the `commerce_orders` table.
3. In a controller action, call `Commerce::getInstance()->getCarts()->getCart(true)` and nothing else.
4. Look in the `commerce_orders` table. Notice that the Order that was created has `shippingAddressId` and `billingAddressId` set to `null`.
5. Run the controller action again.
6.  Look in the `commerce_orders` table again. Notice that the Order now has `shippingAddressId` and `billingAddressId` set to the customer's `primaryShippingAddressId` and `primaryBillingAddressId` respectively.

**Expected behavior**
At step 4, the `shippingAddressId` and `billingAddressId` should be set to the customer's `primaryShippingAddressId` and `primaryBillingAddressId` respectively.

**Additional info**
- Craft version: 3.4.20
- Commerce version: 3.1.5
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26

**Comment by nfourtythree** [comment]
Hi @benface 

A fix for this was pushed for this in the `3.1.6` release.

Thanks.
