### ISSUE TITLE
Ability to use the same address for shipping and billing when creating order in the CP

### ISSUE THREAD

**Issue by benface** [craftcms/commerce#1477]
**What are you trying to do?**
When the shipping and billing addresses of an order are the same, the order creation UI in the CP allows us to "Copy" one to the other, but that creates a new address record in the database. It would be nice to have the ability to use the same address record for both shipping and billing, to prevent duplicate data.

**What's your proposed solution?**
A checkbox in the shipping address area that says "Same as billing". When checked, the whole shipping address dropdown (with "Edit address", "Select address", etc.) would be disabled.

**Comment by nfourtythree** [comment]
Hi @benface 

Thank you for your input.

To avoid any issues in the future life of the order the addresses are stored separately once an order is completed. This is to make sure there is an accurate representation of the order at all times and also if someone is to edit it in the future.

We have added the ability to copy one address to the other to make store administrator lives easier. This gives the ability to edit in one place, also edits on an address for a customer can be made through the customer portion of the control panel if the edits are something that will be permanent.

With all of the above, we are not currently looking to make your suggestion a feature.

Thanks.
