### ISSUE TITLE
Add the 'Show title field' switch for products

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/commerce#148]
I'm working on a site where I would like to give products a title, based on their field's content. Is this not (yet) possible, or am I missing something?

Additional request #185

- [ ] Solve #244 at the same time.

**Comment by lukeholder** [comment]
Yes, that is reasonable to add to commerce. Will need to add this to the post 4/42018 todo list. Will leave this ticket open.

**Comment by terryupton** [comment]
+1 for this feature. Have the exact same requirement now. Thought I would comment here rather than add a new ticket. Is this something still on the agenda @lukeholder ?

**Comment by CC-DP** [comment]
Looking to have this feature as well!

**Comment by sm9** [comment]
+1, as per this Craft Stack Exchange post: https://craftcms.stackexchange.com/questions/18808/how-to-auto-generate-a-craft-commerce-product-title/

**Comment by toddpadwick** [comment]
This is definitely something we could really do with. We'd want to concatenate {brandName}-{productName} into the title as both of those fields are displayed separately on the front end. for example:

**Rolex**
_Submariner 14060_

This would have a title and slug as `rolex-submariner-14060`

**Comment by lukeholder** [comment]
Will be in the upcoming Commerce 3.2
