### ISSUE TITLE
Can't save any orders in the CP (missing customer id?)

### ISSUE THREAD

**Issue by Mathias-Syversen** [craftcms/commerce#1484]
Craft CMS 3.4.20
Craft Commerce 3.1.5

See this issue about missing customer id's: #1483

After struggling with missing customers on orders I now also have a problem where I cannot save any order in the CP. The save button is disabled.

From what I can see in the source code this button is disabled if customer is missing from the order. But the button is disabled on all orders, those who came in with customer id, and those who are missing one.

![1](https://user-images.githubusercontent.com/53942798/83408009-2e37d900-a412-11ea-9e74-4a13e82a3e36.jpg)

As you can see on the picture above, the button is disabled. But on the picture below you see the order has a customer, and this example is an order that never "failed". It had an customer from the start.

![2](https://user-images.githubusercontent.com/53942798/83408005-2d9f4280-a412-11ea-9c4a-59daea3944ee.jpg)

**Comment by nfourtythree** [comment]
Hi @Mathias-Syversen 

Could I ask, does the order have both a shipping and billing address?

Thanks.

**Comment by Mathias-Syversen** [comment]
Hi,

It does not. The orders only have a shippingAddress

**Comment by nfourtythree** [comment]
Hi @Mathias-Syversen 

To save an order or cart on the edit order page both billing and shipping addresses are required.

Thanks!

**Comment by Mathias-Syversen** [comment]
Hi @nfourtythree 
The config requireBillingAddressAtCheckout is set to false, and we set no billing address during checkout. Craft cant possibly demand this in the CP?

Editing has worked fine up until Commerce 3.4.1

**Comment by nfourtythree** [comment]
Hi @Mathias-Syversen 

The `requireBillingAddressAtCheckout` is only currently used during the payment action.

We have however made an update that will be included in the next release that will fix this issue for you and allow saving of a cart/order with or without addresses.

Thanks!
