### ISSUE TITLE
Addresses are getting attached to cart with no information

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1486]
**Description**
I'm seeing customers have an address saved to their profile but the address information is blank in the system. It's as if an addressId is being assigned to their profile, and then it shows blank in the database for any fields.

In the database, I see blank rows as well. This happened after an update to 3.1.6

![image](https://user-images.githubusercontent.com/744385/83560523-3ef85580-a4cb-11ea-8c48-330f19c70fed.png)

What's the best way to check  in the system that the customer has a filled out shipping address?

**To Reproduce**
How, and what happened?
- not sure exactly how this is happening. 
  - the person had reset their password earlier so not sure if it happened at that point or later.
- but there are many addresses in the commerce_addresses table now with blank information. There were not any before the update to 3.1.6

![image](https://user-images.githubusercontent.com/744385/83566678-3efd5300-a4d5-11ea-8091-e6001a9d3e45.png)

**Expected behavior**
What did you expect to happen?
To not have a shipping profile attached to their cart until an address was saved.

**Additional info**
- Craft Commerce: 3.1.6

**Comment by keyurshah** [comment]
does it have anything to do with this commit? 

https://github.com/craftcms/commerce/commit/0982926858ade6ace4c6a2c8bba2dbb50be16aa4

**Comment by keyurshah** [comment]
Is there a way to downgrade to 3.1.5 until this is sorted? I tried doing so but got an error saying the schema version was a mismatch in project config

**Comment by lukeholder** [comment]
@keyurshah Will get a fix out in the next couple hours.

**Comment by brandonkelly** [comment]
We just released Commerce 3.1.8 with this fix.
