### ISSUE TITLE
cart.shippingMethod returns matching shipping method but cart.shippingMethodHandle returns null

### ISSUE THREAD

**Issue by benface** [craftcms/commerce#1489]
**To Reproduce**
1. Ensure that the current cart has no shipping method set on it, but that at least one exists that would match the shipping address (and it is enabled).
2. In Twig: `{% set cart = craft.commerce.carts.cart %}`
3. After this line of code, if you do `{% set shippingMethod = cart.shippingMethod %}`, notice `shippingMethod` is set to the first (or cheapest?) shipping method that matches, even though it's not actually set on the cart.
4. But if you do `{% set shippingMethodHandle = cart.shippingMethodHandle %}` instead, notice `shippingMethodHandle` is `null`.
5. Strangely, if you do `{% set shippingMethod = cart.shippingMethod %}` and THEN `{% set shippingMethodHandle = cart.shippingMethodHandle %}`, `shippingMethodHandle` is now set to the `shippingMethod.handle`.

**Expected behavior**
Not exactly sure, but either `shippingMethod` should return `null` at step 3, or `shippingMethodHandle` should NOT return `null` at step 4. I would say the former makes the most sense to me.

**Additional info**
- Craft version: 3.4.22.1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Commerce version: 3.1.7

**Additional context**

**Comment by nfourtythree** [comment]
Hi @benface 

Thank you for raising the issue.

We are looking at [improvements on this process in the future](https://github.com/craftcms/commerce/issues/1494) however the solution will likely involve a breaking change of some description. This means that it will not be implemented until there is a major release.

For the moment if you want to check if shipping has been set on a cart you should check the state of `shippingMethodHandle`. This will let you know whether something has been set specifically or automatically.

Hope this helps, thanks.

**Comment by benface** [comment]
> For the moment if you want to check if shipping has been set on a cart you should check the state of shippingMethodHandle. This will let you know whether something has been set specifically or automatically.

Unless `shippingMethod` has been "checked" first, right? So to be clear, assuming I'm not accessing `shippingMethod` ever, if `shippingMethodHandle` is set and not `null`, it means a shipping method has been set specifically (not automatically), right?

**Comment by nfourtythree** [comment]
Hi @benface 

Correct, if `getShippingMethod()` hasn’t been called. 

Thanks.
