### ISSUE TITLE
Dashboard widgets reports/charts includes deleted orders

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#1490]
**Description**
Dashboard widgets reports/charts includes data from deleted orders. After running garbage collection the numbers are correct however in my opinion the the reports should not included deleted orders regardless of garbage collection.

**Comment by nfourtythree** [comment]
Hi @philipboomy 

Thank you for bringing this to our attention.

We have pushed up a fix for this and it will be included in the next release.

Thanks!

**Comment by brandonkelly** [comment]
We just released Commerce 3.1.8 with this fix.
