### ISSUE TITLE
LineItem order in Cart

### ISSUE THREAD

**Issue by sarahschuetz** [craftcms/commerce#1496]
**Description**
LineItems in the cart are in descending order according to their creation date. This is fine as long as you use serve-rside rendered templates. However, we build our checkout using Vue.js and update our products based on the response of the `commerce/cart/update` request.

When adding a new item to a cart with previous added products, the response has a lineItems array where all old items are in descending order according to their creation date. The new item is pushed to the end of the array and therefore displayed as the last product.
When the cart is updated again (for example by changing an amount) the newest item ist now also part of the underlying database query and as such ordered to the front of the array, which is causing our products to reorder.

**Expected behavior**
Either productItems should be ordered in ascending order by default or new lineItems should be added to the beginning of the array instead of pushing it to the end. I would expect the `commerce/cart/update` request to always return the lineItem array in the same order no matter if I am adding a product or updating one.

**Comment by nfourtythree** [comment]
Hi @sarahschuetz 

Thank you for bringing this to our attention.

We have pushed a fix for this which will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in you project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#5bae5251135ba9ba20dac281acc0763dae59fe3c as 3.1.8",
  "...": "..."
}
```

Then run `composer update`.

Thanks.

**Comment by sarahschuetz** [comment]
Thanks for fixing the issue so quickly!
