### ISSUE TITLE
Cache Order Statuses in the component

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1497]
**What are you trying to do?**
I would like to fetch many orders and their statuses at once, so it would be nice if you could cache order statuses in your component

**What's your proposed solution?**
Cache your Order statuses, all you need to do is to include a `$this->_orderStatuses = $orderStatuses` here
https://github.com/craftcms/commerce/blob/develop/src/services/OrderStatuses.php#L90

```PHP
    public function getAllOrderStatuses($withTrashed = false): array
    {
        // Get the caches items if we have them cached, and the request is for non-trashed items
        if ($this->_orderStatuses !== null) {
            return $this->_orderStatuses;
        }

        $results = $this->_createOrderStatusesQuery($withTrashed)->all();
        $orderStatuses = [];

        foreach ($results as $row) {
            $orderStatuses[] = new OrderStatus($row);
        }

        $this->_orderStatuses = $orderStatuses // new line

        return $orderStatuses;
    }
```

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#97c1142d85d3f0fef455e6822f11508f31d447c0 as 3.1.8",
  "...": "..."
}
```

Then run `composer update`.
