### ISSUE TITLE
Tax Category removal causes error

### ISSUE THREAD

**Issue by thegodshatetexas** [craftcms/commerce#1499]
**Description**
Navigation to `/admin/commerce/store-settings/tax` after deleting the only tax category produces the following error: `Trying to get property 'id' of non-object`

![Screen Shot 2020-06-10 at 2 31 47 PM](https://user-images.githubusercontent.com/881593/84310359-20c3d280-ab27-11ea-8352-400d718163b8.png)

**To Reproduce**
How, and what happened?
1. In the CP go to Commerce -> Store Settings -> Tax
2. Remove general tax category

**Expected behavior**
I expected to be able to add a new tax category when none existed

**Additional info**
- Craft version: 3.4.23
- PHP version: 7.4.6
- Database driver & version: MySQL 5.7.30
- Plugins & versions: 

<table class="data fullwidth fixed-layout" dir="ltr">
  <tbody>
    <tr>
      <th class="light">Amazon S3</th>
      <td>1.2.8</td>
    </tr>
    <tr>
      <th class="light">Copy</th>
      <td>1.0.0-RC11</td>
    </tr>
    <tr>
      <th class="light">Craft Commerce</th>
      <td>3.1.7</td>
    </tr>
    <tr>
      <th class="light">Date Range Field</th>
      <td>2.1.0</td>
    </tr>
    <tr>
      <th class="light">Feed Me</th>
      <td>4.2.3</td>
    </tr>
    <tr>
      <th class="light">Reasons</th>
      <td>2.1.1</td>
    </tr>
    <tr>
      <th class="light">Redactor</th>
      <td>2.6.1</td>
    </tr>
    <tr>
      <th class="light">Redactor Tweaks</th>
      <td>2.0.4</td>
    </tr>
    <tr>
      <th class="light">Super Table</th>
      <td>2.4.9</td>
    </tr>
    <tr>
      <th class="light">Typed link field</th>
      <td>1.0.23</td>
    </tr>
  </tbody>
</table>

**Additional context**
- General was the only tax category that I had before removal.
- Local dev hosting is being done through Nitro.

**Comment by nfourtythree** [comment]
Hi @thegodshatetexas 

Thank you for raising this issue. We have pushed an update that should stop this from happening. In the update, it is also now possible to change the default tax category from the listing page.

This will all be included in the next Commerce release.

Thanks!
