### ISSUE TITLE
Add a method to remove an adjuster from a LineItem

### ISSUE THREAD

**Issue by ryanmwc** [craftcms/commerce#1501]
**What are you trying to do?**
I want to be able to loop through adjusters on a `LineItem` and remove one. I posted [a ticket here in StackExchange](https://craftcms.stackexchange.com/questions/35546/commerce-remove-tax-adjuster-from-line-item-in-plugin) and asked several times on Discord, but got no solutions.

**What's your proposed solution?**
I see a `getAdjustments()` method in the `LineItem` model but not a `setAdjustments()` method or something like `removeAdjustmentById()`. It doesn't appear there's any method to do this or a way to remove an adjuster from an array set on the line item.  

I tried doing this with the `LineItems::EVENT_BEFORE_SAVE_LINE_ITEM` event as demonstrated on StackExchange. Several people mentioned using the [`OrderAdjustments::EVENT_REGISTER_ORDER_ADJUSTERS`](https://docs.craftcms.com/commerce/v3/adjusters.html#replace-an-adjuster), but when I `dd` the `$event->types` array, it provides me nothing to work with:
```
[
    0 => 'craft\\commerce\\adjusters\\Shipping'
    1 => 'craft\\commerce\\adjusters\\Discount'
    2 => 'craft\\commerce\\adjusters\\Tax' 
]
```

**Additional context**
I notice that in the CP you are able to manually remove an adjuster, but it's done asynchronously through JS and I can't track down the code that's doing it.

<img width="805" alt="Screen Shot 2020-06-09 at 4 57 13 PM" src="https://user-images.githubusercontent.com/59359516/84418949-2ea55080-ac18-11ea-9a65-1e5b36f8f573.png">

If this is already possible to do in my own plugin, please share the solution here and I'll follow through with it on StackExchange if it works.

**Comment by nfourtythree** [comment]
Hi @ryanmwc 

I have posted a solution over on stack exchange on how this can be achieved.

Thanks!
