### ISSUE TITLE
Automatic SKU Format: SKU field missing

### ISSUE THREAD

**Issue by bartrylant** [craftcms/commerce#1502]
**Description**
When you tick "Automatic SKU Format" in the product type settings, it hides the SKU field altogether. The description says: "What the unique auto-generated SKUs should look like, when a SKU field is submitted without a value."
It now works as auto generated entry titles, but that's not what the description says it does. I would think it should do this:

- Always show the SKU field
- Only when the SKU field is not filled in, it should be propagated with whatever is set in the settings.

Use case: I have a client that has a lot of products with SKU codes, but some without. She always fills in the SKU fields, but in case there is no SKU provided, I just want to fill the field with a random number (`{{ random(0000000000001,9999999999999)}}`). So I want to show the SKU field so she can fill it when she has an sku number, but if the doesn't fill in the field, it should be filled with a random number. The way it is now, is that setting random as a field value automatically removes the SKU field.

**Comment by nfourtythree** [comment]
Hi @bartrylant 

Thank you for your message.

Your use case of creating a random SKU is definitely not particularly common. The auto SKU format field is designed to be used for people that piece together the SKU based on static strings and data from custom fields on the product and variant.

Therefore the field is hidden initially for new variants so store administrators don't accidentally fill out this information and overwrite the format. 

After it has been saved the field will show up and at that point, it can be edited and will not be overridden by the SKU format.

I agree that we should maybe look at the wording when setting up the product type to make this a bit clearer.

Thanks.
