### ISSUE TITLE
Error editing an order when a line item's purchasable has been deleted

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#1504]
**Description**
An error occurs when recalculating an order that has a line item with a deleted purchasbale.

**To Reproduce**
1. Create an order and complete it
2. Delete a product/variant related to one of the line items
3. Try to edit the order (e.g. change qty on a line item)

**Expected behavior**
Recalculation as normal.

**Comment by joshangell** [comment]
Terrible hack I used to fix this for my project was to change line 1216 of `src/controllers/OrdersController.php` to:

```
if ($purchasableId && $purchasable = Craft::$app->getElements()->getElementById($purchasableId)) {
```

I could then edit as normal, save the order and revert the file change ...

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#c1299c15292f41c728fd9c8e2ab5094bf8ea0e5d as 3.1.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by joshangell** [comment]
Ahh wonderful, thanks both!
