### ISSUE TITLE
Disable checkboxes for unavailable SKUs in CP order edit page

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1505]
**What are you trying to do?**
Currently on CP order edit pages when **Add a line item** is in use, all SKUs (including those that are not available) have checkboxes that can be selected. As a result, a user can select an unavailable item and click *Add*, at which point the *Add a line item** interface closes.

**What's your proposed solution?**
Disabling checkboxes for unavailable SKUs would help avoid confusion by preventing users from even trying to add them to the cart.

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for your suggestion. This functionality will be updated on the completion of a feature update in craft itself. craftcms/cms#6223

We will continue to post updates here, you can also follow along with that issue.

Thanks.
