### ISSUE TITLE
Control panel discount not working with plugin’s order adjustment

### ISSUE THREAD

**Issue by jameslindeman** [craftcms/commerce#1506]
**Description**
A discount set via the control panel does not seem to take into account the adjusted price from a plugin’s OrderAdjustment. 

**To Reproduce**
1. In the CP go to Commerce > Promotions > Discounts and add a new discount
2. Under Actions set ‘Per Item Percentage Off’ to be a percent (say 50%) off the discounted item price and save.
3. For the plugin, register the adjuster to run first. I did that like this:
```
Event::on(
	OrderAdjustments::class,
	OrderAdjustments::EVENT_REGISTER_ORDER_ADJUSTERS,
	function(RegisterComponentTypesEvent $event) {
	    array_unshift($event->types, AnotherDiscount::class);
	}
);
```
4. For the adjuster itself, take another 50% off all items. For example:
```
public function adjust(Order $order): array {

	$adjustments = [];
	$lineItems = $order->getLineItems();

	foreach ($lineItems as $item) {

		$adjustment = new OrderAdjustment;
		$adjustment->type = 'discount';
		$adjustment->name = 'Another Discount';
		$adjustment->sourceSnapshot = [ 'data' => 'value' ];

		$price = $item->salePrice;
		$discount = $price * .5;

		$adjustment->amount = -$discount;
		$adjustment->setOrder($order);
		$adjustment->setLineItem($item);
		$adjustments[] = $adjustment;

	}

	return $adjustments;

}
```

**Expected behavior**
On a $100 product, the plugin’s adjuster takes $50 off the item, as expected. I’d then expect the CP enabled discount to calculate 50% off $50, not the base price ($100). But it doesn’t. It takes another $50 ignoring the first discount. The total is then 0 instead of $25.

**Additional info**
- Commerce version 3.1.7
- Craft version: 3.4.23
- PHP version: 7.2.24
- Database driver & version: Valet+ 1.0.26

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#cd17e965c932968d7e0c704ba93e8750d0c00b95 as 3.1.8",
  "...": "..."
}
```

Then run `composer update`.

Also adding within this fix the new `EVENT_REGISTER_DISCOUNT_ADJUSTERS` event, to ensure the discount is registered before our built-in discount adjuster:

https://github.com/craftcms/commerce/blob/cd17e965c932968d7e0c704ba93e8750d0c00b95/src/services/OrderAdjustments.php#L52-L70
