### ISSUE TITLE
Variant relation field does not save its content

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/commerce#151]
Setup:
Product variant has a relationship field that ties it to a single entry.

On creating a product with two variants and selecting content for both (required) relationship fields, the relation is not saved. Also, no 'this field is required' error is thrown.

**Comment by lukeholder** [comment]
Can you please `composer update` and let me know if it persists.

Please also give clearer steps to reproduce.

**Comment by lukeholder** [comment]
@nilsenpaul any updates?

**Comment by nilsenpaul** [comment]
@lukeholder Sorry, didn't really find the time to check it out today. Just updated and checked it out, and the problem seems to be solved! Will do some more testing and open a new issue if the problem persists, with more info.

**Comment by lukeholder** [comment]
Thanks
