### ISSUE TITLE
getAllEnabledStatesAsListGroupedByCountryId returns states in random order

### ISSUE THREAD

**Issue by brianjhanson** [craftcms/commerce#1512]
**Description**
I'm not sure if this is really a bug, but the `getAllEnabledStatesAsListGroupedByCountryId` seems to return states in a random order on every refresh.

**To Reproduce**
Output `{% dd  craft.commerce.states.getAllEnabledStatesAsListGroupedByCountryId %} and refresh. On each refresh the order seems to change.

[Video of the output](https://jmp.sh/Bd12pz3)

**Expected behavior**
I expected them to be ordered alphabetically.

**Additional info**
- Craft version: 3.4.18
- PHP version: 7.3.16
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Cookies</th>
                        <td>1.1.12</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>3.1.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Feed Me</th>
                        <td>4.2.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Freeform</th>
                        <td>3.6.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Gift Voucher</th>
                        <td>2.3.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Klaviyo Connect</th>
                        <td>3.1.3.2</td>
                    </tr>
                                    <tr>
                        <th class="light">one-campaign-monitor</th>
                        <td>dev-feature/craft-3</td>
                    </tr>
                                    <tr>
                        <th class="light">One Imgix</th>
                        <td>dev-craft-3</td>
                    </tr>
                                    <tr>
                        <th class="light">PayPal Checkout for Craft Commerce</th>
                        <td>1.1.0</td>
                    </tr>
                                    <tr>
                        <th class="light">PayPal for Craft Commerce</th>
                        <td>2.1.0.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Rackspace Cloud Files</th>
                        <td>dev-feature/parse-env-vars</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.6.1</td>
                    </tr>
                                    <tr>
                        <th class="light">SEOmatic</th>
                        <td>3.3.2</td>
                    </tr>
                                    <tr>
                        <th class="light">ShipStation Connect</th>
                        <td>1.3.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Stripe for Craft Commerce</th>
                        <td>2.3.0</td>
                    </tr>
                            </tbody>
        </table>

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

> You can work around the bug without waiting for the release by just sorting one country in the country list manually within the CP, and same for each group of states inside each country.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#fb4cba2f85a36d4a25c3fdd760256d66d8f4bb0a as 3.1.8",
  "...": "..."
}
```

Then run `composer update`.

Thanks.

**Comment by brianjhanson** [comment]
Thanks @lukeholder!
