### ISSUE TITLE
Using AJAX to Update Cart is replacing the cart contents instead of adding to it.

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce#1514]
**Description**
When I make a AJAX request with the action "commerce/cart/update-cart" using a different product it replaces the products already in the cart instead of adding to the cart.

**To Reproduce**
How, and what happened?
1. Add an item to cart using AJAX.
2. Item get added to the cart.
3. Add another item to cart using AJAX.
4. Item gets added to the cart but the first item is no longer there.

**Expected behavior**
What did you expect to happen?
Both items should be in the cart.

**Additional info**
- Craft version: 3.4.23
- PHP version: 7.4.6
- Database driver & version: 5.7.30
- Plugins & versions:
   Commerce 3.1.8

**Additional context**
![Screen Shot 2020-06-16 at 1 15 48 PM](https://user-images.githubusercontent.com/43895851/84823930-05980d80-afd4-11ea-966c-6c1966597283.png)
![Screen Shot 2020-06-16 at 1 16 11 PM](https://user-images.githubusercontent.com/43895851/84823938-07fa6780-afd4-11ea-9199-dfaa48efcdfb.png)

**Comment by lukeholder** [comment]
Please ensure you are using Commerce Pro and not Commerce Lite. The latter only allows one item in the cart at a time: https://docs.craftcms.com/commerce/v3/editions.html

**Comment by simeon-smith** [comment]
This was the issue. Thank you.
