### ISSUE TITLE
Settings > Plugins > Documentation links to version 2

### ISSUE THREAD

**Issue by duskosobic** [craftcms/commerce#1517]
**Description**
If you visit Settings > Plugins and click at Documentation, you will be sent to https://docs.craftcms.com/commerce/v2/ instead of https://docs.craftcms.com/commerce/v3/

**To Reproduce**
How, and what happened?
1. Go to Settings page
2. Then Plugins
3. Click Documentation in "Craft Commerce" section
4. Version 3 plugin links to version 2 documentation

**Expected behavior**
What did you expect to happen?
Documentation link should go to https://docs.craftcms.com/commerce/v3/

**Additional info**
- Craft version: Solo 3.4.24
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Craft Commerce	3.1.9

**Comment by nfourtythree** [comment]
Hi @duskosobic 

Thank you for pointing this out. We have pushed a fix for this that will be included in the next release.

Thanks!
