### ISSUE TITLE
Can't save a new address in New Order

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1519]
**Description**

![image](https://user-images.githubusercontent.com/731309/85082312-dc64c080-b211-11ea-988e-9dad4efa44e7.png)

Create customer test@test.com (BTW not obvious that wants ONLY an email - given you can search by name it was confusing me that everytime I clicked 'create' on an unrecognised name it jsut shoved my own email in - that's not great UX).

Go to billing, add New Address.

Can't save it because something is not right with the field checking - as you can see the country is filled in, but there is an error underneath it and the Done button is greyed out.  Can't get it to change, selecting other countries etc does not work.

**Expected behavior**

Able to save an address

**Additional info**
- Craft version: 3.4.24
- PHP version: 7.2
- Database driver & version: Mysql
- Plugins & versions: Commerce 3.1.9

**Additional context**

Windows 10 64 bit with Firefox latest.

**Comment by nfourtythree** [comment]
Hi @bossanova808 

I have managed to verify the following:

> Create customer test@test.com (BTW not obvious that wants ONLY an email - given you can search by name it was confusing me that everytime I clicked 'create' on an unrecognised name it just shoved my own email in - that's not great UX).

There is a new issue specifically for this: #1523 

As for your address issue, I am struggling to recreate it. Do you have any custom validation rules? Could you send a video or exact steps on how I can reproduce this on a fresh install?

Thanks.

**Comment by bossanova808** [comment]
I don't have easy access to a fresh install right this moment.

My validation rules are:
```
        $event->rules[] = [['firstName'], 'required'];
        $event->rules[] = [['lastName'], 'required'];
        $event->rules[] = [['phone'], 'required'];
        $event->rules[] = [['address1'], 'required'];
        $event->rules[] = [['city'], 'required'];
        $event->rules[] = [['zipCode'], 'required'];
        $event->rules[] = [['countryId'], 'required'];
```
...is it possible that your thingy is not setting the `countryId`?

**Comment by bossanova808** [comment]
(of course I'll set up a fresh install if that proves to be needed - is what I meant to add!)

**Comment by nfourtythree** [comment]
Thanks for the info @bossanova808 

Will replicate these custom validation rules and see what is happening.

**Comment by nfourtythree** [comment]
Hi @bossanova808 

Thank you for the info and bringing this to our attention.

We have pushed an update that fixes this issue, it will be included in the next releaase.

To get this early, change your `craftcms/commerce` requirement in you project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#b311d0bd6850dd0c14be4be6d6cefbde91bc38d9 as 3.1.9",
  "...": "..."
}
```

Then run `composer update`.

Thanks.
