### ISSUE TITLE
Add to cart much slower in Commerce 3 vs. Commerce 2 (and other requests)

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1520]
**Description**

Adding items to cart...was near enough to instant with Commerce 2.  

With Commerce 3, takes a minimum of a few seconds every time, same server and templates etc.  It's just _a lot_ slower.

Indeed, am noticing a distinct slow down in all cart related operations - increasing qtys, removing items, etc.  Definitely a noticeable performance drop across the board on the front end.

In the profiler for these ajax operations, I am seeing a great number of queries that are slower than I'd expect (16ms+), and many of them repeated...including, e.g., ones summing refunds (which seems unnecessary for a not-yet-completed order!)

![image](https://user-images.githubusercontent.com/731309/85088099-9b28dc80-b222-11ea-9c18-9899cbf0bd80.png)

Any tips of trying to work out where the issues are coming from and what I can do to re-gain performance would be great.  It's slow enough and different enough I am quite sure we're going to be getting issues from customers about it.

**Comment by lukeholder** [comment]
Should be fixed in https://github.com/craftcms/commerce/pull/1543

**Comment by bossanova808** [comment]
Do you folks know when you might cut a release?  Debating going to the develop version in the meantime....

**Comment by lukeholder** [comment]
@bossanova808 will be tonight/in the morning.
