### ISSUE TITLE
Edit addresses in the user area - can't tell which address is which from insufficient details shown

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1522]
Would it be possible to show the full address in this view - as sometimes we need to edit something in a user's account, e.g. the business name, and we have to click through all the addresses to find the right one...be much easier if the full details were visible here instead.

![image](https://user-images.githubusercontent.com/731309/85095416-b1d82f00-b234-11ea-8c8b-81543ab89652.png)

Thanks for considering!

**Comment by nfourtythree** [comment]
Hi @bossanova808 

As you have said, clicking the "I" icon will show you the full address but rightfully so this could be less than ideal for large lists of addresses.

Your request will be handled within the [address format setting](https://github.com/craftcms/commerce/issues/1305) feature we are looking to implement.

Thanks.

**Comment by bossanova808** [comment]
Ok thanks - we have some customers with like 50 addresses so ... yeah, it's a pickle.
