### ISSUE TITLE
product.defaultVariantId is null

### ISSUE THREAD

**Issue by superpikar** [craftcms/commerce#1529]
**Description**
After updating commerce from 3.1.3 to 3.1.7, the new product value of `defaultVariantId` is null **but** the value of `defaultVariant.id` is not null
 
Update commerce to 3.1.9 but the problem still remains

following is my testing page
```
{% set products = craft.products().all() %}
  List of Product and its Variant ID
  <ul>
    <li>id - defaultVariant.id - defaultVariantId</li>
    {% for item in products %}
      <li>{{ item.id }} - {{ item.defaultVariant.id }} - {{ item.defaultVariantId is null ? 'null' : item.defaultVariantId }}</li>
    {% endfor %}
  </ul>
```
the output 
![image](https://user-images.githubusercontent.com/2832280/85203628-37450780-b339-11ea-956b-9cd691f22ad9.png)

**To Reproduce**
How, and what happened?
1. Update commerce to 3.1.9
2. create a testing page /templates/testing.twig with the code snippet above

**Expected behavior**
product.defaultVariantId value is not null

**Additional info**
- Craft version: 3.4.24
- Commerce version: 3.1.9
- PHP version: 7.2
- Database driver & version:
- Other Plugins & versions:

**Additional context**

**Comment by nfourtythree** [comment]
Hi @superpikar 

Thank you for bringing this to our attention.

We have pushed a fix for this which will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in you project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#b089cbbdc3980c3172a20845d50fe4ac5ea22ca2 as 3.1.9",
  "...": "..."
}
```

Then run `composer update`.

Either after the next release or when you have done the above you can run the console command `./craft resave/products` this should fix any issues that you have currently.

Thanks.
