### ISSUE TITLE
See rule info from rule index page. Allow rule duplication.

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#153]
> Created by: Kevin Laaksonen ([klaaks3@gmail.com](klaaks3@gmail.com)) on 2018/03/21 16:40:01 +0000
Votes at time of UserVoice import: 1

------
The ability to show which conditions are applied to the rules in the shipping method rule view?  It is time consuming to click on each rule to double check the settings.  A "quick view" would be a huge help to keep track of settings.  When dealing will a lot of rules, this would save a lot of time and help with accuracy.  

Also a way to "copy and paste" rules when adding a shipping method or rule.

**Comment by lukeholder** [comment]
Keep the rules admin table, use HUD to show conditions and price information.

**Comment by lukeholder** [comment]
**Action**

- [ ] Add a save as new rule link
- [ ] Show rules details on new admin table

**Comment by lukeholder** [comment]
Fixed for next release (3.2)
