### ISSUE TITLE
Checkout fails without any relevant error message when gateway is missing

### ISSUE THREAD

**Issue by aNickzz** [craftcms/commerce#1531]
**Description**
A.K.A. Carts don't update their gateway ID when the gateway has been removed from the CP. (though whether or not it should is debatable).

When checking out the page just reloads with no message. I'm showing cart validation messages, but stepping through the code I've found the validation errors are on the `$paymentForm` (missing credit card number, missing name, etc.), but I'm using a Manual gateway since we don't take payments, and there are no credit card fields on the checkout. I think this is due to the payment gateways changing after the cart has been created. 

**To Reproduce**
We have a few people working on this and I think this is what happened, but there is likely some project.yaml sync voodoo happening too, as this is only happening in one development instance of the site.

1. Create a gateway "dummy" (id=1)
2. Add something to your cart
3. Delete the "dummy" gateway
4. Create a "manual" gateway (id=2)
5. Attempt to checkout
6. Validation error on gateway id=1 (missing credit card fields, there is no credit card form for a manual gateway)

**Expected behavior**
Either an error message stating that the selected gateway is missing / deleted / archived / not available or the gateway used by the order defaults to the new one with id=2

**Additional info**
- Craft version: Craft Pro 3.4.22.1
- Commerce version: 3.1.7
- PHP version: 7.1.33
- Database driver & version: MySQL 5.7.30
- Other Plugins & versions: Available on request

**Additional context**
![image](https://user-images.githubusercontent.com/15243523/85354154-14893d80-b549-11ea-8f78-b056411f28d9.png)

![image](https://user-images.githubusercontent.com/15243523/85354137-0affd580-b549-11ea-8a5e-45422011198e.png)

As a workaround, for now, I'm setting 

```twig
<input type="hidden" name="gatewayId" value="{{ craft.commerce.gateways.getGatewayByHandle('storeCredit').id }}">
```

in my checkout template but obviously I wouldn't want to be relying on user-submitted data.

**Comment by lukeholder** [comment]
Now when a gateway is deleted, all carts are updated to remove that gateway.
