### ISSUE TITLE
Custom shipping methods show a zero price

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce#1532]
When viewing custom shipping method options, the price value is shown as zero.

![image](https://user-images.githubusercontent.com/133571/85367627-317b3c00-b55c-11ea-9fd4-212178bda2d0.png)

**Comment by engram-design** [comment]
Related to this, I can't seem to call `method.getShippingRules()` from my custom shipping methods in https://github.com/verbb/postie/issues/36

```
{% for handle, method in cart.availableShippingMethodOptions %}
    {{ dump(method.getShippingRules()) }}
{% endfor %}
```

See https://d.pr/i/Tb3xni which is correct for Commerce shipping methods, but not for a shipping method provided by Postie.

**Comment by engram-design** [comment]
Looks like this issue might be back in 3.4.x.

![image](https://user-images.githubusercontent.com/1221575/151085539-30f10f22-13fe-45df-adb3-d955d1facc75.png)

Here, I'm outputting the available methods with `Order::getAvailableShippingMethodOptions()` and `Order::getAvailableShippingMethods()` (deprecated) with only the latter approach working correctly.

```
<h2>availableShippingMethods</h2><br>
    {% for handle, method in cart.availableShippingMethods %}
        {% set price = method.priceForOrder(cart)|commerceCurrency(cart.currency) %}
        
        {{ method.name }} - {{ price }}<br>
    {% endfor %}

    <h2>getAvailableShippingMethodOptions</h2><br>
    {% for handle, method in cart.getAvailableShippingMethodOptions %}
        {% set price = method.priceForOrder(cart)|commerceCurrency(cart.currency) %}
        
        {{ method.name }} - {{ price }}<br>
    {% endfor %}

    <br><br>
```

The top 3 are Commerce-created methods, the others are Postie-provided ones.
