### ISSUE TITLE
Discount Conditions Variants/Categories Popup "filtering" issue

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#1533]
**Description**
I am not sure if this is an issue or not but when I got to select a product that is applicable to a coupon discount I am seeing a filtering in the modal where I can select "Enabled" or "Disabled" and I am not sure what they do. "Enabled" shows all products. Also products that are "Disabled" in my products index page. What does "Enabled" means? The same as "Live" which is the term used on the products index page?

**To Reproduce**
1. `Commerce -> Discounts -> Conditions`
2. `Click Choose under "Product Variant (Purchasable)"`
3. `Click the filter button and see "Enabled" and "Disabled" `

**Comment by nfourtythree** [comment]
Hi @philipboomy 

Thank you for raising the issue. This is an interesting one and actually leads to things we will be looking to improve in the future. That is the display of products/variants and the statuses that go with them.

I think in your case here there is maybe a bit of confusion about what is being shown. This is a list of variants, even for those products that only have a single variant. Show the enabled/disabled filter is tied to the variant and not the product. We understand how this could be confusing.

For the moment we have pushed an update, that will be included in the next release, which adds the product's status to the list:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/KouB4Z4W/Image%202020-06-24%20at%2010.05.01%20am.png?v=235087aeda16491a6bb9b17f0cda0cde)

This should, at least for the short term, help identify the status of the products/variants being selected. Again, we are looking at how to improve all this in the future as "status" is quite an involved thing when it comes to products (product status, variant status, available for purchase, stock level etc). We are relying on some updates in Craft itself before we can really tackle how we show this data in its best format.

Thanks!
