### ISSUE TITLE
Product::getVariants() should return a VariantQuery object

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#1534]
**What are you trying to do?**
`Product::getVariants()` now returns an array. This has the following issues:

- All variants are fetched, also disabled ones.
- Can't use eager-loading properly with custom parameters (https://docs.craftcms.com/v3/dev/eager-loading-elements.html#defining-custom-parameters-on-eager-loaded-elements)
- It is inconsistent with, for example, the use of `Entry::getChildren()`

**What's your proposed solution?**
`Product::getVariants()` should return a `VariantQuery` object, like `Entry::getChildren()` does

**Comment by Anubarak** [comment]
Of course that's a great feature, but just in case it's not accepted: you can do eager loading with custom parameters and fetch only enabled/active/available variants. Otherwise I would have mentioned this already as a feature request because it would make my site way too slow

**Comment by boboldehampsink** [comment]
@Anubarak I couldn't get it to work with eager loading + custom parameters

**Comment by Anubarak** [comment]
Maybe it was only possible in earlier versions. I stuck on a 1 year old version of commerce due to breaking changes. What's your code and version?

**Comment by lukeholder** [comment]
You should be able to use eager loading with custom params on the eager loaded criteria. It is working for me. For example:

```
{% set eagerproducts = craft.products()
.with([
['variants', { sku: 'ANT-001' }]
])
.all() %}

{% for product in eagerproducts %}
    {{ product.title }}
<br>
{% for variant in product.variants %}
    {{ variant.sku }}<br>
{% endfor %}
{% endfor %}
```

returns:

```
A New Toga
ANT-001
Parka With Stripes On Back

Romper For A Red Eye

The Fleece Awakens

The Last Knee-High

Full-Size Dry Boxer
```

**Comment by lukeholder** [comment]
As for making the `product.variants` act as an element query, this would not be possible in a backwards compatible way at the moment. You have the ability to do eager loading as mentioned above, and also doing something like `craft.variants.product(product)` instead of `product.variants` if you want a query object for that product.
