### ISSUE TITLE
more options for discounts

### ISSUE THREAD

**Issue by circa1977** [craftcms/commerce#1535]
We've been trying to use discounts for a particular type of promotion and the options available don't quite support it. I'm sharing what we're hoping to do as a feature request.

**What are you trying to do?**
We use Craft Commerce for online catering orders. We'd like to offer a free item when a minimum order amount (`cart.total`) has been reached.

The discount should apply to a specific product added to the cart. As a current example, we'd like to provide a free Sangria Cocktail Mixer Kit if the order total is > $150.

The price of the Mixer Kit is $10. I've tried providing a $10 discount and limiting that to the product, but I run into 2 issues:

1. The minimum amount—$150—only applies to the product, not the cart total, which means you'd need to add 15 items to your cart for the discount code to work.
2. The $10 discount applies to all 15 $10 items, enabling you to get $150 worth of product for free, when we only want to give you 1 free kit.

We've worked around this by just adding text to the cart / checkout page saying that the order includes a free kit once you hit that threshold. (We have other code in our templates that determines pickup/delivery options based on `cart.total`, so we have this conditional logic in place.) But we still have the need to provide promotions along the lines of "Use coupon code ABCDEF to get a free XYZ with your order of $150 or more."

**What's your proposed solution?**
Add additional configuration options for discount codes.

**Comment by nfourtythree** [comment]
Hi @circa1977 

Thank you for your message.

You could achieve what you after by using a [custom adjuster](https://docs.craftcms.com/commerce/v3/adjusters.html). There is an example of a custom discount adjuster here: https://docs.craftcms.com/commerce/v3/adjusters.html#example

These adjusters can contain whatever logic you would like to figure out the discount you need for the line item.

If you get stuck with this the [Craft Stack Exchange](https://craftcms.stackexchange.com/) is a great place to post. Someone may have solved this before or if not it could

**Comment by circa1977** [comment]
@nfourtythree Thanks for the reply. We do use custom adjusters for specific fees that we need to add. But that seems like overkill if someone in Marketing just wants to discount a single quantity of a single product based on the cart total. Why wouldn't that be a candidate for an enhancement for the discount rules?

**Comment by nfourtythree** [comment]
Hi @circa1977 

What you have described is more of a "buy X get Y" rather than a "traditional" discount, which we have an open issue for: https://github.com/craftcms/commerce/issues/47.

We are also looking at adding a condition builder to discounts in the future so this request would fall under that umbrella. Here is the issue for that feature that you can track/voice your thoughts on: https://github.com/craftcms/commerce/issues/80

Thanks
