### ISSUE TITLE
Inconsistent Variable Type When Item in Cart has a Sale that Makes the Price 0.

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce#1539]
**Description**
I have an item with a sale on it. The item is $10. The sale is for $10. This makes the item 0. When then item is added to the cart the "totalAsCurrency" variable from getting the cart via JSON is the integer of 0. When the price is not zero it would be a string with the dollar sign in front. i.e. "$10.00". 

**To Reproduce**
How, and what happened?
1. Have a variant with a sale that makes the item price 0.
2. Add then item to the cart.
3. Check the totalAsCurrency value. It is an integer of 0.
4. Add an item to the cart that doesn't have a sale price of 0.
5. Check the totalAsCurrency value. It is a string.

**Expected behavior**
What did you expect to happen?
The totalAsCurrency value should always be a string with the currency symbol in front of it.

**Additional info**
- Craft version: 3.4.25
- Commerce version: 3.1.10
- PHP version: 7.4
- Database driver & version: 8.0.20
- Other Plugins & versions: N/A

**Comment by lukeholder** [comment]
Will be fixed in combination with https://github.com/craftcms/commerce/issues/1541

**Comment by lukeholder** [comment]
Fixed in 3.1.11
