### ISSUE TITLE
Shipping method order total options

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#154]
> Created by: Joel King ([joel@parktool.com](joel@parktool.com)) on 2018/03/02 20:08:03 +0000
Votes at time of UserVoice import: 1

------
It would be nice if there were a setting in shipping method conditions or even some Commerce config items to specify which adjustments should be included when evaluating min/max order totals for shipping method rules. This way would allow the shipping method to be set up so that, for example, free shipping would apply when a customer spends at least $50 after discounts but before taxes.

**Comment by lukeholder** [comment]
This is already possible by creating a discount that has a min purchase price of $50 and giving the order free shipping. Make sure to put the discount as the last discount on the list.
