### ISSUE TITLE
CP Edit Order: Address Modal Submit Button Not Visible

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce#1540]
**Description**
When going to edit the address on an order the bottom part of the address modal is hidden. I can access it by zooming out, but scrolling scrolls the background.

I took a screen recording to help illustrate what I was running into. 
[Screen Recording 2020-06-26 at 10.27.53 AM.mov.zip](https://github.com/craftcms/commerce/files/4837817/Screen.Recording.2020-06-26.at.10.27.53.AM.mov.zip)

**To Reproduce**
1. In the CP go to any order page
2. Click 'edit'
3. Click 'edit address'
4. Try to submit the address

**Expected behavior**
I expected to scroll down the modal and be able to click submit on the form.

**Additional info**
- Craft version:  Craft Pro 3.4.24
- Commerce version: 3.1.9
- PHP version: 7.3
- Database driver & version: Mysql 5.7
- Other Plugins & versions:
```
Amazon S3	1.2.8
Cookies	1.1.12
Craft Commerce	3.1.9
Doxter	3.4.9
Instant Analytics	1.1.7
Linkit	1.1.11
oEmbed	1.3.2
Redactor	2.6.1
Retour	3.1.39
SEOmatic	3.3.8
Similar	1.0.6
Stripe for Craft Commerce	2.3.1.1
Twigpack	1.2.2
```

**Additional context**

**Comment by dhahn** [comment]
Actually, I the issue is with any modal on that page. What I noticed was that if you have a longer order page it breaks for the "snapshots" modal as well. As in, half the modal is off the screen. It appears to be calculating the middle based on the length of the page and not the size of the screen.

**Comment by nfourtythree** [comment]
Hi @dhahn 

I have tried to replicate this in Chrome, Safari and Firefox and I can't seem to get the issue you are having.

Could you try disabling your plugins and any browser extensions that may interfere and let me know how you get on? Also, could you let me know what browser and version you are using?

Thanks.

**Comment by dhahn** [comment]
It actually looks like updates we're making to the page are causing it, but I can't find out what. For instance, we have this bit of code we're adding:

```
    <div id="moment-order-actions" class="btngroup right first">
        <div class="btngroup right first">
            <a target="_blank" href="{{ siteUrl('/shop/customer/order?number=' ~ order.number) }}" class="btn">View as Customer</a>
            <div class="btn menubtn"></div>
            <div class="menu">
                    <li><a href="{{ cpUrl('moment/return-labels/new?orderId=' ~ order.id) }}">Create Return Label</a></li>
                    <li><a href="{{ cpUrl('moment/replacement-orders/new?orderId=' ~ order.id) }}">Start Replacement Order</a></li>
                </ul>
            </div>
        </div>
    </div>

```

There's more `<li>` than that but this is the gist of it. We then load that into the page via:

```
        Craft::$app->view->hook('cp.commerce.order.edit', function (&$context) {
            return MomentModule::$instance->templates->render('orders/partials/_main-edit-pane', $context);
        });
```

That bit was actually a remnant of something we had to do in Commerce 1 / Craft 2 so maybe there's a better way now, but really that's just injecting it into the page with `display: none`.

Then we use this to show it on the page:

```
  var $momentOrderActions = $('#moment-order-actions');
  $momentOrderActions.prependTo('#action-button')
  $momentOrderActions.show();
```

Is there a better way for us to be doing this that will not conflict now (or long term) with updates to that page?

**Comment by nfourtythree** [comment]
Hi @dhahn 

If you change you template hook to use `cp.commerce.order.edit.main-pane` you will probably find that this will work as expected.

Hope this helps, thanks!

**Comment by dhahn** [comment]
So simple. So glorious. Thank you that worked!
