### ISSUE TITLE
Should variant price return a float

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1542]
Noticed that the `price` attribute of the Variant element returns a string compared to the `getPrice()` method that returns a float.

https://github.com/craftcms/commerce/blob/1fa1a4895eeb149b0c3c15da21c8d165a52b7217/src/elements/Variant.php#L190

Good use for the typecast behavior.

**Comment by lukeholder** [comment]
Will be expanding the typecast behavior to more models like variants. Stay tuned.

**Comment by lukeholder** [comment]
Price should be typecast to float in 3.1.11
