### ISSUE TITLE
Unable to edit payment currencies

### ISSUE THREAD

**Issue by jhealey5** [craftcms/commerce#1547]
**Description**
After a payment currency is initially set it can't be changed due to the field getting `disabled="0"` on the payment currency edit screen. I can remove the disabled attribute via inspector, edit it and save fine, but without doing that it's non-editable.

**To Reproduce**
1. Create multiple payment currencies
2. Edit one of those to change the rate.

**Additional info**
- Craft version: Craft Pro 3.4.26
- Commerce version: 3.1.10
- PHP version: 7.3.14
- Database driver & version: MySQL 5.7.29

**Comment by nfourtythree** [comment]
Hi @jhealey5 

Thank you for bringing this to our attention, we have pushed a fix that will be included in the next release.

Thanks!
