### ISSUE TITLE
Deprecation method used in cart query with AJAX

### ISSUE THREAD

**Issue by yingban** [craftcms/commerce#1548]
Hi!

I am getting the cart with AJAX and i always have a deprecation method that I see in my CP warnings:
Message: Order::getAvailableShippingMethods() has been deprecated. Use Order::getAvailableShippingMethodOptions().
Origin: /vendor/yiisoft/yii2/base/ArrayableTrait.php:126

How I get the cart:

```
getCraftCart () {

    return new Promise((resolve) => {
      Axios({
        url: CraftVars.baseUrl + '?action=commerce/cart/get-cart&note=from+ajax',
        method: 'GET',
        mode: 'no-cors',
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
          'X-CSRF-Token' : CraftVars.csrfToken,
        }
      }).then((result) => {
        resolve(result.data.cart);
      });
    });
  },
```

- Craft version: Craft Pro 3.4.26 
- PHP version: 7.2.22
- Craft Commerce version: 3.1.10

**Comment by bossanova808** [comment]
Seeing this as well.  In the stack trace is:

```
craft\commerce\elements\Order::toArray([], ["lineItems.snapshot", "availableShippingMethodOptions", "availableShippingMethods"])
Called from /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/commerce/src/controllers/BaseFrontEndController.php:62
```

which is coming from: https://github.com/craftcms/commerce/blob/bf0e9963f20321b334a5b282f06434acbcf205c4/src/controllers/BaseFrontEndController.php#L56 - where it refers to both

**Comment by lukeholder** [comment]
Yeah we would need to figure out a way to add the same `availableShippingMethods` value in the ajax JSON response without calling the deprecated method in a backwards compatible way. We can't just remove it or it would break existing sites.
