### ISSUE TITLE
Uploaded Assets to be all in lowercase

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#155]
> Created by: Karlo Estrada ([karloestrada@gmail.com](karloestrada@gmail.com)) on 2018/02/21 00:17:59 +0000
Votes at time of UserVoice import: 1

------
Having this problem when uploading images on Linux environment where the server is case sensitive. So when I am uploading an image with JPG as uppercase. This results into a 404 not found.

**Comment by lukeholder** [comment]
Please see the craftcms/cms repo.
