### ISSUE TITLE
Bug with new discount event 

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1550]
**Description**

With the following code:

```
        Event::on(Discounts::class, Discounts::EVENT_DISCOUNT_MATCHES_LINE_ITEM, static function(MatchLineItemEvent $e) {
            CommerceLogic::onBeforeMatchLineItemHandler($e);
        });
```
I am seeing discounts being erroneously still applied even when `$event->isValid = false;`  in the called function

I do  not see this behaviour with the deprecated event:

```
        Event::on(Discounts::class, Discounts::EVENT_BEFORE_MATCH_LINE_ITEM, static function(MatchLineItemEvent $e) {
            CommerceLogic::onBeforeMatchLineItemHandler($e);
        });
```

..in this case the discount is (correctly) not applied if `$event->isValid = false;` .

The actual logic in the called function is simple and the same since before Commerce V1...

```
    public static function onBeforeMatchLineItemHandler(MatchLineItemEvent $event): void
    {

        $lineItem = $event->lineItem;
        $discount = $event->discount;

        // Student roll printing 10% off
        if ($discount->id == "9") {

            if ($lineItem->purchasable instanceof \craft\commerce\elements\Variant) {
                if (!(strpos($lineItem->purchasable->title, "Roll Print") === 0)) {
                    $event->isValid = false;
                }
                else {
                    //self::log("Discounted roll print: $lineItem->purchasable->title");
                }
            }
        }
}
```

**Additional info**
All latest versions as of now.

**Comment by lukeholder** [comment]
Is your `EVENT_BEFORE_MATCH_LINE_ITEM` event handler still around at the same time? If it is still attached (even your handler doesn't do anything)?

**Comment by bossanova808** [comment]
Going to close this for now as I believe that somehow perhaps my update to 3.1.10 was incomplete...as moving to the 'performance enhanced' -develop version seems to have solved this.
