### ISSUE TITLE
Commerce Lite - Add to cart does not replace

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/commerce#1552]
When adding products to the cart in commerce lite, the behaviour is described in the documentation as follows:

_In the Lite edition of Craft Commerce only single line item can exist in the cart. Whenever a customer adds something to the cart, it replaces whatever item was in the cart. If multiple items are added to the cart in a single request, only the last item submitted is added to the cart._

However, the Order element actually prepends and doesn't append, so you're always stuck with the first added line item.
https://github.com/craftcms/commerce/blob/develop/src/elements/Order.php#L1547

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#0dc10d1a4a64d3fe96a0bd8fc3fede20fb2bdbd7 as 3.1.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by lenvanessen** [comment]
Cheers
