### ISSUE TITLE
When previewing a product with variants it throws an error.

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce#1554]
**Description**
When I preview a product I get the following error:

```
Argument 1 passed to craft\commerce\services\PaymentCurrencies::convert() must be of the type float, null given, called in /nitro/sites/site/craft/vendor/craftcms/commerce/src/helpers/Currency.php on line 82
```

This does not happen when I view the page directly. Only in the preview pane even with no differences between the live page and the "draft". I think it may be related to the commerceCurrency filter. This doesn't appear to happen with a product that doesn't have variants.

**To Reproduce**
How, and what happened?
1. Preview a product with variants in the CMS.
2. Preview won't load.
3. Preview throws error above.

**Expected behavior**
What did you expect to happen?
The preview should load just like the live page does.

**Additional info**
- Craft version: 3.4.27
- Commerce version: 3.1.11
- PHP version: 7.4
- Database driver & version: MySQL 8.0.20
- Other Plugins & versions:

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release in e0bf5f0f90a31eb067b3b4fcbd0b6a3343b472f1.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#e0bf5f0f90a31eb067b3b4fcbd0b6a3343b472f1 as 3.1.11",
  "...": "..."
}
```

Then run `composer update`.
