### ISSUE TITLE
User addresses in CP do not show State if State was set to an ID rather than a text value

### ISSUE THREAD

**Issue by Mosnar** [craftcms/commerce#1556]
**Description**
The user address fields in the control panel only show a field with the state value, which is blank if the state is a reference to a state ID.

**Additional info**
- Craft version: Craft Pro 3.4.27
- Commerce version: Commerce Pro 3.1.11
- PHP version: 7.3.13
- Database driver & version: MySQL 8.0.19

**Comment by nfourtythree** [comment]
Hi @Mosnar 

Thank you for bringing this to our attention. We have pushed a fix for this that will be included in the next release.

Thanks!
