### ISSUE TITLE
BUG: existing orders showing wrong shipping method when the choosen method gets disabled

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#1557]
**Description**
An existing order has in our case shipping handle `standard` which stands for `DHL`. Now the customer decides to change to shipping carrier to `PostNL` so I created another shipping method with handle `standardPostNl` and disabled the `standard` method so it can't be chosen by a buyer in the frontend. In the orders overview Craft somehow now decides to show `PostNL` as shipping method while it should still show `DHL`. This very confusing and shouldn't happen.

**To Reproduce**
1. Have an order with method `standard`:
1.1. Shipping methods: https://nimb.ws/sLxkQI
1.2. Order overview: https://nimb.ws/FtoYE6
1.3. Order detail: https://nimb.ws/9jha45
2. Disable method `standard`: https://nimb.ws/BcxqkL
3. Overview now shows `PostNL` instead of `DHL`: https://nimb.ws/JVlkNI
4. Order detail page now shows only the handle instead of also the title: https://nimb.ws/6HzOkL

**Expected behavior**
Overview and detail page should show the selected shipping method, no matter if it the method is disabled for the frontend.

**Additional info**
- Craft version: 3.4.27
- Commerce version: 3.1.11
- PHP version: 7.3.13 & 7.4.4
- Database driver & version: MySQL 5.7.26

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

Thank you for bringing this to our attention.

We have pushed a fix for this that will be included in the next release.

To get this early, change your `craftcms/commerce` requirement in you project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#d322f7055ec9df03aa7b10b19bd7998705a8bf67 as 3.1.11",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
