### ISSUE TITLE
Kickstarter reward management

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#156]
> Created by: Roger Lee ([roger@gadget-labs.com](roger@gadget-labs.com)) on 2018/02/08 06:14:01 +0000
Votes at time of UserVoice import: 1

------
We are running a Kickstarter project and has over 2000 backers. Is it possible to import all the backers and make them into sales records?

The purpose is that we want to manage all the orders in one place and send emails to backers to confirm their address and chance to upsale.

**Comment by lukeholder** [comment]
You can create a PHP module in Craft 3 that could import the orders.
