### ISSUE TITLE
Move the “Categories Relationship Type” discount setting under an “Advanced” toggle

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#1560]
The “Categories Relationship Type” setting is pretty [confusing](https://discordapp.com/channels/456442477667418113/672206118122160149/730671617826357259) to shop owners, and also pretty niche. I imagine 99% of use cases would be happy with the behavior you get when “Both” is selected.

So I think it should be moved under an “Advanced” toggle, which is hidden by default, similar to what we do in Matrix and Redactor field settings, among others. That gives shop owners permission to ignore it unless they have a good reason to care.

While you’re at it, the instruction (and possibly option label) copy should be updated for clarity. At the very least the reference to “Products” should be replaced with “purchasables”, and “categories” should be lowercased.

**Comment by lukeholder** [comment]
Fixed in https://github.com/craftcms/commerce/pull/1565
