### ISSUE TITLE
Using craft.commerce.countries.allEnabledCountries doesn't return them in the same order as the CMS

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce#1561]
**Description**
When using craft.commerce.countries.allEnabledCountries to get all the countries that are enabled in the CMS they do not return in the same order as they are in the CMS>

**To Reproduce**
How, and what happened?
1. Run a loop to display craft.commerce.countries.allEnabledCountries on the page.
2. It is order by the ID number not the order in the CMS.

**Expected behavior**
What did you expect to happen?
It would return as the order in the CMS.

**Additional info**
- Craft version: 3.4.27
- Commerce version: 3.1.1
- PHP version: 7.4.7
- Database driver & version: MySQL 8.0.20
- Other Plugins & versions:

**Comment by nfourtythree** [comment]
Hi @simeon-smith 

I have just tried this on the latest version of Commerce and it seems to be working as expected.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/6qu2o4Gp/Screen%20Recording%202020-07-10%20at%2010.03%20am.gif?v=15d162f25315c644537a5b0368083223)

Thanks.

**Comment by simeon-smith** [comment]
@nfourtythree, figured it out. I was using this in JavaScript and json_encoding it produces an object with the ids as keys instead of an array. Since JavaScript automatically sorts objects it was reordering by ID.
