### ISSUE TITLE
makePrimaryBillingAddress and makePrimaryShippingAddress not working when creating new address from front end

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1562]
**Description**
When creating a new address from a front end form, `makePrimaryBillingAddress` and `makePrimaryShippingAddress` are ignored on save. It is not until after the address is saved that it can be set as primary billing and/or shipping address.

**To Reproduce**
How, and what happened?
1. From a front end form, enter a new address and select a checkbox to make the address primary for billing and/or shipping.
2. Save the new address.
3. Check the new address in front end or CP. Address saved all data except `makePrimaryBillingAddress` and `makePrimaryShippingAddress` properties.

**Expected behavior**
Expected primary billing and shipping properties to be set on save of new address. I believe it used to work as expected but changed with one of the recent releases.

**Additional info**
- Craft version: Pro 3.4.27
- Commerce version: Pro 3.1.11
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Is this for the `commerce/customer-addresses/save` or `commerce/cart/update-cart` endpoint?

Thanks!

**Comment by jmauzyk** [comment]
@nfourtythree I'm noticing this behavior for the `commerce/customer-addresses/save` endpoint. I also just noticed that the behavior only happens when primary billing or shipping is not set on any other addresses. So, for example, when adding a new address to my account with a _Make Primary Billing_ option selected, if there are no existing addresses set as primary billing it will fail to set the new address as primary billing. However, if an existing address is set as primary billing it will successfully set the new address as the primary billing.

**Comment by nfourtythree** [comment]
Thanks for the further info, will take a look into it

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for the information that helped track down the issue.

We have just pushed an update that fixes this and it will be included in the next release.

Thanks!
