### ISSUE TITLE
Add multiple items to cart

### ISSUE THREAD

**Issue by ducxinh201** [craftcms/commerce#1564]
**What are you trying to do?**
I call request to add multiple items to cart, But only one item added to cart. It seem to limit only 1 item in cart.
```
action: commerce/cart/update-cart
purchasables[0][id]: 480393
purchasables[0][qty]: 5
purchasables[1][id]: 484662
purchasables[1][qty]: 1
```

**What's your proposed solution?**
Allow Add multiple items to cart

**Additional context**

**Comment by lukeholder** [comment]
Sounds like you are on the solo edition of craft commerce which limits one item in the cart at a time. Is that right?
