### ISSUE TITLE
Can't delete invalid line items

### ISSUE THREAD

**Issue by aNickzz** [craftcms/commerce#1567]
**Description**
I have a custom validator for line items. In the process of development, the validation requirements have changed, thus I have invalid items in my cart. I am unable to delete these items from the cart because the validation fails and the cart won't save. For now, I will disable validation briefly, but I'd like to know if this is perhaps a bug or maybe I've missed something. The validation scenario is always "default" even when deleting the item.

**To Reproduce**
How, and what happened?

1. Add an item to your cart (using `actionUpdateCart`)
2. Add a custom validator that marks the item in your cart as invalid
3. Try to remove the item from your cart (using `actionUpdateCart`)
4. The validation is called on the item to be deleted and it fails
5. The item is not removed from the cart
    a. For the duration of the request, the cart _thinks_ the item is removed.

**Expected behavior**
What did you expect to happen?

The line item is removed from the cart

**Additional info**

- Craft version: Craft Pro 3.4.22.1
- Commerce version: 3.1.7
- PHP version: 7.1.33
- Database driver & version: MySQL 5.7.30
- Other Plugins & versions: Available on request

**Comment by lukeholder** [comment]
@aNickzz I am not able to reproduce in Commerce 3.1.11. Screencast: https://jmp.sh/tJTOPQn

**Comment by aNickzz** [comment]
The "custom validator" I'm using is an `EVENT_BEFORE_VALIDATE` handler, since I couldn't work out how to effectively modify the rules applied to the line item class. Also, the validation logic is slightly complex as it involves parsing and checking values stored in the `->options` property.

```
Event::on(
	LineItem::class,
	LineItem::EVENT_BEFORE_VALIDATE,
	function (ModelEvent $modelEvent) {
		/**
		 * @var LineItem $lineItem
		 */
		$lineItem = $modelEvent->sender;

		$isBad = true;

		if ($isBad) {
			$lineItem->addError('options', 'is bad');
			$modelEvent->isValid = false;

			return;
		}
	}
);
```

**Comment by lukeholder** [comment]
If you move to `EVENT_DEFINE_RULES` then you should be fine as I demonstrated in the video.


```
Event::on(LineItem::class, Entry::EVENT_DEFINE_RULES, function(DefineRulesEvent $e) {

}
```

If you just want to validate a line item as it is added to the cart:

      ```php
      use craft\commerce\elements\Order;
      use craft\commerce\models\LineItem;
      use craft\commerce\events\LineItemEvent;
      use yii\base\Event;
     
      Event::on(
          Order::class,
          Order::EVENT_BEFORE_ADD_LINE_ITEM,
          function(LineItemEvent $event) {
              // @var LineItem $lineItem
              $lineItem = $event->lineItem;
              // @var bool $isNew
              $isNew = $event->isNew;
              // @var bool $isValid
              $isValid = $event->isValid; // set to false to stop it added to the cart.
              // ...
          }
      );
      ```
