### ISSUE TITLE
Locale/Site management per product type

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#157]
> Created by: Trevor Davis ([davist11@gmail.com](davist11@gmail.com)) on 2018/01/19 22:57:44 +0000
Votes at time of UserVoice import: 10

------
You should be able to select which locale/site each product type is available in, the same way you can control it at the Section level.

**Comment by jsunsawyer** [comment]
Yes! (Assuming you're talking about the "Propagate entries across all enabled sites?" option.)

This is completely crushing our dreams of merging two sister commerce sites that share the same template files. Both sites have a unique set of products. If we merged these sites, it'd be hard to tell which product belongs to which site.

We just ran into this issue for multi-site categories as well. https://github.com/craftcms/cms/issues/2122

Would be nice if everything worked consistently.

**Comment by davist11** [comment]
Any potential plans for this? We have a large commerce site with a lot of extra records since the products are technically available on every site but only need to be available on one.

**Comment by lukeholder** [comment]
Will address this when we get to multi-store which will work with multi-site

**Comment by lukeholder** [comment]
Duplicate of #37 

(#39 also included now in #37)

**Comment by davist11** [comment]
Is it possible to remove my email address from the original issue description? 😅

**Comment by angrybrad** [comment]
@davist11 done!
