### ISSUE TITLE
GraphQL: hasVariant products query argument extension

### ISSUE THREAD

**Issue by yingban** [craftcms/commerce#1570]
Hi !

I am trying to get products filtered by variant attributes.
It is working well with 'hasSales' since last update. 

Would it possible to add Craft Commerce API built-in dimensions (width, height and length) as arguments to hasVariant product query, as well as price array argument like with date (['and', '>= 2018-04-04', '< 2018-05-01']) ?
Also, would it possible to extend the range query argument to any custom field with Int/Float type?

For example
`query Variants($colour: [QueryArgument]) { variants( colour: $colour, width: ['and', '> 100', '< 200'], height: 200, price: ['and', '> 10', '< 10'] ) { id } }`

Or is there any way do to it already with GraphQL?

**Comment by nfourtythree** [comment]
Hi @yingban 

Thank you for the feature request.

Querying by variant dimensions has now been added to the variant element query and also the GraphQL queries.

This will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in you project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#37683f347dc538b9407d3b439d2afd87f73c8c60 as 3.1.12",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by yingban** [comment]
Hi @nfourtythree !

Thank you very much for your reactivity and the feature, it works great !

It has been two years I do some lobby at my company to work with Craft CMS and Commerce, it would have been bad for me if I could not do that products filtering :-)
