### ISSUE TITLE
Variable "categoryRelationshipType" does not exist.

### ISSUE THREAD

**Issue by Maximilian-Schwarz** [craftcms/commerce#1571]
**Description**
Twig Runtime Error – Twig\Error\RuntimeError
Variable "categoryRelationshipType" does not exist.
1. in /var/www/html/vendor/craftcms/commerce/src/templates/promotions/discounts/_edit.html

This happens after the upgrade to craft commerce 3.1.12

**To Reproduce**
How, and what happened?
1. `In the CP click on Sales->Discount->Edit a Discount`

**Additional info**
- Craft version: 3.4.27
- Commerce version: 3.1.12
- PHP version: 7.3

**Comment by nfourtythree** [comment]
Hi @Maximilian-Schwarz 

Could you please provide a stack trace for this error, it will help us track down the issue.

I can't seem to reproduce it locally.

Thanks.

**Comment by Maximilian-Schwarz** [comment]
`Twig\Error\RuntimeError: Variable "categoryRelationshipType" does not exist. in /var/www/html/vendor/craftcms/commerce/src/templates/promotions/discounts/_edit.html:182
Stack trace:
#0 /var/www/html/storage/runtime/compiled_templates/14/14a6faf99ccc66aa4972fff620533c45128c1198e73dfb6ae0f1aef358680742.php(301): __TwigTemplate_d8ce0ca7f40939d567fe0085ff552dea50094c7739bc333a97ada23a3c1b18c1->{closure}()
#1 /var/www/html/vendor/twig/twig/src/Template.php(184): __TwigTemplate_d8ce0ca7f40939d567fe0085ff552dea50094c7739bc333a97ada23a3c1b18c1->block_content(Array, Array)
#2 /var/www/html/storage/runtime/compiled_templates/c1/c10780a12bb81501efb1983abbc06e7b9045e71c09b39fbdc06f9160c939bfff.php(411): Twig\Template->displayBlock('content', Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(184): __TwigTemplate_73f152753aa39263630d455320e0bf49660957d676ad397618fb6d26450ebb6d->block_main(Array, Array)
#4 /var/www/html/storage/runtime/compiled_templates/c1/c10780a12bb81501efb1983abbc06e7b9045e71c09b39fbdc06f9160c939bfff.php(266): Twig\Template->displayBlock('main', Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Template.php(184): __TwigTemplate_73f152753aa39263630d455320e0bf49660957d676ad397618fb6d26450ebb6d->block_body(Array, Array)
#6 /var/www/html/storage/runtime/compiled_templates/5b/5b73ddd06bf24ffd893a0201db84a959fbaa4e9cfd62112a32607524ab85d6d4.php(75): Twig\Template->displayBlock('body', Array, Array)
#7 /var/www/html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_1708096b567c48bd145aae5dda8228d08baa1df568d8963ef887321060d248ed->doDisplay(Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /var/www/html/storage/runtime/compiled_templates/dc/dc679540b6e82969b15e71828b3bc8126eb590f31e03bd1b269b079fb269bdbe.php(56): Twig\Template->display(Array, Array)
#10 /var/www/html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_3dc827453dc44f466a3b098ad9fdae0fbfc405dfa9afee858562c45f7cc25999->doDisplay(Array, Array)
#11 /var/www/html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /var/www/html/storage/runtime/compiled_templates/c1/c10780a12bb81501efb1983abbc06e7b9045e71c09b39fbdc06f9160c939bfff.php(138): Twig\Template->display(Array, Array)
#13 /var/www/html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_73f152753aa39263630d455320e0bf49660957d676ad397618fb6d26450ebb6d->doDisplay(Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /var/www/html/storage/runtime/compiled_templates/10/10922e41e4d1bb2638f61ba3f7487c45b3daf4f6aa69eadada8c3ff1e6220073.php(46): Twig\Template->display(Array, Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_23c37954f44b21e162a88788b0896710fe0d1ea1bc4e391aebdd9bb76a2bf183->doDisplay(Array, Array)
#17 /var/www/html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/html/storage/runtime/compiled_templates/14/14a6faf99ccc66aa4972fff620533c45128c1198e73dfb6ae0f1aef358680742.php(146): Twig\Template->display(Array, Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_d8ce0ca7f40939d567fe0085ff552dea50094c7739bc333a97ada23a3c1b18c1->doDisplay(Array, Array)
#20 /var/www/html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/html/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#22 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#23 /var/www/html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#24 /var/www/html/vendor/craftcms/cms/src/web/View.php(375): Twig\Environment->render('commerce/promot...', Array)
#25 /var/www/html/vendor/craftcms/cms/src/web/View.php(436): craft\web\View->renderTemplate('commerce/promot...', Array)
#26 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('commerce/promot...', Array, 'cp')
#27 /var/www/html/vendor/craftcms/commerce/src/controllers/DiscountsController.php(85): craft\web\Controller->renderTemplate('commerce/promot...', Array)
#28 [internal function]: craft\commerce\controllers\DiscountsController->actionEdit(3, NULL)
#29 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('edit', Array)
#32 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit', Array)
#33 /var/www/html/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('commerce/discou...', Array)
#34 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('commerce/discou...', Array)
#35 /var/www/html/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#36 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /var/www/html/web/index.php(21): yii\base\Application->run()
#38 {main}`

**Comment by nfourtythree** [comment]
Hi @Maximilian-Schwarz 

It looks like this is coming from your compiled templates if you clear those via `Utilities > Clear Caches > Compiled Templates` you should be good to go.

Thanks!

**Comment by Maximilian-Schwarz** [comment]
Ah perfect. Thanks i clear the cache and everything is working. I'm sorry for the trouble.
