### ISSUE TITLE
Ability to customize transaction hash

### ISSUE THREAD

**Issue by Mosnar** [craftcms/commerce#1573]
**What are you trying to do?**
The gateway I've been working on is for Authorize.Net - one of its many quirks is that the transaction ID has a maximum length of 20 characters. I've been working around this for a while by truncating the transaction hash provided by Commerce; however, this always felt cryptographically sketchy to me. Additionally, it forces me to use a `LIKE` query to find the transaction when a webhook reports back with the truncated transaction hash.

Reference: https://developer.authorize.net/api/reference/index.html#payment-transactions (Click "REQUEST FIELD DESCRIPTION" and see "refId")

**What's your proposed solution?**
I would suggest providing some kind of idiomatic method with Commerce to produce a transaction hash of a certain length and/or format. Ideally, Authorize.net would fix this, but as we all know, these old-school payment providers do not move quickly.

**Comment by lukeholder** [comment]
Truncating the transaction hash provided by Commerce is the way to go in the custom gateway. 20 chars is still unique enough to no be guessable, and if thats the limit for auth.net then a random hash to a limit of 20 chars is the best we can do anyway.
