### ISSUE TITLE
Commerce Plugin - Enabling fullname for firstname and lastname and shortform for year

### ISSUE THREAD

**Issue by chandamotiyani** [craftcms/commerce#1578]
### Description

As per the https://docs.craftcms.com/commerce/v2/payment-form-models.html documentation here Commerce plugin has a first name and last name as required, what if we want to just use the full name instead. I guess that option isn't available and also for the year we need to pass full-year what if we want to pass the short year like for 2020 only 20. There is no option of doing such changes.

Or if it is then where to find documentation for that?

**Comment by lukeholder** [comment]
@chandamotiyani 

In Commerce 2 you can use the `EVENT_REGISTER_ADDRESS_VALIDATION_RULES` event: https://docs.craftcms.com/commerce/v2/events.html#the-registeraddressvalidationrules-event

This lets you remove the required firstName and lastName and make the fullName required instead.

In Commerce 3 the first and last name are no longer required (no fields are required on addresses).

Hope that helps.
