### ISSUE TITLE
‘Make Payment’ form doesn’t work with registered JS files or asset bundles

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/commerce#1583]
**Description**

Calling `View::registerJsFile` or `View::registerAssetBundle` within `getPaymentFormHtml` doesn’t work in the ‘Make Payment’ under `/admin/commerce/orders/{orderId}#transactionsTab`.

**Expected behavior**

That the form would output the same as it does on the frontend.

**Additional info**
- Craft version: Craft Pro 3.4.28.1
- Commerce version: 3.1.12
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Other Plugins & versions: N/a

**Comment by nfourtythree** [comment]
Hi @joshuabaker 

Could you elaborate a little further on what exactly "doesn't work". Does the form not load? JS error? PHP error? Visual error?

What payment gateway are you using?

Thanks!

**Comment by joshuabaker** [comment]
To confirm, the `View::registerJsFile` seems to be the main issue here.

The gateway hasn’t been released yet but [these are the impacted lines](https://github.com/craftplugins/commerce-square/blob/e92370f51929af94bf5db6c9a23f30320bbf3e8c/src/gateways/SquareGateway.php#L350-L352), which closely resembles [this line](https://github.com/craftcms/commerce-stripe/blob/60ceaea65ae3c709e242bbd1d60fc7074dc7bdcc/src/gateways/Gateway.php#L151) in the Stripe gateway. I have tried without specifying the `position` too.

**Comment by nfourtythree** [comment]
Closing this issue for now. Happy to re-open if you have any further information on what is happening.

Thanks!

**Comment by joshuabaker** [comment]
@nfourtythree Would you mind reopening. This is one for me to look into further in the next few weeks. 😊
