### ISSUE TITLE
order.shippingMethod.name returning null

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1584]
**Description**
I am upgrading to the latest Craft Commerce version 3.1.12 and I am no longer able to view `order.shippingMethod.name` for a finished order

It returns a null value now but previously it was returning the user friendly name.

I am using this with Postie as well.

**To Reproduce**
How, and what happened?
1. Place an order
2. On the order confirmation page, call `{{ order.shippingMethod.name }}`

**Expected behavior**
Show the user friendly shipping method name

**Additional info**
- Craft version:  3.4.29.1
- Commerce version: 3.1.12
- PHP version: 7.4
- Database driver & version: MySQL 8
- Other Plugins & versions:

**Additional context**

**Comment by lukeholder** [comment]
What is the contents of `order.shippingMethodHandle` on the order ? (Maybe check the DB)

**Comment by keyurshah** [comment]
I get the proper value when I output that, which in my case is: `FLAT_RATE_SHIPPING`

`{{ order.shippingMethodId }}` is also null

**Comment by Mosnar** [comment]
Also had this issue, also using Postie. After updating, the shipping method in my receipt emails started returning "Free Shipping" even though that option is entirely disabled. I ended up getting the name from the shipping adjuster instead.

**Comment by GaryReckard** [comment]
I am also noticing the issue @Mosnar mentioned. I am on Craft CMS 3.4.25, also using Postie, v2.2.5. I just tested an upgrade from Commerce 3.1.9 => 3.1.12, and every order has "Free Shipping" as the shipping method after completing the order, even thought that shipping method isn't enabled.
