### ISSUE TITLE
Sale Promotion Not Applied When Editing an Order

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce#1587]
**Description**
At a high level, what's happened is a customer checks out during a sale and then wants us to add an item to their order. If we add the item to their order it's added at the retail price of the item.

**To Reproduce**
How, and what happened?
1. As a customer, complete an order with a promotion
2. Afterwards as an admin, try to add a item during a promotion
3. Additionally, if you recalculate it doesn't apply either.

**Expected behavior**
What did you expect to happen?
When adding an order in the admin we expect the sale prices to pull over as they would a customer.

**Additional info**
- Craft version: Craft Pro 3.4.28.1
- Commerce version: 3.1.9
- PHP version: 7.3
- Database driver & version: Mysql 5.7
- Other Plugins & versions:
Amazon S3	1.2.8
Cookies	1.1.12
Craft Commerce	3.1.9
Doxter	3.4.9
Instant Analytics	1.1.7
Linkit	1.1.11
oEmbed	1.3.4
Redactor	2.6.1
Retour	3.1.39
SEOmatic	3.3.8
Similar	1.0.6
Stripe for Craft Commerce	2.3.1.1
Twigpack	1.2.3

**Additional context**

**Comment by lukeholder** [comment]
If the correct customer is applied to the order and the order is recalculated, the salePrice should apply as it would to a customer checking out on the front end.

When pressing 'recalculate order', in addition to recalculating the sale price, it will also recalculate the adjustments (discounts/tax/shipping) on the order.

This will not happen when you just add an item to the cart, as we don't want to recalculate the whole order without having the editor doing so explicitly.

**Comment by lukeholder** [comment]
We could do better to document this. Will do so soon.
