### ISSUE TITLE
Event for beforeDuplicatedElemenetSaved

### ISSUE THREAD

**Issue by Maximilian-Schwarz** [craftcms/commerce#1589]
**What are you trying to do?**
I have a custom plugin which automatically set's the SKU for new products. Everything is working. But if i want to duplicate a product the duplicateElement() function override my custom values.

**What's your proposed solution?**
I think it's a good solution to add an event to add custom "$newAttributes" to the clone.

**Comment by lukeholder** [comment]
@Maximilian-Schwarz can you explain how are you setting the SKU? Could you share what you are doing in more detail please. Duplication will copy everything about the existing product and its variants, adding a `-1` to the end of the SKU so that it remains unique.

**Comment by Maximilian-Schwarz** [comment]
The plugin is listing to the event "EVENT_BEFORE_SAVE_ELEMENT". Here i get all variants loop over them and set the new SKU for each variant.

**Comment by lukeholder** [comment]
Closing this as stale. Can you give full steps to reproduce and we can take a look again.
