### ISSUE TITLE
Commerce update has converted characters to HTML entities in order line item snapshots

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#1592]
**Description**
I have recently updated a site and this included updating Craft Commerce from 2.x to 3.1.12. 

Since performing the update, I have noticed that in previous order entries, some product titles have had their characters converted into HTML entities. 

The product entries themselves have not been affected, it is just the snapshot description for line items in previous orders - see screenshot.

<img width="569" alt="Screenshot 2020-07-27 at 15 00 47" src="https://user-images.githubusercontent.com/6592882/88550763-f5833d00-d019-11ea-8fdf-c442b97d2950.png">

Do you know why this has happened, and is there any way to convert them back? The client still needs to send out invoices / emails for some of these orders, so this issue is being carried across into them. As a temporary fix, I have addded the `|raw` filter to the description tags within the invoice and emails. 

But I would still like to get these converted to their original state in the CMS as well.

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

I have just tried to replicate this locally and I can't seem to reproduce what you are seeing. When I retrieve an order via an element query or in an ajax response it seems they are all showing as expected.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/lluYpdNy/Screenshot%202020-09-14%20at%2011.04.47.png?v=84c1f6ec7d34e1ec8b67206f802ee138)

Is this still an issue for you, are you up to date with the latest Commerce release?

Thanks.

**Comment by nfourtythree** [comment]
Hi

I am going to close this issue for now. If the problem still persists please update this issue with steps on how to reproduce and I will reopen it and further investigate.

Thanks!
