### ISSUE TITLE
Shift VAT exceptions

### ISSUE THREAD

**Issue by karensg** [craftcms/commerce#1593]
**What are you trying to do?**
My business is in the Netherlands. I would like to apply tax for all European countries except Netherlands. That is possible by creating 2 tax rates (NL & EU). However, my prices already include VAT and that option can only be applied to 1 tax rate.

**What's your proposed solution?**
2 options: (1) either we can add a field to exclude VAT shift for certain countries or (2) be able to have included tax for not only default tax rate. The first option is probably the most convenient.

**Additional context**
In Europe, you have to always charge VAT, but can shift it for the EU companies from abroad.

**Comment by lukeholder** [comment]
> my prices already include VAT

If you have entered your prices to include a tax amount, that amount can only be for a single tax rate (amount).

I am sorry I am not sure exactly what you are asking?

>but can shift it for the EU companies from abroad.

If a business enters a valid VAT ID into the businessTaxId of the address, then the VAT will no be applied.

**Comment by karensg** [comment]
That is the thing. If the shop is in Europe, it has to apply VAT to the companies in the same country. It can, however, omit VAT for companies in other European countries. Likes this:
NL company sells to NL companies = we have to apply VAT
NL company sells to FR companies = we can omit VAT

The only way to achieve that is to create different tax regions (NL & EU without NL). Both have the same tax rate (21% in my case). However, then I can not answer `Is this tax is already included in the taxable subject?`-question with "Yes" twice.

Does it make more sense to you now?

**Comment by nfourtythree** [comment]
Hi @karensg 

Thanks for the further information.

I believe this can be solved with 1 x Tax Category, 2 x Tax Zones and 1 x Rate. 

**Zones**

- Europe - Country Based, all European countries except NL, Default: yes
- NL - Country Based, Only Netherlands selected

**Categories**

- General - Set to default and available to applicable Product Types

**Rates**

- General Tax - Zone: Europe, Category: General, Tax included: yes

Having things set up like this should see that the tax is included for European countries that aren't NL and will be removed if you have an NL address.

Hope this helps!

Thanks.

**Comment by karensg** [comment]
@nfourtythree, the tax should not be removed in NL, but only for European, non NL companies. 
What worked for me now, is adding a module which "breaks" the NL VAT number on entry save. But this is not ideal.

**Comment by nfourtythree** [comment]
Hi @karensg 

Thank you for your reply, glad you got things working for your project.

I am going to close this issue for now. If my previous solution does not work for your project then, unfortunately, I don't think I quite follow the brief that the project is adhering to.

If this continues to be an issue then it might be best to see a copy of your DB along with clear instructions (including expected prices) to support@craftcms.com this way we might be able to see what is happening.

Thanks.
