### ISSUE TITLE
Improve on-the-fly customer creation in the order editor.

### ISSUE THREAD

**Issue by mattstein** [craftcms/commerce#1594]
**What are you trying to do?**

In a fresh Commerce install, the very first step of creating an order in the control panel is confusing. 

I’m prompted to `Search...` an empty list for a customer, with the option to create whatever I’ve just entered. It’s not clear that I’m supposed to be entering an email address, so if I enter a name/username like `bob` I’ll get an “Invalid email.” error:

![not-bob](https://user-images.githubusercontent.com/2488775/88599463-6eda5a00-d031-11ea-8e3f-f21b4c6c2ef5.gif)

I think it’s reasonable to attempt to search by name or username, but there’s nothing to indicate a new customer requires entering an email address. The `Create “...”` option also seems to imply that `bob` should be valid.

**What's your proposed solution?**

I’d probably improve this by...

- Changing the `Search...` placeholder to `Search or enter customer email...` to better describe appropriate input.
- Not displaying the `Create “...”` option if an email address hasn’t been entered.
- Changing the `Create “...”` option’s default avatar icon to an envelope icon or something representing an email address, since that’s what we’re starting with and it’s already under the Customer field heading.

**Additional context**

<img width="1294" alt="examples" src="https://user-images.githubusercontent.com/2488775/88601274-e3af9300-d035-11ea-8bbc-1655f1e2b59a.png">

**Comment by nfourtythree** [comment]
Improvements have been made along the lines of @mattstein's suggestion.

These will be included in the next release.

Thanks.
