### ISSUE TITLE
Variant Doesn't Populate in Sale Form When Creating Sale from Product Page

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce#1595]
**Description**
When making a sale from the product page, the variant doesn't automatically populate in the matching items tab. Guessing this is the root of it, but the link it takes you to is `/admin/commerce/promotions/sales/new?purchasableIds=null`

**To Reproduce**
How, and what happened?
1. In the CP, go to any product page without any sales associated to it
2. Click "Add all to Sale"
3. In the modal that pops up, click "Create Sale"
4. You should not see a variant show up

**Expected behavior**
Believe this is a regression in Commerce 3, but would expect the sale to be created with the variant populated in matching items

**Additional info**
- Craft version: Craft Pro 3.4.29.1
- Commerce version: 3.1.12
- PHP version: 7.3
- Database driver & version: Mysql 5.7.12
- Other Plugins & versions:

```
Amazon S3	1.2.9
Cookies	1.1.12
Craft Commerce	3.1.12
Doxter	3.4.9
Instant Analytics	1.1.7
Linkit	1.1.11
oEmbed	1.3.4
Redactor	2.6.1
Retour	3.1.39
SEOmatic	3.3.8
Similar	1.0.6
Stripe for Craft Commerce	2.3.1.1
Twigpack	1.2.3
```

**Comment by nfourtythree** [comment]
Hi @dhahn 

Thank you for bringing this to our attention.

We have pushed a fix that will be included in the next release.

Thanks!
