### ISSUE TITLE
Add "cp.commerce.order.edit.details" hook in templates/orders/_edit at the end of block details

### ISSUE THREAD

**Issue by GaryReckard** [craftcms/commerce#1597]
**What are you trying to do?**
I'd like to add some custom functionality in the details pane on the right side of the Order edit page. The closest hook I've found is the "cp.commerce.order.edit.main-pane". Currently using some JS to move my code from there to the end of #details div, but it would be convenient to have a hook there.

**What's your proposed solution?**
At the end of this block: https://github.com/craftcms/commerce/blob/c81a22f2f790c572002f7587306f589e3cb3ba7b/src/templates/orders/_edit.html#L167-L169
Add
`{% hook "cp.commerce.order.edit.details" %}`

**Comment by lukeholder** [comment]
Fixed in e21985a6c202865bf412e3903054524033f9b921 will be in the next release.

**Comment by GaryReckard** [comment]
Thanks, Luke!!
