### ISSUE TITLE
Bulk-download invoice PDFs from the Orders index page

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#1598]
It should be possible to select multiple orders from the Orders index page, and click a “Download PDF” button at the top, to download invoice PDFs for each of them, as a zip file (similar to how bulk asset downloads work).

**Comment by lukeholder** [comment]
This is now possible in the imminent release of Commerce 3.2

You can download multiple PDFs from the Order index page, and they will be delivered in a zip archive.
