### ISSUE TITLE
Ability to Eagerload Purchasables and Products to Orders

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce#1603]
**What are you trying to do?**
I'd love to be able to eagerload lineItems, purchasables/variants, and products onto an order. In this case, when I run something like:

```
        foreach ($order->getLineItems() as $item) {
            $item->purchasable->product->hsCode;
        }
```

it produces a few n+1s without a way to get around it.

**What's your proposed solution?**

Would love to just be able to do something like this:

```
        $order = Order::find()
            ->with([
                'lineItems',
                'lineItems.purchasable',
                'lineItems.purchasable.product'
            ])
            ->id(2138648)
            ->one();
```

**Comment by sjelfull** [comment]
+1. Recently built a custom reporting page, and easily reached 10000+ queries.

This would have saved me writing custom queries for this.

**Comment by Anubarak** [comment]
I would totally love this. I had to write a 500+ lines script for eager load everything and went down from 20.000 Queries to 150 Queries. Craft Commerce in it's current state is a query heavy mess sometimes. I really hope they are going to improve the performance for reports/order lists in the future. 

There are many functions that query elements again and again with no caching and there is nearly no way around it.
I started to build caching wrappers for so many Commerce functions. You can't even call `$order->getEmail()` [without performance issues](https://github.com/craftcms/commerce/issues/1469#issuecomment-642120154)

**Comment by lukeholder** [comment]
OK added this for the next release:

- Added the ability to eager load line items, transactions and adjustments with the `withLineItems`, `withTransactions`, `withAdjustments` order query params.

```twig
{% for order in craft.orders.limit(100).all() %}
<strong>{{ order.id }}</strong>
<ul>
<li>Line Items: {{ order.lineItems|length }}</li>
<li>Transactions: {{ order.transactions|length }}</li>
<li>Adjustments: {{ order.adjustments|length }}</li>
</ul>
{% endfor %}
```
= 300+ queries

```twig
{% for order in craft.orders.withAdjustments().withTransactions().withLineItems().limit(100).all() %}
<strong>{{ order.id }}</strong>
<ul>
<li>Line Items: {{ order.lineItems|length }}</li>
<li>Transactions: {{ order.transactions|length }}</li>
<li>Adjustments: {{ order.adjustments|length }}</li>
</ul>
{% endfor %}
```
= 4 queries

We can't use the normal `with` eager loading as that is reserved for elements only in core. This is the best we can do for now. When GraphQL support is added to orders, the eager loading will happen by default for these child records of an order 👍

**Comment by dhahn** [comment]
This is amazing! And so quick!

What do you think about extending this to variants and products from the line item?

Perhaps `withLineItems()` can take an arg of what it can eager load? Something like `withLineItems()`

**Comment by lukeholder** [comment]
I am currently adding support for more eager loaded things on the order like addresses and customers. Will also be in the next release.

The issue with eager loading the products/purchasables is that it is it isn't just commerce variants that could be eager loaded - some installs have custom purchasables like digital products or tickets etc, and since we only store the purchasableId on the line item, I can't do a multi-element query to get them all. If we stored the purchasable type on the line item we could do it a query per element type. Adding the type name to the line item would need a migration, and not sure we will get this into the next release at this point.

Can you submit a new ticket/issue/FR for eager-loading purchasables on order line items? Will get it after the release it out. Thanks.

**Comment by lukeholder** [comment]
@dhahn ^

**Comment by dhahn** [comment]
yeah absolutely! Thanks for the detailed response totally makes sense

**Comment by lukeholder** [comment]
Added support for eager loading order related customers, users, and addresses.

`withAddresses`
`withCustomer` (loads the user too)

**Comment by lukeholder** [comment]
Gotten a large 1000+ order index queries down to ~60 db queries. Super fast.

**Comment by Anubarak** [comment]
@lukeholder Thank you so much.
This is really awesome and makes my life so much easier.
