### ISSUE TITLE
GraphQL variant query sales attributes

### ISSUE THREAD

**Issue by yingban** [craftcms/commerce#1607]
Hi!

I am trying to get sales attributes in a variant query with the following code 
`query  {
  variant(id: 690) {
    id
    title
    price
    salePrice
    sales {
      name
      description
    }
  }
}`

it seems that only name and description attributes are available in the API.
Would it possible to add the "Effect" attribute to the response?

Thank you in advance.

**Comment by nfourtythree** [comment]
Hi @yingban 

We have added the following return data along with `name` and `description`. These will be in the next release of Commerce.

```
apply
applyAmount
applyAmountAsPercent
applyAmountAsFlat
dateFrom
dateTo
```

Thanks.

**Comment by yingban** [comment]
@nfourtythree awesome, thanks
