### ISSUE TITLE
Improve Documentation around using Custom Fields for Carts/Orders.

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce#1609]
**What are you trying to do?**
I need fields to store some custom values during the checkout process. Things like ship as quickly as possible and agree to terms.

**What's your proposed solution?**
Add a few customField{#} to the cart/order so that these can be stored in them.

**Comment by simeon-smith** [comment]
NVM, I was able to find out how to do this. Going to change it to a request to improve the documentation around it.

**Comment by nfourtythree** [comment]
Thanks.

Will be added as part of craftcms/docs#28

**Comment by yingban** [comment]
Hi @simeon-smith!
Could you please tell me how you did it? 
Thanks
