### ISSUE TITLE
Product Titles not rendered in Field Layout

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#1613]
**Description**
After the 3.2 update, Product `title` fields are no longer rendered as part of their Field Layouts.

**To Reproduce**
How, and what happened?
1. Create a Product Type _with manual titles_. Other options don't matter.
2. Ensure title is present somewhere in Field Layout settings
3. Visit Product Edit screen
4. Title does not appear

(Existing Product Types have the same issue!)

**Expected behavior**
😄

**Additional info**
- Craft version: 3.5
- Commerce version: 3.2.0.1
- PHP version: 7.4.8
- Database driver & version: Postgres
- Other Plugins & versions: —

**Additional context**
PR Incoming!

**Comment by lukeholder** [comment]
Fixed in 3.2.0.2
