### ISSUE TITLE
3.2.0.2 `_updateFieldLayoutConfig` update error

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1615]
Trying to update to Craft 3.5 and Commerce 3.2.0.2

```
One of Craft Commerce’s migrations failed.

TypeError: Argument 1 passed to craft\commerce\migrations\m200730_233644_field_layout_changes::_updateFieldLayoutConfig() must be of the type array, null given, called in /Users/joshcrawford/public_html/site/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php on line 74

Migration: craft\commerce\migrations\m200730_233644_field_layout_changes

Output:

> drop column titleLabel from table {{%commerce_producttypes}} ... done (time: 0.051s)
> drop column variantTitleLabel from table {{%commerce_producttypes}} ... done (time: 0.044s)
Exception: Argument 1 passed to craft\commerce\migrations\m200730_233644_field_layout_changes::_updateFieldLayoutConfig() must be of the type array, null given, called in /Users/joshcrawford/public_html/site/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php on line 74 (/Users/joshcrawford/public_html/site/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php:97)
#0 /Users/joshcrawford/public_html/site/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php(74): craft\commerce\migrations\m200730_233644_field_layout_changes->_updateFieldLayoutConfig(NULL)
#1 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\migrations\m200730_233644_field_layout_changes->safeUp()
#2 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(228): craft\db\Migration->up(true)
#3 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\commerce\migrations\m200730_233644_field_layout_changes))
#4 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Updates.php(227): craft\db\MigrationManager->up()
#5 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#6 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#7 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#8 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#10 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('migrate', Array)
#11 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#12 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('updater/migrate', Array)
#13 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(684): craft\web\Application->runAction('updater/migrate')
#14 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(227): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#15 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /Users/joshcrawford/public_html/site/public_html/index.php(30): yii\base\Application->run()
#17 {main}
```

**Additional info**
- Craft version: 3.5.0
- Commerce version: 3.2.0.2
- PHP version: 7.0

**Comment by lukeholder** [comment]
We can't reproduce this. Could you have modified your project config manually or had a bad merge? Or possibly rebuilt the project config before an update?

**Comment by lukeholder** [comment]
We also have not had any other reports of this as yet.

**Comment by engram-design** [comment]
Who knows, will close

**Comment by tobiaskrueger** [comment]
Got the exact same error, when i try to update Craft Commerce.

Following updates are available for Craft Commerce:

3.2.1
3.2.0.2
3.2.0.1
3.2.0

My setup:

PHP version: 7.1.31
OS version: Linux 4.4.0-81-generic
Database driver & version: MySQL 5.5.5
Craft edition & version: Craft Pro 3.5.2

```TypeError: Argument 1 passed to craft\commerce\migrations\m200730_233644_field_layout_changes::_updateFieldLayoutConfig() must be of the type array, null given, called in /var/www/cms.project.test/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php on line 74

Migration: craft\commerce\migrations\m200730_233644_field_layout_changes

Output:

> drop column titleLabel from table {{%commerce_producttypes}} ... done (time: 0.030s)
> drop column variantTitleLabel from table {{%commerce_producttypes}} ... done (time: 0.025s)
Exception: Argument 1 passed to craft\commerce\migrations\m200730_233644_field_layout_changes::_updateFieldLayoutConfig() must be of the type array, null given, called in /var/www/cms.project.test/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php on line 74 (/var/www/cms.project.test/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php:97)
#0 /var/www/cms.project.test/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php(74): craft\commerce\migrations\m200730_233644_field_layout_changes->_updateFieldLayoutConfig(NULL)
#1 /var/www/cms.project.test/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\migrations\m200730_233644_field_layout_changes->safeUp()
#2 /var/www/cms.project.test/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#3 /var/www/cms.project.test/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\commerce\migrations\m200730_233644_field_layout_changes))
#4 /var/www/cms.project.test/vendor/craftcms/cms/src/services/Updates.php(227): craft\db\MigrationManager->up()
#5 /var/www/cms.project.test/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#6 /var/www/cms.project.test/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#7 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#8 /var/www/cms.project.test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/cms.project.test/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/cms.project.test/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('migrate', Array)
#11 /var/www/cms.project.test/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#12 /var/www/cms.project.test/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('updater/migrate', Array)
#13 /var/www/cms.project.test/vendor/craftcms/cms/src/web/Application.php(684): craft\web\Application->runAction('updater/migrate')
#14 /var/www/cms.project.test/vendor/craftcms/cms/src/web/Application.php(247): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#15 /var/www/cms.project.test/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /var/www/cms.project.test/web/index.php(21): yii\base\Application->run()
#17 {main}```

**Comment by arthurdewolf** [comment]
We are also running into this error when updating Commerce from 3.2.x-dev to 3.2.1

`> add column shippingMethodName string to table {{%commerce_orders}} ... done (time: 0.015s)
    > update in {{%commerce_orders}} ... done (time: 0.640s)
    > update in {{%commerce_orders}} ... done (time: 0.072s)
    > update in {{%commerce_orders}} ... done (time: 0.063s)
    > update in {{%commerce_orders}} ... done (time: 0.087s)
    > drop column titleLabel from table {{%commerce_producttypes}} ... done (time: 0.036s)
    > drop column variantTitleLabel from table {{%commerce_producttypes}} ... done (time: 0.032s)
Exception: Argument 1 passed to craft\commerce\migrations\m200730_233644_field_layout_changes::_updateFieldLayoutConfig() must be of the type array, null given, called in /var/www/project/cms/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php on line 74 (/var/www/project/cms/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php:97)
#0 /var/www/project/cms/vendor/craftcms/commerce/src/migrations/m200730_233644_field_layout_changes.php(74): craft\commerce\migrations\m200730_233644_field_layout_changes->_updateFieldLayoutConfig(NULL)
#1 /var/www/project/cms/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\migrations\m200730_233644_field_layout_changes->safeUp()
#2 /var/www/project/cms/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#3 /var/www/project/cms/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\commerce\migrations\m200730_233644_field_layout_changes))
#4 /var/www/project/cms/vendor/craftcms/cms/src/services/Updates.php(227): craft\db\MigrationManager->up()
#5 /var/www/project/cms/vendor/craftcms/cms/src/console/controllers/MigrateController.php(328): craft\services\Updates->runMigrations(Array)
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /var/www/project/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/project/cms/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/project/cms/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('all', Array)
#10 /var/www/project/cms/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#11 /var/www/project/cms/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#12 /var/www/project/cms/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#13 /var/www/project/cms/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#14 /var/www/project/cms/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /var/www/project/cms/craft(22): yii\base\Application->run()
#16 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft Commerce.'

in /var/www/project/cms/vendor/craftcms/cms/src/services/Updates.php:235`
