### ISSUE TITLE
After an order is complete: a native way to know if the Shipping and Billing Address are the same. 

### ISSUE THREAD

**Issue by outline4** [craftcms/commerce#1616]
**The Problem**
On the checkout page it's easy to determine if a shipping and billing address are the same. It can be done via the id. If the id is the same, they are the same.  

But when an order is complete, the shipping address and the billing address get two different id's and there's no easy way to determine if they are the same. 

**Workaround**
During checkout you can set a field that will hold this information (e.g. cf_sameAddress_lightswitch) and then you are able to call this variable in the email templates and other frontend templates. 

	<input type="hidden" name="fields[cf_sameAddress_lightswitch]" value="{{ cart.shippingAddress.id == cart.billingAddress.id ? 1 : 0 }}">

**What's your proposed solution?**
Please set the `shippingSameAsBilling` and the `billingSameAsShipping` in the order object. These values are there, but always null. Or add a new variable like "sameAddress" that you could access with `order.sameAddress`.

Also the `makePrimaryShippingAddress` and `makePrimaryBillingAddress` are always null. These could be set as well and used in a template. Like: `{% if order.makePrimaryShippingAddress %}This is your new primary shipping address{% endif %}`

**Comment by lukeholder** [comment]
For the next release I have added the ability to compare address objects:

```twig
 {%  if order.shippingAddress.sameAs(order.billingAddress) %}
 <p>Addresses are the same</p>
 {% endif %}
```

This will allow you to compare the addresses before or after completing an order to know if they contain the same values.
