### ISSUE TITLE
Orders overview in backend: A server error occurred

### ISSUE THREAD

**Issue by goellner** [craftcms/commerce#1617]
**Description**
Getting a "A server error occurred." after updating Craft and Commerce to latest versions. 

**To Reproduce**
How, and what happened?
1. `In the CP go to admin/commerce/orders`
2. Click on list all.
3. A server error occurred.

**Expected behavior**
See a list of orders.
**Additional info**
- Craft version: 3.5
- Commerce version: 3.2.0.2
- PHP version: 7.2

**Additional context**
We have some old orders, with a deleted payment gateway. The old orders are referencing the ID 1 of payment gateways, which does not exist anymore. Is there any way to delete all orders manually?

**Comment by nfourtythree** [comment]
Hi @goellner 

Could you please provide a stack trace for the error as I am unable to replicate this issue.

Thanks!

**Comment by lukeholder** [comment]
@goellner Thanks, fixed for the next release.

btw gateways are never deleted from the DB, just archived.
