### ISSUE TITLE
Calling unknown method: craft\commerce\models\LineItem::hasStock()

### ISSUE THREAD

**Issue by mofman** [craftcms/commerce#1619]
**Description**
Not able to add product to basket

**To Reproduce**
How, and what happened?
1. Try to add product to basket

Calling unknown method: craft\commerce\models\LineItem::hasStock()

**Expected behavior**
What did you expect to happen?

**Additional info**
- Craft version: 3.5
- Commerce version: 3.2
- PHP version: 7.2

**Comment by bhashkar007** [comment]
@mofman I am getting the same issue. Did you get any solution of it?

**Comment by nfourtythree** [comment]
Hi @bhashkar007 

Could you please provide a stack trace for the error that you are receiving.

Thanks!

**Comment by mofman** [comment]
@bhashkar007 check to make sure you are using the latest version 3.2 - i believe i had been messing with the composer.json file and had somehow downgraded to 2.2.

**Comment by bhashkar007** [comment]
Hi @nfourtythree 
Please see below:
`yii\base\UnknownMethodException: Calling unknown method: craft\commerce\models\LineItem::hasStock() in /home/demo2/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /home/demo2/vendor/craftcms/commerce/src/elements/Variant.php(639): yii\base\Component->__call('hasStock', Array)
#1 /home/demo2/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\commerce\elements\Variant->craft\commerce\elements\{closure}('qty', NULL, Object(yii\validators\InlineValidator), 1)
#2 /home/demo2/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\commerce\models\LineItem), 'qty')
#3 /home/demo2/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\commerce\models\LineItem), Array)
#4 /home/demo2/vendor/craftcms/commerce/src/base/OrderValidatorsTrait.php(123): yii\base\Model->validate()
#5 /home/demo2/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\commerce\elements\Order->validateLineItems('lineItems', NULL, Object(yii\validators\InlineValidator), Array)
#6 /home/demo2/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\commerce\elements\Order), 'lineItems')
#7 /home/demo2/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\commerce\elements\Order), Array)
#8 /home/demo2/vendor/craftcms/commerce/src/controllers/CartController.php(357): yii\base\Model->validate()
#9 /home/demo2/vendor/craftcms/commerce/src/controllers/CartController.php(340): craft\commerce\controllers\CartController->_returnCart()
#10 [internal function]: craft\commerce\controllers\CartController->actionUpdateCart()
#11 /home/demo2/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /home/demo2/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#13 /home/demo2/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('update-cart', Array)
#14 /home/demo2/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('update-cart', Array)
#15 /home/demo2/vendor/craftcms/cms/src/web/Application.php(280): yii\base\Module->runAction('commerce/cart/u...', Array)
#16 /home/demo2/vendor/craftcms/cms/src/web/Application.php(583): craft\web\Application->runAction('commerce/cart/u...', Array)
#17 /home/demo2/vendor/craftcms/cms/src/web/Application.php(259): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /home/demo2/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /home/demo2/public_html/index.php(22): yii\base\Application->run()
#20 {main}`

More information:
Craft CMS v3.5.9
Craft Commerce v2.2.9
PHP v7.0.33

**Comment by mofman** [comment]
@bhashkar007 you need to update craft commerce to 3.2

**Comment by bhashkar007** [comment]
@mofman 
Yes, I tried to update to Craft Commerce to 3.0.0+ but was getting migration error :(

**Comment by lukeholder** [comment]
@bhashkar007 can you make a new ticket with the migration error and/or error in the logs for that?

**Comment by lukeholder** [comment]
We are going to make a fix for this error on 2.2.x so upgrading to 3.x is not required to get this fixed.

**Comment by bhashkar007** [comment]
Thanks @lukeholder I did it here [#1726](https://github.com/craftcms/commerce/issues/1726)

**Comment by nfourtythree** [comment]
@bhashkar007 as @lukeholder mentioned we have just pushed an update for Commerce `2.2` that fixes this issue.

We have just released version `2.2.22` which has this fix in it.

Thanks!
