### ISSUE TITLE
Ability to export commerce settings as a file for import into another site

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#162]
> Created by: Pete Eveleigh ([pete@moresoda.co.uk](pete@moresoda.co.uk)) on 2017/10/09 11:40:21 +0000
Votes at time of UserVoice import: 1

------
Similar to Cartthrob, allow the export of the Commerce setup so it can easily be applied to a new site (for instance, go from local dev to staging).

**Comment by lukeholder** [comment]
We now support project config. Let us know if this doesn't meet your needs. Thanks.
