### ISSUE TITLE
Validation Error When Trying to Duplicate Products 

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce#1620]
**Description**
When trying to use the "Duplicate" action on any of our Products we get the error "Could not duplicate elements due to validation errors." Can confirm that these products do not have a validation error when saving them. Can also confirm that the validation errors are still working (at least for fields that are required). As in, if I remove the text from a field that is required the expected error is thrown.

**To Reproduce**
How, and what happened?
1. In the CP go to the products index /admin/commerce/products
2. Select the checkmark next to a single product
3. Click on the "duplicate" action
4. We get a "Could not duplicate elements due to validation errors."

**Expected behavior**
We expect the element to be duplicated.

**Additional info**
- Craft version: Craft Pro 3.4.29.1
- Commerce version: 3.1.12
- PHP version: 7.3
- Database driver & version: Mysql 5.7
- Other Plugins & versions:

```
Amazon S3	1.2.9
Cookies	1.1.12
Craft Commerce	3.1.12
Doxter	3.4.9
Instant Analytics	1.1.7
Linkit	1.1.11
oEmbed	1.3.4
Redactor	2.6.1
Retour	3.1.39
SEOmatic	3.3.8
Similar	1.0.6
Stripe for Craft Commerce	2.3.1.1
Twigpack	1.2.3
```

**Additional context**
We just recently updated to Craft 3.4 and Commerce 3.1 so possible something there broke it. I'm not confident it worked in Commerce 2.x though. I can't remember using it myself.

**Comment by nfourtythree** [comment]
Hi @dhahn 

I have just tried this and was able to duplicate a product as expected.

Could you please send your `composer.json`, `composer.lock` and a DB backup to support@craftcms.com so we can look into this further.

Thanks!

**Comment by dhahn** [comment]
Hey @nfourtythree, yes will do! I'll try to dig around a bit today and see if we have some custom code conflicting with it as well.

**Comment by nfourtythree** [comment]
Hi @dhahn 

I will close this issue now, as further to our conversation via support it looks like it might be something with your application code.

If you do find a bug please update this issue and I will re-open it.

Thanks!
