### ISSUE TITLE
Bug on sample template buy/index

### ISSUE THREAD

**Issue by bleepsandblops** [craftcms/commerce#1621]
https://github.com/craftcms/commerce/blob/6948f07f3068c883141552af0b36c27fa7cf88b3/example-templates/buy/index.html#L208
should probably be `getTotalShippingCostAsCurrency()` ?
And also:
https://github.com/craftcms/commerce/blob/6948f07f3068c883141552af0b36c27fa7cf88b3/example-templates/buy/index.html#L210
https://github.com/craftcms/commerce/blob/6948f07f3068c883141552af0b36c27fa7cf88b3/example-templates/buy/index.html#L213

**Comment by lukeholder** [comment]
Thanks, fixed for the next release out soon.
