### ISSUE TITLE
Edit order page: Product name/description are always in english even if the CP language is in french for the user

### ISSUE THREAD

**Issue by PopaWeb** [craftcms/commerce#1631]
**Description**
In the edit order page, when you add a product, the product name/description are always in english even if the CP language is in french for the user. The search field only find the product if you type the name in english.

**To Reproduce**
How, and what happened?
1. Edit the user Preferences -> Language to French (Canada)
2. In Commerce: add a new product with english and french name
3. Add a new order
4. Add a product.

**Expected behavior**
Display and search product with name and description in french

**Additional info**
- Craft version: Pro 3.5.1
- Commerce version: Pro 3.2.1
- PHP version: 7.3.17
- Database driver & version: MySQL 5.7.29
- Other Plugins & versions:

**Comment by nfourtythree** [comment]
Hi

This will be completed as part of #1719

Thanks!
