### ISSUE TITLE
Sales sortOrder

### ISSUE THREAD

**Issue by Bavixke** [craftcms/commerce#1633]
**Description**
`craft.commerce.sales.allSales` sortOrder shows null.

**To Reproduce**
How, and what happened?
1. In the CP reorder the sales
2. Dump `craft.commerce.sales.allSales` on the front

**Expected behavior**
Showing the correct order for sortOrder. (It's there in the DB)

**Additional info**
- Craft version: Craft Pro 3.3.20.1
- Commerce version: 2.2.21
- PHP version: 7.2.33
- Database driver & version: MySQL 5.7.29

**Additional context**
Tested it in Craft Commerce 3.2.1 and it also broken.

**Comment by brandonkelly** [comment]
Commerce 3.2.2 is out now with a fix for this.
