### ISSUE TITLE
In Dev Mode Cart's Keep Getting Recreated

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce#1634]
**Description**
When in local development I can add an item to the cart. It comes back as fine from the update-cart response. However, when I refresh it is gone. The active cart still shows in the admin panel but it appears it's creating a new empty cart. I'm not seeing this in the production environment. It also seems to have started after I setup a second site and setup Craft to share authentication tokens between them.

**To Reproduce**
How, and what happened?
1. Add an item to the cart through AJAX.
2. See it in the response.
3. Refresh and try to get the cart.
4. New cart id and no items in the cart.

**Expected behavior**
What did you expect to happen?
It should remain in the cart.

**Additional info**
- Craft version: 3.4.30 & 3.5.2
- Commerce version: 3.1.12 & 3.2.1
- PHP version: 7.4
- Database driver & version: 8.0
- Other Plugins & versions:

**Comment by lukeholder** [comment]
Sounds like there is an issue with your PHP session?

Can you log in and remain logged in on your site in development?

Are you doing anything headless?

**Comment by simeon-smith** [comment]
So I have more details on this. It appears to be an issues related to signing into the subdomain.

I have the default cookie domain set to "domain.com". I know your docs say to set it to ".domain.com" with the period in front. However, this doesn't work when you have a naked domain as the main domain.

If I follow these steps I end up with an issue:
1. Log into the subdomain.
2. Go to the main domain.
3. Add an item to the cart.
4. Refresh the page.
5. New cart is created. Old cart is still in the CMS.

I can make the main domain work if I clear the cookies and cache again. Signing out and back in doesn't fix it. But we will have users who are signing into the subdomain and getting redirected to the main domain after completing a form.

**Comment by simeon-smith** [comment]
BTW, I remain logged in on both domains regardless of which I sign in on.

I am using AJAX to work with the cart/checkout but the sign in process is all twig templating.

**Comment by simeon-smith** [comment]
Also, the carts are associated to the user that is logged in.

**Comment by simeon-smith** [comment]
Ok, I was able to get it working now after clearing all site data instead of just cookies, session and local storage.

Wondering if its related to the issues with changing the defaultCookieDomain like mentioned here:
https://github.com/craftcms/cms/issues/5799

**Comment by nfourtythree** [comment]
Hi @simeon-smith 

Thanks for the update. Will close this issue for the moment. If you have any further problems please let us know.

Thanks!

**Comment by simeon-smith** [comment]
@nfourtythree I think this may be an issue related to Nitro and session storage.

https://github.com/craftcms/nitro/issues/204
