### ISSUE TITLE
Add LineItem->setLineItemStatus

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1638]
Please add a function to set the lineItem status via PHP and remove the cached status

**What are you trying to do?**
I'm trying to create an endpoint to change the status for a LineItem and return the new Status

**What's your proposed solution?**
Set the new LineItem status via
```PHP
$lineItem->setLineItemStatus($lineItemStatus);


public function setLineItemStatus(LineItemStatus $status = null)
{
    if($status !== null){
        $this->_lineItemStatus = $status;
        $this->lineItemStatus = (int)$status->id;
    } else {
        $this->lineItemStatus = null;
        $this->_lineItemStatus = null;
    }
}
```

**Additional context**
When you currently just set the status via attribute, the value is still cached
```PHP
$status = $lineItem->getLineItemStatus();
if($status !== null && $status->handle === 'something'){
    // do something in this case....
}

$lineItem->lineItemStatusId = $newStatusId;
// ....
$order->setLineItems($lineItems);
// save the order and try to return the new status...
$lineItem->getLineItemStatus(); // <-- will return the old status, not the new one
```

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#de87ba92ee4620ded4c0b1a77f24d17d896681f3 as 3.2.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Commerce 3.2.2 is out now with a fix for this.
