### ISSUE TITLE
Changing Order Status sort order results in "Undefined index: name" error.

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce#1639]
**Description**
When I try to change the sort order of an Order Status I get "Undefined index: name" back from the server. Also, once this is tried I get the same error when trying to apply the project config.

It is creating a file that has the guid name like so:

`0a5158a3-519d-48c0-9792-a6dba06c9034.yaml`

With the content:

`sortOrder: 1`

It does not update the sortOrder in the order status yaml file.

If I remove the newly created guid only file and update the sort order manually then I can apply the changes from the project config.

**To Reproduce**
How, and what happened?
1. Change the sort order of the order status in the CMS.
2. Look in network to see the error coming back.
3. Try to run `./craft project-config/apply`.
4. It will error with "Undefined index: name".
5. Remove the newly created guid named file in the orderStatuses.
6. Update the sort order in the yaml file for the status you want to change.
7. Run `./craft project-config/apply` again. It works.

**Expected behavior**
What did you expect to happen?
It should work going through the CMS.

**Additional info**
- Craft version: 3.5.2
- Commerce version: 3.2.1
- PHP version: 7.4
- Database driver & version: 8.0 mysql
- Other Plugins & versions:

**Additional context**
A similar error has been reported in the Craft CMS repo. But this appears to be specific to how Commerce is creating their yaml files. https://github.com/craftcms/cms/issues/6464

**Comment by simeon-smith** [comment]
It appears that running `./craft project-config/apply` helps with this as a bunch of the project config files aren't getting created.

https://github.com/craftcms/cms/issues/6609

**Comment by pdaleramirez** [comment]
@simeon-smith Were you trying to upgrade your Craft version from 3.4 to 3.5 or is this a fresh install of Craft and Commerce plugin? If this is a fresh install of Craft version 3.5.2, are you still experiencing the same problem?

**Comment by ssmith-wombatweb** [comment]
@pdaleramirez it was an upgrade. I haven't needed to rebuild since then so I can't tell you if it was still the case after 3.5.2.

**Comment by lukeholder** [comment]
Closing this as a rebuild of the project config fixes the issue - we have not had other reports of the same issue. Putting it down to an old project config bug. 

Rebuilding from the primary environment the project config is the only solution if project config was in a bad state.

**Comment by pdaleramirez** [comment]
@ssmith-wombatweb There's a bug when when upgrading from 3.4 to 3.5.0. Upgrading to 3.5.x should resolve the issue.
