### ISSUE TITLE
When updating Craft to 3.5 and Commerce to 3.2.1 there are several project config files that are missing.

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce#1640]
See this issue in Craft.

https://github.com/craftcms/cms/issues/6609

**Comment by simeon-smith** [comment]
It appears that running `./craft project-config/apply` helps with this as a bunch of the project config files aren't getting created.

https://github.com/craftcms/cms/issues/6609

**Comment by simeon-smith** [comment]
These files are primarily orderStatus files. Without them I'm getting this issues: https://github.com/craftcms/commerce/issues/1639

**Comment by lukeholder** [comment]
Closed in favour of https://github.com/craftcms/commerce/issues/1639
