### ISSUE TITLE
Discounts matching a product variant/purchasable are not applied

### ISSUE THREAD

**Issue by sparkalow** [craftcms/commerce#1641]
**Description**
Adding a discount matching a purchasable/product variant, results in discount not being applied to the matching product when added to the cart. Seems to be related to strict data type comparison.

**To Reproduce**

1. In the CP create a discount matching a single specific Product Variant (Purchasable).
2. Add a matching product to the cart on frontend and notice discount is not applied.

**Expected behavior**

Discount to be applied to the matching product in the cart.

**Additional info**
- Craft version: 3.5.2
- Commerce version: 3.2.1
- PHP version: 7.2.19
- Database driver & version: Mysql  5.7
- Other Plugins & versions: AsyncQueue	2.1.1, Feed Me	4.2.3, PayPal for Craft Commerce	2.1.0.1, Redactor 2.7.0

**Additional context**

I believe the cause is related to the below code in  /src/services/Discount.php. The php `in_array` check is using strict comparison. The $purchasableId (needle) is an `int` and the array (haystack) is an array of `strings` resulting in a `false` return using strict comparison. The types are different between needle and haystack and will always return false.

```
if (!in_array($purchasableId, $discount->getPurchasableIds(), true)) {
    return false;
}
```

In my anecdotal testing, I remove the strict flag and the discount matching. I did not test thoroughly with other discounts or product variants however.

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#b949348535e44c4f818ec1d180565fbc24ac3f35 as 3.2.2.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Commerce 3.2.3 is out now with a fix for this.
