### ISSUE TITLE
Set the order of the lineItem before EVENT_AFTER_APPLY_REMOVE_LINE_ITEM

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1642]
**What are you trying to do?**
I need to store information when a LineItem is removed from an order and I would like to get the correct order via `$lineItem->getOrder()` but the LineItem does not contain the correct order but it will fetch it again from the DB without the current changes.
Do I need to listen to the "beforeSave" event of the order to remember the order and check the objects by myself to grab the current order?

**What's your proposed solution?**
Just set 
```PHP
$lineItem->setOrder($this);
// before you continue 

$previousLineItem->delete();

if ($this->hasEventHandlers(self::EVENT_AFTER_APPLY_REMOVE_LINE_ITEM)) {
    $this->trigger(self::EVENT_AFTER_APPLY_REMOVE_LINE_ITEM, new LineItemEvent([
        'lineItem' => $lineItem
    ]));
}
```

I'm not really sure why you even fetch it again and don't use the `$previousLineItem` . It would make so much more sense in my opinion. Element and Order events are not triggered with a fresh element as well

**Comment by lukeholder** [comment]
```
                $previousLineItem->delete();

                if ($this->hasEventHandlers(self::EVENT_AFTER_APPLY_REMOVE_LINE_ITEM)) {
                    $this->trigger(self::EVENT_AFTER_APPLY_REMOVE_LINE_ITEM, new LineItemEvent([
                        'lineItem' => $previousLineItem
                    ]));
                }
```
If you change the code in Commerce to the above, does that work for you?

**Comment by Anubarak** [comment]
Damn... totally forgot I can use `$event->sender` and loop all lineItems to compare the ID

**Comment by lukeholder** [comment]
We should still probably pass the right line item. Yes, sender is also possible.

**Comment by Anubarak** [comment]
> If you change the code in Commerce to the above, does that work for you?
Sorry, you are right, that's the Record... my bad. Please ignore this.
