### ISSUE TITLE
Default line item status is not applied on order complete

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#1643]
**Description**
If you have a default line item status setup it is not applied to the line items when an order completes

**To Reproduce**
1. Craft line item status in CP
2. Set it as default
3. Create an order and complete it

**Expected behavior**
The default line item status should be applied to all line items.

**Additional info**
- Commerce version: 3.2.1

**Comment by nfourtythree** [comment]
This has been fixed and will be included in the next release.

**Comment by brandonkelly** [comment]
Commerce 3.2.2 is out now with this fix.

**Comment by challahan** [comment]
I'm getting an error message when submitting payment on my local environment (using the default templates) after applying this update. May be related to this particular fix?  Not sure.

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`DATABASENAME`.`craft_commerce_lineitems`, CONSTRAINT `craft_commerce_lineitems_lineItemStatusId_fk` FOREIGN KEY (`lineItemStatusId`) REFERENCES `craft_commerce_lineitemstatuses` (`id`) ON DELETE) The SQL being executed was: UPDATE `craft_commerce_lineitems` SET `price`='12.18', `saleAmount`='0', `salePrice`='12.18', `weight`='0', `height`='0', `length`='0', `width`='0', `subtotal`='12.18', `total`='12.18', `lineItemStatusId`=0, `dateUpdated`='2020-08-14 00:59:32' WHERE `id`=175

**Comment by challahan** [comment]
Update - I did not have any line item statuses set in the CP. I added a random one for new orders and now I don't get the error.

**Comment by brandonkelly** [comment]
We just released 3.2.2.1 with a fix for that, @challahan.
