### ISSUE TITLE
Unknown property `priceAsCurrency` on Order edit for custom purchasables

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#1646]
**Description**
Custom purchasables are throwing an error on the order edit page when trying to add a new line item.

**Comment by nfourtythree** [comment]
This was highlighted by verbb/events#63

A fixed has been pushed which will be included in the next Commerce release.

**Comment by joshangell** [comment]
Eyyyy, thanks @nfourtythree 👍

**Comment by brandonkelly** [comment]
Commerce 3.2.2 is out now with this fix.
