### ISSUE TITLE
Cannot change relation field value in orders field layout when they are not empty

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1647]
**Description**
Currently you cannot change the value of relation fields, when they already contain a value in a orders field layout. However it works when they are inside a matrix field.

I don't see any JS errors in my console.
![order-error](https://user-images.githubusercontent.com/6122122/90111667-42bc1a00-dd4f-11ea-890a-e33fd5b0fb02.gif)

**Edit**:
I guess there is another issue that selects the wrong tab, when you save an order. You can see that after I saved it for a short moment, when all tabs are listed before they become invisible

**Additional info**
- Craft version: Craft Pro 3.5.3
- Commerce version: "dev-develop#de87ba92ee4620ded4c0b1a77f24d17d896681f3 as 3.2.1"

**Comment by brandonkelly** [comment]
Commerce 3.2.2 is out now with fixes for this.
