### ISSUE TITLE
Unable to switch or cancel a subscription on the front-end

### ISSUE THREAD

**Issue by jameslindeman** [craftcms/commerce#1650]
**Description**
Unable to switch a Stripe subscription plan or cancel a plan on the front-end. This could be a problem with https://github.com/craftcms/commerce-stripe but starting here as it seems to be a problem since the recent Commerce 3.2 update. 

**To Reproduce**
1. Setup at least two Stripe subscriptions in the CP and enable them for customers to select.
2. Using the example templates, subscribe to a plan on the front-end
3. Then go to /shop/plans and click ‘manage’
4. Try to switch the plan by clicking ‘Switch’ next to the alternative plan
    * I’m then seeing a flash error after this: `Unable to modify subscription at this time.`
5. Try to cancel the plan by clicking ‘Unsubscribe’
    * I’m then seeing a flash error after this: `Unable to cancel subscription at this time.`

I only get the flash errors on the front-end. I can switch and cancel a membership from the control panel.

**Additional info**
- Craft version: 3.5.4
- Commerce version: 3.2.2.1
- Commerce Stripe: 2.3.1.1
- PHP version: 7.2.24

**Comment by nfourtythree** [comment]
Hi @jameslindeman 

I have just tried to replicate this locally and I was able to unsubscribe as expected. 

The error you are seeing is triggered when trying to save the element. This could suggest there is an issue on saving the element. Is there any custom logic or fields in your project that could be causing an issue?

Thanks.

**Comment by jameslindeman** [comment]
Hi @nfourtythree, thanks for taking a look. Guess it must be my end but struggling to find it.

There was some custom logic to send a tax code to Stripe, and a couple of custom Subscription fields to save country and state, although I’ve disabled all plugins and removed those fields. Still not able to unsubscribe on front-end but control panel works.

**Comment by lukeholder** [comment]
@jameslindeman 

The error is triggered in here: https://github.com/craftcms/commerce/blob/ef859326ed7aefe5443b92dc4d82102dbb2b13be/src/controllers/SubscriptionsController.php#L332-L362

Since you mention it working on the backed, are you possibly trying to switch the subscription of the non-current user on the front end?  See lines: https://github.com/craftcms/commerce/blob/ef859326ed7aefe5443b92dc4d82102dbb2b13be/src/controllers/SubscriptionsController.php#L338

**Comment by jameslindeman** [comment]
Thanks @lukeholder 

I’m logged in as the user I’m trying to unsubscribe/switch. Doing a dump and die for the subscription I’m trying to manage looks right. I’m also testing with the example templates, and have disabled plugins. If I unsubscribe/switch in the CP, those changes are reflected in the front-end template I’m looking at.

**Comment by kevadamson** [comment]
![image](https://user-images.githubusercontent.com/1021744/91981522-e41c0780-ed20-11ea-8210-e6600e0c191e.png)

Had the same issue. Told it's because userId is string, but getId is integer. == would work but not ===?

**Comment by lukeholder** [comment]
Thanks, this is fixed in 3.2.6
