### ISSUE TITLE
Live Previews broken since 3.2 (fields and variants)

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1651]
**Description**

My Live previews - for products specifically (i.e. entry live previews appear to be fine) are borked since upgrading to Commerce 3.2 - the fields are all missing.

In addition, since ~ Commerce 3.0, live previews of variants have not been showing, but at least the rest of the live previews were intact.

With 3.2, live previews are now totally empty on the left (other than the title field) - and variants are missing on the actual preview (still).

![image](https://user-images.githubusercontent.com/731309/90347526-61365400-e074-11ea-8962-a0b9b76cea47.png)

**Additional info**
Everything up to date as of this morning to released versions

**Additional context**
? Might be plugin related - but I can't really tell - there's no errors in the console/network tab of devtools...also, given our complex entry previews are loading ok, this _seems_ less likely.

Let me know what I can do to help you debug....

**Comment by engram-design** [comment]
Just tested on a brand-new install with Craft CMS 3.5.4 and Commerce 3.2.2.1 and seeing the same.

![Screen Shot 2020-08-17 at 5 13 05 pm](https://user-images.githubusercontent.com/1221575/90368113-ef2e3100-e0ac-11ea-9180-221e8b516687.png)

![Screen Shot 2020-08-17 at 5 13 31 pm](https://user-images.githubusercontent.com/1221575/90368143-fead7a00-e0ac-11ea-8f66-b3b21b1105ee.png)

**Comment by brandonkelly** [comment]
Craft 3.2.3 is out now with a fix for this.

**Comment by bossanova808** [comment]
Just confirming this is indeed all fix - the fields in the live preview, plus the variants are back in the preview for the first time in a while.  Thanks so much!
