### ISSUE TITLE
Searching in orders is broken in the CP

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#1652]
**Description**
When searching for orders in the CP, I get an internal server error.

**To Reproduce**
How, and what happened?
1. Search for an order in the CP
2. Says internal server error

**Expected behavior**
No error

**Additional info**
- Craft version: 3.5.4
- Commerce version: 3.2.2.1
- PHP version: 7.4.9
- Database driver & version: PostgreSQL 11.8
- Other Plugins & versions: -

**Additional context**
Full stacktrace on Sentry: https://sentry.io/share/issue/92fb2f4e39a64d95acfb857def55e69e/

**Comment by nfourtythree** [comment]
Hi @boboldehampsink 

Thank you for bringing this to our attention.

We have pushed a fix for this which will be included in the next release.

Thanks!

**Comment by brandonkelly** [comment]
Commerce 3.2.3 is out now with a fix for this.
