### ISSUE TITLE
Entry queries returning zero results when generating pdf file

### ISSUE THREAD

**Issue by jlapan** [craftcms/commerce#1654]
**Description**
I have a setup an order pdf file that takes a line item's option and performs an entry query to get details about that entry to include in the pdf. However, the entry query returns zero results every time, no matter how simple I make the entry query.

**To Reproduce**
How, and what happened?
1. Add a new PDF at Commerce -> System Settings->PDFs
2. In pdf twig file include line `{% set entries = craft.entries().all() %}`
3. Next line, enter `{{ entries|length }}`
4. Pdf renders properly but outputs "0"

**Expected behavior**
This is working in Commerce 3.1.12, but is not in Commerce 3.2.1.

**Additional info**
- Craft version: Craft Pro 3.5.3
- Commerce version: Commerce 3.2.1
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.26

**Comment by lukeholder** [comment]
Hi @jlapan I can not reproduce this issue:

![image](https://user-images.githubusercontent.com/133571/90470849-21906a80-e14f-11ea-8e85-e9f7078d0f7e.png)

I am able to get the entries returned within a rendered PDF download.

Could you be editing the wrong template?

**Comment by jlapan** [comment]
Hey @lukeholder, thanks for your response. I am editing the correct template. I also just updated to the recent version of Craft and Craft Commerce, but the issue still persists.
![Screen Shot 2020-08-18 at 9 46 23 AM](https://user-images.githubusercontent.com/45296777/90521148-3e6d7380-e138-11ea-868f-d15069a02791.png)
![Screen Shot 2020-08-18 at 9 46 44 AM](https://user-images.githubusercontent.com/45296777/90521152-3f9ea080-e138-11ea-8b49-5237f70f00a5.png)

**Comment by lukeholder** [comment]
Can you send your DB backup, and full templates to support@craftcms.com and reference this ticket? Thanks.

**Comment by lukeholder** [comment]
Can you send your DB backup, and a single template file that reproduces this issue to support@craftcms.com and reference this ticket? Thanks. @jlapan

**Comment by jlapan** [comment]
Thanks Luke. I just emailed the requested files and my DB backup to the support email address.

**Comment by lukeholder** [comment]
@jlapan Looking at your DB and project, it looks like you are trying to query for entries where there is none in the current site: 

https://craftcms.com/docs/3.x/entries.html#querying-entries
> The current site will be used by default.

If you don't specify the `site` or `siteId` param in the in the entry query, the current (in your case the 'ecommerce' site) will be used, but in the `ecommerce` site, you have no entries.

**Comment by jlapan** [comment]
This makes perfect sense and I somehow missed this in the documentation. Thanks for your help.
