### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#1656]
**Description**
<img width="661" alt="Screen Shot 2020-08-18 at 08 53 21" src="https://user-images.githubusercontent.com/378974/90480339-622cbb80-e130-11ea-871c-71e04fddc062.png">

**Additional info**
- Craft version: 3.5.5
- Commerce version: 3.2.2.1
- PHP version: 7.4.9
- Database driver & version: PostgreSQL 11.8
- Other Plugins & versions: -

**Comment by nfourtythree** [comment]
Hi @boboldehampsink 

Thank you for bringing this to our attention.

We have pushed a fix that will be included in the next release. b5839f787bd54326e7ba87f217d67b7c6f1cc1e0

Thanks!

**Comment by brandonkelly** [comment]
Commerce 3.2.3 is out now with a fix for this.
