### ISSUE TITLE
Add the ability to include the Order object in `createLineItem` or an additional config array

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1657]
**What are you trying to do?**
I'm trying to change an Order, add a lineItem and populate the LineItem based on the orders data (it's for a booking system and the lineItem can have different **base** prices based on the order itself. I cannot do it via Adjuster for several reasons)
Unfortunately I need to store the currently saved order in a global variable to grab it in the `EVENT_CREATE_LINE_ITEM` event.

Currently the following code is not really convenient in my opinion...

```PHP
public function actionSomeControllerAction()
{
    $cart = Order::find()->one();

    // it was false before
    $cart->setFieldValue('someField', true);
    $lineItem = Plugin::getInstance()->getLineItems()->createLineItem(
        $cart->id,
        $variant->id
    );
}

// ....
Event::on(
    LineItems::class,
    LineItems::EVENT_POPULATE_LINE_ITEM,
    [$this, 'populateLineItem']
);
// .... 
public function populateLineItem(LineItemEvent $event)
{
    // will echo '0' instead of `1` because this will fetch the order from the DB again.
    echo (string)$event->lineItem->getOrder()->getFieldValue('someField');
}
```
My current work-around is to store the order in a global variable and do
```PHP
public function populateLineItem(LineItemEvent $event)
{
    $cart = Module::$instance->myVariable;
}
```

**What's your proposed solution?**
Either include an additional config array in the function (not really cool, since there are already many parameters in that function)
or split the function into different one, so people can call them one after another by themself
```PHP
$lineItem = Plugin::getInstance()->getLineItems()->getMeALineItem(...);
$lineItem->setOrder($cart);
Plugin::getInstance()->getLineItems()->someMethodToPopulateFromPurchasableAndTriggerEvents();
```

Of course we could just move these 
```PHP
$lineItem = new LineItem();
$lineItem->qty = $qty;
$lineItem->setOptions($options);
$lineItem->orderId = $orderId;
$lineItem->note = $note;
``` 
into a custom service, but if you change that one, we must change it accordingly.
I guess the easiest way would be to do
```PHP
public function createLineItem(int|Order $orderOrId, int $purchasableId, array $options, int $qty = 1, string $note = ''): LineItem
```
if it was PHP8... I guess you know what I mean.

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.

Added a new param to `LineItems::createLineItem()`:

`* @param Order|null $order Optional, lets the line item created have the right order object assigned to it in memory. You will still need to supply the $orderId param in the first param position.`

**Comment by Anubarak** [comment]
Thank you so much
