### ISSUE TITLE
Sales not applied based on customer in CP order edit page

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1662]
**Description**
When a sale has a user group defined as a condition and line items are added in the CP order edit page, sales are applied based on the current user editing the order in the CP rather than the customer defined for the order.

**To Reproduce**
How, and what happened?
1. Start with a sale that has a condition limiting to a particular user group, a customer account that belongs to that group, and an admin account which does not belong to that group.
2. Using the admin account, start a new order in the CP, assign the customer account, and start adding line items that should be eligible for the sale.
3. Sale is not applied since current user is technically the admin.

**Expected behavior**
Sales should be matched and applied based on the customer associated with the order rather than the user creating the order in the CP.

**Additional info**
- Craft version: Pro 3.5.5
- Commerce version: Pro 3.2.2.1
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for bringing this to our attention. We have pushed a fix for this that will be included in the next Commerce release.

Thanks!
