### ISSUE TITLE
Dashboard widgets errors

### ISSUE THREAD

**Issue by jlachancekffein** [craftcms/commerce#1664]
Error: Class 'craft\commerce\stats\Craft' not found
File: /src/craftCMS/vendor/craftcms/commerce/src/stats/TopProductTypes.php
Line: 55

The problem is the missing ```use Craft;``` at the beginning at the file.

That cause error when user is redirect to the dashboard after connexion.

Versions
-------------------------------------------
Craft 3.5.4
Craft Commerce 3.2.2.1

**Comment by nfourtythree** [comment]
Hi @jlachancekffein 

This has been fixed in 01865a692989965a0af700ef08c7b6506c0f5c74 and will be included in the next Commerce release.

Thanks.
