### ISSUE TITLE
Special characters being output as encoded in order addresses

### ISSUE THREAD

**Issue by Tam** [craftcms/commerce#1671]
**Description**
Special characters are being output as their encoded versions rather than as themselves in the Order addresses section.

<img width="668" alt="Screenshot 2020-08-26 at 13 42 45" src="https://user-images.githubusercontent.com/977594/91304941-3188f980-e7a2-11ea-9917-4355afb798aa.png">

The above should read `Friend's`.

**To Reproduce**
1. Use a special character (i.e. an apostrophe) in an address

**Expected behavior**
To render the character correctly.

**Additional info**
- Craft version: Craft Pro 3.5.6
- Commerce version: 3.2.3
- PHP version: 7.3.5
- Database driver & version: MySQL 5.5.5

**Comment by nfourtythree** [comment]
Hi @Tam 

Thank you for bringing this to our attention.

We have pushed a fix to solve this issue and it will be included in the next Commerce release.

Thanks!
