### ISSUE TITLE
How can I change the freeShipping field behaviour for commerce plugin

### ISSUE THREAD

**Issue by chandamotiyani** [craftcms/commerce#1672]
### Description
If I check the Free Shipping flag for the product for a particular product and if user adds other products in the cart which hasn't free shipping in it but I want the whole order to get free shipping even only one product has free shipping enabled, so how I achieve that?

Do I need to overwrite the actionPay function of PaymentController.php if Yes then what other things need to be taken care of?

**Comment by lukeholder** [comment]
Best to make a free shipping category and apply that to the products that will cause the free shipping for the whole order. Then in your shipping rule, make a rule that says that if it contains a product that has the free shipping category, match the order, and have the shipping be a zero price. Hope that make sense, let me know if you have any issues.

**Comment by chandamotiyani** [comment]
@lukeholder how to define in the rule that looks for the products come under that free shipping category?
Can you please elaborate precisely?

Thanks

**Comment by chandamotiyani** [comment]
@lukeholder I got to realize what you try to mean, I do have 5 different types of the products already, but I don't want to apply free shipping by the product types rather I want to check if the free shipping flag which is already there or I can create a new field for this, regardless of the product type I want the rule should check for that existing free shipping field or newly created one, if the products come under that then that rule should get applied to it!

Is it possible this way or in some way?
