### ISSUE TITLE
Can't preview email using postgres, no function Rand()

### ISSUE THREAD

**Issue by fireynis** [craftcms/commerce#1673]
**Description**
In the control panel, selecting preview for an email template for orders will result in an error as PostgresSql does not have a Rand() function.

**To Reproduce**
How, and what happened?
1. Go to emails
2. Attempt to preview one on a site using postgres

**Expected behavior**
The preview would open and the email would be displayed using an order

**Additional info**
- Craft version: Craft Pro 3.5.6
- Commerce version: 3.2.3
- PHP version: 7.3.17
- Database driver & version: PostgreSQL 12.2

**Additional context**
The issue is in the preview set up, specifically in `vendor/craftcms/commerce/src/controllers/EmailsController.php at line 49– craft\elements\db\ElementQuery::one()` at line 49 `$order = Order::find()->isCompleted(true)->orderBy('RAND()')->one();`

That RAND() call will not work with a Postgres database, it has the order by function of random() instead.

**Comment by lukeholder** [comment]
Thanks, this has been fixed for the next release.
