### ISSUE TITLE
saveShippingMethod does not call _memoizeShippingMethod

### ISSUE THREAD

**Issue by cgivord** [craftcms/commerce#1674]
When calling getAllShippingMethods(), then saveShippingMethod() and finally another getAllShippingMethods(), it does not show the saved one.

Two obvious choices here:
 - Maybe updating _fetchedAllShippingMethods to false,
 - Or probably better, just calling _memoizeShippingMethod() with the saved one.

**Comment by lukeholder** [comment]
Thanks for reporting. Marked as a bug, and will fix shortly.

**Comment by lukeholder** [comment]
Fixed in b07702ed88daadaa67716ef197e4af7c5e7f64ed

**Comment by lukeholder** [comment]
Thanks this has been fixed for the next release.
