### ISSUE TITLE
Please move the download PDF button to the other side of the element index dropdown

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1675]
Just a UI niggle that drives me bonkers.

I get unreasonably frustrated that the element index options dropwdown jumps right when I select an order...the number of times I end up clicking 'Download PDF' by accident is ridiculous... (which, incidentally, we _never_ actually want to us use as we don't use Commerce PDF - indeed, if there is no PDF template, perhaps this button could even be hidden completely...)

But, more generall, really, any extra buttons should come _after_ the main dropdown, surely? As that is in the same place, top left, in pretty much all the rest of the Craft CP, is it not?  It's just a muscle memory inconsistency thing...

![image](https://user-images.githubusercontent.com/731309/91369346-e842b380-e84e-11ea-9f90-a2f70c37c8c6.png)

Thanks for considering!

**Comment by nfourtythree** [comment]
Hi @bossanova808 

Currently, this is the same way things work for other elements e.g. entries:

![image](https://user-images.githubusercontent.com/266453/91857083-51676400-ec5f-11ea-954b-2a3f02acec48.png)

Also, if you disable all the PDFs within `Commerce > System Settings` the button won't show either.

Hope this helps, thanks.

**Comment by bossanova808** [comment]
Ok no worries - it's just the PDF thing is frustratingly slow when you click on it by accident.  But even with entries I feel it should add to the right, personally...the more things in a UI that stay where they are, the better...

(The reason I did not have it completely disabled was there was, a while back now, a breaking issue with Commerce if you had an empty value for your PDF template...but presume that is solved by now, so will get rid of that...)
