### ISSUE TITLE
Variant Title Format always required?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1678]
In product type settings the "Variant Title Format" looks to be always required, even when you select the "Show the Title field for variants" checkbox and it hides the field.

We would expect, if show title field is selected, that the Variant Title Format is ignored and the title field is required.

Currently if we submit an empty title field for a variant, the product still saves and uses Variant Title Format to generate the value. 

We would expect it to return a required validation error for the title field.

**Additional info**
- Craft version: 3.5.7
- Commerce version: 3.2.3
- PHP version: 7.3

**Comment by lukeholder** [comment]
Thanks for reporting. Can reproduce, will work on a fix now. Reproducing this doesn't cause #1679 for me.
