### ISSUE TITLE
Extra variant tabs created when saving product type

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1679]
No idea what has happened here, we were testing the "Variant Title Format" and "Show the Title field for variants" settings within the Product Type settings. We probably hit save 2-3 times, validation errors caused it to fail a few times. After that i noticed that extra tabs, all with the variants field, were added to our product field layout:

<img width="855" alt="Screenshot 2020-08-27 at 10 32 34" src="https://user-images.githubusercontent.com/1846063/91424007-26d96d80-e851-11ea-967d-fbb94197449b.png">

**Additional info**
- Craft version: 3.5.7
- Commerce version: 3.2.3
- PHP version: 7.3

**Additional context**
This issue is related to what we were doing when it happened: https://github.com/craftcms/commerce/issues/1678

**Comment by lukeholder** [comment]
Not able to reproduce this. Can you send your DB backup/dump, composer.json, composer.lock and `config/project` folder to support@craftcms.com - thanks!

**Comment by lukeholder** [comment]
Please send the above, and we can re-open this.

**Comment by samhibberd** [comment]
Will do, sorry @lukeholder
