### ISSUE TITLE
Card payments form showing twice?

### ISSUE THREAD

**Issue by kevadamson** [craftcms/commerce#1680]
**Description**
When I go to pay for a digital product, card details are shown, then when I click buy, card details form is shown again, but a different one (see screen shots attached).

![1](https://user-images.githubusercontent.com/1021744/91431291-12e53a00-e858-11ea-8b05-536db6501eb3.png)
![2](https://user-images.githubusercontent.com/1021744/91431294-137dd080-e858-11ea-9cb7-8b5314392529.png)

My code on page for displaying the form is:

`{{ cart.getGateway().getPaymentFormHtml({})|raw }}`

**Expected behavior**
I'd like just the second form to show, as this is the same layout as the payment form for subscriptions elsewhere on the site (which is working fine - just that one form shows).

**Additional info**
- Craft version: Craft Pro 3.5.7
- Commerce version: 3.2.3
- PHP version: 7.1.33
- Database driver & version: MySQL 5.6.47
- Other Plugins & versions:

Cloner 1.1.2
Conditional Fields 0.0.6
Control Panel Body Classes 2.2.1
Control Panel CSS 2.2.1
Craft Commerce 3.2.3
Dashboard Begone 1.0.1
Digital Products 2.4.1
Expanded Singles 1.1.3
Express Forms 1.0.6
Field Manager 2.1.8
Groupie 1.0.3
Internal Assets 2.3.1
Logs 3.0.3
Membership 1.0.0
Redactor 2.7.2
Redactor Anchors 1.1.0
Redactor Custom Styles 3.0.4
Redactor nofollow link plugin 1.0.1
Single Cat 1.2.1
Stripe for Craft Commerce 2.3.1.1
Super Table 2.6.2

**Comment by lukeholder** [comment]
Looks like the form/page thinks the gateway is the dummy gateway and you are in devMode. The dummy gateway populates a test credit card in devMode for you.

You need to make sure you are setting the gatewayId so order.getGateway() gets the right gateway. Are you submitting the gatewayId in the `commerce/payments/pay` request so it is set on the order? I am guessing your are getting some errors since you are being returned to the payment page again - what error flash messages are you getting?

**Comment by kevadamson** [comment]
What's interesting is that if I "add" a product (first click of the buy button) and the remove it, when I go to add it again or other products, it brings up the Stripe gateway form only, without the first form. But then I guess it now knows the ID as the form has been submitted?

**Comment by kevadamson** [comment]
Yep, adding the gateway ID to the add form rather than just the pay sorted the issue. Schoolboy error! Thanks for the quick response and chatting it through with me!
