### ISSUE TITLE
On every address update during checkout new address record being created instead of being edited.

### ISSUE THREAD

**Issue by abrunovski** [craftcms/commerce#1683]
**Description**
Please advice if this behaviour is intentional, on every address update during checkout new address record being created, instead of editing an existing one, as per [docs](https://craftcms.com/docs/commerce/3.x/update-cart-addresses.html#_4-updating-an-existing-address) `shippingAddress[id]` is present in the request. I'm using craft commerce in the web app and saving Shipping address a couple of times during checkout and sometimes user wants to update or correct address so on every interaction like this new address record being created.

**Expected behavior**
Address with specified id to be updated

**Additional info**
- Craft version: 3.5.5
- Commerce version: 3.2.3
- PHP version: 7.4.9
- Database driver & version: 8.0.19

**Related**
[1429](https://github.com/craftcms/commerce/issues/1429)
[1349](https://github.com/craftcms/commerce/issues/1349)

Request fields
<img width="637" alt="request_fields" src="https://user-images.githubusercontent.com/33316284/91503633-1394d380-e91f-11ea-8938-e5c54e652c4c.png">

Response address (has a new id)
<img width="499" alt="response_address" src="https://user-images.githubusercontent.com/33316284/91503652-23141c80-e91f-11ea-836d-d9dd59f5c424.png">

**Comment by nfourtythree** [comment]
Hi @abrunovski 

Thank you for bringing this to our attention.

We have pushed a fix that will be included in the next Commerce release.

Thanks!
