### ISSUE TITLE
lineItem.snapshot is a string, not a json object in ajax response from update-cart.

### ISSUE THREAD

**Issue by Mathias-Syversen** [craftcms/commerce#1684]
Craft CMS: 3.5.7
Commerce: 3.2.3

We have a vue js cart on our commerce site, and this cart is populated by the "/actions/commerce/cart/get-cart" endpoint.
When we update the cart (add a new line item, update qty on line item, or get an error on couponCode) we get the lineItem.snapshot back as a string (looks like a json string) and not an object.

![Screenshot 2020-08-27 at 17 01 59](https://user-images.githubusercontent.com/53942798/91547624-7fc60600-e924-11ea-988a-8ce20ce6deca.png)
This is how lineItem.snapshot looks when we get it from "/actions/commerce/cart/get-cart"

![Screenshot 2020-08-27 at 17 02 36](https://user-images.githubusercontent.com/53942798/91547677-8d7b8b80-e924-11ea-8101-1d1d2fbf387f.png)
And this is how lineItem.snapshot looks on the json response we get from "commerce/cart/update-cart"

**Comment by nfourtythree** [comment]
Hi @Mathias-Syversen 

I can't seem to replicate this locally:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/RBuOpmoR/Screenshot%202020-09-14%20at%2010.42.16.png?v=20ee4dfad79ebc2b9d29323db0cb6b8c)

Both `update-cart` and `get-cart` return the line item snapshot as an object for me. 

Are you up to date with the latest Commerce release?

Thanks

**Comment by nfourtythree** [comment]
Hi

I am going to close this issue for now. If you are still facing issues please update this with steps to reproduce and we will look into it further.

Thanks!

**Comment by freder** [comment]
I'm also experiencing this. `snapshot` is a json string (rather than an array)... _sometimes._ – haven't had the time yet to investigate further, but it's def. happening. for now I'm simply doing the conversion myself:

```php
function getSnapshot($lineItem) {
	$snapshot = $lineItem->snapshot;
	// TODO: why is this sometimes a string?
	if (is_string($snapshot)) {
		$snapshot = json_decode($snapshot, true);
	}
	return $snapshot;
}
```

- craft `4.4.8`
- craft commerce `4.2.1`

**Comment by jonleverrier** [comment]
I'm experiencing the same problem as @freder. I'm not using AJAX though as originally reported.

- craft `4.4.15`
- commerce `4.2.11`

Some observations FWIW:

- I'm using `Order::EVENT_BEFORE_SAVE` to populate some custom order fields from a line item snapshot before save
- I also have a bunch of custom order fields that are set to `required` 
- Whilst creating a manual order, If the required fields trigger form validation (they're left blank), but are then corrected, when I press "update order" in the CP, it triggers a problem in my event code
- My code is looking for an array not a json string. @freder fix worked for me, but this seams like odd behaviour
