### ISSUE TITLE
Order is not showing contact name or address

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/commerce#1685]
When we export our data from the orders we can find a billingAddressId and a shippingAddressId, but the data like firstName, lastName, address are not in the file. How can we export this?

Craft: 3.4.17.1
Commerce Lite: 3.1.3

**Comment by carolineboeykens** [comment]
Hi @lukeholder, do you have any news on this issue?

**Comment by nfourtythree** [comment]
Hi @carolineboeykens 

An update for this was pushed in a newer version of Commerce than you have installed.

Having said that, I have just also pushed a fix for Commerce exports that will be included in the next release.

So keep an eye out for that next release and then you should have all the things you need.

Thanks!
