### ISSUE TITLE
HTML Entities Shown "Raw" in CP

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#1688]
**Description**
In the CP, HTML entities are being shown encoded:

For example, the apostrophe in the edit address box shows up fine as usual:

![Screen Shot 2020-08-30 at 3 03 26 PM](https://user-images.githubusercontent.com/3707869/91668469-9c07a580-ead2-11ea-97c7-b1a3643e2bc9.png)

But rendered in the address screen:
![Screen Shot 2020-08-30 at 3 03 03 PM](https://user-images.githubusercontent.com/3707869/91668470-9ca03c00-ead2-11ea-8377-7ef2323c98a5.png)

Not sure if this is related to the new address format in 3.2? Wanted to test the new ``DefineAddressLinesEvent`` but it's also happening without modifying the data in the event as well.

**Additional info**
- Craft version: 3.5.7
- Commerce version: 3.2.3
- PHP version: 7.3
- Database driver & version: MySQL 5.7

**Comment by nfourtythree** [comment]
This is a duplicate for #1671

Thanks.
