### ISSUE TITLE
Print URL instead of PDF

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#169]
> Created by: Stefan Arnold ([outline4000@gmail.com](outline4000@gmail.com)) on 2017/06/11 16:25:44 +0000
Votes at time of UserVoice import: 3

------
Instead of the PDF option I would like to be able to have a print URL. 

e.g. https://myshop.com/print?id=x

I would just specify the url: https://myshop.com/print
I tried to work with the pdf, but the output was so deformed, that I made a print template. 
Now I show this link via a preparse field in the orders... but it's far from user friendly... 

I would like to have a "Show Order Reciept" button. 

Thanks

**Comment by andris-sevcenko** [comment]
> Created by: Luke Holder ([luke@pixelandtonic.com](luke@pixelandtonic.com)) on 2018/03/21 16:12:49 +0000


------
Can you please explain a little more, not sure exactly what you are trying to do. Thanks.

**Comment by andris-sevcenko** [comment]
> Created by: outline4 ([s.a@outline4.ch](s.a@outline4.ch)) on 2018/03/28 10:33:08 +0000


------
On top of an &quot;Order Pdf Path&quot;, I would like a &quot;Order Print Template Path&quot;. That will open a window with that URL and have the id of the order attached. 

If I have a special Template to print out orders like: 
https://myshop.com/printOrder?id=x 

Basically it&#39;s the same functionality as the PDF template, but without the pdf part. 
I just want customers to be able to print out a special page... that&#39;s all folks. 

At the moment I create this link via preparse: 
{{siteUrl }}printOrder?id={{craft.commerce.orders.id(craft.request.lastSegment)[0].number}}

and then in my template I have the following code: 

{% extends &quot;_layouts/_printOrder&quot; %}
{% block content %}
	{% set order = craft.commerce.orders.number(craft.request.param(&#39;id&#39;)).first() %}
	{% if order|length %}
		&lt;div id=&quot;print_container&quot;&gt;
			…Here&#39;s my Print Template…
		&lt;/div&gt;
	{% endif %}
{% endblock %}

**Comment by lukeholder** [comment]
A Print URL would easy to do per project, Commerce doesn't need to do anything here to help that.
