### ISSUE TITLE
Include the dateUpdated attribute for LineItems after save

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1691]
**What are you trying to do?**
I would like to save a LineItem and access the new `dateUpdated` attribute.

**What's your proposed solution?**
Set the correct `dateUpdated` attribute in the `saveLineItem` function.

https://github.com/craftcms/commerce/blob/develop/src/services/LineItems.php#L281

```PHP
if ($success) {
	$dateCreated = DateTimeHelper::toDateTime($lineItemRecord->dateCreated);
	$lineItem->dateCreated = $dateCreated;

        // add the dateUpdated as well... see above

	if ($isNewLineItem) {
		$lineItem->id = $lineItemRecord->id;
	}

	$transaction->commit();
}
```

**Comment by nfourtythree** [comment]
Hi @Anubarak 

Thank you for bringing this to our attention.

We have pushed a fix that will include this in the next Commerce release.

Thanks!
