### ISSUE TITLE
Better example needed for zipCode formula

### ISSUE THREAD

**Issue by fwof1976** [craftcms/commerce#1693]
We will be launching our site soon through a company building it through Craft SMS Pro. We are designating zip codes with locations. They asked us to put it in TWIG format, but under CMS the only example given is: zipCode [0:2] == 'NG'

This doesn't really explain what I need to substitute in or change in the array. It allows me to test it, but I am not sure what to change out in order to test it. I cannot find a similar setup online anywhere to move forward. Any help appreciated.

**Comment by fwof1976** [comment]
I found the answer: Zip code condition formula
A zip code condition formula is a short expression of logic that returns either true or false. The expression syntax is powered by Twig.

Below are some examples of a zip code condition formula:

zipCode[0:2] == '60' or zipCode[0:2] == '70'
The zip code condition will match if the zip code has 60 or 70 as it’s first 2 characters.

zipCode in ['NG102', 'NG103', 'NG102']
The zip code condition will match if the zip code is any of the above values.

**Comment by angrybrad** [comment]
Glad you're all sorted! Going to go ahead and close this issue.
