### ISSUE TITLE
Billing / Shipping Full Name Missing in Orders View

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#1694]
**Description**
Any reason Billing full name and shipping full name don't appear in the table?

I thought full name was just a concatenation of First + Last?

![Screen Shot 2020-09-01 at 3 03 24 PM](https://user-images.githubusercontent.com/3707869/91900424-4c58e380-ec64-11ea-9405-943a9383ea17.png)

**Additional info**
- Craft version: 3.5.7
- Commerce version: 3.2.3
- PHP version:7.3
- Database driver & version: MySQL 5.7

**Comment by nfourtythree** [comment]
Hi @RitterKnightCreative 

In 2.2 we added `fullName` as its own property for people to set and had the old concatenation method as a fallback. But in 3.0 we [removed the get method](https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#L723) and therefore the fallback.

The increases flexibility and is more suited for a worldwide audience. 

If you would like the concatenation to happen you could still do this using `Address::EVENT_BEFORE_SAVE` to update the `fullName` attribute with your desired content.

Hope this helps, thanks!
