### ISSUE TITLE
Allow Subtotal in Order View

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#1695]
**What are you trying to do?**
Had a client ask for the subtotal view on the orders page.

I thought for sure this was an option so was surprised when it wasn't, since it seems everything else is.

![Screen Shot 2020-09-01 at 2 55 33 PM](https://user-images.githubusercontent.com/3707869/91901039-3f88bf80-ec65-11ea-8c11-b9b96b28d77a.png)

**Comment by nfourtythree** [comment]
Hi @RitterKnightCreative 

Thanks for raising this.

We have just pushed an update that adds "Item Total" and "Item Subtotal" to the table attributes.

This will be available in the next release Commerce.

Thanks!
