### ISSUE TITLE
Allow Multiple Tax Zones to use the "Included in price"

### ISSUE THREAD

**Issue by jhealey5** [craftcms/commerce#1696]
We have a store that ships to multiple countries and we have multiple tax rates depending on where it's being sent to. We want to show that tax on checkout, whether it's included or not.

For e.g ; 
Shipping to ABC = 20% VAT (included in price)
Shipping to DEF = 10% VAT (included in price)
Shipping to XYZ = 50% VAT (not included)

I think this would be possible if we could allow included tax rates in other zones than default, but for some reason this seems to be limited to just the default category and I'm not sure why, is there something obvious preventing this being used on other zones? If I add multiple rates to the default zone it adds them all up.

![image](https://user-images.githubusercontent.com/1771431/91995626-f487ae80-ed2f-11ea-8852-799d75f88654.png)

**Comment by lukeholder** [comment]
@jhealey5 it's because the included tax is removed from the price of the item in the cart  if the order's tax addressis not sent to the non-default zone.

By saying that you have an included tax means you entered the price into the product page and included that tax amount into the price, and we can only assume you did that for a single zone/location (the default zone). You can only enter a single price - and this way you can do so, knowing exactly what taxes you are building into the price. 

If you have any more questions please let us know.

**Comment by jhealey5** [comment]
@lukeholder Thanks for that. Our client wants this to not only affect the default zone though, they have multiple zones setup (e.g; EUR, USA, UAE, etc) and each of those has a VAT rate set (e.g; 20% for EUR, 10% for USA, 50% for UAE) and the client wants the VAT included in the price (and displayed on the checkout) for each of those zones/rates. The only way I've been able to get it included in the price rather than on top is in the default zone with that tickbox. Is there another way to achieve this? 

I don't know exactly how VAT is supposed to work but this seems like a reasonable request from the client, the fact it's not achievable with the default commerce setup leads me to believe this is a more unique setup than most. Is there a glaring problem with the way the client is trying to set it up?

**Comment by lukeholder** [comment]
It sounds like they don't actually want to include a tax amount into the price, but just tell the customer that it is included the price - even though the price of the product will be the same for everyone?

**Comment by jhealey5** [comment]
@lukeholder Yeah that sounds about right.

**Comment by jhealey5** [comment]
@lukeholder The only way around this I can figure is to disable tax and not use it, then hardcode the various rates just for display on the checkout process. This would prevent any tax showing up on the orders though. Is there any alternative built into craft commerce that would do the who tax thing just not applying it to the price?

**Comment by mariovass** [comment]
@lukeholder do you have an update on this by any chance?

**Comment by JamesNuttall** [comment]
Would really like to see this issue re-opened or at the very least a bit of extra insight provided into why there has been no more discussion or workaround recommended. We have the same issue as @jhealey5 and really don't believe its so unorthodox.

We want to charge all users US$60 for our product with the tax being included within that. For example:
- A user purchasing from the UK should pay US$60 with US$10 (20%) being listed on the order and receipt as the included VAT
- A user purchasing from Switzerland should also pay US$60 but instead with US$4.62 (7.7%) being listed on the order and receipt as the included VAT

**Comment by lukeholder** [comment]
This should be solved once Commerce 3.4 is out today.
