### ISSUE TITLE
Unknown argument "hasProduct" on "variants"

### ISSUE THREAD

**Issue by Saboteur777** [craftcms/commerce#1697]
**Description**
According to the [documentation](https://craftcms.com/docs/commerce/3.x/dev/element-queries/variant-queries.html#parameters) there should be a hasProduct parameter, but it seems to be broken: 

```
{
 variants(
 status: "enabled"
 limit: null
 orderBy: "title ASC"
 trainingDays: 83221,
 hasProduct: {limit:null, status: "enabled", relatedTo: 109}
) {
 title
}
```

```
{
  "errors": [
    {
      "message": "Unknown argument \"hasProduct\" on field \"variants\" of type \"Query\". Did you mean \"hasStock\"?",
      "category": "graphql",
      "locations": [
        {
          "line": 7,
          "column": 5
        }
      ]
    }
  ]
}
```

The same seems to be working in PHP: 
```
$productQuery = Product::find()
 ->limit(null)
 ->status('enabled')
 ->relatedTo(109);

$variants = Variant::find()
 ->status('enabled')
 ->limit(null)
 ->orderBy('title ASC')
 ->trainingDays(83223)
 ->hasProduct($productQuery)
 ->all();
```

**Additional info**
- Craft version: 3.5.8
- Commerce version: 3.2.3
- PHP version: 7.4.2
- Database driver & version: MySQL 5.5.5

**Additional context**
See request n. 8822.

**Comment by nfourtythree** [comment]
Hi

We have just pushed an update that adds `hasProduct` parameter to variant GraphQL queries.

This will be included in the next release of Commerce.

Thanks!

**Comment by Saboteur777** [comment]
Thanks a lot!
