### ISSUE TITLE
Support partial shipping!

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#170]
> Created by: Stefan Arnold ([outline4000@gmail.com](outline4000@gmail.com)) on 2017/06/07 22:01:32 +0000
Votes at time of UserVoice import: 8

------
Partial shipping would be a bliss. 

A customer of mine has some products that are custom made. Sometimes these items take up to two month to make... 

So in the meantime it would be nice if a shop owner could send the rest of the ordered stuff directly and the custom stuff later. Of course shipping costs would have to be adapted. 

Maybe you'd have to split the orders and make two orders: One for the stuff in stock, one for the stuff out of stock.

Maybe it would be best to do it like amazon: give an option to choose to send all items at once or the fastest way. Shipping rates would reflect the choice. In the backend you'd have to have the ability to attach a special category if they have to be made or ordered from an other manufacturer and a timeframe when this will happen. 

It would be really really nice to have this! And of course it should be core :)

**Comment by julienmarie** [comment]
Would really need it too. I'd there any way to do it?

**Comment by lukeholder** [comment]
Commerce 3 alpha has a line item status that could be used. Moving this into the #43
