### ISSUE TITLE
Variant actions unresponsive after CMS 3.5/Commerce 3.2 update

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1701]
**Description**
Since upgrading to CMS 3.5/Commerce 3.2, variant actions are unresponsive on CP edit product pages. Default button and Reorder handle don't respond at all. Clicking on the Actions button displays the menu, but clicking on a menu option doesn't perform the action.

**To Reproduce**
1. In a CP edit product page with variants, go to the _Variants_ tab.
2. Try clicking a _Default_ button for a variant to to change.

**Expected behavior**
Expected buttons to perform actions. No actions performed.

**Additional info**
- Craft version: Pro 3.5.8
- Commerce version: Pro 3.2.3
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by lukeholder** [comment]
Hi @jmauzyk, sorry I can't reproduce this issue on those versions. Can you try clearing your caches/template caches in utilities?

**Comment by jmauzyk** [comment]
@lukeholder Ah, that did the trick. Thanks!

**Comment by lukeholder** [comment]
Good to hear!
