### ISSUE TITLE
Illegal offset type in isset or empty when use filter commerceCurrency with convert=true

### ISSUE THREAD

**Issue by nickwanhere** [craftcms/commerce#1702]
**Description**
Showing Illegal offset type in isset or empty when the template use commerceCurrency filter with currency string and convert=true. If take out convert=true, the template renders normally.

**To Reproduce**
How, and what happened?
1. Payment Currency setup two currencies, e.g. HKD as base, USD
2. In any template, put this {{1000|commerceCurrency('HKD',convert=true)}}

**Expected behavior**
The template should show HK$ 1000.00

**Additional info**
- Craft version: 3.4.30
- Commerce version: 3.1.12
- PHP version: 7.3.21
- Database driver & version: 5.7.27
- Other Plugins & versions: NA

**Additional context**
I try to debug on this and found src/helpers/Currency.php.
In the function of formatAsCurrency, if the convert is true, the $currency will be retrieved again via 
`Plugin::getInstance()->getPaymentCurrencies()->getPaymentCurrencyByIso($currency)` as object.
In the later statement, `Plugin::getInstance()->getCurrencies()->getCurrencyByIso` is called with the object, but the function definition saying the parameter is String instead of Object.

If I add `$currency = $currency->iso;` under line 78 to resume the object back to string, the the template works again.

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.

```

HKD string, converted: {{1000|commerceCurrency('HKD',convert=true)}}<br>

USD string, converted: {{1000|commerceCurrency('HKD',convert=true)}}<br>

USD paymentCurrency, converted: {{1000|commerceCurrency(craft.commerce.paymentCurrencies.primaryPaymentCurrency,convert=true)}}<br>

HKD paymentCurrency, converted: {{1000|commerceCurrency(craft.commerce.paymentCurrencies.getPaymentCurrencyByIso('HKD'),convert=true)}}<br>

USD paymentCurrency, not converted: {{1000|commerceCurrency(craft.commerce.paymentCurrencies.primaryPaymentCurrency)}}<br>

HKD paymentCurrency, not converted: {{1000|commerceCurrency(craft.commerce.paymentCurrencies.getPaymentCurrencyByIso('HKD'))}}<br>
```

results in:

```
HKD string, converted: $1,000.00
USD string, converted: $1,000.00
USD paymentCurrency, converted: $1,000.00
HKD paymentCurrency, converted: HK$2,000.00
USD paymentCurrency, not converted: $1,000.00
HKD paymentCurrency, not converted: HK$1,000.00
```
