### ISSUE TITLE
Reset order transaction cache after proceeding a payment

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1703]
**Description**
When you save an order and create a transaction afterwards (proceed the payment) you cannot grab the newly created transaction via 
```PHP
$order->getTransactions();
```
This is because you cache all transaction in `$order->getTransactions()` but don't invalidate the cache after creating a transaction.
Since Commerce 3.X you included the transactions as search keywords, thus `$order->getTransactions()` is called after saving the order -> the old transactions are cached.

**To Reproduce**
1. Save an order via PHP
2. Create a new transaction via `Commerce::getInstance()->getPayments()->processPayment()` in PHP
3. try to grab the transaction via `$order->getTransactions()` and see it does not contain the new transaction

**Expected behavior**
- getting all transactions with the newly created one

**Comment by lukeholder** [comment]
Thanks, this has been fixed for the next release.
