### ISSUE TITLE
"Delete Permanently" action in CP not working for soft-deleted Orders

### ISSUE THREAD

**Issue by yoannisj** [craftcms/commerce#1708]
**Description**

Permanently deleting soft-deleted orders via the CP's "Delete permanently" button introduced in Craft 3.5 is currently not possible.

After quick look at the [source code](https://github.com/craftcms/commerce/blob/develop/src/elements/actions/DeleteOrder.php#L33), it seems that the `hardDelete` argument is not passed to `\craft\services\Elements::deleteElement()` when the order is already trashed, which results in the order just being soft-deleted again.

**To Reproduce**

1. In the CP, navigate to /commerce/orders and enable the "Trashed" filter to list only trashed orders
2. Select one or more of the trashed orders in the list, and click on the "Delete permanently" action button at the top
3. The "Orders deleted" message is displayed, but the orders are still listed and still exist in the database.

**Expected behavior**

The trashed orders which were deleted permanently should be removed from the database completely, and not listed anymore in the CP.

**Additional info**
- Craft version: 3.5.7
- Commerce version: 3.2.3
- PHP version: 7.4
- Database driver & version: MariaDB 1:10.2.30

**Comment by lukeholder** [comment]
This also affects products. Will fix shortly.
