### ISSUE TITLE
Countries & States select all checkbox is not working

### ISSUE THREAD

**Issue by CMeldgaard** [craftcms/commerce#1712]
**Description**
Under Store Settings -> Countries & States, the select all checkbox is not working. When clicking it just gets a blue border around it (Chrome):

![Screenshot 2020-09-08 at 09 51 19](https://user-images.githubusercontent.com/14794642/92448509-f979b180-f1b8-11ea-9b34-d455a60695dc.png)

**To Reproduce**
How, and what happened?
1. Go to Countries & States in the CP
2. Click on the top checkbox, in header of the table, this should select all countries
3. Nothing happens

**Expected behavior**
I expected all countries to be selected, so that i can disable them all, and then only activate those few countries i need.

**Additional info**
- Craft version: 3.5.1
- Commerce version: 3.2.1
- PHP version: 7.3.17

**Comment by nfourtythree** [comment]
Hi @CMeldgaard 

This was an issue in Craft itself and was fixed in version `3.5.6`. You should find it works properly after updating Craft to the latest version.

Thanks!
