### ISSUE TITLE
Paid Status "Partial"

### ISSUE THREAD

**Issue by sarahschuetz** [craftcms/commerce#1714]
**Description**
After the checkout some of our orders get PAID STATUS 'Partial'. Furthermore they stay carts and are not maked as completed and converted to orders. This only happens to some of the orders and seems to be very random (so far I could not detect a pattern).

Out payment provider shows all the payment requests as "authorized" so there doesn't seem to be a problem with the payment itself and no reason for Craft to mark the payment as partial.

I also compared the Gateway Response of two orders (1 with PAID STATUS 'Paid' and marked as completely and 1 with PAID STATUS 'Partial' and still a cart instead of an order) and they were identical except for IDs, Amount etc.

**Additional info**
- Craft version: 3.4.30
- Commerce version: 3.1.12 (PRO)
- PHP version: 7.1.33

**Comment by lukeholder** [comment]
Hi, can you send a DB dump/backup to support@craftcms.com and reference this issue. Please also mention the order IDs affected.

Thanks.

**Comment by sarahschuetz** [comment]
@lukeholder I've sent you an email concerning this issue.

Additionally, I am trying to get a deeper understanding of what is happening myself but I am having a hard time understanding how Craft and the different Gateways play together and what is exactly happening behind the scenes. When are the Gateways called, what response is expected, when and on what grounds is an order completed etc. 

Do you have/know any resources besides the official docs which can help to get a bigger more detailed image of the whole checkout process?

**Comment by davidhellmann** [comment]
Hey @lukeholder any updates here?

**Comment by lukeholder** [comment]
@davidhellmann Replied on support just now.

**Comment by lukeholder** [comment]
Closing this issue, and tracking at: https://github.com/craftcms/commerce/issues/1383
