### ISSUE TITLE
Failing Order Condition Formula throws server error

### ISSUE THREAD

**Issue by yoannisj** [craftcms/commerce#1716]
**Description**

If there is a syntax or logical mistake in a discount's "Order Condition Formula" field, a server error gets thrown in the front-end when applying the discount coupon to the cart. This is not such a big deal when applying the coupon over ajax, but more problematic when using regular HTTP form submission.

**To Reproduce**

1. In the CP, create a discount coupon and include a syntax error in the "Order Condition Formula" field
2. In your front-end cart update form, apply the coupon code for discount created in step 1.
3. A server error is thrown and a 500 response code is returned

**Expected behavior**

Since the "Order condition formulae" field is often edited by non-dev staff members, it would be preferrable to handle errors raised when resolving them more gracefully. As an example, sending the error message to craft's logs and/or adding a "something went wrong" error to the cart model would avoid 500 responses being sent to end customers.

**Additional info**
- Craft version: 3.5.8
- Commerce version: 3.2.3
- PHP version: 7.4
- Database driver & version: Maria DB 1:10.2.30

**Comment by lukeholder** [comment]
Added the missing syntax validator to the order condition formula field on the discount edit page. This will stop invalid syntaxes from saving.

**Comment by lukeholder** [comment]
Will be in the next release, thanks!
