### ISSUE TITLE
Ability to add a manual S3 bucket name

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#172]
> Created by: Alex McFarlane ([alex@alexmcfarlane.com](alex@alexmcfarlane.com)) on 2017/05/10 12:07:38 +0000
Votes at time of UserVoice import: 1

------
If you don't have the S3:listBuckets() permission. It is impossible to add an S3 bucket in the admin site. Add the ability to enter a bucket name manually in the UX.

**Comment by lukeholder** [comment]
See https://github.com/craftcms/cms
