### ISSUE TITLE
TopProductTypes strip non-producttype purchasables

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1720]
**Description**
Our client created a TopProductType widget
![image](https://user-images.githubusercontent.com/6122122/92701786-b5b9b000-f350-11ea-9cbc-7e109a99b4de.png)
and is confused because of the empty line. This is because we have purchasables that are not variants. The query

> SELECT `pt`.`id` AS `id`, `pt`.`name`, SUM(`li`.`qty`) as qty, SUM(`li`.`total`) as revenue
FROM `commerce_orders` `orders`
INNER JOIN `elements` `elements` ON `elements`.`id` = `orders`.`id`
LEFT JOIN `commerce_lineitems` `li` ON `li`.`orderId` = `orders`.`id`
LEFT JOIN `commerce_purchasables` `p` ON `p`.`id` = `li`.`purchasableId`
LEFT JOIN `commerce_variants` `v` ON `v`.`id` = `p`.`id`
LEFT JOIN `commerce_products` `pr` ON `pr`.`id` = `v`.`productId`
LEFT JOIN `commerce_producttypes` `pt` ON `pt`.`id` = `pr`.`typeId`
LEFT JOIN `content` `content` ON (`content`.`elementId` = `v`.`productId`) AND (`content`.`siteId`=1)
WHERE (`dateOrdered` >= '2020-09-06 22:00:00') AND (`dateOrdered` <= '2020-09-13 21:59:59') AND (`isCompleted`=1) AND (`elements`.`dateDeleted` IS NULL)
GROUP BY `pt`.`id`
ORDER BY SUM(`li`.`qty`) DESC
LIMIT 5

currently has the following result
![image](https://user-images.githubusercontent.com/6122122/92701977-eac60280-f350-11ea-8d82-beca5b1eea1e.png)

Could you eventually strip those out or write at least something like "Not a product type" please?

**Comment by nfourtythree** [comment]
Hi @Anubarak 

Thank you for bringing this to our attention.

We have pushed a fix for this that will be included in the next Commerce release.

Thanks!
