### ISSUE TITLE
getAllShippingZones() does not return all shipping zones.

### ISSUE THREAD

**Issue by cgivord** [craftcms/commerce#1721]
**Description**

When calling getAllShippingZones(), then saveShippingZone() and finally another getAllShippingZones(), it does not show the saved one.

Maybe updating _fetchedAllShippingZones to false,
Or adding the saved one into the _allShippingZones array.

**Expected behavior**
The last getAllShippingZones() should return the shippingZone saved before.

**Additional info**
- Craft version: 3.5.9
- Commerce version: 3.2.4
- PHP version: 7.2
- Database driver & version: Mysql 5.6
- Other Plugins & versions: -

**Comment by nfourtythree** [comment]
Hi @cgivord 

Thank you for bringing this to our attention.

We have pushed up a fix for this which will be included in the next Commerce release.

Thanks!
