### ISSUE TITLE
PDF local image not loading with dompdf 0.8.6

### ISSUE THREAD

**Issue by martinleveille** [craftcms/commerce#1727]
**Description**
We have an order PDF template that use local image like this:

`<img src="{{ alias('@webroot/images/logo-invoice.png') }}" alt="Invoice">` 

After testing and according to the dompdf 0.8.6 changelog, there is a breaking change and a new `chroot` option need to be set when initializing dompdf.

https://github.com/dompdf/dompdf/releases/tag/v0.8.6

**Additional info**
- Craft version: 3.5.9 Pro
- Commerce version: 3.2.6 Lite
- PHP version: 7.4.8
- Database driver & version: MySQL 8.0.21

**Comment by brandonkelly** [comment]
As a quick fix to this, you can add this to your `composer.json` file:

```json
"require": {
  "...": "...",
  "dompdf/dompdf": "0.8.5"
}
```

Then run `composer update`.

Note that this may put your Composer requirements in conflict with future Commerce releases, if we end up bumping the Dompdf requirement down the road. If a future update fails due to a Composer conflict involving Dompdf you will just need to remove that line and re-run `composer update`.

**Comment by lukeholder** [comment]
@martinleveille out of interest, have you got `pdfAllowRemoteImages` config setting set to true?

**Comment by martinleveille** [comment]
@brandonkelly Thanks, this is what I did when I discovering the issue. But after thinking about it, I decided to add a new Twig function to get the base64 encoded image string in my PDF template. With this new function, I can run dompdf 0.8.6.

@lukeholder I tested this config setting, but it only work on my staging and production env. I am not able to make this work in my local Valet env. 

I would also like to add that with dompdf 0.8.6, it is now necessary to enable the `pdfAllowRemoteImages` config setting if you have external stylesheets like a Google Fonts.

**Comment by pdaleramirez** [comment]
@martinleveille Were you able to enable `pdfAllowRemoteImages` setting on your local environment? and test the pdf file again if it loads the image?

**Comment by pdaleramirez** [comment]
The solution on this issue for now is to downgrade to 0.8.5 https://github.com/craftcms/commerce/issues/1727#issuecomment-692753376. When Craft 4 gets released we'll add the enhancement for dompdf v0.8.6 and up in Commerce.

**Comment by martinleveille** [comment]
> @martinleveille Were you able to enable `pdfAllowRemoteImages` setting on your local environment? and test the pdf file again if it loads the image?

I already have this setting turned on to get external Google Fonts stylesheets in the PDF.

I've try many things like `{{ alias('@webroot/images/logo-invoice.png') }}` or `{{ url('images/logo-invoice.png') }}` or directly `https://example.test/images/logo-invoice.png` as the src, but for a reason that I don't know, my local PHP is not able to resolve local hosted sites with Laravel Valet and my Mac is set with 127.0.0.1 as the primary DNS server.

Anyways, I'm ok with my `image64()` Twig function for now. Thanks :)

**Comment by pdaleramirez** [comment]
@martinleveille You can use an event to modify the pdf render options. Usage is in the comment. https://github.com/craftcms/commerce/blob/d866afbabd25977e326a7643713239bb33cf82ec/src/services/Pdfs.php#L171
