### ISSUE TITLE
Calling commerce APIs using postman

### ISSUE THREAD

**Issue by chandamotiyani** [craftcms/commerce#1731]
I need to run commerce APIs through postman so that I can write tests for them
before writing unit tests I need to make sure that I'm able to call APIs and get the response, currently, we do use JS to point endpoints but I believe there must be API set up so that we can use these for iOS and Android applications

What I'm doing in the postman I have attached in the files

Do let me know what am I missing!
Also please suggest
<img width="967" alt="Screen Shot 2020-09-16 at 2 29 02 pm" src="https://user-images.githubusercontent.com/16190427/93301805-23c21380-f838-11ea-9424-47718590218d.png">
<img width="958" alt="Screen Shot 2020-09-16 at 2 30 10 pm" src="https://user-images.githubusercontent.com/16190427/93301851-2f153f00-f838-11ea-9cd8-1f2bd54d520a.png">

 if there is any other way of writing tests for commerce plugin such as to test add to cart, update cart, checkout functionality, etc.

**Comment by lukeholder** [comment]
@chandamotiyani is there anything in the logs explaining the 400 bad request? Maybe a CSRF token? try turning CSRF off temporarily in your general settings.

The request should work if it is a valid request.

**Comment by chandamotiyani** [comment]
Yea I already had disabled CSRF token temporarily but didn't work, so as per the images can you suggest what can be the issue?

**Comment by nfourtythree** [comment]
Hi @chandamotiyani 

Here are some screenshots of how I have things set-up in Postman.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/xQuLXOwW/Screenshot%202020-09-16%20at%2010.35.15.png?v=b4abff983b15954a573dbab9db596e24)

![](https://p191.p3.n0.cdn.getcloudapp.com/items/P8ub4NQq/Screenshot%202020-09-16%20at%2010.35.33.png?v=f55280974a14549ec7187dca50cb6c01)

![](https://p191.p3.n0.cdn.getcloudapp.com/items/wbu7lvQk/Screenshot%202020-09-16%20at%2010.35.50.png?v=3f4d8432e02cc0462fa3871b487c455c)

These settings along with `'enableCsrfProtection' => false` in the `general.php` config file should get you what you need.

Thanks!

**Comment by chandamotiyani** [comment]
@nfourtythree Thank you very much for the screenshots 👍
