### ISSUE TITLE
Example "shop" templates - product list does not have links to single product

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1732]
We can add product to cart from homepage of "shop" template, but we cannot visit single product page.

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Thank you for the suggestion. The example product list now contains links to example product pages (9ab3658b7ea4df29a8010830dcae8351f662d247).

These updated templates will be included in the next Commerce release.

Thanks!

**Comment by piotrpog** [comment]
@nfourtythree FYI, i also found out that products in shopping carts also dont have links. Both cart page and cart popup that shows up in right top corner.
