### ISSUE TITLE
Orders index/export is very slow, resulting in timeouts

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#1744]
**Description**
The orders index (at admin/commerce/orders) and the orders export are very slow. Loading 100 orders already takes almost 6 seconds on a very decent server. Exporting orders even results in timeout errors. I have a total of about 1500 orders.

**To Reproduce**
How, and what happened?
1. Seed about 1500 orders
2. Open orders index or try to export

**Expected behavior**
It could be fast, but it is not

**Additional info**
- Craft version:  3.5.10.1
- Commerce version: 3.2.6
- PHP version: 7.4.10
- Database driver & version: PostgreSQL 11.9
- Other Plugins & versions: -

**Comment by lukeholder** [comment]
Could you send a db dump to support@craftcms.com so we can look to reproduce? Thanks. @boboldehampsink

**Comment by boboldehampsink** [comment]
Done

**Comment by bossanova808** [comment]
Just for comparison info - we have about 18000 orders, and loading 100 of them on the orders index page takes 1.01 seconds in full, on our $20 Vultr VPS ....performance has massively improved with this with recent Commerce updates for us.

**Comment by boboldehampsink** [comment]
Thanks luke

**Comment by lukeholder** [comment]
That fix commit wasn't exactly it. Additional commits since then have improved things. You need to clear your template caches after making the update, after the release comes out. @boboldehampsink
