### ISSUE TITLE
Craft Commerce 3.2.6 order PDF download problem with permission

### ISSUE THREAD

**Issue by williamgomes** [craftcms/commerce#1745]
**Description**
Hello guys, i am currently using CraftCMS 3.4.27 and CraftCommerce 3.1.10 for my production. I really liked new features from CraftCMS 3.5 so i decided to give it a try and deployed CraftCMS 3.5.10 together with CraftCommerce 3.2.6 into my staging server. After deployment i found out that i can not download CommercePDF from CP. Whenever i try to download an order PDF, i got permission error:

```
[yii\base\ErrorException:2] yii\base\ErrorException: touch(): Unable to create file /var/www/20200917191813/storage/runtime/temp/commerce_dompdf/DejaVuSans.ttf.tmp.5f6494addbe0b because No such file or directory in /var/www/20200917191813/vendor/dompdf/dompdf/lib/Cpdf.php:1176
```

If i create this `commerce_dompdf` directory manually inside `storage/runtime/temp`, then everything works fine on my staging server. For my production server, i never had to create any directory manually and everything is running smoothly. Am i doing something wrong?

**To Reproduce**
How, and what happened?
1. Used latest CraftCMS (3.5.10) & CraftCommerce (3.2.6).
2. Login to CP
3. Try to download any order PDF.

**Expected behavior**
The order PDF should download properly without creating `commerce_dompdf` directory manually every time i deploy.

**Additional info**
- Craft version: 3.5.10
- Commerce version: 3.2.6
- PHP version: PHP 7.3.19

**Comment by william-mymy** [comment]
Hello, so after doing some debugging and research, i found 2 bugs in `craft\commerce\services\Pdfs`.

First bug inside `renderPdfForOrder()`:

     $dompdf = new Dompdf();
     // Set the config options
     $pathService = Craft::$app->getPath();
     $dompdfTempDir = $pathService->getTempPath() . DIRECTORY_SEPARATOR . 'commerce_dompdf';
     $dompdfFontCache = $pathService->getCachePath() . DIRECTORY_SEPARATOR . 'commerce_dompdf';
     $dompdfLogFile = $pathService->getLogPath() . DIRECTORY_SEPARATOR . 'commerce_dompdf.htm';

so all three `commerce_dompdf` folders in the above code are not getting created during the process of PDF generation. But in actual scenarios, these folders should be created if they are not. So my suggestion would be to use the `FileHelper` class to create each folder individually, something like below:

        $dompdf = new Dompdf();
        // Set the config options
        $pathService = Craft::$app->getPath();
        $dompdfTempDir = $pathService->getTempPath() . DIRECTORY_SEPARATOR . 'commerce_dompdf';
        FileHelper::createDirectory($dompdfTempDir);
        $dompdfFontCache = $pathService->getCachePath() . DIRECTORY_SEPARATOR . 'commerce_dompdf';
        FileHelper::createDirectory($dompdfFontCache);
        $dompdfLogFile = $pathService->getLogPath() . DIRECTORY_SEPARATOR . 'commerce_dompdf.htm';
        FileHelper::createDirectory($dompdfLogFile);

I tested the code with the above fixes and it solves my problem completely.


Second bug also inside `renderPdfForOrder()`:

        // Should throw an error if not writable
        FileHelper::isWritable($dompdfTempDir);
        FileHelper::isWritable($dompdfLogFile);

The above two lines should throw an error because these two directories should not be `writable` as the `commerce_dompdf` folder is not there.

Please let me know if I should create a pull request for the first bug. Thanks a lot. 😃

**Comment by williamgomes** [comment]
Hello, so after doing some debugging and research, i found 2 bugs in `craft\commerce\services\Pdfs`.

First bug inside `renderPdfForOrder()`:

     $dompdf = new Dompdf();
     // Set the config options
     $pathService = Craft::$app->getPath();
     $dompdfTempDir = $pathService->getTempPath() . DIRECTORY_SEPARATOR . 'commerce_dompdf';
     $dompdfFontCache = $pathService->getCachePath() . DIRECTORY_SEPARATOR . 'commerce_dompdf';
     $dompdfLogFile = $pathService->getLogPath() . DIRECTORY_SEPARATOR . 'commerce_dompdf.htm';

so all three `commerce_dompdf` folders in the above code are not getting created during the process of PDF generation. But in actual scenarios, these folders should be created if they are not. So my suggestion would be to use the `FileHelper` class to create each folder individually, something like below:

    $dompdf = new Dompdf();
    // Set the config options
    $pathService = Craft::$app->getPath();
    $dompdfTempDir = $pathService->getTempPath() . DIRECTORY_SEPARATOR . 'commerce_dompdf';
    FileHelper::createDirectory($dompdfTempDir);
    $dompdfFontCache = $pathService->getCachePath() . DIRECTORY_SEPARATOR . 'commerce_dompdf';
    FileHelper::createDirectory($dompdfFontCache);
    $dompdfLogFile = $pathService->getLogPath() . DIRECTORY_SEPARATOR . 'commerce_dompdf.htm';
    FileHelper::createDirectory($dompdfLogFile);

I tested the code with the above fixes and it solves my problem.


Second bug also inside `renderPdfForOrder()`:

    // Should throw an error if not writable
    FileHelper::isWritable($dompdfTempDir);
    FileHelper::isWritable($dompdfLogFile);

The above two lines should throw an error because these two directories should not be `writable` as the `commerce_dompdf` folder is not there.

Please let me know if I should create a pull request for the first bug. Thanks a lot. 😃

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
