### ISSUE TITLE
Expiry Date - Translation Error

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1746]
Should this not be:

`'Expiry Date' => 'Expiry Date',`

https://github.com/craftcms/commerce/blob/38a3d88e01089e414dd41fe1a0dcc55bd047bbc5/src/translations/en-GB/commerce.php#L120

**Comment by angrybrad** [comment]
Resolved https://github.com/craftcms/commerce/pull/1811

**Comment by angrybrad** [comment]
Oops... misread the issue. Really resolved in https://github.com/craftcms/commerce/pull/1812
