### ISSUE TITLE
HTML entities appearing in product names

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1747]
**Description**

![image](https://user-images.githubusercontent.com/731309/93659085-ff0eab80-fa84-11ea-8804-1d8d1371b6d7.png)

**To Reproduce**

Have a product with, e.g. `"` in the name

**Expected behavior**

I'd prefer to see the quotes than the HTML entities

**Additional info**

All up to date versions...

**Comment by nfourtythree** [comment]
Hi @bossanova808 

This sounds like a duplication of #1592 and I was unable to replicate the issue.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/E0unx1Nx/Screenshot%202020-09-21%20at%2009.27.40.png?v=086ecb35d9128a385deb27d5ec51d573)

![](https://p191.p3.n0.cdn.getcloudapp.com/items/5zuGQ6kO/Screenshot%202020-09-21%20at%2009.28.16.png?v=12f63280b398c3d70d3e85e66df4cb4e)

You mentioned you are up to date, have you tried resaving the product? Does the issue persist?

Thanks.

**Comment by bossanova808** [comment]
Well, I have re-saved my products several times recently follow various upgrade related issues (seems to be the current fix for everything!).  Will do so again and let you know if I see weirdness again....thanks
