### ISSUE TITLE
Remove line item doesn't work on a custom controller

### ISSUE THREAD

**Issue by mostafasoufi** [craftcms/commerce#1749]
Hi,

I created a new controller which is deleted the cart item by ID, here is the method that I using:

```
public function actionDelete(int $id)
{
    $cart = Plugin::getInstance()->getCarts()->getCart();

    foreach ($cart->getLineItems() as $key => $lineItem) {
        if ($lineItem->id == $id) {
            $cart->removeLineItem($lineItem);
        }
    }

    Craft::$app->getSession()->setNotice(Craft::t('site', 'Item Removed.'));
    Craft::$app->getResponse()->redirect(Craft::$app->getRequest()->getReferrer())->send();
}
```

But after redirecting, the item could still exist! I printed out the line items after deleting the foreach, It was not exist and OK but I don't know why the line item gets the value again after redirecting.

**Comment by lukeholder** [comment]
@mostafasoufi you are removing it from the order in memory, but you need to save the order for it to persist.

`if(Craft::$app->getElements()->saveElement($cart)){ ...`
