### ISSUE TITLE
Lock an entry while editing

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#175]
> Created by: Anna Myous ([sanbo@wtnet.de](sanbo@wtnet.de)) on 2017/04/05 09:48:20 +0000
Votes at time of UserVoice import: 5

------
Some cients have several editors/publishers, therefor it must be possible to lock an entry while editing. It is a must have!

**Comment by lukeholder** [comment]
See https://github.com/craftcms/cms/issues/824
