### ISSUE TITLE
Chrome Autocomplete prevents seeing customers dropdown

### ISSUE THREAD

**Issue by CMeldgaard** [craftcms/commerce#1752]
**Description**
When trying to create a order via the CP, Chrome Autocomplete dropdown prevents seeing the customers that match the search.

**To Reproduce**
How, and what happened?
1. In the CP go to Orders
2. Click "+ New Order"
3. Search for customer, here chrome will show the autocomplete dropdown
![Group 39](https://user-images.githubusercontent.com/14794642/93975274-7f7c2780-fd77-11ea-93e9-3a24e7400990.png)

**Expected behavior**
I expect to be able to see the dropdownlist generated by Craft Commerce, and not Chrome Autocomplete

**Additional info**
- Craft version: 3.5.10.1
- Commerce version: 3.2.6
- PHP version: 7.3

**Additional context**
The problem arrise because Chrome ignores autocomplete="off" - changing it to autocomplete="no" ought to fix it.

**Comment by nfourtythree** [comment]
Hi @CMeldgaard 

A fix for this was pushed in yesterday's Commerce release. 

Thanks!

**Comment by CMeldgaard** [comment]
@nfourtythree doesn't seem to fix the issue - i can see that the updated code has changed to name of the input, as per the new code, but it still triggers Chromes autofill.

Setting the autocomplete attribute to the same value as the name will fix the problem - as far as i can see it's a general problem with chrome not working with autocomplet="off"

**Comment by nfourtythree** [comment]
Thank you for the update @CMeldgaard 

We have pushed another update as per your suggestion. This will be included in the next release.

Thanks!
