### ISSUE TITLE
Chart taking a long time to load

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#1755]
The chart on the orders index page is taking longer to load than it used it. Seems to take an extra 7 seconds for our site.

We've narrowed it down to when it seems to have happened and it looks like Craft v3.4.6 introduced it.

**Comment by nfourtythree** [comment]
Hi @samuelbirch 

What version of Commerce are you running?

Thanks

**Comment by samuelbirch** [comment]
@nfourtythree we're currently running Commerce 2.2.21. We're going to try testing with the latest version of Commerce 3 as well.

**Comment by samuelbirch** [comment]
@nfourtythree Commerce 3 works fine but that is probably because the chart has been removed from the orders element index page.

**Comment by lukeholder** [comment]
Orders index page in Commerce 3 was substantially optimised with eager loading in recent releases. We currently are not going to add eager loading and optimisations to the Commerce 2 orders (order index).

**Comment by samuelbirch** [comment]
thanks @lukeholder, thats not a problem. We've reverted Craft back to the version where it wasn't an issue for now. 

The speed issue is being caused by the volume of orders that we have.

Is there a way of simply turning off the chart? - a user permission would be great or via the config file would work?
