### ISSUE TITLE
Store salePrice so its easier to do sort or filter of price.

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#1756]
**What are you trying to do?**
Sort product based on price but but default variant price on product is before any sales so sorting is always correct. Same goes with filtering of products.

See here https://themes.woocommerce.com/storefront/shop/ for an example of filtering (right hand side range slider) and sorting in the bottom left.

These 2 features are difficult when default variant salePrice is not stored.

**Comment by nfourtythree** [comment]
Hi @philipboomy 

Due to the way sales work this will be part of the catalog pricing tables feature we have on the roadmap #1041

Please follow along with that issue with any information or feedback you might have. 

Thanks!
