### ISSUE TITLE
404: Invalid route on email preview

### ISSUE THREAD

**Issue by billmn** [craftcms/commerce#1757]
After the **update to 3.2.7**, the email preview returns an invalid route (404).

![Schermata 2020-09-25 alle 09 17 46](https://user-images.githubusercontent.com/779534/94238199-45925900-ff10-11ea-86f4-1aff9ad8a7de.png)

**To Reproduce**
- In the CP, create a new email in Commerce > System Settings > Emails
- Set an empty template
- In Email list, click on preview button

**Additional info**
- Craft version: 3.5.11.1
- Commerce version: 3.2.7
- PHP version: 7.4

**Comment by nfourtythree** [comment]
Hi @billmn 

I have just tried this with the steps you mentioned and I get a blank preview (as expected when using a blank template).

What is the URL that is trying to be accessed?

Could you please send the full stack trace for the error?

Thanks!

**Comment by nfourtythree** [comment]
I just noticed in your screenshot that the word `render` is missing from the action request.

When you hover over the preview button, what is the URL you see?

**Comment by billmn** [comment]
Hi @nfourtythree,
this is the url of the button https://domain.test/index.php?p=cp/actions/commerce/emails/preview-email&emailId=1


And this is the Stack Trace:
```
yii\base\InvalidRouteException: Unable to resolve the request: commerce/emails/preview-email in /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/yiisoft/yii2/base/Controller.php:151
Stack trace:
#0 /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('preview-email', Array)
#1 /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('preview-email', Array)
#2 /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/craftcms/cms/src/web/Application.php(285): yii\base\Module->runAction('commerce/emails...', Array)
#3 /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/craftcms/cms/src/web/Application.php(588): craft\web\Application->runAction('commerce/emails...', Array)
#4 /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/craftcms/cms/src/web/Application.php(264): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#5 /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#6 /Users/dbellini/Code/git/mbemantova/pentoleretro/web/index.php(22): yii\base\Application->run()
#7 /Users/dbellini/.composer/vendor/laravel/valet/server.php(191): require('/Users/dbellini...')
#8 {main}

Next yii\web\NotFoundHttpException: Page not found. in /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/craftcms/cms/src/web/Application.php:592
Stack trace:
#0 /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/craftcms/cms/src/web/Application.php(264): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#1 /Users/dbellini/Code/git/mbemantova/pentoleretro/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#2 /Users/dbellini/Code/git/mbemantova/pentoleretro/web/index.php(22): yii\base\Application->run()
#3 /Users/dbellini/.composer/vendor/laravel/valet/server.php(191): require('/Users/dbellini...')
#4 {main}
```

**Comment by nfourtythree** [comment]
Hi @billmn 

I think this might be a template cache issue. Could you try clearing your template caches and see if it solves the issue?

Thanks.

**Comment by billmn** [comment]
I have executed `craft clear-caches/all` but doesn't solve.

I realized I didn't give you all the information about Craft installation. I don't know if it will help but these are the installed plugins:

- Contact Form
- Contact Form Honeypot
- Craft Commerce
- Mix
- Super Table

**Comment by nfourtythree** [comment]
Hi @billmn 

Could you try deleting the `storage > runtime` folder and see if that makes a difference.

If not could you send your `composer.json`, `composer.lock` and a backup of your DB to support@craftcms.com please.

Thanks.

**Comment by billmn** [comment]
It works!

I realized that I cleared the cache but didn't click the "Preview" button again (after a refresh) ... but I have refreshed the page with the error 🤦‍♂️

Sorry about that

**Comment by nfourtythree** [comment]
No problem. Glad it is all working!
