### ISSUE TITLE
Custom shipping methods cannot call `getShippingRules()`

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1758]
**Description**
Reported in https://github.com/craftcms/commerce/issues/1532 and https://github.com/verbb/postie/issues/36

I can't seem to call `method.getShippingRules()` from my custom shipping methods in https://github.com/verbb/postie/issues/36

```
{% for handle, method in cart.availableShippingMethodOptions %}
    {{ dump(method.getShippingRules()) }}
{% endfor %}
```

The above returns an empty array for any custom shipping method Postie provides. This value correctly returns an array of `ShippingRule` models for any static shipping methods defined in the CP.

Probably something to do with the `ShippingMethodOption` model?

**Additional info**
- Craft version: 3.5.11.1
- Commerce version: 3.2.7
- PHP version: 7.1
- Database driver & version: MySQL
- Other Plugins & versions: Postie 2.3.1

**Comment by lukeholder** [comment]
A shipping method option is an option object that is just populated from the data in a shipping method and its matching rule (price), it is not the shipping method object itself. If you want to get the shipping method/rule, you would need to use the handle selected to retrieve it. If you want to access data about the shipping rule used when calculating the adjustment, it is stored on the adjustment in `adjustment.sourceSnapshot`.

**Comment by lukeholder** [comment]
We need to document this better. Added a ticket here: https://github.com/craftcms/docs/issues/81

**Comment by engram-design** [comment]
Right, I suppose that makes sense, it's just a change in behvaiour from whenever that was introduced (3.1 or something?), so it's tripping people up.

**Comment by engram-design** [comment]
Actually, this doesn't really help. There is no saved shipping method to lookup with `craft.commerce.shippingMethods.getShippingMethodByHandle(handle)` because they're generated dynamically, depending on the response from the API. This call only fetches database-stored ones?

At the end of the day, we're just trying to access additional information on the shipping rule, which is the raw response from the provider API's about the rates. Things like the ETA of the package.

We were using `getAvailableShippingMethods()` which is now deprecated. What's the reason for that?

Can the creation of a `ShippingMethodOption` model serialize the method or the associated rules to the model? That way the templates have access to this information about the shipping method or rules.

**Comment by RitterKnightCreative** [comment]
@lukeholder Usually when you deprecate stuff it's replaced with a better alternative. In this case, there doesn't seem to be one? FWIW This makes me feel a little uneasy about using Commerce in the future if the ground keeps shifting. 

I'm guessing this is an oversight but how do you suggest plugins like Postie that leverage external APIs for shipping like FedEx and UPS add additional info to the snapshot? To expand on @engram-design Josh's point, for example, we do something like this on a client's site to show estimated transit /delivery time, among other things:

![Screen Shot 2020-10-05 at 10 53 09 AM](https://user-images.githubusercontent.com/3707869/95102742-60778100-06f9-11eb-8296-28971394047e.png)

Unless I use the deprecated method, the only thing we can retrieve is name and price. Serializing the rules for third party plugins seems like it would be effective? The only thing we need to make sure is to not cache that additional data on the cart until it becomes an order or the user will get stale data.

**Comment by engram-design** [comment]
To re-iterate what Postie does, is store a bunch of useful information from the providers into `options` https://github.com/verbb/postie/blob/craft-3/src/providers/FedEx.php#L251-L263, which are populated from the shipping method - https://github.com/verbb/postie/blob/1939c35e913bf800f879b1f3f694832cc207ed83/src/models/ShippingMethod.php#L59

This gives users like @RitterKnightCreative the opportunity to control any additional data and show as required.

**Comment by RitterKnightCreative** [comment]
@lukeholder @brandonkelly Not sure if there's an update here?

**Comment by engram-design** [comment]
@lukeholder Any more thoughts on this? Is Postie doing something wrong?

Just to refresh your memory, Postie is creating these shipping methods - using our own class `verbb\postie\models\ShippingMethod` which extends `craft\commerce\base\ShippingMethod`.

Consider the following debug code:

```
<h2>availableShippingMethods</h2><br>
{% for handle, method in cart.availableShippingMethods %}
    {% set price = method.priceForOrder(cart)|commerceCurrency(cart.currency) %}
    
    {{ method.name }} - {{ price }}<br>

    {% if className(method) == 'verbb\\postie\\models\\ShippingMethod' %}
        <code>{{ dump(method.rateOptions) }}</code>
    {% endif %}
{% endfor %}

<h2>getAvailableShippingMethodOptions</h2><br>
{% for handle, method in cart.getAvailableShippingMethodOptions %}
    {% set price = method.priceForOrder(cart)|commerceCurrency(cart.currency) %}
    
    {{ method.name }} - {{ price }}<br>

    {% if className(method) == 'verbb\\postie\\models\\ShippingMethod' %}
        <code>{{ dump(method.rateOptions) }}</code>
    {% endif %}
{% endfor %}
```

We're demonstrating the difference between `Order::getAvailableShippingMethods()` (deprecated) and `Order::getAvailableShippingMethodOptions()` with only the former approach working correctly. This is similar to https://github.com/craftcms/commerce/issues/1532#issuecomment-1021759658

This results in the following:

![image](https://user-images.githubusercontent.com/1221575/151087335-66a0fb5a-1988-4193-8742-6199b7217ae0.png)

Postie shipping methods provide `rateOptions` as some more raw, useful data from providers. For Australia Post, this might be insurance information like extra cover $'s, or Fedex showing estimated delivery times. People need to be able to get this additional information and output it in a custom way to customers during checkout. I don't believe it's good enough for Postie to use the description or name of a method to include this - instead leaving it up to the developer to construct this information as they see fit.

Hope that makes sense and can be reproduced so you can see what's happening?

**Comment by RitterKnightCreative** [comment]
@brandonkelly @lukeholder With Craft 4/Commerce 4 coming this year - maybe you're looking to solve this with something you can't talk about yet? 

The method we're calling now is deprecated, if it's removed in Craft/Commerce 4, we'd be stuck on Craft 3 for some time until there's a workaround.
