### ISSUE TITLE
Add "cp.commerce.shippingmethod.edit" hook in templates/shippingmethods/_edit

### ISSUE THREAD

**Issue by CMeldgaard** [craftcms/commerce#1759]
**What are you trying to do?**
I'd like to add some custom functionality / settings fields on the Shippingmethod edit page.

**What's your proposed solution?**
Before this field:
https://github.com/craftcms/commerce/blob/f7086c7d8b7d36c28fc3c1a27be9076a0ecd1271/src/templates/shipping/shippingmethods/_edit.html#L51-L57

Add
`{% hook "cp.commerce.shippingmethod.edit" %}`

**Comment by lukeholder** [comment]
@CMeldgaard Was can add something like this, but interested in knowing what it would be used for. Thanks.

**Comment by CMeldgaard** [comment]
We are creating an integration to a shipping handling system. To avoid having to duplicate the entire code from crafts shippingmethods, we would add a selectbox, where we use that select Box to connect the craft shipping method with the shipping system, Because each shipping method has a unique id in the shippingsystem.

**Comment by CMeldgaard** [comment]
@lukeholder Is this something that will come in the foreseable future ? Else i'll try and find a different solution to be able to set this setting.

**Comment by lukeholder** [comment]
@CMeldgaard We don't want to add twig hooks in between fields. Does it need to be inside the `<form`?

We could add a `{% hook 'cp.commerce.shippingMethods.edit.content' %}` at the bottom?

**Comment by CMeldgaard** [comment]
@lukeholder sure, that wont't be an issue for me, as long as i can save the data when pushing save on the shippingmethod :D

**Comment by pdaleramirez** [comment]
@CMeldgaard we created the template hook as request. We'll have it on next release.
