### ISSUE TITLE
Disable Search In Section Settings

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#176]
> Created by: Sean Smith ([sean@caffeinecreations.ca](sean@caffeinecreations.ca)) on 2017/03/14 18:33:14 +0000
Votes at time of UserVoice import: 1

------
I'd like to be able to disable a section from appearing in search results when creating the section. So in the section settings (on create/edit) I'd like a checkbox to allow/disable search results from this particular channel.

Currently you have to do it in the search template, which to me is counter intuitive.

**Comment by nfourtythree** [comment]
Please see https://github.com/craftcms/cms repo
