### ISSUE TITLE
Unable to Export Orders with "Raw data (fastest)" Export Type

### ISSUE THREAD

**Issue by jlapan** [craftcms/commerce#1760]
**Description**
I am unable to export orders using the Export Type of "Raw data (fastest)" and receive the following error:

`yii\base\ErrorException: Trying to get property 'id' of non-object in [my-directory-path]/vendor/craftcms/commerce/src/services/LineItems.php:409`

**To Reproduce**
How, and what happened?
1. In the CP under Commerce->Orders, click the "Export..." button.
2. Choose "Raw data (fastest) Export Type.
3. For "Format" choose "CSV" (it actually doesn't work for any of the available formats).
4. Click "Export"

**Expected behavior**
I expected the file to download.

**Additional info**
- Craft version: Craft Pro 3.5.7
- Commerce version: 3.2.3
- PHP version: 7.2.27
- Database driver & version: MySQL 5.5.62

**Comment by nfourtythree** [comment]
Hi @jlapan 

We pushed a fix related to raw exports in `3.2.5` I noticed that you are on a version previous to that.

Could you try updating and see if the issue persists?

Thanks.

**Comment by jlapan** [comment]
@nfourtythree, thank you. That corrected my issue :)
