### ISSUE TITLE
Throw an event to manipulate DomPDF before rendering a PDF via $dompdf->output()

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1761]
**What are you trying to do?**
I'm trying to render images in my order PDF, but DomPDF suddenly changed the way images are loaded. This is explained in https://github.com/dompdf/dompdf/issues/2229
So it would be nice to be able to manipulate your DomPDF object and add
```PHP
$options->setChroot(Craft::getAlias('@assetPath'));
``` 
to be able to render the assets again.

**What's your proposed solution?**
Either create an event to manipulate the path or add a settings variable available via
```PHP
$chrootPath = Plugin::getInstance()->getSettings()->pdfChrootPath;
// ...
// check if path is not empty and such...
$options->setChroot($chrootPath);
```

**Comment by pdaleramirez** [comment]
@Anubarak There is currently breaking change for dompdf 0.8.6 downgrading the previous version would solve the issue for now. Similar issue mentioned here https://github.com/craftcms/commerce/issues/1727

**Comment by Anubarak** [comment]
@pdaleramirez thank you. I know that. I explained it in my first post

**Comment by pdaleramirez** [comment]
Duplicate issue #1727

**Comment by Anubarak** [comment]
Why should that be duplicated?
I just want an event to manipulate the DomPDF Object
It's not only because of that specific issue

**Comment by pdaleramirez** [comment]
@Anubarak dompdf 0.8.6 requires php version 7.1, Craft 3 needs to support 7.0. Craft 4 would raise the php requirement by then we can add the enhancement.

**Comment by Anubarak** [comment]
I know that.. but what does the PHP Version has to do with an additional event to change the DomPDF object in general?

**Comment by pdaleramirez** [comment]
@Anubarak Dompdf states here https://github.com/dompdf/dompdf/releases/tag/v0.8.6 that php requirement is > 7.1.

**Comment by Anubarak** [comment]
I know that... I just don't know why the php requirement for dompdf is an argument against an event in commerce. Maybe @lukeholder can explain why their PHP version prevents you to include an event. Because I can do that without any issues, the version does not matter.

**Comment by pdaleramirez** [comment]
@Anubarak We'll add an event to allow setting of options before it gets rendered.

**Comment by Anubarak** [comment]
Thank you very much 👍

**Comment by pdaleramirez** [comment]
@Anubarak You can use an event to modify the pdf render options. Usage is in the comment. https://github.com/craftcms/commerce/blob/d866afbabd25977e326a7643713239bb33cf82ec/src/services/Pdfs.php#L171
