### ISSUE TITLE
Add "default variant price" attribute to product

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1762]
If there was default variant price attribute, we would be able to sort products by this price using `orderBy` in element queries, for example:

```
products.orderBy('defaultVariantprice asc')
```

**Comment by pdaleramirez** [comment]
@piotrpog You can't sort stock through the Product Element because a product type might not support multiple variants. The correct way to this is query via the Variant Element 
E.g.
```
$products = Variant::find()->orderBy('stock asc')->all();
```
I hope that works.

**Comment by lukeholder** [comment]
Should be able to do `products.orderBy('defaultPrice asc')`
