### ISSUE TITLE
Make Coupon Code case in-sensitive

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#1763]
It would nice if coupons are case in-sensitive. Most customers copy paste coupon codes however there are still some who type it in and when doing so they often forget about uppercase vs lowercase.

For example:

Coupon code: **10%Off**

Customer enters **10%off** and it does not work.

**Comment by lukeholder** [comment]
I can't reproduce.

Code that does the matching: https://github.com/craftcms/commerce/blob/develop/src/services/Discounts.php#L956

```php
strcasecmp("10%Off", "10%off") == 0;
```
returns true.

Are you on the latest version?

**Comment by philipboomy** [comment]
Thanks for looking into it Luke

Ah I see... I am submitting via ajax and I I get a response saying coupon code not valid if I replace a lower case with uppercase for example. Perhaps that makes a difference?

**Comment by lukeholder** [comment]
@philipboomy what version are you on?

**Comment by philipboomy** [comment]
Sorry I missed your questions about being on the latest version but yes. I am on latest.

Commerce 3.2.7
Craft 3.5.12.1

**Comment by lukeholder** [comment]
Dug a little deeper and found the issue. Fixed for the next release.

**Comment by philipboomy** [comment]
@lukeholder Thank you looking into it and fixing it.

**Comment by boboldehampsink** [comment]
@lukeholder it appears coupon codes are now case-sensitive once again on 3.3.4.1 w/ postgres
