### ISSUE TITLE
Saving disabled product - empty stock throws integrity constraint violation 

### ISSUE THREAD

**Issue by i-just** [craftcms/commerce#1764]
Craft CMS Pro 3.5.12
Craft Commerce Pro 3.2.7

When adding new product and setting it to not be enabled if no stock value is provided or I don't check "unlimited" when I try to save it, I get the following error:
```
Integrity constraint violation: 1048 Column 'stock' cannot be null
The SQL being executed was: INSERT INTO `td_commerce_variants` 
```

Have I missed something here or is this a bug and it should either allow you to save as the product is set to be disabled or it should show a proper error message (if devMode disabled it results in Internal Server Error).

**Comment by lukeholder** [comment]
This has been fixed in 

12f50de767927502503c2cf59f411b1e159c39c8
b37e51cfe9f94869f54bef63786ab09dbee2e21d
ca74cb45741d7780989a7bbcae33a3f2f2487385

Will be in the next release.
