### ISSUE TITLE
Shipping Address gets overwritten when saving order in CP, if copied from Billing Address, or loaded from saved address

### ISSUE THREAD

**Issue by GaryReckard** [craftcms/commerce#1766]
**Description**
If you are creating a new order in the CP, add a billing address, and then “Copy to Shipping Address”, and then edit the shipping address, add a line item and “Update Cart”, the shipping address reverts to the billing address.

Also, if you were to select an existing user, it will bring up their saved addresses. If you make edits to those and click "Update Order" your edits get clobbered, and the original addresses come back.

**To Reproduce**
How, and what happened?
1. In the CP, go to create a new order
2. Add a new customer
3. Fill out a new Billing Address
4. Choose to Copy to "Shipping Address"
5. Make edits to shipping address.
6. Add a line item. And then "Update Cart"
7. Edits to shipping address disappear, ends up same as Billing Address

**Expected behavior**
I'd expect my edits to the Shipping address to hold.

**Additional info**
- Craft version: 3.4.25 and 3.4.25
- Commerce version: 3.1.9
- PHP version: 7.3

**Comment by nfourtythree** [comment]
Hi @GaryReckard 

Thank you for bringing this to our attention. We have pushed an update for this which will be included in the next release of Commerce.

Thanks!

**Comment by GaryReckard** [comment]
**Much** appreciated, @nfourtythree!!!
