### ISSUE TITLE
Incorrect tax calculations on total taxable price when tax included in subject price

### ISSUE THREAD

**Issue by mattsbanner** [craftcms/commerce#1770]
Hi 😄 

**Description**
Experiencing incorrect tax calculations on order total taxable price when tax is included within subject price. I've been unable to pinpoint exactly what is going wrong within the plugin. I seem to be getting 16.67% tax when it should be 20%.

**To Reproduce**
1. Install Craft Commerce Pro to fresh CMS project.
2. Copy over Commerce shop example templates to templates directory.
3. Switch payment currency to GBP.
4. Create UK tax zone
    - Default when no shipping address: _TRUE_
    - Type: _Country-based_
    - Countries: _United Kingdom_
5. Create VAT tax rate
    - Taxable Subject: _Order Total Taxable Price_
    - Rate: _20%_
    - Tax Zone: _UK_
    - Tax Included in Taxable Subject: _TRUE_
6. Add an example product to cart and set delivery address country to UK.

**Expected behavior**
When looking at the cart. VAT should be shown at 20% of the order price. Instead we're seeing rather random results. A single product at £70.00 is showing with included tax of £11.67.

This discrepancy seems to be effecting both products and shipping.

**Additional info**
- Craft version: 3.5.12.1
- Commerce version: 3.2.7
- PHP version: 7.3.21
- Database driver & version: MySQL 5.7.31
- Other Plugins & versions: None

**Comment by mattsbanner** [comment]
Clearly this was a long day...

Commerce is calculating things absolutely fine, it's me that's wrong! 😄

**Comment by masiorama** [comment]
@mattsbanner can you please elaborate what kind of error did you do, because I am experiencing the same problem: setting 22% included tax and it is calculated as it is 18% or something similar...  scratching my head for hours.

**Comment by mattsbanner** [comment]
I was calculating tax incorrectly. This might not be your problem and the below may be obvious to you and not explain the issue you are having, but it's where my head was at!

If you have a product that costs $100 and 20% of it is tax, it's not as simple as the tax being $20 as the $100 already includes the tax, we want to know what it was before the tax was added.

The tax free price of a $100 product at 20% would be $83.33. To calculate this you can do 100/1.2 as we have 120% of the value we want. In your case it would be 100/1.22 for 22%. 

100 - (100/1.22) = 18.33%, so this may be what you are seeing.

**Comment by masiorama** [comment]
@mattsbanner can I quote you?  

> Clearly this was a long day...
> 
> Commerce is calculating things absolutely fine, it's me that's wrong! 😄

Thank you!
