### ISSUE TITLE
Deleted products aren't being deleted from database

### ISSUE THREAD

**Issue by joe-protz** [craftcms/commerce#1772]
**Description**
Deleted products seem to persist, not allowing me to replace them with new products of the same SKU

**To Reproduce**
How, and what happened?
1. Used feedme to feed products into commerce 
2. Delete the products in the CP
3. Re-Run the feed
4. Try to enable the products in the cp
5. Get error:  ` SKU "<sku-name>" has already been taken.`

**Expected behavior**
What did you expect to happen?
- The original products to be fully deleted and the new products to be enabled

**Additional info**
- Craft version: Craft Pro 3.4.5
- Commerce version:  3.1.12
- PHP version: 7.3.21
- Database driver & version: MySQL 5.6.40
- Other Plugins & versions: 
  - Feedme: 4.2.3

**Additional context**
I checked the DB and it seems like all of the products (from both feeds ) are still there despite deleting them. The feed is 155 products and I have 310 in the db table commerce_products.

I found a few other similar issues, and tried to SSH in and ran `$ php craft gc --delete-all-trashed=1`
 Which resulted in `Running garbage collection ... done` 
However this seemed to not change anything in the DB.

**Comment by joe-protz** [comment]
Related to #734
UPDATE: I was wrong, running garbage collection does delete the products themselves however it is not deleting the variants, which is causing the issue.

**Comment by joe-protz** [comment]
UPDATE 2:
I re ran the feed but this time with the variant enabled by default, deleted the items, and then re-ran GC. It seems enabling them caused them to be properly linked and they got deleted. However I'm still stuck with all of the old variants with a `NULL productId` in the database, is there a way to manually remove them so I can free the sku?

**Comment by lukeholder** [comment]
Fixed the bug where disabled variants where not getting deleted.

If you want to delete all variants without a product id, you will need to run the following code:

```php

        $variants = Variant::find()
            ->productId(':empty:')
            ->anyStatus()
            ->all();

foreach ($variants as $variant) {
  $elementsService = Craft::$app->getElements();
  $elementsService->deleteElement($variant, true);
  $variant->deletedWithProduct = false;
}
```
