### ISSUE TITLE
Changing currency error

### ISSUE THREAD

**Issue by SHoogland** [craftcms/commerce#1777]
**Description**
Changing the store currency after an order has been created, then returning to that order gives an internal error.

**To Reproduce**
How, and what happened?
1. Create an order (buy something idk doesnt matter)
2. change the store currency admin/commerce/store-settings/paymentcurrencies
3. return to the created order
4. big 500 internal server error

![image](https://user-images.githubusercontent.com/2057831/95558973-55816100-0a17-11eb-97c1-ac3b1afb318f.png)

**Expected behavior**
Some graceful way of craft commerce telling me the original order currency no longer exists

**Additional info**
- Craft version: 3.5.12.1
- Commerce version: 3.2.7 (Lite)
- PHP version: 7.4.11
- Database driver & version: MySQL 5.7.31
- Other Plugins & versions:

**Additional context**
Probably not a very common issue, but it took me a while to figure out what I did wrong

**Comment by nfourtythree** [comment]
Hi @SHoogland 

We have pushed an update that relates to this issue. The update will be included in the next upcoming release of Commerce.

It was actually a bug that you were able to change the primary payment currency. The primary payment currency is only allowed to be changed if there **are no completed orders** in the system. Once there are completed orders the primary currency is locked in.

My assumption is that you have come across this issue during development? I can't see a reason for changing the primary currency on a production site, I would be interested to hear if you do have a specific use case for that (if my assumption is wrong).

Included in the next release is the reset data command line functionality (#581) this will allow you to reset your Commerce data and get your project working again.

If you do not wish to reset all of the data you can delete all elements in the craft `elements` table with a `type` of `craft\commerce\elements\Order`. This will also fix your issue.

Thanks!

**Comment by SHoogland** [comment]
Your assumption is correct, I was setting up a new site, and came across this on my development machine. Nice work fixing it so quick 👍
