### ISSUE TITLE
Asset File Model - getImg(transform)

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#178]
> Created by: Adam Menczykowski ([adammenczykowski@gmail.com](adammenczykowski@gmail.com)) on 2017/03/02 16:39:53 +0000
Votes at time of UserVoice import: 2

------
As the title suggests, extend the getImg method to accept image transforms when generating a full image tag from an image asset.

**Comment by nfourtythree** [comment]
See https://github.com/craftcms/cms repo
