### ISSUE TITLE
Cannot display column with ID in products list in control panel

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1787]
When i click cogwheel icon to set which columns should be displayed, there is no "ID" option.

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.

**Comment by stenvdb** [comment]
@lukeholder The "ID" doesn't show the product's ID but its title instead here. Seems wrong? And the new "ID" column cannot be unchecked.

**Comment by nfourtythree** [comment]
Hey @stenvdb 

Thank you for pointing this out, we have pushed an update that should fix this issue.

Thanks!
