### ISSUE TITLE
Mark fields "unique" / New Fieldtype "Unique" field

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#179]
> Created by: Florian ([fw@demodern.de](fw@demodern.de)) on 2017/03/01 16:34:06 +0000
Votes at time of UserVoice import: 2

------
Fields can't be marked unique..but sometimes that makes a lot of sense.

There's a super simple plugin for this field type: https://github.com/rally-agency/Craft-Unique-Text-FieldType

but those 3 lines of code really seem to be native...not a plugin?

**Comment by lukeholder** [comment]
Please submit this to https://github.com/craftcms/cms/issues
