### ISSUE TITLE
Data "dateOrdered" different in combination with hook

### ISSUE THREAD

**Issue by hilbertknl** [craftcms/commerce#1790]
**Description**
We use a module to export orders to the customers E-accounting application.
Therefore we use a custom build plugin with this hook: Order::EVENT_AFTER_COMPLETE_ORDER
When you open the attribute 'dateOrdered' inside this sender object, you will se a PHP DateTime object.
When manually executing the script and manually getting the order data (\craft\commerce\elements\Order::find()->id(ORDERID)->one();) you will see a string date.

This happend after we installed the newest version of Craft and Commerce.

**To Reproduce**
How, and what happened?
1. Use the hook as described
2. Log the result
3. Do the same with manually getting an order
4. Log the result

**Expected behavior**
What did you expect to happen?
I expected a normal date string as we got in the previous version.
The results should be equal.

**Additional info**
- Craft version: SOLO 3.5.13.2
- Commerce version: PRO 3.2.8.1
- PHP version: 7.3.13

**Comment by lukeholder** [comment]
The dateOrdered should always be DateTime object unless it is null.

`
$order = \craft\commerce\elements\Order::findOne(65);
$dateOrdered = $order->dateOrdered;

$entry = \craft\elements\Entry::findOne(68);
$postDate = $entry->postDate;
```

Both `$postDate` and $dateOrdered` are both DateTime objects.

I tested the attribute (on latest craft and commerce) both in a query as above and in the event you referenced and I am getting a DateTime object both times (https://jmp.sh/eLVvaHY).

Closing for now, but please let me know if I missed something.
