### ISSUE TITLE
'Manage Products' permission also requires 'Access Craft Commerce' permissions?

### ISSUE THREAD

**Issue by shornuk** [craftcms/commerce#1791]
**Description**
We have a front end product form. I've enabled the "Mangage Products" permission for the relevant product type. However when trying to add a product the front end form reports ''does not have permission". The only was I can get it to work, is to enabled the "Access Craft Commerce" permission in General which in turn, also requires CP access. 

Is this right?

**Additional info**
- Craft version: 3.5.11.1
- Commerce version: 3.2.6
- PHP version: 7.3.11

**Comment by pdaleramirez** [comment]
@shornuk Yes, that is the correct behavior. You can only add products if the current logged in user has the control panel access with "Access Craft Commerce" ticked and manage products permission under Craft Commerce section.

**Comment by shornuk** [comment]
👍
