### ISSUE TITLE
Manage multi-stocks (or multi warehouses)

### ISSUE THREAD

**Issue by DidoMarchet** [craftcms/commerce#1794]
Hi,
I think it could be useful have the possibility to manage multi-stocks (or multi warehouses).
I thinks this is a good enanchement for sellers who have different shops and they want to notify where the product is available (for example).

Hope it could be an idea.

Thanks and regards,

Davide

**Comment by nfourtythree** [comment]
Hi @DidoMarchet 

Thank you for the FR. I will close this as this is part of the inventory management FR we have here: #44

Thanks!
