### ISSUE TITLE
Dynamic price modifiers built into the options params

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#180]
> Created by: Markus Rönkkö ([markus.ronkko@padio.fi](markus.ronkko@padio.fi)) on 2017/02/22 14:37:08 +0000
Votes at time of UserVoice import: 5

------
For a product, I'd like to add custom fields with options which modify line item price in cart. I have multiple fields and all of them have multiple options. Some options affect the price but some not.

**Comment by lukeholder** [comment]
Use line item options, and the onPopulateLineItem to change the price based on those options.
