### ISSUE TITLE
Shipping rate seems incorrect when a discount is applied

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#1800]
**Description**
A client has let me know that when a certain discount is applied to an order, it affects the shipping rate of the order in a way that they did not expect. Please can you let me know if this can be adjusted. 

**To Reproduce**
How, and what happened?
1. Order total came to £124.99
2. Discount the customer applied was 25% off the order total, which meant the order total was adjusted to £99.99
3. The shipping method the customer chose has a conditional for free shipping on orders over £100
4. This order qualified for the free shipping as it didn't seem to factor discount applied

**Expected behavior**
What did you expect to happen?
I would expect the shipping rate to be taken from the order total, after discount adjustments have been made, but it doesn't seem that way. Is there any way to adjust this?

**Additional info**
- Craft version: 3.4.27
- Commerce version: 3.1.4

**Comment by lukeholder** [comment]
The shipping rule in question says:

"The minimum total *value* of items in the cart (before any adjustments) to match this rule. Zero matches all carts."

This means the value of the products in the order, not their price after discount adjustments have been applied.

This is because shipping rules and adjustments are run before the discount adjuster are run.

The same condition on purchase *value* is on the discounts conditions, since discounts that are being checked at the beginning of the discounts being applied, don't know the final price after the future discounts are applied. Its a chicken and egg problem.

You could try using a Discount with the following condition:

https://jmp.sh/pXWuG3R

That makes the order have free shipping.

but you would make the discount be the last one in the list, so that is processes last.

**Comment by engram-design** [comment]
Just ran across this exact issue on a multi-site. I did consider shifting to a discount, but I need the shipping threshold to be site-aware, ie: free shipping over £100, or over $150 (AUD), or over $120 (USD). This can be achieved by using shipping methods' restriction to countries.

I would expect (and the client also did like @iamtompickering ) that free shipping handle discounts.

Can you use order conditions to maybe check against the site it's used on?

**Comment by iamtompickering** [comment]
That is the same situation my client is in with regards to the shipping thresholds @engram-design. 

For this reason, using the Order Condition Formula would not work.

**Comment by lukeholder** [comment]
@iamtompickering 

As explained the condition is labelled as a total order value not including any adjustments (including discounts):

Fields description:
> The minimum total value of items in the cart (before any adjustments) to match this rule. Zero matches all carts.

I will try to figure out a new condition that could try to pre-calculate the item total including discounts, but we will need to test the affect on performance, and also to see if it is even possible. No promises, but will keep you updated here.

Re-opening this issue while I work on it.

**Comment by bartrylant** [comment]
This is something I would also really need to be honest. Client just started sales for the first time on her website and now has over 100 orders far below the threshold for free shipping, that all got free shipping.

**Comment by iamtompickering** [comment]
@bartrylant 

I have created fork which uses Commerce 3.1.4 (this was my current Commerce version on the site in question) and includes an adjustment which seems to resolve this issue. 

https://github.com/iamtompickering/commerce

All I have changed is the conditionals for `maxTotal` and `minTotal` in `src/models/ShippingRule.php`. I have created a new variable which deducts the discount from the order subtotal, and uses that within the conditionals. 

Hope this helps!

**Comment by bartrylant** [comment]
Hi @iamtompickering 

Is that the only file you changed? I'm on 3.2.13.2 now, so I'm wondering if this would work…

**Comment by iamtompickering** [comment]
@bartrylant 

The only other change in my fork was to `src/elements/db/OrderQuery.php`. I had to adjust the conditional:

```
if ($commerce && version_compare($commerce['version'], '3.0.7', '>='))
```

I think because my fork was called `dev-shipping-threshold`, it wasn't hitting this conditional. But you need the `storedTotalDiscount` to be added to the DB. 

So I just changed the conditional to:

```
if ($commerce) {
```

Seemed a bit hacky, but it worked...

**Comment by iamtompickering** [comment]
@bartrylant could be my bad this...

https://github.com/iamtompickering/commerce/tree/shipping-threshold

Didn't link to the correct fork in my original comment. 

This is the change you want to look for in `src/models/ShippingRule.php `

```
        $totalMinusDiscount = $order->itemSubtotal + $order->storedTotalDiscount;

        // order total rules exclude maximum limit (min <= x < max)
        if ($this->minTotal && $this->minTotal > $totalMinusDiscount ) {
            return false;
        }
        if ($this->maxTotal && $this->maxTotal <= $totalMinusDiscount ) {
            return false;
        }
```

**Comment by lukeholder** [comment]
Working on this in #1948

**Comment by bartrylant** [comment]
Hi

I thought this was fixed in a Commerce release from a few weeks ago, but it seems like it is not. Any updates?
