### ISSUE TITLE
Address detail page in control panel - show if address is default for billing/shipping

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1802]
Right now we can see this info on the addresses list, but no on the single address details page.

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Thank you for the issue.

We have added a notice to the edit address page if you are editing a primary address for a customer.

We considered adding toggles to be able to edit but it feels too "out of context" when you are on the address and is easy enough to do from customer/user edit.

This update will be in the next release.

Thanks.

**Comment by piotrpog** [comment]
@nfourtythree 
Thanks!
