### ISSUE TITLE
404 error when creating shipping zone

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#1809]
404 error when trying to create a shipping zone.

Create a shipping method.
Create a shipping rule
Under Conditions, try to create a new Shipping Zone.
The form that appears in the modal tries to submit to  `/index.php?p=admin/actions/commerce/shippingZones/save and causes a 404 error`

I believe the URL should be `/index.php?p=admin/actions/commerce/shipping-zones/save`

**Additional info**
- Craft version: 3.5.14
- Commerce version: 3.2.8.1
- PHP version: 7.3

**Comment by fantasticmachine** [comment]
I submitted a pull request to fix this issue but it appears the build is failing.

**Comment by lukeholder** [comment]
Thanks, I merged the fix!
