### ISSUE TITLE
Free shipping based on shipping method

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#181]
> Created by: idol chan ([idolchan@gmyle.com](idolchan@gmyle.com)) on 2017/02/21 04:49:32 +0000
Votes at time of UserVoice import: 3

------
Free shipping on product / promotion is globally applied on all shipping methods. Making that a checklist of all shipping methods so the user can can select what shipping method is free shipping

**Comment by lukeholder** [comment]
This will be possible in the future with #80
