### ISSUE TITLE
saveDiscount does not update _allDiscounts

### ISSUE THREAD

**Issue by cgivord** [craftcms/commerce#1813]
**Description**
In the discount service, _allDiscounts is never updated / invalidated.

**To Reproduce**
$d = CommercePlugin::getInstance()->getDiscounts()->getDiscountByCode('XXX');
if (!$d) {
  $d = new Discount();
  $d->code = 'XXX';
  ...
  CommercePlugin::getInstance()->getDiscounts()->saveDiscount($d);
}
...
$d = CommercePlugin::getInstance()->getDiscounts()->getDiscountByCode('XXX');
// $s is null

**Expected behavior**
The newly saved discount could be retrieved from the DB.

**Additional info**
- Craft version: 3.5.14
- Commerce version: 3.2.8.1
- PHP version: 7.2
- Database driver & version: mysql 5.6
- Other Plugins & versions:

**Comment by lukeholder** [comment]
Thanks, this is fixed for the next release.
