### ISSUE TITLE
Different SKU, price and stock per locale

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#182]
> Created by: Anonymous ([arnotenhagen@gmail.com](arnotenhagen@gmail.com)) on 2017/02/07 18:58:47 +0000
Votes at time of UserVoice import: 6

------
We have customers who want to insert different SKU, price and stock per locale. So:

Germany -> SKU DE983123, Price: 100, Stock 5
France -> SKU FR983123, Price: 110, Stock 50

**Comment by nfourtythree** [comment]
Further discussion on #37
