### ISSUE TITLE
Possible to use getId() instead of property purchasableId when checking discount for item

### ISSUE THREAD

**Issue by davecosec** [craftcms/commerce#1824]
be able to manipulate the purchasable ID for custom purchasables, currently accessing the property directly doesnt allow this

Change 396 in craft\commerce\services\Discounts

```
       if ($discount->getPurchasableIds() && !$discount->allPurchasables) {
            if (!in_array($lineItem->purchasableId, $discount->getPurchasableIds(), true)) {
                return false;
            }
        }
```

to

```
       if ($discount->getPurchasableIds() && !$discount->allPurchasables) {
            if (!in_array($lineItem->getPurchasable()->getId(), $discount->getPurchasableIds(), true)) {
                return false;
            }
        }
```

**Comment by lukeholder** [comment]
@davecosec The purchasableId is populated on the line item from the purchasable set on the line item when it was created: https://github.com/craftcms/commerce/blob/aa6ca834cd977902354fdf7296b27a021bb586b9/src/models/LineItem.php#L656

The purchasableId is a property of the line item, you can't change the purchasableId of a line item, so by the time the discount code is being run, the ID is locked in on the line item.

What are you trying to do.

**Comment by davecosec** [comment]
Fair enough, it's quite an edge case, I've resorted to just overriding the discount class. Thanks anyway!
