### ISSUE TITLE
Confusion re. demo templates and account creation during checkout

### ISSUE THREAD

**Issue by j-greig** [craftcms/commerce#1825]
**Description**
I'm confused by the account creation flow in the demo 'shop' templates and have been testing this on a vanilla install to try and get my head round it. 

One of our clients has a whole load of orders that are not connected to a user account so it would be super helpful to have some guidance on this.

Could you please provide details of how this whole flow works?

Some of the things I'm unsure of...
1. Why is the "Register me for a user account" checkbox on the payment screen, not on the earlier Register/Checkout screen? (the account is created as soon as you submit on the Register/Checkout form, I think?)
2. Sometimes the "Register me for a user account" is not visible on the payment form, even though I'm not logged in. Is the `craft.users.email(cart.email).one()` value being cached somewhere? (Edit, I can see in the Cart Debug that my email / customer ID from a previous session is being used, even though I'm not logged in).

**Additional info**
- Craft version: 3.5.14
- Commerce version: 3.2.8.1
- PHP version: 7.1

**Comment by lukeholder** [comment]
The "Register me for a user account" sets the `registerUserOnOrderComplete` property to true on the order.

If set to true, and when *the order is completed*, a user account is created for the customer of the order:

https://github.com/craftcms/commerce/blob/aa6ca834cd977902354fdf7296b27a021bb586b9/src/services/Customers.php#L828-L901

As you can see from the code above a user is not created regardless of the `registerUserOnOrderComplete` param if:
- A user account already exists for the customer of the order
- The edition is not Pro
- The order had no email (should have been caught earlier during checkout but just in case, it checks)
- A user already exists with the same email as the order's email. (Order consolidation will take care of moving this order to that user)

No error happens with any of the above, it just skips creating a user for that order.

In the example templates we only show the checkbox on the payment screen, but you can put it anywhere during checkout.

We also guard for an existing user account with the same email address as the order and don't show the button:

```twig
{% set user = craft.users.email(cart.email).one() %}
{% if not user %}
<label for="registerUserOnOrderComplete">
    <input type="checkbox" id="registerUserOnOrderComplete" name="registerUserOnOrderComplete" value="1" /> {{ "Register me for a user account"|t }}
</label>
{% endif %}
```

But the above check is optional, it was just done to simplify the form for people that may already have a user account.

**Comment by j-greig** [comment]
That was quick, thanks @lukeholder !
