### ISSUE TITLE
Edit/insert addresses of users in CP

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#183]
> Created by: Anonymous ([arnotenhagen@gmail.com](arnotenhagen@gmail.com)) on 2017/02/07 18:56:00 +0000
Votes at time of UserVoice import: 5

------
Why is it not possible to add or edit an address of an user in de control panel? We have customers who want to add/edit the first address of all users. So please expand the Commerce Customer Info fieldtype with this feature.

**Comment by lukeholder** [comment]
You can edit the customer addresses with the customer field added to the user field layout.
