### ISSUE TITLE
Allow placing in cart more products than are on stock

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1833]
In many eccomerce systems we can save cart with more products then there are on stock, such cart just is impossible to purchase.

In craft commerce it seems that when we update cart with more items that are on stock, an incorrect amount shows up (along with errors if we choose to display them) but when we refresh page products are set to their maximum stock number.

So for rexample, we have 10 socks on stock. Client initially added 5 of them to cart. Then clint changes number to 20, error shows up. And when page is refreshed, number magically changes to 10 - maximum amount.

But client never wanted to get 10 socks. He initially wanted 5. This behavior is kinda unpredictable. Maybe if there are no 20 socks, client would want to remove product from cart all together? But after refreshing cart, error disappears so someone might not notice new number (10 socks) and think everything is as he/she wanted.

**Comment by pdaleramirez** [comment]
@piotrpog I couldn't recreate your issue. I tested on Commerce 2 and 3 both with single and multiple variants. I used the example templates for each versions. It doesn't set to the maximum stock amount, It sets to the previous inputted quantity. What exact version of Commerce are you using? Are there any major changes to the template you've done? It could be front end code causing the issue.
