### ISSUE TITLE
Default templates - use snapshot of line items instead of "purchasable" property

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1834]
I noticed that default templates do not use snapshots.

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Whereabouts in the example templates are you seeing this issue?

Generally people will be using data from the `purchasable` key in the cart/before payment. And then test the existence of the `purchasable` in things like order history where there is a chance that data may no longer exist.

**Comment by piotrpog** [comment]
Actually, there is no issue at all - i thought that order data will change after we change details of the product price in the database (because snapshit was not used), but it seems that it is not the case.

Sorry for false alarm!
