### ISSUE TITLE
Error to get the product's variants in console

### ISSUE THREAD

**Issue by mostafasoufi** [craftcms/commerce#1839]
I wonder why getting `getVariants()`  in the below product query returns the error on the console, It was working before the latest updates.

```
$product             = Product::find();
$product->defaultSku = 23;

$searchedProduct     = $product->one();
$variants            = $searchedProduct->getVariants();
```

```
Calling unknown method: craft\console\Request::getUrl()
vendor\yiisoft\yii2\base\Component.php:300
```

Also, I used a `where` instead of the variable but still didn't work.

```
$searchedProduct = $product->where(['defaultSku' => $directoProduct->getSku()])->one();
```

Any idea?

**Additional info**
- Craft version: Craft Pro 3.5.14
- Commerce version: 3.2.9.1
- PHP version: 7.2.19

**Comment by pdaleramirez** [comment]
@mostafasoufi It might because you are trying to get variants on a missing `$searchedProduct` can you try wrap it in a condition like this 
```php
        $variants = null;
        if ($searchedProduct !== null) {
            $variants = $searchedProduct->getVariants();
        }
```
And see if that works.

**Comment by mostafasoufi** [comment]
I already used a condition to make sure the `$searchedProduct` has value or not.

```
if (!$searchedProduct) {
     $this->stdout($this->ansiFormat("NOTICE: The product with SKU: {$directoProduct->getSku()} not found in e-store.", Console::FG_BLUE) . PHP_EOL);
     continue;
}
```

Anyway now it working fine! It's weird. maybe it depended on the latest update.

Thanks!
