### ISSUE TITLE
Product Title Format

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#185]
> Created by: Trevor Davis ([davist11@gmail.com](davist11@gmail.com)) on 2017/02/03 19:24:51 +0000
Votes at time of UserVoice import: 8

------
It would be great to be able to use twig to format Product Titles.

For example, we have product titles that are made up of a collection (relationship), model number (string), and suffix (string).

{collection.first.title} {modelNumber} {titleSuffix}

**Comment by nfourtythree** [comment]
Duplication of #148
