### ISSUE TITLE
Craft Commerce: "Invalid Configuration – Variant is missing its product" on all delete actions

### ISSUE THREAD

**Issue by SystemsAlex** [craftcms/commerce#1853]
**To Reproduce**
How, and what happened?
1. Create Product types with feild on field layouts for Products and Variants
2. Add a product though commerce or select an existing
3. Delete
4. Invalid Configuration – yii\base\InvalidConfigException Variant is missing its product

**Expected behavior**
Product Deleted

**Additional info**
- Craft version: 3.5.14
- Commerce version: 3.2.9.1
- PHP version: php:7.4-fpm
- Database driver & version: Mysql (latest)
- Other Plugins & versions: Super Table, SEO, Redactor, Read-only Field, Custom Plugin 

**Additional context**
https://github.com/craftcms/commerce/issues/405
https://github.com/craftcms/commerce/issues/650

It seems that this is due to some Product Types added several months ago, based on restoring an old database from backup.

I have fully debugged the issue and can confim that the Product in question has the correct ID's for the product and Variants in place.  It seems as thought as this is thrown in $element->afterDelete(); that the function to "setProduct" in commerce isn't being called, or alternatively something is getting cloned or requeried without setting up $this->productId.   Although it is likely the case that the field layouts have an issue, this is clearly still a bug, given that the productId is correct in the DB.

1. in /var/www/vendor/craftcms/commerce/src/elements/Variant.phpat line 416
407408409410411412413414415416417418419420421422423424425     * @throws InvalidConfigException if the product ID is missing from the variant
     */
    public function getProduct()
    {
        if ($this->_product !== null) {
            return $this->_product;
        }
 
        if ($this->productId === null) {
            throw new InvalidConfigException('Variant is missing its product');
        }

**Comment by lukeholder** [comment]
@SystemsAlex Can you make sure you are on Commerce 3.2.11 - I think this issue should be fixed.

**Comment by SystemsAlex** [comment]
I'm on commerce 3.2.9.1, composer says it has nothing to update.

**Comment by SystemsAlex** [comment]
Your right that said seems to have fixed it, I was convinced that said fix was in an earlier version, apologies.
