### ISSUE TITLE
[FR] - change status of order from order list

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1854]
Just like we can set multiple entries status to disabled. Widget is even there, on order list, but it just allows removing.

**Comment by lukeholder** [comment]
You can do already this from the order edit screen if you change the status while on a selected status source: https://jmp.sh/2Rq8dRP

**Comment by piotrpog** [comment]
@lukeholder 
Thanks for the video!
Just noticed this option - it was not present on "all orders" page, only on lists of orders with a specific status. Maybe it should also be added there?
