### ISSUE TITLE
Shipping/billing address summary in control panel order view - display field labels next to address values

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1855]
So, instead of :
```
john smith
New york
USA
```
Display this:
```
Name: John
Surname: smith:
City: New york
Country: USA
```

Or at least allow overwriting this display with custom twig template that would render address summary.

**Comment by nfourtythree** [comment]
Hi @piotrpog 

This is possible using the `Address::EVENT_DEFINE_ADDRESS_LINES` event (https://github.com/craftcms/commerce/blob/develop/src/models/Address.php#L39-L44)

The `getAddressLines` method is used when retrieving the addresses for display. This event gives you the ability to customise the output. It is a key/value pair array that is iterated over, so the value is what will be output.

Thanks!
