### ISSUE TITLE
GraphQL variant priceAsCurrency/salePriceAsCurrency

### ISSUE THREAD

**Issue by rb1193** [craftcms/commerce#1856]
**What are you trying to do?**
Hi, I'm querying variants via GraphQL. Apologies if this is documented somewhere and I've missed it, but is it possible to get the price/salePriceAsCurrency values?

**What's your proposed solution?**
Either add the priceAsCurrency and salePriceAsCurrency values to the GraphQL type, or implement a currency directive that can be used to format the output

**Comment by nfourtythree** [comment]
Hi @rb1193 

Thanks for the request.

`priceAsCurrency` and `salePriceAsCurrency` have been added to variants GraphQL queries and `defaultPriceAsCurrency` has been added to products queries.

This update will be included in the next release of Commerce.

Thanks!

**Comment by rb1193** [comment]
Wow, that was quick. Thanks very much!
