### ISSUE TITLE
Ability to search orders by name

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#186]
> Created by: Terry Upton ([terry@amasci.co.uk](terry@amasci.co.uk)) on 2017/01/29 00:11:23 +0000
Votes at time of UserVoice import: 14

------
Add the ability to enter part of a billing name on order list screen to filter orders by name.

**Comment by angrybrad** [comment]
> Created by: Jeremy Daalder ([jd@imagescience.com.au](jd@imagescience.com.au)) on 2017/02/19 23:16:32 +0000


------
I can search by billing name (although partial searching doesn&#39;t work very well) (you may need to add the billing name/company as columsn to get this to work).... what&#39;s really missing is searching by :

Shipping method
Shipping name/company/address (billling details work already)
Orders containing particular products

**Comment by angrybrad** [comment]
> Created by: Clive Portman ([clive@cliveportman.co.uk](clive@cliveportman.co.uk)) on 2017/02/20 10:14:19 +0000


------
Search by order short number and ID. I think you can search by order full number already.

**Comment by angrybrad** [comment]
> Created by: Stephan Fischer ([info@fischer-dev.de](info@fischer-dev.de)) on 2017/09/08 10:24:58 +0000


------
I support this, specially searching for shortNumber (or partials of order number)

**Comment by lukeholder** [comment]
This is possible in Commerce 2.0

**Comment by echantigny** [comment]
@lukeholder I am trying to do exactly this, search by Shipping Full Name (which is a column too) and it is not working.  The only customer info that seems to be searched is the email address.  Be aware that this might give false positives because a lot of email addresses contains the person's name.

Could this please be reviewed?

Thank you
