### ISSUE TITLE
Bring back orders index revenue chart

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#1860]
In previous versions of Commerce, there was a nice line chart showing a quick overview of order revenue. I'm aware there are now widgets available on the dashboard, but it provides a bit of a disconnect to the order information.

What was the reason for removing it? A number of our clients miss this chart, and have asked for it back.

**Comment by nfourtythree** [comment]
Hi @engram-design 

As you mentioned Commerce now provides a number of widgets which deal with the statistical side of things. The order index is designed to be used for managing orders and having the chart there meant it was a mix of concerns. There were a number of user's that were saying the opposite that it was taking up a lot of room and in the way based on they would only look at it once a day or so.

Ahead of us implementing/updating the reporting (#42) features in Commerce the dashboard widgets will be a way to see the statistical data. I believe that setting up a useful dashboard for your clients would yield a better overall experience than simply bringing back the old chart.

Thanks!
