### ISSUE TITLE
Multisite order emails - use mailer config rather than reading project config 

### ISSUE THREAD

**Issue by mattsbanner** [craftcms/commerce#1863]
We're running a Craft CMS multisite with Commerce. The shops sell the same products on both sites but under different brand identities. For ordinary site emails (password resets, etc.), we [override the mailer config](https://github.com/craftcms/cms/issues/6025#issuecomment-624096713) to check the site handle and set the correct from name and address.

```php
'mailer' => function() {
    $settings = craft\helpers\App::mailSettings();
    $mailer = Craft::createObject(craft\helpers\App::mailerConfig($settings));

    $siteHandle = Craft::$app->getSites()->getCurrentSite()->handle;

    if ($siteHandle == 'siteTwo') {
        $mailer->from = [
            getenv('EMAIL_SYSTEM_EMAIL_ADDRESS_SITE_TWO') => getenv('EMAIL_SENDER_NAME_SITE_TWO'),
        ];
    } else {
        $mailer->from = [
            getenv('EMAIL_SYSTEM_EMAIL_ADDRESS') => getenv('EMAIL_SENDER_NAME'),
        ];
    }

    return $mailer;
},
```

Unfortunately, the above doesn't work in Commerce as it fetches the email address directly from the config and ignores our custom configuration in `app.php`.

If an alternative email address hasn't been declared in Commerce. The existing mailer object should be used as opposed to reading the config, thus taking any overrides into account.

**Comment by pdaleramirez** [comment]
@mattsbanner There is a way to do this in Commerce by using the event `craft\commerce\services\Emails::EVENT_BEFORE_SEND_MAIL` but to trigger this event you'll have to set the email setting to **Send to custom recipient**
You could test this out
```
            Event::on(
                Emails::class,
                Emails::EVENT_BEFORE_SEND_MAIL,
                function (MailEvent $event) {
                    // @var Message $message
                    $message = $event->craftEmail;
                    // @var Email $email
                    $email = $event->commerceEmail;
    
                    $siteHandle = Craft::$app->getSites()->getCurrentSite()->handle;
    
                    if ($siteHandle == 'siteTwo') {
                        $message->from = [
                            getenv('EMAIL_SYSTEM_EMAIL_ADDRESS_SITE_TWO') => getenv('EMAIL_SENDER_NAME_SITE_TWO'),
                        ];
                    } else {
                        $message->from = [
                            getenv('EMAIL_SYSTEM_EMAIL_ADDRESS') => getenv('EMAIL_SENDER_NAME'),
                        ];
                    }
    
                }
            );
```

**Comment by martinhellwagner** [comment]
@pdaleramirez 

Any idea why this code isn't working for us?

**Comment by nfourtythree** [comment]
Hi @martinhellwagner

I have just tried this locally with the following code and everything works as expected:

```php
Event::on(Emails::class, Emails::EVENT_BEFORE_SEND_MAIL, function(MailEvent $event) {
    $siteHandle = Craft::$app->getSites()->getCurrentSite()->handle;

    if ($siteHandle == 'testing') {
        $event->craftEmail->setFrom(['test@craftcms.com' => 'Testing Name']);
    }
});
```

Hopefully, this will work for you.

Thanks!

**Comment by martinhellwagner** [comment]
@nfourtythree 

Sorry for the confusion – we had another issue in our code. I've deleted my previous comments already. Thanks for taking the time to try it out though – much appreciated! 🙏🏼
