### ISSUE TITLE
Discount User/Email

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#187]
> Created by: Anders ([a@23d.one](a@23d.one)) on 2017/01/25 07:06:33 +0000
Votes at time of UserVoice import: 1

------
I propose simplifying the user/email limits. If you set to, for example 1 per user, and 1 per email, the user overrides the email. This means only a registered and logged in user can apply the discount. Would it not make sense to have a switch for either user or email, seeing as a user should have an email connected to their account.

**Comment by nfourtythree** [comment]
Duplicate of #470
