### ISSUE TITLE
Override Variant url format

### ISSUE THREAD

**Issue by billmn** [craftcms/commerce#1870]
Hey guys, 
for SEO purposes, I have added a custom route for Variants in routes.php file that allow to use an uri format like `/product-1-sku` rather than `/product-1?variant=94`.

The problem is that the Variant's URI format is hardcoded inside the `getUrl` method and I haven't found a way to customize it to reflect the route format.

Does exists a way to do it?

Thank you

**Comment by pdaleramirez** [comment]
@billmn We are working on this, Similar issue (https://github.com/craftcms/commerce/issues/1848)

**Comment by elivz** [comment]
This was closed as "completed", but I don't think this is actually possible still? The `?variant=123` format is still [hardcoded in the Variant element class](https://github.com/craftcms/commerce/blob/853e7d9bde9268c1e1d86a8e30d77ffd1057e6cf/src/elements/Variant.php#L766). I've been trying to figure out a way to override this using a behavior or DI or something for a while, but still haven't managed to come up with a solution.
