### ISSUE TITLE
successMessage and failMessage don't work for JSON requests

### ISSUE THREAD

**Issue by OwenMelbz** [craftcms/commerce#1871]
When you send a hashed `successMessage` or `failMessage` to update the cart, the value does not get used for JSON responses.

The code located: https://github.com/craftcms/commerce/blob/3d31e4c20c5f6f00d83b26c32ee379ff3a436c88/src/controllers/CartController.php#L366

```php
if (($cartUpdatedNotice = $this->request->getParam('cartUpdatedNotice')) !== null) {
    $cartUpdatedMessage = Html::encode($cartUpdatedNotice);
    Craft::$app->getDeprecator()->log('cartUpdatedNotice', 'The `cartUpdatedNotice` param has been deprecated for `carts/*` requests. Use a hashed `successMessage` param instead.');
} else {
    $cartUpdatedMessage = Craft::t('app', 'Cart updated.');
}

if ($request->getAcceptsJson()) {
    return $this->asJson([
        'success' => !$this->_cart->hasErrors(),
        $this->_cartVariable => $this->cartArray($this->_cart),
        'message' => $cartUpdatedMessage,
    ]);
}

$this->setSuccessFlash($cartUpdatedMessage);
```

As the line `$cartUpdatedMessage = Craft::t('app', 'Cart updated.');` sets the variable to "Cart updated"

It then directly references the variable `'message' => $cartUpdatedMessage,` which then passes "Cart updated" back through the response regardless of the value.

When you look inside `$this->setSuccessFlash($cartUpdatedMessage);`

You can see it does the `$message = $this->request->getValidatedBodyParam('successMessage') ?? $default;`

Which would convert the body param into the value you supplied. 

But as this code is never executed you get the hardcoded response for all JSON requests.

Thanks :)

**UPDATE:** I've found the `failMessage` doesn't get validated or converted by either the JSON or text/html responses e.g. the code does rather than setting the flash message.

```php
$error = Craft::t('commerce', 'Unable to update cart.');

if ($request->getAcceptsJson()) {
    return $this->asJson([
        'error' => $error,
        'errors' => $this->_cart->getErrors(),
        'success' => !$this->_cart->hasErrors(),
        'message' => $error,
        $this->_cartVariable => $this->cartArray($this->_cart)
    ]);
}

Craft::$app->getUrlManager()->setRouteParams([
    $this->_cartVariable => $this->_cart
]);

Craft::$app->getSession()->setError($error);
```

**Comment by pdaleramirez** [comment]
Fixed for next release
