### ISSUE TITLE
PDF attachment send with emails are translated

### ISSUE THREAD

**Issue by johnvanhulsen** [craftcms/commerce#1876]
**Description**
I've send the attachment with some emails and the PDF isn't translated and has some other styles with commerceCurrency.

Attachment in mail:
<img width="221" alt="Schermafbeelding 2020-11-16 om 22 16 48" src="https://user-images.githubusercontent.com/2969578/99309276-77ada080-2859-11eb-9c70-ef3c418b5f90.png">

Attachment when download in admin:
<img width="250" alt="Schermafbeelding 2020-11-16 om 22 18 24" src="https://user-images.githubusercontent.com/2969578/99309406-a75ca880-2859-11eb-97ff-90bf145065a0.png">

**To Reproduce**
How, and what happened?
1. Set website language to NL
2. In the CP, add attachment to e-mail in `/commerce/settings/emails`
3. Send mail and check translations and currency in PDF
4. Download PDF from order in admin panel
5. Compare

**Expected behavior**
I've expected the e-mail will respect the settings and translation from the main website.

**Additional info**
- Craft version: Craft Pro 3.5.15.1
- Commerce version: 3.2.11
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5
- Other Plugins & versions: No relevants

**Comment by pdaleramirez** [comment]
@johnvanhulsen Thank you for reporting this issue. There is an existing bug on emails and pdf attachments where it doesn't get the correct site locale if you set you email recipient to custom. But if you set it to customers it should work as expected.

We are working to fix this and adding setting locale option to the email setup. Any update on this goes here https://github.com/craftcms/commerce/issues/1884

**Comment by lukeholder** [comment]
This has been fixed in https://github.com/craftcms/commerce/pull/1895
