### ISSUE TITLE
Added configuration to not make a request related to sales for each variant in the detail of a product

### ISSUE THREAD

**Issue by jlachancekffein** [craftcms/commerce#1883]
**What are you trying to do?**

In the administration panel, when viewing the detail of a product, a request is made for each variant in order to return the related sales.

This causes a problem when there are several variants for a single product.

![Capture d’écran 2020-11-18 à 14 54 51](https://user-images.githubusercontent.com/24896469/99580934-177c4300-29ae-11eb-8cf5-499aa6310f2c.png)

**What's your proposed solution?**
It would be interesting to have a configuration option to display or not this functionality.

For now, in order to work around the problem, I am getting each request to determine if it is a request with request queryParam ('p') === 'admin/actions/commerce/sales/get-sales-by-purchasable-id '.

If so, I directly return a void-type response to prevent sql query.

**Comment by lukeholder** [comment]
This is now fixed in the latest release: 3.2.13
