### ISSUE TITLE
Adding multiple products to the cart with Postman doesn't work on trial pro version

### ISSUE THREAD

**Issue by Stalex89** [craftcms/commerce#1888]
**Description**
Using the API endpoint to update cart with multiple products returns success response,
however the cart is not updated with the new products. I'm using the pro trial version of Craft Commerce.

**To Reproduce**
1. Create the following endpoint in Postman `http://localhost:8080?action=commerce/cart/update-cart&note=from+ajax`
(replace the domain with yours)
method: post,
accept: application/json,
with the following body: 
`{
    "cartUpdatedNotice" : "Multiple products added to the cart.",
    "purchasables[0][id]" : 4,
    "purchasables[0][qty]" : 1,
    "purchasables[1][id]" : 12,
    "purchasables[1][qty]" : 5
}`
(replace the ids with the one you have in your project)

2. Send the request
3. Check the order in the CP

**Expected behavior**
Multiple products added to the cart

**Additional info**
- Craft version: Craft Pro 3.5.15.1
- Commerce version: 3.2.12
- PHP version: 7.3.12
- Database driver & version: MySQL 5.7.28
- Other Plugins & versions: Element API | 2.6.0

**Additional context**
Calling cart update with single product in the payload also doesn't work:
`{
    "cartUpdatedNotice" : "Multiple products added to the cart.",
    "purchasables[0][id]" : 4,
    "purchasables[0][qty]" : 1,
}`

However calling the cart update with that payload works: 
`{
    "cartUpdatedNotice" : "Added product with id 4 to the cart.",
    "purchasableId" : 4,
    "qty" : 10
}`

Screenshots: 

<img width="1410" alt="Screenshot 2020-11-23 at 13 33 50" src="https://user-images.githubusercontent.com/23526237/99962905-3ce3c500-2d91-11eb-806b-02cacaf8e140.png">
<img width="1415" alt="Screenshot 2020-11-23 at 13 37 24" src="https://user-images.githubusercontent.com/23526237/99962938-4d943b00-2d91-11eb-977c-c7bbbcbf213f.png">
<img width="1438" alt="Screenshot 2020-11-23 at 13 34 31" src="https://user-images.githubusercontent.com/23526237/99962955-52f18580-2d91-11eb-9e82-ba1e127f9003.png">
<img width="1424" alt="Screenshot 2020-11-23 at 13 34 47" src="https://user-images.githubusercontent.com/23526237/99962959-54bb4900-2d91-11eb-8bb3-2781925ce298.png">
<img width="1420" alt="Screenshot 2020-11-23 at 13 36 40" src="https://user-images.githubusercontent.com/23526237/99962975-5ab12a00-2d91-11eb-8c50-9c3a695a62a1.png">
<img width="1435" alt="Screenshot 2020-11-23 at 13 36 58" src="https://user-images.githubusercontent.com/23526237/99962990-5e44b100-2d91-11eb-8fcd-e794cc21c2d9.png">
<img width="1423" alt="Screenshot 2020-11-23 at 13 37 42" src="https://user-images.githubusercontent.com/23526237/99963063-7d434300-2d91-11eb-9203-bad7baecd5d9.png">
<img width="1420" alt="Screenshot 2020-11-23 at 13 37 53" src="https://user-images.githubusercontent.com/23526237/99963076-80d6ca00-2d91-11eb-9d78-64a72de9b2fc.png">
<img width="1159" alt="Screenshot 2020-11-23 at 13 41 32" src="https://user-images.githubusercontent.com/23526237/99963136-9e0b9880-2d91-11eb-82c5-59fe9bc0144a.png">

**Comment by Stalex89** [comment]
UPD: ok, I tried to add the body fields directly as request parameters and it worked:
<img width="1416" alt="Screenshot 2020-11-23 at 15 40 42" src="https://user-images.githubusercontent.com/23526237/99975233-46295d80-2da2-11eb-93c7-8e32b777bfa4.png">

However, is it still possible to use JSON body to send data?

**Comment by pdaleramirez** [comment]
@Stalex89 Passing JSON raw data is supported when updating a cart. Your purchasable data format should look something like 
```
    "purchasables": [
        {"id": 4, "qty": 1},
        {"id": 12, "qty": 1}
    ]
```

**Comment by Stalex89** [comment]
@pdaleramirez Thank you for your response, can you please tell me where I can find the documentation for API endpoints of Commerce (I am using the headless Craft, and all the examples in documentation are using twig templates)?

Also, I would like to fetch `craft.commerce.countries.allCountriesAsList`, `craft.commerce.states.allStatesAsList`, `cart.availableShippingMethodOptions` etc., but it gives me 403 error while trying:

<img width="1415" alt="Screenshot 2020-11-24 at 10 17 48" src="https://user-images.githubusercontent.com/23526237/100074261-d1f0c780-2e3e-11eb-94ef-920af9d94e55.png">

Can you please tell me how the request should look like? (Sorry if the questions are pretty obvious, I'm new to the Commerce plugin)
