### ISSUE TITLE
All Product Types index page and Product Type specific index pages

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#189]
> Created by: James L ([james@yellostudio.co.uk](james@yellostudio.co.uk)) on 2016/12/19 16:34:17 +0000
Votes at time of UserVoice import: 1

------
Often many of our ecommerce sites want a /products/ index page which lists all product types available in the system.

The biggest issue is that the productTypes will only have a handle, which would be say, microwaveOvens (doesn't fix the standard convention of URLs).

We have a workaround for the product types index page, which is to query all productTypes, convert the type handle camelCase to a slugified version using a regex, e.g.

{% set typeSlug = type.handle|replace('/([A-Z])+/', '-$1')|lower %}

Then add a route for this, e.g.

    'products/(?P<productType>[a-zA-Z0-9_-]+)' => 'products/_type',

Then in the _type template we can do: 

{% set handle = craft.request.segment(2)|replace('-', '') %}
{% set typeProducts = craft.commerce.products.type(handle) %}

As long as the DB collation is non case sensitive.

I wish there was a better built in solution for this, such as having a configurable options for both (currently non existent) index pages with automatic exposure of data to both pages with potential limit / filter options.

Alternatively allowing the product type to have a 'base' slug would be an acceptable resolution.

**Comment by lukeholder** [comment]
This is not handled by the plugin, this is up to the developer.
