### ISSUE TITLE
'Cart updated.' translation issue

### ISSUE THREAD

**Issue by tom-c** [craftcms/commerce#1893]
**Description**
Translation customised system message for 'Cart updated.' is no longer applying.

**Expected behavior**
I believe line 371 of CartController.php should call the 'commerce' category for translation, rather than 'app'…

**Additional info**
- Craft version: Craft Pro 3.5.15.1
- Commerce version: 3.2.12

**Additional context**
Fixed temporarily by making an 'app.php' translation file and adding it in there.

**Comment by lukeholder** [comment]
Thanks, this was fixed in https://github.com/craftcms/commerce/pull/1880 and will be in the next release!

**Comment by tom-c** [comment]
Sorry, should have searched the repo more thoroughly. Thanks for being on it 👍
