### ISSUE TITLE
Lineitem is always saved in default language?

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/commerce#1897]
**Description**
A lineitem gets saved always in the defaultSite language. When I have an order e-mail with `orderLanguage` something different than the default language, the e-mail gets translated correctly, but the `item.description` remains in the default language. Also `item.snapshot.product.title` and so forth doesn't seem to be properly translated?

When I set a cart as completed via the CP, I actually see the descriptions of the line items change language.

**Expected behavior**
I expect the lineitems to give me the language of the orderLanguage.

**Additional info**
- Craft version: 3.5.16
- Commerce version: 3.2.12
- PHP version: 7.4
- Database driver & version: MySQL 5.7.31

**Comment by pdaleramirez** [comment]
@TomDeSmet There is an existing bug where email is not getting the correct language. We are working a fix and enhancement for this issue. Details here https://github.com/craftcms/commerce/issues/1884
