### ISSUE TITLE
Making specific address fields required

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1899]
It would be useful if we were able to make specific address fields required - so user could not save order when he entered only part of address, without all required fields.

**Comment by nfourtythree** [comment]
Hi @piotrpog 

We purposefully leave this open for the develop to handle using the `Address::EVENT_DEFINE_RULES` event. This is a base mode event for defining rules.

Thanks!

**Comment by piotrpog** [comment]
@nfourtythree 
Thanks for info.
