### ISSUE TITLE
Payment forms templates eg Strip, PayPal etc

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#190]
> Created by: Anonymous ([studio@green17creative.com](studio@green17creative.com)) on 2016/12/09 23:39:38 +0000
Votes at time of UserVoice import: 4

------
It would be great to have some of the core things like cart payment templates forms for eg Strip, PayPal in the demo templates

**Comment by lukeholder** [comment]
In Commerce 2, Gateways now include their `getPaymentFormHtml()` method to return a standard payment form. Thanks @andris-sevcenko
