### ISSUE TITLE
Order edit not showing all purchasable types

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#1902]
In the order edit page, adding a line item only shows the commerce purchasables not any other purchasable types.

Would it be possible to show all purchasable types (via tabs would work) when adding a new line item?

**Comment by pdaleramirez** [comment]
@samuelbirch The query for that **Add a line item table** is that it gets purchasables from the `purchasables` table. It will display all purchasable objects that extends `Purchasable` class. Not sure of the other purchasable types you are referring. Is it extending the Purchasable class?

**Comment by samuelbirch** [comment]
@pdaleramirez you are right. My mistake, i think the search indexes had not updated and therefore the new purchasable types did not show.

It would be handy to have a table column that shows the purchasable/product type though, that would make it easier to see at a glance. Also be good to have the the columns sortable.

**Comment by pdaleramirez** [comment]
@samuelbirch Great, I will close this issue for now and we can another issue for the search table enhancement.
