### ISSUE TITLE
Business ID field not saved during checkout

### ISSUE THREAD

**Issue by tomfischerNL** [craftcms/commerce#1909]
### Description
When following the checkout steps, and filling in the address fields, and Business name, Business ID and business Tax ID, the field Business ID is not saved after continuing to the next step. 

### Steps to reproduce

1. Go to commerce demo template shop (/shop)
2. Add products to cart
3. Continue checkout and fill in the address details, including the Business ID and go to confirm addresses.
4. Go back to the step "addresses" or continue checkout.
5. Business ID field is empty

### Additional info

- Craft version: 3.5.16
- PHP version: 7.3.24
- Database driver & version: MySQL 5.5.5

Thanks in advance ;)

**Comment by nfourtythree** [comment]
Hi @tomfischerNL 

I have just checked this with the latest release of Commerce and using the example templates and the Business ID is saving as expected.

Have you checked the naming of the field? Are you using the `addressLines` property/method to display the address? If so `businessId` is not currently included in that output.

Thanks.

**Comment by tomfischerNL** [comment]
Hi @nfourtythree ,

I downloaded the latest version of Craft Commerce and the demo templates, and still, Business ID stays empty after saving. Business Tax ID is correctly filled but Business ID not. I'm using the demo templates from github.

![Schermafbeelding 2020-12-04 om 12 35 58](https://user-images.githubusercontent.com/2330195/101159176-45f45200-362d-11eb-90e3-83b34654a8eb.png)

**Comment by nfourtythree** [comment]
Hi @tomfischerNL 

Thank you for the extra info and clarification.

We have highlighted the issue and pushed a fix for it which will be included in the next release of Commerce.

Thanks!

**Comment by tomfischerNL** [comment]
Thanks :-) 👍🏼

 

Met vriendelijke groet,

Tom Fischer




Bezoekadres
Het Eeftink 11-22 
7541 WH Enschede

T	+316 24 89 41 19
E	info@wateengoedidee.nl
W	www.wateengoedidee.nl
