### ISSUE TITLE
Ability to dynamically set pricing, discounts and taxes by user group

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#191]
> Created by: Simon ([sbritchford@telus.net](sbritchford@telus.net)) on 2016/12/08 21:43:18 +0000
Votes at time of UserVoice import: 5

------
Tax categories (for example) are product-linked. What I'd like to see is a more flexible approach that allows us to link these and other rates or adjustments based on the type of user logged-in. This would create a  capability unique to commerce where the same product can be priced, taxed and promoted differently to different customers eg: end consumers or retailers.

**Comment by lukeholder** [comment]
Discounts, and Sales have a user and user group condition. When we move to a condition builder we can extend user group permissions to taxes and shipping.

This will be more  in the sales performance refactor as we move to generating a pricing catalog. #1041
