### ISSUE TITLE
sortOrder for order statuses is always set to 99 in project config .yaml file

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/commerce#1911]
**Description**
When you create new order statuses and drag them in the desired order, the .yaml files that get created all contain `sortOrder: 99`, so when it is deployed to a server, they are in alphabetic order instead of the chosen order.

**Additional info**
- Craft version: 3.5.16
- Commerce version: 3.2.12
- PHP version: 7.4
- Database driver & version: MariaDB 10.5

**Comment by pdaleramirez** [comment]
@thijskaspers I couldn't recreate this issue. I am able to sort the order status fine with correct sortOrder in project config. Can you check if your project config is writable locally and your server?
