### ISSUE TITLE
Cart totalQty doesn't update on validation failure

### ISSUE THREAD

**Issue by olivierbon** [craftcms/commerce#1916]
**Description**
If you try to add _x_ quantity of an item to your cart and stock is less than what you want, Commerce will return the correct error, however, `totalQty` would reflect your chosen quantity, not the _reality_.

**To Reproduce**
Using Commerce example templates

1. Add an item to your cart in a quantity > than stock
2. Look at the Cart badge

**Additional info**
- Craft version: latest
- Commerce version: latest

**Comment by pdaleramirez** [comment]
This is happening on the mini cart (upper right corner) of the example template.

**Comment by lukeholder** [comment]
This has been fixed in 3.3.0 - Order notice is now added to the order: https://craftcms.com/docs/commerce/3.x/orders-carts.html#order-notices
