### ISSUE TITLE
Shipping costs specified on a per-item basis

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#192]
> Created by: Cole Henley ([cole@ournameismud.co.uk](cole@ournameismud.co.uk)) on 2016/12/06 16:24:47 +0000
Votes at time of UserVoice import: 2

------
Basically ability to define a shipping cost matrix on a per-product basis and/or an override to … override … specific shipping rules inline

**Comment by lukeholder** [comment]
For small stores where shipping cost is known (no zones are regarded) then it's best to put the shipping cost into the price of the item. Then maybe show the shipping cost in a custom field.
