### ISSUE TITLE
attachPdf migration error

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce#1920]
Updating to 3.2.13 causes the following error when running migrate:

```
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attachPdf' in 'where clause'
The SQL being executed was: SELECT *
FROM `commerce_emails`
WHERE `attachPdf`=TRUE 
```

I can see in the database that this column doesn't exist before the migration takes place. Going from 3.2.12.

**Additional info**

- Craft version: 3.5.16
- Commerce version: 3.2.12
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Other Plugins & versions:

**Comment by lukeholder** [comment]
Can you please send your pre updated DB backup/dump to support@craftcms.com so we can take a look. 

As well as all your logs in `storage/logs`.

That column was previously added but was removed in the `vendor/craftcms/commerce/src/migrations/m200801_233755_pdfs.php` migration.

So it sounds like you had a previous migration failure at one point.

W can try to figure it out with your DB/Logs.

**Comment by bymayo** [comment]
@lukeholder Sent these details over to your email.

**Comment by bymayo** [comment]
Fixed by adding `'backupDbOnUpdate' => false` to `genera.php`.

The migrations failed due to timing out backing up a large database.
