### ISSUE TITLE
Module twig filter not available in email preview

### ISSUE THREAD

**Issue by russback** [craftcms/commerce#1921]
### Description
I have a custom module with twig filters and when using those in an email template, the email preview errors as it's not able to find the filter. Presumably because the module isn't loaded or available at the time that preview is rendered.

### Steps to reproduce

1. Create a custom module with a registered TwigExtension and a filter method called displayPrice()
2. Add a call to that  in the email template, for example `{{ item.price | displayPrice }}`

### Additional info

- Craft version:3.5.16
- Plugins & versions:Commerce 3.2.12 (Pro)

**Comment by lukeholder** [comment]
@russback hmm, it should work.

 Could you share the code for how you are registering your filter? Does your filter work on the front-end of your website on a normal template?

**Comment by russback** [comment]
Sorry @lukeholder I see the issue:

```
if (Craft::$app->getRequest()->getIsSiteRequest())
{
  Craft::$app->getView()->registerTwigExtension(new TwigExtension());
}
```

I was only loading the extension for frontend requests.
