### ISSUE TITLE
Unable to refund transaction - missing required billing information

### ISSUE THREAD

**Issue by jlapan** [craftcms/commerce#1922]
**Description**
I am unable to refund a transaction through the "Transactions" tab in Commerce. I am using Authorize.net as our gateway and am getting an error that billing information as well as email is required. When looking at the order's "Order Details" tab, there is a complete and correct billing and shipping address for the order. The customer also has an email address. Here is the gateway response snapshot:

`{
    "refId": "9329",
    "messages": {
        "resultCode": "Error",
        "message": {
            "code": "E00027",
            "text": "The transaction was unsuccessful."
        }
    },
    "transactionResponse": {
        "responseCode": "3",
        "authCode": [],
        "avsResultCode": "P",
        "cvvResultCode": [],
        "cavvResultCode": [],
        "transId": "0",
        "refTransID": "42393131582",
        "transHash": [],
        "testRequest": "0",
        "accountNumber": "XXXX2452",
        "accountType": "Visa",
        "errors": {
            "error": [
                {
                    "errorCode": "33",
                    "errorText": "Bill To First Name is required."
                },
                {
                    "errorCode": "33",
                    "errorText": "Bill To Last Name is required."
                },
                {
                    "errorCode": "33",
                    "errorText": "Bill To Address is required."
                },
                {
                    "errorCode": "33",
                    "errorText": "Bill To City is required."
                },
                {
                    "errorCode": "33",
                    "errorText": "Bill To State/Province is required."
                },
                {
                    "errorCode": "33",
                    "errorText": "Bill To Zip/Postal Code is required."
                },
                {
                    "errorCode": "33",
                    "errorText": "Email is required."
                }
            ]
        },
        "transHashSha2": "B6EC4F122952F4CD11874AEE00AAE9B89484834EE138F16F061DEDD5A9C926B6FA779D9B82B89A43E854352A3D60366A59277C2105B6DE2B5A50FB34C068A842"
    }
}`

**To Reproduce**
How, and what happened?
1. Open the order to be refunded and navigate to the "Transactions" tab.
2. Enter in the amount to refund and optionally enter a refund note.
3. Click the refund button

**Expected behavior**
Trying to do a full refund through the Commerce "Transactions" tab's "Refund" form.

**Additional info**
- Craft version: Craft Pro 3.5.15.1
- Commerce version: 3.2.12
- PHP version: 7.2.30
- Database driver & version: MySQL 5.5.62
- Other Plugins & versions: Authorize.net for Craft Commerce 1.0.12

**Comment by lukeholder** [comment]
@jlapan Are you using this plugin? https://github.com/digital-pros/commerce-authorize

Might be better to post a support ticket there, since the likely solution would be on that side, and not on Commerce's side.
