### ISSUE TITLE
Assigning custom field elements on  Order Element via property isn't working

### ISSUE THREAD

**Issue by pdaleramirez** [craftcms/commerce#1924]
**Description**
Assigning custom field elements on Order Element via property isn't working

**To Reproduce**
How, and what happened?
E.g.
```
$order = Order::findOne(1);
$order->theUserField = [$user->id];
Craft::$app->getElements()->saveElement($order);
```
**Expected behavior**
What did you expect to happen?
Able to save related elements via property assignment.

**Additional info**
- Commerce version: 3.2.13

In the meantime use setFieldValue ```$order->setFieldValue('theUserField', [$user->id]);```

**Comment by lukeholder** [comment]
In Craft CMS Core is it a requirement to set all custom fields with `setFieldValue`. See docs: https://craftcms.com/docs/3.x/extend/element-types.html#element-content
> When saving values on a custom field, always use the setFieldValue() or setFieldValues() methods rather than directly accessing the field handle as a property on the element object. This ensures the value is normalized and marked as dirty for delta saves.
