### ISSUE TITLE
Add custom line item fields to the json response of get cart request

### ISSUE THREAD

**Issue by Stalex89** [craftcms/commerce#1930]
**What are you trying to do?**
In a cart overview for each line item I want to show an image of product variant for that item; For example I added two variants of product "chair" ("red chair" and "yellow chair"), and I need to show their images in the list of cart line items.

I cannot find a way to add custom fields to line items in the response from getting cart by axios. Fetching fields with twig is not an option, as I'm using the headless mode in Craft and I'm fetching data with axios on decoupled frontend.

**What's your proposed solution?**
It would be nice to have a way to add custom fields to each line item in the response of get cart request

**Comment by pdaleramirez** [comment]
@Stalex89 You can modify the cart response by using the `BaseFrontEndController::EVENT_MODIFY_CART_INFO` event and get all the variant images URL and assign it to an array. In your case. You would code something like this.

```
        Event::on(BaseFrontEndController::class, BaseFrontEndController::EVENT_MODIFY_CART_INFO, function(ModifyCartInfoEvent $event) {
          
            $event->cartInfo['lineItems'] = array_map(function ($value) {
                
                $variant = Plugin::getInstance()->variants->getVariantById($value['purchasableId']);

                $value['images'] = array_map(function ($value) {
                
                    return $value->geturl();
                }, $variant->getFieldValue('localImage')->all());
               
                return $value;
            }, $event->cartInfo['lineItems']);

        });
```
