### ISSUE TITLE
Wrong payment currencies in orders

### ISSUE THREAD

**Issue by palomamtnez** [craftcms/commerce#1936]
Duplicate of issue  #1890  as that was closed. 

The answer from the Commerce Currency Prices development team is stated on that ticket and it is likely that the issue comes from Craft CMS Commerce.

///

**Description**
I have set up multiple payment currencies for craft commerce:
NZD - which is the base currency, AUD, EUR, GBP, JPY, USD.

When I go to Commerce -> Orders -> All orders, the total price of the order is rendered as expected in the grid as shown in the picture:
![image](https://user-images.githubusercontent.com/13962572/100149623-5b69cd80-2f03-11eb-9df3-6955ec0840bd.png)

But when I click on the order, the order summary always shows in NZD even if it was paid for in another currency:
![image](https://user-images.githubusercontent.com/13962572/100149671-6d4b7080-2f03-11eb-8f57-a5e38342fd71.png)

I'm not sure if this is a bug or I am missing something.

**Expected behavior**
To have the order summary in the currency the order was paid in.

**Additional info**
- Craft version:  Pro 3.5.14
- Commerce version:
- PHP version: 7.3.19
- Database driver & version: MySQL 5.6.48
- Other Plugins & versions:

Abandoned Cart for Craft Commerce  1.5.3
Asset Rev  6.0.2
Cloudflare 0.5.1
Colorit 1.0.9.3
Commerce Currency Prices  2.6.4
Craft Commerce  3.1.9
Element API 2.6.0
Embedded Assets 2.2.6
Facebook Product Catalog  1.2.0
Freeform	3.6.12
Google Shopping Feed  1.2.1
Imager	v2.4.0
Image Resizer	2.0.9
Instant Analytics	1.1.7
HTTP2 Server Push  1.0.1
Mailgun	1.4.3
Matrix Toolbar	 1.0.6
Navigation	1.3.20
Neo	2.7.19
PayPal for Craft Commerce	2.1.0.1
Redactor	2.6.1
Retour	3.1.39
SEO	3.3.8
Stripe for Craft Commerce	2.3.1.1
Typed link field	1.0.23

**Comment by pdaleramirez** [comment]
I re-opened the original issue
