### ISSUE TITLE
Edit Orders

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#194]
> Created by: James Jacoby ([james@mobyinc.com](james@mobyinc.com)) on 2016/11/30 19:19:24 +0000
Votes at time of UserVoice import: 29

------
Add ability to add/edit/remove line items, including adjustment of prices, qty, variant. Less important, but nice would be ability to override override adjustments and/or order total.

**Comment by lukeholder** [comment]
Duplicate #45
