### ISSUE TITLE
Entering non numeric price value shows internal server error instead of validation message

### ISSUE THREAD

**Issue by gijsstegehuis** [craftcms/commerce#1942]
**Description**
Entering non numeric price value shows internal server error instead of a decent validation message.

**To Reproduce**
1. In the CP add a new product
2. Enter a non numeric value in the product's price field. E.g. `€8`
3. Save it
4. Shows an internal server error message

**Expected behavior**
To not be able to enter a non numeric value or get a decent error message.

**Additional info**
- Craft version: 3.5.17.1
- Commerce version: 3.2.13.2
- PHP version: 7.4.13
- Database driver & version: PostgreSQL 12.1
- Other Plugins & versions: -

**Comment by lukeholder** [comment]
Fixed in #1944
