### ISSUE TITLE
Invalid discounts prevent any changes to cart

### ISSUE THREAD

**Issue by gavinplatt** [craftcms/commerce#1945]
**Description**

Not certain if this is a bug or intended behaviour. If it's intended behaviour then I'd be interested to learn how others are dealing with this scenario.

**To Reproduce**

1. Create a discount coupon code
2. Add a relevant item to cart, apply the discount code
3. Delete or disable the discount, or set its expiry date to the past
4. Try make any change to the cart created in (2) – e.g. add an item, delete existing item. It's not possible.

If doing step (4) via the CP, an error message `The order is not valid: invalid coupon code` is displayed. If doing step 4 on the frontend, we could display a similar message to the user.  

**Expected behavior**

I would expect users to still be able to make changes to their cart even when a discount code is not valid – in particular adding a new item. I would expect the discount valid check to occur when proceeding to checkout. 

**Additional info**

- Craft version: 3.5.17.1
- Commerce version: 3.2.13.2
- PHP version: 7.1.33
- Database driver & version: MySQL 5.5.5

**Comment by gavinplatt** [comment]
I've noticed the tags change on this – so to confirm, this is expected correct behaviour, for the time being?

**Comment by lukeholder** [comment]
Craft 3.3 will have a new `order.notices` variable to show customers what changed/issues with an order that are not classed as validations errors. We will then move the coupon validation to being a notice only, allow you to update the order. Keep an eye out as 3.3 will be out in the next couple weeks.

**Comment by lukeholder** [comment]
3.3 is out with this feature. Thanks!
