### ISSUE TITLE
Email Service Integrations

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#195]
> Created by: Katrin Kerber ([katrinkerber@gmail.com](katrinkerber@gmail.com)) on 2016/11/09 12:17:10 +0000
Votes at time of UserVoice import: 9

------
It would be great to have first party integrations/plugins for popular email marketing services, such as MailChimp and Campaign Monitor, so that customers and their details can be added to lists when they check out.

The way the Shopify MailChimp integration is set up is very good, as it passes on quite a lot of data by which list managers can then segment/group their subscribers.

**Comment by lukeholder** [comment]
This can be done with a plugin.
