### ISSUE TITLE
Multiple controllers should use `setSuccessFlash()` for consistency.

### ISSUE THREAD

**Issue by mattstein** [craftcms/commerce#1955]
**Description**

Unlike most of Commerce’s site-facing controller actions, the following do not set a success flash notice for successful, non-JSON responses. Each _does_ set a failure flash message, however:

- [x] PaymentSourcesController::actionAdd()
- [x] PaymentsController::actionPay()
- [x] PaymentsController::actionCompletePayment()

**Expected behavior**

Ideally each would conform with other controller responses in implementing `$this->setSuccessFlash()`.

**Comment by nfourtythree** [comment]
Updated `setSuccessFlash` to `PaymentSourcesController::actionAdd()` 200b3dbea71ae1fad9649305859e642ff8dbb2f9

**Comment by nfourtythree** [comment]
@mattstein due to the fact that `pay` and `completePayment` both redirect to a specific "success" page where people have full control over what they want to show it is not required to use `setSuccessFlash`. Also, this prevents any issues with consistency across gateways.
