### ISSUE TITLE
Gateway settings not being affected by Commerce's gatewaySettings config setting

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/commerce#1957]
**Description**
I'm configuring gateway settings using Commerce's `config/commerce.php` file, but the gateway's settings aren't being overridden. 

Other settings (other than gateway settings) are being overridden and I'm seeing the expected notice e.g. "This is being overridden by the dimensionUnits config setting in config/commerce.php."

Is the gatewaySettings config setting still the recommended way of doing this? I'm mainly coming from Commerce 1.

**To Reproduce**

In the CP create a gateway with the handle 'paypal'. 

My gateway is using the [PayPal Checkout](https://plugins.craftcms.com/commerce-paypal-checkout) plugin so has a testMode setting.

Basic config example:
````
<?php
return [
    '*' => [
        'dimensionUnits' => 'cm',
        'gatewaySettings' => [
            'paypal' => [
                'testMode' => true,
            ],
        ]
    ],
];
````

**Expected behavior**
I expected the gateway with the handle 'paypal' to have it's `testMode` setting to be overridden and set true. 

**Additional info**
- Craft version: Craft Pro 3.5.17.1
- Commerce version: 3.2.13.2
- PHP version: 7.3.21
- Database driver & version: MySQL 5.7.30

**Comment by jamiepittock** [comment]
I've just come across [Gateway Configuration](https://craftcms.com/docs/commerce/3.x/gateway-config.html).

The [Configuring Commerce](https://craftcms.com/docs/commerce/3.x/configuration.html) and/or [Config Settings](https://craftcms.com/docs/commerce/3.x/config-settings.html#payments) pages could really do with being updated.

**Comment by nfourtythree** [comment]
Hi @jamiepittock 

Thank you for mentioning this, we will take a review on the docs and see if there are improvements we can make.

It is also worth noting that gateways are normal plugins, which means you can create a config file for them in your config folder. In your case, it would be `commerce-paypal-checkout.php`.

Hope this helps, thanks!

**Comment by jamiepittock** [comment]
Thanks @nfourtythree. It's not just the docs that need improvement though, unless they're just wrong. I think my original issue stands. The Commerce `gatewaySettings` config option doesn't seem to have any effect.

> It is also worth noting that gateways are normal plugins, which means you can create a config file for them in your config folder. In your case, it would be commerce-paypal-checkout.php.

I did try that already and again couldn't get it to have any affect on by gateway settings.

**Comment by nfourtythree** [comment]
Hi @jamiepittock 

We are looking to make configuration around gateway settings more straightforward in future versions, part of that is in #1963

As for:

> I did try that already and again couldn't get it to have any affect on by gateway settings.

Please file any issue over on the https://github.com/craftcms/commerce-paypal-checkout repo with steps on how to reproduce the issue. This way we can take a look into what is happening and hopefully get things resolved.

Thanks!
