### ISSUE TITLE
Error from purgeOrphanedCustomers command

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#1958]
**Description**
I am getting this error in our logs
```
yii\db\Exception SQLSTATE[HY000]: General error: 1093 You can't specify target table 'commerce_customers' for update in FROM clause
The SQL being executed was: DELETE FROM `commerce_customers` WHERE `id` IN (SELECT `customers`.`id` AS `id`
FROM `commerce_customers` `customers`
LEFT JOIN `commerce_orders` `orders` ON `customers`.`id` = `orders`.`customerId`
WHERE (`orders`.`customerId` IS NULL) AND (`customers`.`userId` IS NULL)) 
```

It seems to originate from this command `craft\commerce\services\Customers::purgeOrphanedCustomers`

```
// This will also remove all addresses related to the customer.
--
  | Craft::$app->getDb()->createCommand()
  | ->delete(Table::CUSTOMERS, ['id' => $customers])
  | ->execute();
  | }

```

I do have the table `commerce_customers` in my database, so not sure why that is occurring.

**To Reproduce**
How, and what happened?

It seems to occur on it's own, as part of a daily maintenance task

**Additional info**
- Craft version: Craft Pro 3.5.16
- Commerce version: 3.2.13.1
- PHP version: 7.4.9
- Database driver & version: MySQL 8.0.19
- Other Plugins & versions:

Thank You

**Comment by nfourtythree** [comment]
Thank you for bringing this to our attention.

We have just released version `3.2.14` which has a fix for this included.

Thanks!
