### ISSUE TITLE
Optional decimals in prices

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#196]
> Created by: Øyvind Østmo ([oyvind@redrabbits.com](oyvind@redrabbits.com)) on 2016/11/08 13:55:31 +0000
Votes at time of UserVoice import: 5

------
In Norway it doesn’t make sense to have decimals in prices, and applying % discounts leaves us with decimals more often than not. Would be awesome with a setting for it or something.

Example: 
399 product at 30% discount

NOK 279,3 = ugly
NOK 279 = pretty

In the cases with XX9 NOK being the typical pricing, a % discount often leaves the price at XX9,8 for example. So preferably to keep the 9 ending, I would just loose the decimals without rounding, or always round down.

**Comment by lukeholder** [comment]
This will be handled under #695
