### ISSUE TITLE
Deprecate `Gateways::getGatewayOverrides`, remove in future version.

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#1963]
**What are you trying to do?**
Clean up the idea and process around how to override/configure gateway settings.

Move away from the `commerce-gateways.php` config file in favour of using each gateway plugin's own config file. This is better consistency with how all plugins work and avoids confusion.

- [x] Deprecate the usage of `Gateways::getGatewayOverrides()` (in 3.3)
- [x] Remove `Gateways::getGatewayOverrides()` (next breaking version)

**Comment by nfourtythree** [comment]
This has been done in the upcoming `3.3` release.

**Comment by boboldehampsink** [comment]
Can you give me an example on how to use this now?

commerce-gateways.php
```
<?php

return [
    'dummy' => [
        'isFrontendEnabled' => getenv('GATEWAY_HANDLE') === 'dummy',
    ],
];

```

**Comment by nfourtythree** [comment]
Hi @boboldehampsink 

I believe I have answered your question here: https://github.com/craftcms/commerce/issues/2101#issuecomment-825509174

Thanks!
