### ISSUE TITLE
EVENT_AFTER_REMOVE_LINE_ITEM not triggered when removing line items via the CP?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1966]
**Description**
`EVENT_AFTER_REMOVE_LINE_ITEM` does not appear to be triggered when removing line items via the CP.

Having had a little dig around the code, there is the `EVENT_AFTER_APPLY_REMOVE_LINE_ITEM` which I assume is triggered when the order is subsequently saved and a line item was removed? Although it's not 100% clear as the docs for both `EVENT_AFTER_REMOVE_LINE_ITEM` and `EVENT_AFTER_APPLY_REMOVE_LINE_ITEM` are the same.

Either way I can't get the `EVENT_AFTER_REMOVE_LINE_ITEM` to trigger when removing via the CP, although it works when removing a line item via the controller, by passing the remove param (as outlined in the docs):

`lineItems[LINEITEMID][remove]:  1`

Sorry if I am missing something?

**Expected behavior**
Event triggered in both scenarios.

**Additional info**
- Craft version: 3.5.17.1
- Commerce version: 3.2.14

**Comment by pdaleramirez** [comment]
@samhibberd 
`EVENT_AFTER_REMOVE_LINE_ITEM ` only gets triggered for non completed orders. I've marked this as enhancement to make this a feature that will be added in future releases.

**Comment by samhibberd** [comment]
Hi @pdaleramirez, thanks for the additional detail. 

For me it, on non complete orders, it still doesn’t appear to trigger when removing items in the cp.

**Comment by pdaleramirez** [comment]
@samhibberd  `EVENT_AFTER_REMOVE_LINE_ITEM` is only trigged on the cart. It is part of the recalculation. It would be ideal to another event for this.

**Comment by lukeholder** [comment]
@samhibberd What are you wanting to do when it is removed (in memory) from the CP editor? Wouldn't you rather know when it was really removed with `EVENT_AFTER_APPLY_REMOVE_LINE_ITEM`?

**Comment by samhibberd** [comment]
@lukeholder what you said, yes. I think the naming (and me not properly reviewing the code / docs) caused a little confusion here.

**Comment by lukeholder** [comment]
No worries, will update the docs for the events.

Thanks.

**Comment by samhibberd** [comment]
Perfect, just some clarity into the difference between these two events, docs are massively improved since the team updated them so big 👍 there!! No mean feat.

https://craftcms.com/docs/commerce/3.x/extend/events.html#afterremovelineitemtoorder
https://craftcms.com/docs/commerce/3.x/extend/events.html#afterapplyremovelineitemfromorder
