### ISSUE TITLE
Allow Email to be rendered from field or a template path

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1968]
Right now we can set path for Twig file, but it would be useful if we could paste Twig code directly into panel.

**Comment by lukeholder** [comment]
@piotrpog What benefit are you looking for with this request? Only admins have access to edit emails, and email settings are stored in the project config, so the person editing the email would have the ability to edit the templates?

**Comment by piotrpog** [comment]
@lukeholder 
Freeform plugin allows admin to use both file based and control panel based message template.. So my client asked if it would be possible to have functionality of editing contents of emails that commerce uses, just like he can edit these sent by freeform.

**Comment by lukeholder** [comment]
Recommend making a single or global with content fields to be used by your customer to customize the contents of emails. Your email template would use those content variables.

Having said that, we are keeping this request open as a feature request: https://github.com/craftcms/commerce/issues/1967
