### ISSUE TITLE
Deleting customer's saved address affects past orders

### ISSUE THREAD

**Issue by modelesque** [craftcms/commerce#1973]
**Description**
If I delete a customer's saved address, it removes it from any past order was using it as the billing or shipping address.

**To Reproduce**
1. Complete some orders.
2. Go to the customer's user account under the "Customer's Info" tab
3. Delete an address that was used for some orders.
4. Check those orders and see the addresses completely gone.

It should be noted that I have created a customer account area with a page for them to manage these addresses (add/edit/delete). Editing or deleting them dynamically affects any order they were used in. I used the `commerce/customer-addresses/delete` controller action to delete the address in the customer account.

**Expected behavior**
Is this expected behavior?? If so, how are customers supposed to manage their saved saved passwords without it affecting any past completed orders?

I would expect that once an order is completed, data like the billing and shipping addresses stay unless you change it from the order itself. But removing it from the customer's account completely (and without clear warning) removes it from any order that address was connected to. Why isn't there some sort of snapshot for address info on orders?

**Additional info**
- Craft version: 3.5.17.1
- Commerce version: 3.2.13.2 (Pro)
- PHP version: 7.3.x
- Database driver & version: mysql

**Comment by nfourtythree** [comment]
Hi @modelesque 

I have just tried to reproduce this issue and am unable to replicate your scenario. When an order is completed the addresses are duplicated and those new addresses are linked only to the order, this is done to stop what you mentioned from happening.

Here is a video of my experience:

https://user-images.githubusercontent.com/266453/105465344-b3fee200-5c8a-11eb-98d6-28e0a7c3694e.mp4

As you can see deleting the customer's addresses had no impact on the completed order.

You mentioned about using the `commerce/customer-addresses/delete` action, are you sue the correct address IDs are being passed?

Thanks.

**Comment by modelesque** [comment]
@nfourtythree:

> You mentioned about using the `commerce/customer-addresses/delete` action, are you sue the correct address IDs are being passed?

Yes 100%, they are being pulled from the address model in a loop.

**Comment by nfourtythree** [comment]
Hi @modelesque 

As mentioned before I am unable to replicate the issue you are seeing. Do you have any custom code running? Can you get the same behaviour with a fresh install of Commerce and the example templates?

You mentioned the "address model in a loop" do you have an example of that template?

Thanks
