### ISSUE TITLE
Add a total of items without shipping costs

### ISSUE THREAD

**Issue by Stalex89** [craftcms/commerce#1975]
**What are you trying to do?**
On my checkout design, I need to show the subtotal, tax and total of items separately excluding shipping costs. Currently it shows subtotal of items, but tax and a total are already include shipping costs.

**What's your proposed solution?**
Please add the following to the cart response:
1) total of items (number and "as currency") without including the shipping costs
2) item tax (number and "as currency") without including the shipping costs
3) shipping tax (number and "as currency")
4) shipping total cost (number and "as currency")

In my case it should be like that: 
ItemsSubtotalAsCurrency : "€624.00",
ItemsTaxAsCurrency (21%): "€131.04",
ItemsTotalAsCurrency: "€755.04",

ShippingCostAsCurrency: "€19.95",
ShippingCostTaxAsCurrency (21%): "€4.19",
ShippingCostTotalAsCurrency": "€24.14",

TotalAsCurrency: "€779.18"

**Additional context**
<img width="1229" alt="Screenshot 2021-01-25 at 11 05 49" src="https://user-images.githubusercontent.com/23526237/105691271-50c8b600-5efd-11eb-8eb4-af3c6124df37.png">

**Comment by rjanits** [comment]
@Stalex89 How can I achieve something like that?
We need to charge 20% Tax on Shipping Costs too.
