### ISSUE TITLE
Product page shows inconsistent behaviour when showing sales that are dependent on other factors

### ISSUE THREAD

**Issue by nilutz** [craftcms/commerce#1976]
**Description**
The product page shows inconsistent behaviour when showing sales that are dependent on other factors. Read further to understand what I mean.

**To Reproduce**
Imagine you have a range of products and want to generate sales on some of them. You create a sale/promotion and add some products/purchables to it.
![Screenshot 2021-01-26 at 09 27 50](https://user-images.githubusercontent.com/15090546/105819774-ea08d280-5fb8-11eb-85df-f6a7dbcd8147.png)
Later you decide to add a more restrictions to that sale, by applying also a categories to the sale.
![Screenshot 2021-01-26 at 09 28 13](https://user-images.githubusercontent.com/15090546/105819804-f5f49480-5fb8-11eb-9e1f-fc8873af21fa.png)

The problem is the following: While Product A has Category A and Product B has **not** Category A both appear in the product page to belong to that product.
![Screenshot 2021-01-26 at 09 32 08](https://user-images.githubusercontent.com/15090546/105820112-68657480-5fb9-11eb-8ff9-b1f137da49c9.png)
That being said, the sale behaviour/calculations are in order, so the sale applies only to Product A. Nonetheless we found it very confusing that both products appear to have that sale. Of course you could argue that Product B is still part of that sale, but our client found it very confusing when he noticed that the sale didn't apply even though it said so.

**Expected behavior**
Maybe redo the query and dont't show that this product is part of the sale or show that sale sign in a faded grey to indicate that it's inactive ?

**Additional info**
- Craft version: Craft Pro 3.5.15.1
- Commerce version: 3.2.11
- PHP version: 7.1.33
- Database driver & version: PostgreSQL 12.2

**Comment by pdaleramirez** [comment]
@nilutz I would suggest to use the event `Sales::EVENT_BEFORE_MATCH_PURCHASABLE_SALE` this will customize your sale based on you specification.  
Your code would look something like this 

```
     use craft\commerce\events\SaleMatchEvent;
     use craft\commerce\services\Sales;
     use yii\base\Event;

       Event::on(
            Sales::class,
            Sales::EVENT_BEFORE_MATCH_PURCHASABLE_SALE,
            function (SaleMatchEvent $event) {
                if ($event->purchasable->getProduct()->productCategory->one()->slug == 'product-a') {
                    $event->sale->applyAmount = -10;
                }
            }
        );
```

**Comment by nilutz** [comment]
Hi,
Thanks for the support. The actual calculation of the sale works as expected. The problem is that the product page indicates/shows that a product is part of sale while not being processed (as it should be). Nonetheless we find it confusing to show that a product is part of sale:
![Screenshot 2021-01-26 at 09 32 08](https://user-images.githubusercontent.com/15090546/105820112-68657480-5fb9-11eb-8ff9-b1f137da49c9.png)
