### ISSUE TITLE
Unable to enter product dimensions after Craft 3.6 update

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1977]
**Description**

We are unable to enter (or even see) our product dimensions, after our recent update to Craft 3.6.  Can click in fields, but they do not display the current values or accept a value:

![image](https://user-images.githubusercontent.com/731309/106086798-f2a70780-6176-11eb-8de4-0ea19c02f3b0.png)

**Additional info**

![image](https://user-images.githubusercontent.com/731309/106086913-19653e00-6177-11eb-8872-2976097d91ff.png)

**Comment by lukeholder** [comment]
Working on a fix now.

**Comment by nfourtythree** [comment]
Hi @bossanova808 

Thank you for bringing this to our attention. We have pushed a fix for this which will be included in the next Commerce release.

Thanks!

**Comment by bossanova808** [comment]
Great thanks - any hints as to when this release is coming (we have some new products we can't add...)?

I can't tell if the other commits lately are dangerous or not, I could just pull in up to those commit of course, if you think that is safe enough, but happy to wait if a release is fairly imminent...

Thanks again and hope you're all well, JD

**Comment by lukeholder** [comment]
@bossanova808 3.2.14.1 is out now.
