### ISSUE TITLE
Product titles are not auto-regenerated when making a change to Product Title Format inside Product Types in the Commerce settings.

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce#1979]
**Description**
Product titles are not auto-regenerated when making a change to Product Title Format inside Product Types in the Commerce settings.

**To Reproduce**
How, and what happened?
1. `Go to Commerce > Product Types` then make a change to the Product Title Format
<img width="1626" alt="Screenshot 2021-01-28 at 12 38 21" src="https://user-images.githubusercontent.com/5698596/106139760-bf0fb180-6165-11eb-9883-f04c4cfe37fc.png">

2. Click Save

**Expected behavior**
What did you expect to happen?
1. I expected the product titles to be auto-regenerated based on the new change.

**Actual behavior**
Nothing is updated atomically. However, if I manually re-save a product the title is updated. 

**Additional info**
- Craft version: Craft Pro 3.5.18
- Commerce version: 3.2.14
- PHP version: 7.4.13

**Additional context**

**Comment by lukeholder** [comment]
Hi, thanks for reporting this. Updated for the next release.
