### ISSUE TITLE
Are you able to create product combos? e.g. Axe, Axe sharpener, or Axe + Sharpener combo

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#198]
> Created by: Anonymous ([someone@gmail.com](someone@gmail.com)) on 2016/10/19 21:08:38 +0000
Votes at time of UserVoice import: 3

------
Are you able to create product combos? e.g. Axe, Axe sharpener, or Axe + Sharpener combo

**Comment by bossanova808** [comment]
Just commenting to follow a long here.

Combos would be very handy.

**Comment by lukeholder** [comment]
See discussion on #260
