### ISSUE TITLE
Searches with the word "plus" have no results

### ISSUE THREAD

**Issue by bitboxfw** [craftcms/commerce#1980]
**Description**
We have a few products with the word "plus" in the title. Now, for example, if you search for the word "plus" in the control panel, no products are found. The same thing happens when you do a search in Twig or PHP.

**To Reproduce**
1. Create a new product with the title "RollerMouse Red Plus"
2. Search for "plus" in the control panel (without quotation marks)
3. Only if you type "RollerMouse Red Plus" or "red plus" (with quotation marks) the product will be found

**Additional info**
- Craft version: 3.5.18
- Commerce version: 3.2.14
- PHP version: 7.4.14
- Database driver & version: MySQL 5.7.32
- Other Plugins & versions:

Beam	2.1.5
CP Clear Cache	1.1.0
Dumper	2.0.0
Error Notifier	1.0.4
Freeform	3.10.3
Klarna Checkout for Craft Commerce	3.0.1
Minifier	2.0.5
PayPal Checkout for Craft Commerce	1.2.0
Redactor	2.8.5
ReOrder	1.1.5
Socializer	1.2.0
Translator	1.1.2

**Comment by angrybrad** [comment]
@bitboxfw you're running into the same issue and workaround(s) as https://github.com/craftcms/cms/issues/7248#issuecomment-742946846
