### ISSUE TITLE
Flat amount discount applied to last line item instead of order

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1982]
**Description**
Discounts with a flat amount discount are applying the flat amount to the last line item in the order, rather than applying the adjustment to the order itself.

**To Reproduce**
1. From the CP order edit page, apply a discount code that applies a flat discount amount to the order and recalculate order.
2. Flat amount is deducted from last line item in order and listed with its details.

**Expected behavior**
Expected the flat discount amount to be applied as a discount adjustment to the order and listed down at the bottom with order-level tax amounts.

**Additional info**
- Craft version: Pro 3.5.18
- Commerce version: Pro 3.2.14
- PHP version: 7.4.4
- Database driver & version: MySQL 5.5.5

**Comment by pdaleramirez** [comment]
@jmauzyk This is actually the indented behavior when you apply "Flat Order Discount Amount Off" action. The description states _"This amount is spread across line items in order of highest price to lowest price, until the discount is used up."_ 
![e105a41f-d4b6-4c53-8f1b-1e00f0a5e827](https://user-images.githubusercontent.com/4172750/106846807-8c773300-66e8-11eb-98e6-f7e90e6fffe0.jpg)

**Comment by jmauzyk** [comment]
@pdaleramirez Sorry, completely overlooked that part of the instructions. As the German saying goes, "Those who can read have a clear advantage."
