### ISSUE TITLE
Sending order processing email gives session_set_cookie_params error

### ISSUE THREAD

**Issue by payello** [craftcms/commerce#1984]
**Description**
Describe what the problem is.

When the order processing email is being fired we get the following error - `Email template parse error for email “Processing”. Order: “f35123c”. Template error: “An exception has been thrown during the rendering of a template ("session_set_cookie_params(): Cannot change session cookie parameters when headers already sent").” /apps/NAME/templates/_emails/components/order.twig:1 ` Email is stuck in the queue

Using an email template (tested in the browser and manually sends in the admin commerce section). We have set up here - admin/commerce/settings/emails

**To Reproduce**
How, and what happened?
1. Complete the order and hit confirm
2. 

**Expected behavior**
What did you expect to happen?
would expect to receive the confirmation email 

**Additional info**
- Craft version:  3.6.3 (just updated to this locally but staging is Craft Pro 3.5.17.1) 
- Commerce version: 3.2.14
- PHP version: 7.3.9
- Database driver & version: MySQL -5.7.33
- Other Plugins & versions: 

**Additional context**

**Comment by payello** [comment]
As an update to this, later on, the emails for the orders all sent at once. Presumably due to a queue clearing. In the general.php file `runQueueAutomatically` is set to `1`

**Comment by lukeholder** [comment]
Hmmm my guess is that you have reference to the current user or session or cookies in your email/PDF templates with twig. 

You can not access the session from those templates. As the session is not there when running the queue. 

Let us know.

**Comment by stenvdb** [comment]
Came across this issue because I got the same error during an email myself. For me it was the following code snippet that accidentally got in the pdf template that caused it:

```
{% if cart is not defined %}
  {% set cart = craft.commerce.carts.cart %}
{% endif %}
```
