### ISSUE TITLE
PHP 8 Error when viewing profile in CMS

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/commerce#1987]
**Description**
I get an [error screen](https://www.screencast.com/t/jV5HLNzfE) when trying to view my profile

**To Reproduce**
How, and what happened?
1. Navigated to my own profile in the CMs

**Expected behavior**
What did you expect to happen?
View & edit profile

**Additional info**
- Craft version: Craft Pro 3.6.3
- Commerce version: 3.2.14.1
- PHP version: 8.0.1
- Database driver & version: MySQL 8

**Additional context**
[Error](https://www.screencast.com/t/kMeWEdHqYaVQ)
[Fix](https://www.screencast.com/t/XO41oXLi) - remove `&$key` it's not being used anyway

**Comment by nfourtythree** [comment]
Hi @mattcdavis1 

Thank you for bringing this to our attention. We have pushed a fix that will be included in the upcoming `3.3` release.

Thanks!
