### ISSUE TITLE
Add gatewayHandle property to order model

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#1988]
Right now, we have only `gatewayId`. But shipping methods have both `shippingMethodId` and `shippingMethodHandle`.

**Comment by lukeholder** [comment]
We only support gateway that have an ID, whereas dynamic shipping methods that are provided by 3rd party plugins only have a handle, and are not listed in our database.

shippingMethodId will be removed from orders in Commerce 4:

https://github.com/craftcms/commerce/blob/develop/src/services/Orders.php#L196

**Comment by lukeholder** [comment]
If you need to get the handle do `order.gateway.id`
