### ISSUE TITLE
ShippingRule->matchOrder() returns true for a basket with no shippable items.

### ISSUE THREAD

**Issue by mikeymeister** [craftcms/commerce#1990]
**Description**
I have a cart which contains only purchasables that are not shippable (in this case digital products). Our checkout process checks using each shipping rule's `->matchOrder()` function to determine whether to request shipping addresses from the customer. This function returns true for a cart of unshippable items. 

There is a check on line 237 of the ShippingRule model to see if the order has any shippable items, that continues to further checks even with no shippable items but I would have thought if there was nothing to ship the function would return false at this point?

**To Reproduce**
How, and what happened?
1. Create a cart of purchasables which return false for `$purchasable->getIsShippable()`
2. Loop through the available shipping methods and rules and call each rule's matchOrder function.

**Expected behavior**
I would expect a cart with nothing that can be shipped to not match any shipping rules. Perhaps I've misunderstood the purpose of the match order function or missed a setting in the shipping rule?

**Additional info**
- Craft version: Craft Pro 3.6.2
- Commerce version: 3.2.14.1
- PHP version: 7.3.14
- Digital Products version: 2.4.1
- Database driver & version:
- Other Plugins & versions:

**Comment by lukeholder** [comment]
Thanks for reporting this. It has been fixed for the next release in add1e2de6aff1382a3421322ba354aafb45c849c
