### ISSUE TITLE
Currency error in orders

### ISSUE THREAD

**Issue by palomamtnez** [craftcms/commerce#1992]
**Description**
1. The main currency is set up as NZD, however, the grid shows orders that were paid in USD showing without the currency code. 

2. Shipping is displaying in NZD when the order was paid in a different currency.

Examples
1.

![Screen Shot 2021-02-10 at 10 25 39 AM](https://user-images.githubusercontent.com/13962572/107435803-82927b80-6b91-11eb-9f1a-03d4da3badf4.png)

![Screen Shot 2021-02-10 at 10 25 19 AM](https://user-images.githubusercontent.com/13962572/107435762-760e2300-6b91-11eb-873b-6e9eb58bf833.png)

2.
![Screen Shot 2021-02-10 at 10 24 50 AM](https://user-images.githubusercontent.com/13962572/107436534-87a3fa80-6b92-11eb-92f6-4225e3d361b2.png)

**To Reproduce**
How, and what happened?
As screenshots

**Expected behavior**
1. Show all orders in the grid with their respective currency codes.
2. Show shipping with their respective currency code. 

**Additional info**
- Craft version: 3.5.16
- Commerce version: 3.2.14
- PHP version: 7.3.26
- Database driver & version: MySQL 5.7.33
- Other Plugins & versions:

Commerce Currency Prices: 2.7.1
Stripe for Craft Commerce: 2.3.2.1
PayPal for Craft Commerce: 2.1.0.1

**Comment by pdaleramirez** [comment]
@palomamtnez If the customer paid on a currency other than base currency, It is only displayed on the transaction tab in order edit page. Displaying the total amount paid using the selected currency in payment amount column. I would suggest to submit this issue on the third party plugin `Commerce Currency Prices`.
