### ISSUE TITLE
Allow dynamic overriding/setting of a Variant's getIsShippable() method

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/commerce#1993]
Is it possible to allow dynamic overriding of a Variant's `isShippable` method?

Our products and variants can be physical (shippable), digital, and sometimes a combination of both. I know we could use the Digital Products plugin, or roll our own Purchasables, but that doesn't give the best AX or fit with our content model.

We also know we can use other ways of marking a product/variant as shippable or not - shipping categories or custom fields, for example. But the `isShippable(`) method is baked into the out-of-the-box shipping rules and adjuster and again, we'd rather not have to roll our own.

**Comment by pdaleramirez** [comment]
@jamiepittock There is no way to dynamically change the isShippable behavior of a purchasable on latest version. This would be a feature enhancement, some kind of bundling a physical and digital product.

**Comment by nfourtythree** [comment]
Hi @jamiepittock 

This was completed in `3.3.2`, thanks!
