### ISSUE TITLE
Disabled discounts still get applied

### ISSUE THREAD

**Issue by bartrylant** [craftcms/commerce#1994]
**Description**
I recently noticed in two Commerce installs that a disabled discount still gets applied. On one site I had a "free shipping" discount (without code). "Don’t apply any subsequent discounts to an order if this discount is applied" was enabled, and the discount was on top of the discounts list. My client set the status of this discount to "disabled" yesterday. Since then, new orders don't get the free shipping discount (which makes sense, the discount is disabled), but it still stops applying subsequent discounts, which shouldn't happen.

**Expected behavior**
Disabled discounts shouldn't stop subsequent discounts, even when that option is ticked.

**Additional info**
- Craft version: Craft Pro 3.5.17.1
- Commerce version: 3.2.13.2
- PHP version: 7.4.14

**Comment by pdaleramirez** [comment]
@bartrylant I am not able to replicate this issue. Can you test on fresh cart? By deleting active and inactive carts. It could be that the session cart is still getting the discount from the previous setting. How do you apply a discount without a code?

**Comment by pdaleramirez** [comment]
Closing this for now, I will re-open this if a bug is confirmed.
