### ISSUE TITLE
"Call to a member function geturl() on null" on empty asset/entry fields in variants

### ISSUE THREAD

**Issue by Stalex89** [craftcms/commerce#2002]
**Description**
When custom non-required asset/entry field added to the product variant, but left empty, and if such product variant was added to the cart, retrieving a cart with the product variant in it returns 500 error "Call to a member function geturl() on null". Please add a check on null value for asset/entry custom fields before calling ->getUrl() on field value of the product variants while fetching cart data.

**To Reproduce**
How, and what happened?
1. `In the CP, Add product with variants`
2. `Add custom non-required asset/entry fields to the product variant`
3. `Try to add product variant to the cart in frontend/postman`

**Expected behavior**
The asset/entry field in the product variant should be checked on empty value before calling ->getUrl() method on the asset/entry value, and return null in the cart overview when it has no value

**Additional info**
- Craft version: Craft Pro 3.5.17.1
- Commerce version: 3.2.13.2
- PHP version: 7.4.15
- Database driver & version: MySQL 5.5.68
- Other Plugins & versions:

**Additional context**
![Screenshot 2021-02-15 at 10 04 57](https://user-images.githubusercontent.com/23526237/107926230-bbf22f00-6f75-11eb-8003-8285e16624db.png)
![Screenshot 2021-02-15 at 10 19 15](https://user-images.githubusercontent.com/23526237/107927634-8bab9000-6f77-11eb-8cca-796cb1fc741f.png)
![Screenshot 2021-02-15 at 10 19 25](https://user-images.githubusercontent.com/23526237/107927639-8cdcbd00-6f77-11eb-98fd-83e9e7f55968.png)

**Comment by lukeholder** [comment]
We don't call `getUrl` on any custom field. Are you modifying the cart json response on the server side to add img field info to the response maybe?

**Comment by Stalex89** [comment]
Sorry, my fault, the code is indeed called from the modified cart json response, this topic can be closed.
