### ISSUE TITLE
States order not reflected in Address dropdowns

### ISSUE THREAD

**Issue by matthisamoto** [craftcms/commerce#2005]
**Description**
When I set a custom order of the States under United States in the Commerce admin (as described in [this closed issue](https://github.com/craftcms/commerce/issues/1284)), ultimately the dropdown in my Address forms does not reflect this ordering. I assume that this is because, although the order of the printing of the items in the JSON object is correct, it is using an integer key JavaScript and is processing it in numerical order in the for loop in the JavaScript.

JavaScript snippet that populates the select, for loop appears to run in order of the integer keys not the order in which the JSON object is printed:
```
for (var id in states[cid])
{
    var state = states[cid][id];
    var $option = document.createElement('OPTION');
    $option.text = state;
    $option.value = id;
    $states.appendChild($option);
}
```

The States JSON as printed in the page markup via the `{% js %}` tag:
```
var states = {"233":{"55":"North Carolina","22":"Alabama","23":"Alaska","24":"Arizona","25":"Arkansas","26":"California","27":"Colorado","28":"Connecticut","29":"Delaware","30":"District of Columbia","31":"Florida","32":"Georgia","33":"Hawaii","34":"Idaho","35":"Illinois","36":"Indiana","37":"Iowa","38":"Kansas","39":"Kentucky","40":"Louisiana","41":"Maine","42":"Maryland","43":"Massachusetts","44":"Michigan","45":"Minnesota","46":"Mississippi","47":"Missouri","48":"Montana","49":"Nebraska","50":"Nevada","51":"New Hampshire","52":"New Jersey","53":"New Mexico","54":"New York","56":"North Dakota","57":"Ohio","58":"Oklahoma","59":"Oregon","60":"Pennsylvania","61":"Rhode Island","62":"South Carolina","63":"South Dakota","64":"Tennessee","65":"Texas","66":"Utah","67":"Vermont","68":"Virginia","69":"Washington","70":"West Virginia","71":"Wisconsin","72":"Wyoming"}};
```

The States JSON as printed by an added `console.log(states);`, and in the ultimate `option` output of the JavaScript that populates the `select`:
```
233:
22: "Alabama"
23: "Alaska"
24: "Arizona"
25: "Arkansas"
26: "California"
27: "Colorado"
28: "Connecticut"
29: "Delaware"
30: "District of Columbia"
31: "Florida"
32: "Georgia"
33: "Hawaii"
34: "Idaho"
35: "Illinois"
36: "Indiana"
37: "Iowa"
38: "Kansas"
39: "Kentucky"
40: "Louisiana"
41: "Maine"
42: "Maryland"
43: "Massachusetts"
44: "Michigan"
45: "Minnesota"
46: "Mississippi"
47: "Missouri"
48: "Montana"
49: "Nebraska"
50: "Nevada"
51: "New Hampshire"
52: "New Jersey"
53: "New Mexico"
54: "New York"
55: "North Carolina"
56: "North Dakota"
57: "Ohio"
58: "Oklahoma"
59: "Oregon"
60: "Pennsylvania"
61: "Rhode Island"
62: "South Carolina"
63: "South Dakota"
64: "Tennessee"
65: "Texas"
66: "Utah"
67: "Vermont"
68: "Virginia"
69: "Washington"
70: "West Virginia"
71: "Wisconsin"
72: "Wyoming"
```

**To Reproduce**
How, and what happened?
1. Change the default order of States under United States per 
2. Check addresses select box for updated order

**Expected behavior**
I expected the states to appear in the order set in the admin.

**Additional info**
Craft edition & version	**Craft Pro 3.5.16**
Craft Commerce	**3.2.12**
PHP version	7.3.27
OS version	Linux 3.10.0-1062.9.1.el7.x86_64
Database driver & version	MySQL 5.7.33
Image driver & version	GD 7.3.27
Yii version	2.0.38
Twig version	2.12.5

**Comment by pdaleramirez** [comment]
@matthisamoto The 233 number in the JSON is the countryId of the states. The JSON format is structured with countryId as a key with states as its children. 
To only return the states without the countryId you have to specify the countryId beforehand. It would look something like this in PHP.
```
	$countryId = Plugin::getInstance()->getCountries()->getCountryByIso('US')->id;
        $states = Plugin::getInstance()->getStates()->getAllStatesAsListGroupedByCountryId()[$countryId];
```
You can manipulate the order in PHP and then you can then pass that $states variable in your template or have it return in your ajax request.

**Comment by matthisamoto** [comment]
@pdaleramirez I'd appreciate you looking at this one more time. I'm not really sure what the point of adding the ordering is if it's never reflected in the list?

**Comment by goodmixer** [comment]
Re-ordering the states in the system is not reflected on the front end for the user. Also States added for country other than the prepopulated ones (USA, Canada, Australia) seems to stay in the order they were created regardless of moving them around in the CMS .

**Comment by nfourtythree** [comment]
Hi all,

I am unable to replicate this with the latest version of commerce and the following test template:

```twig
{% set statesByCountryId = craft.commerce.states.getAllEnabledStatesAsListGroupedByCountryId() %}

<ul>
  {% for countryId, states in statesByCountryId %}
    {% set country = craft.commerce.countries.getCountryById(countryId) %}
  	<li>
      <h3>{{ country.name }}</h3>
      <ol>
        {% for state in states %}
        	<li>{{ state }}</li>
        {% endfor %}
      </ol>
    </li>
  {% endfor %}
</ul>
```

Here is a video of things working as expected.


https://user-images.githubusercontent.com/266453/109432798-db249e00-7a04-11eb-91b5-97a17067e92a.mp4

Are there any more specific steps, or a screen recording that you can show us to help diagnose the issue you are having?

Thanks
