### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#201]
> Created by: Paul Woods ([pwoods@gcdtech.com](pwoods@gcdtech.com)) on 2016/10/13 11:48:13 +0000
Votes at time of UserVoice import: 6

------
Craft Commerce would completely win me if it could handle donations and regular giving for a charity.

**Comment by lukeholder** [comment]
Documentation: https://docs.craftcms.com/commerce/v2/donations.html
