### ISSUE TITLE
Can't update the plugin if allowAdminChanges = false

### ISSUE THREAD

**Issue by goraxan** [craftcms/commerce#2010]
**Description**
During an update from 3.2.8.1 to 3.2.15.2, when executing `php craft migrate/all` we got the following error `Exception 'yii\base\NotSupportedException' with message 'Changes to the project config are not possible while in read-only mode.'` because the https://github.com/craftcms/commerce/blob/develop/src/migrations/m201120_093135_add_locale_setting_to_email_and_pdf.php#L45 migration tries to update the project config

Is this the expected behavior? If so, how should we deploy to production where allowAdminChanges is always set to false?

Thanks

**Additional info**
- Craft version: 3.5.14
- Commerce version: 3.2.8.1
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.20
- Other Plugins & versions:

**Comment by pdaleramirez** [comment]
@goraxan it looks like that your folder `config/project` does not have write permission or your environment is preventing it from making changes to the project config folder. Would you be able to check your permission and environment? to see if that's the issue.

**Comment by lukeholder** [comment]
Hi @goraxan

Sounds like you pushed to production an update of commerce without also pushing the migrated/updated project config files at the same time? If you disable allowAdminChanges production then the commerce update migration should have been run on the local development machine first. The docs for that setting are:

https://craftcms.com/docs/3.x/config/config-settings.html#allowadminchanges

> Therefore you should only disable this in production environments when you have a deployment workflow that runs composer install automatically on deploy.

In the migration file you linked, we check to see the project config is updated to the matching schema version and wouldn't have tried to modify the project config in production if you had already done it on a local machine.

https://github.com/craftcms/commerce/blob/develop/src/migrations/m201120_093135_add_locale_setting_to_email_and_pdf.php#L30

If you think this could be clearer in the docs please make an issue on http://github.com/craftcms/docs
