### ISSUE TITLE
Duplicating products using "save as new product" in products detail page vs "duplicate" on product list

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#2012]
Both these functionalities work pretty much the same, except one detail. When we use "save as new product", new one has SKU with  number added, to ensure that it is not the same as SKU of original one.

But when we use "duplicate" on product list, both original and copy have same SKU, copy just starts as disabled and cannot be enabled until SKU is manually changed.

Maybe these one of these two behaviors should be used in both cases? My clients are sometimes confused why they sometimes have two products with what looks like duplicate SKU after they use "duplicate" functionality.

**Comment by pdaleramirez** [comment]
I couldn't recreate this issue, Most likely this issue has been resolved on newer version of Craft CMS
