### ISSUE TITLE
Big performance slowdown in orders index with >= 3.2.14

### ISSUE THREAD

**Issue by martinleveille** [craftcms/commerce#2013]
For the same database with 7 650 orders, when we browse to `/admin/commerce/orders` we have a big performance issue between version 3.2.13.2 and 3.2.14.

With the debug bar, here the number of SQL queries that are returned for the AJAX call to `/admin/actions/element-indexes/get-elements` :

Commerce Pro 3.2.13.2 = 303 queries (30 duplicates)
Commerce Pro 3.2.14 = 2523 queries (2248 duplicates)
Commerce Pro 3.2.15.2 = 2534 queries (2231 duplicates)

**Additional info**
- Craft version: Pro 3.6.6
- Commerce version: Pro 3.2.14
- PHP version: 7.4.15
- Database driver & version: MariaDB 10.5.8
- Other Plugins & versions: Only Commerce

**Comment by lukeholder** [comment]
@martinleveille Please send a DB dump, composer.json and compose.lock to support@craftcms.com and we can take a look.

**Comment by martinleveille** [comment]
@lukeholder We can't send you a dump of the database because there too much sensitive data. You can close this issue, we will stick with the 3.2.13.2 version, Thanks.
