### ISSUE TITLE
Variant URLs instead of queries

### ISSUE THREAD

**Issue by alexanderloewe** [craftcms/commerce#2014]
**What are you trying to do?**
I have implemented my first project with Commerce. There I noticed some rather awkward things. I'd like to give every product a slug and a nice URL like: `shop.com/cat/shirt-slim-blue` instead of `shop.com/cat/shirt?variant=1973`

**What's your proposed solution?**
It would be optimal for many reasons, if each product variant had directly an independent slug instead of solving this via the DB id. That would make the full process easier and better for the dev and the content creator.

**Comment by pdaleramirez** [comment]
Duplicated issue here https://github.com/craftcms/commerce/issues/1848
