### ISSUE TITLE
Promotions -> Sales are applied to all products in the shop

### ISSUE THREAD

**Issue by alexanderloewe** [craftcms/commerce#2016]
**Description**
I have created 10 sale (5% 10%, 15% aso) and they are applied to all products in the shop even when I don't apply them to any product. When i deactivate the sales under promotions everything is fine again.

**Additional info**
- Craft version: 3.66
- Commerce version: 3.2.14.1
- PHP version: 7.4

**Comment by alexanderloewe** [comment]
I have tested it to a few carts. The `wrong` price don't only show up in the cart. It shows up in the product pages as well.

**Comment by pdaleramirez** [comment]
@alexanderloewe Are your matching items under **Product Variant (Purchasable)** in `/commerce/promotions/sales/2#matching-items` blank? because if it is blank it defaults to all products.

**Comment by lukeholder** [comment]
Asked and answered. Closing for now.

**Comment by alexanderloewe** [comment]
Yes, the field was empty. 

However, I find this approach somewhat counterintuitive.

In the case that a sale should affect all products, it would make much more sense from a UX perspective to place a light switch for it. If the sale has no product applied, this should have no effect on the products. 

This way everything should be clear. Also, it's better for editors of the shop, so a dev can build all sales they need and then the shop admins can apply them if needed.
