### ISSUE TITLE
Pricing in cart and orders

### ISSUE THREAD

**Issue by alexanderloewe** [craftcms/commerce#2017]
**What are you trying to do?**
I want to do some things with the prices in the cart and the order:
1. I'd like to show the price of all products before the shipping is added. I do something like: `{% set preTotal = cart.getTotalPrice - cart.getTotalShippingCost %}` but it would be nice to have a variable witch gives back this data.
2. It would be nice to have a variable which give back all sales and discounts amounts in one: `totalSaleAmount` and `totalDiscount` in one variable.
3. **Important**: Also, I have noticed that the shipping price is based on the price before any adjustment. Here it would be good to have the option to reference the shipping to the price after all adjustments as well.

**Comment by lukeholder** [comment]
1.

We would need to provide the same for every combination of totalPrice minus tax/shipping/discounts. You will need to do this yourself for now.

2.

Sales are different to discounts so it doesn't make sense to make a method to combine them. If you want combine them you can do so in the template same as above.

3.

Upcoming Commerce 3.3 will include discounts in total price of the order for the purpose of shipping conditions.

Thanks.

**Comment by alexanderloewe** [comment]
1. I see the point
2. For the client it does not matter if it is a discount or a sale, so I think this one would make sens to add it from a UX point of view.
3. 👍🏻
