### ISSUE TITLE
Are there no email templates? 

### ISSUE THREAD

**Issue by amityweb** [craftcms/commerce#2018]
Forgive me if I am missing something obvious, but I cant see any email templates. The documentation refers to entering a HTML email template, at commerce/_emails/orderReceived for example. 

Do these not exist and we have to build all our own templates?

**Comment by lukeholder** [comment]
Copy the `shop` folder from the repo here https://github.com/craftcms/commerce/tree/develop/example-templates into your project's templates folder.

Can you link to the docs referencing a `orderReceived` template? The latest example templates use a `commerce/special/receipt` for both email and pdf examples.

**Comment by amityweb** [comment]
Thanks for speedy reply.

I am using the example templates... but I cant see any email templates in shop and buy folders. BUT you have pointed out its special/receipt.  I must admin I did not look in there as its called special and so not descriptive of emails! And your docs suggest a commerce and/or _emails folder. Docs are here https://craftcms.com/docs/commerce/3.x/order-status-emails.html
