### ISSUE TITLE
Place an order without Shipping Address?

### ISSUE THREAD

**Issue by afairhurst** [craftcms/commerce#2020]
I'm working on an commerce website for a florist. They offer local delivery and Click & Collect.

Customers often order for other people, thus the Shipping Address usually varies for each order. Currently when a customer returns to the shop, the Shipping Address is auto populated, to an existing address associated to the customer. Can we avoid this behaviour? We want the system to assume nothing.

I can't find a method to remove the Shipping Address from an Active Cart (i.e. cart) 
(not from a customer)? Attempting to do so fails – at least one Shipping Address remains attached to the cart. REF [1436](https://github.com/craftcms/commerce/issues/1436)

It seems that if a customer has one address saved, then it's impossible to remove this address from the cart. This is then affecting the ability to use the Shipping Estimator, which fails to work if a customer already has a Shipping Address attached to their cart.

Additionally, we'd like to provide the option for customers to Click & Collect, without attaching a Shipping Address to their order. As there's no default functionality for Click & Collect we're using a separate Shipping Method for this purpose. 

Craft version: 3.6.6
Commerce version: 3.2.15.2
PHP version: 7.4.15

Thank you!

**Comment by lukeholder** [comment]
Commerce config setting `autoSetNewCartAddresses` defaults to true, you can change this to false.

https://craftcms.com/docs/commerce/3.x/config-settings.html#autosetnewcartaddresses

**Comment by afairhurst** [comment]
Hi Luke,

Thanks for your swift reply.

Even with this config setting, and caches cleared, I'm still seeing the same behaviour; Shipping and Billing addresses are still automatically added to the cart. 

**config/general.php**
`autoSetNewCartAddresses' => false,`

Please can you take another look.

Thank you,

Andrew
