### ISSUE TITLE
Overlapping UI when editing order status

### ISSUE THREAD

**Issue by gioppe** [craftcms/commerce#2023]
**Description**
If the status label is too long it "overflows" its box. On Firefox, the status message field "follows" in some way the status field width, overflowing the box as well.

![immagine](https://user-images.githubusercontent.com/1929797/109160753-7e13b880-7776-11eb-8658-ea5010929323.png)

**To Reproduce**
How, and what happened?
1. Set a status of ~30 letters.
2. Edit order, change status.

**Expected behavior**
Status label should get shortened if too long? Status message field width should not change anyway.

**Additional info**
- Craft version: 3.6.7
- Commerce version: 3.2.15.3

**Additional context**

**Comment by nfourtythree** [comment]
Hi @gioppe 

Thank you for bringing this to our attention, we have pushed a fix for this.

It will be included in the next release of Commerce.

Thanks.
