### ISSUE TITLE
Remove Sales from a product or variant directly in the product entry

### ISSUE THREAD

**Issue by alexanderloewe** [craftcms/commerce#2025]
To remove a sale from a product or a variant I have to navigate to the matching sale in the settings `/commerce/promotions/sales/ID`. 

It would be much better to `handle sales like a category or a tag`, which I can remove directly in the place I have added it.

**Comment by pdaleramirez** [comment]
@alexanderloewe 
You can click on the sales assigned to a product in the bottom right corner of the product page.
You can actually assign sales based on the product category and manage product sales in sales settings.

**Comment by lukeholder** [comment]
This is already possible as @pdaleramirez pointed out. You can also add them on the variant itself.
