### ISSUE TITLE
Variants tab at the top with rest of the tabs

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#203]
> Created by: Jason Mayo ([jason@bymayo.co.uk](jason@bymayo.co.uk)) on 2016/08/26 12:54:30 +0000
Votes at time of UserVoice import: 7

------
I've got a client running Commerce at the moment that has a few entries that have a LOT of content in. I've managed to split these in to seperate tabs to reduce the length of the page.

But having the 'Variants' underneath the main tabs, causes the page to be long and could easily be missed.

If this 'Variants' tab could be moved to the top of the page with the rest of the tabs this would cut the page in half, and make it more manageable for the client.

**Comment by lukeholder** [comment]
Done in Commerce 2
