### ISSUE TITLE
Return JSON when calling actionSetPrimaryAddress

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/commerce#2033]
**Description**
I'm trying to save primary addresses from the frontend in Vue.
I'm doing an Axios POST request to `actionSetPrimaryAddress` with the `ID` and the `type` of an address and the address is set to primary shipping/billing correctly.

But as the return on this controller is `redirectToPostedUrl()` I'm not getting back any meaningful success or error message and even worse, that function is calling the request url again but this time as GET instead of POST returning a `400 Post request required` error.

**Expected behavior**
Return a proper JSON response as other controllers do and maybe add an optional parameter for the redirect URL.

**Additional info**
- Craft version: 3.6.7
- Commerce version: 3.2.16
- PHP version: 7.4
- Database driver & version: MySQL 5

**Comment by lukeholder** [comment]
Sounds like you are referring to `\craft\commerce\controllers\AddressesController::actionSetPrimaryAddress()` which is a control panel only endpoint that also requires the `commerce-manageOrders` permission which customers would not have on the front-end.

If you are working with addresses on the front-end you would use the `\craft\commerce\controllers\CustomerAddressesController::actionSave()` endpoint and pass an `address[id]` and `makePrimaryBillingAddress` or `makePrimaryShippingAddress`.

You will then get a json response if you are using axios.

Hope that helps.

**Comment by TomDeSmet** [comment]
Of course! Stupid me. I already used that to save new addresses and didn't think about using it to update those addresses as well. Thanks for your quick reply Luke!
