### ISSUE TITLE
Product image not generated for order confirmation email

### ISSUE THREAD

**Issue by j-greig** [craftcms/commerce#2034]
**Description**
We have a product thumbnail in our order confirmation/completion/update templates.

The image does not seem to render in time to be included in the email that is sent, resulting in a missing image.

We have tried using both native Craft transforms and Imager to create the product thumbnail but without any luck.

Is there something else we can try to get the image showing?

Thanks.

**Additional info**
- Craft version: 3.5.18
- Commerce version: 3.2.14

**Additional context**
If I trigger the confirmation to be sent manually via the CP, the product image appears fine, ditto if I preview the order confirmation template in my browser by passing in an order ID to it.

```
{% set transformedProductImage = craft.imager.transformImage(productImage, [
  { width: 100 }
],
{ format: 'jpg', ratio: 1/1, position: '50% 50%', jpegQuality: 80
 }) %}
<img src="{{ transformedProductImage[0].url }}">
 ```

**Comment by j-greig** [comment]
PS. Just been directed to https://github.com/craftcms/cms/issues/7267, unsure what I should change though?

**Comment by andris-sevcenko** [comment]
What URL ends up getting sent out?

**Comment by brandonkelly** [comment]
Doh… when I implemented craftcms/cms@be89e925992e68a8328e3bdf61ab742b9d363bae I forgot that Commerce does its own email template rendering, separate from Craft’s built-in code. So we need to make the same change on that end. We’ll follow up over at

**Comment by nfourtythree** [comment]
Hi @j-greig 

We have pushed a fix for this that will be included in the next Commerce release.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#e37afd5d7eacada2eef2cc06bec77f58669e6a1c as 3.2.17",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by j-greig** [comment]
Thanks @nfourtythree, have just tested this on the live site and the images still seem to be broken. I will run a few more checks though.

One question — the site in question is now suddenly showing £0.00 in both the Total Price  and Total Paid columns of admin/commerce/orders, could there be something in the dev release that is causing this?

**Comment by nfourtythree** [comment]
Hi @j-greig 

Hopefully, everything is now working as expected.

The total column sounds like this issue: https://github.com/craftcms/commerce/issues/1482

It is likely that it is because you were using the `dev-develop` version which makes it difficult to check version numbers

**Comment by j-greig** [comment]
Yes all good now, thank you kindly @nfourtythree 👍
