### ISSUE TITLE
Expected a Shipping Category Model, null returned when opening an order with a line item that used a deleted shipping category

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#2038]
**Description**
We had a shipping category that got deleted. 
Orders with line items related to this shipping category returns an internal server error so now the order won't open.

in this file:   ..\vendor\craftcms\commerce\src\models\LineItem.php   Line 75

**Additional info**
- Craft version: 3.5.17.1
- Commerce version: 3.2.10

**Comment by pdaleramirez** [comment]
What are the steps did you do to delete the shipping category? because a shipping category can't be deleted if there is an existing relation to previous orders.

**Comment by Sam-Black-0013** [comment]
Craft did not allow it if the category was still related to a product, so we created the new shipping categories, moved the products from the old one to the new one, and then deleted the shipping category. Orders that had those products, closed down. 

If it is possible to save it as a snapshot in the line item and just use that as the source.

**Comment by pdaleramirez** [comment]
@Sam-Black-0013 I followed the steps you've done and I couldn't replicated the issue. I did delete all the orders with the line items that had the previous shipping category.

If you deleted the orders (closed down) with line items that has the previous shipping category, the snapshot should not matter cause it will get deleted as well as you delete the order.

Do you have a plugin that is referencing a line item? If you have, that might be the issue. You can test this by uninstalling other plugins and ensure that the plugin's table is deleted too and see if the issue persist. I will re-open the issue if you still have issue after you followed the steps.
