### ISSUE TITLE
Add a "zip code zone level" to shipping and tax zones

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#204]
> Created by: Luke Holder ([luke@pixelandtonic.com](luke@pixelandtonic.com)) on 2016/08/23 10:11:25 +0000
Votes at time of UserVoice import: 7

------
A zip code regex that could match one or more zip codes?

**Comment by primo1108** [comment]
I'm also looking for this method too

**Comment by keyurshah** [comment]
Wondering the status of this? I looked for a plugin to use as a workaround but no luck. 

Thanks!

**Comment by oddnavy** [comment]
This would be very handy for a project we're working on

**Comment by sjelfull** [comment]
@oddnavy Correct, custom method is the way to go.

**Comment by andrewhawkes** [comment]
This is ideal now :) for what I needed!

![Annotation 2019-10-25 161414](https://user-images.githubusercontent.com/4975742/67583076-c9612580-f742-11e9-9cc3-81cfad3d35e3.jpg)

**Comment by andrewhawkes** [comment]
You can also pass regex to include or exclude postcode areas e.g.
```
not (zipCode[0:2] matches '/(?:BT|ZE|HS|GY|JE|IM)/')
```
