### ISSUE TITLE
Link to product in order detail

### ISSUE THREAD

**Issue by JoeriE** [craftcms/commerce#2048]
**What are you trying to do?**
In the order detail view, I would like to link the product title to the product detail page. Or is this already possible or easy to change myself?

![image](https://user-images.githubusercontent.com/11161180/111176947-1351e200-85aa-11eb-9609-1f51d45cd4b0.png)

**What's your proposed solution?**
Add link to product page in CMS behind the product title / description.

Thanks in advance

Best wishes,
Joeri

**Comment by pdaleramirez** [comment]
@JoeriE You can modify the cart twig template inside the `{% for item in cart.lineItems %}` loop. In the example template it is located in `cart/index.twig` you can see the `{{ item.description }}` inside the loop. You can add a link before that.

**Comment by nfourtythree** [comment]
Hi @JoeriE 

This has been updated and will be included in the upcoming `3.3` release of Commerce.

Thanks!
