### ISSUE TITLE
Count of orders having a particular status in the orders view

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#205]
> Created by: Jeremy Daalder ([jd@imagescience.com.au](jd@imagescience.com.au)) on 2016/08/12 04:42:22 +0000
Votes at time of UserVoice import: 4

------
We'd like to see the count of orders having a particular status appended to the name of the status in the left hand column of the orders view - this would help a lot in order processing.

**Comment by lukeholder** [comment]
This is now available as of 2.1
