### ISSUE TITLE
Customers with no primary billing or shipping address not returned in customer list

### ISSUE THREAD

**Issue by nickcobley** [craftcms/commerce#2052]
**Description**
We had to do a bit clean of customer data which involved removing in many cases the primary billing and/or shipping address. This left most customers without a primary shipping or billing address.

The side effect of this, is if the user also doesn't have an associated user account, the customer is not returned in the customer's list.

**To Reproduce**

1. Add two addresses to the customer, making sure it doesn't have a user account associated
2. Edit the customer, delete the primary address ensuring the remaining address is not marked as primary for billing or shipping
3. View the customer list, this customer should not be present

**Expected behavior**
What did you expect to happen?

Customer should be returned in the customer list

**Additional info**
- Craft version: 3.6.8
- Commerce version: 3.2.17
- PHP version: 7.4.16
- Database driver & version: 5.5.5

**Comment by pdaleramirez** [comment]
This a limitation for customers list in current version. In future major releases we'll address this issue by making the User element as a customer. Most likely it will be in version 4 release.

**Comment by nickcobley** [comment]
Still feels like a bug to me. It's a simple case of, make one of the addresses the primary shipping address, it will then be returned in the search results. Is there a MySQL query I could be provided to at least work around this issue to find the first address for each customer and set it as the primary?

**Comment by nfourtythree** [comment]
Hi @nickcobley 

We have pushed an update that fixes this. Customers (either those with a user or a completed order) will now be returned even if they do not have primary billing and shipping addresses.

This will be included in the next release of Commerce

Thanks!
