### ISSUE TITLE
When switching plans, getPlan()->id and getPlan->id return different data

### ISSUE THREAD

**Issue by ryanirelan** [craftcms/commerce#2055]
**Description**
When using the `EVENT_AFTER_SWITCH_SUBSCRIPTION_PLAN` event to do a user group change, `getPlan()->id` and `getPlan->id`return different plan data. The former returns the previous plan (switched from) while the latter returns the new plan.

Is that expected behavior?

**Additional info**
- Craft version: 3.6.10
- Commerce version: 3.2.17.3
- PHP version: 7.3.27
- Database driver & version: MySQL 5.5.5

**Additional context**
I can send you screenshots privately, if curious. Thank you!

**Comment by lukeholder** [comment]
@ryanirelan sorry for missing this one. 

When we trigger the event we pass oldPlan and newPlan as params.

https://github.com/craftcms/commerce/blob/b437d0c458482b91cf44c3da9f7e23846c1c67df/src/services/Subscriptions.php#L662-L669

What are you calling `getPlan()` on?

**Comment by lukeholder** [comment]
Let me know if this was not solved for you and I will reopen.
