### ISSUE TITLE
getplans().getAllPlans() returns all plans regardless of status

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#2056]
When using
`{% set plans = craft.commerce.getPlans().getAllPlans() %}
`
All plans are returned regardless of whether they are enabled in the CP.

**Expected behavior**
Only enabled plans should be returned. This would be in keeping with other similar constructs within Craft such as fetching Entries.

**Additional info**
- Craft version: 3.6.9
- Commerce version: 3.2.17

**Comment by fantasticmachine** [comment]
Looking more closely I don't think this is a bug but is intended behaviour. It just feels counter to how other similar things work within Craft.

**Comment by pdaleramirez** [comment]
@fantasticmachine Please use the `getAllEnabledPlans` method to only get enabled plans. 
E.g.
```
{% set plans = craft.commerce.getPlans().getAllEnabledPlans() %}
```
