### ISSUE TITLE
Editing line item quantities in order view on Ipad

### ISSUE THREAD

**Issue by NixonGit** [craftcms/commerce#2058]
**Description**
A client of ours is editing orders using and ipad air in landscape mode. When they click the edit button and try to change the quantity all of the items in the order disappear and the totals are set to 0. Recalculating the order brings back the initial order but they still cannot edit. I can provide a screen recording if thats helpful

**To Reproduce**
How, and what happened?
1. Using an ipad
2. In an order
3. Try to edit the quantity
4. All items are removed and totals set to 0

**Expected behavior**
What did you expect to happen?
Ability to freely edit the quantities of line items regardless of device or browser

**Additional info**
- Craft version: 3.5.16
- Commerce version: 3.2.12
- PHP version: 7.2.34
- Database driver & version: MySql 5.7.33
- Other Plugins & versions:

**Comment by pdaleramirez** [comment]
@NixonGit can you send the screen recording to `support@craftcms.com`. We'll check it out.

**Comment by lukeholder** [comment]
Fixed in #2062
