### ISSUE TITLE
Improved community space

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#206]
> Created by: Alex ([alex@sustainit.com](alex@sustainit.com)) on 2016/07/23 00:07:42 +0000
Votes at time of UserVoice import: 6

------
Craft and Craft commerce in particular, need improved community resources. Slack is great in real time but is not an archive so you end up asking the same question as someone a week back. Slack also takes away from Stack Exchange - better with everything in one basket. If you Google issues relating to Craft CMS you get very little useful info.

**Comment by angrybrad** [comment]
> Created by: Anna Brown ([anna@mediagirl.com](anna@mediagirl.com)) on 2017/09/23 18:36:19 +0000


------
I couldn&#39;t agree more. I think Slack works against the community in this exact way.

**Comment by angrybrad** [comment]
> Created by: brad ([brad@pixelandtonic.com](brad@pixelandtonic.com)) on 2017/09/24 22:57:54 +0000


------
Definitely open to hearing other options... but there some questions that happen in Slack that would not make good Stack Exchange questions and some questions that pop up on Stack Exchange that are much better off in Slack.

**Comment by angrybrad** [comment]
> Created by: Anna Brown ([mediagirlnm@gmail.com](mediagirlnm@gmail.com)) on 2017/09/25 19:59:54 +0000


------
I regularly reference Stack Exchange for code samples as I&#39;m sure a lot of us do. I generally Google first since I think Google results are better. The more code on Stack Exchange the better. Perhaps a regular reminder to Slack folks?

**Comment by lukeholder** [comment]
Off Topic.
