### ISSUE TITLE
Edit adjustments link in Order does nothing

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#2060]
Not sure if this is a bug or not.
When editing an order, clicking Edit Adjustments doesn't appear to work.
Note: I am trying to remove a custom adjuster from an order so this may have some bearing.

**To Reproduce**
Edit a completed order with an adjustment.
Click "Edit Adjustments"
The Link disappears but there is no way to edit the adjustments

**Expected behavior**
Would expect a UI to be able to remove/edit adjustments

**Additional info**
- Craft version: 3.6.9
- Commerce version: 3.2.17

**Comment by fantasticmachine** [comment]
No JS errors but if I try it on another order then I see the fields as expected.

I’ll investigate a bit further. It’s no doubt something about how I’ve created that order.

**Comment by fantasticmachine** [comment]
I'm going to close this as it's almost certainly an oddity with this particular site rather than a bug.

**Comment by adrum** [comment]
If anyone comes back here wondering the same thing, the Vue component to edit Adjustments only shows the form elements when the Order recalculation mode is set to none. Sure enough, I had overriding this, and this was causing the UI to be hidden.
