### ISSUE TITLE
Ability to set rounding method

### ISSUE THREAD

**Issue by elivz** [craftcms/commerce#2061]
**What are you trying to do?**
We are integrating with an external ERP system that uses "bankers rounding" (rounding halves to the nearest even number, the default in .NET). When calculating percentage-based price modifiers (discounts, taxes, etc) this can lead to 1-cent discrepancies in some cases.

**What's your proposed solution?**
From what I can see, it looks like that is entirely controlled by [one line of code in the CurrencyHelper](https://github.com/craftcms/commerce/blob/main/src/helpers/Currency.php#L40). What would be great is if either the `mode` parameter could be made configurable in the Commerce config file, or if it were possible to override that class with one of our own somehow. Then we could set to the mode to `PHP_ROUND_HALF_EVEN` (or any of the other options) and make things match.

**Comment by nfourtythree** [comment]
Hi @elivz 

Thank you for your issue. We currently have a feature request for control over currency rounding.

Please add your thoughts and feedback on this issue: #1636 

Thanks!
