### ISSUE TITLE
Extend discount formulas to support custom order fields

### ISSUE THREAD

**Issue by goraxan** [craftcms/commerce#2066]
**What are you trying to do?**
We are trying to add this formula to an existing discount `order.monthModality.numElements == 4` (so that only orders with a month modality of 4 items are selectable for the discount) being `monthModality` a category field.

Since the order is converted into an array for [safety reasons](https://craftcms.com/docs/commerce/3.x/discounts.html#discount-condition-formula) and only the `'lineItems.snapshot', 'shippingAddress', 'billingAddress'` related fields are available, we cannot use our custom fields in the formula. 
All we can do is define a numeric field in the order itself (for example called `numElements`), update it inside the event `EVENT_POPULATE_LINE_ITEM` every time a line item changes, and change our formula to be `order.numElements == 4`. Since that field is included in the order array, that'd work.

Alternatively we could define our custom adjuster but that'd force us to move the rest of the existing discount logic to our coded adjuster.

**What's your proposed solution?**
Allow custom fields to be used in the discount formulas by adding them in the order array.

**Additional context**
CraftCMS version: 3.5.14
CraftCMS Commerce version: 3.2.15.2
PHP version: 7.4.16

**Comment by levinelson** [comment]
+1

I'm using Digital Products. Because Digital Products don't support variants, I'm planning on using a discount to change the price of a Digital Product after a user selects a "License Type" in the checkout process. I was planning on using `order.licenseType == 'studio'` to apply the appropriate discount.

Unfortunately, I was bummed to find out custom fields are not supported on orders.

**Comment by lukeholder** [comment]
This is fixed in #2102 so you will have access to custom fields in the formula. Should be released in 3.0.1 on 4th April.

**Comment by lukeholder** [comment]
3.3.1 is now out!

**Comment by levinelson** [comment]
Awesome, thanks!
