### ISSUE TITLE
min AND max qty for discount rules

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#207]
> Created by: Eric Wiley ([eric@infotoken.com](eric@infotoken.com)) on 2016/07/22 14:32:03 +0000
Votes at time of UserVoice import: 1

------
Allow ability to apply tiered volume discounts (and prevent multiple discounts from being applied when all rules are met)

Thanks!

**Comment by lukeholder** [comment]
This should be possible in Commerce 2.x
