### ISSUE TITLE
Login as pending user on front-end

### ISSUE THREAD

**Issue by lennartlott** [craftcms/commerce#2071]
**What are you trying to do?**
It should be possible to log in as a pending user on front-end to place orders and subscriptions.
Email verification in the order process is a **conversion killer**.

Now: Signup -> Email verification -> Payment -> Confirmation

Better: Signup -> Payment -> Confirmation + Email verification

**Comment by pdaleramirez** [comment]
@lennartlott This currently possible by doing the Guest checkout flow. Documentation here https://craftcms.com/docs/commerce/3.x/customers.html#guest-checkout
You can pass the `registerUserOnOrderComplete` request to false in the form to allow guest checkout.

**Comment by lennartlott** [comment]
@pdaleramirez This works for normal orders but it is not possible to complete a subscription as guest. Or am I mistaken?
