### ISSUE TITLE
Multi-PDF Export

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#208]
> Created by: James Lindeman ([mail@jameslindeman.co.uk](mail@jameslindeman.co.uk)) on 2016/07/21 19:41:56 +0000
Votes at time of UserVoice import: 2

------
Option to export multiple PDF. Ideally for a set time period. For example export all invoices for the last financial quarter.

**Comment by RandomJo** [comment]
My team is working on a Craft Commerce site for a client who would really like this feature. They are coming from Etsy, so they're used to being able to print PDFs in bulk to use as part of their fulfillment process.

**Comment by lukeholder** [comment]
This will be possible in the next release of Craft Commerce (3.2) Thanks!

cc @RandomJo
