### ISSUE TITLE
Suggestion for "Addition" adjustment type.

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#2080]
It's possible to use positive numbers on a "Discount" adjuster to increase the price of a line item. However this still shows labelled as "Discount" In the order detail page of the CP. This is potentially confusing language for site admins who may not quite understand why a "Discount" increases the price.

Could we have an additional adjustment type for "Additions" (or some other language) for adjustments that add to the price rather than discount it. Or perhaps even simply group adjustments that add to the price separately to the discounts and label accordingly in the CP.

**Comment by lukeholder** [comment]
We are looking into a price adjustments type and will track it here: https://github.com/craftcms/commerce/issues/1042
