### ISSUE TITLE
Refund transaction reference on EVENT_AFTER_REFUND_TRANSACTION 

### ISSUE THREAD

**Issue by aryehischechter** [craftcms/commerce#2081]
**What are you trying to do?**
Get the refund transaction on the EVENT_AFTER_REFUND_TRANSACTION event.
Right now, the event only passes the parent transaction and the amount.
But if we need the reference, or more specifically the transactionId, of the refund itself we need to make another query for the latest transaction where the parentId is the transaction we're refunding.
This is a race condition and a poor implementation when the refund transaction could be passed in the event.

**What's your proposed solution?**
The code [here](https://github.com/craftcms/commerce/blob/develop/src/services/Payments.php#L372) triggers the event and creates a RefundTransactionEvent.
The Event structure should have an optional property reference to the $refundTransaction, which is created a few lines earlier.
It can't be a required property since the BEFORE event wont have it.

**Comment by lukeholder** [comment]
This has been fixed and will be in the 3.3.1 release tomorrow.

**Comment by lukeholder** [comment]
3.3.1 is now out!
