### ISSUE TITLE
CommerceEditAddressModal size issue. **Min width is set to 980px**

### ISSUE THREAD

**Issue by rehanawan** [craftcms/commerce#2087]
**Description**
Describe what the problem is.
Edit Shipping Address modal is set to min width size 990 px, which makes it larger than the screen size.
![image](https://user-images.githubusercontent.com/18535538/114705389-fd118000-9d27-11eb-85e1-255079ed0a06.png)

**To Reproduce**
How, and what happened?
1. `In the CP...`
2.

**Expected behavior**
What did you expect to happen?

**Additional info**
- Craft version:
- Commerce version:
- PHP version:
- Database driver & version:
- Other Plugins & versions:

**Additional context**

**Comment by pdaleramirez** [comment]
@rehanawan The modal is auto resize based on the screen size. The form is still usable because of the overflow scroll.

**Comment by rehanawan** [comment]
![image](https://user-images.githubusercontent.com/18535538/114849018-a1a2c900-9ddf-11eb-99f0-032b2b33c2b0.png)
@pdaleramirez as you can see in the screenshot, Overflow is not working. And it is then unable to click the save but as it is below the screen,

**Comment by rehanawan** [comment]
I assume the min-height calculation is somehow wrong. 
![image](https://user-images.githubusercontent.com/18535538/114849661-41f8ed80-9de0-11eb-95e0-09edca61e659.png)
