### ISSUE TITLE
Discount>Flat Amount Off Order - amount of discount is inversed when there is an error saving the discount

### ISSUE THREAD

**Issue by paddling** [craftcms/commerce#2090]
**Description**
When creating or updating a discount in Craft Commerce with the action on the order being a "Flat Amount Off Order" AND there is an issue when saving that discount, the Flat Amount Off Order value will be inverted.  (e.g. value turns from 5 to -5). The discount then becomes incorrect.

**To Reproduce**
How, and what happened?
1. In the CP, create or update a discount that has an action of "Flat Amount Off Order"
2. Set the amount off to be a positive number.
3. Create some sort of problem with the discount that would not allow it to save (e.g. add invalid syntax to the `Order Condition Formula` field.
4. Save the discount
5. Because of the invalid syntax, the order will not save.
6. View the `Actions` tab and you can confirm that the discount was inversed to be a negative number.
7. Note the discount is allowed to save after fixing the syntax error. There is no issue with saving the action as a negative number.

**Expected behavior**
The value for the amount off should not be affected.

**Additional info**
- Craft version: Craft Pro 3.6.10
- Commerce version: 3.2.17.1
- PHP version: 7.3.24
- Database driver & version: MySQL 5.5.5

**Additional context**
See video

https://user-images.githubusercontent.com/58182286/115034903-00c51400-9e9a-11eb-87bf-18fba7af8810.mp4

**Comment by lukeholder** [comment]
Fixed for the next release in #2093
