### ISSUE TITLE
Empty address state field prevents product from being added to cart

### ISSUE THREAD

**Issue by petehjfd** [craftcms/commerce#2096]
Our site is configured to require a state for UK addresses.  We had a situation where a user had a UK address associated with their account that was missing a state.  When the user tried to add a product to their cart, it failed with the error message: "Country requires a related state selected."

It's not supposed to be possible on the site for a user to add a UK address without a state, so we're looking into how that happened.  But even so, surely this is not the right place to be showing that error?  I can unerstand preventing the user from completing checkout without providing a state, but preventing them from adding anything to their cart seems a bit excessive.  The user certainly won't understand what the error means or how to resolve it.

**Additional info**
- Craft version: 3.6.11.2
- Commerce version: 3.2.17.3
- PHP version: 7.4
- Database driver & version: MySQL 5.7

**Comment by nfourtythree** [comment]
Hi @petehjfd 

Thank you for your message.

It seems like this mostly centres around some bad data as you mentioned:

> It's not supposed to be possible on the site for a user to add a UK address without a state, so we're looking into how that happened.

By adding your state validation to addresses this will happen every time the cart is saved to check that everything is valid. If you would only like the validation to happen during certain requests it would require you to look into updating the state validation rule with some custom logic.

Commerce uses a generic `commerce/cart/update-cart` endpoint to give the most amount of flexibility possible to developers and not force anyone to have to post specific data to specific endpoints. This means out of the box Commerce simply applies the validation rules that are set when an order element is saved and does not try to guess any context in regards to the data being posted.

Thanks!
