### ISSUE TITLE
Shipping rule validation requires Order Condition Formula

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#2098]
**Description**
Validation for shipping rules is now requiring Order Condition Formula, resulting in the error message "Order Condition Formula cannot be blank" when trying to save a rule with that field empty.

**To Reproduce**
1. Navigate to a shipping method rule with an empty Order Condition Formula.
2. Click Save button.
3. Flash message displays "Couldn't save shipping rule," and error message under Order Condition Formula field displays "Order Condition Formula cannot be blank."

**Expected behavior**
Expected to be able to save rule without Order Condition Formula as in previous versions.

**Additional info**
- Craft version: Pro 3.6.12
- Commerce version: Pro 3.3.0
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by lukeholder** [comment]
Thanks fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to `"dev-develop as 3.0.0"` and run `composer update`. After the update is out your can restore your composer.json to its previous state.
