### ISSUE TITLE
Default tax zone not respected

### ISSUE THREAD

**Issue by tigerchick** [craftcms/commerce#2099]
**Description**
Since upgrading to Commerce 3.3.0 it seems that the default tax zone setting is not respected.
Within the tax zone entry there is a checkbox setting "Default to this tax zone when no shipping address is set". It does not appear to work.
Prior to shipping country address being set, carts are having adjustments applied to them that should not be the case if the default tax zone was being correctly applied.

**Additional info**
- Craft version: 3.6.12
- Commerce version: 3.3.0
- PHP version: 7.3.27
- Database driver & version: MySQL 5.5.62
- Other Plugins & versions:

**Additional context**
The site in question is currently in development. It is possible that this problem existed prior to commerce 3.3.0 but it is only after upgrading that I noticed it.

**Comment by lukeholder** [comment]
@tigerchick I can't reproduce this issue.

Can you confirm the shipping address is not being set automatically (which it is for logged in users) and this could be why the default is not being used?

Output the shipping address like this -> `{{ cart.shippingAddress.id ?? 'no address' }}`

It should be using the default zone if you see 'no address'. Let me know.

**Comment by tigerchick** [comment]
Hi @lukeholder,
Thanks for looking. You are right - it only happens when I'm logged in, and yes, the shipping address is being set automatically - so that is all correct behaviour.
However, this is where the plot thickens , looking at the shipping address on the backend - it is empty. That is except for the country field which is set to the first country in the list: Afghanistan.
There is no way on the backend to select no country in the dropdown list - as in, for that field to be empty.
This is the dump of `{{ dump(cart.shippingAddress ?? 'None' )}}`

`object(craft\commerce\models\Address)#1769 (35) { ["id"]=> string(1) "1" ["isStoreLocation"]=> bool(false) ["attention"]=> string(0) "" ["title"]=> string(0) "" ["firstName"]=> string(0) "" ["lastName"]=> string(0) "" ["fullName"]=> string(0) "" ["address1"]=> string(0) "" ["address2"]=> string(0) "" ["address3"]=> string(0) "" ["city"]=> string(0) "" ["zipCode"]=> string(0) "" ["phone"]=> string(0) "" ["alternativePhone"]=> string(0) "" ["label"]=> string(0) "" ["businessName"]=> string(0) "" ["businessTaxId"]=> NULL ["businessId"]=> string(0) "" ["stateName"]=> NULL ["countryId"]=> NULL ["stateId"]=> NULL ["notes"]=> string(0) "" ["custom1"]=> string(0) "" ["custom2"]=> string(0) "" ["custom3"]=> string(0) "" ["custom4"]=> string(0) "" ["isEstimated"]=> bool(false) ["_stateValue":"craft\commerce\models\Address":private]=> NULL ["_vatValidator":"craft\commerce\models\Address":private]=> NULL ["_errors":"yii\base\Model":private]=> NULL ["_validators":"yii\base\Model":private]=> NULL ["_scenario":"yii\base\Model":private]=> string(7) "default" ["_events":"yii\base\Component":private]=> array(0) { } ["_eventWildcards":"yii\base\Component":private]=> array(0) { } ["_behaviors":"yii\base\Component":private]=> array(0) { } }`

Here we see that the ID is '1', so it's recognising that there is an existing shipping address, however the countryID is null.

In my template I do pre-fill the shipping fields with pre-existing values. The country field isn't fetching anything pre-exisintg because it is null but at the same time it is behaving as if that value is set in a way that it would negate the default VAT tax zone.

**Comment by lukeholder** [comment]
Going to ask you send this into support with clear steps to reproduce.

Please send to support@craftcms.com with your DB backup, composer.json, and composer.lock files.

We will attempt to reproduce from there and this ticket will be updated by us if there was any bug confirmed.
