### ISSUE TITLE
Visualize how people interact with the products

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#210]
> Created by: Anonymous ([seba78ml@gmail.com](seba78ml@gmail.com)) on 2016/06/23 15:49:54 +0000
Votes at time of UserVoice import: 3

------
This is a whole area which CraftCommerce not paid attention to. 
System statistics in dashboard, best sellers, most viewed products, best rated products, tracking user behavior. This is essential to evaluate and create marketing campaigns and perform monitoring results.  Absolutely necessary, now the main client is in the shadow of what happens between users and products.

**Comment by lukeholder** [comment]
Relevant: https://plugins.craftcms.com/recently-viewed

**Comment by lukeholder** [comment]
Decided to leave this for plugins to achieve at the moment.
