### ISSUE TITLE
Shipping costs not being applied to checkout total/summary

### ISSUE THREAD

**Issue by knynkwl** [craftcms/commerce#2100]
**Description**
The shipping cost is not being applied to the total in the checkout summary.

**To Reproduce**
![Screen Shot 2021-04-21 at 11 24 13 AM](https://user-images.githubusercontent.com/4225771/115735782-c0154100-a358-11eb-9004-063bcfe44266.png)

![Screen Shot 2021-04-21 at 11 20 09 AM](https://user-images.githubusercontent.com/4225771/115735750-b986c980-a358-11eb-97f4-40ed489da766.png)

**Expected behavior**
The shipping cost showing in summary and applied to the order total.

**Additional info**
- Craft version: 3.6.10
- Commerce version: 3.2.17.3

**Comment by pdaleramirez** [comment]
@knynkwl I couldn't replicate this issue on the version you've given. Would you be able send us the db in `support@craftcms.com` as well as the `composer.json` and `composer.lock` files. We'll debug further.

**Comment by knynkwl** [comment]
@pdaleramirez unfortunately we cannot provide a DB due to security issues. Is there another way to debug this?

**Comment by lukeholder** [comment]
@knynkwl Can you take screenshots using the example templates? I don't see the adjustment line on the order in your screenshots? Is it missing?

**Comment by knynkwl** [comment]
@lukeholder here's a screenshot of the whole summary

![Uploading Screen Shot 2021-04-28 at 9.21.56 AM.png…]()

**Comment by knynkwl** [comment]
This was an issue with a plugin. Thanks
