### ISSUE TITLE
Add an on check availability event

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#2106]
**What are you trying to do?**
Control whether an item is available based on some custom logic, in our case the value of custom fields eg custom date fields to stopSellingOn, startSellingOn 

**What's your proposed solution?**
Add an ON CHECK AVAILABILITY event to both product and purchasable `getIsAvailable()` methods. 

Added side effect is that these purchasables will then get picked up by the new notices logic and removed on recalculation!!

**Comment by nfourtythree** [comment]
Hi @samhibberd 

This has been added to the upcoming `3.3.1` release due soon.

You can track the status of `3.3.1` here: https://github.com/craftcms/commerce/pull/2103

Thanks!
