### ISSUE TITLE
Exception when getting notices by type / attribute if there are currently no notices

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#2108]
Throws exception when getting or checking for notices by type / attribute if there are currently no notices on the cart, because the value of the private variable`$_notices` is `null`.

https://github.com/craftcms/commerce/blob/692211a67c7aac90f2af2bdb1d2cbb7172684222/src/elements/traits/OrderNoticesTrait.php#L41

https://github.com/craftcms/commerce/blob/692211a67c7aac90f2af2bdb1d2cbb7172684222/src/elements/traits/OrderNoticesTrait.php#L46

https://github.com/craftcms/commerce/blob/692211a67c7aac90f2af2bdb1d2cbb7172684222/src/elements/traits/OrderNoticesTrait.php#L51

**Comment by lukeholder** [comment]
Thanks taking a look now.

**Comment by lukeholder** [comment]
Thanks, fixed for the release tomorrow.
