### ISSUE TITLE
Order site always in primary site

### ISSUE THREAD

**Issue by MarcelWeidum** [craftcms/commerce#2110]
**Description**
When we order on the primary or on the secondary site, the order is always registering under the primary site.

**To Reproduce**
1. Order on primary site
2. Look in backend at Order site, it is always on the primary

**Additional info**
- Craft version: Pro 3.6.12
- Commerce version: 3.2.17.4
- PHP version: 7.3.16
- Database driver & version: MySQL 5.5.5
- Other Plugins & versions: -

**Comment by pdaleramirez** [comment]
@MarcelWeidum Commerce doesn't support multi store yet. Your order will always be placed on the primary site. On Commerce version 4, we'll be adding multi store feature.

**Comment by pdaleramirez** [comment]
@MarcelWeidum Are you referring to the `orderSiteId` column in the orders table?

**Comment by hilbertknl** [comment]
I also work on this project. I managed to log the order in the event EVENT_BEFORE_SEND_MAIL.
This result shows "siteId" and "orderSiteId" to be "1" where "2" was expected.
Opening the MySQL database table "commerce_orders" shows me that "orderSiteId" is "2".

Store 1 is nl, store 2 is nl-BE.

Order JSON:
`{"number":"d6114d1eeb5aa2a2ba775996ff6459b0","reference":"d6114d1","orderLanguage":"nl-BE","orderSiteId":1,"siteId":1}`

**Comment by pdaleramirez** [comment]
@hilbertknl I tested the `EVENT_BEFORE_SEND_MAIL` event, the $order and $orderData variables contains the correct `orderSiteId` value based on where you checked out.

Can you test by disabling all other plugins and modules, and see if you are still getting the wrong values? If you still have the same problem please send us your db and composer.json with composer.lock files to `support@craftcms.com` We'll debug further.

**Comment by pdaleramirez** [comment]
@MarcelWeidum  Thank you for sending us your db in support but I couldn't replicate the issue with your exact setup. Closing this for now and will re-open if you encounter again this issue. I replied in details in the support ticket.

**Comment by cruiser12** [comment]
hello, we have a similar problem. `cart.orderLanguage` is actually defined by the current sites order language. But whenever we update the cart by AJAX when e.g. updating the shipping address, the `cart.orderLanguage` will always return to the primary site language.

AJAX post parameters:

```
action: commerce/cart/update-cart
successMessage: 62bc1d15b0bf3dcbc1f39f1913fd899ca6a00e8100fd445c11c34a5ba0830c6bAddresses selected.
redirect: 5c12ff76b54ae0d639e1ad36f3d267e26ec09eb1dca362316e07a0871f2ac77e/fr/shop/checkout?address-saved
CRAFT_CSRF_TOKEN: 9qOdFkkupiFE1IuENcqJIcKMfSir6DXsLo8q3ee6UrP1Q00kOlcmjrOVy0U7duRtFK3jwViez2OIvlB_wbcAg2bnZJ_X2Dr0gg98EU0Fa-0=
shippingAddress[firstName]: test
shippingAddress[lastName]: test
shippingAddress[businessName]: test
shippingAddress[countryId]: 215
shippingAddress[address1]: test
shippingAddress[city]: test
shippingAddress[zipCode]: 4143
shippingAddress[phone]: 041779858543
email: test@test.ch
shippingAddress[notes]: 
orderLanguage: fr-CH
makePrimaryBillingAddress: 1
makePrimaryShippingAddress: 1
shippingAddress[id]: 201
billingAddress[id]: 201
billingAddressSameAsShipping: on
billingAddress[firstName]: test
billingAddress[lastName]: test
billingAddress[businessName]: test
billingAddress[countryId]: 215
billingAddress[address1]: test
billingAddress[city]: test
billingAddress[zipCode]: 4143
billingAddress[phone]: 0041779858543
billingAddress[notes]: 
```

will result in 

```
{
"success":true,
"cart":{
...
orderLanguage: de-CH
...
}}
```

even the request was sent from a site that has `fr-CH` site language and also the `cart.orderLanguage` parameter was set to `fr-CH` in request.
