### ISSUE TITLE
Call to undefined method craft\commerce\models\OrderNotice::create()

### ISSUE THREAD

**Issue by knynkwl** [craftcms/commerce#2111]
We started to get this error when we changed our products to have unlimited stock to limited stock. 

Craft: 3.6.12.1
Commerce: 3.3.0.1

![Screen Shot 2021-04-29 at 5 30 08 PM](https://user-images.githubusercontent.com/4225771/116621027-989e1580-a910-11eb-98cb-632a05dd9648.png)

**Comment by lukeholder** [comment]
Thanks for reporting this. It has been fixed for the next release:


To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-3.3.1#dcd77fe559f28ce6cd000658cca9eed87fc633d5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by knynkwl** [comment]
@lukeholder I tried and got this error with the plugins installed. I tried `-W` but it failed as well.

![Screen Shot 2021-04-30 at 7 54 23 AM](https://user-images.githubusercontent.com/4225771/116691754-49e09200-a989-11eb-8c61-f6366e5df556.png)

**Comment by knynkwl** [comment]
I also tried `rm` the composer.lock file and reinstalling `composer i`

**Comment by lukeholder** [comment]
Apologies, just found that the fix I pushed had a typo causing a PHP error... just fixed it again.

Also see the composer constraint I gave you was wrong, please try the following...

Change your craftcms/commerce requirement in composer.json to:

"require": {
  "craftcms/commerce": "dev-develop#419a05ebc8a760d5035572221ab7dd4c182f2018 as 3.3.0.1",
  "...": "..."
}
Then run composer update.

3.3.1 will be released in about 36 hours.
