### ISSUE TITLE
[RFC] Don't block the checkout process when the Business ID is invalid

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/commerce#2113]
**What are you trying to do?**
We want people to be able to check-out if their Business ID is not valid. Currently, it adds an error to the cart, but this also prevents people from finishing their order (without tax discount ofcourse).

**What's your proposed solution?**
Just save the address with the invalid business tax id.

**Comment by lukeholder** [comment]
Sounds like you have the  `validateBusinessTaxIdAsVatId` config variable set to true? The default is false.

Set to true, it will force a validation error if the ID entered is not valid on the address. 

If you have tax rates set up that look for a valid vat ID, they will still work, but just not apply the VAT removal if the ID is not valid, allowing them to check out still.

Let me know if I missed anything.

**Comment by lenvanessen** [comment]
@lukeholder yes, I'll cry myself asleep in shame tonight.
