### ISSUE TITLE
Multiple Donation objects

### ISSUE THREAD

**Issue by nathansnelgrove** [craftcms/commerce#2115]
I have a lot of NPO clients who would love to have more than one donation object, where the end user can state the final price and manage it in the cart. (This would be great for subscriptions too.) Having one donation object is good for basic stores, but the clients who need Craft the most (with complicated content and e-commerce needs) ironically are unable to do so because of this limitation in Commerce.

**Comment by lukeholder** [comment]
Hi @nathansnelgrove 

Just top clarify, there is a single donation purchasable, but you can have more than one in the cart by submitting line item options when adding to the cart:

<img width="1047" alt="CleanShot 2021-05-03 at 17 20 18@2x" src="https://user-images.githubusercontent.com/133571/116860251-de6e1d00-ac33-11eb-824d-f8ebdc37b3e5.png">

Would that be a solution or are you looking for a different purchasable ID?

**Comment by nathansnelgrove** [comment]
Ah, I did not realize this. This solves this particular problem, thank you! The ability to make this recurring would be killer, but that’s a separate feature request (and I know recurring products are on the todo list). 

I think a note about this in the documentation would be helpful; it wasn’t clear to me when I read it. 

Thank you!
