### ISSUE TITLE
Customer Notices - Previously selected shipping method

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#2116]
Firstly, spelling error in this message: `Previously selected shipping method is **no** longer available.`.

But we're getting this error in the CP when editing a order complete and paid:

![image](https://user-images.githubusercontent.com/1221575/116769559-6f03fc00-aa80-11eb-8679-75accd53d7d7.png)

Looking at the order in the DB directly:
shippingMethodHandle = freeShipping
shippingMethodName = Free Shipping

And can confirm this shipping method exists:

![image](https://user-images.githubusercontent.com/1221575/116769593-9a86e680-aa80-11eb-9305-64806a10718c.png)

Should this error be shown, as I don't think it's correct? 

**Additional info**
- Craft version: 3.6.12
- Commerce version: 3.3.0

**Comment by bossanova808** [comment]
Yep been seen (erroneously) a few times here too

**Comment by lukeholder** [comment]
Fixed the typo. Thanks.

Cant seem to replicate on the edit order page: https://cln.sh/f8ZRwZ (screen capture)

Any suggestions? @bossanova808 @engram-design

**Comment by bossanova808** [comment]
So far I've just had reports of folks seeing it and not understanding it.  I'll try and track it down more concretely.

**Comment by bossanova808** [comment]
Actually, reading the docs on these - does completing an order clear notices?

I.e. say a customer changes their order along the way, and therefore there is a notice about a shipping method on the cart along the way....is it the case this notice will stay attached to the order, unless explicitly cleared, right through to checkout and beyond - and then be visible to the order processors in the back end?

If so...that doesn't make much sense to me, personally.  I guess I could an add explicit clear notices call on the order complete page or something, but just seems a bit odd (if I am reading that right).  As that will happen quite a lot in our case, and there's no need for the message to make it to the order processing stage...

**Comment by philipboomy** [comment]
I am getting that message too and I think its appearing in my carts and orders when I remove shipping methods frontend based on whats in the cart. I can send "digital product" as email except if they add a physical thing like a fruit basket. So they if the customer add digital product to their cart and select email as shipping method and then later add a fruit basket I automatically remove the email shipping method.

**Comment by lukeholder** [comment]
In Commerce 3.4 (beta next week fd12627e9e537eb271d0eb45598d2eb8a31fee21) we will be clearing the notices on order completion. We asses the customer is happy to dismiss the notices since they have decided to complete/pay for the order.

We can't see where this is being added incorrectly. Please submit a new ticket if you can give reproducing steps.

Thanks.
