### ISSUE TITLE
Dashboard Widget "Total revenue" missing orders

### ISSUE THREAD

**Issue by CMeldgaard** [craftcms/commerce#2117]
**Description**
When inserting the "Total revenue" widget, and selects a specific dateragen, for instance May 1 to May 2, the widget is missing ordres. The end date always says that the orders are zero, even if there are ordres. I also experience that it calculates order with, that are ordered before May 1 with.

**Expected behavior**
I expect that when i select the periode from May 1 to May 2, only the selcted dates, and the dates in between is calculated.

**Additional info**
- Craft version: 3.6.12
- Commerce version: 3.2.17.4
- PHP version: 7.4

**Comment by williamhibberd** [comment]
I'm getting a `Undefined offset: 1` error after updating to commerce 3.3.2 more info here: https://github.com/craftcms/cms/issues/5525#issuecomment-849556294

Does this have something to do with this fix?

**Comment by nfourtythree** [comment]
Hi @williamhibberd 

This is likely to do with this issue: https://github.com/craftcms/commerce/issues/2163 (steps to help in [this comment](https://github.com/craftcms/commerce/issues/2163#issuecomment-849441202)) and is something we are aware of and fixing via: https://github.com/craftcms/commerce/pull/2161

Thanks
