### ISSUE TITLE
Http\Adapter\Guzzle6\Client' not found 

### ISSUE THREAD

**Issue by pepsDev** [craftcms/commerce#2124]
**Description**
Can't open Orders in CP after upgrading the Mollie-Plugin craftcms/commerce-mollie 3.0.

**Error**
`Class 'Http\Adapter\Guzzle6\Client' not found`

**Additional info**
Craft version: 3.6.12
Commerce version: 3.3.0
PHP version: 7.4.18

**Comment by lukeholder** [comment]
Duplicate of https://github.com/craftcms/commerce-mollie/issues/35

Responding there.
