### ISSUE TITLE
Removing qty on lineitem results in TypeError

### ISSUE THREAD

**Issue by joostwaaijer** [craftcms/commerce#2125]
**Description**
When removing the qty on a lineItem and saving the cart, you'll get a TypeError Unsupported operand type.

**To Reproduce**
How, and what happened?
1. Add any product to the cart
2. Go to cart
3. Leave qty blank
4. Submit an update cart request

**Expected behavior**
LineItem should be removed when the qty value is empty or set the qty to 0.

**Additional info**
- Craft version: 3.6.13
- Commerce version: 3.3.1
- PHP version: 8.0.6
- Database driver & version: Postgres 12.6
- Other Plugins & versions:

**Comment by pdaleramirez** [comment]
@joostwaaijer Thank you for reporting this bug. This bug only occurs on PHP 8. I created a PR for the fix you can track it here #2131

**Comment by joostwaaijer** [comment]
Thanks!

**Comment by lukeholder** [comment]
This has been fixed in 3.3.2 that has been released. Thanks.
