### ISSUE TITLE
Enable/Disable Feature for Countries and States

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#213]
> Created by: Bryan Garrant ([info@garrant.com](info@garrant.com)) on 2016/06/08 00:39:31 +0000
Votes at time of UserVoice import: 3

------
It would be great if Commerce would allow you to enable/disable Countries and States in the Control Panel. Some clients only ship to limites countries and some only ship to a few states (heavy weight sales items). This way if a client wanted to expand in the future they could just enable the country or state.  needed.

**Comment by nfourtythree** [comment]
Closed by #1181
