### ISSUE TITLE
Address state cannot be changed in the admin panel

### ISSUE THREAD

**Issue by paweltatarczuk** [craftcms/commerce#2136]
**Description**
Changing the address state does nothing.

**To Reproduce**
How, and what happened?
1. `Place an order with a shipping address to New Zealand and "State" filled`
1. `In the CP enter the previously created order page`
2. `Press "Edit"`
3. `Choose "Edit Address" next to the "Shipping Address"`
4. `Change "State" to a different value`
5. `"State" remains unchanged.`

**Expected behavior**
State should be updated on the address.

**Additional info**
- Craft version: 3.6.14 / 3.5.19.1
- Commerce version:  3.3.1.1 / 3.2.14.1
- PHP version: 7.3.26
- Database driver & version: MySQL 8.0
- Other Plugins & versions: -

**Additional context**
This happens on a clean Craft + Commerce install and on the real website.

**Comment by nfourtythree** [comment]
Hi @paweltatarczuk 

Thank you for bringing this to our attention. We have pushed a fix for this which will be included in the next release of Commerce.

Thanks!
