### ISSUE TITLE
Unable to validate newly created Product

### ISSUE THREAD

**Issue by francoislevesque** [craftcms/commerce#2138]
**Description**
Unable to validate newly created Product

**To Reproduce**

Run the following code using the latest Craft CMS / Craft Commerce versions

```php
$commerce = Commerce::getInstance();
$artworkType = $commerce->getProductTypes()->getProductTypeByHandle('artwork');

// Create/Get product
$product = new Product();
$product->enabled = false;
$product->title = 'test';
$product->typeId = $artworkType->id;

$variant = new Variant();
$variant->title = 'variant';
$product->setVariants([$variant]);

$product->validate();
```

It throws the following error:

```
Return value of craft\\commerce\\elements\\Variant::getShippingCategoryId() must be of the type int, null returned
```

**Expected behavior**
The validation should work and return `true` or `false`.

**Additional info**
- Craft version: 3.6.14
- Commerce version: 3.3.1.1
- PHP version: 7.4.13
- Database driver & version: MySQL 8.0.23
- Other Plugins & versions: -

**Comment by lukeholder** [comment]
This has been fixed for the next release, in that the default category will be returned if no category is set. 

In the meantime, simply assigned a shipping and tax category when making products programatically:

```php
$product = new Product();
$product->enabled = false;
$product->title = 'test';
$product->typeId = $artworkType->id;
$product->shippingCategoryId = Plugin::getInstance()->getShippingCategories()->getDefaultShippingCategory()->id;
$product->taxCategoryId = Plugin::getInstance()->getTaxCategories()->getDefaultTaxCategory()->id;
```

**Comment by nfourtythree** [comment]
This has been fixed in https://github.com/craftcms/commerce/releases/tag/3.3.3

**Comment by francoislevesque** [comment]
This issue doesn’t appear to be fully fixed. We get the following error :Notice: Undefined variable: shippingCategory Probably due to this line : Witify IncFrançois Lévesque, B.Eng MScA,Partenaire ***@***.***(438) 403-9972 333 sherbrooke Est, suite 705,H2X4E3, ***@***.***  De : Nathaniel HammondEnvoyé le :1 juin 2021 14:06À : craftcms/commerceCc : François Lévesque; AuthorObjet :Re: [craftcms/commerce] Unable to validate newly created Product (#2138) This has been fixed in https://github.com/craftcms/commerce/releases/tag/3.3.3—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
