### ISSUE TITLE
DefineAttributeKeywordsEvent not triggered for 'sku'

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#2142]
When dealing with the `sku` attribute it is never hitting the parent `getSearchKeywords()` method and as such the `DefineAttributeKeywordsEvent` is never triggered for this attribute:

https://github.com/craftcms/commerce/blob/6be10645d4d9c33bf6eb6511fa42d2fb4a55cd10/src/elements/Product.php#L698

**Comment by lukeholder** [comment]
Thanks, this has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#a81ccef7432e9a04e2f0a774614753d1d435b245",
  "...": "..."
}
```

Then run `composer update`.

**Comment by nfourtythree** [comment]
This has been fixed in https://github.com/craftcms/commerce/releases/tag/3.3.3
