### ISSUE TITLE
Relationship between purchasable and sale persists after it has been removed

### ISSUE THREAD

**Issue by tigerchick** [craftcms/commerce#2143]
**Description**
If I assign a sale to a purchasable or a purchasable category (either through the product entry > variant > related sales field or the promotions > sales entries) , this relationship seems to persist after it has been removed again.

**Expected behavior**
Once a purchasable or category relationship has been been removed, that sale should no longer apply to the purchasable - but it does.

**Additional info**
- Craft version: Craft CMS 3.6.15
- Commerce version:  3.3.2
- PHP version: 7.3.28
--

**Additional context**
By way of example, if I relate "Spring Sale" to a purchasable, `product.defaultVariant.onSale`  correctly equals 1.
and `product.defaultVariant.salePrice` correctly shows me the sale price.
If I then take that relationship away by removing the purchasable from matching items in the sale or from within the product entry form, `product.defaultVariant.onSale`  incorrectly equals 1 and `product.defaultVariant.salePrice` incorrectly shows me the sale price as if I had "Spring Sale" still related.

**Comment by pdaleramirez** [comment]
@tigerchick This the correct behavior as you can see on the description of the Matching items -> Product Variant (Purchasable). It says "Leave all purchasable fields blank for any purchasable.". It will apply the sale to all products. If you want to not apply the sale, you can change the status of the sale by disabling it.
