### ISSUE TITLE
Cannot uncheck variants on add all to sale

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce#2146]
**Description**
When I click the `add all to sale` button.
<img width="296" alt="Screenshot 2021-05-21 at 09 20 15" src="https://user-images.githubusercontent.com/5698596/119105974-c2c98b80-ba15-11eb-9f55-893854973b39.png">

I get the overlay with the variants checked. However, I am unable to uncheck these variants.
Is this intended behaviour or a bug? I can't see the logic to not allowing which variants can/cannot be selected so perhaps this should allow you to check/uncheck each variant you want to add to a sale.

<img width="1269" alt="Screenshot 2021-05-21 at 09 16 37" src="https://user-images.githubusercontent.com/5698596/119106118-eab8ef00-ba15-11eb-85fd-2b96db9cc599.png">

**To Reproduce**
How, and what happened?
1. Goto a product in the CMS
2. Click `add all to sale` button 
3. Try and uncheck some of the variants

**Expected behaviour**
I expect as these are checkboxes to be able to check/uncheck which variants I want to add to the sale.

**Comment by nfourtythree** [comment]
Hi @terryupton 

Thank you for bringing this to our attention. I have verified that this is indeed a bug and seems to happen when you open the add to sales modal more than once.

We will look at getting this fixed.

Thanks!

**Comment by nfourtythree** [comment]
This has been fixed in https://github.com/craftcms/commerce/releases/tag/3.3.3
