### ISSUE TITLE
Order layout breaks when using template hooks

### ISSUE THREAD

**Issue by NixonGit** [craftcms/commerce#2148]
When adding extra elements using the `cp.commerce.order.edit.order-actions` and `cp.commerce.order.edit.order-secondary-actions` the layout breaks. 

![cp commerce order edit order-secondary-actions](https://user-images.githubusercontent.com/17004710/119313894-f9004880-bc6b-11eb-96f2-b886c2a018e7.png)

![cp commerce order edit order-actions](https://user-images.githubusercontent.com/17004710/119313874-f43b9480-bc6b-11eb-9076-685a7267d749.png)

![mobile](https://user-images.githubusercontent.com/17004710/119313911-fd2c6600-bc6b-11eb-8b69-9cbcb3451bab.png)

**Comment by lukeholder** [comment]
Fixed in Craft Commerce `3.4-beta.1`
