### ISSUE TITLE
No Error Handling for a Null Conversion Rate in Payment Currency

### ISSUE THREAD

**Issue by wooge** [craftcms/commerce#2149]
**Description**
In Store Settings -> Payment Currencies, when adding a new non-default Payment Currency, where the Conversion Rate is left blank, when you hit Save, you get a YII error instead of a Craft CMS error.
 
**Expected Behavior**
Craft CMS should probably provide the error.

**Additional info**
- Craft version: 3.6.15
- Commerce version: 3.3.2
- PHP version: 7.4 (Nitro)
- Database driver & version: (Maria / Nitro)

<img width="1361" alt="Screen Shot 2021-05-25 at 12 12 15 AM" src="https://user-images.githubusercontent.com/3161182/119438420-268dd600-bcee-11eb-8705-fa6b1f8ac025.png">

**Comment by lukeholder** [comment]
Thanks this has been fixed for the next release due out next week.
