### ISSUE TITLE
Support partial refunds and partial payments

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#215]
> Created by: Jeremy Daalder ([jd@imagescience.com.au](jd@imagescience.com.au)) on 2016/06/01 06:56:47 +0000
Votes at time of UserVoice import: 42

------
It would be very handy if Commerce's CP methodfs for doing refunds and payments could be extended to support partial amounts.

This allows you to do things like e.g. refund shipping on an order without having to visit your payment provider.

**Comment by andris-sevcenko** [comment]
> Created by: Stefan Arnold ([outline4000@gmail.com](outline4000@gmail.com)) on 2017/06/07 21:47:27 +0000


------
+1

**Comment by andris-sevcenko** [comment]
> Created by: Mark Reckard ([mark@milesherndon.com](mark@milesherndon.com)) on 2017/07/25 19:34:46 +0000


------
+1

**Comment by andris-sevcenko** [comment]
> Created by: Anonymous ([james@redskystudios.co.uk](james@redskystudios.co.uk)) on 2017/09/28 16:23:52 +0000


------
A basic functionality and should already be in an ecommerce platform. Businesses who retail online see this as an absolute essential requirement to running a shop. It is quite common for customers to order multiple items or more than one size of an item to see if it fits, then simply return the items they do not want.
Surely this is something that is a an absolute must requirement?
It&#39;s ok giving a partial refund through the psp but how can a business tally up from an admin panel whats been returned and not. Doesn&#39;t seem quite right this is not something that is being worked on with the highest of priorities?

**Comment by andris-sevcenko** [comment]
> Created by: Anonymous ([topsolutionshosting@gmail.com](topsolutionshosting@gmail.com)) on 2017/10/28 18:12:35 +0000


------
It doesn&#39;t make sense this isn&#39;t already a part of Craft Commerce.

**Comment by andris-sevcenko** [comment]
> Created by: Pixelated ([micky@mickykelleher.com](micky@mickykelleher.com)) on 2017/11/07 10:59:27 +0000


------
+1

**Comment by andris-sevcenko** [comment]
> Created by: Anna Brown ([anna@mediagirl.com](anna@mediagirl.com)) on 2017/11/14 00:50:20 +0000


------
I&#39;m getting huge push back from my current client about this functionality being missing.

**Comment by andris-sevcenko** [comment]
> Created by: Bill S. ([billsader1987@gmail.com](billsader1987@gmail.com)) on 2017/12/18 23:53:23 +0000


------
Considering how much is being charged for Commerce on top of a Pro license, it really is inexcusable that this isn&#39;t a default feature.

At the very least address this concern and give us a roadmap

**Comment by lukeholder** [comment]
Partial refunds are now included in Commerce 2.
