### ISSUE TITLE
Payment with disabled gateway should always throw an error when performed from the frontend

### ISSUE THREAD

**Issue by joostwaaijer** [craftcms/commerce#2150]
Currently one of our customers faced the problem that there was a customer that completed an order with a gateway that was disabled for customers. We currently use the `EVENT_BEFORE_PROCESS_PAYMENT` to avoid this issue.

**To Reproduce**
How, and what happened?
1. Create an order in the frontend
2. Proceed to checkout
3. Confirm the order with a gateway that should be disabled on the frontent

**Expected behavior**
Expected an error that tells the customer to chose a different payment gayeway

**Additional info**
- Craft version: 3.5.19.1
- Commerce version: 3.2.17.4
- PHP version: 7.4.19
- Database driver & version: PostgreSQL 12.6

**Comment by lukeholder** [comment]
Thanks this has been fixed for the next release.
