### ISSUE TITLE
Option to disable email queue and send all emails immediatly

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#2157]
There are some situations awhen this might be useful, for example if our queue is periodically filled with jobs that take a long time to finish and emails are delayed due to it.

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Thanks for creating this feature request.

While we consider how/if we implement something like this you are actually able to set the priority for the `SendEmail` job. That can be done by using `EVENT_BEFORE_PUSH` in a custom module.

Here is the example code on how that works:

```php
use craft\commerce\queue\jobs\SendEmail;
use yii\queue\PushEvent;
use yii\queue\Queue;
...

Event::on(Queue::class, Queue::EVENT_BEFORE_PUSH, function(PushEvent $event) {
    if ($event->job instanceof SendEmail) {
        $event->priority = 99;
    }
});
```

By default Craft/Commerce jobs are created with a priority of `2048`.

Hope this helps for now, thanks!

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Just a further update, we have PR ready for `3.4` that automatically add the `SendEmail` job to the queue with a high priority https://github.com/craftcms/commerce/pull/2218

This should help to force these jobs to happen first.

Thanks.
