### ISSUE TITLE
"New product" button missing on Commerce 3.3.2

### ISSUE THREAD

**Issue by CMeldgaard** [craftcms/commerce#2159]
**Description**
When going to the product interface under "Commerce", there is no "New product" button. If i downgrade to version 3.3.1 the button returns

**To Reproduce**
How, and what happened?
1. Install Commerce 3.3.2
2. Go to products overview
3. No "New product" button

**Additional info**
- Craft version: 3.16.15
- Commerce version: 3.3.2
- PHP version: 7.4
- Other Plugins & versions:

**Comment by pdaleramirez** [comment]
@CMeldgaard I couldn't replicate the issue. There were no template changes and hooks added on 3.3.2 version.

**Comment by CMeldgaard** [comment]
@pdaleramirez it was a caching issue - i tried everything, and the last one was to clear all the caches in the system, which fixed it.
