### ISSUE TITLE
PHP Error in stats if mysql timezones are not installed/imported

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/commerce#2163]
It seems that this commit has broken our installation:
https://github.com/craftcms/commerce/commit/6b277e9b29386cdb14a5e96e184a1e00e5970e92

PHP Notice – yii\base\ErrorException
Undefined offset: 1
1. in /Users/lenvanessen/Projects/xxx/vendor/craftcms/commerce/src/widgets/TotalRevenue.phpat line 140
131132133134135136137138139140141142143144145146147148149 
        if (empty($stats)) {
            // TODO no stats available message
            return '';
        }
 
        $labels = ArrayHelper::getColumn($stats, 'datekey', false);
        if ($this->_stat->getDateRangeInterval() == 'month') {
            $labels = array_map(static function($label) {
                list($year, $month) = explode('-', $label);
                $month = $month < 10 ? '0' . $month : $month;
                return implode('-', [$year, $month, '01']);
            }, $labels);
        } else if ($this->_stat->getDateRangeInterval() == 'week') {
            $labels = array_map(static function($label) {
                $year = substr($label, 0, 4);
                $week = substr($label, -2);
                return $year . 'W' . $week;
            }, $labels);

**Comment by nfourtythree** [comment]
Hi @lenvanessen 

Thank you for reporting this. This is something we are aware of and have a fix in progress for: https://github.com/craftcms/commerce/pull/2161

The issue we have identified is with projects using MySQL/MariaDB engine for the databases. Is this the case for you?

It is a situation where not all server operating distributions have timezones installed in the `mysql` database.

The fix will have a fallback to support if these are not installed but we will be recommending that people install/import them in the future.

It is a simple process to get the timezones installed/import and only takes a few seconds. This will get the project back up and running quickly.

Documentation on how to do that can be found here:

- [MariaDB docs](https://mariadb.com/kb/en/time-zones/#mysql-time-zone-tables)
- [MySQL docs](https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html#time-zone-installation)

Obviously, on top of that, we are looking to get the fix sorted asap.

**Comment by nfourtythree** [comment]
This has been fixed in https://github.com/craftcms/commerce/releases/tag/3.3.3
