### ISSUE TITLE
Add ordering/sorting products by sku in the control panel

### ISSUE THREAD

**Issue by sparkalow** [craftcms/commerce#2167]
**What are you trying to do?**
I'd like to be able to order/sort the list of products in the control panel by sku.

**What's your proposed solution?**
The "SKU" field can be added to the columns in the data grid. I propose ordering the data grid by the "SKU" column when clicked similar to other fields like "Title".

**Comment by nfourtythree** [comment]
Hi @sparkalow 

Thank you for your feature request. We have made an update that will include this functionality in the upcoming next release of Commerce. You will have the ability to sort the products index page by their default SKU.

Thanks.

**Comment by nfourtythree** [comment]
This was added in https://github.com/craftcms/commerce/releases/tag/3.3.3
