### ISSUE TITLE
Extra queries when getting line item adjustments

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#2171]
We are getting a bunch of extra queries when querying for line item adjustments, the line item is retrieved even when its's not needed where `$hasLineItemId` is `true` and when a line item have previously been saved with it's `$this->id` set:

https://github.com/craftcms/commerce/blob/e748b711fcf2d61eec17891d95f1820c423b2e9e/src/models/LineItem.php#L768

NB. I'm not sure how much of a performance impact this will have, as line items / queries may be cached anyway? but in my example the query total dropped around 30%

**Comment by pdaleramirez** [comment]
@samhibberd I don't think that query is expensive cause it will only query the items related to the adjustment. The reason why It load many queries cause it will get all line items in your order. They query would depends how many items you have in the cart or order. I don't see a way to modify the query and improve the performance.

**Comment by samhibberd** [comment]
Thanks @pdaleramirez. Perfect @nfourtythree.
