### ISSUE TITLE
Adding/editing discount - if we set per user limit field as empty, discount cannot be saved

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#2176]
It applies also to other limits like per email.
If field is empty, it should work the same if there was 0 there. 
Also, there is no error message displayed below field, just general error "Couldn’t save discount.".

**Comment by lukeholder** [comment]
Added the validation errors for the next release. We are not going to assume blank means the author intended to type 0 as it changes the effect of the discount, and we want the author to be aware of the action.
