### ISSUE TITLE
Front End Order Notices 

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#2177]
**Description**
We are in the process of implementing the new notice logic with our front end cart, with the new `PurchasableAvailableEvent` it's just what we need to cover issues that crop up with unavailable items left in a cart.

We are however running into an issue with adding / clearing the notices, and we are not sure if this an error in our implementation / interpretation of docs or something more.

We are primarily working with the `lineItemsRemoved` notice.

Our current process is to recalculate any cart at a template level before displaying it to ensure any items are removed and the notices are added, but the cart is not saved in this state, we don't want to save the cart on every page load or physically remove the items until the customer acknowledges the removal.

```twig
{% if cart and cart.id and not cart.isCompleted %}
	{% do cart.recalculate() %}
{% endif %}
```

We display any notices and provide the link to clear them by hitting up the `update-cart` action with `clearNotices` set.

This is where we run into the issue, as the controller action then loads in the cart in the state before having notices applied and items removed, it is then resaved which actually adds the notices and removes the line items. This means the cart is now saved with items removed and notices set, completing the action again then clears the notices.

It feels like are the options are to:

1) Save the cart on every page load, in case an item is no longer purchasable
2) Write our own custom controller that recalculates and clears notices all in the same action.

Before we start digging deeper, and because this is relatively new feature, we wanted to raise this issue and check we are not missing something and if this is the way the adding / clearing notices process should work?

**Additional info**
- Craft version: 3.6.15
- Commerce version: 3.3.2
- PHP version: 7.4
- Database driver & version: MySQL 8

**Comment by pdaleramirez** [comment]
@samhibberd I think option 2 would be ideal for your use case. Once you got the user's confirmation to update the cart you can call the

```
$this->runAction('update-cart')
$order->clearNotices();
```
Inside your controller action method. That way it will update the cart with recalculation and clear notices at the same time.

**Comment by samhibberd** [comment]
Thanks @pdaleramirez thats cool, thanks for confirming.

It just feels strange that you need to save then clear then resave the order, all good and working though.
