### ISSUE TITLE
Live shipping rates

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#218]
> Created by: Matt Stein ([matt@workingconcept.com](matt@workingconcept.com)) on 2016/04/13 16:12:30 +0000
Votes at time of UserVoice import: 14

------
Use carrier APIs (or services like EasyPost, Shippo) to get real-time shipping rates based on cart/product weight and dimensions.

**Comment by lukeholder** [comment]
This is already possible with a plugin that provides a custom shipping method (or adjuster).
