### ISSUE TITLE
Looks like discount is still applied after discountMatchesLineItem event where isValid is set to false.

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#2180]
**Description**
Looks like discount is still applied after discountMatchesLineItem event where isValid is set to false.

**To Reproduce**
Added a discount code with no restriction and then in our module I've added: 

```
        Event::on(
            Discounts::class,
            Discounts::EVENT_DISCOUNT_MATCHES_LINE_ITEM,
            function(MatchLineItemEvent $event) {

                Craft::info(json_encode($event->lineItem), 'discountLineItem');
                Craft::info(json_encode($event->discount), 'discountLineItem');

                $event->isValid = false;
            }
        );
```
Then added one product to the cart and applied the discount code. I see in the web.log that both `$event-lineItem` and `$event->discount` are there, so it's matching.

**Expected behavior**
Then I would expect that `$event->isValid = false` cancelled this and it therefore shouldn't apply the discount, but it looks like it does. It still gives me the discount and if I look in the `craft_commerce_lineitems` table I see the `subtotal` is the full price, but `total` is price minus discount. 

So do I misinterpret this function or is something wrong?

**Additional info**
- Craft version: 3.5.19.1
- Commerce version: 3.2.17.4
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7

**Additional context**
This one does work if I set `isValid` to false: 
https://craftcms.com/docs/commerce/3.x/extend/events.html#discountmatchesorder
But we only want to exclude some lineitems based on a certain condition for all discountcodes.

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

It would be great if you could send across some screenshots of how you have the discount set up. I tried replicating this a few ways and they worked as expected, I was able to set `isValid` to `false` and not have the discount applied.

The only exception to this was if I didn't add any restriction but had an order level discount. Due to the way we have to reconcile cart financials (including things like taxes) we take an order level discount and spread it across line items ([info in the docs](https://craftcms.com/docs/commerce/3.x/discounts.html#flat-amount-off-order)). This process will not trigger the match line item logic as it is not required in this instance.

Thanks.

**Comment by WHITE-developer** [comment]
Hi @nfourtythree,

Thanks for your reaction.

It is a 'Flat order discount', so if I understand correctly that won't match on line items. Was confused because the lineitems and discount variables are there in the event object, so thought it should be possible to cancel them.

We have this use-case:

Discount coupon: 10 euro

Product A: 20 euro
Product B: 5 euro (discount not allowed)
Product C: 5 euro
Product D: 3 euro

If I order :
- A, B and D then we would still expect a flat 10 euro discount for product A and D
- B, C and D should only apply 8 euro discount for product C and D
- B, of course no discount

Any idea how to accomplish this?

There are the coupon settings:

![Screenshot from 2021-06-02 11-31-42](https://user-images.githubusercontent.com/22771556/120457315-a410b080-c396-11eb-8108-02d8bfaf5df2.png)

No specific settings for Matching items and conditions

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

Thanks for the further information, this helped us understand what was going on.

It did uncover a bug where non-promotable purchasables were able to have order level discounts applied to them. We have just pushed a fix for this which will be included in the next release of Commerce.

In the example you gave, this does mean that you could set "Product B" to be not promotable and the discount will stop being applied. Obviously this would stop other discounts and sales too so might not be fully applicable for your situation.

On that note, I have created a new feature request that would allow you to choose purchasables the would prevent (exclude) order level discounts being spread to them. This would then mean they could still be promotable and take advantage of other sales and discounts.

You can follow that feature request here: #2225

Please add any thoughts or feedback over on that issue and I will close this one for now.

Thanks!
