### ISSUE TITLE
Saving variant manually without stock value returns PDOException

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/commerce#2186]
**Description**
We have a product import script that created products and variants manually e.g. 
```php
$product->setVariants($variants);
if(Craft::$app->getElements()->saveElement($product, false, true, true)) {...
```

We recently updated from commerce 3.2.17.4 to 3.3.3 and now our import is failing when saving variants.

Our system doesn't use stock so we've always just set `hasUnlimitedStock` to true.
However that now seems to through an insert PDOexception because `stock` is being passed as NULL.
The stock field can't be null obviously.

`Integrity constraint violation: 1048 Column 'stock' cannot be null`

I can't see any obvious changes in recent changelogs so I assume this might be an upstream issue?

Note - saving products in the CMS works as expected.

**To Reproduce**
1. create product + variant manually (not via CMS) and set hasUnlimitedStock to true and don't pass stock as 0.
2. save product and variant.

**Expected behavior**
Save the product and variant and set hasUnlimitedStock to true and use the stocks field in the database's default value e.g. 0 (not NULL).

**Additional info**
- Craft version: 3.6.15
- Commerce version: 3.3.3
- PHP version: 7.4
- Database driver & version: mysql 5.7

**Comment by pdaleramirez** [comment]
@mediabeastnz The stock validation is always required. When you run the validate method it will auto set stock to `0` if no value is given. There were no changes on stock validation recently.

To resolve your issue you can submit a stock value of 0 or run validate method before saving the element.

**Comment by mediabeastnz** [comment]
Hmmmm nothing was changed on our import script so we thought the recent updates must have changed how that works.
But yes, we've modified the script now to set stock to 0 as well as hasUnlimitedStock to true and that resolves the issue.
