### ISSUE TITLE
Querying Variants with hasUnlimitedStock

### ISSUE THREAD

**Issue by jerome2710** [craftcms/commerce#2188]
I would like to narrow my Variant-query to exclude any variants that have unlimited stock. This already is a column in the database table, but it cannot be used in the query:

```php
$variants = Variant::find()
            ->hasUnlimitedStock(false)
            ->limit(null)
            ->all();
```

```Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\commerce\elements\db\VariantQuery::hasUnlimitedStock()'```

Of course, it would be possible to skip these variants after the query. However, our collection of products is increasing rapidly and I would like to prevent these from being loaded at all.

**Comment by lukeholder** [comment]
This has been completed, and will be in the next release due out next week.
