### ISSUE TITLE
Save new product as a draft

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#219]
> Created by: Anonymous ([andy@brink.uk](andy@brink.uk)) on 2016/03/15 18:41:10 +0000
Votes at time of UserVoice import: 4

------
When entering new products allow 'save as a draft' which saves progress without the need to complete all required fields. This would be most helpful!

**Comment by lukeholder** [comment]
Duplicate of https://github.com/craftcms/commerce/issues/1137
