### ISSUE TITLE
Prevent empty `commerce.yaml` file being created on project config rebuild events

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#2194]
Running `./craft project-config/rebuild` will generate an empty `commerce.yaml` file. Then, when saving anything (not even Commerce related) the blank file will be deleted.

See https://github.com/craftcms/commerce/pull/2192 for a fix.

**Additional info**
- Craft version: 3.6.16
- Commerce version: 3.3.3
- PHP version: 7.2.33

**Comment by lukeholder** [comment]
Thanks. Fixed for the next release.
