### ISSUE TITLE
Adding items to cart with commerce/cart/update-cart - qty not validated

### ISSUE THREAD

**Issue by i-just** [craftcms/commerce#2197]
When adding variants to cart with commerce/cart/update-cart the qty is not validated against the maximum qty. When I use the same method (commerce/cart/update-cart) to update the variant that's already in the cart then the maxQty validation kicks in as expected. Can you please advise if there's a trick I'm missing or is this a bug?

The relevant parts of the form are:
```
<form method="POST">
    {{ csrfInput() }}
    <input type="hidden" name="action" value="commerce/cart/update-cart">
    <select id="variation" name="purchasableId">
        {% for variant in product.variants %}
            <option value="{{ variant.id }}" {% if variant.stock <= 0 and variant.hasUnlimitedStock == false %}disabled{% endif %}>
                {{ variant.title }} - {{ macro.displayPrice(variant, cart) }}
            </option>
        {% endfor %}
    </select>
    <select id="qty" name="qty">
        {% for i in 1..10 %}
             <option value={{ i }}>{{ i }}</option>
        {% endfor %}
    </select>
</form>
```
I have also tried the approach listed in example templates (with purchasables[][id] and puchasables[][qty] but that also seems to not be validated against maxQty.

Craft Pro 3.6.16
Craft Commerce Pro 3.3.3
PHP 7.4.19
MySQL 5.5

**Comment by nfourtythree** [comment]
Hi @i-just 

On the latest version of Commerce, I tested the example templates and your example code.

In both situations things worked as expected. I set a variant's max allowed qty to 2 and tried to add 3. Each time I received an error from Commerce.

Could you try checking this again and see if you are still having an issue.

Thanks.

**Comment by i-just** [comment]
Hi @nfourtythree 

Thanks for looking into this. Long story short, I was having this problem: [https://github.com/craftcms/commerce/issues/714](https://github.com/craftcms/commerce/issues/714). All clear now. 

Thank again for checking!
