### ISSUE TITLE
Empty price field on new product - TypeError instead of the required warning - PHP 8

### ISSUE THREAD

**Issue by ianreidlangevin** [craftcms/commerce#2198]
**Description**
Hi guys ! Only with PHP 8 -> In Products > New product -> When adding a new product, if the price field is empty, the "required price" warning is not showing. Instead, a TypeError is shown. See screenshot below. 
The issue appears only when using PHP 8. It happens only with new product, if I delete the price on an existing product and try to save, no problem, the warning is shown.

**To Reproduce**
How, and what happened?
1. Use PHP 8
2. Add a new product without setting a price (empty required price field) and save

**Expected behavior**
A red warning is shown around the required price field.

**Additional info**
- Craft version: 3.6.16
- Commerce version:  3.3.3
- PHP version: 8.0.0
- Database driver & version: MySQL 5.7.32
- Other Plugins & versions: Amazon S3 1.2.11, Redactor 2.8.7, Stripe for Craft Commerce 2.3.2.1

Thanks a lot for investigating! Have a nice day.

<img width="1425" alt="Capture d’écran, le 2021-06-09 à 10 10 29" src="https://user-images.githubusercontent.com/85630027/121374209-b4cca380-c90d-11eb-9c78-2a5b5e2b1a23.png">

**Comment by pdaleramirez** [comment]
I couldn't replicate this on Commerce 3.3.3 with PHP 8. Have you tested this disabling other plugins and modules and see if that resolves the issue?

**Comment by ianreidlangevin** [comment]
Hi Dale, thanks for the reply. I investigated a little more this morning with a brand new installation (Craft and Commerce, same versions). It appears to come from the Automatic SKU Format. Sorry for misleading you. If I don't enter any value in the Automatic SKU Format field (in system settings / product types), everything is good, the warning is shown as supposed. If I enter {product.slug} for example or {{ product.slug }}-{{ seq(product.slug) }}, the typeError is back. Hope this help, thanks again for your help.

**Comment by lukeholder** [comment]
This will be fixed in the next release. Thanks.

**Comment by brandonkelly** [comment]
Commerce 3.3.5 is out now with the fix for this. Thanks for reporting!
