### ISSUE TITLE
Edit email address of guest customer in order

### ISSUE THREAD

**Issue by timeverts** [craftcms/commerce#2203]
**What are you trying to do?**
If a customer checks out as a guest and they enters their email address incorrectly, they will not receive any automated emails associated with that order. As an administrator, I want to be able to edit the email address attached to the guest customer (or order) from the CMS. Then I can use the existing 'Resend Email' functionality to resend the relevant email(s) for that order to the customer.

Right now it seems like the only way to achieve this is to edit the relevant order, delete the (guest) customer and recreate them with the correct email address. But I'm not sure if this process has any other side affects when all I am really wanting to do is update the email address of the customer (e.g. particularly cause when recreating the customer the order gets recalculated).

**What's your proposed solution?**
Make it possible to simply edit the email address of a guest customer for an order.

**Comment by pdaleramirez** [comment]
Duplicate issue https://github.com/craftcms/commerce/issues/1861
