### ISSUE TITLE
Design – Subscription ID overlaps sidebar

### ISSUE THREAD

**Issue by abuerin** [craftcms/commerce#2211]
**Description**
The subscription ID text hash overlaps the sidebar 

`/admin/commerce/subscriptions/{id}`

**Expected behavior**
Possible fixes
```
text-overflow: ellipsis;
overflow: hidden;
```
or
```
hyphens: auto;
```

<img width="1014" alt="Bildschirmfoto 2021-06-16 um 22 13 31" src="https://user-images.githubusercontent.com/85960512/122287184-f69eb080-cef0-11eb-842d-e6078b68542c.png">

**Comment by nfourtythree** [comment]
Hi @abuerin 

Thank you for reporting this. We have pushed a fix that also includes the ability to quickly copy the subscription's reference to your clipboard.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/4gun1GDj/edddfeea-257f-4f42-8cfa-639d9c591737.png?v=7d955b706da61a9578005966f0c65ad5)

This update will be in the next release of Commerce.

Thanks.

**Comment by brandonkelly** [comment]
Commerce 3.3.5 is out now with the fix for this. Thanks for reporting!

**Comment by abuerin** [comment]
Thanks
