### ISSUE TITLE
Exportable orders and customers to CSV/Excel

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#222]
> Created by: Jeremy Timms ([jeztimms@gmail.com](jeztimms@gmail.com)) on 2016/03/09 22:53:30 +0000
Votes at time of UserVoice import: 30

------
As the title says, button with data ranges to export customer data and order data to CSV. Mostly for marketing and of course, accounts. Very very important indeed. Standard stuff.

**Comment by andris-sevcenko** [comment]
> Created by: idol chan ([idolchan@gmyle.com](idolchan@gmyle.com)) on 2016/04/25 03:41:17 +0000


------
Quick ways to export customer / order data is almost a basic requirement for a success ecommerce app.

**Comment by andris-sevcenko** [comment]
> Created by: Matt Murtaugh ([hello@mattmurtaugh.com](hello@mattmurtaugh.com)) on 2017/05/06 04:06:11 +0000


------
This is the only thing that is keeping me from migrating one of my stores over to Craft Commerce. Being able to export an order with the billing and shipping address is essential. 

The large # of orders we receive make it much easier for us to export orders from our current store, format them and then print them on labels.

If this was a feature of Craft Commerce, I would without a doubt switch my store over. Unfortunately, I rely too heavily on this functionality now to do so.

**Comment by missmatsuko** [comment]
In the meantime, you may be able to use the Sprout Reports plugin:
https://sprout.barrelstrengthdesign.com/craft-plugins/reports

**Comment by lukeholder** [comment]
You can exports orders from the order index screen.

**Comment by rob-baker-ar** [comment]
Exported orders in CSV format (even in "expanded" mode) do not have address details in separate columns.

JSON / XML expanded exports do have the address detail. Unfortunately, we need an export file that can easily be opened in Excel by non-developer people.

So, I added this: #2007

**Comment by icreatestuff** [comment]
It looks like this is still a problem unless I'm missing something. Neither the Raw, Expanded or Order (Legacy) export options from the orders index screen will provide individual columns for the shipping and billing address fields.

Craft 4.3.6.1
Commerce 4.2.4

**Comment by terryupton** [comment]
What is the status of this? I have a customer with the same issue.
It wasn't clear if this was solved and merged as part of this comment? <https://github.com/craftcms/commerce/issues/222#issuecomment-780477280>

Customer is currently on Craft 3 and Commerce 3.
