### ISSUE TITLE
Change base currency after fresh installation: Rate cannot be blank.

### ISSUE THREAD

**Issue by cfelbertp** [craftcms/commerce#2221]
**Description**
After installing Craft CMS and the Commerce plugin (Pro) I tried to change the Base currency from USD to EUR. I clicked USD and selected EUR in the Dropdown. The conversion rate field showed "1" but was disabled. When I tried to save, the error **"Rate cannot be blank."** was shown.

I have no items in the cart and never submitted an order.

**To Reproduce**
How, and what happened?
1. CP menu Commerce
2. Store Settings
3. Payment Currency

**Expected behavior**
Currency changes to EUR.

**Additional info**
- Craft version: 3.6.17
- Commerce version: 3.3.4.1
- PHP version: 7.4
- Database driver & version: 
- Other Plugins & versions: no other plugins
- Nitro: 2.0.7

**Comment by javangriff** [comment]
I also ran into this issue on new Commerce site running Commerce 3.3.4.1 on Craft CMS 3.6.17.

**Comment by lukeholder** [comment]
This has been fixed for the next release due out soon.

**Comment by brandonkelly** [comment]
Commerce 3.3.5 is out now with the fix for this. Thanks for reporting!
