### ISSUE TITLE
Customer addresses missing after creating cp order

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#2224]
After creating a cp order (for an email that is not a user). If i then go to the customers screen, i can see that customer with the order address as the primary billing and shipping, but the number of address show 0. If i view that customer, then it shows no addresses.

commerce version: 3.3.4.1

**Comment by samuelbirch** [comment]
just checked the db, and it seems the commerce_customers_addresses table is not being populated.

**Comment by brandonkelly** [comment]
Commerce 3.3.5 is out now with the fix for this. Thanks for reporting!

**Comment by samuelbirch** [comment]
Is there a migration to fix existing customers with this issue or is it only for new customers?
