### ISSUE TITLE
Obey cancelUrl in CartPaymentController::actionPay()

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#223]
> Created by: Sjoerd Adema ([sjoerd@triz.nu](sjoerd@triz.nu)) on 2016/02/27 20:46:57 +0000
Votes at time of UserVoice import: 1

------
When the action can't be completed due to missing parameters (e.g. no email address attached to order) it redirect to the current page. Would be better to redirect to the cancelUrl (which is the current page by default anyways) so we can use custom templates & actions to process payments. Also, it would be cool if there is a flash message set on that particular error (no email).

**Comment by lukeholder** [comment]
Cancel url is for when the customer cancels the payment in an offsite payment page.
