### ISSUE TITLE
Add an index for the isStoreLocation column on commerce_addresses table

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/commerce#2238]
**What are you trying to do?**

- We have +300k addresses in our database. 
- We're using a custom tax and shipping adjuster. 
- We use our store location address to calculate shipping and tax prior to checkout (before the customer enters their own address).

We were finding that updating the cart could take +6s to complete but once we got into the checkout process, where true addresses are entered and used, that update time would drop to ~800ms.

**What's your proposed solution?**
We added an index for the `isStoreLocation` column on `commerce_addresses` and we now get consistent ~800ms responses regardless of whether we're looking up the store location address or using a customer's address.

**Comment by lukeholder** [comment]
Thanks. Will add memoization dB table index for next 3.4 beta.
