### ISSUE TITLE
Changing primary valuta to something else not working due to disabled state of conversion field

### ISSUE THREAD

**Issue by kevinmu17** [craftcms/commerce#2239]
**Description**
I'm trying to change the payment currency (/commerce/store-settings/paymentcurrencies) to another primary default USD -> EUR but can't save due to errors of the conversion field can't be empty. But this field is disabled.

**To Reproduce**
How, and what happened?
1. In the CP go to commerce > store-settings > paymentcurrencies
2. Change the primary valuta to something else
3. Error thrown about conversion field can not be empty. The field is has a disabled property, but is filled with the value 1. But the disabled property prevents this data from beging send.

**Expected behavior**
The field not being disabled? :)

**Additional info**
- Craft version: 3.6.16
- Commerce version: 3.3.4.1
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.33
- Other Plugins & versions: N/A

**QUICK workaround**
Inspect the input and remove the disabled property from the input, than hit the save button again

**Comment by pdaleramirez** [comment]
@kevinmu17 We'll be releasing fix for this on the next release, You can put this on your composer.json to fix it right away

```json
"require": {
  "craftcms/cms": "dev-develop#32518e7952e6607e931a91dc792fe811cec07c55",
  "...": "..."
}
```

PR: https://github.com/craftcms/commerce/pull/2227/files
