### ISSUE TITLE
Re-order Countries

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#224]
> Created by: Sjoerd Adema ([sjoerd@triz.nu](sjoerd@triz.nu)) on 2016/02/27 20:44:01 +0000
Votes at time of UserVoice import: 2

------
Would be great if we could order shipping countries in the CP. Now they're ordered on primary key but a custom ordering can be handy when you want to default a certain shipping country (e.g. i want Nethernlands to be default but Belgium comes higher in the list)

**Comment by vonscriptor** [comment]
This doesn't appear to be working for me in **Craft Commerce Lite v2.2.13**.

I moved United States to the top of the list and it notified me that the countries were reordered, but I see no change on the **shop/checkout/addresses** template example.

`{% for key, option in countries %}
                            {% set optionValue = (model ? model.countryId : '') %}
                            <option value="{{ key }}" {% if key == optionValue %} selected{% endif %}>{{ option }}</option>
                        {% endfor %}`
