### ISSUE TITLE
undefined customer dropdown in cp new order

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#2247]
commerce 3.3.5

unable to create cp order because the customer dropdown is undefined

![Screenshot 2021-07-07 at 10 26 26](https://user-images.githubusercontent.com/13586/124736211-affc0f00-df0e-11eb-8579-7fd3e71aac80.png)

shipping method is also undefined.

the previous version does not have this issue.

**Comment by pdaleramirez** [comment]
Fixed on version 3.3.5.1
