### ISSUE TITLE
Let payment methods depend on chosen shipping method

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#225]
> Created by: Paul Verheul ([paul@nilsenpaul.nl](paul@nilsenpaul.nl)) on 2016/02/25 14:05:28 +0000
Votes at time of UserVoice import: 1

------
Say, I have a store where my customers can pick up their order. I want the payment method 'pay in store' to be available only if my customer has selected 'pickup in store' as a shipping method.

**Comment by lukeholder** [comment]
This is up to the developer to implement. Either through templates or hooking into order validation.
