### ISSUE TITLE
Variant Positioning

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce#2250]
**What are you trying to do?**
I'd like to be able to position variants when inserting/updating via Feed Me.

Currently there doesn't seem to be a way to specify the position.

**What's your proposed solution?**
A position value that can be adjusted.  The product variant API for shopify has `position` accessible.

![image](https://user-images.githubusercontent.com/744385/124795740-3875b200-df05-11eb-9a9f-c5040e3c2334.png)

Thanks!

**Comment by lukeholder** [comment]
Duplicate of https://github.com/craftcms/feed-me/issues/708

Will track there.
