### ISSUE TITLE
Add a price adjuster for payment methods

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#226]
> Created by: Paul Verheul ([paul@nilsenpaul.nl](paul@nilsenpaul.nl)) on 2016/02/25 14:03:10 +0000
Votes at time of UserVoice import: 3

------
Some of our customers choose to let their customers pay a small fee, depending on the payment method they choose. Would love it if this could be a setting for the individual payment methods. Even better: make it possible to let this be a percentage of the total order amount (so you can let customers pay your PayPal fee).

**Comment by alexstojda** [comment]
This would be awesome!
