### ISSUE TITLE
Variants defineSortableAttributes should allow plugins to modify the attributes

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#227]
> Created by: Marion Newlevant ([marion.newlevant@gmail.com](marion.newlevant@gmail.com)) on 2016/02/23 21:26:13 +0000
Votes at time of UserVoice import: 1

------
commerce/elementtypes/Commerce_VariantElementType.php function defineSortableAttributes doesn't have the hook to allow plugins to modify the attribues (Orders and Products do)

**Comment by lukeholder** [comment]
This can now happen in the  `craft\cms\services\Elements::EVENT_REGISTER_SORT_OPTIONS`.
