### ISSUE TITLE
🐛 3.4 Broke a few things

### ISSUE THREAD

**Issue by OwenMelbz** [craftcms/commerce#2270]
**Description**
We've just updated to 3.4 and noticed the order screen has gone a bit wonky - easiest way to show is this initial screenshot of before and after so... before....

![image](https://user-images.githubusercontent.com/1094740/125603991-7c918663-9a16-4c24-9329-55aa90958a44.png)

and after:

![image](https://user-images.githubusercontent.com/1094740/125604048-e4add29d-d3b0-48a2-8a98-8a3d292a8a95.png)

Missing a bunch of buttons, and got some extra buttons.

**To Reproduce**
How, and what happened?
1. Updated to 3.4

**Expected behavior**
Same buttons as previously

**Additional info**
- Craft version: Craft Pro 3.7.0
- Commerce version: 3.4.0
- PHP version: 7.4.20
- Database driver & version: MySQL 8.0.25
- Other Plugins & versions:
Advance Link Field	1.1.4
CMS Guide	2.0.5
CP Field Inspect	1.2.5
Craft Commerce	3.4.0
Field Manager	2.2.4
Mailgun	1.4.3
MatrixMate	1.2.7
Navigation	1.4.19
PayPal Checkout for Craft Commerce	1.2.2
Redactor	2.8.7
Redactor Anchors	1.1.0
SEO	3.3.44
Stripe for Craft Commerce	2.3.2.1
Super Table	2.6.8
Table Maker	2.0.1

**Comment by nfourtythree** [comment]
Hi @OwenMelbz 

Thank you for bringing this to our attention. We have pushed up a fix and will look to get a release out for this asap.

Thanks!

**Comment by brandonkelly** [comment]
Commerce 3.4.0.1 is out now with the fix. Thanks again for reporting!
