### ISSUE TITLE
bug with getting orders by orderSiteId

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#2272]
OrderQuery.php

`if ($this->orderSiteId) {
            $this->subQuery->andWhere(Db::parseParam('commerce_orders.orderSiteId', $this->orderStatusId));
        }`

should be:

`if ($this->orderSiteId) {
            $this->subQuery->andWhere(Db::parseParam('commerce_orders.orderSiteId', $this->orderSiteId));
        }`

**Comment by samuelbirch** [comment]
also:

`if ($this->orderLanguage) {
            $this->subQuery->andWhere(Db::parseParam('commerce_orders.orderLanguage', $this->orderStatusId));
        }`

should be:

`if ($this->orderLanguage) {
            $this->subQuery->andWhere(Db::parseParam('commerce_orders.orderLanguage', $this->orderLanguage));
        }`

**Comment by brandonkelly** [comment]
Thanks for reporting these! We just released Commerce 3.4.0.1 with fixes for them.

The fixes are also available on the `3.3` branch if you’re not ready to update to Craft 3.7 + Commerce 3.4 yet. To update to the latest commit of the `3.4` branch, change your `craftcms/commerce` requirement in `composer.json` to:

```json
"craftcms/commerce": "3.3.x-dev as 3.3.5.1"
```

Then run `composer update`.
