### ISSUE TITLE
3.4 changes to getAvailableShippingMethodOptions - custom shipping method no longer included

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/commerce#2273]
**Description**
Our custom shipping method is no longer being included in `cart.getAvailableShippingMethodOptions`.

https://github.com/craftcms/commerce/blob/develop/src/elements/Order.php#L1841

`$availableMethods` does include our custom shipping method. `$methods` doesn't (because that looks for shipping methods in the database), so the code in the subsequent for loop never runs.

Is this a bug or a change to how custom shipping methods are handled?

**Comment by pdaleramirez** [comment]
@jamiepittock The change for the shipping method object is that `dateCreated` and `dateUpdated` properties has been added. Does you custom code affect that change?

**Comment by jamiepittock** [comment]
@pdaleramirez I think it's the changes in this commit - f307ccfa78b9bafce8421ee52c9b99159d483a74

**Comment by pdaleramirez** [comment]
@jamiepittock I think I know the line that caused the issue. We'll resolve it.

**Comment by pierrestoffe** [comment]
@pdaleramirez @lukeholder Unless a fix is planned for today/tomorrow would you have a temporary workaround please?

**Comment by lukeholder** [comment]
@pierrestoffe fix will be out very shortly in the next few hours.

**Comment by jamiepittock** [comment]
@lukeholder you're a legend, cheers! Has something related to this also affected how an Order's getShippingMethod() method works? Calling that method doesn't seem to set the least expensive option anymore (if one hasn't already been selected).

**Comment by lukeholder** [comment]
@jamiepittock @pierrestoffe This has been fixed and released in 3.4.0.2 thanks.

**Comment by lukeholder** [comment]
@jamiepittock can you make a new issue for that please. Thanks.

**Comment by jamiepittock** [comment]
@lukeholder done #2276
