### ISSUE TITLE
Error "Setting unknown property: craft\commerce\models\ShippingMethodOption::provider" upon checkout

### ISSUE THREAD

**Issue by bfopma** [craftcms/commerce#2277]
**Description**
We are working on upgrading a Craft Commerce 2 site to Craft Commerce 3. Upon checkout, I'm running into this error:

`Setting unknown property: craft\commerce\models\ShippingMethodOption::provider`

This seems similar to https://github.com/craftcms/commerce/issues/1378 . When looking at getAvailableShippingMethodOptions(), it looks like the code changes added to resolve this issue were changed or removed in Commerce 3.4.0.2. Adding back these changes does seem to resolve the issue I'm experiencing.

Not sure if this is something I'm doing wrong, something that needs to be changed in Postie, or just directly related to the changes in 3.4.0.2 yesterday. Any help is appreciated!

**To Reproduce**
1. Enable UPS shipping method option in Postie
2. Add item to cart
3. Attempt to check out

**Additional info**
Postie: 2.4.8
Commerce version: 3.4.0.2
Craft version: 3.7.3.2
PHP version: 7.4

**Comment by lukeholder** [comment]
Just added a fix which I would love for you to test:

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#d27edbc38c6946462c4fae2bb6d822f4a0690373 as 3.4.0.2",
  "...": "..."
}
```

Then run `composer update`.

Please let me know if that fixes it for you and we will cut a release.

**Comment by bfopma** [comment]
Thank you, @lukeholder . This appears to be working!

Brady

**Comment by lukeholder** [comment]
@bfopma 

You can now restore your composer.json to it's original state and run composer update as `3.4.0.3` is out with this fix.
