### ISSUE TITLE
Invalid Call — Setting read-only property

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#2278]
**Description**
Getting the invalid call exception "Setting read-only property: craft\commerce\models\ShippingMethodOption::type" when navigating to the edit page for a completed order.

**To Reproduce**
1. From the Orders index, click on an order that has been completed.
2. Returns Invalid Call – yii\base\InvalidCallException.

**Additional info**
- Craft version: Pro 3.7.4
- Commerce version: Pro 3.4.0.2
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by bossanova808** [comment]
I just did a test Craft 3.7/Commerce 3.4 upgrade and am seeing this on our shipping page (front end in my case!).

**Comment by lukeholder** [comment]
Fixing this now.

**Comment by lukeholder** [comment]
This was fixed in https://github.com/craftcms/commerce/issues/2277

Cutting a release now.
