### ISSUE TITLE
Duplicate a variant

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#233]
> Created by: Robin Wissink ([info@creativeorange.nl](info@creativeorange.nl)) on 2016/02/18 09:41:21 +0000
Votes at time of UserVoice import: 23

------
When managing a fashion store for example, you have to add a lot of variants for each product (colors, sizes, corresponding images). It would be great to be able to duplicate the first variant, and then for example only change the stock amount. This would greatly improve the experience of craft commerce for shop managers.

**Comment by lukeholder** [comment]
Related: https://github.com/craftcms/cms/issues/862

**Comment by lukeholder** [comment]
Related: #202
