### ISSUE TITLE
Coupon/Discount on Variant rather than product

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#234]
> Created by: Philip Zaengle ([philip@zaengle.com](philip@zaengle.com)) on 2016/02/09 02:14:24 +0000
Votes at time of UserVoice import: 17

------
In some cases store owners will want to give a discount / coupon code on a specific SKU or set of SKUs rather than an entire product.

**Comment by andris-sevcenko** [comment]
> Created by: idol chan ([idolchan@gmyle.com](idolchan@gmyle.com)) on 2016/04/25 04:53:29 +0000


------
Agree. Search by variant&#39;s attributes are important too. Commerce should focus to a variant level.

**Comment by andris-sevcenko** [comment]
> Created by: Terry Upton ([terry@amasci.co.uk](terry@amasci.co.uk)) on 2017/01/12 18:05:06 +0000


------
Yes a big +1 for this from me.

**Comment by andris-sevcenko** [comment]
> Created by: Will Law ([will.law@me.com](will.law@me.com)) on 2017/03/31 15:52:09 +0000


------
This is essential functionality. Need this!

**Comment by lukeholder** [comment]
This is now available in Commerce 2.0
