### ISSUE TITLE
Print multiple invoices/packing slips from dashboard

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#237]
> Created by: Ian Isted ([ian@ianisted.co.uk](ian@ianisted.co.uk)) on 2016/01/22 10:39:00 +0000
Votes at time of UserVoice import: 13

------
The ability to select multiple orders from the Orders screen and print invoices or packing slips would be invaluable to many larger companies.

This would speed up processes for order fulfilment staff.

**Comment by lukeholder** [comment]
See duplicate: #208
