### ISSUE TITLE
Make Plugin name changeable

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#239]
> Created by: Robert Krieg ([hello@robertkrieg.ch](hello@robertkrieg.ch)) on 2016/01/13 08:21:58 +0000
Votes at time of UserVoice import: 5

------
It would be nice if its possible to change the Plugin Name "Commerce" in the CP Navigation.

So people could call it "Shop" "Order Material" "Image Store" or something more meaningful to client CP admins.

The most easy way would be to simply make the Plugin name translatable: Craft::t('Commerce');

This way, you can easily overwrite the name in different translation files.

Thanks, Robert

**Comment by lukeholder** [comment]
This would need to be done by making a commerce general config setting called `pluginName` which defaults to "Commerce". If a developer sets the variable then set the CP nav top level label to the the setting's value.

**Comment by lukeholder** [comment]
Decided to leave this to static translations.

https://docs.craftcms.com/v3/static-translations.html#prep-your-messages

"Commerce" in the nav is already passed through the `|t` filter.
