### ISSUE TITLE
Full Multi-Currency

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#24]
Different primary currency per store?

Full multi-currency prices and system discounts

https://docs.google.com/spreadsheets/d/1amiQvydtxWna6cfEMcSdfeWx7uMY6E-h40oGu5KS6SM/edit

- [ ] Use the money/money library #31 
- [ ] Convert all values to int/string

**Comment by karensg** [comment]
Is there a chance this issue can be included in 3.0 milestone? Asking for a friend..

**Comment by adrienne** [comment]
Just tagging myself for updates because i *need* this functionality for a customer i would like to get switched to Craft.
