### ISSUE TITLE
address title field

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#240]
> Created by: Robert Krieg ([hello@robertkrieg.ch](hello@robertkrieg.ch)) on 2016/01/13 08:19:34 +0000
Votes at time of UserVoice import: 7

------
It would be nice to add a "title" field to the address model.

In german (and probably other languages aswell) you need to know someones gender/title to properly address the person.

A proper german address would e.g. be:

Herr
Max Muster
Teststrasse 17
1234 Testingen

Also, if you want to personally welcome a person in a formal way, it would be:

Sehr geehrter Herr Müller / Sehr geehrte Frau Müller (Dear Mr. Müller / Dear Mrs. Müller)

So I kindly request you to add a non-mandatory title field to the address model.

Thanks, Robert

**Comment by lukeholder** [comment]
This is available in commerce 1 & 2
