### ISSUE TITLE
'Save and Add Another' on the Create Product entry screen

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#243]
> Created by: Robin Hodges ([rob@highpass.co.uk](rob@highpass.co.uk)) on 2015/11/30 15:03:18 +0000
Votes at time of UserVoice import: 8

------
In normal entries, categories etc you can 'Save and Add Another' as well as 'Save and Continue Editing'

Can we have this for Commerce Products?

**Comment by andris-sevcenko** [comment]
> Created by: Anonymous ([ole@railway.no](ole@railway.no)) on 2015/12/07 07:09:12 +0000


------
Yes, please!

Related to craftcms.stackexchange.com/questions/12705/cant-duplicate-a-product-in-craft-commerce/12713

**Comment by andris-sevcenko** [comment]
> Created by: Adam Menczykowski ([adammenczykowski@gmail.com](adammenczykowski@gmail.com)) on 2017/03/20 16:27:03 +0000


------
I&#39;m not seeing this feature in Commerce 1.2.1337. When editing a product, I can only &#39;save&#39; or &#39;save AS a new product&#39;. A third option would be good to have as the original request: &#39;save and ADD another&#39;

**Comment by bartrylant** [comment]
Yes this would be great. Also, a keyboard shortcut for this save action would make it even better.

**Comment by lukeholder** [comment]
Fixed for the next release.
