### ISSUE TITLE
Rename "Title" field

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#244]
> Created by: Bart Rylant ([bart.rylant@gmail.com](bart.rylant@gmail.com)) on 2015/11/07 11:01:42 +0000
Votes at time of UserVoice import: 6

------
It would be nice if we could rename the title field, just like we can with entries. Especially with products (and since we can make products of different types) it would be better if we can say what the title field really should contain.

**Comment by lukeholder** [comment]
Fixed by https://github.com/craftcms/commerce/issues/148
