### ISSUE TITLE
Add data/query support for retrieving all items a particular customer has bought

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#247]
> Created by: Jeremy Daalder ([jd@imagescience.com.au](jd@imagescience.com.au)) on 2015/11/03 07:18:22 +0000
Votes at time of UserVoice import: 2

------
This has uses in creating re-order sheets, but also in reporting etc.

Indeed, keeping track of items purchased & quantities etc (independent of orders as such) - is very useful for stats/tracking in general.

**Comment by lukeholder** [comment]
Moving into #42
