### ISSUE TITLE
Making a variant blueprint

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#248]
> Created by: Bart Rylant ([bart.rylant@gmail.com](bart.rylant@gmail.com)) on 2015/10/10 08:05:15 +0000
Votes at time of UserVoice import: 24

------
Some products have the same variants. It would be nice if there was a way to make a sort of "variant blueprint" per product type. E.g. for t-shirts, you could make a blueprint for XS - S - M - L - XL with some default values filled in (e.g. price). If a product from that product type doesn't need all of the variants, or has something that is not default, you would just have to edit that variant. This would be much faster than adding e.g. 5 variants for every product, over and over again.

**Comment by AugustMiller** [comment]
For anyone coming upon this request: You can create a disabled "Blueprint" product, and duplicate it (`Save as new Product`) whenever you need those values quickly copied over.

**Comment by lukeholder** [comment]
Like @AugustMiller said, you can save as new product to duplicate a product with its variants. 

See also: #233
