### ISSUE TITLE
Order statuses set by payment gateway or actual payment status

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#249]
> Created by: Jeremy Daalder ([jd@imagescience.com.au](jd@imagescience.com.au)) on 2015/08/17 23:05:31 +0000
Votes at time of UserVoice import: 6

------

I would like it if either

Each paymetn gateway had a configurable option for 'landing status',
i.e.
success payment by credit card -> 'Order received (payment complete)
Order submitted with manual payment (direct deposit) -> 'Order On Hold Pendiny Payment' or similar.

This depend on how you architect the relationship between orders and payments of course.

See attached for how CartThrob does it. Nothing is perfect but this is quite flexible.

Obviously plugin hooks are another method, and I understant the desire not to integrate much business logic, but I suspect that having one success status for each payment gateway would solve a lot of scenarios.

**Comment by lukeholder** [comment]
Recommend using the `craft\commerce\services\OrderStatuses::EVENT_DEFAULT_ORDER_STATUS` to set the default order status.

Will make a guide.

**Comment by edwardpmartinez** [comment]
Hi, @lukeholder. Is there currently a guide on how to use `craft\commerce\services\OrderStatuses::EVENT_DEFAULT_ORDER_STATUS`?

**Comment by lukeholder** [comment]
```php
use craft\commerce\events\DefaultOrderStatusEvent;
use craft\commerce\services\OrderStatuses;
use craft\commerce\models\OrderStatus;
use craft\commerce\Plugin;
use yii\base\Event;

 Event::on(
          OrderStatuses::class,
          OrderStatuses::EVENT_DEFAULT_ORDER_STATUS,
          function(DefaultOrderStatusEvent $event) {
              if($order->myCustomField == 'hello'){
                 $event->orderStatus = Plugin::getInstance()->getOrderStatuses()->getOrderStatusByHandle('myStatus');;
              }
          }
     );

```

**Comment by lukeholder** [comment]
@edwardpmartinez see above for an example

**Comment by lukeholder** [comment]
https://docs.craftcms.com/commerce/v3/events.html#order-events

**Comment by lukeholder** [comment]
Closing this as default order status can be overridden with the `EVENT_DEFAULT_ORDER_STATUS` event.
