### ISSUE TITLE
Database Exception: SQLSTATE[42S02]: Base table or view not found:

### ISSUE THREAD

**Issue by brambeekman** [craftcms/commerce#2497]
### Description

After installing Craft Commerce I get this error:

`
Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bier.commerce_discounts' doesn't exist
The SQL being executed was: ALTER TABLE commerce_discounts ADD userGroupsCondition varchar(255) DEFAULT 'userGroupsAnyOrNone'

Migration: craft\commerce\migrations\m201218_103541_add_user_condition_column_in_promotions

Output:

> add column userGroupsCondition string DEFAULT 'userGroupsAnyOrNone' to table {{%commerce_discounts}} ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bier.commerce_discounts' doesn't exist
The SQL being executed was: ALTER TABLE commerce_discounts ADD userGroupsCondition varchar(255) DEFAULT 'userGroupsAnyOrNone' (/Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE co...')
#1 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE co...')
#2 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/commerce/src/migrations/m201218_103541_add_user_condition_column_in_promotions.php(19): yii\db\Migration->addColumn('{{%commerce_dis...', 'userGroupsCondi...', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\migrations\m201218_103541_add_user_condition_column_in_promotions->safeUp()
#5 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#6 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\commerce\migrations\m201218_103541_add_user_condition_column_in_promotions))
#7 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/services/Updates.php(257): craft\db\MigrationManager->up()
#8 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#9 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#13 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('migrate', Array)
#14 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('migrate', Array)
#15 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/web/Application.php(276): yii\base\Module->runAction('updater/migrate', Array)
#16 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/web/Application.php(677): craft\web\Application->runAction('updater/migrate')
#17 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/craftcms/cms/src/web/Application.php(233): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Users/brambeekman/Documents/brambeekman/websites/untaplist/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/brambeekman/Documents/brambeekman/websites/untaplist/web/index.php(22): yii\base\Application->run()
#20 {main}

`

### Steps to reproduce

1. Composer Update and Install

**Comment by angrybrad** [comment]
Is this a fresh install of the latest (3.4.0.3) or were you updating from a previous version? If you were updating from a previous version, what version was it?

**Comment by brambeekman** [comment]
> Is this a fresh install of the latest (3.4.0.3) or were you updating from a previous version? If you were updating from a previous version, what version was it?

It was a fresh install, the first try was from the plugin store, and the second try with composer in the command line

**Comment by brambeekman** [comment]
After exporting all commerce tables from another site and add the collum `allGroups` in the `commerce_discounts`  it works. Maybe something goes wrong with installing if you have custom users groups in Craft Pro?

**Comment by AugustMiller** [comment]
Bram DM'd me about this any some other Commerce questions—thought I'd transcribe my response from Discord!

> My impression was that only the `Install.php` migration was run when a plugin is installed… bizarre that Craft thinks it'd need to apply one of the incremental migrations.

**Comment by lukeholder** [comment]
@brambeekman just seen an issue with our column check code in the migration you see the error in. It wasn't checking for the table prefix.

Thinking that might have caused your issue if you tried to run the migration after a previous install.

**Comment by brambeekman** [comment]
> @brambeekman just seen an issue with our column check code in the migration you see the error in. It wasn't checking for the table prefix.
> 
> 
> 
> Thinking that might have caused your issue if you tried to run the migration after a previous install.

Ah thanks! Yeah there was a previous install. 😁
