### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#250]
> Created by: Hagen Rode ([hagen00@gmail.com](hagen00@gmail.com)) on 2015/07/05 18:43:48 +0000
Votes at time of UserVoice import: 41

------
Upon login, let admin see an awesome dashboard that gives a snapshot / summary / stats / graphs of various things. e.g. sales for month, % change when compared to previous month (at that same date), sales for year, best sellers, latest orders etc. Compare to dashboards of other big players (e.g. CS Cart, Magento, Shopify, WooCommerce).

**Comment by andris-sevcenko** [comment]
> Created by: Andrew Fairlie ([andrew.fairlie@rye.agency](andrew.fairlie@rye.agency)) on 2015/12/10 12:54:18 +0000


------
Absolutely agree. This feels like the one area of Craft Commerce that is unsellable at the moment.

**Comment by andris-sevcenko** [comment]
> Created by: John ([info@evolve.hk](info@evolve.hk)) on 2016/02/29 08:12:14 +0000


------
Totally agree as well.
Full stats ftw!

**Comment by andris-sevcenko** [comment]
> Created by: Anonymous ([seba78ml@gmail.com](seba78ml@gmail.com)) on 2016/06/15 01:17:47 +0000


------
I agree, i think it´s essential information for products and campaigns monitoring and sales strategies. It´s a must-have

**Comment by andris-sevcenko** [comment]
> Created by: Hagen Rode ([hagen00@gmail.com](hagen00@gmail.com)) on 2017/02/20 07:56:35 +0000


------
The best example is arguably Prestashop. They have a really nice backend interface, with regards to dashboard/reports and especially the view one gets when drilling into a specific customer.

**Comment by andris-sevcenko** [comment]
> Created by: Jason Mayo ([jason@madebyshape.co.uk](jason@madebyshape.co.uk)) on 2017/04/19 08:45:55 +0000


------
This is one feature we really wanted. For now we created a few widgets to help do this - https://github.com/madebyshape/commerce-widgets

**Comment by lukeholder** [comment]
Recommend using main dashboard widgets for now. In the future, we may add multiple dashboards to Craft core.
