### ISSUE TITLE
Setting `registerUserOnOrderComplete` to true not resulting in user creation when order created in CP

### ISSUE THREAD

**Issue by GaryReckard** [craftcms/commerce#2503]
### Description
In my `EVENT_BEFORE_COMPLETE_ORDER` event, I am conditionally setting `$order->registerUserOnOrderComplete = true;`, but have found that when an admin creates an order in the CP, a user never gets created.

I believe it's these lines that are causing the user to not get created:
https://github.com/craftcms/commerce/blob/2934bdea112bdb3f3fd7774e53bba1a0590e2779/src/services/Customers.php#L827-L830
since the order is created in the CP, the _admin_ is logged in.

I've since come up with a workaround, basically copying everything in `_createUserFromOrder` and running that in my `EVENT_BEFORE_COMPLETE_ORDER` when appropriate.

### Steps to reproduce

1. Set `$order->registerUserOnOrderComplete = true;` in `EVENT_BEFORE_COMPLETE_ORDER` event
2. Create order in CP, see if User account gets created.

### Additional info

- Craft CMS version: 3.6.16
- Craft Commerce version: 3.3.3
- PHP version: 7.3

**Comment by lukeholder** [comment]
This has been fixed for the next release. Thanks.

The `registerUserOnOrderComplete` order parameter is now honoured when completing an order from the control panel.

**Comment by lukeholder** [comment]
This was in recently released 3.4.2
