### ISSUE TITLE
Call to a member function getPaymentCurrencies() on null

### ISSUE THREAD

**Issue by janhenckens** [craftcms/commerce#2509]
### Description
Running into this issue through https://github.com/studioespresso/craft-scout/issues/178.
The plugin tries to check whether or not a class is an instance of `craft\base\Element` ([here](https://github.com/studioespresso/craft-scout/blob/master/src/ScoutIndex.php#L45) by calling `new $class`, `new Product` in this case). That results in this error:

`Error: Call to a member function getPaymentCurrencies() on null in /Users/jhenckens/Sites/scout/vendor/craftcms/commerce/src/elements/Product.php:177`

https://github.com/craftcms/commerce/blob/85d1250a4fc359ffd067221102057c9d9451134c/src/elements/Product.php#L175-L179

Doesn't look to be related to Scout, as calling `new Product();` on its own in a module throws the same error.

I found a workaround to solve it in the plugin but I'm kinda lost as to what is causing this.

### Steps to reproduce

1.  Put `$product = new Product();` in a boostrapped module's init() function
2. Refresh the CP

### Additional info

- Craft CMS version: 3.7.7
- Craft Commerce version: 3.4.1
- PHP version: 8.0.3
- Database driver & version:
- Plugins & versions: Scout 2.4.0

**Comment by lukeholder** [comment]
At the moment the Product class depends on the Commerce plugin being instantiated.

If you need to call the commerce plugin, you will need to make sure all plugins are loaded before doing your work...

```php
Craft::$app->on(Plugins::EVENT_AFTER_LOAD_PLUGINS, function() {
    $product = new Product();
});
```

**Comment by janhenckens** [comment]
Is this different from other plugins/custom elements? I don't recall having to do this for other third-party elements.

**Comment by lukeholder** [comment]
Are you just trying to find out if it is an element?

Could you use...

```php
$class = new ReflectionClass($class);
if ($class->implementsInterface('\craft\base\ElementInterface'))
{
 //is an element
}
```

could also use https://www.php.net/is_subclass_of

**Comment by janhenckens** [comment]
That's the fix I have ready for the issue in Scout 👍
