### ISSUE TITLE
Can't scroll inside "Create a new tax zone" window

### ISSUE THREAD

**Issue by jamiewade** [craftcms/commerce#2510]
### Description
When you have added enough countries/states to a tax zone for the window to be scrollable, you can't scroll down to the save button.

### Steps to reproduce

1. Go to a Tax Rate
2. In the Tax Zone field, click "New tax zone"
3. Add as many countries/states as you can
4. Try and scroll down the save button

Running the latest version of Chrome on the latest version of OS X.

### Additional info

- Craft CMS version: Craft CMS 3.7.8
- Craft Commerce version: Craft Commerce 3.4.1

**Comment by pdaleramirez** [comment]
@jamiewade Can you post a screenshot of your layout? Not sure what you are referring to. On that page the Save button is on the upper right section so you don't need to scroll down to click on the save button.

**Comment by jamiewade** [comment]
@pdaleramirez See the "Steps to reproduce"; this is referring to the modal window for adding a new tax zone when you are editing a tax rate:

![Screenshot 2021-08-11 at 11 24 06](https://user-images.githubusercontent.com/6672331/129013309-e4ee2eb8-983e-4e11-a8f6-7b88a236de77.png)

And you can see here how the layout breaks when many countries are added:

![Screenshot 2021-08-11 at 11 25 58](https://user-images.githubusercontent.com/6672331/129013558-1dccc338-4b5d-44c2-99e1-d1341900c9ee.png)

Once the Save button disappears from view, you cannot scroll down to it.

**Comment by pdaleramirez** [comment]
This issue is resolved on Commerce4.
