### ISSUE TITLE
Shipping methods: costs per item and per order

### ISSUE THREAD

**Issue by JoeriE** [craftcms/commerce#2516]
### Description

I've a client with a complicated shipping rule and I was wondering if this is possible in Craft Commerce by default. There are two types of shipping categories (general & merchandise). 

- General: all costs are calculated per item (in this example €6 per item)
- Merchandise: the costs of merchandise items is always €6 (doesn't depend on how many items)

I've added these to a shipping method like this:

![image](https://user-images.githubusercontent.com/11161180/129195754-bc597fe7-fcce-416f-b8af-d77827a5748b.png)

This doesn't seem to be correct: if I add one product that belongs to the general category, the shipping cost will be €12 (base rate + per item rate). But it actually needs to ignore the base rate for the general category. 

Is this possible?

### Additional info

- Craft CMS version: 3.7.7
- Craft Commerce version: 3.4.1

**Comment by pdaleramirez** [comment]
@JoeriE This is possible, in your `Shipping Category Conditions` in the `Conditions` tab. You can DISALLOW the merchandise shipping category.
