### ISSUE TITLE
Utility to Transfer Entries to Products

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#252]
> Created by: Chandra McFarlen ([chandra.mcfarlen@drivesimplicity.com](chandra.mcfarlen@drivesimplicity.com)) on 2015/06/16 19:44:20 +0000
Votes at time of UserVoice import: 1

------
I have a production site that displays my customer's products, but does not do any online sales. Their products are currently setup as entries within Channel Sections. If it will be necessary for these Entries to become Products, it would be fantastic if their was a slick utility to make this transition easier.

**Comment by lukeholder** [comment]
Recommend using the FeedMe plugin: https://plugins.craftcms.com/feed-me
