### ISSUE TITLE
unique SKU is not checked

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#2520]
Hello,

I can add the same sku for different products. Craft is not checking if it is unique before saving.

Craft: 3.6.12
Commerce: 3.3.0.1

**Comment by pdaleramirez** [comment]
@Sam-Black-0013 I've tested this on Commerce v3.3.0.1 and I couldn't recreate the issue. Will you be able to specify the steps to reproduce your issue?
