### ISSUE TITLE
Multisite and carts changing to wrong site

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#2523]
### Description
I have recently added multisite functionality to my project, and it has caused a strange issue with Commerce. 

So to explain the setup a little bit, I have two sites set up, and I only have the products enabled on one of these sites, let's call it Site A. On the front end, when I go to a product via Site A, I can add it to the cart no issues and everything looks fine in the active cart. I go through the checkout steps and fill out my details, everything still okay. 

But when I try and pay (using crafts PayPal checkout plugin), I get the error `Expected an order id to be passed`. I have had a look through the GitHub issues for the PayPal checkout plugin, but none seem to help my issue. 

Something I have noticed however, is that when I try to pay, when I refresh the active cart in the CMS, the order site has changed from Site A to Site B. And because it has changed, it removes the products from the cart - I'm guessing because the products are disabled in Site B. 

Whilst testing this, I noticed that if I enable the products in the Site B, I can checkout and pay without any issues. The stock level of the product adjusted for the product in both sites. But surely I shouldn't have to have the products enabled across all sites?! I don't want people to be able to access the products via Site B. 

### Additional info

- Craft CMS version: 3.6.14
- Craft Commerce version: 3.3.5.1

**Comment by pdaleramirez** [comment]
@iamtompickering Craft Commerce supports Multi Site but not Multi Store. I think what you are trying to do is make your application to be a Multi Store which is not available yet. On latest version when you create a product it is propagated to all sites meaning it is available on all sites. Commerce treats all site as one and expected that products are available on all sites.

Multi store functionality is on our roadmap you can track it here: https://github.com/craftcms/commerce/discussions/2283

 The error handling for this though could be improved. Letting the user know that all products should be enabled to proceed the checkout process.

**Comment by pdaleramirez** [comment]
Duplicate issue #2283
