### ISSUE TITLE
POS and Inventory Management

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#254]
> Created by: Nathan Doyle ([natetronn@gmail.com](natetronn@gmail.com)) on 2015/05/04 20:46:33 +0000
Votes at time of UserVoice import: 62

------
It would be great if Craft Commerce came with POS (point-of-sale) and Inventory Management integration and or capabilities.

A good example of POS is from Shopify:

http://www.shopify.com/pos

Inventory examples:

http://www.inventory.com
http://inventoryapi.com

Inventory and POS:

http://www.vendhq.com
http://www.vendhq.com/partners/developers

I put both POS and Inventory Management in one since it seems like they could go hand in hand. Inventory on the site and Inventory on the web could be tracked concurrently if need be (though some might separate web/local inventory but still like using the same setup versus two different dashboards.)

This will bridge the gap between Web Based and Brick and Mortar commerce. Opening up the market for Craft Commerce immensely! 

Craft Commerce with POS w/ Inventory Management and you'll have a powerful solution which can meet the needs of many many clients out there.

It's possible to throw the job to a 3rd party POS/Inventory solution via an API though, at the very least, if Craft Commerce planned for such a thing in the beginning by putting Inventory Management and POS on it's list of things people may require in the future it will greatly ease the process I would think. Plan now, benefit down the road versus thinking of Craft Commerce as a web based only solution and not planning for future growth that is.

Note: I realize, at this point, there is allot of lower hanging fruit to grab than this and it's no an easy addition to just throw together on a whim etc. 

With that said, if we are to use Craft Commerce for anything more than a small product based website and compete with larger solutions like Magento or Shopify this is something that will be instrumental in achieving greater success across the board. 

Throw in Craft for content and you're going to start seeing some amazing things happen!

**Comment by andris-sevcenko** [comment]
> Created by: Max McClaskie ([max.mcclaskie@gmail.com](max.mcclaskie@gmail.com)) on 2016/01/06 23:52:24 +0000


------
Second this idea, Id like the ability to allow clients to create purchase orders so that they can log what items they have on order and then easily flip a switch when they arrive to add them to the available inventory on the website.

**Comment by andris-sevcenko** [comment]
> Created by: Andrew Cull ([andrew@agema.io](andrew@agema.io)) on 2016/07/06 15:56:05 +0000


------
We are looking at building a POS through our Craft site and controlling access to employees, essentially an organized view of all products that we run through web-checkout. We&#39;ve used the Shopify System for several years as well as Odoo -  they all require internet.  Seems like a solid solution in the interim, inspired by https://snipcart.com/blog/pos-system-ecommerce-integration.

With a barcode tab and an easy to program scanner, you could also have simple form that populates and searches for the barcoded products adding them all to a cart.  Just a not-to-difficult solution until some great dev builds a real one.

**Comment by andris-sevcenko** [comment]
> Created by: Anonymous ([andycarrcleaner@yahoo.com](andycarrcleaner@yahoo.com)) on 2016/10/19 08:22:30 +0000


------
It would be great to add a scale support for weighted goods so that the system calculated the price by itself like this system, for example http://posvt.com/

**Comment by lukeholder** [comment]
See #44 for Inventory.

See #46  for POS.
