### ISSUE TITLE
Small weight value being rounded to 0

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#2540]
### Description
We have some products (springs) that are really small with a weight of `0.0002` pounds. When you enter that weight into the weight field and save it, the weight value is then set to 0. It looks like the smallest value that you can enter in weight is `0.0006` which is then rounded to `0.001`. Nothing immediately stuck out to me in the code that would cause this. I also looked at the DB column and saw it was  `DECIMAL 14,4` so there should be enough room to support that number of decimals.

I wasn't sure if this was an expected minimum, and I need to hook into a before save event to do some rounding or something else was going on. Thanks in advance.

### Steps to reproduce

1. Add a weight of `0.0002` to a variant
2. Save it
3. See that the weight of the variant is now 0

### Additional info

- Craft CMS version: Craft Pro 3.6.18
- Craft Commerce version: 3.3.0.1
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Avatax</th>
                        <td>2.1.6</td>
                    </tr>
                                    <tr>
                        <th class="light">Classnames</th>
                        <td>1.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Command Palette</th>
                        <td>3.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>3.3.0.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Feed Me</th>
                        <td>4.3.5.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Imgix</th>
                        <td>2.1.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Linkit</th>
                        <td>1.1.12.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Navigation</th>
                        <td>1.4.14</td>
                    </tr>
                                    <tr>
                        <th class="light">Postie</th>
                        <td>2.4.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Ray</th>
                        <td>1.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.8.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Retour</th>
                        <td>3.1.53</td>
                    </tr>
                                    <tr>
                        <th class="light">Scout</th>
                        <td>dev-master</td>
                    </tr>
                                    <tr>
                        <th class="light">SEOmatic</th>
                        <td>3.3.41</td>
                    </tr>
                                    <tr>
                        <th class="light">Stripe for Craft Commerce</th>
                        <td>2.3.2.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Style Inliner</th>
                        <td>2.3.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Super Table</th>
                        <td>2.6.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Table Maker</th>
                        <td>2.0.1</td>
                    </tr>
                            </tbody>
        </table>

**Comment by nfourtythree** [comment]
Hi @davist11 

Thank you for raising this issue.

It looks like the value is being stored correctly but is shown on the form incorrectly and therefore if you were to resave would overwrite the value with the incorrect data. This is a bug that we will look to get fixed.

Thanks!

**Comment by lukeholder** [comment]
Fixed for the next release.
