### ISSUE TITLE
Bots and crawlers creating 100'000s of uselss order elements

### ISSUE THREAD

**Issue by francoislevesque** [craftcms/commerce#2543]
### Description

Our webstore currently has a small amount of traffic (about 30 unique users per day). However, about 7000 orders are created everyday because of bots and crawlers. Many of them are legitimate crawlers (from bing, microsoft, google). This bloats the following tables:

- searchindex
- elements
- elements_sites
- commerce_orders
- commerce_customers

We reduced `purgeInactiveCartsDuration` to 30 days, which helps mitigating the issue. However, `searchindex` and `elements` tables are quite huge, which has an impact on performance.

Is there a way to prevent cart & customer creation when a bot IP is detected?

### Steps to reproduce

1. Create a simple craft commerce site
2. Market it online and wait for the bots & crawlers to come 🕷

### Additional info

- Craft CMS version: 3.7.12
- Craft Commerce version: 3.3.3
- PHP version: 7.4
- Database driver & version: MySQL 8.0
- Plugins & versions:

**Comment by nfourtythree** [comment]
Hi @francoislevesque 

Thank you for your issue.

My assumption here is that you are using `craft.commerce.carts.cart` in your templates? When using that method a load of a page with a brand new session with no other action taken (e.g. adding to cart, updating addresses) should not cause the cart to save.

You can test that this is the case by having the `commerce_orders` DB table open, going to the site in a new private window and seeing if a new record is created.

If one is created just by viewing the page this would point to something else happening, maybe some custom code?

Let me know what you discover.

Thanks!

**Comment by francoislevesque** [comment]
Hi @nfourtythree !

Thanks for the info, we found the culprit :

```php
private function setPaymentCurrency($currency): void
{
    $commerce = Commerce::getInstance();
    $cart = $commerce->getCarts()->getCart();
    if ($cart->paymentCurrency != $currency) {
        $cart->paymentCurrency = $currency;
        Craft::$app->getElements()->saveElement($cart, false, false);
    }
}
```

We are using a IP geolocator service to guess the user's country & currency. Would you propose a different approach to automatically set the paymentCurrency without saving a cart?

**Comment by AugustMiller** [comment]
You may be able to just set `$cart->paymentCurrency` for the current request, and leave the cart in memory, for display purposes. Subsequent calls to `craft.commerce.carts.cart` would use the same, memoized cart.

Then, another listener for `Order::EVENT_BEFORE_SAVE`, could handle setting it for "new" carts:

```php
Event::on(
    Order::class,
    Order::EVENT_BEFORE_SAVE,
    function (ModelEvent $e) {
        // Don't alter it after the first save, though:
        if (!$e->isNew) {
            return;
        }

        $e->sender->paymentCurrency = 'CUR'; // Or use your IP/Geo plugin to fetch a value!
    });
```

**Comment by nfourtythree** [comment]
Hi @francoislevesque 

Thank you for your response.

@AugustMiller beat me to the suggestion, set the payment currency in memory for the cart and then use the before save event to update the payment currency information.

Also to note that the update cart action takes a `paymentCurrency` param so if you want to add a hidden field to any of your forms you could do that as well to make sure it is set.

Hope this helps, thanks!

**Comment by francoislevesque** [comment]
Thank you 🤗
