### ISSUE TITLE
Example template (account signin) tag not closed properly

### ISSUE THREAD

**Issue by aeu** [craftcms/commerce#2548]
### Description
Markup on sample sign-in page is broken, specifically the remember me input field isn't closed out properly.

### Steps to reproduce

1. Open sample file
2.See that the close is missing

### Additional info

Craft CMS version: Craft Pro 3.7.12
Craft Commerce version: 3.4.2
PHP version:7.3.25
Database driver & version: MySQL 5.5.5
Plugins & versions:
Amazon S3 1.2.15
Craft Commerce 3.4.2
Feed Me 4.4.0
Mandrill 1.3.1
Postie 2.4.9
Redactor 2.8.8

**Comment by nfourtythree** [comment]
Closing this issue as discussed in this comment: https://github.com/craftcms/commerce/pull/2550#issuecomment-920668435
