### ISSUE TITLE
Multiple currencies

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#255]
> Created by: Pål Strøm ([pal@mustasj.no](pal@mustasj.no)) on 2015/05/04 19:45:49 +0000
Votes at time of UserVoice import: 69

------
So that one product can have dollar price and euro price, for instance.

**Comment by andris-sevcenko** [comment]
> Created by: Russ Back ([russ@rallyagency.co.uk](russ@rallyagency.co.uk)) on 2015/12/03 19:49:12 +0000


------
I would also like to see the ability to set distinct prices per currency/locale too. So rather than relying on dynamic currency conversion (which could mean from a base price of GBP 100) you end up with a converted price of USD 187.67), you can ensure that prices remain consistent in all locales and are not subject to exchange rate fluctuation.

**Comment by andris-sevcenko** [comment]
> Created by: Russ Back ([russ@rallyagency.co.uk](russ@rallyagency.co.uk)) on 2015/12/03 19:51:50 +0000


------
It would also be useful if inventory was localised too. We have one client on Magento (which he and we loath but is our best bet right now) who has different fulfilment houses for UK and US sales. Setting inventory at the locale level (or inheriting the default where no locale-specific inventory is set), would support this.

**Comment by andris-sevcenko** [comment]
> Created by: Luke Holder ([luke@pixelandtonic.com](luke@pixelandtonic.com)) on 2016/10/19 13:40:18 +0000


------
Craft Commerce 1.2 Introduced multi-currency payment support.

More details here:

https://craftcommerce.com/docs/payment-currencies

**Comment by andris-sevcenko** [comment]
> Created by: Anonymous ([adrienne@shoeboxed.com](adrienne@shoeboxed.com)) on 2017/07/27 21:21:45 +0000


------
I really need this too; I have numerous clients with international businesses and they need to be able to explicitly set prices for all currencies instead of converting.

**Comment by andris-sevcenko** [comment]
> Created by: Martin Sjåstad ([sjaastad@noisolation.com](sjaastad@noisolation.com)) on 2018/03/16 11:37:50 +0000


------
We neeed this!!!

**Comment by LexiunDev** [comment]
I'm voting for this too. As per discussion inside the craftcommerce slack channel a simple currency conversion doesn't work for us either as it generates weird price points. Just like on Wordpress/Woocommerce with WPML we'd like to set custom prices (original and discount) per locale.

12 sepperate craft + craftcommerce installs isn't commercially viable and will make a management nightmare. 

As long as the backend is still in a single currency but custom prices can be set per locale it's still a great solution for us.

**Comment by LexiunDev** [comment]
<img width="1198" alt="screenshot 2018-04-11 20 44 09" src="https://user-images.githubusercontent.com/19554198/38636497-073661a4-3dd1-11e8-9f93-1b9125ea434c.png">

**Comment by petergeller** [comment]
Hi, we build a really nice website for a surfshop and used also Craft commerce to prepare the first steps to communicate and sell later on different boards and articles through that shop. We adjusted the variant with a custom data field, to display 4 different currencies/prices at the moment based on the selected region. Right now we have USD, AUD, EUR, JPY. Everything works fine to display the prices but for all Model calculations we need to overwrite the base price for each variant, based on that value of the currency field. Is it somehow possible to overwrite the base price on some entry point, that it will be used for all further calculations throughout related price Models?

![image](https://user-images.githubusercontent.com/466560/43796666-2f2304f4-9a85-11e8-9358-caa1f5fd6201.png)

**Comment by bleepsandblops** [comment]
Hey @petergeller , if that's helpful here's the bit of code that I use that changes the price for the line item when you add it to the cart:
~~~~
Event::on(LineItems::class, LineItems::EVENT_POPULATE_LINE_ITEM, function(LineItemEvent $e) {
  if ($e->lineItem->getOrder()->getPaymentCurrency() !== 'GBP') {
    $price = $e->lineItem->snapshot['priceIn'.ucfirst(strtolower($e->lineItem->getOrder()->getPaymentCurrency()))];
  } else {
    $price = $e->lineItem->price;
  }
  
  $cart = CommercePlugin::getInstance()->getCarts()->getCart();
  $cart->setPaymentCurrency($e->lineItem->getOrder()->getPaymentCurrency());

  $e->lineItem->price = $price;
  $e->lineItem->note  = $e->lineItem->getOrder()->getPaymentCurrency();
});
~~~~
It works fine BUT the drawback is that in the control panel it's not very clear what the purchase currency was, as it's showing GBP all the time. So you'd want to set up your own Order pages etc so that it doesn't get too confusing for the e-comm admin

**Comment by nfourtythree** [comment]
Discussion continuing on #24
