### ISSUE TITLE
Price modifiers can be excluded from taxation

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#256]
> Created by: Anonymous ([tom@agentc.com.au](tom@agentc.com.au)) on 2015/05/04 19:21:19 +0000
Votes at time of UserVoice import: 1

------
For some products it would be great if you could choose to exclude taxation on a price modifier. 

The most common example would be a giftcard, you have the price of the card itself which includes tax, but the value loaded onto the gift card is tax free (in Australia at least).

**Comment by lukeholder** [comment]
The suggestion would be to use tax categories for the loaded value amount to mark it as tax-free.
