### ISSUE TITLE
Bug in template file for checkout steps

### ISSUE THREAD

**Issue by aeu** [craftcms/commerce#2563]
### Description
The sample template files include a nav that shows checkout progress.  (Email, Account, Address, Shipping, Payment Method, and Payment).  As you step through the checkout path, it compares the URL to the paths, and adds a class to the nav to delineate progress.

Payment is a substring of Payment Method, so when you are on the Payment Method step, both Payment and Payment Method are decorated.  (See attached screenshots).

### Steps to reproduce

1. Step through sample template files.
2. Reach Payment step.  Notice the payment and payment method are decorated.

### Additional info

Craft CMS version: Craft Pro 3.7.12
Craft Commerce version: 3.4.2
PHP version:7.3.25
Database driver & version: MySQL 5.5.5

**Comment by aeu** [comment]
![checkout-shipping](https://user-images.githubusercontent.com/2225377/134501530-144e1a02-c511-4f79-b08a-cba07827f5ff.png)
![checkout-payment-method](https://user-images.githubusercontent.com/2225377/134501543-92a5fb95-5d81-4857-83ff-ba27b776f29e.png)

**Comment by aeu** [comment]
![checkout-shipping](https://user-images.githubusercontent.com/2225377/134501786-17417cde-ec77-4d3c-a59f-70ca134e7cb5.png)
![checkout-payment-method](https://user-images.githubusercontent.com/2225377/134501792-3e666f5e-f13c-4e92-9d58-18715cf2fb59.png)

**Comment by aeu** [comment]
https://github.com/craftcms/commerce/blob/develop/example-templates/build/shop/_private/layouts/includes/nav-checkout.twig#L43

**Comment by lukeholder** [comment]
Thanks for reporting this has been fixed for the next release.
