### ISSUE TITLE
Missing User accounts for Commerce Customers

### ISSUE THREAD

**Issue by ArtDepartmentMJ** [craftcms/commerce#2581]
### Description
We seem to be missing the users associated with our commerce customers. When I say missing, they are not appearing in the CP (in Users or Commerce) however we can see their Customer accounts and orders. All users are required to register so they should all have User accounts and I can see these in the database just not in the CP. Any ideas?

### Steps to reproduce

1. Go to Commerce->Customers
2. No Associated User accounts

### Additional info

- Craft CMS version: 3.7.16
- Craft Commerce version: 3.4.4
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions:

**Comment by pdaleramirez** [comment]
Please test this again without any custom modules or plugins when doing the checkout. It could have been that the user data is saving on another element type
