### ISSUE TITLE
Refund button does nothing when clicked

### ISSUE THREAD

**Issue by jaspertandy** [craftcms/commerce#2587]
### Description

On a new transaction, the refund button does nothing - no HTTP requests triggered, no console errors.

### Steps to reproduce

1. Process transaction
2. Visit admin UI
3. Navigate to payments tab
4. Try to refund a successful transaction
5. Nothing happens

I'm aware that this isn't a good bug report but I'm hoping for some assistance on how to debug this - that button is supposed to trigger this JS, or "this happens when xyz file doesn't load correctly" or something like that. If anyone's able to help me get started on where to look that'd be appreciated.

### Additional info

- Craft CMS version: 
- Craft Commerce version: 3.3.5.1 
- Craft Commerce Stripe version: 2.3.2.1
- PHP version: 7.4.24
- Database driver & version: MySQL

**Comment by lukeholder** [comment]
@jaspertandy I would first advise upgrading to the latest commerce-stripe and commerce releases.

Could you also check your web browser developer console: https://developer.chrome.com/docs/devtools/open/

That will show if there are any javascript/http errors.

**Comment by jaspertandy** [comment]
I've tracked this down to pagespeed. Doesn't seem to affect anything else, but I would guess that one of my filters is causing some sort of event to not get added to that link. I don't know what it is and I don't know enough about how Craft Commerce attaches these events to look further into it, but here's my pagespeed config:

```
		pagespeed on;
		pagespeed FileCachePath /pagespeed_cache;

		pagespeed LowercaseHtmlNames on;
		pagespeed XHeaderValue "hello";
		pagespeed PreserveUrlRelativity on;
		pagespeed FetchHttps enable;

		pagespeed EnableFilters add_head,make_show_ads_async,make_google_analytics_async,collapse_whitespace,combine_css,combine_javascript,combine_heads,convert_meta_tags,dedup_inlined_images,defer_javascript,elide_attributes,extend_cache,convert_gif_to_png,convert_jpeg_to_progressive,convert_jpeg_to_webp,convert_png_to_jpeg,convert_to_webp_animated,convert_to_webp_lossless,inline_images,recompress_jpeg,recompress_png,recompress_webp,jpeg_subsampling,resize_images,strip_image_color_profile,strip_image_meta_data,flatten_css_imports,hint_preload_subresources,include_js_source_maps,inline_import_to_link,inline_css,inline_google_font_css,inline_javascript,inline_preview_images,resize_mobile_images,lazyload_images,local_storage_cache,responsive_images,rewrite_javascript,move_css_above_scripts,move_css_to_head,insert_dns_prefetch,prioritize_critical_css,remove_comments,rewrite_css,rewrite_style_attributes_with_url,sprite_images;
```

And here's what I've added to ~fix~ bypass the issue:

```
		pagespeed Disallow "*/admin/commerce*";
```

Not sure whether you consider this an issue but maybe it'll help someone else who has a similar problem one day!
