### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#259]
> Created by: Jozo ([wmd@wmd.hr](wmd@wmd.hr)) on 2015/05/04 17:47:26 +0000
Votes at time of UserVoice import: 2

------
To make this even powerfull > Same way as you have added system mails > Can you add  MACROS that will work with statuses same as System mails 
IN MACRO you specify template or file that do something  > Then add that Macro to Status same like System mail
When order Status is changed, mail is sent > but in same time MACRO for that status is activated that do something
This will be great  for process automatization  and save quite much time and many clicks

**Comment by lukeholder** [comment]
Sounds like something that should be core. Please make a feature request at http://github.com/craftcms/cms
