### ISSUE TITLE
Products in lite edition show "Discounts"

### ISSUE THREAD

**Issue by mikejpeters** [craftcms/commerce#2590]
### Description

When using the LITE edition of Craft Commerce and editing a product,
the sidebar shows "Related Discounts" and lets the user add a discount,
despite discounts not being a feature of the LITE edition.

On a related note, why do the Tax & Shipping dropdowns display as well, when the LITE edition only supports a single shipping & tax configuration?

![image](https://user-images.githubusercontent.com/3334654/137807587-8cce70ff-cba7-4ebe-a296-475333052a4d.png)

### Steps to reproduce

1. Edit a product
2. Sidebar shows "Related Discounts" and option to "Add Discount"

### Additional info

- Craft CMS version: 3.7.16
- Craft Commerce version: 3.4.5 LITE
- PHP version: 7.4.16
- Database driver & version: MySQL 8.0.26
- Plugins & versions:

**Comment by nfourtythree** [comment]
Hi @mikejpeters 

Thank you for bringing this to our attention. We have pushed a fix for this which will be included in the next release of Commerce.

Thanks!
