### ISSUE TITLE
Order status appears not updated in certain contexts

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/commerce#2596]
### Description

Some of our orders have had their order status updated and the correct update shows on the "Status History" tab of the order but on the listings of orders these order show their old status, also relevant to note that the count next to the order status is different to the number shown in the listing area:

![image](https://user-images.githubusercontent.com/39988088/139649526-3b4c6fa4-7d0d-427e-847b-0c6ac849d1c7.png)

It looks like the numerical count is correct as looking at 3 of those orders they show what the status was changed to but is not being reflected in the above listing:

![image](https://user-images.githubusercontent.com/39988088/139650094-c1480222-0956-4f3c-b9f4-810cde7e5439.png)

_It is important to note that the status change above marked with the note "Order status automatically updated..." is the work of some custom module code that boils down to:_

```php
Event::on(Order::class, Order::EVENT_AFTER_ORDER_PAID, function(Event $e) {
    /** @var Order $order */
    $order = $e->sender;
    $order_status = OrderStatus::find()->where([ 'handle' => 'charged' ])->one();
    $order->orderStatusId = $order_status->id;
    $order->message = 'Order status automatically updated to "charged"';
    Craft::$app->getElements()->saveElement($order, false);
});
```

### Steps to reproduce

1. Place an order
2. Attempt to manually change it's status in the control panel

### Additional info

We recently updated this installation; Commerce `3.2.14.1 => 3.4.4` and Craft `3.6.6 => 3.7.16`, but all the orders we can currently see the issue on were placed after that update. 

No errors were encountered during the migrations of the update and all seemed well on our non-live environment before deploying to production, however, when testing this again this is reproducible in our non-live environment.

- Craft CMS version: 3.7.16
- Craft Commerce version: 3.4.4
- PHP version: 7.4.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
Asset Rev	6.0.2
CP Field Inspect	1.2.5
Craft Commerce	3.4.4
Digital Download	2.1.7
Digital Products	2.4.3.2
Dumper	2.0.0
Imager	v2.4.0
Inlin	2.1.1
Minify	1.2.10
Navigation	1.4.21
PayPal Checkout for Craft Commerce	1.2.2.2
Redactor	2.8.8
SEOmatic	3.4.15
Stripe for Craft Commerce	2.3.2.1
Template Select	2.0.2
Wordsmith	3.3.0.1

**Comment by nfourtythree** [comment]
Hi @rob-baker-ar 

Just a couple of quick questions:

- Is the correct order status showing in the sidebar on the Order Edit page?
- What is the time difference when the automated status change normally happens. Are they close together?

Thanks.

**Comment by nfourtythree** [comment]
Hi @rob-baker-ar 

Thanks for the updated information. It certainly does sound like a caching thing and there are some caches at play on the element indexes. 

I have just tried to replicate this locally by having a piece of code automatically update the order status. However, I was unable to replicate the issue you are seeing.

Each time I ran the code the order would end up in the correct status showing in the CP.

Could there be anything else at play here? Other code? Manipulating the DB? Load balanced environment? Or anything else you could think of that would help us replicate what is happening for you?

Thanks.

**Comment by rob-baker-ar** [comment]
I don't think the automatic status change has anything to do with this. That will only ever happen once per order and only when the order is in a "new" status. I just mentioned it as it was the first status change shown in one of my screen grabs.

It happens for us when any manual status change is made to any order (i.e. edit order, change status, save).

We try to never make any manual changes to the database - there are no manual changes to this db that I'm aware of.

We are operating with a single VM instance - no load balancing, it's a relatively simple shop site.

We use redis for cache purposes - configured in the standard way for Craft, redis is also used for the session and mutex (but not the queue). redis is running on localhost.

I will check through the rest of the module code more closely but that will probably not be done until tomorrow. I'll update once done.

Thanks.

**Comment by nfourtythree** [comment]
@rob-baker-ar as you check through everything it might be worth dumping all the cache and seeing if that solves the issue.

**Comment by rob-baker-ar** [comment]
So from what i can see here, this is definitely a cache issue and seems not to be related to custom module code. I was able to replicate this with our custom module entirely disabled.

In regard to the cache, after triggering the issue _(changing an order's status - listing count vs display different)_ and then clearing these cache items:

![image](https://user-images.githubusercontent.com/39988088/139821747-85e7bda1-eaba-486b-ad54-94c2c00e7129.png)

The count vs listed orders became correct on refresh. **But** if the issue is triggered again, then the issue shows again - cache needs to be cleared each time a status changes.

So, from what I can see here, altering an order's status and saving does not invalidate a cached item / items that the order listing uses but the count next to the order status in the aide bar does not use - that always seem to be correct.

**Comment by nfourtythree** [comment]
Hi @rob-baker-ar 

Thank you for the further information.

Are you able to test your project locally or on a different environment that uses non-Redis caching? This could help isolate if it is a general problem, a problem with your Redis set-up or a problem with Commerce and Redis.

Thanks.

**Comment by rob-baker-ar** [comment]
I can _sort of_ do this. I disabled everything related to redis in `config/app.php` on our non-live env so Craft is using default settings for cache, session, mutex. This appears to fix the issue. It's not a solution, but it offers a clue!

My guess now would be something along the lines of a race condition between cached data used on between different AJAX requests / responses.

Looking at some of the code: `actions/commerce/orders/get-index-sources-badge-counts` goes straight to the database whereas `actions/element-indexes/get-elements` (not part of Commerce - core Craft) internally uses `Element::indexHtml()` which in the end calls `$elementQuery->cache()->all()` - not sure how useful that is but illustrates how the listing is subject to the cache where the visible listing is not.

**Comment by rob-baker-ar** [comment]
I have been looking for a good excuse to try out nitro!

I just fired up a nitro instance of this site using a SQL backup from live - when using the nitro redis service, the issue is reproduceable, when redis is disabled it is not. This _should_ prove that it's not something to do with our installation of redis - instead something more general to do with redis / caches.

**Comment by nfourtythree** [comment]
Hi @rob-baker-ar 

I too have this set up with nitro and Redis but still am unable to replicate the issue. 

Could you send your composer files and a DB backup to support@craftcms.com this would allow us to get things up and running at our end and see if we can spot anything.

Thanks.

**Comment by rob-baker-ar** [comment]
OK, I have to get consent for that, there may be data compliance issues. I saw this coming and have already asked the necessary people. I'll update this when I can.

**Comment by nfourtythree** [comment]
Ok cool. In the meantime you could try setting up a fresh install of Craft and Commerce using nitro and Redis and see if you are able to replicate the issue. That could also narrow things further.

**Comment by rob-baker-ar** [comment]
Hi @nfourtythree I now have consent to send on a database dump. I'll email a link to that today.

I have not had time to set-up a fresh install with a fresh database, but as above, when importing our database into a fresh nitro install with our `composer.lock` the issue is happening.

One further thing I have discovered: In order to see this happen, an order's status needs to be changed on the order screen itself. If you tick / select one or more orders on an order listing and change their status via `cog drop down > Update Order Status...` Craft seems to invalidate caches correctly and we get the correct display after the status changes.

**Comment by nfourtythree** [comment]
Closing this ticket as it was resolved through support. 

Updating both Craft and Commerce to the latest versions solved the issues.
