### ISSUE TITLE
Shipping Zone Doesn't Work

### ISSUE THREAD

**Issue by clarknelson** [craftcms/commerce#2597]
### Description
I am investigating a bug where the shipping method is not being applied to the cart. When I use "Anywhere" the method is available for the cart but when I use "US Shipping" it does not appear available for the cart.

![Screenshot from 2021-11-01 15-11-53](https://user-images.githubusercontent.com/4106671/139735847-69988b1a-742a-4344-9509-075a5646d42f.png)
When I use the country dropdown, USA is the only country available to select.

![Screenshot from 2021-11-01 15-17-03](https://user-images.githubusercontent.com/4106671/139736017-5d3e1376-c695-4abc-a528-a7154655e4e8.png)
Trying a state based approach also does not work

### Additional info

- Craft CMS version: 3.6.18
- Craft Commerce version: 3.3.2
- PHP version: 7.4.24
- Database driver & version: MySQL 5.7.35
- Plugins & versions:

**Comment by nfourtythree** [comment]
Hi @clarknelson 

I have just tried this on the latest version of Commerce and everything seems to be working as expected.

I created a new zone that was "Country-based" with the only United States selected in the countries dropdown. I think used that zone in a shipping rule.

Using the example templates I stepped through the checkout making sure to enter an address with the United States selected. This then allowed me to select the resulting shipping method.

Please let us know if you have any further information that could help us replicate this issue, thanks.

**Comment by clarknelson** [comment]
Thank you! One aspect I believe I did not make clear. When selecting from the country based option, the United States is the **only** option I am able to select from. Do you know why that may be? It is what indicated to me there may be an error on the plugin side.

Do you think there may be a plugin interacting with this field the wrong way? Here is my composer.json requires:

```json
"require": {
  "adm/enrollment": "^1.0.0",
  "aelvan/stamp": "2.1.0",
  "barrelstrength/sprout-encode-email": "2.0.7",
  "besteadfast/craft-preparse-field": "1.2.4",
  "bitboxde/error-notifier": "1.0.4",
  "c10d/craft-hcaptcha": "1.1.0",
  "clarknelson/craft-recaptcha-3": "1.2.0",
  "craftcms/aws-s3": "1.2.11",
  "craftcms/cms": "3.6.18",
  "craftcms/commerce": "3.3.5.1",
  "craftcms/commerce-paypal-checkout": "1.2.2.2",
  "craftcms/commerce-stripe": "2.3.2",
  "craftcms/redactor": "2.8.7",
  "craftcms/simple-text": "2.0.2",
  "doublesecretagency/craft-cpbodyclasses": "2.2.1",
  "doublesecretagency/craft-cpcss": "2.4.0",
  "doublesecretagency/craft-cpjs": "2.4.0",
  "doublesecretagency/craft-matrixcolors": "2.0.1",
  "doublesecretagency/craft-smartmap": "3.3.5",
  "elivz/vzurl": "2.1.2",
  "lewisjenkins/craft-dynamic-fields": "3.0.11",
  "mmikkel/cp-field-inspect": "1.2.5",
  "nystudio107/craft-cookies": "1.1.14",
  "nystudio107/craft-retour": "3.1.53",
  "nystudio107/craft-seomatic": "3.3.42",
  "nystudio107/craft-typogrify": "1.1.18",
  "ostark/craft-async-queue": "2.2.0",
  "putyourlightson/craft-snaptcha": "3.0.5",
  "solspace/craft3-calendar": "3.2.1",
  "studioespresso/craft-dumper": "2.0.0",
  "supercool/buttonbox": "2.0.4",
  "topshelfcraft/supersort": "3.1.0",
  "topshelfcraft/walk": "3.0.0",
  "topshelfcraft/wordsmith": "3.3.0.1",
  "verbb/cp-nav": "3.0.15",
  "verbb/field-manager": "2.2.4",
  "verbb/super-table": "2.6.8",
  "vlucas/phpdotenv": "^3.4.0"
},
```

**Comment by nfourtythree** [comment]
Hi @clarknelson 

I would suggest going in the control panel and heading to `Commerce > Store Settings > Countries & States` to see if all the other countries are enabled.

Thanks.

**Comment by clarknelson** [comment]
Okay I see what is going on, thank you!
