### ISSUE TITLE
Order PDF from order index translates wrong

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#2599]
### Description
When downloading a PDF from the order index page, the translations are using the logged in user language instead of the order language.

Downloading from the order detail page is working correct.

Also, in our case the site uses `nl-NL`, but for the user language you can only select `nl`, which makes it impossible to select the right user language to get it working.

### Steps to reproduce
1. Have an order with for example `nl-NL` as site language
2. Have a user with for example `en` as control panel language
3. Download the PDF from the order detail page -> no problem
4. Download the PDF from the order index -> wrong translations 

### Additional info

- Craft CMS version: 3.7.18.2
- Craft Commerce version: 3.4.6

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

Thank you for bringing this to our attention. We have pushed a fixed that will be included in the next Commerce release.

Thanks!
