### ISSUE TITLE
UI Issue - First/Last Name fields don't show up initially in payment modal

### ISSUE THREAD

**Issue by jalendport** [craftcms/commerce#2603]
If you click the "Make a Payment" button on an order's "Transactions" tab, the fields for First Name and Last Name don't show up until you toggle to another gateway and then back:

### What I'm seeing:
![image](https://user-images.githubusercontent.com/6537823/140418367-dfa777ff-3cbe-4ca2-afc9-56135ed94f20.png)

### What I expect to see:
![image](https://user-images.githubusercontent.com/6537823/140418439-f20a5161-5a0e-45c3-9bae-dcf6aebb7e13.png)

The issue appears to be some CSS that is only being applied when the gateway is switched, and not when the modal is first opened:

![image](https://user-images.githubusercontent.com/6537823/140418709-2acb97a5-0d85-43e3-b149-1f94f98695c3.png)

This is using the Stripe gateway, so it's possible this issue belongs in that repo...

### Additional info

- Craft CMS version: 3.7.17.2
- Craft Commerce version: 3.4.6
- PHP version: 7.4.15
- Database driver & version: MySQL 5.5.5

**Comment by jalendport** [comment]
My best guess is that [this line](https://github.com/craftcms/commerce/blob/3602efdaa3385839031a48687daaaedafe3a178d/src/web/assets/commercecp/src/js/CommercePaymentModal.js#L52) in the JS is not firing correctly or firing too soon (perhaps it just needs to be added the following timeout?)...

**Comment by nfourtythree** [comment]
Hi @jalendport 

Thank you for reporting this issue. We have pushed a fix that will be included in the next release of Commerce.

Thanks!
