### ISSUE TITLE
Programatically creating line items with min/max qty restrictions set doesn't work

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#2604]
### Description
We have a use-case where we add items to the cart through a module. When a product has been setup with min/max qty restrictions, validation fails to add the line item.

To start, pick a product and set the "Allowed Qty" to 2 and 4 (min/max).

Then, add the code below to a module. Replace the `purchasableId` to the product's variant you just restricted.

```php
use craft\commerce\Plugin as Commerce;

$cart = Commerce::getInstance()->carts->getCart();
$purchasableId = 4;
$qty = 3;

$lineItem = Commerce::getInstance()->getLineItems()->createLineItem($cart->id, $purchasableId, [], $qty);
Commerce::getInstance()->getLineItems()->saveLineItem($lineItem);

Craft::dd($lineItem->getErrors());
```

You'll receive the following error:
```
[
    'qty' => [
        0 => 'Minimum order quantity for this item is 2.'
    ]
]
```

I believe this is due to the following code:

https://github.com/craftcms/commerce/blob/9f2414241d997fd46b56dcfe80cfb11bda34f842/src/elements/Variant.php#L771-L781

Here, it only takes into account line items that already exist on the order. As we're creating a new line item, `$qty = 0`. I'm not sure on the ramifications of doing:

```php
$getQty = function(LineItem $lineItem) {
    $qty = 0;
    foreach ($lineItem->getOrder()->getLineItems() as $item) {
        ...
    }
    if (!$qty && $lineItem->qty) {
        $qty = $lineItem->qty;
    }
    return $qty;
};
```

### Additional info
- Craft CMS version: 3.7.20
- Craft Commerce version: 3.4.7
- PHP version: 7.2

**Comment by engram-design** [comment]
Actually, after double checking Commerce's controller, we should be doing:

```
$lineItem = Commerce::getInstance()->getLineItems()->createLineItem($cart->id, $purchasableId, [], $qty);
$cart->addLineItem($lineItem);

Commerce::getInstance()->getLineItems()->saveLineItem($lineItem);
```

So that the cart knows about the new line items. That solves that! 😅

**Comment by ezequiel9** [comment]
Hi, Sorry for doing this, I have spent several hours trying to add an item from my module and I cannot make it work. 

Craft commerce 4
PHP 8.2

```php
$cart = Plugin::getInstance()->getCarts()->getCart();
$lineItemInstance = Plugin::getInstance()->getLineItems();
$lineItem = $lineItemInstance->createLineItem($cart, $variant->id, [], 60);
$cart->addLineItem($lineItem);
Plugin::getInstance()->getLineItems()->saveLineItem($lineItem);
dd(Plugin::getInstance()->getCarts()->getCart());
```

That code seems to work well, but wen I go the the front end and try to see the order item I have added above, its empty. No items are saved in my cart.

How can I solve it?
