### ISSUE TITLE
Unable to use EVENT_DEFINE_IS_DELETABLE

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#2606]
Craft added `EVENT_DEFINE_IS_EDITABLE` and `EVENT_DEFINE_IS_DELETABLE` in 3.7: https://github.com/craftcms/cms/issues/8023

Although when trying to hook into the `EVENT_DEFINE_IS_DELETABLE` event for commerce elements it is not working, would I be right in thinking, that even though the elements support the new event, that the various controllers would need to be updated to use `getIsDeletable()` to trigger this event.

I can use the `beforeDelete` event to prevent a delete under certain conditions, and although this works, the CP does display both the `Product Deleted` & `Product could not be deleted` flashes.

**Comment by pdaleramirez** [comment]
@samhibberd You are right. Although the event `EVENT_DEFINE_IS_DELETABLE` is called on the base element class and wrapped with the `getIsDeletable` method, the method has to be implemented on a Controller class. The `getIsDeletable` is not used in any Commerce controllers. I can see it is being use on the CMS Entry Controller class. We'll add this event as an enhancement

**Comment by samhibberd** [comment]
@pdaleramirez looks like the same deal for `EVENT_DEFINE_IS_EDITABLE` and the `getIsEditable()` method in commerce controllers and UI.

**Comment by pdaleramirez** [comment]
The event has been implemented since version 3.4.8 changelog here https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#348---2021-11-25
