### ISSUE TITLE
Base example templates that can be extended.

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#261]
> Created by: Jae Barclay ([jae@ejaedesign.com](jae@ejaedesign.com)) on 2015/05/04 12:08:57 +0000
Votes at time of UserVoice import: 6

------

**Comment by andris-sevcenko** [comment]
> Created by: Luke Holder ([luke@pixelandtonic.com](luke@pixelandtonic.com)) on 2016/01/06 22:53:19 +0000


------
Jae Barclay: Craft Commerce comes with example templates, if you are aware of this could you expand on what type of downloadable templates you expect?

**Comment by andris-sevcenko** [comment]
> Created by: Hagen Rode ([hagen00@gmail.com](hagen00@gmail.com)) on 2016/09/26 11:59:57 +0000


------
Hi Luke, I would think that you would just want to massively expand the existing templates. Specifically on product listing I.e filtering (category, brand, various SKUs), sorting, pagination (SEO friendly). On product view,  showing how to select SKU from drop-downs (e.g. size/color dropdown) etc

**Comment by lukeholder** [comment]
We aren't going to make extendable templates but looking into attributes and values being first party which would enable better example templates.
