### ISSUE TITLE
getSalesForPurchasable returns incorrect data

### ISSUE THREAD

**Issue by joepagan** [craftcms/commerce#2611]
### Description

If I delete a matched item on a Sale which has 1 variant tied to it save the `Sale` in the dashboard:

![image](https://user-images.githubusercontent.com/2337910/142208532-831d42fd-a4e0-487b-9023-36906c7d02fc.png)

Then call:

```
Commerce::getInstance()->sales->getSalesForPurchasable($variant)
```

It returns a `Sale` which has the detached `Variant` tied to it.

### Additional info

I did look for a related change in the changelog before posting, appreciate i'm a few versions behind but not in a position to update at the moment

- Craft CMS version: "craftcms/cms": "3.7.13",
- Craft Commerce version: "craftcms/commerce": "3.4.2",
- PHP version: 8.0.12
- Database driver & version: mysql:5.7.27
- Plugins & versions:

**Comment by lukeholder** [comment]
Hmm, I am thinking this is expected behavior.

The field description says:

>  Leave all purchasable fields blank for any purchasable

so calling `getSalesForPurchasable($variant)` will still match the variant since the sale applies to all purchasables in the system.

Am I missing something?

**Comment by lukeholder** [comment]
Maybe you are looking for `ommerce::getInstance()->sales->getSalesForPurchasable($variant)`?

**Comment by lukeholder** [comment]
@joepagan Yes, we have that on the list to do in the Commerce 4 beta. It is a slight change in behavior so doing it then.

**Comment by joepagan** [comment]
@lukeholder fantastic, thanks for the heads up.
