### ISSUE TITLE
Limiting discounts to "all of these groups" behaves weirdly

### ISSUE THREAD

**Issue by aelvan** [craftcms/commerce#2614]
### Description

When creating a discount with a discount code, and limiting it to user groups using "Users in all of these groups", it appears that the user can _only_ belong to the groups selected. Ie, if the user belongs to group "GroupA" and "GroupB", and you select "GroupA" on the discount, it's not be applicable for the user. If the user only belongs to "GroupA", it also works. If you change it to "Users in any of these groups", the discount works. 

This seems like a bug, _or_ bad wording in the select options? 

What I would expect is (given the example user above):

"Users in all of these groups" + "GroupA" = Applicable
"Users in all of these groups" + "GroupA" and "GroupB" = Applicable
"Users in all of these groups" + "GroupA", "GroupB" and "GroupC" = Not applicable

### Steps to reproduce

1. Create a user that belongs to group "GroupA" and "GroupB".
2. Create a discount with a discount code, and a limitation on "Users in all of these groups" and select "GroupA"
3. Add a product to the cart, and add the discount code.

### Additional info

- Craft CMS version: 3.7.20
- Craft Commerce version: 3.4.7
- PHP version: 8.0.8 & 7.4.25
- Database driver & version: MySQL 5.5.5 (MariaDB 10.5.8)
- Plugins & versions: -

**Comment by pdaleramirez** [comment]
@aelvan This is actually the expected behavior, If you select the option "Users in all of these groups" and your selection is Group A and Group B, the user must be in both group to apply the discount. If the user is only in Group A, the discount doesn't get applied.

**Comment by aelvan** [comment]
@pdaleramirez Yes, the way you describe it is the way I expected it to work. But it's not the way it works for me at the moment.

What I'm describing is that if I select the option "Users in all of these groups", the selection _on the discount_ is "Group A", and the user is in group "Group A" _and_ "Group B", the discount is not applied.

**Comment by pdaleramirez** [comment]
@aelvan That is the correct behavior the discount group selection must match the user's group.

**Comment by aelvan** [comment]
I understand that it's the expected behaviour – if it's the correct one is a matter of interpretation. It feels extremely weird to me that the the boundary of the selection works on both the discount and the user, and it seems to leave a hole in the discount functionality. To show what I mean, let's use a simplified version of my use case which triggered this issue. 

A shop has a customer club which in itself grants certain discounts if you're a member. Different conditions also grant additional discounts. Users are added and removed to different groups based on API calls to the third party club service. Some discounts are not exclusive to club members, and could apply to all customers, but at a different rate. So let's say I have the following three groups/conditions set up (again, this is simplified):

Club members are added to the group "Club members".
Customers who purchased a product in-store within the last three months gets added to the "Recent customer" group (applicable to both club members and normal customers).
Customers who signed up for the newsletter is added to the "Newsletter Signup" group (applicable to both club members and normal customers).

User 1 is member of "Club members" and "Recent customer".
User 2 is member of "Club members", "Recent customer" and "Newsletter Signup".
User 3 is member of "Club members".

Now, if I want to create a discount that applies to users that are members of both "Club members" and "Recent customer", the logical solution would be to use "Users in all of these groups" and select those two groups. But that would disqualify User 2, which is also member of the "Newsletter Signup" group. If I were to use "Users in any of these groups", all the users would get the discount, which isn't what I want. I could add duplicate discounts for all the different combinations of groups, but that is completely untenable from the client perspective when you get more than a handful of different conditions to take into account. 

I understand that changing the way that "Users in all of these groups" works now could potentially break peoples discounts, but I think maybe that option should be renamed, and a new one added. The one that's there now is more like "Users exclusively in all of these groups".
