### ISSUE TITLE
Promotions: Default "empty" condition should not then apply to all products

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/commerce#2615]
### Description
This is more a suggestion / topic than a bug as Commerce is doing what it "should" be doing, I just don't think what is "should" do is a safe choice...

We've had this a few times, where a client has removed products from a promotion and ended up with no conditionals in the promotion. They've then had *every product on the site* listed and purchasable for 0 money. Because the default behaviour with no conditionals is to apply to all items.

Applying a discount to all items is _dangerous_ and I feel ought to be protected by an explicit opt-in; not simply a lack of conditions. It should be a hard mistake to make to have all your products listed and purchasable for free... not something that's happened a few times by doing what to a client feels like something unrelated - removing an item from promotion.

**Comment by lukeholder** [comment]
Agree, we will put the purchasable selection behind a 'All Purchasables' checkbox. Unchecking it will show the purchasable selection input. Same with Categories. Will be in next release.

**Comment by MattWilcox** [comment]
Great stuff Luke, thanks so much.

**Comment by lukeholder** [comment]
Fix is in draft at https://github.com/craftcms/commerce/pull/2634

**Comment by nfourtythree** [comment]
Hi @MattWilcox 

This update was included in the `3.4.9` release of Commerce which is now out.

Thanks!
