### ISSUE TITLE
Order Condition Formula fails validation if it contains a date filter

### ISSUE THREAD

**Issue by simple-nicholas** [craftcms/commerce#2616]
### Description
Further to https://github.com/craftcms/commerce/issues/2505, using a date filter gives the error "Invalid order condition syntax".

**Comment by pdaleramirez** [comment]
@simple-nicholas The correct syntax for the condition should be
```
'2021-10-01'|date > order.eventDate|date("Y-m-d")
```
You need to add the `|date` filter
