### ISSUE TITLE
Demonstrable import/export workflow

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#262]
> Created by: Jae Barclay ([jae@ejaedesign.com](jae@ejaedesign.com)) on 2015/05/04 11:59:05 +0000
Votes at time of UserVoice import: 46

------
To import/export product catalog via JSON, XML, CSV, etc.

**Comment by andris-sevcenko** [comment]
> Created by: Chandra McFarlen ([chandra.mcfarlen@drivesimplicity.com](chandra.mcfarlen@drivesimplicity.com)) on 2015/06/16 19:46:57 +0000


------
The ability to schedule imports would be extremely helpful!

**Comment by andris-sevcenko** [comment]
> Created by: Øyvind Østmo ([oyvind@redrabbits.com](oyvind@redrabbits.com)) on 2015/11/20 11:04:16 +0000


------
Super important! At our agency, even working with small brands, they all need their shop integrated with their internal systems (ERP).

**Comment by andris-sevcenko** [comment]
> Created by: Russ Back ([russ@rallyagency.co.uk](russ@rallyagency.co.uk)) on 2015/12/03 19:57:14 +0000


------
Could apply to orders too, for fulfilment systems.

**Comment by andris-sevcenko** [comment]
> Created by: Adam Menczykowski ([adammenczykowski@gmail.com](adammenczykowski@gmail.com)) on 2017/02/23 13:10:30 +0000


------
Feed Me https://github.com/engram-design/FeedMe can consume XML, RSS, ATOM or JSON feeds and could presumably update the product catalog. This is for import only. Presumaby using Craft&#39;s own Element API plugin could be used as a way to share a JSON feed of products too?

**Comment by lukeholder** [comment]
Recommend FeedMe: https://plugins.craftcms.com/feed-me
