### ISSUE TITLE
Multi-store (shared catalog across multi-domain)

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#263]
> Created by: Jae Barclay ([jae@ejaedesign.com](jae@ejaedesign.com)) on 2015/05/04 11:48:28 +0000
Votes at time of UserVoice import: 14

------
A "master" catalog should have "branches" of product subsets that can be made available across multi-domains. 

For example, if I have a catalog of pet-related products, I should be able to manage it in a single Craft site/instance, yet be able to share a subset of my catalog to a separate site that only caters to larger dogs or to another site that sells pet clothing items.

**Comment by watarutmnh** [comment]
At slack channel, I learned that each site would share the same store, but products can be disabled in particular sites. But It would be nicer if we could set different price across multi-domains.
In my case, I want to have multiple stores for different regions and need to have products having different prices due to distribution contract.

**Comment by lennartlott** [comment]
This Feature would take Craft Commerce to a new level.

Each site should have its own product pricing and its own order management incl. order numbers.

**Comment by samuelbirch** [comment]
Allowing the ability to set the price per site would be great, and as an addition to this perhaps the ability to define a currency per site?

**Comment by outline4** [comment]
We would need a multi-store where you can set different prices/stock/shipping per site. In fact everything should be customizable per site. This would make international stores possible. At the moment we have separate installs per country. Sharing data over multiple stores would be a plus!

**Comment by benshrimpton** [comment]
@outline4 Second that! I thought Craft Commerce did this with the Multi Site native Craft feature, but it turns out, thats not the case. Make that possible... and goodbye Magento.

**Comment by lukeholder** [comment]
Discussion will continue in #37
