### ISSUE TITLE
The Manual gateway throws an error if Craft version < 3.7.22

### ISSUE THREAD

**Issue by ragnarfrosti** [craftcms/commerce#2638]
### Description
The function `availableForUseWithOrder()` uses the function `Craft::parseBooleanEnv` which was introduced in Craft 3.7.22.

We use that gateway when users pay their orders using invoice. This change broke production when we updated Commerce to latest point release while running Craft 3.7.18.

Commerce requirements are Craft 3.7.0.

**Comment by nfourtythree** [comment]
Hi @ragnarfrosti 

Thank you for bringing this to our attention. We have just released version `3.4.9.1` which should fix this issue.

Thanks!
