### ISSUE TITLE
Can't scroll inside "Transactions Info" window

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce#2639]
### Description
When accessing the transactions info window, it isn't possible to scroll the box. This makes reading the Gateway Response impossible without inspecting the source code.
<img width="845" alt="Screenshot 2021-12-15 at 09 26 55" src="https://user-images.githubusercontent.com/5698596/146161051-9d2cf6ff-908a-42c7-bbc0-97443774ef7b.png">

### Steps to reproduce

1. Access an order > transactions
2. Click the transaction info.
3. Cannot scroll window if there is a long/wide or unformatted/structured Gateway Response which is normally the case.

**Comment by nfourtythree** [comment]
Hi @terryupton 

Thank you for bringing this to our attention. 

We have pushed a fix for this which will be included in the next release of Commerce.

Thanks!
