### ISSUE TITLE
Catalog localization out of the box

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#264]
> Created by: Jae Barclay ([jae@ejaedesign.com](jae@ejaedesign.com)) on 2015/05/04 11:44:17 +0000
Votes at time of UserVoice import: 9

------
Content localization is already in place. Catalog in CC (Craft Commerce) should also be, right out of the box.

**Comment by lukeholder** [comment]
Commerce Products support multi-site, including translation. Full multi-site support should be a separate FR.
