### ISSUE TITLE
Order details not shown in the CMS (JS error: Uncaught ReferenceError: process is not defined)

### ISSUE THREAD

**Issue by mdominguez** [craftcms/commerce#2640]
### Description
After updating Commerce from 3.4.7 to 3.4.9.1 I get a JS error when viewing order details in the CMS.
[View screenshot](https://share.getcloudapp.com/NQuxLx1G)

### Steps to reproduce

1. Update to 3.4.9.1
2. Check the details of an order through /admin/commerce/orders/xxx

### Additional info

- Craft CMS version: 3.7.25.1
- Craft Commerce version: 3.4.9.1 (at 3.4.7 it worked fine)
- PHP version: 8.0
- Database driver & version: 
- Plugins & versions:

**Comment by nfourtythree** [comment]
Hi @mdominguez 

Thank you for bringing this to our attention we have pushed a new version of Commerce `3.4.9.2` that addresses this issue.

Thanks!

**Comment by bossanova808** [comment]
Gotta say folks, even the literally most basic amount of testing would and should have picked this up....appreciate the quick fix but c'mon....

**Comment by boboldehampsink** [comment]
@bossanova808 agreed, I have a feeling this happens a lot on the Commerce team
