### ISSUE TITLE
Sales promotion "All Purchasables cannot be blank"

### ISSUE THREAD

**Issue by jerome2710** [craftcms/commerce#2653]
### Description
One of our clients reported that he is not able to save a sales promotion for specific purchasables or categories. The checkbox for "all" seems to be required:

![Schermafbeelding 2021-12-24 om 15 42 03](https://user-images.githubusercontent.com/4600095/147359889-3fea11c7-daf2-4c71-9f35-4e14950fa7e3.png)

### Steps to reproduce

1. Create a new sales promotion
2. Disable "All purchasables" and select one or more specific purchasables
3. Save the promotion

### Additional info

- Craft CMS version: Craft Pro 3.7.26
- Craft Commerce version: 3.4.9.2
- PHP version: 8.0.13
- Database driver & version: MySQL 8.0.26
- Plugins & versions: verbb/giftvoucher 2.7.0 and others

**Comment by nfourtythree** [comment]
Hi @jerome2710 

Thank you for your message.

This issue was resolved in the `3.4.9.3` release of Commerce, please update to this version to resolve the issue.

I will close this issue for now, please comment here if it persists after updating.

Thanks!

**Comment by jerome2710** [comment]
I can confirm that after the update this works again, thanks!
