### ISSUE TITLE
Breaking change in PDF generation since 3.4.7

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/commerce#2654]
### Description
Since this commit:
https://github.com/craftcms/commerce/commit/8ef93c61ecf9aa0108606a27194a24aaac69e2db

Our integration has stopped working. It's because the method allows the parameter `$pdf` to be a null, which for us is fine, we render the template from the template path, rather than from a CMS configured template.

However, since these lines where added
```
        $pdfLanguage = $pdf->getRenderLanguage($order);
        Locale::switchAppLanguage($pdfLanguage);
```

We're calling getRenderLanguage on a null, causing a 500 error. Can we adjust this behavior a little bit so it honors the nullible param?

```
if($pdf !== null) {
        $pdfLanguage = $pdf->getRenderLanguage($order);
        Locale::switchAppLanguage($pdfLanguage);
 }
 ````

**Comment by lukeholder** [comment]
Going to combine this with https://github.com/craftcms/commerce/issues/2633
