### ISSUE TITLE
Internal server error when saving a discount with All categories switch off

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#2660]
### Description

Getting an internal server error when trying to save a discount with the **All categories** lightswitch off. Found the corresponding error in logs:
`[error][yii\db\IntegrityException] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'allCategories' cannot be null...`

### Additional info

- Craft CMS version: Pro 3.7.28
- Craft Commerce version: Pro 3.4.9.3
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for your message.

I can't seem to reproduce this error, see the video below:

https://user-images.githubusercontent.com/266453/148737445-bd7341de-b5d1-4054-8c6d-811c34c6372a.mp4

However, I have pushed up a couple of fixes to completely make sure that what you are seeing is not possible. This update will be included in the next release of Commerce.

Thanks!

**Comment by jmauzyk** [comment]
@nfourtythree that did the trick, thanks!
