### ISSUE TITLE
I am running a single site on craft commerce but when I try to save a product It gives me this error 

### ISSUE THREAD

**Issue by azazelA** [craftcms/commerce#267]
### Description
After recently updating commerce I'm starting to get error when try to save a new product 

<img width="869" alt="screen shot 2018-03-28 at 11 18 44 pm" src="https://user-images.githubusercontent.com/19649989/38049063-9b344f20-32e0-11e8-8392-86f93152b67a.png">

### Steps to reproduce

1. Go to Commerce > Products > New Product
2. Fill in the fields 
3. Click Save

### Additional info

- Commerce version: dev-develop as 2.0.0-alpha.99
- Craft version: 3.0.0-RC16.1
- PHP version: 7
- Database driver & version: Postgres 
- Plugins & versions: Stripe, Similar, Postmark, Craft Commerce, CKEditor, Architect

**Comment by lukeholder** [comment]
please `composer update` and it should be fixed. 

cc @magnessjo

**Comment by azazelA** [comment]
I've already done that part, I just updated to RC17 but the error exists

**Comment by lukeholder** [comment]
@azazelA RC17 is the craft version, you need to update commerce with `composer update`

**Comment by lukeholder** [comment]
`composer clear-cache` first if it's not picking it up
@azazelA

**Comment by azazelA** [comment]
Okay Its fixed now! Thanks
