### ISSUE TITLE
Set default "free" shipping method

### ISSUE THREAD

**Issue by clarknelson** [craftcms/commerce#2672]
### Description

We have two custom shipping methods on our site, "no shipping" and "in-store pick up". Both are free so Craft doesn't always know which to apply. We would like the "no shipping" option to be applied if available. Is there a way to set the "default" shipping method? I imagine there might be a system similar to shipping product types with a default option to select. Also, is there a way I can resolve this using a plugin? We are already heavily relying on a custom plugin so I can add some code to make this distinction if needed.

### Steps to reproduce

1. Two product types. One (Events) makes available the "no shipping" option. Another (Products) has available pick-up. 
2. I would "disallow" the pick up options for the events type, but if you have both in the cart, you may want to pick up.
3. When only "events" are in the cart, it is inconsistent as to whether the "no shipping" or "pick up" option is selected. We would prefer if the "no shipping" option was selected for other logic in out system.

### Additional info

- Craft CMS version: 3.7.28
- Craft Commerce version: 3.4.10.1
- PHP version: 7.4.27
- Database driver & version: mysql 5.5.5

**Comment by pdaleramirez** [comment]
@clarknelson The quickest solution would be to add hidden input shipping method value in update-cart form

```
            {% for handle, method in cart.availableShippingMethodOptions %}
              {% if handle == 'freeShipping' %}
                {{ hiddenInput('shippingMethodHandle', handle) }}
              {% endif %}
            {% endfor %}
```

if freeShipping is available it is always selected as default when form is submitted.
