### ISSUE TITLE
Memoization cache in `LineItems::getAllLineItemsByOrderId()` causes memory leak

### ISSUE THREAD

**Issue by khalwat** [craftcms/commerce#2673]
### Description

I'm writing an exporter for Commerce Orders that needs to call `getAllLineItemsByOrderId()` for each order as they are processed for export.

In the export, I'm using `Db::each()` and using a [generator function](https://www.php.net/manual/en/language.generators.overview.php) to keep the memory usage low so a large number of orders can be exported.

Unfortunately, there's a memory leak caused by memoization of line items in `getAllLineItemsByOrderId()`:

https://github.com/craftcms/commerce/blob/develop/src/services/LineItems.php#L155

```php
    public function getAllLineItemsByOrderId(int $orderId): array
    {
        if (!isset($this->_lineItemsByOrderId[$orderId])) {
            $results = $this->_createLineItemQuery()
                ->where(['orderId' => $orderId])
                ->orderBy('dateCreated DESC')
                ->all();

            $this->_lineItemsByOrderId[$orderId] = [];

            foreach ($results as $result) {
                $result['snapshot'] = Json::decodeIfJson($result['snapshot']);
                $lineItem = new LineItem($result);
                $lineItem->typecastAttributes();
                $this->_lineItemsByOrderId[$orderId][] = $lineItem;
            }
        }

        return $this->_lineItemsByOrderId[$orderId];
    }
```

This causes PHP to fall over after only ~500 orders are exported with 256MB allocated to it. Obviously increasing this will help, but it's only a matter of time before the limit is reached.

This is because the query results memoized by `$orderId`, so when iterating through orders, the memory usage just keeps going up.

Here's what it looks like doing the export with the memoization in (unmodified Commerce):

https://user-images.githubusercontent.com/7570798/150935609-c9913ff3-b16d-4a94-9e33-658cb473a5b8.mov

You can see the memory usage going up consistently with each Order that's being exported.

Now here's what the memory usage looks like for the same export if I strip memoization out of `LineItems::getAllLineItemsByOrderId()`:

https://user-images.githubusercontent.com/7570798/150935698-d24bcebf-3cea-4353-a811-1faaa61f2a94.mov

You can see the memory usage going up a little, then dropping back down as garbage collection kicks in, and staying constant overall for the entire export.

### Potential solutions:

1. Have a flag or setting to disable memoization in Commerce for the times when a large report or export of Orders needs to be done
2. Have a method in the `LineItems` service that allows you to clear the memoization cache
3. Perhaps Commerce could be using [MemoizableArray](https://github.com/craftcms/cms/blob/develop/src/base/MemoizableArray.php) and some kind of memory check could be added to that base class to ensure the memoization doesn't run wild with memory use.

### Steps to reproduce

1. Loop through a few thousand Commerce orders
2. Call `getAllLineItemsByOrderId()` for each order in the loop
3. Monitor memory usage with `memory_get_usage()`

### Additional info

- Craft CMS version: 3.7.28
- Craft Commerce version: 3.4.9.3
- PHP version: 8.x
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by lukeholder** [comment]
Yeah the method was designed for short running requests dealing with the (usually) same  order ID (usually the cart), but we have memoization in the `$order->getLineItems()` anyway, so it is pretty unnecessary in that regard. The only place we call the method is in `$order->getLineItems()` also.

I am going to remove the memoization from the method in 4.0 and leave it to the caller, but in the meantime I added a cache cap 932ec52 for 3.4.x (the next release).
