### ISSUE TITLE
Subscription element's $userId property is a string, but is documented as an int

### ISSUE THREAD

**Issue by mtnorthrop** [craftcms/commerce#2679]
### Description
The `$userId` property of `craft\commerce\elements\Subscription` is declared as an `int` in its docblock, but actually returns a string when the property is read.

The `$userId` property:
https://github.com/craftcms/commerce/blob/932ec524c16d5376756ddd1cee4807b9564ba54f/src/elements/Subscription.php#L69-L72

### Steps to reproduce

Fetch a subscription element and dump it:
```php
$subscription = Subscription::find()->uid($uid)->one();
Craft::dump($subscription);
Craft::dump(is_int($subscriptionElement->userId));
```

Output:
```
craft\commerce\elements\Subscription#1
(
    [userId] => '6684'
    ...
)

false
```
This issue was addressed in #1650, but it doesn't look like the underlying problem of the `$userId` property being incorrectly documented was fixed.

When trying to compare this value with a User element's ID, for example, it's currently possible to get around the issue by using a loose comparison (`==` instead of `===`) or by typecasting the `$userId` property with `(int)`, but some confusion could be avoided if the property's docblock matched its contents.

### Additional info

- Craft CMS version: 3.7.29
- Craft Commerce version: 3.4.10.1
- PHP version: 7.4.3

**Comment by pdaleramirez** [comment]
@mtnorthrop On Commerce 4 will be adding typed properties to classes making the userId to be the correct type. On Commerce 4 PHP requirement will be 7.4 which supports typed properties.
