### ISSUE TITLE
Can I delete a 'product type' without deleting products it is associated with?

### ISSUE THREAD

**Issue by mdunbavan** [craftcms/commerce#2680]
### Description
I am trying to trim down a huge list of product types that were created on a legacy site I worked on a while back(9 months ago). I am trying to take 18 product types and trim them down to about max 3 types across the site.

The trouble is when I try and delete the type, commerce tells me it will delete its associated products which is not what I want.

### Steps to reproduce

1. Log into Craft cpanel
2. Go to commerce->system-settings
3. Go to Product types and click the 'x' next to the type.

### Some expected behaviour if possible

Ideally there would be a way to transfer the products to a new type. A bit like how when you delete a user you can transfer their data to another user. I'm not sure if that would be possible?

I am open to ideas and also fine with doing something that might mean writing a migration to migrate all products to a specific type?

### Additional info

- Craft CMS version: 3.7.30.1
- Craft Commerce version: 3.4.10.1
- PHP version: 8.0.6
- Database driver & version: MySQL 5.7.31

### Proposed migration idea

Create a migration that loops through products and inserts the new id into the typeId for each product eg below:

```
public function safeUp()
    {
        // Steps to do the job
        // 1. Find all products that are available
        // 2. Loop through each product and Find its product type id
        // 3. Create data to assign to the products product and set the typeId to the default type id
        // 4. Update products and insert data.

        $db = Craft::$app->getDb();
        $defaultTypeId = 82;
        $catsByProductTypeId = [];

        $products = Product::find()->limit(null);
        foreach ($products->each() as $product) {
            $productData = [
                'id' => $product->id,
                'typeId' => $defaultTypeId
            ];

            // Insert the actual product and variant
            $this->insert(ProductRecord::tableName(), $productData);
        }


    }
```

Would this work? Would this possibly break everything? What other places would I need to look out for if trying to change typeId, are there other tables that rely upon the type id and would they concurrently need updating to use the same id as the product typeId too?

**Comment by pdaleramirez** [comment]
@mdunbavan You can create a migration to update the columns to the product type id for the products. Make sure that the product types that is being transferred to has the same setup such as having multiple variants otherwise there will be issues.

You can replace the commerce_products : **typeId** column to the new typeId and other tables with the column **productTypeId** you can checkout the Install migration https://github.com/craftcms/commerce/blob/develop/src/migrations/Install.php on which tables have those column

**Comment by mdunbavan** [comment]
@pdaleramirez I have updated the migration file. Does this look as expected:

```
public function safeUp()
    {
        // Steps to do the job
        // 1. Find all products that are available
        // 2. Loop through each product and Find its product type id
        // 3. Create data to assign to the products product and set the typeId to the default type id
        // 4. Update products and insert data.

        $db = Craft::$app->getDb();
        $defaultTypeId = 82;
        $catsByProductTypeId = [];

        // Loop through and change product typeId

        $products = Product::find()->limit(null);
        foreach ($products->each() as $product) {
            $productData = [
                'id' => $product->id,
                'typeId' => $defaultTypeId
            ];

            // Insert the actual product and variant
            $this->insert(ProductRecord::tableName(), $productData);
        }

        // Loop through sites and assign producttypeId with new one
        $productTypeSites = (new Query())
            ->select(['id', 'name', 'handle'])
            ->from(['{{%commerce_producttypes_sites}}'])
            ->all();
        
            if ($productTypeSites) {
                foreach ($productTypeSites as $productTypeSite) {
                    $productTypeSite->productTypeId = $defaultTypeId;
                }
            }
        
        $productTypeShippingCategories = (new Query())
            ->select(['id', 'name', 'handle'])
            ->from(['{{%commerce_producttypes_shippingcategories}}'])
            ->all();

            if ($productTypeShippingCategories) {
                foreach ($productTypeShippingCategories as $productTypeShippingCategory) {
                    $productTypeShippingCategory->productTypeId = $defaultTypeId;
                }
            }

        $productTypeTaxCategories = (new Query())
            ->select(['id', 'name', 'handle'])
            ->from(['{{%commerce_producttypes_taxcategories}}'])
            ->all();

            if ($productTypeTaxCategories) {
                foreach ($productTypeTaxCategories as $productTypeTaxCategory) {
                    $productTypeTaxCategory->productTypeId = $defaultTypeId;
                }
            }


    }
```

**Comment by mdunbavan** [comment]
Managed to get the migration to run

```
$products = Product::find()
            ->all();
        foreach ($products as $product) {
                $product->typeId = $defaultTypeId;
                // Insert the actual product and variant
                // $this->insert(ProductRecord::tableName(), $productData);
                if(Craft::$app->elements->saveElement($product)) {
                    echo 'Successfully saved product<br />';
                } else {
                    throw new \Exception("Couldn't save product: " . print_r($product->getErrors(), true));
                }
        }
```
