### ISSUE TITLE
Sale price not applying to product

### ISSUE THREAD

**Issue by clarknelson** [craftcms/commerce#2695]
### Description
I have everything configured correctly as far as I can tell in the dashboard.

**Product Page**
![Screenshot from 2022-02-09 10-34-07](https://user-images.githubusercontent.com/4106671/153247716-49e39802-4856-4b5d-9e7c-649856d466ef.png)

**Discount**
![Screenshot from 2022-02-09 10-26-30](https://user-images.githubusercontent.com/4106671/153247841-4cee51ff-4929-4179-9fcd-19d66b0c3a9f.png)

But on the front-end, it doesn't look like the sale is being applied to the variant.
![Screenshot from 2022-02-09 10-48-36](https://user-images.githubusercontent.com/4106671/153249064-c19927de-05b6-4a09-89ac-6f7a10459a9a.png)

I've tried clearing the cache, re-creating the sale, re-saving the products, nothing seems to work. Do you have any idea how to fix this?

### Additional info

- Craft CMS version: 3.7.28
- Craft Commerce version: 3.4.10.1
- PHP version: 7.4
- Database driver & version: MySQL 5.7

**Comment by pdaleramirez** [comment]
@clarknelson It should get applied when you add the product to the cart or you can display it on the template as

```
{{ product.defaultVariant.salePriceAsCurrency }}
```

As long as you set up matching items in your sale setting

**Comment by lukeholder** [comment]
Can you screenshot the other conditions in the discount edit page:
![CleanShot 2022-02-11 at 17 36 34@2x](https://user-images.githubusercontent.com/133571/153568454-671b8d80-ac22-4e67-a624-fb4f49184240.png)
?

**Comment by clarknelson** [comment]
No problem!
![Screenshot from 2022-02-11 07-52-46](https://user-images.githubusercontent.com/4106671/153603555-42c3a5e3-114e-44ab-a57b-a675ebf20e95.png)

**Comment by pdaleramirez** [comment]
@clarknelson @rynpsc Can you check if the promotable switch in product page it turned on?
![Parka With Stripes On Back - Commerce Dev](https://user-images.githubusercontent.com/4172750/154041480-b67fc75b-6e35-4ff0-84b7-8215b53da48d.png)

**Comment by rynpsc** [comment]
Yes, promotable is turned on.

**Comment by clarknelson** [comment]
yes I can also confirm that toggle is checked
![Screenshot from 2022-02-15 09-16-10](https://user-images.githubusercontent.com/4106671/154091449-0eee51fe-5c9d-41b1-bbf3-2b4fc4c53df0.png)

**Comment by pdaleramirez** [comment]
@clarknelson Please send your db to support@craftcms.com we'll try to reproduce the issue and debug further.

**Comment by clarknelson** [comment]
Okay I just sent you a copy

**Comment by pdaleramirez** [comment]
The issue was the Discounts -> Matching Items -> All Categories is turned off.

**Comment by rynpsc** [comment]
Will there be a fix for this? Based on the instructions in the CP leaving the toggle off but not choosing any categories should still work, so it looks to be a bug or the instructions need to corrected.

> Categories that the purchasables must be related to. Leave blank for all categories.

![commerce-discount-categories](https://user-images.githubusercontent.com/5955881/155131497-b765d926-ddbc-45f9-bc06-c54e613b92bb.png)

**Comment by clarknelson** [comment]
Same here, there might be an issue. I have two sales, both with "all purchasables" selected. They have different categories selected though. I have a 25% discount for "z" products and a 50% discount for "y" products. When I add a "z" product to my cart and apply the "z" code it looks to work. But when I apply the "y" code it also applies to the z product. I believe this is because "all purchasables" is selected?

**Comment by joepagan** [comment]
I just had this also in
```
"craftcms/cms": "3.7.32",
"craftcms/commerce": "3.4.11",
````
Might have just been some crazy caching or something but...
A brand new £1 flat price sale with 100% coverage of products/categories/users was not being honoured.
I disabled all other sales... no change to price
I deleted all the disabled sales... sale price comes through...

**Comment by clarknelson** [comment]
These are my versions, I am realizing we are a bit out of date. I will update and see if there is a difference. 
```
"craftcms/cms": "3.7.28",
"craftcms/commerce": "3.4.10.1",
```

**Comment by joepagan** [comment]
To add to this further, after deleting everything and making a single new promotion sale, I can also confirm that the "all categories" lightswitch needs to be `on` in order for the sale to work, despite the field description:
>Leave blank for all categories.

**Comment by lukeholder** [comment]
> Leave blank for all categories

That was the old description before we added the all categories light switch. That line was removed but somehow made its way back into the description somehow. It should removed from the description in the latest release.
