### ISSUE TITLE
Can't update shipping methods for `estimatedShippingAddress` once an address is set on the cart

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce#2699]
### Description

I have a shipping/delivery estimator that updates the `estimatedShippingAddress` with the `commerce/cart/update-cart` action via AJAX.

This works when I pass the following:
`estimatedBillingAddressSameAsShipping`
`estimatedShippingAddress[countryId]`
`estimatedShippingAddress[zipCode]`

When the user is new the cart returns the expected shipping methods in `cart.availableShippingMethodOptions`.
The data for `estimatedShippingAddress` can be changed, i.e. countryId and the results are updated and returned as expected.

If a user then goes through the checkout and/or completes an order a `shippingAddressId` is set.

Once this is set, regardless of what the `estimatedShippingAddress` is set to, the cart will just return shipping methods based on the `shippingAddressId` .

I've tried setting `shippingAddressId` to `NULL` and passing a blank string but it stays set on the cart. I've also tried the same with `estimatedBillingAddressId` but no luck.

I would expect updating the `estimatedShippingAddress` to return the correct shipping methods.
Is this a bug or is this how it's supposed to work? At the moment, I can't see how a shipping estimator could work other than when a user is new.

If an existing user logs in their default address is set on the cart.

I notice in the demo templates, Craft's estimator has this condition: `{% if not cart.getShippingAddress() %}` so I presume it just never runs for existing users?

Is it possible to unset the active shipping address on the cart? Or would it be possible for the cart to return something like `estimatedShippingMethods` based on the `estimatedShippingAddress`.

### Steps to reproduce

As above.

### Additional info

- Craft CMS version: 3.7.30.1
- Craft Commerce version: 3.4.10.1

**Comment by pdaleramirez** [comment]
@andrewhawkes the cart.shippingAddress will auto set the current logged customer's primary address. To avoid setting it automatically and allow null value for shippingAddress.

Create a `commerce.php` file in config folder then add a setting autoSetNewCartAddresses config to false.
https://craftcms.com/docs/commerce/3.x/config-settings.html#autosetnewcartaddresses
