### ISSUE TITLE
`order.shippingAddress()` returns `NULL` if the cart is accessed in the same template 

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce#2701]
### Description

With an active logged in user, accessing an order shipping address via `order.shippingAddress()` returns `NULL` if the cart object is defined. If the cart is not defined, the order shippingAddress returns as expected. This also appears to be happening with the billingAddress. Everything else such as the `lineItems` return as expected.

See my below example I made in a basic twig template to isolate and debug the issue:

### Steps to reproduce

Create an order for a user via the control panel and login as the user:

#### Order shippingAddress() returning as expected:

```
{% set number = craft.app.request.param('number') %}
{% set order = craft.orders.number(number).one() %}

<pre>
  {{ dump(order.shippingAddress()) }}
</pre>
```

Returns:
```
object(craft\commerce\models\Address)...
```

#### Order shippingAddress() returns NULL:

```
{% if cart is not defined %}
  {% set cart = craft.commerce.carts.cart %}
{% endif %}

{% set number = craft.app.request.param('number') %}
{% set order = craft.orders.number(number).one() %}

<pre>
  {{ dump(order.shippingAddress()) }}
</pre>
```
Returns
`NULL`

Note the above will return the order if the user is logged out. 

### Additional info

- Craft CMS version: 3.7.30.1
- Craft Commerce version: 3.4.10.1

**Comment by pdaleramirez** [comment]
@andrewhawkes I couldn't recreate this issue, are you passing a correct `number` in your second example?

**Comment by andrewhawkes** [comment]
> @andrewhawkes I couldn't recreate this issue, are you passing a correct `number` in your second example?

Yep, the URL with params is exactly the same I'm just defining the cart as shown in the second example. To be clear this only happens once a user is logged in and has already completed an order.

**Comment by andrewhawkes** [comment]
> @andrewhawkes I couldn't recreate this issue, are you passing a correct `number` in your second example?

Also, I should have made it clearer in the example but as the original issue, I can access other order properties like the `lineItems` etc. It's just the addresses.

**Comment by pdaleramirez** [comment]
@andrewhawkes The `order.shippingAddress()` returns null if the current logged in customer doesn't have a primary shipping address set

**Comment by andrewhawkes** [comment]
> @andrewhawkes The `order.shippingAddress()` returns null if the current logged in customer doesn't have a primary shipping address set

Is this a bug then? You would expect the address to be returned from the order details (as shown in the backend) regardless of what the user has set now etc.

**Comment by pdaleramirez** [comment]
It should return the address from the completed order. I could not replicate the issue. You can send your db to support@craftcms.com we can debug further.

**Comment by andrewhawkes** [comment]
> It should return the address from the completed order. I could not replicate the issue. You can send your db to [support@craftcms.com](mailto:support@craftcms.com) we can debug further.

I'll have to get approval from the client but in the meantime, I'll try and isolate the issue as it doesn't appear to be consistent.
