### ISSUE TITLE
estimatedShippingAddress not returned when using `commerce/cart/update-cart` (JSON)

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce#2703]
### Description

See https://github.com/craftcms/commerce/issues/1084

This appears to have disappeared again?

### Additional info

- Craft CMS version: 3.7.30.1
- Craft Commerce version: 3.4.10.1

**Comment by pdaleramirez** [comment]
@andrewhawkes The estimatedShippingAddress is still there when you use the carArray function

```
        $order = Order::findOne(1);
        $json = Plugin::getInstance()->getOrders()->cartArray($order);
```

If the cart has the `estimatedShippingAddressId` value, the estimatedShippingAddress attribute should appear.

**Comment by andrewhawkes** [comment]
@pdaleramirez sorry, this is specifically when you update via AJAX to `commerce/cart/update-cart` it's not returned in the response.

**Comment by andrewhawkes** [comment]
> @andrewhawkes the update-cart response is missing many attributes on latest version. This will be added on Commerce 4. To add the estimatedShippingAddressId attribute you can use the `EVENT_MODIFY_CART_INFO`
> 
> https://github.com/craftcms/commerce/blob/110f012b1bd5a24aa75224c9a1d4c630273ba0fe/src/controllers/BaseFrontEndController.php#L79

Is there any ETA on commerce 4 because the `estimatedShippingAddress` was supposed to be returned. It's useful to have that info returned so you can validate what the details are for estimating shipping etc.

**Comment by pdaleramirez** [comment]
@andrewhawkes Most likely 2nd quarter of this year.

**Comment by andrewhawkes** [comment]
@pdaleramirez thanks for getting back to me
