### ISSUE TITLE
Custom Variant validations not handled correctly

### ISSUE THREAD

**Issue by goraxan** [craftcms/commerce#2706]
### Description
I have a requirement that a Variant can't have it's price changed, so I'm trying to prevent it from saving if I detect the price changes with the following code
```
        Event::on(
            Variant::class,
            Variant::EVENT_BEFORE_SAVE,
            function(ModelEvent $e) {

                /** @var Variant $entry */
                $entry = $e->sender;
                if (!$entry->firstSave) {
                    $variant = Variant::find()->id($entry->id)->one();
                    if($variant->price != $entry->price){
                        $entry->addError('price', "The price can't be changed");
                        $e->isValid = false;
                    }
                }
            }
        );
```
What happens is that the variant is not saved due to marking it as isValid = false, but the product is updated with the new price, leaving it inconsistent and without showing any error to the user.

IMO the expected behaviour should be, show the error next to the price field, and don't update anything.

No error and price updated from the products table page:
![Capture](https://user-images.githubusercontent.com/8337784/154258079-2d58b035-bebe-41c7-8f2b-a9e61d23a01e.png)
Variant price from the product details page:
![image](https://user-images.githubusercontent.com/8337784/154257690-ad3f0f50-58c4-4c87-8ad7-7490933fe1b1.png)

### Steps to reproduce

1. Create a product with a variant
2. Save it with a price
3. Update the existing variant with a new price
4. The product price is the new price, while the variant price is the old price, and no errors are shown

### Additional info

- Craft CMS version: 3.7.23
- Craft Commerce version: 3.4.8
- PHP version: 7.4.16
- Database driver & version: MySQL 8.0.12

**Comment by pdaleramirez** [comment]
@goraxan use this event instead

```
        Event::on(
            Variant::class,
            Variant::EVENT_BEFORE_VALIDATE,
            function(\yii\base\ModelEvent $e) {
```

It will prevent saving for both product and variant models.
