### ISSUE TITLE
Events firing before and after product type is removed missing

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#2710]
There are only `EVENT_BEFORE_SAVE_PRODUCTTYPE` and `EVENT_AFTER_SAVE_PRODUCTTYPE` in `ProductTypes` class.

**Comment by pdaleramirez** [comment]
@piotrpog can you elaborate more on the issue? The events weren't removed on latest version.

**Comment by piotrpog** [comment]
@pdaleramirez maybe i just cannot find them :) But when i checked `ProductTypes` class, i found only `EVENT_BEFORE_SAVE_PRODUCTTYPE` and `EVENT_AFTER_SAVE_PRODUCTTYPE` and nothing for removing product type.

**Comment by pdaleramirez** [comment]
@piotrpog The product type is stored in project config if you want to watch the event use the project config event instead E.g.
https://github.com/craftcms/cms/blob/048c88360807e28b5f577b756973eb2014601da6/src/services/ProjectConfig.php#L188
