### ISSUE TITLE
Events for saving/deleting order statuses missing

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#2711]
There are no events firing when order status is saved or deleted.

**Comment by pdaleramirez** [comment]
@piotrpog Saving and deleting order statuses are handled by the project config service you use the event `craft\services\ProjectConfig::EVENT_ADD_ITEM` and `craft\services\ProjectConfig::EVENT_REMOVE_ITEM`.
https://github.com/craftcms/cms/blob/ff47e1aa80238560f60d1f430c7099e8f2ee821f/src/services/ProjectConfig.php#L153
