### ISSUE TITLE
Unable to attach behaviors to ProductType

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/commerce#2715]
### Description

It's not possible to add a custom behavior to the class `craft\commerce\models\ProductType`.

Its method `behaviors()` is [overridden](https://github.com/craftcms/commerce/blob/develop/src/models/ProductType.php#L405) and as such skips the event `craft\base\Model::EVENT_DEFINE_BEHAVIORS`.

Could it be changed to something like the following, so the event is triggered ?

```
/**
     * @inheritdoc
     */
    public function behaviors(): array
    {
        return array_merge(parent::behaviors(), [
            'productFieldLayout' => [
                'class' => FieldLayoutBehavior::class,
                'elementType' => Product::class,
                'idAttribute' => 'fieldLayoutId',
            ],
            'variantFieldLayout' => [
                'class' => FieldLayoutBehavior::class,
                'elementType' => Variant::class,
                'idAttribute' => 'variantFieldLayoutId',
            ],
        ]);
    }
```

### Additional info

- Craft CMS version: 3.7.34
- Craft Commerce version: 3.4.9.3
- PHP version: 8.0.15
- Database driver & version: MariaDB 5.5.5

**Comment by lukeholder** [comment]
Will do for the next release.

**Comment by brandonkelly** [comment]
Commerce 3.4.12 is out now with support for `EVENT_DEFINE_BEHAVIORS` for `craft\commerce\models\ProductType`.
