### ISSUE TITLE
Line items not always available in afterDelete

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#2722]
I'm not sure if this is a bug or by design but if an order is deleted and line items have either not been eager loaded as a part of the initial query or retrieved via `$order->getLineItems()` then they are not available to work with on the order in the afterDelete event.

We needed to recreate the purge logic but also to trigger events (which commerce currently does not do #2721) so we can take action on each line item that is being removed (we have separate elements related to each item that need to be deleted) and discovered that unless we eager load or get line items in beforeDelete then we cant do this.

I would have thought, that irrespective of eager loading or not, that the order state in afterDelete should reflect the state before deleting.

**Comment by lukeholder** [comment]
If you need to do something with the line items before they are deleted, then an Order's beforeDelete is the correct location to do so? Unless I am missing something, and will then re-open.

**Comment by samhibberd** [comment]
I've forgotten the exact scenario tbh (been a while since we worked on this) but I think it depends on whether beforeDelete is cancellable (which i think it is), if so then we would need access to the line items in the afterDelete method (so we can do stuff with them), the order is available and I would expect to be able to access all the order stuff?
