### ISSUE TITLE
Field layouts not populated properly

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/commerce#2725]
### Description

On a config change event, the product and variant layout fields and tabs are not populated properly. The array dumped in these examples have the fields as defined before the product type was saved :

```
use craft\commerce\Plugin as Commerce;

Craft::$app->projectConfig->onUpdate(ProductTypes::CONFIG_PRODUCTTYPES_KEY.'.{uid}', function (ConfigEvent $e) {
    $type = Commerce::getInstance()->productTypes->getProductTypeByUid($e->tokenMatches[0]);
    dd($type->getProductFieldLayout()->fields);
    dd($type->getVariantFieldLayout()->fields);
})
```
Related to https://github.com/craftcms/cms/issues/10237 

### Steps to reproduce

1. Add an event to listen to a change on the config ProductTypes::CONFIG_PRODUCTTYPES_KEY
2. Add/remove a field to a product/variant layout
3. Save

### Additional info

- Craft CMS version: 3.7.34
- Craft Commerce version: 3.4.9.3
- PHP version: 8.0.15
- Database driver & version: MariaDB 5.5.5

**Comment by pdaleramirez** [comment]
@ryssbowh To get the updated values you should be calling `$e->newValue` instead

```
Craft::$app->projectConfig->onUpdate(ProductTypes::CONFIG_PRODUCTTYPES_KEY.'.{uid}', function (ConfigEvent $e) {
            $values = $e->newValue;
        });
```

Calling values by uuid will get old values cause it triggers before applying config changes.

**Comment by ryssbowh** [comment]
Thank you, I'll try that
