### ISSUE TITLE
Problems when hasUnlimitedStock is null

### ISSUE THREAD

**Issue by nettum** [craftcms/commerce#2733]
### Description
If you import products & variants from other systems (e.g. using feed-me) it's pretty easy to ignore setting the `hasUnlimitedStock` field for variants to `0`. This may cause problems later with your queries as craft commerce expects the `hasUnlimitedStock` stock to be either `0` or `1`.

As long as all products & variants are created from Crafts UI (CP) this will never be a problem, but Craft Commerce should probably do something to avoid this potential pitfall anyway.

Is there any reason why `NULL` is allowed for this field? 
Could that field be set to not allowing `NULL` and/or set the default value to be `0` in the database schema?
Either that or the craft commerce logic should be updated to expect `NULL` as a valid value for this field and take that into consideration on the element queries.

As it is now some of the query-functions will not work as expected if this field is set to `NULL`. (e.g. `hasStock()`).

See related issue: https://github.com/craftcms/commerce/issues/1157

### Steps to reproduce

To simulate a system where you have imported variants without explicitly setting the hasUnlimited stock you could do the following:

1. Set up the spoke and chain [demo](https://github.com/craftcms/spoke-and-chain).
2. Update the seed data so some of the variants does not have unlimited stock, e.g. `UPDATE commerce_variants SET hasUnlimitedStock = 0, stock = 10 LIMIT 30;`
3. Create a query that uses `hasStock()` or `hasUnlimitedStock()` and verify that the numbers are correct e.g:
```
  {% set hasStock = craft.variants().hasStock(true).count() %}
  {% set hasUnlimitedStock = craft.variants().hasUnlimitedStock(true).count() %}
  <div>
    <h1>Num variants hasStock: {{ hasStock }}  , Num hasUnlimitedStock: {{ hasUnlimitedStock }}</h1>
  </div>
```
In my case I get `Num variants hasStock: 75 , Num hasUnlimitedStock: 45` which is correct.

4. Update some of the database rows to have `hasUnlimitedStock` set to `NULL`.  E.g. 
```
UPDATE commerce_variants SET hasUnlimitedStock = NULL WHERE hasUnlimitedStock = 0 LIMIT 5;
UPDATE commerce_variants SET hasUnlimitedStock = NULL WHERE hasUnlimitedStock = 1 LIMIT 5;
```
5. Rerun the query from step 2 and verify that the numbers have changed:
`Num variants hasStock: 65 , Num hasUnlimitedStock: 40`

### Additional info

- Craft CMS version: 3.7.36 Pro
- Craft Commerce version: 3.4.11
- PHP version: 8.0
- Database driver & version: MySQL 8.0
- Plugins & versions: same as spoke-and-chain demo

**Comment by pdaleramirez** [comment]
@nettum This will get resolved on Commerce 4 because PHP typed properties will be implemented. The Variant element will have `public bool $hasUnlimitedStock = false;`

**Comment by nettum** [comment]
Thanks for the update! That will probably also resolve(ish) https://github.com/craftcms/feed-me/issues/636
