### ISSUE TITLE
Column not found: 1054 Unknown column 'language' in 'field list'

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/commerce#2735]
### Description

We are experiencing migration errors while upgrading from Craft Commerce 2 to 3 in a production environment. The upgrade migrations ran successfully in my local environment and twice in the client's staging environment prior to our attempt to run them in production.

I doubt this is a bug but there may be other factors in production that I am unaware of that may be causing these issues. We recently updated this site's CMS to 3.7.30.1. We also updated most of the installed plugins. For that phase, we updated Craft Commerce 2 to the latest version (2.2.27). All of those updates went live without any issues.

For phase 2, my entire goal was to upgrade Craft Commerce 2 to version 3. We are attempting to upgrade from 2.2.27 to 3.4.11. Here is the exception I see each time I trigger the upgrade migrations:

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language' in 'field list'
The SQL being executed was: SELECT id, name, handle, description, templatePath, fileNameFormat, enabled, sortOrder, isDefault, uid, language
FROM commerce_pdfs
ORDER BY sortOrder

Migration: craft\commerce\migrations\m200801_233755_pdfs

Output:

> create table {{%commerce_pdfs}} ... done (time: 0.058s)
> drop column attachPdf from table {{%commerce_emails}} ... done (time: 0.116s)
> drop column pdfTemplatePath from table {{%commerce_emails}} ... done (time: 0.116s)
> add column pdfId integer to table {{%commerce_emails}} ... done (time: 0.114s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language' in 'field list'
The SQL being executed was: SELECT id, name, handle, description, templatePath, fileNameFormat, enabled, sortOrder, isDefault, uid, language
FROM commerce_pdfs
ORDER BY sortOrder (/home/vhosts/SITENAME/production/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /home/vhosts/SITENAME/production/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT id, n...')
#1 /home/vhosts/SITENAME/production/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT id, n...')
#2 /home/vhosts/SITENAME/production/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /home/vhosts/SITENAME/production/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
#5 /home/vhosts/SITENAME/production/vendor/craftcms/commerce/src/services/Pdfs.php(183): craft\db\Query->all()
#6 /home/vhosts/SITENAME/production/vendor/craftcms/commerce/src/services/Pdfs.php(243): craft\commerce\services\Pdfs->getAllPdfs()
#7 /home/vhosts/SITENAME/production/vendor/craftcms/commerce/src/services/Pdfs.php(341): craft\commerce\services\Pdfs->getPdfById(1)
#8 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): craft\commerce\services\Pdfs->handleChangedPdf(Object(craft\events\ConfigEvent))
#9 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#10 /home/vhosts/SITENAME/production/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#11 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/services/ProjectConfig.php(750): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#12 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/services/ProjectConfig.php(522): craft\services\ProjectConfig->_processConfigChangesInternal('commerce.pdfs.e...', true, NULL)
#13 /home/vhosts/SITENAME/production/vendor/craftcms/commerce/src/migrations/m200801_233755_pdfs.php(98): craft\services\ProjectConfig->set('commerce.pdfs.e...', Array)
#14 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\migrations\m200801_233755_pdfs->safeUp()
#15 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#16 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\commerce\migrations\m200801_233755_pdfs))
#17 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/services/Updates.php(250): craft\db\MigrationManager->up()
#18 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(532): craft\services\Updates->runMigrations(Array)
#19 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/controllers/UpdaterController.php(201): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#20 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#21 /home/vhosts/SITENAME/production/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /home/vhosts/SITENAME/production/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#23 /home/vhosts/SITENAME/production/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('migrate', Array)
#24 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('updater/migrate', Array)
#25 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/web/Application.php(684): craft\web\Application->runAction('updater/migrate')
#26 /home/vhosts/SITENAME/production/vendor/craftcms/cms/src/web/Application.php(244): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#27 /home/vhosts/SITENAME/production/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /home/vhosts/SITENAME/production/public/index.php(31): yii\base\Application->run()
#29 {main}

```

Additionally, I tried setting the `backupOnUpdate` general config setting to `false` since we manually back up the DB prior to doing any updates but that didn't seem to help. I got that idea from an [older issue I found here](https://github.com/craftcms/commerce/issues/1920) (references the old `backupDbOnUpdate` setting) when I saw the same "attachPdf" exception _after_ refreshing the page upon seeing the "language" column exception.

EDIT: I noticed there are numerous lines in the log above this exception that say:

```
Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
```
These warnings alternate between LEVEL1 and LEVEL2. I'm not sure if this is related but I thought it looked suspicious.

### Additional info

- Craft CMS version: 3.7.30.1
- Craft Commerce version: 2.2.27, 3.4.11
- PHP version: 7.3.33
- Database driver & version: MySQL 5.7.37
- Plugins & versions:

Amazon S3 1.3.0
Cookies 1.1.15
CP Field Inspect 1.2.5
Control Panel CSS 2.4.0 (uninstalled via CP at the moment as it was not in use)
Craft Commerce 2.2.27
Imager X v3.5.5
Inventory 2.1.1
Linki 1.1.12.1
Link Vault 3.2.0
Redactor 2.9.0
Relabel 2.0.2
Sprout Reports 1.2.11
Typogrify 1.1.18

**Comment by pdaleramirez** [comment]
@benjaminkohl It seems to be that the `language` column had been removed in your database. It could have been manually removed via custom module or plugin. Could you test adding a `language` column to the `commerce_emails` table and test if that solves the migration issue?

**Comment by benjaminkohl** [comment]
From what I can tell, this exception is being thrown while running the m200801_233755_pdfs migration that creates the commerce_pdfs table. The language column doesn't get added to that table until a later migration called m201120_093135_add_locale_setting_to_email_and_pdf. So maybe something about this migration is executing some newer code that references the newer language column which does not yet exist at the time of the first migration. I do see that lines 5-7 in that stack trace are doing things with the PDF service.

```
#5 /home/vhosts/SITENAME/production/vendor/craftcms/commerce/src/services/Pdfs.php(183): craft\db\Query->all()
#6 /home/vhosts/SITENAME/production/vendor/craftcms/commerce/src/services/Pdfs.php(243): craft\commerce\services\Pdfs->getAllPdfs()
#7 /home/vhosts/SITENAME/production/vendor/craftcms/commerce/src/services/Pdfs.php(341): craft\commerce\services\Pdfs->getPdfById(1)
```

Or it could all be a red herring because all these migrations executed successfully locally and in the staging environment (after getting errors a few times). That's why I was reviewing the logs trying to figure out if some other error/exception occurred _before_ this exception and this one is just a result of something else going wrong.

**Comment by benjaminkohl** [comment]
I ran through the upgrade locally again and it was successful but I do see numerous instances of this error in the logs again. Maybe the production environment is not handling these errors in the same manner as my local environment? The client's staging environment is on the same server and has the same setup as their production environment so I am unsure why the upgrade didn't fail there.
```
2022-03-17 10:07:11 [-][-][-][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1
2022-03-17 10:07:11 [-][-][-][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1
```

**Comment by pdaleramirez** [comment]
@benjaminkohl I think it would be good to download an updated db from production and update it locally then import it to your production server.

It could production db is corrupted for some reason.

**Comment by benjaminkohl** [comment]
That sounds like a good plan to me since my local upgrades run smoothly. I'm running it by our client. Thanks.

**Comment by lukeholder** [comment]
I just made a more robust check for the error you are getting in this commit:

c7794530e4d920b6d1a87c150abc58740daddb19


To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#c7794530e4d920b6d1a87c150abc58740daddb19 as 3.4.13",
  "...": "..."
}
```

And try the migration to 3.4.x again.

Let me know how it 
Then run `composer update`.

If that works, let us know, and we can then roll it our into a future release (3.4.14)

Thanks,

**Comment by lukeholder** [comment]
Will re-popen if this is still an issue. Let us know.

**Comment by benjaminkohl** [comment]
Thanks. We scheduled the update for Tuesday evening and I am just going to run through it in my local environment while the production site is in maintenance mode.
