### ISSUE TITLE
Update Cart : Deprecated Messages

### ISSUE THREAD

**Issue by magnessjo** [craftcms/commerce#274]
### Description

I'm getting a few deprecated messages when I submit a AJAX post to update cart method.  

**Messages:**

craft\commerce\models\LineItem::getTax() has been deprecated. Use getAdjustmentsTotalByType('tax') instead.

craft\commerce\models\LineItem::getShippingCost() has been deprecated. Use getAdjustmentsTotalByType('shipping') instead.

craft\commerce\models\LineItem::getDiscount() has been deprecated. Use getAdjustmentsTotalByType('discount') instead.

### Steps to reproduce

1.  Submit a post to '/actions/commerce/cart/update-cart' with a purchase id and qty.  

### Additional info

- Craft version: 3.0.0-RC17
- PHP version: 7.0.19
- Database driver & version: MySQL 5.7.18
- Plugins & versions:

Commerce : dev-develop as 2.0.0-alpha.99

**Comment by lukeholder** [comment]
Thanks, `composer update` to fix.

**Comment by magnessjo** [comment]
@lukeholder,

  Verified.  Thank you.
