### ISSUE TITLE
Line items returned in a different order when eager loaded

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/commerce#2740]
### Description

We noticed line items in our frontend carts were not being ordered by the date they were added/created. 

However, if we view the same active cart in the control panel they are ordered as expected.

The difference seems to be whether or not the line items have been eager loaded.

`{% set cart = craft.orders.number(craft.commerce.carts.cart.number).one() %}`

Line items in the above cart are not eager loaded and they are ordered by date created, as expected.

`{% set cart = craft.commerce.carts.cart %}` 
or 
`{% set cart = craft.orders.number(craft.commerce.carts.cart.number).withLineItems().one() %}`

Line items in these carts are eager loaded (by default or explicitly) and are ordered by some other criteria (I've not worked out what).

### Additional info

- Craft CMS version: 3.7.36
- Craft Commerce version: 3.4.11

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#ade0d084164f22b5583c62b9f32fdfb820baf253 as 3.4.13",
  "...": "..."
}
```

Then run `composer update`.
