### ISSUE TITLE
[4.x]: Choosing a line item in backend order creation fails with error

### ISSUE THREAD

**Issue by Nellyaa** [craftcms/commerce#2743]
### Description

You can't create an order in the backend, as adding line items throws an error. 

### Steps to reproduce

1. Choose a user and click 'new order' in the Commerce tab
2. Click on 'add a line item'
3. Select a line item
4. Click add
5. Get red error message at the top, line item doesn't get added to the order

### Expected behavior

After clicking 'add' line item gets added to the order without error :)

### Actual behavior

After clicking 'add', the following error message appears: 

 craft\commerce\services\LineItems::getLineItemById(): Argument #1 ($id) must be of type int, null given, called in /var/www/vendor/craftcms/commerce/src/controllers/OrdersController.php on line 1314

### Craft CMS version

4.0.0-beta.2

### Craft Commerce version

4.0.0-beta.1

### PHP version

8.1.3

### Operating system and version

Linux 5.10.16.3-microsoft-standard-WSL2

### Database type and version

MySQL 10.7.3

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Commerce
- Redactor

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
