### ISSUE TITLE
[3.x]: Order Condition Formula field error on save

### ISSUE THREAD

**Issue by joepagan** [craftcms/commerce#2744]
### Description

https://craftcms.com/docs/commerce/3.x/shipping.html#order-condition-formula 
Suggests I can run twig in the mentioned field to show a shipping method or not.

```twig
order.lineItems|filter(li => li.purchasable.variantLightswitchField == true)|length > 0
```

However, I get a field error:
> Invalid order condition syntax.

I believe my twig is ok, tested in a frontend template with the result I expect.

Can the error message here be more descriptive?

### Steps to reproduce

1. add twig above to a shipping method rule's order condition formula field

### Expected behavior

1. behave as docs suggest

### Actual behavior

1. cannot save field

### Craft CMS version

3.7.32

### Craft Commerce version

3.4.11

### PHP version

8.0

### Operating system and version

php:8.0-fpm-alpine

### Database type and version

mariadb:10.2.31

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
The condition formulas twig sandbox only allows a limited number of filters and functions to be used. Currently the `filter` filter is not available in order condition formulas:

https://github.com/craftcms/commerce/blob/4.0/src/services/Formulas.php#L190-L190

I don't think I see a security implication, so will look to enable it for the next Commerce 3 release.

We will also go ahead and document the list of available filters and functions. Thanks.

Will close this issue once we have added the filter.

**Comment by lukeholder** [comment]
Also just noticed, the `order` variable passed into the condition is an associative array representing the order, and not the real order element. So doing `li.purchasable.variantLightswitchField` in the formula wont work like it would in on the front end.

If you want to add the lightSwitchField value to the line item data you would need to add it to the snapshot, and use that data to determine the match:

`li.snapshot`

Add things to the snapshot with: 
```
use craft\commerce\elements\Variant;
use craft\commerce\events\CustomizeVariantSnapshotDataEvent;
use yii\base\Event;
Event::on(
    Variant::class,
    Variant::EVENT_AFTER_CAPTURE_VARIANT_SNAPSHOT,
    function(CustomizeVariantSnapshotDataEvent $event) {
        // @var Variant $variant
        $variant = $event->variant;
        // @var array|null $fields
        $fields = $event->fields;
        // Modify or redact captured `$data`
        // ...
    }
);
```

**Comment by joepagan** [comment]
Thanks for the reply @lukeholder limited list of filters partly explains that, would indeed be helpful to add to the docs, a more descriptive field error would also be good if that isn't too much work "filter not available" or something.

Also thanks for the suggestion on how to add data to a snapshot, very helpful thanks!

**Comment by lukeholder** [comment]
The `filter` filter is now out in Commerce 3.4.13
