### ISSUE TITLE
Products: Admins can save with required category selection field empty

### ISSUE THREAD

**Issue by gracecanfield** [craftcms/commerce#275]
### Description

Currently, if a user leaves a required field empty, it doesn't prevent them from saving a product.

### Steps to reproduce

I can't give you a URL to actually walk you through steps, but [here's a screencast](http://recordit.co/RCVp7d3JcZ) that shows me:
1. Editing an existing product that I was able to save with a required field empty
2. Saving it again successfully, with the required (category selection) field still empty.

### Additional info

- Craft version: Craft Pro 3.0.0-RC17
- PHP version: 7.0.28
- Database driver & version: MySQL 5.7.21
- Plugins & versions:

**Comment by lukeholder** [comment]
Thanks for reporting! Please do a `composer update` to pull in the fix. Thanks!
