### ISSUE TITLE
Promotions Per User Coupon Limit

### ISSUE THREAD

**Issue by magnessjo** [craftcms/commerce#276]
### Description

Previously in Commerce 1, if you left the field 'Per User Coupon Limit' to 0 it would be unlimited (per the instructions).  In Commerce 2, if you leave it as 0, the coupon will be invalid.  

The coupons returns an error 'The promotional code that you have entered could not be found' when set to zero. 

I believe there is an error in the $allUsedUp query in the matchCode method of the Discounts controller.  

### Steps to reproduce

1.  Add a new promotion discount coupon.  Leave it at zero for per user coupon limit 
2.  Submit an Ajax form to update-cart with the coupon code.  

### Additional info

- Craft version:  Craft Pro 3.0.0-RC17.1
- PHP version: 7.0.19
- Database driver & version: MySQL 5.7.18
- Plugins & versions:

Commerce : dev-develop as 2.0.0-alpha.99

**Comment by lukeholder** [comment]
@magnessjo Hopefully this part of the docs will assist: https://github.com/craftcms/commerce-docs/blob/v2/en/order-model.md#getadjustmentstotalbytypetype-included

Let me know.
