### ISSUE TITLE
[3.x]: Docs are referencing missing example for Restoring Previous Cart Contents

### ISSUE THREAD

**Issue by rbrv** [craftcms/commerce#2760]
### Description

In the docs, under [Restoring Previous Cart Contents](https://craftcms.com/docs/commerce/3.x/orders-carts.html#restoring-previous-cart-contents), there is a reference to the [example templates](https://craftcms.com/docs/commerce/3.x/example-templates.html).

The example templates no longer seem to contain an example looping over line items in older carts (allowing the customer to add them to the current order).

![Screenshot 2022-04-02 at 12 00 18](https://user-images.githubusercontent.com/43676281/161378079-1fc76824-5480-4b21-9892-93a80e7d0f54.png)

### Craft CMS version

3.x

### Craft Commerce version

3.x

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for that, will get that fixed.

**Comment by mattstein** [comment]
Thanks for pointing this out, @rbrv! Just added an example directly to that page since we don’t have one in the example templates.
