### ISSUE TITLE
[3.x]: Discounts - excludeOnSale not working with baseDiscount

### ISSUE THREAD

**Issue by rjanits** [craftcms/commerce#2769]
### Description
Global discount codes (eg: 20 euros) do not work with `ExcludeOnSale` settings.

### Steps to reproduce

1. Create a discount code with a `baseDiscount` (eg. 20 euros)
2. Set the `exludeOnSale` switch to true
3. Add sale products to cart and apply discount.

### Expected behavior
If there are only sale items in the shopping cart the voucher should not be applied.

### Actual behavior
Voucher code 'baseDiscount' will be applied anyway. 
When i use a discount with `perItemDiscount` everything works as expected.

**I don't know if this behavior is planned that way.** But unfortunately for most customers it seems like it is a bug.
It would still be nice if there was the possibility to generate exceptions so that the voucher is not applied.
Any ideas?

### Craft CMS version

3.7.37

### Craft Commerce version

3.4.13

### PHP version

7.4

### Database type and version

MySQL 5.7

### Image driver and version

Imagick

### Installed plugins and versions

- Gift Voucher: 2.7.0
- Navigation: 1.4.24
- Sendcloud: 1.0.5
- Redactor: 2.10.5
- Shortcodes: 1.1.0
- Sprig: 1.12.2
- Super Table: 2.7.1
- Table of contents: 1.0.2
- Stripe for Craft Commerce: 2.4.3
- Sprout SEO: 4.6.9
- Formie: 1.5.12
- Field Manager: 2.2.4
- Feed Me: 4.4.2
- Embedded Assets: 2.10.3
- Digital Products: 2.4.3.2
- Asset Rev: 6.0.2
- Anchors: 2.3.1

**Comment by pdaleramirez** [comment]
@rjanits That is currently how it works. The flat amount order discount is an order adjustment and not a line item adjustment. If you input an order adjustment it will ignore the excluded sale condition.

 If you want to change the behavior I would suggest to create a [custom adjuster])(https://craftcms.com/docs/commerce/3.x/extend/adjusters.html)
