### ISSUE TITLE
[4.x]: Other tab inside the order details is not appear

### ISSUE THREAD

**Issue by aodihis** [craftcms/commerce#2770]
### Description
In Craft 3,  inside the order details page there are other Tabs besides the main tab, like transaction and order history, but In Craft 4 the other tabs disappear, even the tabs that we have set inside the field layout are not appear in order details page. 
But when we take a look inside the inspect tools, we can find the HTML of the other tabs but set to hidden.
Do any setup that needs to do to make these tabs appear?

### Craft CMS version

4.0.0-beta-4

### Craft Commerce version

4.0.0-beta-2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @aodihis 

Thank you for bringing this to our attention. We have just pushed an update that will fix this issue. The update will be included in the next beta release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "4.0.x-dev#5a68b381d7f8859351aafc39409d841147bb8890 as 4.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by brandonkelly** [comment]
Commerce 4.0.0-RC1 is out now with that fix.
