### ISSUE TITLE
[4.x] Updating cart with invalid email throws exception

### ISSUE THREAD

**Issue by Nellyaa** [craftcms/commerce#2771]
### Description

When you update an cart with update-cart action and enter an email that is an invalid email, you get an exception.

### Steps to reproduce
1. Update a cart with the update-cart action with e.g. a form with an email
2. Get exception

### Expected behavior

A flash message 'invalid email' is being returned instead and the website doesn't break.

### Actual behavior

The website reloads and you get an exception page.
Code:

´´´
Invalid Argument – [yii\base\InvalidArgumentException](http://www.yiiframework.com/doc-2.0/yii-base-invalidargumentexception.html)
E-Mail ist keine gültige E-Mail-Adresse.
1. in /var/www/vendor/craftcms/cms/src/services/Users.phpat line 178
169170171172173174175176177178179180181182183184185186187        $user = User::find()
            ->email($email)
            ->status(null)
            ->one();
 
        if (!$user) {
            $user = new User();
            $user->email = $email;
            if (!$user->validate(['email'])) {
                throw new InvalidArgumentException($user->getFirstError('email'));
            }
            if (!Craft::$app->getElements()->saveElement($user, false)) {
                throw new Exception('Unable to save user: ' . implode(', ', $user->getFirstErrors()));
            }
        }
 
        return $user;
    }
 
2. in /var/www/vendor/craftcms/commerce/src/elements/Order.php at line 2183– craft\services\Users::ensureUserByEmail('fj')
2177217821792180218121822183218421852186218721882189        }
 
        if ($this->_email === $email) {
            return;
        }
 
        $user = Craft::$app->getUsers()->ensureUserByEmail($email);
        $this->_email = $email;
        $this->setCustomer($user);
    }
 
    /**
     * Returns the email for this order. Will always be the registered users email if the order's customer is related to a user.
3. in /var/www/vendor/craftcms/commerce/src/controllers/CartController.php at line 205– craft\commerce\elements\Order::setEmail('fj')
199200201202203204205206207208209210211 
        $this->_setAddresses();
 
        // Set guest email address onto guest customers order.
        if ($email = $this->request->getParam('email')) {
            if ($this->_cart->getEmail() === null) {
                $this->_cart->setEmail($email);
            }
        }
 
        // Set if the customer should be registered on order completion
        if ($this->request->getBodyParam('registerUserOnOrderComplete')) {
            $this->_cart->registerUserOnOrderComplete = true;
4. craft\commerce\controllers\CartController::actionUpdateCart()
5. in /var/www/vendor/yiisoft/yii2/base/InlineAction.php at line 57– call_user_func_array([craft\commerce\controllers\CartController, 'actionUpdateCart'], [])
6. in /var/www/vendor/yiisoft/yii2/base/Controller.php at line 178– [yii\base\InlineAction::runWithParams](http://www.yiiframework.com/doc-2.0/yii-base-inlineaction.html#runWithParams()-detail)([])
7. in /var/www/vendor/yiisoft/yii2/base/Module.php at line 552– [yii\base\Controller::runAction](http://www.yiiframework.com/doc-2.0/yii-base-controller.html#runAction()-detail)('update-cart', [])
8. in /var/www/vendor/craftcms/cms/src/web/Application.php at line 301– [yii\base\Module::runAction](http://www.yiiframework.com/doc-2.0/yii-base-module.html#runAction()-detail)('commerce/cart/update-cart', [])
295296297298299300301302303304305306307     * @param string $route
     * @param array $params
     * @return Response|null The result of the action, normalized into a Response object
     */
    public function runAction($route, $params = []): ?BaseResponse
    {
        $result = parent::runAction($route, $params);
 
        if ($result === null || $result instanceof Response) {
            return $result;
        }
 
        $response = $this->getResponse();
9. in /var/www/vendor/craftcms/cms/src/web/Application.php at line 625– craft\web\Application::runAction('commerce/cart/update-cart', [])
619620621622623624625626627628629630631        if ($request->getIsActionRequest()) {
            $route = implode('/', $request->getActionSegments());
 
            try {
                Craft::debug("Route requested: '$route'", __METHOD__);
                $this->requestedRoute = $route;
                return $this->runAction($route, $_GET);
            } catch (Throwable $e) {
                $this->_unregisterDebugModule();
                if ($e instanceof InvalidRouteException) {
                    throw new NotFoundHttpException(Craft::t('yii', 'Page not found.'), $e->getCode(), $e);
                }
                throw $e;
10. in /var/www/vendor/craftcms/cms/src/web/Application.php at line 280– craft\web\Application::_processActionRequest(craft\web\Request)
274275276277278279280281282283284285286                    throw new ForbiddenHttpException();
                }
            }
        }
 
        // If this is an action request, call the controller
        if (($response = $this->_processActionRequest($request)) !== null) {
            return $response;
        }
 
        // If we’re still here, finally let Yii do its thing.
        try {
            return parent::handleRequest($request);
11. in /var/www/vendor/yiisoft/yii2/base/Application.php at line 384– craft\web\Application::handleRequest(craft\web\Request)
12. in /var/www/web/index.php at line 12– [yii\base\Application::run](http://www.yiiframework.com/doc-2.0/yii-base-application.html#run()-detail)()
6789101112// Load shared bootstrap
require dirname(__DIR__) . '/bootstrap.php';
 
// Load and run Craft
/** @var craft\web\Application $app */
$app = require CRAFT_VENDOR_PATH . '/craftcms/cms/bootstrap/web.php';
$app->run();
$_POST = [
    'CRAFT_CSRF_TOKEN' => 'eepx09IoEQeD3bj2k9wyXna_wiy8QPn62IuTMdMMfGSCKZEPVyzTywOZGuKXeSk05bDUuKCUSy0G3PMfiCWWqIjpzFTrPxkx0H7wdT9csf4=',
    'action' => 'commerce/cart/update-cart',
    'redirect' => '0e739e21e1f44565ce4c90002599af97b5156bdb52b5a6984c0bdaef02817a4dhttp://localhost:8080/checkout/adresse',
    'email' => 'fj',
];

$_COOKIE = [
    'CraftSessionId' => '5cde5207e0c63662519c1ad805a8d9ab',
    'CRAFT_CSRF_TOKEN' => '42a0079fe3036271060607bdaa4d583679cf0804a8ac811c3776a4a452105108a:2:{i:0;s:16:"CRAFT_CSRF_TOKEN";i:1;s:40:"zsk1EQ83fmlN3Hyspc134eoRPb_e83eURWazhpb5";}',
];

$_SESSION = [
    'a50e111d5f13061b3bc1c20c2a9c215d__flash' => [],
    'commerce_cart' => '341476abe6f91ede75eb04666025c3df',
];

### Craft CMS version

4.0.0-beta.4

### Craft Commerce version

4.0.0-beta.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @Nellyaa 

Thank you for reporting this. The issue has been fixed and will be included in the next release of Commerce 4.

Thanks!

**Comment by brandonkelly** [comment]
Commerce 4.0.0-RC1 is out now with that fix.
