### ISSUE TITLE
[4.x]: User avatar rendering [object object]

### ISSUE THREAD

**Issue by leevigraham** [craftcms/commerce#2776]
### Description

![Screen Shot 2022-04-20 at 10 01 38 am](https://user-images.githubusercontent.com/25124/164120501-86d1c1ab-df46-4813-b853-6af56bccd5cf.png)

### Steps to reproduce

1. Create order with logged in admin user
2. Check order in admin
3. User photo broken

### Craft CMS version

4.0.0-beta.4

### Craft Commerce version

4.0.*-dev as 4.0.0-beta.2

### PHP version

8.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @leevigraham 

Thank you for reporting.

We have just pushed up a fix that will be included in the next release of Commerce 4.

I can see you are requiring the `4.0` dev branch so a `composer update` will get you these changes right away.

Thanks!

**Comment by brandonkelly** [comment]
Commerce 4.0.0-RC1 is out now with that fix.
