### ISSUE TITLE
[3.x]: Product Element Index generating duplicate database queries

### ISSUE THREAD

**Issue by scottwakefield** [craftcms/commerce#2779]
### Description

Viewing the product element index (`admin/commerce/products`) results in excessive, duplicate database queries (and high memory usage) when you have multiple product types configured.

The duplicate queries appear to be run when Craft determines the available Sort Options for the Element index.

Examples from a fresh Commerce project when debugging:
- Adding 20 product types results in 492 database queries. 441 of those are duplicates.
- Adding 30 product types results in 1,012 database queries. 961 of those are duplicates.

And from a live project we're helping to optimise:
- Adding 63 product types results in 4,187 database queries. 4,098 of those are duplicates.

![image](https://user-images.githubusercontent.com/4173571/164459923-7df86cf1-1f7f-492b-bf7c-44fceb0b1b1b.png)

I suspect an optimisation may be required within Craft itself, but I'm filing the issue here as we've only seen this level of duplicate queries with Products in Commerce so far.

### Steps to reproduce

1. Clean Install Craft & Craft Commerce
2. Add multiple Product Types
3. Visit Products Element Index (`admin/commerce/products`)
4. Check duplicate queries in the Debug Bar

### Expected behavior

0 duplicate database queries.

### Actual behavior

Lots of duplicate database queries :)

### Craft CMS version

3.7.38

### Craft Commerce version

3.4.14

### PHP version

7.4.26

### Operating system and version

macOS Monterey 12.3

### Database type and version

MySQL 8

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@scottwakefield The issue will be resolved on the next release of the CMS https://github.com/craftcms/cms/blob/develop/CHANGELOG.md

**Comment by scottwakefield** [comment]
Excellent! Thanks, @pdaleramirez 👍🏻

**Comment by brandonkelly** [comment]
Craft 3.7.40 is out now with that change.
