### ISSUE TITLE
[4.x]: TypeError on empty product URI format

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#2781]
### Description
When leaving the Product URI format empty on the Product Type edit page and saving it, you get a typeError because the uriFormat has to be a string https://github.com/craftcms/commerce/blob/8fab27ab918a1759464111ab8da718d57b920c47/src/models/ProductTypeSite.php#L49 while it's getting passed a null variable https://github.com/craftcms/commerce/blob/45b437dcdf2fe6d9ccd6cccd1ebe1cb023613812/src/controllers/ProductTypesController.php#L140

### Steps to reproduce

1. Leave the Product URI Format field empty on the product type edit page
2. Save the product type

### Craft CMS version

4.0.0-beta.4

### Craft Commerce version

4.0.0-beta.2

### PHP version

8.0.0

### Operating system and version

Linux 5.13.0-40-generic

### Database type and version

MySQL 8.0.26

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

Thank you for bringing this to our attention. We have pushed a fix which will be included in the next release of Commerce 4.

Thanks!

**Comment by brandonkelly** [comment]
Commerce 4.0.0-RC1 is out now with that fix.
