### ISSUE TITLE
[4.x]: Send Order Email throw exception

### ISSUE THREAD

**Issue by aodihis** [craftcms/commerce#2784]
### Description

When attempting to sent email inside the order page, I got an error and email will not sent, here is the error text

`{"error":"Cannot assign null to property craft\\commerce\\events\\MailEvent::$orderHistory of type craft\\commerce\\models\\OrderHistory","exception":"TypeError","file":"/var/www/html/vendor/yiisoft/yii2/BaseYii.php","line":558,"trace":[{"file":"/var/www/html/vendor/yiisoft/yii2/base/BaseObject.php","line":107,"function":"configure","class":"yii\\BaseYii","type":"::"},{"file":"/var/www/html/vendor/craftcms/commerce/src/services/Emails.php","line":771,"function":"__construct","class":"yii\\base\\BaseObject","type":"->"},{"file":"/var/www/html/vendor/craftcms/commerce/src/controllers/OrdersController.php","line":736,"function":"sendEmail","class":"craft\\commerce\\services\\Emails","type":"->"},{"function":"actionSendEmail","class":"craft\\commerce\\controllers\\OrdersController","type":"->"},{"file":"/var/www/html/vendor/yiisoft/yii2/base/InlineAction.php","line":57,"function":"call_user_func_array"},{"file":"/var/www/html/vendor/yiisoft/yii2/base/Controller.php","line":178,"function":"runWithParams","class":"yii\\base\\InlineAction","type":"->"},{"file":"/var/www/html/vendor/yiisoft/yii2/base/Module.php","line":552,"function":"runAction","class":"yii\\base\\Controller","type":"->"},{"file":"/var/www/html/vendor/craftcms/cms/src/web/Application.php","line":301,"function":"runAction","class":"yii\\base\\Module","type":"->"},{"file":"/var/www/html/vendor/craftcms/cms/src/web/Application.php","line":625,"function":"runAction","class":"craft\\web\\Application","type":"->"},{"file":"/var/www/html/vendor/craftcms/cms/src/web/Application.php","line":280,"function":"_processActionRequest","class":"craft\\web\\Application","type":"->"},{"file":"/var/www/html/vendor/yiisoft/yii2/base/Application.php","line":384,"function":"handleRequest","class":"craft\\web\\Application","type":"->"},{"file":"/var/www/html/web/index.php","line":22,"function":"run","class":"yii\\base\\Application","type":"->"}]}`

### Steps to reproduce

1. Create the order  email
2.  Create an order and complete the order.
3. Click sent email in order page

### Expected behavior
- In step 3 the email should be sent with no errors.

### Actual behavior
- An internal server error is return.

### Craft CMS version

4.0.0-beta-4

### Craft Commerce version

4.0.0-beta-2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @aodihis 

Thank you for bringing this to our attention, a fix has been pushed and will be included in the next release of Commerce 4.

Thanks!

**Comment by brandonkelly** [comment]
Commerce 4.0.0-RC1 is out now with that fix.
