### ISSUE TITLE
[4.x]: Product and Variant GQL return an error

### ISSUE THREAD

**Issue by aodihis** [craftcms/commerce#2793]
### Description
We have entries that have a product field under the matrix and use graphQL to query it, an error occurs.
This only happens on Craft CMS RC, it's working fine on Beta, looks like there is a change on the source when it's preloaded.

Just a suggestion under resolver should it change to this instead to make it safe :

```
// If it's preloaded, it's preloaded.
if (!$query instanceof ElementQuery) {
            return $query;
        }
```

### Steps to reproduce

1. Create an entry.
2. Create a matrix that has a product field.
3. Add that matrix to the entry
4. Query the entry with the matrix field and the product field also.

### Expected behavior

the query will work normally.

### Actual behavior
An error occurs on step 4

### Craft CMS version

4.0.0-RC2

### Craft Commerce version

4.0.0-beta-2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Commerce 4.0.0-RC1 is now out with a fix.
