### ISSUE TITLE
[4.x]: On CMS Payment doesn't work

### ISSUE THREAD

**Issue by aodihis** [craftcms/commerce#2795]
### Description
In Commerce, we can do on cms payment, but somehow this doesn't work on commerce 4. 

### Steps to reproduce

1. Create an order with the complete user and line items inside cms, then update the order
2. On the transaction tab, click on make a payment.
3. The payment form modal will pop up, then input the correct value.
4. Click Pay.
5. The page will refresh after it. 

### Expected behavior
- In step 5 after the page is refreshed, the transaction should be updated, and the status of order should be paid.

### Actual behavior
- Nothing happens.

Tested using dummy and stripe payment gateway.

### Craft CMS version

4.0.0-RC2

### Craft Commerce version

4.0.0-RC1

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@aodihis Which gateway?

**Comment by nfourtythree** [comment]
Hi @aodihis 

Thank you for reporting, we have pushed up a fix for this and we will get a release out for it as soon as we can.

Thanks!
