### ISSUE TITLE
[4.x]: UI issue when creating tax zone from the tax rate page

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#2799]
### Description
When you want to create a tax zone from within the taxrate edit page (/commerce/tax/taxrates/new) and you want to add an address condition on the country the select field is to small to see anythin
https://i.imgur.com/3gZnfkD.png

### Steps to reproduce

1. From a tax rate edit page create a new tax zone
2. try to add a country address condition

### Expected behavior
Have a bigger popup or maybe even a slideout

### Craft CMS version

4.0.0-RC3

### Craft Commerce version

4.0.0-RC1

### PHP version

8.0.8

### Operating system and version

Linux 5.13.0-40-generic

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.5.0 (ImageMagick 6.9.10-23)

**Comment by lukeholder** [comment]
Thanks, made an temporary improvement fix for the next release until, the modal is moved to a slideout.
