### ISSUE TITLE
[4.x]: primary shipping and billing address is not set on new order

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#2804]
### Description
When a customer has an address that is marked as primary address (https://i.imgur.com/wlUL2lB.png) it is not automatically set as the shipping/billing address for new carts, even with overwriting the 'autoSetNewCartAddresses' to true in the commerce.php config file

### Steps to reproduce

1. have a logged in user with a primary billing/shipping address
2. Add an item to the cart
3. both shipping and billing addresses are still empty

### Expected behavior
The new cart should have the primary addresses set as cart address

### Actual behavior
Cart addresses are still empty

### Craft CMS version

4.0.0.1

### Craft Commerce version

4.0.0

### PHP version

8.0.8

### Operating system and version

Linux 5.13.0-40-generic

### Database type and version

MySQL 8.0.26

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
I see the issue. Looks like the auto setting is setting the source address ID and not a order specific copy. Will make a fix shortly.
