### ISSUE TITLE
[3.x]: Unable to set shippingAddress and update it simultaneously 

### ISSUE THREAD

**Issue by rynpsc** [craftcms/commerce#2805]
### Description

From the documentation it suggests that both the `shippingAddressId` and `shippingAddress` fields can be changed in the same request, however this doesn't appear to work.

> If we were updating an existing address, we could use this same form but simply populate shippingAddressId with the ID of the address we’d like to update.

https://craftcms.com/docs/commerce/3.x/addresses.html#submit-new-addresses-during-checkout

To give some context we have checkout page where the user picks their shipping address, they can pick an existing one or add a new one, if there's a validation error with the address they are trying to switch to e.g. address requirements have changed since it was added, we want to keep them within the checkout i.e still submitting to `commerce/cart/update-cart` but show them a form that allows them to edit that address, passing along the new address ID and the updated, valid field values.

In that form we have code that can be simplified down to:

```
<form method="post">
   {{ csrfInput() }}
   {{ actionInput('commerce/cart/update-cart') }}
   {{ hiddenInput('successMessage', 'Updated shipping address.'|hash) }}

   {# This is the address the user is trying to switch to, assume cart.shippingAddress.id is currently 1 #}
   {{ hiddenInput('shippingAddressId', '2') }}
   
   {# Setting address fields on the Address whose ID is 2 #}
   <input type="text" name="shippingAddress[firstName]" value="">

   <button type="submit">Add to Cart</button>
</form>
```

### Steps to reproduce

1. Create two addresses and set the first and last name on both
2. Post to `'commerce/cart/update-cart`, whilst trying to set a different but already existing `shippingAddressId` along with an updated `shippingAddress[firstName]

### Expected behavior

`cart.shippingAddress` is set to that matching the given `shippingAddressId` and `shippingAddress.firstName` is updated to new value

### Actual behavior

`cart.shippingAddress.id` is changed but the `shippingAddress` model still has the old value.

### Craft CMS version

Craft Pro 3.7.40.1

### Craft Commerce version

3.4.14

### PHP version

8.0.1

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 5.7.35

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
I see the issue. Looks like the auto setting is setting the source address ID and not a order specific copy. Will make a fix shortly.

**Comment by lukeholder** [comment]
Have you tried

`<input type="text" name="shippingAddress[id]" value="2">`

to update the address with that ID while in the cart. It should work.
