### ISSUE TITLE
Order Model : Total Discount

### ISSUE THREAD

**Issue by magnessjo** [craftcms/commerce#281]
### Description

The change log lists the removal of base discount (along with other base properties), but it doesn't list Total Discount as being removed from the model.  Is that to be expected?  If so, would iterating over the adjustments discounts (which are on each line item) be the best way to get the total discount for the order?  

**A use case scenario:**  

A summary page for an end user where their cart is listed.  An example cart could be  20 line items with varying quantities.  On the page, there is also a summary of the totals including discounts, tax, shipping, etc. 

The user modifies a line item (either removing it and adjusting the quantity) and the form is posted via AJAX.  The return value is a JSON object with the cart instance (order model).  This model is used to adjust the totals on the page.  

### Additional info

- Craft version: Craft Pro 3.0.0-RC17.1
- PHP version: 7.0.19
- Database driver & version: MySQL 5.7.18
- Plugins & versions:

Commerce : dev-develop as 2.0.0-alpha.99

**Comment by lukeholder** [comment]
@magnessjo Hopefully this part of the docs will assist: https://github.com/craftcms/commerce-docs/blob/v2/en/order-model.md#getadjustmentstotalbytypetype-included

Let me know.

**Comment by magnessjo** [comment]
@lukeholder,

  I am using those tags on page load with no issue (so this issue could be closed and I hack around it), but I imagine this type of UI interaction is common so I wanted to make sure that is the current recommend way.  
![screen shot 2018-03-31 at 3 09 17 pm](https://user-images.githubusercontent.com/856595/38166761-38aeaca6-34f7-11e8-9300-12f3e8c74477.png)


  I've attached an image of discount array that is part of the adjustments object that is returned when a user submits a post to /update-cart.  My work around for getting the current discounts after a coupon has been submitted via AJAX (without page reload), would be to iterate over each discount and compile a total from discount.amount.
