### ISSUE TITLE
[4.x]: Twig Runtime Error on subscription edit page, method FieldLayoutTab::getFields() doesn't exist in Craft 4

### ISSUE THREAD

**Issue by mtnorthrop** [craftcms/commerce#2818]
### Description
I've just upgraded Craft to 4.0.2 and Commerce to 4.0.0. When I click on an existing subscription in the Control Panel, I'm taken to the `/admin/commerce/subscriptions/{subscriptionID}` URL, which maps to the `craft\commerce\controllers\SubscriptionsController::actionEdit()` action.

On this page, I'm shown an error with the message 
```
Twig Runtime Error – Twig\Error\RuntimeError
Calling unknown method: craft\models\FieldLayoutTab::getFields()
```
The stacktrace highlights line 162 of `/commerce/src/templates/subscriptions/_edit.twig`, where `tab.getFields()` is called. Sure enough, in Craft 4, the `FieldLayoutTab` class does not have a `getFields()` method. (This method _does_ exist in Craft 3.7, though.)

**Note: This error only shows up when you're in devMode. When the website is not in devMode, the Twig error is ignored and the page is displayed. Also, this error only appears if you have set up custom subscription fields under _Commerce > System Settings > Subscription fields_.**

### Craft CMS version

4.0.2

### Craft Commerce version

4.0.0

### PHP version

8.0.13

### Operating system and version

Linux 5.4.0-110-generic

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.5.1 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Relevant plugins:

Commerce 4.0.0
Stripe for Craft Commerce 3.0.0

**Comment by lukeholder** [comment]
This is now fixed in 4.1
See changelog here: https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#410---2022-07-19
