### ISSUE TITLE
[3.4.14]: Removing End Date on promotional discount clears usage counter

### ISSUE THREAD

**Issue by zackspear** [craftcms/commerce#2819]
### What happened?

When attempting to remove an end date on a discount to allow further usage of the discount our content editor noticed it reset the usage counter. In my attempt to recreate I confirmed this as removing the end date showed an alert warning it would reset the usage counter (in screenshot below).

Our content editor said, "Yeah- it did say "clear discount usage counter" but 1) Didn't think that would actually happen 2) Thought maybe it was using counter to mean Date? Dunno, but was not my intention"

Edit: In further testing if you hit the "Cancel" option in the alert it will remove the date and not reset the counter.
Seems like a small JavaScript error that's triggering the "Clear Counter" button event. Hopefully a quick fix.

### Steps to reproduce

1. Create a discount with an end date and a finite Total Discount Use Limit
2. Use the discount to increment the usage counter
3. Go back to discount settings and attempt to remove end date in the _Conditions_ tab

<img width="753" alt="Screen Shot 2022-05-18 at 11 52 26" src="https://user-images.githubusercontent.com/2531682/169130378-fa4978e4-609f-4740-8695-c15c2bb668cc.png">
<img width="840" alt="Screen Shot 2022-05-18 at 11 52 54" src="https://user-images.githubusercontent.com/2531682/169130456-13889456-4999-44f2-b2dc-efaaf3b08a76.png">
<img width="698" alt="Screen Shot 2022-05-18 at 11 53 18" src="https://user-images.githubusercontent.com/2531682/169130509-e1ee9fe9-58b9-4208-963d-a4bf476d5076.png">

### Expected behavior

Only the end date would be removed and usage counter would keep its count

### Actual behavior

Removing the end date removes both the end date and resets counter for Total Discount Use Limit

### Craft CMS version

3.7.42

### Craft Commerce version

3.4.14

### PHP version

7.4.28

### Operating system and version

Linux 5.4.0-1058-aws

### Database type and version

MySQL 5.5.5

### Image driver and version

GD 7.4.28

### Installed plugins and versions

- Amazon S3 1.3.0
- Asset Rev 6.0.2
- AsyncQueue 2.3.0
- Braintree for Craft Commerce 2.4.1
- CP Field Inspect 1.4.4
- Contact Form 2.5.1
- Contact Form Honeypot 1.0.3
- Cookies 1.1.15
- Craft Commerce 3.4.14
- Digital Products 2.4.3.2
- Empty Coalesce 1.0.6
- Feed Me 4.5.1
- Fetch 1.3.0
- Gift Voucher 2.7.0
- HTTP2 Server Push 1.0.1
- IPB Auth 1.0.0
- PayPal Checkout for Craft Commerce 1.3.2.1
- Redactor 2.10.8
- SEOmatic 3.4.30
- Snaptcha 3.0.11
- Stripe Payments 3.4.2
- Stripe for Craft Commerce 2.4.3
- Super Table 2.7.1
- Two-Factor Authentication 2.10.0
- Typed link field 1.0.25

**Comment by nfourtythree** [comment]
Hi @zackspear 

Thank you for bringing this to our attention. We have just pushed a fix for this which will be included in the next release of Commerce.

Thanks!
