### ISSUE TITLE
[4.x]: Order status change modal’s email suppression field appears twice

### ISSUE THREAD

**Issue by mattstein** [craftcms/commerce#2821]
### Description

If I go to update order statuses in bulk, I have a new “Suppress emails” option—but it appears twice.

<img src="https://user-images.githubusercontent.com/2488775/169575266-b88e4432-66f9-4c41-9ac5-cd370ef58dd2.gif" width="500">

This is only an issue in that modal, and not when changing the status from the order edit screen.

### Steps to reproduce

1. Start with a Commerce 4 build that has order status emails configured and some orders to work with.
2. Go to **Commerce** → **Orders** and click checkboxes next to one or more orders.
3. Press the element action gear/dropdown menu and **Update Order Status...**.
4. Observe the _two_ “Suppress emails” checkbox fields, where the second controls the first.

### Expected behavior

I’d see a single “Suppress emails” field I could toggle on or off.

### Actual behavior

I see two “Suppress emails” fields, where the first _and_ the second toggle that first one on or off.

### Craft CMS version

4.0.2

### Craft Commerce version

4.0.1

### PHP version

8.0.15

### Operating system and version

macOS 12.3.1

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.6.0

**Comment by mattstein** [comment]
Bonus nitpick: “Cancel” and “Update” represent two distinctly separate actions and should not be conjoined in a unibutton. Separating them would be more in line with Craft’s add asset modal:
<img width="604" alt="Screen Shot 2022-05-20 at 10 25 58 AM@2x" src="https://user-images.githubusercontent.com/2488775/169580984-aab27c4d-f88e-4d27-b6db-487ac2e14fee.png">

**Comment by lukeholder** [comment]
Thanks, fixed both for the next release.

**Comment by brandonkelly** [comment]
Commerce 4.0.2 is out now with these fixes
