### ISSUE TITLE
[4.x]: Error while creating a new Shipping rule with particular parameters

### ISSUE THREAD

**Issue by Stalex89** [craftcms/commerce#2824]
### Description

While creating the custom shipping method and shipping rule if you set the shipping rule "Order Total Weight" -> "Maximum" to 10000  and both "Minimum Total Shipping Cost" and "Maximum Total Shipping Cost" to 8, the following error will be thrown: 

```
   Cannot assign string to property craft\commerce\models\ShippingRule::$maxWeight of type float in 
   /vendor/craftcms/commerce/src/controllers/ShippingRulesController.phpat line 129
```

### Steps to reproduce

1. Create a new Shipping method
2. Click on a " + New shipping rule" button
3. Inside "Conditions" tab set "Order Total Weight" maximum value to 10000
4. Inside "Costs" tab set "Minimum Total Shipping Cost" to 8 and "Maximum Total Shipping Cost" to 8
5. Click on Save

### Expected behavior

Should create a new shipping rules with the following parameters

### Actual behavior

Throws an error (see screenshot)

P.S: It seems to create a new shipping rule when you return to the shipping method page, but it also returns an error when you try to delete this shipping rule (see screenshot)

P.S.S: It seems to work fine if you set the "Order Total Weight" maximum value to lower values (for ex. 10)

Screenshots:

<img width="1557" alt="Screenshot 2022-05-24 at 11 14 06" src="https://user-images.githubusercontent.com/23526237/170003797-ff9d00d4-eb25-489c-96d0-ac79d76d6ccb.png">

<img width="1910" alt="170003833-c366437d-0f43-42f2-8890-6094a2e091e0" src="https://user-images.githubusercontent.com/23526237/170280103-a75c914b-88c4-47b4-a9f2-aced064bc143.png">

### Craft CMS version

Craft Pro 4.0.3

### Craft Commerce version

4.0.1

### PHP version

8.1.6

### Operating system and version

Darwin 21.4.0

### Database type and version

MySQL 8.0.29

### Image driver and version

GD 8.1.6

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi

Thank you for reporting this issue, we have pushed up a fix for this which will be included in the next release of Commerce.

Thanks!
