### ISSUE TITLE
[4.x]:  Sales Cannot be open if have action effect more than one thousand

### ISSUE THREAD

**Issue by aodihis** [craftcms/commerce#2827]
### Description
We have the promotions sale with the action effect is set to flat with value is 1899. The save is work fine, but when we want to open it the page return this error.

`Cannot assign string to property craft\commerce\models\Sale::$applyAmount of type ?float`

and the error pointing to this :

`$variables['sale']->applyAmount = Craft::$app->getFormatter()->asDecimal(-(float)$variables['sale']->applyAmount);`

This only happen if I have the sales action effect value more then one thousand, looks like when you convert to string the value changed to 1,899 and it not accepted.

### Steps to reproduce

1. Created the sales
2. Update the action effect to to flat and update the value is more than one thousand.
3. Save it
4. Re-open the sales  again.

### Expected behavior
- The sales will be open again.

### Actual behavior
- Cannot be open and return an error.

### Craft CMS version

4.0.3

### Craft Commerce version

4.0.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @aodihis 

Thank you for bringing this to our attention. We have pushed up a fix which will be included in the next release of Commerce.

Thanks!
