### ISSUE TITLE
Type Error in elements/Order::setEmail.  

### ISSUE THREAD

**Issue by magnessjo** [craftcms/commerce#283]
### Description

Error: TypeError: Argument 1 passed to craft\commerce\elements\Order::setEmail() must be of the type string, null given.  

### Steps to reproduce

1.  Select Inactive Carts in carts list on the commerce/orders page.  Make sure there are 0 carts in inactive carts 

### Additional info

- Craft version: Craft Pro 3.0.0-RC17.1
- PHP version: 7.0.19
- Database driver & version: MySQL 5.7.18
- Plugins & versions:
Commerce : dev-develop as 2.0.0-alpha.99

**Comment by lukeholder** [comment]
Can't reproduce this error. Please send DB dump where this is happening to support@craftcommerce.com thanks.

**Comment by lukeholder** [comment]
Please see #300

**Comment by lukeholder** [comment]
Start the upgrade again but upgrade to the latest commerce beta. Thanks.

**Comment by magnessjo** [comment]
@lukeholder,

  I attempted a migration but found a PDO error that I entered [304](https://github.com/craftcms/commerce/issues/304).  

  I can attempt to validate this issue is fixed once 304 has been resolved.  

  Thanks for keeping at it.  I know it's been a busy 24 hours!
