### ISSUE TITLE
[4.x]: TypeError Cannot assign string to property craft\commerce\elements\Subscription::$dateCanceled of type ?DateTime

### ISSUE THREAD

**Issue by JansonChe** [craftcms/commerce#2831]
### Description
While testing out the subscription cancel functionality (in both CP and example template) this error showed up. The subscription in Stripe is successfully canceled, but not in Craft Commerce. Therefore the subscriptions are now out of sync. I've tested both immediate cancellation and by end of period. While immediate cancellation only cancels the Stripe Subscription, the one for end of period seems to work after a reload, but both show this error.

Is there a way to get Stripe and Craft Subscriptions in sync again?

Thanks a lot!

### Steps to reproduce

1. Setup Craft 4 with Commerce Light
2. Add Stripe Plugin
3. Setup 2 Products in Stripe, each with 2 Prices (monthly/yearly)
4. Make 4 Plans in Craft Commerce and assign the 4 pricing variants.
5. Copy example Twig Templates accordion to docs.
6. Login as a User (any)
7. Subscribe to one of the plans
8. Try to cancel the subscription in CP or FE (the error appears in both cases)
9. Reload after error and compare Stripe to Commerce Subscriptions panel.

### Expected behavior
- Error should not get Stripe and Commerce out of sync. Either prevent both cancellations or try to sync when trying to cancel the already canceled subscription again.

### Actual behavior
- Subscription gets canceled in Stripe, but not Craft

### Craft CMS version

4.0.3

### Craft Commerce version

4.0.1

### PHP version

8.1.6

### Operating system and version

Linux 5.10.76-linuxkit (Craft Nitro)

### Database type and version

MySQL 8.0.24

### Installed plugins and versions

- "craftcms/commerce": "4.0.1"
- "craftcms/commerce-stripe": "3.0.0"
- "verbb/formie": "2.0.0-beta.10"

**Comment by nfourtythree** [comment]
Hi

Thank you for reporting this, we have pushed a fix which will be included in the next release of Commerce.

Thanks!
