### ISSUE TITLE
[4.x]: Update existing cart address for firstName and lastName not possible

### ISSUE THREAD

**Issue by rene-haefliger** [craftcms/commerce#2832]
### Description
When updating an existing cart address, firstName and lastName are not updated. All other fields are saved correctly.

### Steps to reproduce
Update an existing cart address according to Docs.

```
{% set cart = craft.commerce.carts.getCart() %}
{% set address = cart.shippingAddress %}

<form method="post">
  {{ csrfInput() }}
  {{ actionInput('commerce/cart/update-cart') }}
  {{ hiddenInput('successMessage', 'Updated addresses.'|hash) }}

  {{ hiddenInput('shippingAddress[id]', address.id) }}
  <input type="text" name="shippingAddress[firstName]" value="{{ address.firstName }}">
  <input type="text" name="shippingAddress[lastName]" value="{{ address.lastName }}">

  {# ... #}

  <button>Update Address</button>
</form>
```

### Expected behavior
All fields are saved with changed values.

### Actual behavior
firstName and lastName are not saved.

### Craft CMS version

Craft Pro 4.0.3

### Craft Commerce version

4.1.x-dev

### PHP version

8.0.18

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@rene-haefliger First Name and Last name is not an attribute of the Address element anymore. Use the `fullName` instead as given on the example template

```
    {{ input('text', 'fullName', address.fullName ?? '', {
      id: 'fullName',
      class: ['w-full', 'border border-gray-300 hover:border-gray-500 px-4 py-2 leading-tight rounded']
    }) }}
```

Craft will auto parse the FullName to firstName and lastName but if you want the user to input them separately you'll have to create address custom fields for that.
