### ISSUE TITLE
[3.x]: Cart `totalQty` / line item quantity reflects incorrect quantity when updating cart and receiving cart stock error

### ISSUE THREAD

**Issue by iamkeir** [craftcms/commerce#2836]
### Description

When updating cart line item quantity above available stock and receiving cart stock notice/error, line item quantity and cart `totalQty` reflects quantity **_submitted_**, not actual quantity in cart. You cannot therefore show the cart with the actual/correct quantities.

### Steps to reproduce

1. Add an item to cart with quantity below current stock total
2. Update same line item in cart with quantity above current stock total
3. Output line item quantity, notice it is quantity **_submitted_**, not the actual quantity in cart
4. Output cart `totalQty`, notice it is quantity including what was **_submitted_**, not what is actually in cart
5. View the cart in Craft admin, item quantity/`totalQty` is still the correct quantity in cart
6. Refresh cart page (without re-submitting quantity form), notice item quantity/`totalQty` reverts to correct quantities

### Expected behavior

`totalQty` and line item `qty` should reflect the actual quantities in the cart, not the value that was submitted (and failed). If the submitted value is needed for anything, it could just be retrieved from the submitted form data via `getParam` or similar?

### Actual behavior

`totalQty` and line item `qty` reflect the quantities submitted (and failed).

### Craft CMS version

Craft Pro 3.7.44

### Craft Commerce version

3.4.15

### PHP version

8.0.8

### Operating system and version

Darwin 21.1.0

### Database type and version

MySQL 5.7.34

### Image driver and version

GD 8.0.8

**Comment by lukeholder** [comment]
If the cart is in error, it has data on it that is in error. This allows the customer to fix the data (like qty too high for product, and still see what they entered)

I you want to see the original values of totals we have these:

`cart.*`:

```
storedTotalPrice
storedTotalPaid
storedItemTotal
storedTotalDiscount
storedTotalShippingCost
storedTotalTax
storedTotalTaxIncluded
storedItemSubtotal
```

Otherwise you will need to reteive the cart from the db that is in the last valid state with:

```
{% set originalCart = craft.orders.number(cart.number).one() %}
```

Then do `originalCart.totalQty`.


We could look to add a `storedTotalQty`.

**Comment by iamkeir** [comment]
@lukeholder I am still struggling to understand the logic here.

If I want to`still see what they entered`, we can access this from the form data that was submitted - that is the true indicator of what was entered, and how other forms work in the event of a failure of submission.

Having what they entered stored against `cart.totalQty` is misleading because it isn't the current cart `totalQty` because it failed to add (which is demonstrated by refreshing the cart a further time and it reverts to the actual total quantity).
