### ISSUE TITLE
[4.x]: Fields/UI Elements no longer available in Variant Fields

### ISSUE THREAD

**Issue by robzor** [craftcms/commerce#2837]
### Description
In Commerce 3, the 'UI Elements' options were available when creating a field layout for a variant.

In Commerce 4, they do not exist for variants, only under Product fields.

### Steps to reproduce

1. Go to Commerce > System Settings > Product Types for a product that has variants enabled.

### Expected behavior

![CleanShot 2022-06-06 at 12 57 45](https://user-images.githubusercontent.com/704032/172156731-ad84d2f2-5e06-47d6-a223-d722d111c17b.png)

### Actual behavior

![CleanShot 2022-06-06 at 12 57 31](https://user-images.githubusercontent.com/704032/172156750-425fdc4a-5b13-4dc2-8928-4dfc3bf77517.png)

### Craft CMS version

4.0.4

### Craft Commerce version

4.0.2

### PHP version

8

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @robzor 

Thank you for bringing this to our attention. This turned out to be a bug in Craft, we have pushed a fix for this: https://github.com/craftcms/cms/commit/976a67f07d451e9552e0d9afe2a8aa742b8b557e which will be included in the next patch release of the CMS.

Thanks!

**Comment by robzor** [comment]
Thanks @nfourtythree !
