### ISSUE TITLE
[Bug] Stripe Gateway Property Exception : includeReceiptEmailInRequests

### ISSUE THREAD

**Issue by magnessjo** [craftcms/commerce#284]
### Description

In Commerce 1, there was a setting for 'Include Receipt Email In Requests' in the Stripe Payment Method config.  It appears to have been removed for Commerce 2 and an exception is thrown when checking for existence of the property.  

### Steps to reproduce

1.  Migrate Commerce 1 db to commerce 2.  
2. Install Stripe Commerce plugin
3. Select either an active cart or Gateways under settings.  

### Additional info

- Craft version: Craft Pro 3.0.0-RC17.1
- PHP version: 7.0.19
- Database driver & version:  MySQL 5.7.18
- Plugins & versions:

Commerce : dev-develop as 2.0.0-alpha.99
Commerce Stripe: dev-master as 1.0.0-alpha.99

**Comment by andris-sevcenko** [comment]
The config setting is now called `sendReceiptEmail`. If you change it to reflect that, all should be working.

In the future, please submit Stripe Gateway issues to `craftcms/commerce-stripe` repository, thanks!

**Comment by andris-sevcenko** [comment]
Fixed in craftcms/commerce-stripe@2c2add2
