### ISSUE TITLE
[4.x]: Unable to use different shipping and billing in example templates

### ISSUE THREAD

**Issue by rynpsc** [craftcms/commerce#2841]
### Description

When using the example templates and entering a new shipping and new billing address that are different, the billing address overrides the shipping address and they get set to the same model.

### Craft CMS version

4.04

### Craft Commerce version

4.0.2

### Installed plugins and versions

-

**Comment by rynpsc** [comment]
Sorry I thought it was easier to replicate that in actually is. I'm able to replicate this when checking out as a guest.

1. Start out by adding a shipping address and making the billing address the same as shipping then proceeding to the next page in the checkout via "Confirm addresses".
2. Then go back to the address page and change to using a separate billing address, making edits to the billing address and proceeding to the next page in the checkout via "Confirm addresses".
3. Go back to the address page again and the edits you have made to the billing address have been copied to the shipping address.

Any further edits to the shipping address will always be overridden by the details in the billing address.

This video demonstrates the issue described in steps 1 to 3.

https://user-images.githubusercontent.com/5955881/173013308-72ed7f50-2722-4f77-a394-67347c584aea.mov

I'm also seeing this behaviour in our own templates which were working pre Commerce 4, amongst some other issues with the address changes but with the example templates also having issues is hard to see exactly what's going on.

I've done a quick check and the fields in the example templates are using the correct namespaces `shippingAddress[]`, `billingAddress`. I suspect is has something to do with the way address are being cloned but that's a wild guess.

**Comment by pdaleramirez** [comment]
I believe this issue will get fixed on Commerce version 4.1 release.

**Comment by rynpsc** [comment]
Any idea when we might see 4.1? We've a couple of outstanding issues with addresses including this one along with https://github.com/craftcms/commerce/issues/2850 and https://github.com/craftcms/commerce/issues/2844 that do significantly hinder the checkout process and are a regression in 3.x behaviour.

**Comment by lukeholder** [comment]
@rynpsc 4.1 was released a few hours ago.

See changelog here: https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#410---2022-07-19
