### ISSUE TITLE
[3.4.14]: Can't query order by totalQty

### ISSUE THREAD

**Issue by pnpaes** [craftcms/commerce#2858]
### Description
I am building a custom Module that will be able to filter orders on certain criteria.
One of them is that I have to be able to return orders that have 1 single line item and its quantity is one.
That means that I am trying to apply a `totalQty => 1 `. Although this property is part of the order object it is not available for use in the filter.

Would it be possible to make it available or is there any other way that I can achieve this?

### Craft CMS version

Craft Pro 3.7.38

### Craft Commerce version

3.4.14

### PHP version

8.0.3

### Operating system and version

Linux 5.4.0-70-generic

### Database type and version

MySQL 5.5.5

### Image driver and version

Imagick 3.4.4 (ImageMagick 6.9.10-23)

### Installed plugins and versions

Contact Form - 2.3.0
Contact Form Extensions - 1.3.0
Craft Commerce - 3.4.14
Feed Me - 4.5.2
Field Manager - 2.2.4
Klarna Checkout for Craft Commerce - 3.1.2
Redactor - 2.10.6
Super Table - 2.7.1
XML Sitemap - 1.3.1

**Comment by lukeholder** [comment]
This is now possible as of 4.2.0
