### ISSUE TITLE
[4.x]: address fields in cart revert to primary billing/shipping when updated when user has addresses saved with primary billing/shipping

### ISSUE THREAD

**Issue by Nellyaa** [craftcms/commerce#2863]
### Description

When you are a registered user with saved primary billing and/or shipping settings on one/two on your saved addresses these will always override all changes you did to your carts addresses and get reapplied all the time. 
This makes it impossible to choose an address that is not primary billing/shipping during checkout.

### Steps to reproduce

1. Be a registered user 
2. Save a few addresses with the commerce "primary billing/shipping" field and turn on the lightswitches on an address
3. Create a cart
4. The addresses will be auto-populated with the saved addresses that are primary billing/shipping
5. Change one of the addresses to another that is not primary billing/shipping and update your cart (works on the frontend and the backend)
6. Reload the page
7. Observe that the address has reverted to the saved address that had primary billing/shipping set, all changes to the addresses are lost

### Expected behavior

When you edit the address or select another saved address this address should stay instead of being reverted to the primary billing/shipping address.

### Actual behavior

The changes are being reverted and the primary billing/shipping address will override all changes always.

### Craft CMS version

4.0.5

### Craft Commerce version

4.0.3

### PHP version

8.1.7

### Operating system and version

Linux 5.10.16.3-microsoft-standard-WSL2

### Database type and version

MySQL 10.7.3

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by lukeholder** [comment]
This is now fixed in 4.1 see changelog here: https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#410---2022-07-19
