### ISSUE TITLE
[4.x]: commerce/cart/update-cart doesn't update custom fields

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#2873]
### Description

I have added a couple of custom field to the user addresses object e.g. First Name, Last Name, Phone Number. 

I have tested using the commerce example template files, and while you can update the values of these custom fields using the `users/save-address` form, it seems as though these are not saving within an `commerce/cart/update-cart` form. 

### Steps to reproduce

1. Create custom fields e.g. Phone Number and add to user address fields
2. Try submitting the following form

```
<form method="post">

    {{ csrfInput() }}
    {{ redirectInput('/checkout/shipping') }}
    {{ actionInput('commerce/cart/update-cart') }}

    <input type="text" name="shippingAddress[phoneNumber]">

    <button>
        Submit
    </button>

</form>
```

### Craft CMS version

4.0.2

### Craft Commerce version

4.0.1

### PHP version

8.0.20

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@iamtompickering 

It should be `shippingAddress[fields][phoneNumber]"` to update custom fields
