### ISSUE TITLE
[4.x]: Setting autoSetCartShippingMethodOption in the commerce config results in out of memory

### ISSUE THREAD

**Issue by Nellyaa** [craftcms/commerce#2875]
### Description

When you enable the autoSetCartShippingMethodOption config setting within the commerce settings the frontend and backend become unusable/load forever, ending up with a 502 Bad Gateway.
The website loads fine when the setting is not active.

### Steps to reproduce

1. Enter 'autoSetCartShippingMethodOption' => true in the commerce config file
2. Observe all frontend and some parts of the backend (like admin/commerce/orders/cartsActive) are now not loading anymore

### Expected behavior

Frontend and backend pages load fine and a viable shipping method is being applied to carts automatically

### Craft CMS version

4.0.5

### Craft Commerce version

4.0.3

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
I was able to replicate this. Infinite loop on the condition.
