### ISSUE TITLE
[3.x]: Failing Zip Code Condition Formula test doesn't return an error

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/commerce#2877]
### What happened?

I'm using a regex to match and exclude specific post codes. When entering a non-matching post code, no error is returned to indicate the failure.

Can a custom validator be setup for this to return an error? If so how? If not how do we notify the user?

### Craft CMS version

3 latest

### Craft Commerce version

3 latest

**Comment by pixelmachine** [comment]
Example use case for why this is necessary:

Store sells non-perishable items and perishable items. These require different types of delivery and perishable items cannot be delivered to certain remote locations.

As the zip/post code validation doesn't return any clue that it's been run I can't let the user know they're in an excluded postcode for perishable items but they can still buy perishable ones. I would have to show a long generic message that also applies to numerous other things to explain the restrictions.

**Comment by pixelmachine** [comment]
The alternative to returning an error would be to make the matching formula available to the templates so you could check the against it directly in the template. 

I found the `getZipCodeConditionFormula()` methods but I don't think that's available to the templates.

**Comment by nfourtythree** [comment]
Hi @pixelmachine 

The zip code condition formula matching is there for determining whether a shipping method is selectable, there isn't validation as such. If the customer had selected a shipping method and then changes their address which means that method is no longer available a [cart notice](https://craftcms.com/docs/commerce/3.x/orders-carts.html#order-notices) will be added to the cart.

You are able to get access to the formula in the templates but I am thinking there is maybe an easier way to get what you are looking for. You could check the [getAvailableShippingMethodOptions()](https://docs.craftcms.com/commerce/api/v3/craft-commerce-elements-order.html#method-getavailableshippingmethodoptions) on the order and see if the specific method you are looking for is in there and if not show the information as to why. Would this work for your use case?

Thanks

**Comment by nfourtythree** [comment]
@pixelmachine I assume you must have at least one rule that is linked to a shipping zone that has a zip code condition? If I am following correctly I am not sure you would need to add any more rules.

If you are only wanting to know if the customer has access to a particular shipping method then you can simply see if that method is in the list that is returned in `getAvailableShippingMethodOptions()`. If that method is not in there then you know for one reason or another (depending on what other conditions it has) it is not compatible with the current cart.

Hope this helps.

**Comment by pixelmachine** [comment]
Ok, I think I'm going to close this because I think what I asked is achievable by looping over shipping methods, rules and zones and checking the zipCode.
