### ISSUE TITLE
Discount via coupon code does not take shipping cost into account [3.x]: 

### ISSUE THREAD

**Issue by hhentschel** [craftcms/commerce#2880]
### Description
A customer has items for 48 dollar in the cart and applies a discount for 50 dollar via coupon code.
The result is a cart of 0. In the next step customers chooses a shipping with a cost of 10 dollar. 
Now the Value/Cost the customer has to pay is 10.

The same happens as well, if shipping cost are already applied to cart.

### Steps to reproduce

1. Fill Cart with items of total value smaller than the coupon discount value.
2. Apply discount.

### Expected behavior
The coupon discount should apply to the whole order, including shipping cost.
Or an option to include shipping cost for the discount.
For the described situation, the cost for the customer should be 8 instead of 10.
Subtracting 2 dollar from the 50 dollar discount, which are a leftover.

### Actual behavior
Discount is only applied to cart order without shipping included.

### Craft CMS version

3.7.44

### Craft Commerce version

3.4.15

### PHP version

7.4.29

### Operating system and version

Linux 4.19.0-17-amd64

### Database type and version

MySQL 5.5.5

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

Back In Stock | 1.4.0
Contact Form | 2.5.1
CP Field Inspect | 1.4.4
Craft Commerce | 3.4.15
Expanded Singles | 1.2.0
Feed Me | 4.5.3
Mailjet | 1.2.3
Neo | 2.13.11
Redactor | 2.10.8
Retour | 3.1.72
SEOmatic | 3.4.31
Servd Assets and Helpers | 2.6.3
Sprig | 1.13.0
Typed link field | 1.0.25
Untransform | 1.0.2

**Comment by lukeholder** [comment]
Are your shipping costs added to line items or to the whole order? Discounts can only discount line item totals and not order level adjustments, which I think your shipping cost is.

Could you try adding line item level shipping costs, and no shipping base rate, and see if that fixes it?
