### ISSUE TITLE
[4.x]: Order total incorrect when including line item adjusters

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#2884]
### Description
Order totals are not matching up. See screenshots below of what I am seeing. 

Looks like it is adding an additional line item adjustment, when there should only be one included.

<img width="962" alt="CleanShot 2022-07-08 at 12 35 53@2x" src="https://user-images.githubusercontent.com/6592882/177984973-e04f834e-b05b-44c4-95ae-7b021d80f6c0.png">

<img width="981" alt="CleanShot 2022-07-08 at 12 36 04@2x" src="https://user-images.githubusercontent.com/6592882/177984983-337447ae-cc72-4d8e-9e25-d6ac66fd23ab.png">

<img width="864" alt="CleanShot 2022-07-08 at 12 36 17@2x" src="https://user-images.githubusercontent.com/6592882/177985005-029f9657-8b87-40e6-80ac-17b466ae8717.png">

### Craft CMS version

4.0.2

### Craft Commerce version

4.0.1

### Installed plugins and versions

-

**Comment by iamtompickering** [comment]
@nfourtythree yep that's correct, here's the code in case you need to test

```
public function adjust(Order $order): array
    {
        $adjustments = [];
        foreach ($order->lineItems as $lineItem)
        {

            $adjustment = $this->_getEmptyOrderAdjustmentFor($order);
            $adjustment->lineItemId = $lineItem->id;

            $product = Product::find()
                ->id($lineItem->purchasable->product->id)
                ->one();

            foreach ($lineItem->options as $key => $value) {
            
                if ( ($key == 'giftMessage' || $key == 'giftName') && $value != '' ) {
                    $adjustment->name = $product->title . ': Gift adjustment';
                    $adjustment->type = $product->id;

                    // @TODO: Pull through global variable
                    $adjustment->amount = 4;
                    $adjustments[] = $adjustment;
                }

            }

        }

        return $adjustments;
    }
```

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

I noticed the line `$adjustment->type = $product->id;`, as of version 4 Commerce does not support adjuster types that are not: `discount`, `tax` or `shipping`. This is done to make sure Commerce is compatible with all gateways and that all the monetary data makes sense. 

This is outlined [in the docs](https://craftcms.com/docs/commerce/4.x/extend/adjusters.html#writing-an-adjuster).

Thanks!

**Comment by nfourtythree** [comment]
@iamtompickering I have just tried creating a custom adjuster with a custom type and things seemed to be working as expected.

My adjuster code was:

```php
<?php
namespace modules\adjusters;

use craft\base\Component;
use craft\commerce\base\AdjusterInterface;
use craft\commerce\elements\Order;
use craft\commerce\models\OrderAdjustment;

class MyAdjuster extends Component implements AdjusterInterface
{
    public function adjust(Order $order): array
    {
        $adjustments = [];

        foreach ($order->getLineItems() as $item) {
            $adjustment = new OrderAdjustment;
            $adjustment->type = 'zzz';
            $adjustment->name = '$2 extra';
            $adjustment->description = '$2 extra on everything';
            // `sourceSnapshot` can contain information to explain the adjustment
            $adjustment->sourceSnapshot = [ 'data' => 'value' ];
            $adjustment->amount = 2;
            $adjustment->setOrder($order);
            $adjustment->setLineItem($item);

            $adjustments[] = $adjustment;
        }

        return $adjustments;
    }
}
```

And here are the screenshots of the cart:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/P8uQ2Ry8/4b710a48-42f5-4741-ba87-58b4f24675dc.png?v=7e43d2fa4361ae2ff4f930313e6f9602)

![](https://p191.p3.n0.cdn.getcloudapp.com/items/9ZuoKABL/0290c9d0-0755-430c-82c6-69b2f661a801.png?v=3702dc0ae376e1feb219f2eb3792ce89)

![](https://p191.p3.n0.cdn.getcloudapp.com/items/JruopWqP/fb68ea4c-8b89-4ff0-b550-2c0a594bda48.png?v=b3868e5aeff164edfc6ec084b4e84dab)

Perhaps you can use the simplified adjuster from above to see if that works for you to eliminate any other possible issues.

Thanks.

**Comment by iamtompickering** [comment]
@nfourtythree thanks for the example code here, I'll try reworking my adjuster based around your structure and see how it goes
