### ISSUE TITLE
Update Cart : PDOException

### ISSUE THREAD

**Issue by magnessjo** [craftcms/commerce#289]
### Description

Error: PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'snapshot' at row 1.  

Error occurs when submitting an AJAX post to cart/update-cart.  

Note:  This error wasn't occurring yesterday so it appears related to the merge that occurred yesterday.  

### Steps to reproduce

1. Submit an AJAX post to /commerce/cart/update-cart

### Additional info

- Craft version: Craft Pro 3.0.0-RC17.1
- PHP version: 7.0.19
- Database driver & version: MySQL 5.7.18
- Plugins & versions:

craftcms/commerce: "dev-develop as 2.0.0-alpha.99"

**Comment by lukeholder** [comment]
`composer update` to bring in changes

**Comment by magnessjo** [comment]
Verified, thanks @lukeholder.
