### ISSUE TITLE
[4.x]: Unable to set firstName and lastName on Address

### ISSUE THREAD

**Issue by rynpsc** [craftcms/commerce#2906]
### Description

Since 4.1 you are unable to set `firstName` or `lastName` on the shipping or billing address and instead must use `fullName`. This is problematic as payment gateways such as Sage require an explicit first and last name which aren't passed as separate fields if using `fullName`.

### Steps to reproduce

1. Try to set `shippingAddress[firstName]` and  `shippingAddress[fields]` in the `commerce/cart/update-cart` action.

### Expected behavior

First name and last name are set.

### Actual behavior

First and last name aren't set.

### Craft CMS version

Craft Pro 4.1.4.1

### Craft Commerce version

4.1.0

### PHP version

8.0.21

### Installed plugins and versions

-

**Comment by rynpsc** [comment]
I'v been digging it this a little more and it would appear that if you have validation rules set for `firstName` and `lastName` then the fields are set so it would appear that `safeAttributes` are coming into play? I'm not sure if this is intentional or not?

```php
Event::on(
   Address::class,
   Address::EVENT_DEFINE_RULES,
   static function(DefineRulesEvent $event) {
      $event->rules[] = [['firstName'], 'required', 'message' => Craft::t('site', 'First name cannot be blank.')];
      $event->rules[] = [['lastName'], 'required', 'message' => Craft::t('site', 'Last name cannot be blank.')];
   }
);
```

**Comment by pdaleramirez** [comment]
On latest version of Commerce the address don't support firstName and lastName anymore. If you add firstName and lastName to the Model validation, it will not work because those aren't attributes to the Address Model.

 If you want to add firstName lastName to the address you will have to setup a firstName and lastName custom fields. You can set it up here: /admin/settings/users/address-fields - Control Panel -> Settings -> Users -> Address Fields.

**Comment by rynpsc** [comment]
Ah okay I thought firstName and lastName were still supported, pre 4.1 I'm sure they were still working. 

Most payment gateways require a first and last name but the current built in validation doesn't enforce that and we feel it's best to validate that info at time of entry. I've now added our own validation to enforce that.

For anyone else wanting to enforce first and last name validation the below should be a good starting point. It uses the same library that [Craft uses to parse names](https://github.com/craftcms/cms/blob/2eac9249964ccc553bf841c79b9ee44d58f16b61/src/base/NameTrait.php).

```php
use craft\elements\Address;
use craft\events\DefineRulesEvent;
use yii\base\Event;
use TheIconic\NameParser\Parser;

Event::on(
  Address::class,
  Address::EVENT_DEFINE_RULES,
  static function(DefineRulesEvent $event) {
    $event->rules[] = ['fullName', 'required'];
    $event->rules[] = ['fullName', function($attribute) use ($event) {
      $name = (new \TheIconic\NameParser\Parser())->parse($event->sender->$attribute);

      if (!$name->getFirstname()) {
        $event->sender->addError($attribute, Craft::t('site', 'A first name is required.'));
      }

      if (!$name->getLastname()) {
        $event->sender->addError($attribute, Craft::t('site', 'A last name is required.'));
      }
    }];
  }
);
```
