### ISSUE TITLE
[4.x]: Unable to change shipping / billing address when 'autoSetNewCartAddresses' is true

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#2907]
### Description
I have set `'autoSetNewCartAddresses' => true,` in the commerce config as I would like logged in users to have their primary shipping / billing address set to any of their carts by default. This config setting seems to work perfectly apart from when you try and update to another shipping / billing address. 

When I try and update the cart to a different saved address / brand new address, it just reverts back to the primary shipping / billing address. 

The only way around this currently is to also set whatever new address you're selected to also be the primary address, but this doesn't seem correct. 

From enabled that config setting, I would expect carts to automatically have their shipping / billing addresses set (if the user has any saved), and then you can also update to different addresses but still keep the primary shipping / billing addresses as they are. 

### Craft CMS version

4.1.4.1

### Craft Commerce version

4.0.4

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

We believe this was fixed in the `4.1.0` release of Commerce. Could you please try upgrading and let us know if the problem persists?

I will close this issue for now, but if you find a way to replicate it I can re-open it.

Thanks!
