### ISSUE TITLE
[3.x]: Partial paid status automatically converted to paid/complete. 

### ISSUE THREAD

**Issue by Slampaq-Solutions** [craftcms/commerce#2908]
### Description
We have built a custom module that extends the order process. After an order has been completed we export the data of this order to an external system. There was an unexpected situation in this export that caused an error, which caused a specific cart to get stuck on a partial paid and non-completed status while the order was fully paid. We can explain this behavior and solved this in our custom module.
This cart remained in this partial paid and non-completed status for exactly 28 days. After that it seems that Craft Commerce converted the cart to an order with all following actions: confirmation e-mails and our custom export.
The order was not manually completed by a user, since there was no user logged in the back-end of the website at that time.

How is it possible that this cart which was partially paid was converted to a completed order?

Purging of inactive carts is set to the standard setting of 90 days.

### Steps to reproduce

1. Fill cart with product.
2. Pay the order
3. Generate error by hooking in EVENT_BEFORE_SAVE_ELEMENT of orders.
4. Optionally change content of cart
5. Wait 28 days. We are not sure if this timespan is always the same.

### Expected behavior
Cart stays on partial paid and non-completed status.

### Actual behavior
Cart is completed and converted to an actual order with all following actions.

### Craft CMS version

3.7.44

### Craft Commerce version

3.4.15

### PHP version

7.4.30

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@Slampaq-Solutions I don't think Commerce code is causing the issue. It could be a custom module or plugin is calling an event that triggers the [markAsComplete](https://github.com/craftcms/commerce/blob/89a09ba48f1e813bd4cb17b4b822113463afa527/src/elements/Order.php#L1551) method.
