### ISSUE TITLE
Support product revisions

### ISSUE THREAD

**Issue by Tam** [craftcms/commerce#291]
The option to have revisions for products (similar to entry revisions) would be really useful, especially for larger commerce sites where multiple people can edit the products.

**Comment by RitterKnightCreative** [comment]
+1 for this.   Lots of use cases here besides the usual "oops" moments where you need to revert back.

Let's say you run specials on various products and want to edit the product descriptions to support whatever sale you're running. It's easy to go back to whatever description you had before.  Also it's helpful for testing various versions of the product landing page. 

Being able to have drafts that live alongside the current entry is also one of my absolute favorite Craft features, the fact it's not support in Commerce is really disappointing.

With entries, It's pretty easy to go back to a previous revision but products don't have that luxury. We could relate entries back to products and then pull those in that way, in fact we do that already but it's workaround regardless.

**Comment by RitterKnightCreative** [comment]
Hopefully, we'll get to see this soon, as it looks like Craft 3.2 now supports element revisions.

**Comment by lukeholder** [comment]
Draft and Revision support found here: #219
