### ISSUE TITLE
[4.1.0]: Keep getting 'unable to update cart' error

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#2914]
### Description
I've just updated to 4.1.0 and any form with the `commerce/cart/update-cart` action no longer submit. I have checked the logs and all I can see in there is the general message `Unable to update cart.` 

I had to update to the latest version to fix an issue I was having with `4.0.4` where a dependancy LitEmoji was timing out the server when adding a product to the cart - separate issue but thought I'd mention it. All `update-cart` forms were working perfectly on this version.  
 

### Craft CMS version

4.2.0.1

### Craft Commerce version

4.1.0

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@iamtompickering Can you please look at the `cart.getErrors()` and see what that returns?

**Comment by iamtompickering** [comment]
@lukeholder just done a dump of this and got the following:

```
array(2) { ["shippingAddress.locality"]=> array(1) { [0]=> string(21) "City cannot be blank." } ["shippingAddress.addressLine1"]=> array(1) { [0]=> string(31) "Address Line 1 cannot be blank." } }
```

Just to confirm, this is when I'm just trying to add a product to the cart, so prior to actually going through the checkout process.

**Comment by lukeholder** [comment]
In 4.1 [changelog](https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#changed) we mentioned that addresses are now validated on the order/cart. This was a fix that needed to be made to make address validation work in a singular way across the addressbook and order.

It looks like you have an invalid address already saved on the cart. This wouldnt occur for future carts.

If you want to remove validation on addresses across the board we made a guide: 

https://craftcms.com/knowledge-base/removing-commerce-address-validation
