### ISSUE TITLE
[4.x]: hasMatchingAddress returns false positive if fullName differs

### ISSUE THREAD

**Issue by rynpsc** [craftcms/commerce#2917]
### Description

When an Order has two address with matching address expect for the fullName, `hasMatchingAddress` returns true.

It looks like when getting the Address attributes for comparison it is looking for `givenName` and `familyName` however when calling `toArray` on the Address element it's returning the name parts as `firstName` and `lastName`.

### Steps to reproduce

1. Create two address with the same fields except for the full name and use `hasMatchingAddress`

### Expected behavior

`hasMatchingAddress` returns `false` when all but the full name matches.

### Actual behavior

`hasMatchingAddress` returns `true` when all but the full name matches.

### Craft CMS version

Craft Pro 4.1.4.1

### Craft Commerce version

4.1.0

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @rynpsc 

Thank you for bringing this to our attention. We have pushed a fix for this which will be included in the next release of Commerce.

We are also looking to add to this feature in the upcoming `4.2` release that will allow developers to specify by which attributes addresses are determined as "matching". So for example you could decide that addresses do match if everything is the same but the names are different.

Thanks!
