### ISSUE TITLE
Old posts in Database (-1 slugs)

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/commerce#292]
We've a two Product Types and some products have an `-1` at the slug end and when remove the -1 and save the entries the `-1` comes back. 

```
# Entry in backend
- Title: Lorem
- Slug: lorem-1
```

There is no post with the slug lorem. We've tried some stuff but we can't find out what's go wrong here.

![image](https://user-images.githubusercontent.com/764292/38266427-f28fca0a-3778-11e8-9cf1-65fbfc3a0626.png)

**Comment by andris-sevcenko** [comment]
That screenshot does not show that there are no `lorem` slugs - it's doing a search for `*leo*` - can you retry with `%lorem%`?

**Comment by davidhellmann** [comment]
For me it looks like as we delete the entries there is something left over in the db. But any chance to fix that on a "good way"

**Comment by andris-sevcenko** [comment]
Are you deleting the entries from the DB or using the control panel?

**Comment by davidhellmann** [comment]
Control Panel

**Comment by andris-sevcenko** [comment]
Okay. Can you send in an email to support@craftcms.com with your DB dump? This issue is probably related to #293.

**Comment by davidhellmann** [comment]
Robin figured out this:

![image](https://user-images.githubusercontent.com/764292/38269626-52e67d06-3781-11e8-9b59-d04599cce5a1.png)

```
SELECT elements.id, commerce_products.id FROM `elements` 
LEFT JOIN commerce_products on commerce_products.id = elements.id
WHERE elements.type = 'craft\\commerce\\elements\\Product'
```

I try to delete the "null's". Update this afterwards

**Comment by davidhellmann** [comment]
@andris-sevcenko this six ID's was the problem. Thanks for helping out + robin!
