### ISSUE TITLE
Getting full address from update-cart JSON response

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#2921]
### What happened?

Is it possible to get the full address details within the JSON response when updating a cart?

I can see that you can get the `shippingAddressId` and `billingAddressId`, but cannot see any way of going deeper than this and getting the array of the actual addresses?

### Craft CMS version

4.2.0.2

### Craft Commerce version

4.0.4

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
The extra shipping and billing address on update cart response will get released on 4.2.

**Comment by iamtompickering** [comment]
@pdaleramirez excellent thanks for this!
