### ISSUE TITLE
[3.x]: Coupon is applied even if no line items match

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/commerce#2925]
### Description
A coupon code can be applied to an order where it has no effect. There's no message or error as far as I can see, the code just silently does nothing.

This seems to have been an issue since [Commerce 1](https://github.com/craftcms/commerce/issues/680), I'm not sure it's been resolved in 4.

### Steps to reproduce

1. Add non-matching items to the cart
2. Add coupon

### Expected behavior

Coupon is rejected or an error is raised

### Actual behavior

Coupon is added to the cart but does nothing

### Craft & Commerce version

3 latest

**Comment by pdaleramirez** [comment]
Invalid coupons returns craft notice. You can checkout the example templates here: https://github.com/craftcms/commerce/blob/53f4e111e4fa19e4aef84a58af66b3358bca7ea5/example-templates/dist/shop/_private/layouts/index.twig#L63
