### ISSUE TITLE
[4.x]: Addresses are not being saved to the user

### ISSUE THREAD

**Issue by samueldraper** [craftcms/commerce#2926]
### Description

When logged in customer adds a new address during checkout, it only saves to the order.
Addresses are not being saved to the user.

We are using the example templates. The form uses `actionInput('commerce/cart/update-cart')`.

Does the form actually need to be separated into two forms, with one using `actionInput('users/save-address')` to first save the address and then update the cart separately?

The example templates do not suggest that is requires. Nor do the docs at https://craftcms.com/docs/commerce/4.x/addresses.html#customer-addresses because the information there suggests new addresses for logged in users are automatically to a user on checkout.

### Steps to reproduce

1. Add new address as logged in customer at /shop/checkout/addresses2. 
2. View new address in CP against the relevant order number
3. Check to see address in CP against the user (not saved)

### Expected behavior

Addresses should be saved to the user.

### Actual behavior

Addresses are not saved to the user, only to the order.

### Craft CMS version

Craft Pro 4.2.0.2

### Craft Commerce version

4.1.0

### PHP version

8.1.0

### Operating system and version

Darwin 21.6.0

### Database type and version

MySQL 5.7.34

### Image driver and version

GD 8.1.0

### Installed plugins and versions

Bulk Edit | 4.0.0-RC1
Craft Commerce | 4.1.0
Dumper | 3.0.1
Environment Label | 4.0.2
Feed Me | 5.0.4
Formie | 2.0.4
PayPal Checkout for Craft Commerce | 2.1.0.
Redactor | 3.0.2
SEOmatic | 4.0.7

**Comment by nfourtythree** [comment]
Hi @samueldraper 

As of Commerce 4 addresses on orders and addresses in a user's address book are independent. When a customer selects an address for the cart from their address book, behind the scenes the address is duplicated and assigned to the order. When an address is copied from an address book we do set the "source" so you can tell where it came from (see these [two](https://docs.craftcms.com/commerce/api/v4/craft-commerce-elements-order.html#sourcebillingaddressid) [attributes](https://docs.craftcms.com/commerce/api/v4/craft-commerce-elements-order.html#sourceshippingaddressid)).

This means that if you are creating or editing an address on a cart/order the changes are only applied to that record.

A lot of this is outlined in the [address management](https://craftcms.com/docs/commerce/4.x/upgrading.html#address-management) section of the upgrade guide in the Commerce docs.

There is a [discussion](https://github.com/craftcms/commerce/discussions/2843) related to this. There are also plenty of events within and around order element saving that you could hook into if you wish to integrate the behaviour you mentioned.

This way of handling addresses is much more in line with many other e-commerce platforms and services. For one thing, it means that when editing an address on the order you aren't (maybe unknowingly) editing an address in your address book.

Hope this helps, thanks!

**Comment by samueldraper** [comment]
Thank you @nfourtythree. For clarity... 

The docs state  "When a customer is logged in and checks out with a new address, that address is saved to their address book" at https://craftcms.com/docs/commerce/4.x/addresses.html#customer-addresses.

Is that actually incorrect?

**Comment by nfourtythree** [comment]
Hi @samueldraper 

Great spot! Thank you for alerting us to this, looks like a hangover from the `3.x` docs.

We will get this updated. Apologies if it caused any confusion.

Thanks!
