### ISSUE TITLE
SQLSTATE[23000] Integrity constraint violation… Cant save new products

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/commerce#293]
Can't save new products. 
![image](https://user-images.githubusercontent.com/764292/38266701-a30705d8-3779-11e8-88a4-76f21972689a.png)

RC 17.1
Newest Commerce

**Comment by davidhellmann** [comment]
@andris-sevcenko problem still exists. Do u need a DB here?

**Comment by andris-sevcenko** [comment]
Yeah, would be excellent, thanks!

**Comment by lukeholder** [comment]
@davidhellmann is this still an issue? Haven't seen anyone else submit it. Steps to reproduce? Can re-open if so.

**Comment by davidhellmann** [comment]
No, it’s not an issue anymore.
