### ISSUE TITLE
[4.x]: Decimal weight values not being saved

### ISSUE THREAD

**Issue by nixondesigndev** [craftcms/commerce#2935]
### Description

We have a store set up with the Weight Unit configured to use kilograms. When trying to save a weight value that has a decimal the weight is being rounded down to the nearest whole number.

We've only tested on variants.

### Steps to reproduce

1. Configure Commerce to use kilograms as its weight unit
2. Enter a product/variant weight thats a decimal

### Expected behavior

Weights are saved as entered.

### Actual behavior

Weights are being rounded down to the nearest whole number e.g. 0.6 is saved as 0, 1.2 is saved as 1.

### Craft CMS version

Craft Pro 4.2.1.1

### Craft Commerce version

4.1.0

### PHP version

8.0.21

### Database type and version

MySQL 5.7.38

### Installed plugins and versions

-

**Comment by NixonDesignGithub** [comment]
Are we able to get an update on this as it's impacting shipping rates. Is this intended behaviour?
