### ISSUE TITLE
[4.x]: Discount delivery address always sets billing address condition

### ISSUE THREAD

**Issue by vandres** [craftcms/commerce#2938]
### Description

I would like to create a discount condition depending on the shipping address of the user. The rule is set, but it always also sets it as the billing address condition

Before saving:
![Bildschirmfoto 2022-08-17 um 13 54 51](https://user-images.githubusercontent.com/1436383/185112739-75de2f58-e2ac-49ad-acc6-00d8cf9c86cb.png)

After saving:
![Bildschirmfoto 2022-08-17 um 13 55 05](https://user-images.githubusercontent.com/1436383/185112748-30b82313-5b1b-494e-8bab-ae2cb8a84bc0.png)

### Steps to reproduce

1. Create discount
2. Set shipping address condition
3. Save
4. Billing address condition is now also set

### Expected behavior

Billing address condition can be set individually

### Actual behavior

Billing address condition cannot be set individually

### Craft CMS version

4.2.1.1

### Craft Commerce version

4.1.0

### PHP version

8.1

### Operating system and version

MacOS, Debian Docker

### Database type and version

MariaDB 10.5

### Image driver and version

-

### Installed plugins and versions

```json
  "require": {
    "craftcms/cms": "^4.2.0.2",
    "craftcms/commerce": "^4.1",
    "craftcms/redactor": "^3.0",
    "firephp/firephp-core": "^0.5.3",
    "mmikkel/cp-field-inspect": "^1.4",
    "nystudio107/craft-vite": "^4.0",
    "php-http/curl-client": "^2.2",
    "spicyweb/craft-neo": "^3.2",
    "typesense/typesense-php": "^4.8",
    "vaersaagod/geomate": "^2.0",
    "verbb/expanded-singles": "^2.0",
    "verbb/field-manager": "^3.0",
    "verbb/tablemaker": "^4.0",
    "verbb/wishlist": "^2.0",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "roave/security-advisories": "dev-master",
    "deployer/deployer": "^7.0",
    "yiisoft/yii2-shell": "^2.0.3"
  },
```

**Comment by lukeholder** [comment]
Thanks for reporting, this has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#09f205bfa7d0c9c7dae3c5c1ed3e315a75d41e5e as 4.1.0",
  "...": "..."
}
```

Then run `composer update`.
