### ISSUE TITLE
[3.x]: Custom Shipping Method auto-applies to the order when wanting it simply available as option

### ISSUE THREAD

**Issue by moldedjelly** [craftcms/commerce#2942]
### Description
I'm wanting to create a shipping method that is able to dynamically calculate the cost of shipping based off the order total plus a percentage of the order total. I've managed to get the Shipping Method class setup and working, but I've found that I need to have enabled returning true and matchOrder returning true on the shipping rule, otherwise the shipping method is not available as an option on the order at all, but when both are true, the shipping method is selected automatically and applied to the order.

### Steps to reproduce
Use the instructions in the docs to create a custom shipping method with rule.
https://craftcms.com/docs/commerce/3.x/extend/shipping-methods.html

### Expected behavior
I'd expected the selected shipping method on the order to be empty when creating the order, and then I'd have to select the shipping method from the available shipping methods

### Actual behavior
It seems to apply the custom shipping method as the selected method automatically even if there are other cheaper options available

### Craft CMS version

3.7.42

### Craft Commerce version

3.4.14

### PHP version

7.3.33

### Operating system and version

Linux 5.10.47-linuxkit

### Database type and version

MySQL 5.5.5

### Image driver and version

Imagick 3.4.3 (ImageMagick 6.9.11-60)

**Comment by lukeholder** [comment]
Sounds like you have `autoSetCartShippingMethodOption` setting set to true which sets the cart with the first available shipping method option. Let me know if this is not the case.

**Comment by moldedjelly** [comment]
I don't have autoSetCartShippingMethodOption in my commerce.php config file, so am assuming it's using the default "false". It's strange, because without the custom shipping method loaded up, it's works as expected - ie. there are other shipping methods available that have been setup through the admin like "Pickup" and "Free Shipping" and they are available to select, but none of those are automatically applied to the order as the selected shipping method

**Comment by moldedjelly** [comment]
Hi Luke, 
I'm so sorry, 
I've just tested this again, and it has worked as expected - not auto-applying the custom shipping method to the order.
I really don't know why it has worked suddenly. I am developing within docker, so can only guess that some sort of cache was not updating as I was testing things out before.
