### ISSUE TITLE
[3.x]: EVENT_AFTER_PROCESS_PAYMENT called before payment made (redirect) but not after

### ISSUE THREAD

**Issue by anchovy** [craftcms/commerce#2945]
### Steps to reproduce

1. add an event watcher for EVENT_AFTER_PROCESS_PAYMENT
```
         Event::on(
             Payments::class,
             Payments::EVENT_AFTER_PROCESS_PAYMENT,
             function(ProcessPaymentEvent $event) {

                 // @var Transaction $transaction
                 $order = $event->order;
                 $form = $event->form;
                 $transaction = $event->transaction;
                 $response = $event->response;

                Craft::trace('EVENT_AFTER_PROCESS_PAYMENT Called - $transaction->status = '. $transaction->status);
```
2. Complete an order

### Expected behavior
1. I'd see 2x logs entires:
```
2022-08-24 18:20:16 [-][19][-][trace][application] EVENT_AFTER_PROCESS_PAYMENT Callled - $transaction->status = redirect
2022-08-24 18:21:16 [-][19][-][trace][application] EVENT_AFTER_PROCESS_PAYMENT Callled - $transaction->status = success
```

### Actual behavior
1. Only see the one log entry:
```
2022-08-24 18:20:16 [-][19][-][trace][application] EVENT_AFTER_PROCESS_PAYMENT Callled - $transaction->status = redirect
```

### Craft CMS version

Craft Pro 3.7.51

### Craft Commerce version

3.4.16

### PHP version

8.1.0

### Operating system and version

Mac Monterey

### Database type and version

MySQL 8.0.27

### Image driver and version

Imagick 3.5.1 (ImageMagick 6.9.6-2)

### Installed plugins and versions

Amazon S3	1.3.0
Asset Usage	2.3.1
AsyncQueue	2.3.0
Child Me!	1.3.1
Colour Swatches	1.7.0
Control Panel Nav	3.0.17
CP Field Inspect	1.4.4
Craft Commerce	3.4.16
Embedded Assets	2.11.3
Enupal Snapshot	1.2.9
Events	1.4.21
Feed Me	4.5.3
Field Manager	2.2.5
Forms (Freeform)	3.13.18
Imgix	2.1.0
LJ Dynamic Fields	3.0.12
Logs	3.0.5
Navigation	1.4.28
Payment Express for Craft Commerce 2	1.5.0
PDF Transform	1.0.7
Phone Number	1.5.0
Retour	3.1.73
SendGrid	1.3.1
SEOmatic	3.4.37
Smith	1.2.3
Sprig	1.13.0
Super Table	2.7.2
Table Maker	3.0.4
Template Select	2.0.2
Twigpack	1.2.17
Typed link field	1.0.25
User Group Field	2.0.2
Vizy	1.0.18
Width Fieldtype	1.1.0

**Comment by lukeholder** [comment]
You should only see the one process payment call. Are you possibly looking for `EVENT_AFTER_COMPLETE_PAYMENT` to know when the redirect has returned and is successful?
