### ISSUE TITLE
[4.x]: Manage/Cancel subscription and Payment history panes are hidden in the subscription details page

### ISSUE THREAD

**Issue by martyspain** [craftcms/commerce#2948]
### Description

When clicking on a Subscription from Commerce > Subscriptions, the page renders with an empty content panel. The markup shows that the 'tab--subscriptionManageTab' element has a class of `hidden` applied to it, though I can't work out why. Removing this class reveals the content, but I don't think it should be hidden in the first place.

<img width="1509" alt="Screenshot 2022-08-24 at 14 39 02" src="https://user-images.githubusercontent.com/39329902/186433968-de9f80c7-68b2-4970-977d-b2ba3b3ffe1f.png">

<img width="665" alt="Screenshot 2022-08-24 at 14 41 48" src="https://user-images.githubusercontent.com/39329902/186434011-b45e0718-b252-4c78-a779-389423cd1a24.png">

### Steps to reproduce

1. In a Commerce install with subscriptions (using the Stripe for Commerce plugin), go to Commerce > Subscriptions and click the title of a subscription to view/edit the subscription details. 
2. The page loads with an empty content pane.

### Expected behavior

The subscription details page should show the 'Manage subscription', 'Cancel subscription' and 'Payment history' panels in the content pane.

### Actual behavior

The content pane appears empty, though the content is in the markup but hidden via a CSS class.

### Craft CMS version

4.2.1.1

### Craft Commerce version

4.1.0

### PHP version

8.0

### Installed plugins and versions

- Stripe for Craft Commerce 3.0.1

**Comment by lukeholder** [comment]
This has been fixed in https://github.com/craftcms/commerce/issues/2913

This next release will be out within the next 12 hours. Thanks.
