### ISSUE TITLE
[4.x]: Search for orders related to specific product broken in CP

### ISSUE THREAD

**Issue by peterurban** [craftcms/commerce#2951]
### Description
When filtering for related products in the Orders list. No results are given even though the given product is present in multiple orders. The same happens when trying to do the same with Variants.

### Steps to reproduce

1. Click filtering in the Orders list search field
2. Select _Related to_ and _Product_ 
3. Choose a product

### Expected behavior
Show orders related to that product

### Actual behavior
Shows no result even though the product is present in multiple orders

### Craft CMS version

4.4.2

### Craft Commerce version

4.1.0

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@peterurban Are you using a custom field on the order to relate the order to a product?

If you are talking about the product existing on the line item, that is not a standard order/product relationship that that filter rule uses.

We would need to add that as a feature. So I have added it to our list.

 In the meantime you can search for products with the standard search.

**Comment by peterurban** [comment]
I meant the latter. 

Makes sense. It would be nice to have a feature like that in the future, though. 

For now, just searching for the product will do! Thank you for clearing that up!
