### ISSUE TITLE
[4.x]: fullName field not available when creating orders manually

### ISSUE THREAD

**Issue by peterurban** [craftcms/commerce#2961]
### Description
My client occasionally needs to create orders manually from the CP. However, they cannot edit the fullName field of billing and shipping addresses when creating these.

Any way to show this field in the address overlay?

### Craft CMS version

4.2.3

### Craft Commerce version

4.1.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @peterurban 

Can you check if you have added the full name field to the address field layout? This can be done in the control panel under Settings > Users > Address Fields.

Thanks.

**Comment by peterurban** [comment]
Wow, how did I miss that? Solved the problem.
Thank you!
