### ISSUE TITLE
[4.x]: Can't add new lineitem in cp if the purchasable has a min amount set

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#2962]
### What happened?

If a purchasable has minimum allowedQty set, then when trying to add it via a cp order (add new lineitem) it returns an error.

A generic "couldn't recalculate order" is seen in the ui, but viewing the request shows that the actual error is because the default qty of 1 (when adding via the cp) is less than the minimum qty.

### Steps to reproduce

1. create a purchasable with the minimum allowedQty set to greater than 1.
2. Try to add that purchasable in a cp order.

### Expected behavior

I would expect it to add the purchasable with the minimum allowedQty set as the lineitem qty

### Actual behavior

errors.

### Craft CMS version

4.2.3

### Craft Commerce version

4.1.1

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
This should be fixed in a recent release. Due to the qty field on the add to cart form in the order edit page:

<img width="694" alt="CleanShot 2022-12-06 at 09 28 05@2x" src="https://user-images.githubusercontent.com/133571/205785754-d886c074-5ecd-4549-9e24-e0bfc8876b9e.png">
