### ISSUE TITLE
[4.x]: Failing to add default addresses to new cp order

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#2963]
### Description
When a new cp order is created and a customer is selected, their default billing & shipping addresses are not set to the order.

### Steps to reproduce

1. create a customer with default billing & shipping addresses
2. create a new cp order and select that customer

### Expected behavior
the default billing & shipping addresses are copied to the order (cart)

### Actual behavior
no addresses are set

### Craft CMS version

4.2.3

### Craft Commerce version

4.1.1

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
I can confirm this issue. This has stopped working on Commerce 4. We'll be looking into this.

**Comment by nfourtythree** [comment]
Hi @samuelbirch 

Thank you for bringing the issue to our attention. We have pushed a fix for this which will be included in the next release of Commerce.

Thanks!
