### ISSUE TITLE
[3.x]: Product query by type returns all products if type doesn't exist

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/commerce#2966]
### Description
Trying to use query params to filter down a product query. If the type used in the query param doesn't exist as a product type then the product query returns all products

### Steps to reproduce

1. Create product query
2. Set the query to look for a product type that doesn't exist
3. Results return all products

### Expected behavior
Would hope/think that querying for products under a type that doesn't exist would return 0 products

### Actual behavior
Returns all products

### Craft CMS version

3.7.52

### Craft Commerce version

3.4.16

### PHP version

7.4

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @jamiematrix 

Thank you for bringing this to our attention. We have just pushed a fix which will be included in the next release of Commerce `3.x`.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "v3.x-dev#8fa5c6ec15d81b75424ebde044ecf663dab20fc1 as 3.4.17.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
