### ISSUE TITLE
[4.x]: 

### ISSUE THREAD

**Issue by tibedaniel** [craftcms/commerce#2969]
### Description

Cart variables billingSameAsShipping and shippingSameAsBilling are not updated in  in Twig.

### Steps to reproduce

- Standard form method=post
- address fields
- {{ actionInput('commerce/cart/update-cart') }}
- input type="checkbox" name="shippingAddressSameAsBilling" value="1"

### Expected behavior

Twig variabel craft.shippingSameAsBilling = true

### Actual behavior

Twig variabel craft.shippingSameAsBilling always false

I debugged the process and can confirm that CartController::_returnCart and Controller::asModelSuccess are saving the new value (shippingSameAsBilling=true) but the twig variable is always false

### Craft CMS version

4.x

### Craft Commerce version

4.1.1

### PHP version

8.1

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Those are flags used purely for the current update cart request. If you want to know if the addresses are the same, you can use `cart.hasMatchingAddresses()`
