### ISSUE TITLE
[3.x]: 

### ISSUE THREAD

**Issue by NaveenNCES** [craftcms/commerce#2974]
### Description
I need to get applied e-gift voucher name. But I am not able to find anything on graphql related to gift vouchers.

### Steps to reproduce

1. I am using gift vouchers in my website.

### Expected behavior
By using graphql I am able to get gift vouchers name applied to the cart products.

### Actual behavior
I am not able to get anything related to gift vouchers in graphql

### Craft CMS version

3.7.50

### Craft Commerce version

3.4.17.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
HI @NaveenNCES 

Are you using a plugin for gift vouchers?

Thanks

**Comment by nfourtythree** [comment]
Hi @NaveenNCES 

The Gift Voucher plugin is created by a third party. 

To get help and assistance with the plugin it would be best to post your issue on the plugin's repository.

You can find that here: https://github.com/verbb/gift-voucher/issues

Hope this helps, thanks!
