### ISSUE TITLE
[4.x]: Sales not applying to products

### ISSUE THREAD

**Issue by robzor** [craftcms/commerce#2976]
### Description
If i click 'Add to Sale' in a variant or 'Add all to sales' in the right hand sidebar and select any variants, they are not being applied to the sale. In the console I can see this:

![CleanShot 2022-09-20 at 4 00 04](https://user-images.githubusercontent.com/704032/191293197-0f2b4f0b-9f56-4f9b-9cc4-a498d239de20.png)

The response is `[]`

Shortly afterwards (no user action just with the product page open) there is an XHR request:

![CleanShot 2022-09-20 at 4 00 45](https://user-images.githubusercontent.com/704032/191293418-0df1fe81-82e9-4f2f-bad2-2a97b4d801e4.png)

With a response of `{"sales":[]}`

I am running the site locally via Laravel Valet on OSX. 

Is there a good way I can expose the log for this, as I am getting a 'Added to sale' confirmation toast message but obviously it's not working?

### Steps to reproduce

1. Create a sale
2. Add a variant to the sale

### Expected behavior

Variant is added to sale

### Actual behavior

Variant is not added to sale

### Craft CMS version

4.2.4

### Craft Commerce version

4.1.2

### PHP version

8.0.17

### Operating system and version

Mac OSX Catalina 10.15.7

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @robzor 

Thank you for bringing this to our attention. We have just pushed up a fix for the issue which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#700229aeac88abd6edc2ac3111a6b3f12ac7b917 as 4.1.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks

**Comment by robzor** [comment]
Thanks, I'll give this a go :)

**Comment by stefanfriedrich** [comment]
@nfourtythree bug seems to be back, I have the same problem with craft 4.3.10 and commerce 4.2.5.1.
In sales I can add the variant, but variant onSale is false.

**Comment by lukeholder** [comment]
See my question on #3097 please @stefanfriedrich thanks.
