### ISSUE TITLE
[4.x]: Installation Commerce fails in freshly setup CraftCMS

### ISSUE THREAD

**Issue by thomasgoemaere** [craftcms/commerce#2979]
Hey,

I'm trying to install the package into a fresh new CraftCMS 4 install but i'm getting dependency issues.

<img width="1790" alt="Schermafbeelding 2022-09-23 om 11 08 31" src="https://user-images.githubusercontent.com/1284055/191928795-2c0640a0-82bf-40c9-9e0c-80d2f0806f5b.png">

It seems that Commerce requires **psr/simple-cache** version ^1.0 but CraftCMS already installed version 3.0.0 (required by illuminate/contracts which comes with craftcms/cms).

When installing version 1.x of simple-cache Commerce can be installed without any problem. But that doesn't seem to be the correct way? Or am I missing something?

Thanks in advance,

Kind regards
Thomas

### Craft CMS version

4.2.5.1

### Craft Commerce version

4.x

### PHP version

8.0.23

### Operating system and version

macOS Monterey 12.5.1

### Database type and version

MySQL 14.14

**Comment by nfourtythree** [comment]
Hi @thomasgoemaere & @icreatestuff 

I have just managed to replicate this issue.

For the moment you can delete your project's `composer.lock` and then run `composer require craftcms/commerce` this should get you up and running.

We understand this isn't the most ideal process right now and we will look into what we can do about it.

Thanks

**Comment by nfourtythree** [comment]
This has been updated in the Commerce docs installation instructions.
