### ISSUE TITLE
[4.x]: Unable to restore a trashed product

### ISSUE THREAD

**Issue by billmn** [craftcms/commerce#2982]
### Description
When I try to restore a trashed product from CP I receive this error:
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'deletedWithProduct' cannot be null The SQL being executed was: UPDATE `commerce_variants` SET `deletedWithProduct`=NULL, `dateUpdated`='2022-09-27 15:19:00' WHERE `id`=1223
```

### Steps to reproduce

1. Delete a product
2. Try to restore it

### Craft CMS version

4.2.5.1

### Craft Commerce version

4.1.2

### PHP version

8.1.8

### Operating system and version

Mac OS 12.6

### Database type and version

MariaDB 15.1

### Installed plugins and versions

Abandoned Cart for Craft Commerce 	2.0.1
Contact Form 	3.0.0
Contact Form Honeypot 	2.0.0
Craft Commerce 	4.1.2
Feed Me 	5.0.4
Mix 	1.6.0
PayPal Checkout for Craft Commerce 	2.1.1
Redactor 	3.0.2
SEOMate 	2.0.3
Sprig 	2.1.0
Stripe for Craft Commerce 	3.0.1
Super Table 	3.0.1
Table Maker 	4.0.3
Typed link field 	2.1.4
Wishlist 	2.0.2

**Comment by lukeholder** [comment]
Thanks, this has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#375fd16cc1f00a85f1aea90ee5e87413f78c660c as 4.1.2",
  "...": "..."
}
```

Then run `composer update`.
