### ISSUE TITLE
[4.x]: Order Confirmation PDF - Allow "special" characters

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#2987]
### Description
Someone checked out with a name that contained a letter like this "ł" and it shows a ? in the PDF order confirmation.

Would love that it was possible to output that character in the PDF instead of ? - Looks bad and its not a nice feeling for the customer thinking that their name is "weird".

The system is set up with GB language.

### Craft CMS version

4.2.5.1

### Craft Commerce version

4.1.2

### Database type and version

12.12

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@philipboomy 

See these link: https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding

and maybe this: https://stackoverflow.com/a/29523300

This means you should be able to get it working with:

```html
<head>
  <meta http-equiv="Content-Type" content="charset=utf-8" />
  <style type="text/css">
      body { font-family: DejaVu Sans; }
  </style>
</head>
```
