### ISSUE TITLE
[4.x]: Template path column blank from System Settings > Emails

### ISSUE THREAD

**Issue by robzor** [craftcms/commerce#3000]
### Description
Very minor but on the Emails Table in Commerce settings, the "Template path" column is missing

### Steps to reproduce

1. Go to Commerce > System Settings > Emails

### Expected behavior
For there to be content in the "Template path" column

### Actual behavior
No content in the "Template path" column

![CleanShot 2022-10-17 at 5 25 44](https://user-images.githubusercontent.com/704032/196231522-2bab15ac-42a2-4891-a113-5e6fa9ab4a3b.png)

### Craft CMS version

4.2.7

### Craft Commerce version

4.1.3

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @robzor 

Thank you for bringing this to our attention. 

We have just pushed a fix for this which will be included in the next release of Commerce.

Thanks!
