### ISSUE TITLE
[3.x] [4.x]: A Discount's Minimum Purchase Qty uses all items (not just matching items) as a part of the condition logic

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3004]
### Description
When setting the Minimum Purchase Quantity for a discount condition, it appears to count all items, not just matching items, when determining if the minimum qty of items required, for the discount to be applied, has been met.

Seeing the same behaviour in both 3.x and 4.x

### Steps to reproduce

1. Create discount, no code, all purchasables, all categories, 20% off line items, and minimum purchase qty set to 2.
2. Add 2 items to the cart, one with the promotable toggle on, one off.
3. Discount gets applied, to the promotable item

### Expected behavior
I would expect the discount to only be applied if 2 or more promotable items are added to the cart

### Actual behavior
See steps to reproduce above

NB - Tested and recreated on the demo Spoke & chain site.

### Craft CMS version

3.7.55.3 / 4.2.7

### Craft Commerce version

3.4.17.2 / 4.1.3

### PHP version

7.4 / 8.0.24

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@samhibberd I am not sure this is a bug. We'll discuss this with the team.

**Comment by samhibberd** [comment]
@pdaleramirez have you had a chance to discuss this with the team yet? Looking over the docs for both version 3 and 4, it suggests that the promotable setting must be switched on for sales and discounts to be applied, as I understood this to infer that only promotable items would be included in any logic. 

https://craftcms.com/docs/commerce/4.x/sales.html#conditions

It could make sense that the promotable setting does not get taken into account when the matching items logic is run, but a matching item which is not promotable will never be able to have a discount or sale applied to it. Perhaps why I assumed they would not be included in the matching items result 🤔

**Comment by pdaleramirez** [comment]
@samhibberd Yes, this is the current expected behavior but we'll improve the docs cause it could be confusing.
