### ISSUE TITLE
[4.x]: Unpaid orders are being returned when using .isPaid()

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#3007]
### What happened?

Seems that this example take from the docs are returning unpaid orders/carts unless I am mistaken.

{% set orders = craft.orders()
  .isPaid()
  .all() %}

### Craft CMS version

4.2.8

### Craft Commerce version

4.1.3

### PHP version

8.0

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
In Commerce 4 `craft.orders()` returns all orders and carts and not just completed orders. You should use:

{% set orders = craft.orders()
.isCompleted()
.isPaid()
.all() %}
