### ISSUE TITLE
Payment Currencies

### ISSUE THREAD

**Issue by stovepot** [craftcms/commerce#301]
### Description

Commerce Settings: Payment Currencies

Error: `PHP Notice – yii\base\ErrorException`

`Trying to get property of non-object`

### Steps to reproduce

1. Choose Payment Currencies in Settings
2. Click + New Currency Button

### Additional info

- Craft version:3.0.1
- PHP version: 7.1
- Database driver & version: MSQL
- Plugins & versions: Craft Commerce: 2.0.0-beta.1.1

**Comment by lukeholder** [comment]
Can you please post your log folder (zip) to support@craftcommerce.com and reference this issue number.

**Comment by lukeholder** [comment]
We are pretty sure this is a bad upgrade from Craft 2 and Commerce 1.

If you’re upgrading to Commerce 2 and are having issues - Commerce assumed it would be updated from the latest 1.x release (1.2.1360), which obviously wasn’t the case in some scenarios. If you’re having issues updating Commerce 1 to Commerce 2, the recommended course of action is migrating up again from Craft 2 to Craft 3 and from Commerce 1 to Commerce 2, ensuring you have the latest Commerce 2 version from the plugin store (2.0.0-beta.1.2)
