### ISSUE TITLE
[4.x]: Slide out panel has 2 'Enabled' buttons and only one of them works.

### ISSUE THREAD

**Issue by robzor** [craftcms/commerce#3010]
### Description
If you are in an entry with a Commerce Products field, and double click the Product to open the slide out panel, you see 2 different 'Enabled' switches on the far right, one at the top, and one at the bottom under a heading of 'Status'.

If you click the top one, it does not disable the entry. If you click the bottom one, it does. 

![CleanShot 2022-10-25 at 10 38 57](https://user-images.githubusercontent.com/704032/197741065-6cf00feb-bb8c-41e9-8e97-d89571012e87.png)

For the time being we have told our client to use the bottom Enabled slider.

### Steps to reproduce

1. In an entry that has a Commerce Products field, add a product entry.
2. Double click the product entry to open the slide out panel.

### Expected behavior

There to be only 1 'Enabled' status switcher and for it to work.

### Actual behavior

2 'Enabled' toggles appear, the top one does not disable the entry. The bottom toggle does disable the entry.

### Craft CMS version

4.2.8

### Craft Commerce version

4.1.3

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Fixed for the next release. Thanks.

**Comment by robzor** [comment]
Thank you!
