### ISSUE TITLE
[4.x]: User is not permitted to delete this address

### ISSUE THREAD

**Issue by shifuma** [craftcms/commerce#3011]
### Description
I'm getting 'User is not permitted to delete this address' when trying to delete an address belonging to my own user (full admin)

### Steps to reproduce

1. Use the example code from [Listing Address](https://craftcms.com/docs/4.x/addresses.html#listing-addresses)
2. Click 'Delete' in the browser
3. See error

Also tested with the Commerce example templates on a fresh install and get the same error.

### Expected behavior
A user can delete their own address

### Actual behavior
Permission error: User is not permitted to delete this address

### Craft CMS version

4.3.0

### Craft Commerce version

4.1.3

### PHP version

8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! This ended up being a Craft CMS bug, and we’ve fixed it for the next release.

**Comment by brandonkelly** [comment]
Craft 4.3.1 is out with the fix for this.
