### ISSUE TITLE
[4.x]: Create a product applies wrong (default) tax category

### ISSUE THREAD

**Issue by tmjoen** [craftcms/commerce#3013]
### Description

When creating a new product, it will not preselect the tax category I have marked as default. It will preselect the tax category NOT marked as default. If I flip the default between the two categories, the preselected tax category flips as well. Always to the one not marked as default

### Steps to reproduce

https://user-images.githubusercontent.com/10501945/198102224-53025bed-3475-46f6-bf93-a1dde6327c58.mp4

### Expected behavior

The tax category marked as default should be applied when creating a new product

### Actual behavior

The tax category NOT marked as default is applied when creating a new product

### Craft CMS version

4.3.0

### Craft Commerce version

4.1.2

### PHP version

8.1.11

### Operating system and version

Darwin 21.4.0

### Database type and version

PostgreSQL 13

### Installed plugins and versions

Blitz Recommendations	2.1.1
Contact Form	3.0.0
Craft Commerce	4.1.2
Imager X	4.1.7
Mailgun	3.0.0
MatrixMate	2.1.1
Redactor	3.0.2
SEOMate	2.0.3
Social	3.0.0-beta.1
Stripe for Craft Commerce	3.0.1
Super Table	3.0.3
Typed link field	2.1.4
Vite	4.0.3

**Comment by pdaleramirez** [comment]
@tmjoen There is an existing bug when validating a tax category. Would you be able to test this branch `bugfix/tax-category-failure` in this PR https://github.com/craftcms/commerce/pull/3017/files

To see if that resolves your issue

**Comment by tmjoen** [comment]
Hi @pdaleramirez — sorry for the delay. I updated to 4.2.1 and the problem is still there:


https://user-images.githubusercontent.com/10501945/199693907-d9dce980-604e-4ff1-b83a-d46c98729691.mp4

**Comment by tmjoen** [comment]
Oh sorry I thought this was the merged fix for 4.2.1 `Fixed an error that occurred when viewing tax categories.`. 
I can't see how your branch would fix this though, since I can save the category just fine and it says it's the default, it just isn't applied(?). But I can give it a try! Would you know how to reference a git branch in my composer.json when the branch has an "/"? It just fails for me with: 
"craftcms/commerce": "bugfix/tax-category-failure as 4.2.1"`

**Comment by pdaleramirez** [comment]
@tmjoen Try this dependency `dev-bugfix/tax-category-failure as 4.2.1`

**Comment by tmjoen** [comment]
Thanks @pdaleramirez — that dependency installed nicely. The error persists, though — no change unfortunately!

**Comment by pdaleramirez** [comment]
@tmjoen Would you be able to send your database and composer.json with composer.lock files in `support@craftcms.com`? We'll debug further.

**Comment by tmjoen** [comment]
@pdaleramirez Sure — the files are sent now. Thanks for taking a look!
