### ISSUE TITLE
[4.x]: "clearLineItems" param only clears session data

### ISSUE THREAD

**Issue by bjerringgaard** [craftcms/commerce#3014]
### Description
When adding the same item to cart twice with the "ClearLineItems" parameter, the cart is not correctly reset, and the qty still goes up.
Adding a diffrent item, clears the cart and adds on the newly added item to the cart.

### Steps to reproduce
1. Add purchasable to cart with the /update-cart function with the parameter "ClearLineItems" set to true.
2. Add the same item once again, the qty will go up. 
3. Add diffrent item, the cart will be cleared, and onlt 1 unit of the new item wil be added

### Expected behavior
Completely clear the cart and adding the selected item to the cart with qty 1, adding the same item again, should have no effect (Should clear and re add the item)

### Actual behavior
If the same item is added twice, the Quantity goes up, adding a diffrent item, works as expected.

### Craft CMS version

4.2.7

### Craft Commerce version

4.1.3

### PHP version

8.0.20

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
I can confirm this bug. The behavior of adding a product to the cart with clearLineItems adds up qty on same item instead of clearing the cart. We'll give more feedback soon.

**Comment by lukeholder** [comment]
@bjerringgaard This has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#51569ad047ed4f4c046868173f2e308c83d9059a as 4.2.1",
  "...": "..."
}
```
