### ISSUE TITLE
[3.x]: CP notices don't show when set by custom module

### ISSUE THREAD

**Issue by modelesque** [craftcms/commerce#3018]
### Description
I want to show a success (or fail) message in the CP edit order page. When I set one in an `Order::EVENT_BEFORE_SAVE` using this code:

```
Craft::$app->getSession()->setNotice('Test notice');
```
...nothing shows.

### Steps to reproduce

1. Add `Craft::$app->getSession()->setNotice('Test notice');` in a before-save event.
2. Update an order.

### Expected behavior

I expect to see a blue flash message at the top of the CP edit order page like it works elsewhere in the CP.

### Actual behavior

No flash message shows at all.

### Craft CMS version

3.7.58

### Craft Commerce version

3.4.17.2

### PHP version

7.4.26

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.31

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@modelesque I've tested the issue with the CMS and Commerce version provided and I can't seem to replicate it. Could you send the code in here? Let's see what's going on.

**Comment by pdaleramirez** [comment]
I was able to replicate this issue. We'll give update soon.

**Comment by pdaleramirez** [comment]
I don't this is a bug because Craft CMS 3 doesn't show the notice as well. This enhancement is already on Craft and Commerce 4
