### ISSUE TITLE
[3.x]: orderSiteId and orderSite always return the primary site

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/commerce#3023]
I'm finding that `orderSiteId` and `orderSite` always return the primary site. 
Using siteId from a purchasable returns the correct site.

```php
Event::on(
  Order::class,
  Order::EVENT_AFTER_COMPLETE_ORDER,
  function (Event $event) {
      
    $order  = $event->sender;

    // Always returns Primary site id
    $siteId = $order->orderSiteId; 
    // Always returns Primary site
    $siteEl = $order->orderSite;
    // Always returns correct site id
    // $siteId = $order->lineItems[0]->purchasable->siteId; 

    if ($siteId === 1) 
    {
      $order->orderStatusId = 1; // Processing Site 1
      $message = "Status set to Processing Site 1";
      $order->message = $message;
    }

    if ($siteId === 2) 
    {
      $order->orderStatusId = 2; // Processing Site 2
      $message = "Status set to Processing Site 2";
      $order->message = $message;
    }

    Craft::$app->getElements()->saveElement($order, false);
  }
);
```

In this case if the primary site is 1 then the status will always be set to 1 and if the primary site is 2 then the status will always be 2.

This is Commerce 3.4.18

If this due to incomplete multi-site support, it would be good if the docs could just be updated. 

_Originally posted by @pixelmachine in https://github.com/craftcms/commerce/issues/1327#issuecomment-1303995509_

**Comment by pdaleramirez** [comment]
@pixelmachine I test this issue and it is working as expected. To get the correct `orderSiteId` you need to do a cart checkout with the site's Base URL. Can you confirm that you are checking out the cart with the expected Site's Base URL?

**Comment by pixelmachine** [comment]
@pdaleramirez well annoyingly this is actually working for me today, not sure what changed, I'll need to test some more. Interestingly using the `$order->lineItems[0]->purchasable->siteId` stopped working, so something odd is happening. I will test more asap.

Not really sure what you mean by "you need to do a cart checkout with the site's Base URL".

```php
Event::on(
    Order::class,
    Order::EVENT_AFTER_COMPLETE_ORDER,
    function (Event $event) {
        
      $order = $event->sender;
      $siteId = $order->orderSiteId;

      if ($siteId === 1) {
        $status = Plugin::getInstance()->getOrderStatuses()->getOrderStatusByHandle('processingSiteOne');
        $order->orderStatusId = $status->id;
        $message = "Site: ".$siteId." Order set to Site 1 Processing";
        $order->message = $message;
      }

      if ($siteId === 4) {
        $status = Plugin::getInstance()->getOrderStatuses()->getOrderStatusByHandle('processingSiteTwo');
        $order->orderStatusId = $status->id;
        $message = "Site: ".$siteId." Order set to Site 2 Processing";
        $order->message = $message;
      }

      Craft::$app->getElements()->saveElement($order, false);
    }
);
```

**Comment by pdaleramirez** [comment]
@pixelmachine In the Control Panel -> Settings -> Sites -> Your Site: You'll see the Base Url. The orderSiteId would depend on where you checkout the cart on a site's baseUrl.
