### ISSUE TITLE
[4.x]: Currency of LineItems and Adjustments in Admin Cart are always default

### ISSUE THREAD

**Issue by segidev** [craftcms/commerce#3024]
### Description

The currency that is displayed in the Cart/Order in the Admin always displays the default currency **not the Cart/Order currency**

### Steps to reproduce

1. Add two currencies CHF and EUR where CHF is default
2. Add some items into the cart
3. Set the currency of the cart itself to EUR (via Code)
4. DIsplay the cart in the admin

### Expected behavior

![image](https://user-images.githubusercontent.com/28906187/201008137-e6d16216-4212-40dd-b2c8-6922bfb1d971.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/28906187/201008264-1ce019eb-f3b7-46f3-8ced-a604dd1ed942.png)

### Solution?

As once discussed [here](https://github.com/craftcms/commerce/pull/1946) you have changes this line in `src/models/LineItem.php` from
```php
public function behaviors(): array
{
    $behaviors = parent::behaviors();

    $behaviors['currencyAttributes'] = [
        'class' => CurrencyAttributeBehavior::class,
        'defaultCurrency' => Plugin::getInstance()->getPaymentCurrencies()->getPrimaryPaymentCurrencyIso(),
        'currencyAttributes' => $this->currencyAttributes(),
    ];

    return $behaviors;
}
```
to
```php
public function behaviors(): array
{
    $behaviors = parent::behaviors();

    $behaviors['currencyAttributes'] = [
        'class' => CurrencyAttributeBehavior::class,
        'defaultCurrency' => $this->getOrder()->currency ?? Plugin::getInstance()->getPaymentCurrencies()->getPrimaryPaymentCurrencyIso(),
        'currencyAttributes' => $this->currencyAttributes(),
    ];

    return $behaviors;
}
```

additionally the `src/models/OrderAdjustment.php` file also requires the same adjustment.

### Craft CMS version

Craft Pro 4.2.5.2

### Craft Commerce version

4.1.2

### PHP version

8.1.11

### Operating system and version

Ubuntu 22.04

### Database type and version

Postgres 14

**Comment by segidev** [comment]
Additionally adding or trying to overwrite the behavior does not work.

I can do this:
```php
Event::on(LineItem::class, Model::EVENT_DEFINE_BEHAVIORS, function(DefineBehaviorsEvent $event) {
    /** @var LineItem $lineItem */
    $lineItem = $event->sender;
    $event->behaviors['currencyAttributes'] = [
        'class' => CurrencyAttributeBehavior::class,
        'defaultCurrency' => $lineItem->getOrder()->currency ?? Commerce::getInstance()->getPaymentCurrencies()->getPrimaryPaymentCurrencyIso(),
        'currencyAttributes' => $lineItem->currencyAttributes(),
    ];
});
```

but this function in `src/models/LineItem.php` overwrites it again or is the last behavior in list always overwriting the previous behavior:
```php
/**
 * @inheritDoc
 */
public function behaviors(): array
{
    $behaviors = parent::behaviors();

    $behaviors['currencyAttributes'] = [
        'class' => CurrencyAttributeBehavior::class,
        'defaultCurrency' => Plugin::getInstance()->getPaymentCurrencies()->getPrimaryPaymentCurrencyIso(),
        'currencyAttributes' => $this->currencyAttributes(),
    ];

    var_dump($behaviors);
    die();

    return $behaviors;
}
```

**Comment by lukeholder** [comment]
Hi @segidev 

Commerce does not have multi-currency support. The order is only ever in the base currency which we store in `order.currency`. The attribute that can be changed is the customers chosen 'order.paymentCurrency'.

This is the same through the whole system, the discount amount of `$3` will take `3.0` off the price and does not care about currency, thus the whole system is expected to be in the one currency.

We are adding multi-currency support when we add multi-store functionality in 5.0

We don't recommend trying to change the `order.currency` attributes.

Commerce has a multi-currency (`paymentCurrency`) payment options, with the ability to have a conversion ratio for the price paid, but all orders should still be in the single currency. So looking at the order edit CP, you should only see orders in the base currency, with the transaction tab showing the payment conversions for the paymentCurrecny.

**Comment by segidev** [comment]
Hi @lukeholder 

Thanks for letting me know. See that is one case but there is another case like ours where the customer wants to explicitly define prices for different countries that use **the same** currency.

So each product does not have a `price` but a variant with `priceCH`, `priceDE` and `priceAT` where
- `priceCH` is CHF
- `priceDE` and `priceAT` is EUR

So the convertion does not work this way or is too limited.

Multi currency support would be a great addition for this. The workaround that i do seems to work flawlessly.

Why would you not recommend to change the carts currency? It seems to work without any issues.
