### ISSUE TITLE
[4.x]: Order Status is marked deleted on yaml sync but never undeleted when going back

### ISSUE THREAD

**Issue by segidev** [craftcms/commerce#3029]
### Description
When changing to an older branch and applying the yamls the newer (non existing at that point) entries in `commerce_orderstatuses` get marked as deleted like here:
![image](https://user-images.githubusercontent.com/28906187/201701232-bf8d7ff7-8be4-4c5b-8b4f-04a4963fcfdb.png)

When switching back to the branch where they are supposed to come in they are never undeleted and are therefore not visible even though their yamls exist.

### Steps to reproduce

1. Create a new Order Status
2. Make a commit
3. Go back one commit
4. Apply changes
5. The order status is marked deleted in the db
6. Switch back to you latest commit
7. Order status is still marked as deleted and therefore not appearing in Admin

### Expected behavior
The status should no longer be marked undeleted

### Actual behavior
It stays marked as deleted as seen in the screenshot above

### Craft CMS version

Craft Pro 4.2.5.2

### Craft Commerce version

4.1.2

### PHP version

8.1.11

### Operating system and version

Linux

### Database type and version

PostgreSQL 14.4

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@segidev The order status shouldn't be affected when you do a commit because order status are not stored in the project config. It is stored on the db table `commerce_orderstatuses`. This could an issue with something else, could be a custom module or plugin. Please test this again with other plugins disabled and custom modules disabled,
