### ISSUE TITLE
[4.x]: firstName gets trimmed down when changing primary address.

### ISSUE THREAD

**Issue by jornwildenbeest** [craftcms/commerce#3030]
### Description

firstName gets trimmed down when changing primary address using the `/actions/users/save-address` endpoint.
For example: you have a first name with "Pieter jan".  
When updating the address with `firstName` in the post request, this works fine. But when you change your primary address for example, so the post request only contains `addressId` and `isPrimaryShipping`, the first name gets trimmed down to only "pieter".

### Steps to reproduce

1. Create form to update address with the endpoint`/actions/users/save-address`.
2. update address with two words in the firstName field, for example "Pieter Jan".
3. Create form to only change primary address with the same endpoint, but only `addressId` and `isPrimaryShipping` as parameters in the post request
4. firstName gets changed back to "Pieter".

### Expected behavior
I would expect that the first name stays the same.

### Actual behavior
First name gets trimmed down to "Pieter"

### Craft CMS version

4.3.1

### Craft Commerce version

4.2.2

### PHP version

8.1

### Operating system and version

mac os

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@jornwildenbeest I could not replicate this issue but when you submit the `fullName` input value to the save-address action, you will get inaccurate values such as stripping second word. 

Can you test this again but remove the
```
    {{ input('text', 'fullName', address.fullName ?? '', {
      id: 'fullName',
      class: ['w-full', 'border border-gray-300 hover:border-gray-500 px-4 py-2 leading-tight rounded']
    }) }}
```

html input in the form? Let us know how it goes.

**Comment by jornwildenbeest** [comment]
You are right. We are doing some stuff after saving the address for the first time with the inaccurate values we got returned, that caused it to save it again with only the first name.

So I'm going to close this issue, thanks!
