### ISSUE TITLE
[4.x]: Order Status selector UI bug

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#3036]
### Description
If there are many order statuses, then when editing an order and trying to select a status, the dropdown list can go below the bottom of the browser window. The list is not scrollable and therefore it is impossible to select the last items in the list.

### Craft CMS version

Craft Pro 4.3.3

### Craft Commerce version

4.2.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
I am able to scroll the list in both update status action and in the edit page.

Which browser/OS etc?


https://user-images.githubusercontent.com/133571/203509111-12e5fa9a-9dee-4734-9e51-e84631a85999.mp4

<img width="413" alt="CleanShot 2022-11-23 at 17 15 04@2x" src="https://user-images.githubusercontent.com/133571/203509293-7008b2e2-b393-4d38-86ff-5657195fe4a9.png">
