### ISSUE TITLE
[4.x]: AJAX call to `update-cart` disregards active session.

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/commerce#3039]
### Description
I have a Vue application which I build into a UMD module that gets imported into a website. This way, all code resides on the same domain and the same server. 
From the Vue app, I call the `update-cart` action using `fetch()` passing stringified `application/json` data. All headers are according to the Craft CMS docs.

The request is handled properly, the product is added to **_a_** cart, but it always creates a new cart because the 
```$currentUser = Craft::$app->getUser()->getIdentity();``` inside the `update-cart` controller returns `null`.

So the active session is **not respected** if I do a `POST` request from my Vue app.

The active session **is respected** when:
- I do a `GET` request from my Vue app (the correct active cart is returned).
- I do a `GET` request to the `session-info` controller from my Vue app. It returns my correct Identity.
- Running the `POST` request via PostMan. This puts it into the same cart (without a customer added to it ofcourse, but it keeps the same session).

Extra notes:
- `CSRF` is disabled.
- I can make it work by doing a `getCart` and passing the returned cart number to my `updateCart`, but I should not need to do that.
- I can't believe that UMD module has anything to do with it, because the server gets a request with correct data, so it shouldn't matter to the server where it comes from.

### Expected behavior
- The active session should be respected and return the correct identity.

### Actual behavior
- The session is not respected and returned identity is `null`.

### Craft CMS version

4.3.3

### Craft Commerce version

4.2.2

### PHP version

8.1

### Operating system and version

MacOs Big Sur

### Database type and version

MySQL

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Is the js app and the craft install on the same domain? Is this for all controller endpoints or just commerce endpoints? Can you post to a craft core controller and the session works?

**Comment by TomDeSmet** [comment]
They are both on the same domain. The Vue app just gets imported as a build JS file into the main JS file from the website. So it's one domain.

I'm still doing some extra tests, but I can already say that the `Craft::$app->getUser()->getIdentity()` also returns `null` in a custom module controller. I'll test the core controller next. Also testing again with FormData.

**Comment by TomDeSmet** [comment]
I can also add that using FormData is working (in contrast to what I said earlier). But I really prefer to use JSON...
But maybe this can point us somewhere why it is not working using JSON data?

**Comment by TomDeSmet** [comment]
Another addition that seems to have the same root cause: using JSON data the CSRF never works. Not by using the CSRF token from Craft nor getting a CSRF token from `session-info`. Using FormData, that also works out of the box.

Something is really off with processing JSON data...

**Comment by TomDeSmet** [comment]
My own fault, I was adding the wrong properties for `credentials` to my request.
