### ISSUE TITLE
[4.x]: Redactor product link

### ISSUE THREAD

**Issue by lukas-jansen** [craftcms/commerce#3041]
### Description
When you have a multi site shop and you have a product type which doesn't have urls for the primary site (or where your CP lives) they won't show up when you want to link to them inside a Redactor field. As only the current site is checked https://github.com/craftcms/commerce/blob/develop/src/Plugin.php#L397
This should look for the site dropdown inside Redactor itself.

Now you are forced to give them a url on the primary site to be able to link

### Craft CMS version

4.3.3

### Craft Commerce version

4.2.2

### PHP version

8.1

**Comment by lukeholder** [comment]
Thanks, this is fixed for the next release.
