### ISSUE TITLE
[3.x]: Shipping rate not showing with minimum Total Order Value with positive discount

### ISSUE THREAD

**Issue by joepagan** [craftcms/commerce#3049]
### Description

We use the discount adjuster to add positive values to items for an additional surcharge.

On a shipping rule I have a `Total Order Value` minimum value of £500.

![image](https://user-images.githubusercontent.com/2337910/207674168-5b8206e1-92cb-46f8-a062-91b9711b123a.png)

This shipping rule does not become available on the checkout shipping page, I suspect it's probably down to our positive discount value and maybe commerce doesn't account for that? The description of `Total Order Value` suggests that this is considered. 

Sounds somewhat related to [this closed issue](https://github.com/craftcms/commerce/issues/1800) from an older commerce.

Let me know if I'm missing something here, thanks!

### Steps to reproduce

1. Add shipping rule
2. Set min value
3. Add product to basket where item and discount value is above minimum threshold
4. experience no active shipping rule

### Expected behavior

Rule to show

### Actual behavior

Rule does not show

### Craft CMS version

"craftcms/cms": "3.7.46",

### Craft Commerce version

"craftcms/commerce": "3.4.15",

### PHP version

8.0.12

### Operating system and version

php:8.0.12-fpm-alpine

### Database type and version

aurora (mysql 5.7.27 or maria 10.2.31)

**Comment by pdaleramirez** [comment]
@joepagan The shipping condition will only work for the built-in Discount Adjuster. I believe you are using Custom Discount adjuster because price adjustment is positive instead of negative.
