### ISSUE TITLE
[4.x]: Product id is not correct when added to the cart

### ISSUE THREAD

**Issue by joneslafuente** [craftcms/commerce#3051]
### Description
All working I can add products fine and go through the checkout process. I previously (Craft Commerce 3) had a conditional check if the product id was in the cart then it would show an already added button that linked through to the cart. This is not working in Commerce 4, although for Digital Products (plugin) it is working. Displaying the IDs for each and then the IDs in the cart and I see the cart is showing the next number up for commerce products.

I have an ID 3307 which is the product id and the cart is showing it as 3308. Digital products are showing the correct id in the cart.

So am guessing that is why my conditional buttons are not working.

### Craft CMS version

4.3.4

### Craft Commerce version

4.2.4

### PHP version

8.0.26

### Operating system and version

Linux 5.4.0-120-generic

### Database type and version

MySQL 10.3.37

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

Digital Prodcucts 3.1.0
Embedded Assets 3.1.0
Freeform 4.0.8
Neo 3.5.10
Redactor 3.0.2
Redactor Styles 4.0.2
Stripe for Craft Commerce 3.0.3

**Comment by joneslafuente** [comment]
Ok so not sure if anyone checks on these possible bugs so currently am having to do a -1 on the purchasable id in the cart as that then matches the product id. As mentioned previously digital products have the correct purchasable id so not sure why regular commute products don't.

On a separate issue, I cannot edit or delete a digital product once added. I have this on 2 separate sites I am working on: 
https://github.com/craftcms/digital-products/issues/79

**Comment by pdaleramirez** [comment]
@joneslafuente Product ID and Purchasable ID have different values.  A product have `product.defaultVariantId` attribute which is the `purchasableId` use this instead. I would suggest to do a condition based on product `SKU` instead.
