### ISSUE TITLE
[4.x]: Environment variable for 'Enabled for customers to select during checkout' does not save.

### ISSUE THREAD

**Issue by samueldraper** [craftcms/commerce#3052]
### What happened?

**Seems like similar issue to #2927** 

When trying to use an environment variable for the setting 'Enabled for customers to select during checkout?' the control panel does not save the value. Instead it reverts to the control panel Yes/No dropdown defaulting to "Yes".

It will save the setting from within the control panel dropdown. i.e. I can save it to the desired setting of 'no' and vice versa and it does recognise that the relevant environment variable exists but does not retain it upon save.

**Steps to reproduce**

1. Within control panel got to Commerce > System Settings > Gateways > 
2. Choose a gateway
3. Set the dropdown 'Enabled for customers to select during checkout?' to an environment variable that is saved in the .env file

**Expected behavior**

Should save the env variable.

**Actual behavior**

Reverts to control panel options only.

### Craft CMS version

4

### Craft Commerce version

4

**Comment by samueldraper** [comment]
Update: it appears that the env variable does save to the project's yaml files. But it does not display in the control panel that it has used the env var. Instead it displays Yes/No, which is inconsistent with how the other vars are displayed. So you have to check each gateway yaml file to make sure the change made has been saved.

<img width="669" alt="Screenshot 2023-01-13 at 11 13 10" src="https://user-images.githubusercontent.com/2412282/212307135-9890de7d-1971-4668-ae55-7fcc3422b87c.png">

**Comment by pdaleramirez** [comment]
I was able to replicate this bug.

**Comment by lukeholder** [comment]
This has been fixed for the next release, which should be released within 24 hours. Thanks.
