### ISSUE TITLE
$hasSales variable does nothing — Getting products that have variants on sale

### ISSUE THREAD

**Issue by fabianhijlkema** [craftcms/commerce#306]
### Description
I'm using the Element Api plugin to return a list of products having a variant on sale. When querying variants I can use hasSales as a criterium (why differ between hasSales [VariantQuery.php] and onSale [Variant.php] btw?), but although the $hasSales variable is present in ProductQuery.php, nothing seems to be done with it. So I wonder, is the functionality still missing or am I missing a point?

Thank you for all your good work!
Fabian

### Additional info

- Craft version: 3
- PHP version:
- Database driver & version:
- Plugins & versions: Element Api (latest version)

**Comment by lukeholder** [comment]
We have gone ahead and removed the `hasSales` param attribute from the `ProductQuery` class as it was not used or needed. Will be gone in the next release.

If you need to get products that have variants on sale use the `ProductQuery::$hasVariant` param.

Examples:

Twig
```twig
{% set products = craft.products.hasVariant({hasSales: true}).all() %}
```

PHP
```php
$products = Product::find()->hasVariant(Variant::find()->hasSales(true))->all();
```

**Comment by fabianhijlkema** [comment]
Ah ok, I think I now better understand the structure. In the Element Api I now use the following criteria...

`'criteria' => [
	'hasVariant' => ['hasSales' => true]
]`

**Comment by lukeholder** [comment]
Yeah that looks like it would be correct!
