### ISSUE TITLE
[4.x]: Widget size is not saving

### ISSUE THREAD

**Issue by gaelpleeroy** [craftcms/commerce#3069]
### Description
I have multiple widgets and when I change the size of one (to 3 slots) it display correctly but when I refresh the page the size is reset to 1 slot.

### Steps to reproduce

1. Have multiple widgets
![image](https://user-images.githubusercontent.com/57365491/214949836-8b1d949f-9247-46ba-99e5-3fc88ae620e7.png)
2. Change size of Total Orders form 1 to 3
![image](https://user-images.githubusercontent.com/57365491/214949934-950509a4-24dc-4715-9f40-40cdc3c1cba3.png)
3. Display is good and I get "Widget saved" toast notification
![image](https://user-images.githubusercontent.com/57365491/214950065-164f1215-f47f-4855-ba8d-7f97d24ad11d.png)
4. Reload page and notice the layout come back to step 1 with the Total Orders back to size 1

### Expected behavior
The widget should keep his saved size.

### Actual behavior
The widget is resetting to a size of 1.

### Craft CMS version

Craft Pro 4.3.6.1

### Craft Commerce version

Craft Commerce Pro 4.2.4

### PHP version

8.1.6

### Operating system and version

Linux 5.10.16.3-microsoft-standard-WSL2, Chrome browser

### Database type and version

MySQL 5.7.29

### Installed plugins and versions

- Amazon S3 2.0.1
- Google Maps 4.2.5
- Navigation 2.0.16
- Redactor 3.0.3
- SEOmatic 4.0.19
- Sprig 2.4.0
- Stripe Payments 5.0.9
- Translations admin 3.0.1

**Comment by pdaleramirez** [comment]
@gaelpleeroy The Total Orders widget has a maximum colspan of 1. This is intentional because making the widget wider is unnecessary due to few text being displayed. It is not possible to make the widget wider.
