### ISSUE TITLE
Issue Saving Shipping and Billing Fields

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#307]
### Description

When updating shipping and billing fields via ajax, I'm getting this returned

```
Argument 1 passed to craft\commerce\services\Addresses::getAddressByIdAndCustomerId() must be of the type integer, string given, called in /home/vagrant/Code/clients/safebonesco/website-craft3/vendor/craftcms/commerce/src/controllers/CartController.php on line 284
```

I believe this has to do with the customerId being sent as "new" which was something Commerce 1 required. Is that something we should also be doing in Commerce 2?

### Steps to reproduce

1. Submit an update-cart request via ajax passing "new" as shippingAddressId or billingAddressId

### Additional info

- Craft version: 3
- PHP version: 7.1
- Database driver & version: Maria DB
- Plugins & versions:

**Comment by lukeholder** [comment]
Just adding some quick docs to https://github.com/craftcms/commerce-docs/blob/v2/en/changes-in-commerce-2.md#setting-addresses-in-update-cart

Let me know if you need more clarification.

**Comment by magnessjo** [comment]
@lukeholder, thanks for adding this to docs.  It helped me solve the issue quickly.
