### ISSUE TITLE
[4.x]: Deleting user with existing order/subscription shows success message

### ISSUE THREAD

**Issue by Romanavr** [craftcms/commerce#3070]
### Description
I noticed that for some reason I can't delete a user after upgrading to commerce 4.x  even though the flash message always shows that "Users deleted" https://i.imgur.com/c7ZQEe8.png (however, user still exists after page refresh)
Then I did a little research & found that it was because the user (customer) had an existing order/subscription.
https://github.com/craftcms/commerce/blob/4.2.4/src/Plugin.php#L586
Order: https://github.com/craftcms/commerce/blob/4.2.4/src/services/Orders.php#L173
Subscription: https://github.com/craftcms/commerce/blob/4.2.4/src/services/Subscriptions.php#L408

Returning`false` here https://github.com/craftcms/cms/blob/4.3.6.1/src/services/Elements.php#L1954
And it shows us a success flash message however it's wrong https://github.com/craftcms/cms/blob/4.3.6.1/src/elements/actions/DeleteUsers.php#L173

This is a visual error for common/general user view only(`/*cp-url*/users`), if you'll try to delete a user on the detailed page(`*cp-url*/users/{id}`) you will get a fail flash message. The same behavior should be for the general user view.

### Steps to reproduce
1. Create a user and add an order/subscription to him.
2. Try to delete this user on the users page (`http://site.com/admin/users/all`)
3. The flash message shows "Users deleted" but after page refresh the user(s) is still there.

### Expected behavior
A flash failure message should appear describing why we can't delete the user(s). #3071 

### Actual behavior
It shows a successful flash message "Users deleted"

### Craft CMS version

4.3.6.1

### Craft Commerce version

4.2.4

### PHP version

8.1

### Installed plugins and versions

-

**Comment by Romanavr** [comment]
Any update here?

**Comment by gaelpleeroy** [comment]
Hi, I have the same problem here I can't delete my test user no matter the option I choose (transfer or delete content).

**Comment by lukeholder** [comment]
@Romanavr @gaelpleeroy 

We have made the stop-gap measure in Commerce (#3071) to show an exception on the first undeletable user through the flash error. This will be in the next release.

Although not ideal, we expect Craft 5 will introduce a better way for Commerce to hook into user deletions.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#151d0b250e16459a875df1654dabf73bd41cabf3 as 4.2.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by nfourtythree** [comment]
Version `4.2.10` of Commerce is now out with this fix.

Thanks!
