### ISSUE TITLE
[4.x]: 3 > 4 upgrade issue. Add an index for the droppable v3customerId column on commerce_orders table

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/commerce#3072]
### Description

We have ~400k customer records and ~250k orders. 

After running the commerce/upgrade command it hangs on "Creating a user for every customer…"

We traced it to the `_getOrphanedCustomerIds()` method.

Adding an index for the `v3customerId` column fixed the issue for us.

Moving on now to migrating 450k address records... 😭

### Craft CMS version

4.3.6.1

### Craft Commerce version

4.2.4

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@jamiepittock does this look like the change you made?

https://github.com/craftcms/commerce/pull/3075

We are testing now and will add along with your confirmation. Thanks.

**Comment by jamiepittock** [comment]
Yeah it looks good, thanks! 

FYI the rest of the upgrade ran well (just took a while!). No issues with the order history migration. I see you added an index to that one too.

Looking forward to being on the latest and greatest!

**Comment by lukeholder** [comment]
Fixed in 4.2.5
