### ISSUE TITLE
[4.3]: Multi-site publishing

### ISSUE THREAD

**Issue by mmorkt** [craftcms/commerce#3080]
### Description
So I'm using Craft Commerce on a multi-site. Got all functionality up and running, but the way products is published is not working for me. 

My client's shop is selling B2B. All clients has a unique storefront with the products and prices they can order from my client. So far so good. The problem is when publishing a product on a specific site its published to all sites. I'm missing the feature from Craft CMS's publishing tool, where you can specify where to publish the entry.

![sites](https://user-images.githubusercontent.com/23133663/216273251-c02411b6-8790-4dd5-a2c5-93700bf3a784.jpg)

If I'm disabling `Enabled for site` its still active on all other sites, where it shouldn't be active. So what I'm doing now is setting `Enable` to false and then going through all 6 sites to set `Enabled for site` to false, then re-enable the product. 

### Craft CMS version

4.3.6.1

### Craft Commerce version

4.2.5

### PHP version

8.1.9

### Operating system and version

MacOS

### Database type and version

MySQL

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@mmorkt Craft Commerce only supports Multi-Site and not Multi-Store. A product will be the same across all sites. It will have the same price. You can only change the product’s title and text information. You can set different prices per site when the Multi-Store feature is available.

 The enable for site feature is used to filter product display only. If you disable the products on a specific site, they will not be shown on other sites.

The multi-store will be available on Commerce 5. To track the feature follow this GitHub discussion: https://github.com/craftcms/commerce/discussions/2283
