### ISSUE TITLE
[4.x]: Existing order address labels after Commerce 4 upgrade 

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/commerce#3081]
### Description

After upgrading to Commerce 4, the labels for existing order addresses are both simply "Address".

If you put the order into edit mode and update the order, the labels change to "Billing Address" and/or "Shipping Address".

Existing order addresses upgrade

![Screenshot 2023-02-02 at 10 13 20](https://user-images.githubusercontent.com/35454/216298060-12e38545-ea27-41a5-83a3-6a8300bd3caf.png)

Same order after switching to edit mode and updating the order.

![Screenshot 2023-02-02 at 10 16 01](https://user-images.githubusercontent.com/35454/216298141-b2cd4887-efb8-47a4-99dd-52059bb4a938.png)

### Craft CMS version

4.3.6.1

### Craft Commerce version

4.2.4

### Installed plugins and versions

-

**Comment by Romanavr** [comment]
In my case, my clients basically only have a shipping address. But yes, same problem.
After updating, the "Address" turns into a "Shipping address"

**Comment by jamiepittock** [comment]
@lukeholder Any progress on this? I know it's not the most critical issue but we're almost ready to upgrade and it'd be good to know if this was fixable before then.

**Comment by lukeholder** [comment]
This will be fixed in a future 4.x release based on #3599 - we will update this issue once the release is out.

**Comment by lukeholder** [comment]
Craft Commerce 4.6.8 is now out with this fix!
