### ISSUE TITLE
[4.x]: Address does not show all fields on cp order edit screen

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#3082]
### What happened?

I have a phone field added to the user address fields.

When viewing an order in the CP, this phone field does not show in the address preview pane on the order detail screen.

### Craft CMS version

4.3.3

### Craft Commerce version

4.2.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out with the ability to customize the default address formatter.
