### ISSUE TITLE
[4.x]: Control Panel search for SKU does not return results if it's a "number"

### ISSUE THREAD

**Issue by christianruhstaller** [craftcms/commerce#3084]
### Description
In the control panel on the element search you can not search for SKUs which are numeric. Alphanumeric SKUs will return results as expected. The SKU is part of a product variant.

### Steps to reproduce
1. Have a product variant type with a numeric only SKU
2. Have a product variant type with a alphanumeric SKU
3. Search for the numeric SKU
4. Search for the alphanumeric SKU

### Expected behavior
Both searches should return the corresponding entry.

### Actual behavior
Only the alphanumeric SKU will return a result.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/13237645/217485435-a5bdda18-50fe-4a07-a96f-9ec183488736.png">

<img width="925" alt="image" src="https://user-images.githubusercontent.com/13237645/217485504-2a2c6979-b9ff-4392-ba6b-24e775b57db9.png">
<img width="956" alt="image" src="https://user-images.githubusercontent.com/13237645/217485576-d4b4b872-bc81-4f6e-b36c-0e78947cde9c.png">

### Craft CMS version

4.3.7.1

### Craft Commerce version

4.2.5.1

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@christianruhstaller I couldn’t replicate the issue. Could you try this command?

```
php craft resave/products --updateSearchIndex=1
```

Let us know if that fixes the issue.

**Comment by christianruhstaller** [comment]
This did not resolve the issue. Maybe one part I missed, is that we use variants and the SKU is set on the variant of course.

I looked at the searchindex table and the SKU is not to be found for the product with the numeric SKU. Interestingly the other fields like title are correctly indexed.

Next week I will try to debug the process and see why it does index the other fields but not the SKU.

**Comment by pdaleramirez** [comment]
@christianruhstaller It seems to be working for both products and variants. We’ll re-open if the issue persists.

**Comment by christianruhstaller** [comment]
So the problem was the usage of the relax plugin (https://github.com/ostark/craft-relax).
This plugin removes searchindex values which are only numeric.

See following issue: https://github.com/ostark/craft-relax/issues/15

So I leave this here for a headsup if someone else is experiencing the same problem in commerce and has the relax plugin installed.
