### ISSUE TITLE
[4.x]: Coupon code with no action is applied, but not counting

### ISSUE THREAD

**Issue by vandres** [craftcms/commerce#3085]
### Description

We're having a setup, where we use the Commerce discounts for using the coupon codes and some own Adjuster, to add the actual discount.

This works very well, with one exception. The coupon codes get applied, are written to the database and we can access everything in our adjuster. But since we didn't define anything as a discount action (I think), the applied coupon code doesn't count up.

If this is the intended behaviour, then an option to overwrite that would be nice. But if it is intended, then writing all the information to the database makes no sense imho.

### Steps to reproduce

1. Create an discount with a coupon code and no action
2. Make an order with that discount code
3. The count is still "0"

### Expected behavior

The count should go up

### Actual behavior

The count is still "0"

### Craft CMS version

4.3.7.1

### Craft Commerce version

4.2.5.1

### PHP version

8.1

### Operating system and version

MacOS, Debian Docker

### Database type and version

MariaDB 10.5

### Installed plugins and versions

```json
  "require": {
    "bymayo/commerce-widgets": "^3.0",
    "craftcms/cms": "4.3.7.1",
    "craftcms/commerce": "^4.1.0",
    "craftcms/commerce-paypal-checkout": "dev-develop",
    "craftcms/redactor": "^3.0",
    "mmikkel/cp-field-inspect": "^1.4",
    "nystudio107/craft-retour": "^4.1",
    "nystudio107/craft-vite": "^4.0",
    "php-http/curl-client": "^2.2",
    "putyourlightson/craft-elements-panel": "^2.0",
    "putyourlightson/craft-sprig": "^2.1",
    "sebastianlenz/linkfield": "^2.1",
    "spatie/craft-ray": "^2.0",
    "spicyweb/craft-neo": "^3.2",
    "ttempleton/craft-nocache": "^3.0",
    "typesense/typesense-php": "^4.8",
    "vaersaagod/geomate": "^2.1.0",
    "verbb/expanded-singles": "^2.0",
    "verbb/field-manager": "^3.0",
    "verbb/tablemaker": "^4.0",
    "verbb/wishlist": "^2.0",
    "vlucas/phpdotenv": "^5.4.0",
    "wbrowar/adminbar": "^3.2"
  },
  "require-dev": {
    "deployer/deployer": "^7.0",
    "yiisoft/yii2-shell": "^2.0.3",
    "roave/security-advisories": "dev-master"
  },
```

**Comment by pdaleramirez** [comment]
@vandres This is the expected behavior; it should count up for completed orders and discounts with cost only.
