### ISSUE TITLE
[4.x]: TypeError when setting taxRate name to empty string

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#3089]
### Description
When using Commerce Lite and you remove the taxRate name in the tax settings (/commerce/store-settings/tax) you get a PHP TypeError Cannot assign null to property craft\commerce\models\LiteTaxSettings::$taxName of type string.

### Steps to reproduce

1. Have commerce lite installed
2. Go the the tax settings
3. clear the Tax name field
4. press save

### Expected behavior
A validation error should be thrown as it is a required field.
Also tested this on commerce Pro and their you do get a form validation message saying it can not be empty

### Actual behavior
Database table is getting saved with the name as an empty field so everytime you go to the tax setting, you are receiving this error.
Only way to solve this is by filling in something directly in the database table.

### Craft CMS version

4.3.6.1

### Craft Commerce version

4.2.5.1

### PHP version

8.1.15

### Operating system and version

Linux 5.15.0-60-generic

### Database type and version

MySQL 8.0.32

**Comment by lukeholder** [comment]
This is now fixed and in the 4.2.6 release just out. Thanks.
