### ISSUE TITLE
[4.x]: Handle null gateway in processPayment

### ISSUE THREAD

**Issue by timkelty** [craftcms/commerce#3092]
### What happened?

https://github.com/craftcms/commerce/blob/8a5183cc00add362de0c03eba0facde8651e9750/src/services/Payments.php#L270-L273

`\craft\commerce\elements\Order::getGateway` can return `null`, but `\craft\commerce\services\Payments::processPayment` doesn't account for that.

If there is no gateway, that will result in `cannot access property paymentType on null`.

I'm guessing we should just throw in the event of a `null` gateway, but wasn't sure where or which exception.

In normal scenarios, a gateway would be set, but we still need to account for the scenario if it is types as such.

### Craft CMS version

4.4.x-dev

### Craft Commerce version

4.2.5.1

### PHP version

8.1

### Installed plugins and versions

- only good ones

**Comment by lukeholder** [comment]
This is now fixed and released in 4.2.6 Thanks
