### ISSUE TITLE
[3.x]: missing tax on line items with slow API, EVENT_POPULATE_LINE_ITEM called 5 times when adding a product to cart, line item tax rate info only available on 4th and 5th iteration

### ISSUE THREAD

**Issue by joepagan** [craftcms/commerce#3094]
### Description

Where a cart is empty and I add a product to it, this event gets called 5x times.
Is this right? Or is something contributing to that being called more than it should and there is an issue here?

I am admittedly and regrettably working with a very slow SOAP API on this event, which frequently times out and these requests are contributing to completely overwhelming the SOAP server where the app is required to get customer specific pricing (for lineItem price manipulation), check API stock availability exists on this event.

It looks like the tax rate is only applied on the 4th and 5th rotation of this event, and I think this is causing an issue where:

- SOAP server hits timeouts before 4th or 5th rotation
- process is killed
- lineItem is added to the cart/order with no tax

### Steps to reproduce

1. Add a product to cart
2. Use slow SOAP response which hits timeout in `EVENT_POPULATE_LINE_ITEM` before 4th iteration
3. lineItem is added without tax

### Expected behavior

1. Add a product to cart
2. Use slow SOAP response which hits timeout in `EVENT_POPULATE_LINE_ITEM` before 4th iteration
3. lineItem is still added with tax, or, we are able to determine in this event if tax is added or not and can notify customer user line item has been removed and to try again

### Thoughts / ideas

- Wanted to check tax rates were applied to a line item, and if tax is missing on a line item, remove the line item from cart prompting a message for a customer user to re-add. However, this is not possible with `EVENT_POPULATE_LINE_ITEM` as the first 3 iterations has a line item tax rate: 0
- Is there another event I can use in this chain of events to ensure tax is applied to a lineItem? Such as `EVENT_AFTER_SAVE_LINE_ITEM` (this appears to be called once where cart is empty, but twice if same product already exists in cart)
- Would `EVENT_AFTER_SAVE_LINE_ITEM` still be called if the process is killed in the multiple `EVENT_POPULATE_LINE_ITEM` events that occur?
- If I was to recalculate the order at the final checkout step, or where a lineitem has 0 tax on `EVENT_AFTER_SAVE_LINE_ITEM` would this apply the correct tax to each line item? And If possible would `$order->recalculate()` be what I need?
- Is there another event similar to `EVENT_POPULATE_LINE_ITEM` which is more suitable and only called once?

### Craft CMS version

"craftcms/cms": "3.7.46",

### Craft Commerce version

"craftcms/commerce": "3.4.15",

### PHP version

8.0

### Operating system and version

alpine 8.0 fpm

### Database type and version

aurora / maria 10.2.31

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@joepagan I’ve tested the event, and it seems to be hitting twice only. If you have multiple sites on the project, it will hit the event based on how many sites you have, which is expected behavior.

Please test out disabling the custom module or plugin to see if that causes the issue.
