### ISSUE TITLE
[4.x]: Sales::getAllSales is VERY slow

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#3096]
### What happened?

The query in Sales::getAllSales() is VERY slow, taking 500ms on average (!). It probably needs proper indexing or something? See these screenshots:

<img width="973" alt="Screenshot 2023-02-22 at 08 34 44" src="https://user-images.githubusercontent.com/378974/220553283-5218bdff-18b9-49a8-8de3-15f0120c03bb.png">
<img width="343" alt="Screenshot 2023-02-22 at 08 35 24" src="https://user-images.githubusercontent.com/378974/220553426-a77478be-8f35-465c-8413-a47d534e1484.png">
<img width="1495" alt="Screenshot 2023-02-22 at 08 35 37" src="https://user-images.githubusercontent.com/378974/220553456-61879821-9bb7-4942-b6cf-12b997c2e941.png">

### Craft CMS version

4

### Craft Commerce version

4

### PHP version

8.1

### Operating system and version

Linux

### Database type and version

PostgreSQL 12

**Comment by nfourtythree** [comment]
Hi @boboldehampsink 

Thank you for the issue.

I have just tested this in PGSQL v2 and things seem to be working as expected.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/jkuAgwye/e5928cd3-39f1-4e53-9f3c-43ead060ae4b.png?v=a67247c16e10b7789052c1b2121e5822)

Are you able to test a fresh DB or put this DB on a different server and see if it behaves the same?

Thanks

**Comment by boboldehampsink** [comment]
hi @nfourtythree loaded a dump of this db in a fresh instance, still slow. I will send the dump your way.

**Comment by boboldehampsink** [comment]
I did a vacuum and analyze on the database, and it took this query to 25ms... seems to be the fix! Thanks for checking anyway!

**Comment by nfourtythree** [comment]
Thanks for updating @boboldehampsink and glad you got everything working.
