### ISSUE TITLE
[4.x]: No interface for applying tax categories to tax rates

### ISSUE THREAD

**Issue by amphibian** [craftcms/commerce#3098]
### What happened?

I have a brand new development site and am setting up tax rates. I have two tax categories and multiple tax rates. But there is no interface to assign a Tax Category to any of my Tax Rates.

### Expected behavior

I see a Tax Category menu.

### Actual behavior

I do not see a Tax Category menu.

I tried the [fix in this recent commit](https://github.com/craftcms/commerce/commit/c9cdda166dcbaecaaee6e0ac13e9a0aa7f0f8b6c) but saw no change in behaviour after updating the file in question. I can also verify that the Tax Category field is indeed there in the source code of the page.

### Craft CMS version

4.3.10

### Craft Commerce version

4.2.5.1

### PHP version

8.1.0

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@amphibian I see no issues on the CMS and Commerce version you’ve stated. I can see the Tax Category menu in the Tax Rates setting. Can you ensure that there is no custom CSS from a custom module or plugin hiding the menu? Can you post screenshots, please?

**Comment by amphibian** [comment]
Thanks Dale. I have no custom CSS or JS in the control panel. Here's what I'm seeing:

<img width="876" alt="Screenshot 2023-02-28 at 7 00 57 AM" src="https://user-images.githubusercontent.com/53333/221861707-0d25097d-f744-4d52-81a2-d5232ad25f7c.png">

<img width="693" alt="Screenshot 2023-02-28 at 7 02 22 AM" src="https://user-images.githubusercontent.com/53333/221861732-3da69b5a-3db9-402b-966b-592a85902a00.png">

**Comment by robzor** [comment]
@amphibian you only get Tax Category as a choice with the non 'Order total' options in the 'Taxable Subject' dropdown, e.g. "Line Item price"

**Comment by amphibian** [comment]
Ah, OK. Maybe a note indicating this would be helpful? Perhaps disabling the category menu rather than hiding it entirely?
