### ISSUE TITLE
Store Currency as integers, not floats

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#31]
http://stackoverflow.com/a/3730040/167827

this is the same way stripe itself does it: "A positive integer in the smallest currency unit (that is, 100 cents for $1.00, or 1 for ¥1, Japanese Yen being a 0-decimal currency) representing the total amount for the order."

**Comment by lukeholder** [comment]
Related #697

**Comment by lukeholder** [comment]
Merging into #24
