### ISSUE TITLE
[4.x]: Creating manual orders in the CP throws an exception error, if it contains a dropdown field with a value of "null"

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#3115]
### Description

Since Craft CMS v4.4.2, it is no longer possible to create manual orders in the CP. I'm pretty sure this was working fine in Craft CMS v4.4.1.

### Steps to reproduce

1. Click on the "New order" button in Commerce in the CP
2. A "`Exception – [yii\base\Exception]`" is thrown on `line 139` in in `/var/www/html/craft/vendor/craftcms/commerce/src/controllers/OrdersController.php`

### Expected behavior

No exception to be thrown when clicking on the "New order" button

### Actual behavior

An exception is thrown when clicking on the "New order" button

### Craft CMS version

v4.4.2

### Craft Commerce version

v4.2.5.1

### PHP version

8.0.21

### Operating system and version

Linux 5.15.49-linuxkit

### Database type and version

MariaDB 10.4.25

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by jonleverrier** [comment]
Just to say, I can't reproduce on a clean Craft CMS 4.4.2 installation. I can't reproduce either starting on Craft CMS 4.4.1 and upgrading to 4.4.2.

**Comment by jonleverrier** [comment]
Found the problem!

### Steps to reproduce

1. Create a dropdown field called `test` and add the following values:
<img width="1032" alt="Screenshot 2023-03-15 at 22 37 26" src="https://user-images.githubusercontent.com/2373940/225449508-2305fb55-5021-4f60-9888-05a375481244.png">
2. Add the `test` field to `order fields` in Commerce > System Settings > Order Fields
3. Try and create a new manual order in the CP
4. An exception error is thrown

Removing the value of `null` from the select field makes it work again. Can't remember why I used the value of null - I'm sure it was a workaround for something else.

**Comment by jonleverrier** [comment]
Update: setting one of the options as `Default` fixes the issue. Odd behaviour!

**Comment by pdaleramirez** [comment]
@jonleverrier I was able to replicate this bug. I am not sure if this is a cms or commerce issue. We’ll ask the team to look into this.

**Comment by lukeholder** [comment]
This is now fixed in 4.2.6 of Craft Commerce, just been released. The error will not occur when creating the order, but on first order edit or refresh the custom field will show a validation error as expected.
