### ISSUE TITLE
[4.x]: Unset variables in toast message when updating order status

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#3116]
### Description

When the status of an order is changed from one to another, the toast message displays variables with no values set.

<img width="390" alt="Screenshot 2023-03-15 at 16 46 21" src="https://user-images.githubusercontent.com/2373940/225365492-6cbdf5d4-1d2f-4f8c-a166-2306d2b8b7f6.png">

### Steps to reproduce

1. Go to Orders in the Commerce CP
2. Select an order from the table and, as of Craft CMS v4.4, click on the cog at the bottom of the table
3. Click on Update Order Status and change the status from one value to another
4. The toast message appears with variables which are not set

### Expected behavior

For variables in the toast message to display when an order has its order status changed

### Actual behavior

Variables in the toast message are not set when an order has its order status changed (see screenshot above)

### Craft CMS version

v4.4.2

### Craft Commerce version

4.2.5.1

### PHP version

8.0.21

### Operating system and version

Linux 5.15.49-linuxkit

### Database type and version

MariaDB 10.4.25

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @jonleverrier 

Thank you for highlighting this.

We have pushed a fix which will be included in the next release of Commerce.

Thanks!

**Comment by lukeholder** [comment]
This is now fixed and in the 4.2.6 release of Commerce. Thanks.
