### ISSUE TITLE
[4.x]: SKU already exists when trying to save the same product on a new site.

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/commerce#3124]
### Description
I added new sites to an existing Craft setup. All products were propagated except for the SKU, price and stock fields (see #3125).
When I fill in the SKU field with the same SKU as the product has in all other previously existing sites and saving it, I get the error that the SKU already exists.

### Steps to reproduce

1. Add a new site to an existing Craft setup.
2. Wait for all products to be resaved.
3. Check a product, the SKU field will be blank.
4. Fill in the same SKU as the product has for the other sites.
5. Read the error.

### Expected behavior

SKU's should be propagated and if not, the error should not appear as we're saving the product with it's own SKU.

### Actual behavior

Throws an error.

### Craft CMS version

4.4.5 (also tested on 4.3.10)

### Craft Commerce version

4.2.6 (also tested on 4.2.5.1)

### PHP version

8.1.16

### Operating system and version

MacOS 13.2.1

### Database type and version

MySQL 8.0.32

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
I can confirm this is a bug on > 4.2.5, I've tested and it is because of this commit https://github.com/craftcms/commerce/commit/e99910f3e8413cde0b1ac1158264b01603466fcd
