### ISSUE TITLE
[4.x]: Propagation of products when adding new sites not complete.

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/commerce#3125]
### Description
While adding new sites to an existing Craft setup, products were propagated to the new sites, except for the SKU, price and stock. With hundreds of products, it's impossible to correct this manually and the only way to solve this at the moment is to write a custom job for it, I suppose. But this is not possible due to another bug described in #3124.

I tested this commit in `dev-develop` [commit](https://github.com/craftcms/commerce/pull/3076 ) but that didn't solve it.

### Steps to reproduce

1. Add new sites to an existing Craft setup and wait for the products to be resaved.
2. Check the product in the new site.

### Expected behavior

As it is the same product and there's no multi-store support yet, all product data should be the same across all sites.

### Actual behavior

Price, SKU and stock are empty.

### Craft CMS version

4.4.5 (also tested on 4.3.10)

### Craft Commerce version

4.2.6 (also tested on 4.2.5.1)

### PHP version

8.1.16

### Operating system and version

MacOS 13.2.1

### Database type and version

MySQL 8.0.32

**Comment by pdaleramirez** [comment]
This bug is related to the issue https://github.com/craftcms/commerce/issues/3124. We’ll close this one.
