### ISSUE TITLE
[4.x]: Updating to Craft Commerce 4.2.6 breaks the payment. Error getRedirectData is null, array expected

### ISSUE THREAD

**Issue by alpine-digital** [craftcms/commerce#3126]
### Description
I've updated the Craft Commerce plugin to the latest release: 4.2.6. Due to the newly added redirectData the payment breaks. We are using the Mollie plugin to handle the payments.

### Steps to reproduce

1. Add products to the cart
2. Use the checkout flow
3. Try to pay

### Expected behavior
You get redirected to the Mollie interface with payment options.

### Actual behavior
The payment fails due to the redirectedData that is missing.
![image](https://user-images.githubusercontent.com/117266131/227488082-853b9a15-7255-47e0-beb8-a71b94c65a88.png)

### Craft CMS version

4.4.5

### Craft Commerce version

4.2.5

### PHP version

8.1

### Operating system and version

MacOs

### Database type and version

MySql 5.7.34

### Image driver and version

GD 8.1.0

### Installed plugins and versions

-
![image](https://user-images.githubusercontent.com/117266131/227489735-6f9fa7a5-486e-40ff-931c-c8808fcc0a39.png)

**Comment by Rommert** [comment]
Same issue here!  Craft Commerce 4.2.6, Quick Fix: Roll Craft Commerce back to:  4.2.5.1

**Comment by pdaleramirez** [comment]
@alpine-digital The third-party plugin would need to fix the issue on their end. The `getRedirectData` method interface needs to return an array. The Stripe Commerce plugin does not have this error. I would recommend submitting this issue to the third-party plugin gateway repo.

**Comment by alpine-digital** [comment]
Thank you Dale for the feedback!

**Comment by mediabeastnz** [comment]
👀

**Comment by lukeholder** [comment]
@alpine-digital @chlsydkysr 

This should be fixed in commerce-mollie 4.1.0.1 -  Please update and let us know how it goes.

**Comment by Rommert** [comment]
@lukeholder i have the same issue on Craft CMS: 4.5.6.1, Commerce: 4.3.0, Mollie: 4.1.0.1. I updated Craft/Commerce from 3 to 4.

**Comment by nfourtythree** [comment]
@Rommert 

Thank you for your message, could you check the `composer.lock` file for your project and let me know what version it says for the `craftcms/commerce-omnipay` package.

You can also do this quickly from the command line with the following:

```sh
composer show craftcms/commerce-omnipay
```

Thanks
