### ISSUE TITLE
[3.x]: Date ordered value keeps updating by itself

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#3127]
### Description
We are having an issue where the 'Date Ordered' value keeps updating by itself whenever an order is updated via the CMS. 

My client has been in and updated the status of various orders. Whenever he does this and hits 'Update Order', it will also update the 'Date Ordered' to some daft date in the future e.g. 2024/2025. In some cases, there is a bit of a pattern where it will switch the day / month values around. But this isn't for all of the skewed orders, only a handful.

I am wondering if this is something that is happening only on my clients machine - maybe their date / time is set incorrect on there and then Craft is picking that up?!

I cannot replicate the issue myself. All stays the same even if I update the value back to its original, then make a change and hit 'Update Order'.

Have you had any other issues like this crop up before?

### Craft CMS version

3.8.5

### Craft Commerce version

3.4.20.1

### PHP version

8.0

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@iamtompickering There isn’t any reported bug about Date ordered updating incorrectly. Have you tested disabling any plugins and custom modules? it could be an event that is causing the issue.
Could you also check in the database directly if the records have been changed? It could be a web browser extension translation is causing the issue too.

**Comment by iamtompickering** [comment]
Thanks for this info @pdaleramirez I will look into these bits and get back to you. I did also find this https://github.com/craftcms/commerce/issues/1246, not sure if it could be related as it sounds like very similar behaviour.

**Comment by pdaleramirez** [comment]
@iamtompickering, the bug has been fixed since v3.0.4. Also, is the Commerce plugin updated on the correct version?
