### ISSUE TITLE
Calling unknown method: craft\commerce\services\Carts::setPaymentSource()

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#313]
### Description

When processing a payment as a logged in user and having save "savePaymentSource" set to true, an error is thrown after the page is submitted with token.

Screenshot of stack-trace:
https://cl.ly/2n060R3w1y2S

### Steps to reproduce

1. Login as a user
2. Add product to cart and go to checkout page
3. Process a payment using the Stripe Gateway, with savePaymentSource set to true

### Additional info

As a side note, I noticed that when I was logged in as a user, the cart.id and cart.customerId both had somewhat odd values. The cart.id happened to be 1 less than the user.id set for the logged in user. Also, the cart.customerId was different from the user.id...

https://cl.ly/1t2c1317181H

I wasn't sure ^ this was related to the issue I'm seeing, but I was thinking maybe it's not able to associate the payment source to the right user?

- Craft version: 3
- PHP version: 7.1 
- Database driver & version: Maria
- Plugins & versions:

**Comment by bryantAXS** [comment]
Another item worth mentioning is that products are being added to the cart before the user's account has been created. Then on the checkout page, we're prompting them to create their account (via ajax) after which the payment is submitted.

I've tried the checkout a few different ways:
- Products added before account creation => create account => checkout
- Create account => add products => checkout
- Login to existing account => add products => checkout

All of them give the same result.

**Comment by lukeholder** [comment]
I have closed this issue due to the fix just made for the `::setPaymentSource` error. Please make new issues for other items if applicable.
