### ISSUE TITLE
[4.x]: Discount not working when "Match Order" rule is set

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#3131]
### Description

When creating a discount without a coupon code (so it will apply to everybody), the discount isn't added if "Match Order" rule is set to a specific site, but the client is on the specific site when ordering:
![image](https://user-images.githubusercontent.com/22771556/230036570-26dfcf83-368b-423a-bcaa-6ac9a8f77373.png)

Removing this rule, then the discount is added to the order.

### Craft CMS version

Craft Pro 4.3.4

### Craft Commerce version

4.2.4

### PHP version

8.1.12

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Craft 4.3.10 removed the "Site" condition from any element type that are not multi-site localised/aware (Orders are not multi-site/localised) - so you shouldn't see that condition if you upgrade to Craft 4.3.10.

But, We *should* add an "Order Site" condition, that would filter the order based on which site you were in when managing/building the cart. Will do so shortly. The `cart.orderSiteId` is unique to Commerce Orders, and just tracks which site the order was made on, but the `cart.siteId` will always be the primary site.

Will update here once we add that.

**Comment by lukeholder** [comment]
In 4.2.7 we added the Order Site rule so you can make a condition based on the Site the order was last updated in.

Hope that helps.
