### ISSUE TITLE
[4.x]: Unable to select categories for promotions after completing 'entrification'

### ISSUE THREAD

**Issue by sunscreem** [craftcms/commerce#3134]
### Description

We've now moved all our categories into structures as per the [Entrification blog](https://craftcms.com/blog/entrification) so that we are ready for next version of Craft. This has meant product categories can no longer be selected.

### Steps to reproduce

1. Move all categories into structures.

### Expected behavior

![image](https://user-images.githubusercontent.com/7523595/230421297-607b740d-8305-409c-9add-a3483096c64a.png)

### Actual behavior

When clicking the button it's empty.

### Craft CMS version

4.4.5

### Craft Commerce version

4.2.6

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@sunscreem Commerce will also get a new version to support “structures” on promotions.

**Comment by pdaleramirez** [comment]
> Awesome - thanks @pdaleramirez. Is that likely to be a 5.x release or a 4.x release?

It would be a 5. x release.

**Comment by lukas-jansen** [comment]
@pdaleramirez maybe this should be clearly noted somewhere.

We already started a new commerce project with only entries but now we have to restructure it back to categories as we didn't noticed this yet until now...

And luckily didn't migrated existing commerce projects over yet.

**Comment by lukeholder** [comment]
@lukas-jansen 

We've decided to add a setting to the next release of Commerce to switch sales to use entries for it's relationship condition.

Will update the progress here.

Thanks

**Comment by WHITE-developer** [comment]
@lukeholder Any update on this in which release it would be in.

Starting another shop, so have to decide if we can go the full entry way or need to stick with the categories

**Comment by lukeholder** [comment]
I was just finishing the feature up at the moment, and it will likely be in 4.3 but I can't give an accurate estimate on when that will be out just yet.

**Comment by lukeholder** [comment]
This was completed in Commerce 4.3.0
