### ISSUE TITLE
craft.orders.customer returns active and inactive carts under the orders pages

### ISSUE THREAD

**Issue by mattcheww** [craftcms/commerce#314]
### Description
It appears that `craft.orders.customer(craft.commerce.customers.customer).all()` returns not only completed orders, but both active and inactive carts. I am still using the original templates included in the `templates/shop` directory. On the customer page if you click on an uncompleted order, then it just redirects you back to the customer page.

I thought maybe I might need to add the completed parameter, but the documentation mentions that the customer parameter does not include orders that are still carts. 

### Steps to reproduce

1. Use the example templates, or just use `craft.orders.customer(craft.commerce.customers.customer).all()` on a templates somewhere.
2. Add items to cart, but don't check out
3. Visit `/shop/customer` - This is where I found the uncompleted orders. 

### Additional info

- Craft version: Craft Pro 3.0.1
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins & versions:
   - Craft Commerce - 2.0.0-beta.1.3
   - Redactor - 1.1.0
   - Stripe for Craft Commerce - 1.0.0

**Comment by lukeholder** [comment]
Sorry the docs were out of date with that change. I have updated the docs to explain here:

https://github.com/craftcms/commerce-docs/blob/v2/en/changes-in-commerce-2.md#query-changes
