### ISSUE TITLE
[4.x]: Single line postcode formula input can break formulas added in Craft3

### ISSUE THREAD

**Issue by chrismou** [craftcms/commerce#3147]
### Description

I've just noticed the postcode formula box in shipping zones has changed from a textarea to a single line input in Craft4

There's a couple of issues here, especially when dealing with complex rules. One is that a textarea allowed us to format the rule with spacing and multi lines to make it more readable, eg:

![image](https://user-images.githubusercontent.com/319883/233116007-4285e0cb-428c-4140-b656-fe7703e74499.png)

Another, tying into this, is that the newline character is now ignored, effectively breaking the rule, eg

Craft3
![image](https://user-images.githubusercontent.com/319883/233114307-e5ee12e4-94ab-4d1e-981a-57c46291131c.png)

Craft4
![image](https://user-images.githubusercontent.com/319883/233114809-6088e8e4-5b56-45ea-9b1f-76cd4bcba1cc.png)

Note the lack of space now between the closing bracket and the OR.  This works for now because I assume it's still saved with the newline, but I would guess that if I now hit save, it would strip out newline and the rule would break

I appreciate that these could be reformatted, but it'll just make life a lot more difficult for the next developer who's asked to make a "quick change" to the formula :sweat_smile: 

Is there any way this could be changed back to a textarea?

### Craft CMS version

4.x

### Craft Commerce version

4.x

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for reporting this, I will take a look and let you know how we can improve the situation.

**Comment by lukeholder** [comment]
Thanks for reporting. This will be fixed for the next release. I will let you know here once it's out later today.

**Comment by lukeholder** [comment]
This was fixed in 4.5.3 thanks!
