### ISSUE TITLE
[3.x]: Security vulnerability with DOMPDF < 2.0.2 ?

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/commerce#3153]
### What happened?

We are currently seeing the following in Terminal after running `composer update` on systems running Composer ^2.4. 
Looks like Commerce 3 runs DOMPDF 1.x and only Commerce 4 is on the ^2.x branch?

Unsure how much of a genuine issue this is but wanted to flag it for review because "security vulnerabilities" and sites that take money aren't a confidence inspiring combination. Especially if one is an "SSR forgery" and another is "remote file inclusion".

![Screenshot 2023-04-27 at 10 47 39](https://user-images.githubusercontent.com/814039/234829266-45ff64ba-5b4a-4d18-b249-6634f949e683.png)

### Craft CMS version

3.8.8

### Craft Commerce version

3.4.20.1

### PHP version

7.4

**Comment by pdaleramirez** [comment]
PR pending: https://github.com/craftcms/commerce/pull/3135

**Comment by lukeholder** [comment]
Commerce 3.4.21 is now out and requires Dompdf 2.0+ 

Thanks for reporting.
