### ISSUE TITLE
User Not permitted when trying to update a subscription [3.x]: 

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce#3155]
### Description
When a user tries to update a subscription form on their front-end, we are seeing the following error:
**User Not permitted**
<img width="1833" alt="Screenshot 2023-05-03 at 09 57 38" src="https://user-images.githubusercontent.com/5698596/235873525-64d18a77-7be9-46f9-a216-1cac756785c8.png">

At the moment this is implemented on the `_includes/sprig/subscriptions/sprig-manage-addresses.twig` partial. 
But essentially it uses the following Craft Commerce Subscription code and subscriptions/save controller.
```
 <form id="subscriptionAddressesForm" method="POST">
    {{ csrfInput() }}
    {{ hiddenInput('action', 'commerce/subscriptions/save') }}
    {{ hiddenInput('subscriptionId', subscriptionId) }}
    {{ hiddenInput('fields[subscriptionBillingAddressId]', billingAddress) }}
    {{ hiddenInput('fields[subscriptionShippingAddressId]', shippingAddress) }}
    {% if redirectUrl %}
      {{ redirectInput(siteUrl(redirectUrl)) }}
    {% endif %}
 ```

This action does work if I am logged in as an admin user. But we need this functionality for customer users. 

### Craft CMS version

Craft Pro 3.8.7

### Craft Commerce version

3.4.20.1

### PHP version

8.0.28

### Database type and version

MariaDB 10.4.28

### Installed plugins and versions

-

**Comment by terryupton** [comment]
By setting the customers user group to enable 'manage subscriptions', seems to have resolved this.
<img width="532" alt="Screenshot 2023-05-03 at 11 28 37" src="https://user-images.githubusercontent.com/5698596/235892360-f5f1e976-904d-4ec4-baf6-3a80fa415c49.png">

**Comment by lukeholder** [comment]
One shouldn't have to create permissions for a customer to edit their custom fields. Looking into it now.

**Comment by lukeholder** [comment]
We have fixed this for the next release of commerce; a customer can now update (switch, cancel, reactivate etc) a subscription if they are the owner of the subscription and it’s a front-end request. Otherwise, the normal permissions will apply.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#1c34c5438feef79d2cd21acd30e8cf462178f7c4 as 4.2.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by terryupton** [comment]
Thanks @lukeholder and @nfourtythree 
Is this only Commerce 4? As the client tis on Commerce 3. Will this be ported back to 3 as well?

**Comment by ryanirelan** [comment]
This also closes this discussion: https://github.com/craftcms/commerce/discussions/3105

And my PR for fixing the docs, since I was told this was expected behavior. https://github.com/craftcms/docs/pull/490
