### ISSUE TITLE
State value not being passed correctly

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#316]
### Description
I was working through the updates to how addresses are handled in the cart, and I couldn't figure out why I couldn't get past the Addresses step during checkout. I flipped over to the example templates and ran into the same problem. It appears like even though a state and country are selected, the state isn't being passed correctly. I dumped out all the cart errors and got the following:

```
array (size=1)
  'shippingAddress.stateValue' => 
    array (size=1)
      0 => string 'Country requires a related state selected.'
```

### Steps to reproduce

Screencast: https://drive.google.com/file/d/1gyGBaOIOidIRb47puQXzVmX6IWDWqlRB/view?usp=sharing

### Additional info

- Craft version: Craft Pro 3.0.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Commerce at 5c5b142f6f4f1991401a385d45850c736dd60d1e

**Comment by lukeholder** [comment]
Thanks for reporting, working on a fix now.

**Comment by davist11** [comment]
I'm still seeing this issue when I try and checkout with the provided sample templates: https://github.com/craftcms/commerce/tree/develop/templates/shop

**Comment by echantigny** [comment]
@lukeholder I'm still seeing this exact same issue on 2.0.0-beta.8 .  The commit assigned to the closed has nothing to do with this issue either, targeting a change in an admin setting page template.

@davist11 Did you get through this?  I'm trying to figure it out but everything seems to be set properly and there isn't any doc about the stateValue field that I could find.

**Comment by davist11** [comment]
I updated the `<select name="address[stateValue]">` to be  `<select name="address[stateId]">` and that appeared to have fixed the problem

**Comment by echantigny** [comment]
This does fix the issue for me too.  Changed back to "Require a state" for the Country and changed stateValue for stateId.

Requires an update to the template
\craftcms\commerce\templates\shop\_includes\addresses\form.html

It doesn't explain why the address[stateValue] name was working if "Require a state" was not checked though.

**Comment by lukeholder** [comment]
Thanks guys, will look into it more.
