### ISSUE TITLE
[4.x]: UI bug: Tabs not switching via dropdown in the "Promotions" settings

### ISSUE THREAD

**Issue by Romanavr** [craftcms/commerce#3162]
### Description
![изображение](https://user-images.githubusercontent.com/3519951/235991393-d79488e1-3dbb-4ed8-b1fe-960d24c1f482.png)
It's not possible on the small screens, in the "Promotions" settings(in the CP) switch tabs via dropdown.
Was able reproduce it only for the "Promotions" section on a few different sites with the different commerce 4.x versions.

### Steps to reproduce
1. Go to, for example, Sales settings -> site.com/admin-url/commerce/promotions/sales/new
2. Reduce window size and try to switch tabs using dropdown.

### Expected behavior
It should switch tabs I guess

### Actual behavior
This does not work and throws error in the console: `Uncaught Invalid tab ID`
![изображение](https://user-images.githubusercontent.com/3519951/235994116-703b73c2-9a28-4bd4-a7d5-2a0b7145c2f4.png)

### Craft CMS version

4.4.6.1

### Craft Commerce version

4.2.6

### PHP version

8.1

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@Romanavr Thank you for reporting. I was able to replicate this issue and added a PR fix for this here https://github.com/craftcms/commerce/pull/3166

We’ll add the fix on the next release.

**Comment by lukeholder** [comment]
This was fixed in Commerce 4.2.9. Thanks for reporting it.
