### ISSUE TITLE
[4.x]: Soft-deleted order statuses are not correctly restored when applying the project config

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/commerce#3164]
### Description

Looks like restoring an order status that was previously soft-deleted in the database doesn't work correctly. I created an order status, opened a PR, then went back to another branch and ran `project-config/apply`, which soft-deletes the order status in the database by setting the `dateDeleted` in the `commerce_orderstatuses` table. After going back to the branch with that order status and running `project-config/apply` again, the order status was not restored. I checked the database, and the row still included the `dataDeleted`. Manually setting that value to `NULL` caused the order status to show up again.

### Steps to reproduce

1. Create a new order status.
2. `git stash --include-untracked` all changes in the `config/` folder and apply the project config. This marks the order status as soft deleted in the database.
3. `git stash pop` to get back the config. Apply the project config again.
4. The order status should be visible again, but it isn't, because it's still soft-deleted in the database.

### Expected behavior

Applying the project config should properly restore soft-deleted order statuses.

### Craft CMS version

4.4.7.1

### Craft Commerce version

4.2.7

### PHP version

8.2

### Database type and version

MySQL 8.0

**Comment by pdaleramirez** [comment]
@MoritzLost The order status project config does not yet listen to the restored order status. This is the reason why the database record was not updated. On the latest version, it only updates the database to on update and on remove order status.

**Comment by lukeholder** [comment]
@MoritzLost Thanks, I am looking at this issue again now and will get back to you soon. Thanks.

**Comment by lukeholder** [comment]
This is fixed for the next release of Commerce. I will update this ticket once it is out.

To get the fix early (if you are on Commerce 4), change your `craftcms/comerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#371ab4661cae8922eeda9b4a7ef9bad60a651de4",
  "...": "..."
}
```

Then run `composer update`.

You can also wait for the next official release. Thanks.

**Comment by MoritzLost** [comment]
@lukeholder Thanks Luke!
