### ISSUE TITLE
[4.x]: Different pdf orientation per pdf

### ISSUE THREAD

**Issue by JoeriE** [craftcms/commerce#3168]
### Description

I've a setup with two downloadable PDF's per order. Although, one PDF needs to be in landscape mode and the other one in portrait. Right now the default setting is set in the settings. But I would like to overwrite this setting per PDF. Is this possible?

I was looking at the Before Render PDF event, but can't seem to change this setting there.
```
        Event::on(
            Pdfs::class,
            Pdfs::EVENT_BEFORE_RENDER_PDF,
            function(PdfRenderEvent $event) {
                // Change PDF orientation to landscape here?
            }
        );
```

Thanks!

### Craft CMS version

4.4.7.1

### Craft Commerce version

4.2.7

**Comment by pdaleramirez** [comment]
@JoeriE Similar issue here https://github.com/craftcms/commerce/issues/3146#issuecomment-1519359590. You’ll be able to try out the solution given.
