### ISSUE TITLE
[4.x]: hasUnlimitedStock is incorrect in some situations

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/commerce#3169]
### Description

We're facing a weird issue where `$product->defaultVariant->hasUnlimitedStock` incorrectly returns `false` when it should return `true`. The product edit form shows the checkbox for unlimited stock as checked. This only occurs for some products, not for all. We also can't reproduce it in a development environment, but it happens consistently in the production environment. I tried deleting the product and creating a new product with the same values, but I'm getting the same error.

I also tried to query the product using `php craft shell`:

```
> $product = \craft\commerce\elements\Product::find()->id(8514)->one();
= craft\commerce\elements\Product {#6172
…

> $product->hasUnlimitedStock;
= true

> $product->defaultVariant->hasUnlimitedStock;
= true

> $product->defaultVariant->stock;
= 0
```

Curiously enough, the `hasUnlimitedStock` returns the _correct_ result in the console context. But in a web request, it definitely returns the wrong result – I put `Craft::dd($this->hasUnlimitedStock)` inside `Variant::getIsAvailable()` (which is the method we're using to check if the product is available). Sure enough, this dumps `false`.

Furthermore, the issue _only_ occurs in our custom controller endpoint that is used for checkout. We have a product type `event` which uses this custom controller endpoint for event registrations (purchases). To ensure the event is available (using the stock, availability settings and some custom logic), we have added a `SeminarBehavior` to the `Product` class with a method `isAvailableForBooking()`:

```php
public function isAvailableForBooking(): bool
{
    $this->ensureIsSeminar();
    /** @var Product $product */
    $product = $this->owner;

    return $product->defaultVariant->getIsAvailable()
        && !$product->isFullyBooked();
}
```

`$product->defaultVariant->getIsAvailable()` returns `false` here, because `$product->defaultVariant->hasUnlimitedStock` yields `false` even though it should be true. But the same method (`isAvailableForBooking()`) returns the _correct_ result when we call it in the Twig template. It only returns the wrong result when called from our custom controller in a POST request.

I'm really confused as to what might be causing this, or how to reproduce or debug this. Any ideas?

### Steps to reproduce

No idea, unfortunately. We're using the [event hook mentioned here](https://craftcms.stackexchange.com/questions/40733/set-default-values-for-new-commerce-products) to set default values for new products – could it be related to that? Are we doing something wrong there?

### Expected behavior

`$product->defaultVariant->hasUnlimitedStock` should return the correct result, as should `$product->defaultVariant->getIsAvailable()`.

### Actual behavior

The method returns the incorrect result in some contexts.

### Craft CMS version

4.4.7.1

### Craft Commerce version

4.2.7

### PHP version

8.2

### Database type and version

MySQL 8.0

**Comment by MoritzLost** [comment]
Ok, I'm doubting my sanity. This issue occurs exactly when the `postDate` of the product is set to 2023-03-30 or earlier. If I set it to 2023-03-31 or anything after that, the availability check returns the correct result. When I set it to the 30th or any date before that, it returns the incorrect result. Any ideas what is happening here? Is there any kind of check related to the `postDate` that might influence `hasUnlimitedStock`? I'm completely at a loss here …

**Comment by pdaleramirez** [comment]
@MoritzLost would you be able to send the module with the custom controller including the database of your project to support@craftcms.com? We’ll try to replicate the issue.

**Comment by MoritzLost** [comment]
@pdaleramirez Sorry for the late reply, I was really busy the last weeks. Unfortunately (or maybe fortunately) I can't reproduce this error now. The events that were previously unavailable now work as expected. Really awkward – there was definitely something going wrong there. Since it seemed related to the `postDate`, I think it's likely that it's an edge-case that somehow depends on the `postDate` and the current time … though, I really can't imagine how this might influence the stock fields.

Anyway, I'll close this issue since I can't reproduce it any more. Will reopen in case it happens again.

**Comment by MoritzLost** [comment]
I finally figured out what was causing this issue. The controller checked the wrong product because I was using `ProductQuery::hasVariant()` incorrectly, and unsupported parameters are silently dropped instead of throwing an error, so I didn't find that error. Opened a new issue regarding that: https://github.com/craftcms/commerce/issues/3189
