### ISSUE TITLE
Variants Fields don't show if the product type doesn't have any fields

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#317]
### Description
When creating a product type that has variants, if that product does not have any fields associated with it in the field layout it causes a bug where you are unable to save the product or see the variants field

### Steps to reproduce

1. Create new product type
2. Select has variants
3. Add a custom field to variants layout but not the product layout
4. Go to add a new product of that type

### Additional info

- Craft version: 3.0.1
- PHP version: 7.0.28
- Database driver & version: mysql 5.5.59
- Plugins & versions: 
	- Amazon S3	1.0.8
	- Asset Rev	6.0.0
	- AsyncQueue	1.3.0
	- Craft Commerce	dev-develop
	- HTTP2 Server Push	1.0.0
	- ImageOptimize	1.4.24
	- Minify	1.2.8
	- Postmark	1.0.0-rc.1.2
	- Redactor	1.0.1
	- SEOmatic	3.0.0-beta.16
	- Typed link field	1.0.7
	- Typogrify	1.1.9

**Comment by nfourtythree** [comment]
Hi @lukeholder 

I believe I am up-to-date on `2.0.0-beta.1.3`, the following is the contents of the `composer.json` file in `vendor/craftcms/commerce/composer.json`

```
{
  "name": "craftcms/commerce",
  "description": "Craft Commerce",
  "type": "craft-plugin",
  "version": "2.0.0-beta.1.3",
  "keywords": [
    "cms",
    "craftcms",
    "commerce",
    "yii2"
  ],
  "homepage": "https://craftcommerce.com",
  "license": "proprietary",
  "support": {
    "email": "support@craftcms.com",
    "issues": "https://github.com/craftcms/commerce/issues?state=open",
    "forum": "https://craftcms.stackexchange.com/",
    "source": "https://github.com/craftcms/commerce",
    "docs": "https://github.com/craftcms/docs",
    "rss": "https://github.com/craftcms/commerce/releases.atom"
  },
  "require": {
    "craftcms/cms": "^3.0.0",
    "dompdf/dompdf": "~0.8.2",
    "moneyphp/money": "^3.1.3",
    "dannyvankooten/vat.php": "^1.1.2"
  },
  "autoload": {
    "psr-4": {
      "craft\\commerce\\": "src/"
    }
  },
  "extra": {
    "handle": "commerce",
    "name": "Craft Commerce",
    "description": "An amazingly powerful and flexible e-commerce platform for Craft CMS.",
    "developer": "Pixel & Tonic"
  }
}
```

Seems to have the correct, version number etc. 

Do you think it might be worth nuking it and going again? Luckily I am at a stage where that won't affect me greatly.

Keep u the good work!

**Comment by lukeholder** [comment]
Sorry just saw `Craft Commerce	dev-develop` in your opening post.

I can reproduce, will get a fix out soon.

**Comment by lukeholder** [comment]
Fix will be in the next release.
