### ISSUE TITLE
[4.x]: Lots of coupons make page really show

### ISSUE THREAD

**Issue by JoeriE** [craftcms/commerce#3170]
### Description
I have a discount with 500+ unique coupon codes. Loading this tab takes a really long time and once loaded the page feels really slow. It would be great to have some kind of pagination and search here.

Best wishes,
Joeri

### Craft CMS version

4.4.7.1

### Craft Commerce version

4.2.7

**Comment by nfourtythree** [comment]
Hi @JoeriE 

Thank you for bringing this to our attention. I have managed to replicate the issue, on first glance it appears to be an issue with the underlying JS (that comes from Craft).

We will look into this, see if we are able to get a fix in place and let you know of any updates.

Thanks!

**Comment by nfourtythree** [comment]
Hi @JoeriE 

Sorry for the delay in reply on this. This issue was resolved in version `4.4.0` of Commerce.

Thanks!
