### ISSUE TITLE
Order view: "Send Email" button options not translatable

### ISSUE THREAD

**Issue by jakobhaerter** [craftcms/commerce#3172]
### What happened?

We've defined several email templates in Commerce. All of them are sent automatically, but editors can also trigger them manually. Unfortunately, it's not possible to translate `Send the "[name of email template]" email` options ([it's hardcoded in Vue](https://github.com/craftcms/commerce/blob/develop/src/web/assets/commerceui/src/js/order/apps/OrderSecondaryActions.vue)).

I'd suggest removing the entire string and just using the email template name, just like the `Download PDF` button options.

### Craft CMS version

4.4.7.1

### Craft Commerce version

4.2.7

### PHP version

8.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @jakobhaerter 

Thank you for bringing this to our attention. We have pushed a fix for this which will be included in the next release of Commerce.

Thanks!

**Comment by jakobhaerter** [comment]
@nfourtythree Awesome, thank you guys! ✨
