### ISSUE TITLE
[4.x]: Custom twig filter not available in PDF template

### ISSUE THREAD

**Issue by freder** [craftcms/commerce#3187]
### Description
I define custom twig filters in a module. they work fine on regular pages. however, when I try to generate an invoice pdf with a template that uses one of my filters, the pdf only says `An error occurred while generating this PDF`.

log:

```
2023-06-05 14:30:33 [web.ERROR] [Twig\Error\SyntaxError] Twig\Error\SyntaxError: Unknown "maxNumSeats" filter. in /var/www/html/templates/receipt-pdf.twig:167
Stack trace:
#0 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(560): Twig\ExpressionParser->getFilterNodeClass('maxNumSeats', 167)
#1 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(545): Twig\ExpressionParser->parseFilterExpressionRaw(Object(Twig\Node\Expression\GetAttrExpression))
#2 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(403): Twig\ExpressionParser->parseFilterExpression(Object(Twig\Node\Expression\GetAttrExpression))
#3 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(286): Twig\ExpressionParser->parsePostfixExpression(Object(Twig\Node\Expression\GetAttrExpression))
#4 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(175): Twig\ExpressionParser->parsePrimaryExpression()
#5 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(70): Twig\ExpressionParser->getPrimary()
#6 /var/www/html/vendor/twig/twig/src/Parser.php(127): Twig\ExpressionParser->parseExpression()
[...]
```

looks like custom twig filters are not available.

### Craft CMS version

4.4.13

### Craft Commerce version

4.2.10

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@freder how are you registering your extension?

**Comment by freder** [comment]
@lukeholder can you reproduce the issue?

**Comment by freder** [comment]
or what is the recommended work-around here? – using https://craftcms.com/docs/commerce/4.x/extend/events.html#beforerenderpdf to do everything upfront and then passing the results to the template?

**Comment by lukeholder** [comment]
@freder sorry for the delay on this one.

Can you remove this contdition so that you register your extension in all contexts?

`if (Craft::$app->request->getIsSiteRequest()) {`

**Comment by lukeholder** [comment]
I am closing this as stale. Please create a new issue if the problem persisted after suggested advice. Thanks.

**Comment by freder** [comment]
that worked – thank you!
