### ISSUE TITLE
[4.x]: aria-label typo

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3188]
### What happened?

Misspelled `aria-label` attribute:

https://github.com/craftcms/commerce/blob/19f3687bbbdb4e237c138fec627bc212ca883e68/src/templates/products/_edit.twig#LL96C58-L96C68

### Craft CMS version

4.4.13

### Craft Commerce version

4.2.10

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks fixed for next release!
