### ISSUE TITLE
[4.x]: hasVariant unexpectedly drops unsupported parameters

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/commerce#3189]
### Description

I just found out that `ProductQuery::hasVariant()` _only_ supports passing in a `VariantQuery`, not a variant ID or array of IDs. I assumed `hasVariant()` supports passing in IDs (because this is what I would expect), so I was using the parameter incorrectly:

```php
use craft\commerce\elements\Product;

$variantId = 123;
$product = Product::find()->hasVariant($variantId)->one();
```

This error is on me since the documentation clearly states that the `hasVariant` method _only_ supports passing in a `VariantQuery`. However, the issue is that any unsupported value that is passed in to this method is _silently dropped_ instead of throwing an error. This can be seen here: https://github.com/craftcms/commerce/blob/develop/src/elements/db/ProductQuery.php#L912-L919

If `$this->hasVariant` isn't a `VariantQuery` or an array, the method just returns, causing the parameter to be silently dropped. Instead of returning, an error should be thrown in line 918 to indicate to the user that they have passed in an unsupported parameter. This could also be done in the `ProductQuery::hasVariant` method. Silently dropping unsupported parameters instead of throwing an error is a huge antipattern, this just caused me hours of frustrating debugging.

### Expected behavior

Passing an unsupported parameter to `ProductQuery::hasVariant` should throw an error.

### Actual behavior

Unsupported parameters passed to `ProductQuery::hasVariant` are silently ignored.

Also, if it's possible, allowing an ID or array of IDs to be passed to `ProductQuery::hasVariant` would be great.

### Craft CMS version

4.4.7.1

### Craft Commerce version

4.2.7

### PHP version

8.2

**Comment by lukeholder** [comment]
Thanks for reporting this. I have fixed it for the next release.

**Comment by MoritzLost** [comment]
@lukeholder Thanks!
