### ISSUE TITLE
Clarification on user logins, carts, and update-cart action

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#319]
### Description

We have a checkout form that uses ajax to submit cart details and also create/login guest customers. When a user lands on the checkout page they are logged-out and presumably a Guest user. Then, we ask them to add their email and password, which we submit via ajax to the `users/save-user` method. This returns successfully with the new user id.

Then the user continues to fill out various address and payment fields and submits their order. The payment returns an error "No customer email address exists on this cart."

At that point, when the page has been reloaded, the user is now logged in. If they fill out address and payment fields and submit, everything seems to work.

My conclusion is that after creating a new user via ajax, the `commerce/cart/update-cart` method is returning a different response than the response after the page has been reloaded. Hypothetically, the `update-cart` method should be the same JSON response, but maybe I'm thinking about it incorrectly?

Here are the two responses compared with a few noticeable differences: https://cl.ly/372t2I1Y0I2k

Here's a video of the problem: https://cl.ly/1o101w371k0C

### Steps to reproduce

1. Described above and shown in video

### Additional info

- Craft version: 3
- PHP version: 7.1
- Database driver & version: Maria
- Plugins & versions:

**Comment by bryantAXS** [comment]
@lukeholder any thoughts on this one? I'm happy to keep investigating or provide other info if need be. Thanks!

**Comment by bryantAXS** [comment]
Hey @lukeholder any update on this one?

**Comment by chrisfarnold** [comment]
Hey @lukeholder checking in - thanks.

**Comment by bryantAXS** [comment]
Yep, after the page refreshes everything works correctly. We have a temp workaround in place now to simply reload the page after they create their account.

**Comment by lukeholder** [comment]
OK, this is expected behaviour. If you log in, the cart is no longer a guest and the email address and personal addresses are cleared from the cart.
