### ISSUE TITLE
Graphql full crud operations discussion

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/commerce#3191]
### What happened?

Discussion: https://github.com/craftcms/commerce/discussions/2350
-----
Hello everyone,
I don't want to be rude but a year has already passed since the opening of this discussion and an answer has not yet been found. Everyone is asking when the gql full crud operations will be available for the commerce plug-in.
Wh yplugin price is so high then if you event don't have the basic operations as default? And as a plus you must code by yourself all the operations?
How much. we need to wait for these changes??
Thanks.

### Craft CMS version

Craft Pro 4.4.13

### Craft Commerce version

4.2.11

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for raising it for us to address, I have responded in the discussion: https://github.com/craftcms/commerce/discussions/2350
