### ISSUE TITLE
beforeAddToCart event existence and usage

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#320]
### Description
Looking through the [Changelog](https://github.com/craftcms/commerce/blob/develop/CHANGELOG-v2.md) I notice there is a reference to the `beforeAddToCart` event. But I can't find in that file the constant (that provides the string) to be able to reference it in a custom module or plugin.

---

#### Reference from Changelog
`craft\commerce\services\Carts` now fires the following events: `beforeAddToCart`, `afterAddToCart`, `afterRemoveFromCart` and a cancelable `beforeRemoveFromCart` event.

---

Is this because it has yet to be implemented or am I just missing something obvious ("wood for the trees" situation)?

### Additional info

- Craft version: 3.0.1
- PHP version: 7.0
- Commerce version: 2.0.0-beta.2

**Comment by nfourtythree** [comment]
I don't know if this helps or not but tracking the code through it looks like all of the add to cart functionality is mostly contained within the [actionUpdateCart](https://github.com/craftcms/commerce/blob/develop/src/controllers/CartController.php#L126) method in the Cart controller.

Would that then make sense that the `beforeAddToCart` event is likely to be called on lines [141](https://github.com/craftcms/commerce/blob/develop/src/controllers/CartController.php#L141) and [153](https://github.com/craftcms/commerce/blob/develop/src/controllers/CartController.php#L153)

Obviously, this is all based on assumptions without knowledge of work done outside of what is available on GitHub and your plans. Just thought this could help and if the above was the case I could look at creating a pull request

**Comment by andris-sevcenko** [comment]
@nfourtythree as a rule of thumb events are fired either by a service or an element. If events were fired in controllers, then another plugin just calling the service would avoid triggering those.

For what it's worth, the events were lost in ["The Great Commerce Cart Refactor"](https://github.com/craftcms/commerce/commit/81caa99a763a757a23eb5975aa32c0238c5a20b4#diff-d9adb9314b4d1e091e4ab4c16085678cL152).

Thanks for the offer, but it's probably best left to @lukeholder to have a look and add them back in, as he was the driving force behind that refactor.

**Comment by nfourtythree** [comment]
@andris-sevcenko yea it makes the most sense that events should be fire by a service or element. I made the suggestion as actually the add to cart process doesn't _currently_ live in either a service or an element.

I love that it has a specific name 🤣. 

Yea the offer is there as I would much rather be a help while I am working on a Commerce related project rather than be _that_ annoying person tapping his watch saying "have you done my bug/request yet?"

**Comment by lukeholder** [comment]
@nfourtythree I plan to add back events for adding line items to the cart, but it would be good to know your use-case. Line items can be added to the cart now that are not valid, but they get errors added to them during order validation.

Are you migrating from a Commerce 1 install and looking for the exact same functionality? What will your event listener code do?

**Comment by nfourtythree** [comment]
Hey @lukeholder 

Simply (or not so simply) it is member based pricing (Retail pricing through to 9 other separate levels). So I need the event so I can catch the add and fetch & swap the price that Commerce gets from the variant for the "actual" price.

Unfortunately, due to their product pricing structure, this isn't something that can be done with discounts or similar.

Although now I have actually typed this out I am wondering if this is something achievable with a custom adjuster? 🤔

**Comment by lukeholder** [comment]
@nfourtythree 

I have gone ahead and added the afterAddLineItemToORder event 06641db27519c4c2a1ec8c702 This would allow plugins to listen to when a line item is added.

BUT, this would not allow you to change the price of the line item (it wasn't the right place in Commerce 1 either)

You are best to hook into the line item services: `LineItems::EVENT_POPULATE_LINE_ITEM` event.

There you could change the `saleAmount` and `price` of the line item.

Hope that helps.

**Comment by nfourtythree** [comment]
Cool thanks @lukeholder this sounds like the ticket (having just peeked into the code), and my assumption is that `populateFromPurchasable` is only called during the add process? Obviously, don't want to be changing that data at other points
