### ISSUE TITLE
[4.x]: Huge amount of discounts make add to cart extremely slow

### ISSUE THREAD

**Issue by JoeriE** [craftcms/commerce#3202]
### What happened?

I have 100 000+ coupons in my shop. I know that's a lot but the client has a lot of unique discounts for Winback, Abandoned Cart Leads, After first order, ... and all of them need to be unique codes. 

I use javascript to add them to the cart via commerce/add-to-cart and it takes up to 12 seconds. When disabling all the discounts, it only takes up to 800ms. It really starts to get slower after 30 000 active coupons.

Is there a way to optimize this?

Thanks!

### Craft CMS version

4.4.13

### Craft Commerce version

4.2.11

**Comment by lukeholder** [comment]
Hi @JoeriE thanks for reporting.

Could you send your DB dump and composer.json to support@craftcms.com and we will take a look and try to reproduce.

Thanks!

**Comment by lukeholder** [comment]
I am closing this ticket as I do not believe we received the DB in support. If this is incorrect, please create a new ticket in GitHub and reference the email support ticket number so we can follow up. Thanks.
