### ISSUE TITLE
[4.x]: There is no `commerce/cart/forget-cart` REST endpoint

### ISSUE THREAD

**Issue by freder** [craftcms/commerce#3206]
### Description
There should be a way to forget a cart via the REST API.

### Craft CMS version

4.4.14

### Craft Commerce version

4.2.11

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks, this has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#4b315f6d48e4138559826af0eccc62ea5cf6c165 as 4.2.11",
  "...": "..."
}
```

Then run `composer update`.
