### ISSUE TITLE
[3.x]: adding items to cart gets slower the more items are in the cart.

### ISSUE THREAD

**Issue by hhentschel** [craftcms/commerce#3207]
### Description
Adding items to cart gets slower the more items are being added.

Around the first 5 items the loading time stays about the same, but then it gets slower and slower.
Especially after 10 items in the cart it is noticeable slower, by then it takes ~10s to add a product to the cart.
Using sprig to add items to the cart, but this should'nt have any affect.

There are ~50 discounts in the store.

Similar to issue [here](https://github.com/craftcms/commerce/issues/1323)

Sending db dumb and composer.json and composer.lock file to support@craftcm.com
with link to this issue.

### Craft CMS version

3.8.13

### Craft Commerce version

3.4.21

### PHP version

7.4.21

### Operating system and version

Darwin 22.3.0

### Database type and version

MySQL 5.7.34

### Image driver and version

Imagick 3.4.4 (ImageMagick 6.9.6-2)

### Installed plugins and versions

Back In Stock | 1.4.4
Blitz | 3.12.9
Blitz Recommendations | 1.3.0
Campaign | 1.24.1
Contact Form | 2.5.2
CP Field Inspect | 1.4.4
Datatrans for Craft Commerce | 1.0.0
Express Forms | 1.1.4
Feed Me | 4.6.3.1
Neo | 2.13.18
Redactor | 2.10.12
Retour | 3.2.10
SEOmatic | 3.4.54
Servd Assets and Helpers | 2.9.5
Snaptcha | 3.0.11
Sprig | 1.13.0
Typed link field | 1.0.25
Untransform | 1.0.2

**Comment by lukeholder** [comment]
@hhentschel Could you please send a DB dump and composer.json to support@craftcms.com with a link to this issue and we will take a look! Thanks.

**Comment by hhentschel** [comment]
@lukeholder all already sent.

**Comment by lukas-jansen** [comment]
Having a likewise issue but than in craft 4.
We have ~8k discounts and are both hitting timeouts (100sec, CloudFlare) as memory limits, both tracing back to the recalculation method and especially looping over the discounts

**Comment by hhentschel** [comment]
P&T tested it with my db dump and composer files, and the standard commerce templates,
but they could not find any performance issues. 
they asked me to test is myself with these files, but i have not had any time to do it.

my plan is to upgrade craft and commerce to v4 the next month and see whats going on then with this upgrade, because
there are some new shipping and sales improvements in v4.
maybe this helps, because right now in v3 i have some custom conditions for shipping and discounts.
please keep this ticket open.

**Comment by lukeholder** [comment]
We are working on performance improvements in this branch:

https://github.com/craftcms/commerce/pull/3221

We can see a few more opportunities and will update you all when we merge it into a release.

**Comment by lukeholder** [comment]
Closing this for now as the improvements will be in 4.3 released soon. Make a new ticket with steps to reproduce if you continue to see performance issues. Thanks.
