### ISSUE TITLE
[4.x]: Missing product type condition filter

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#3209]
### Description
When you wan't to create a custom source on the product overview, you can't filter based on product type, because this option is not available. Feels like this is a pretty crucial filter option missing when you have multiple types

### Craft CMS version

4.x

### Craft Commerce version

4.x

### PHP version

8.x

**Comment by lukeholder** [comment]
Thanks for reporting this is fixed for the next release. We will let you know when it is out soon.
