### ISSUE TITLE
Multi Add to cart adds lineItems with 0 value/qty

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#321]
### Description
When using the multi-add functionality if the `qty` inputs are blank or `0` Commerce adds a `lineItem` to the cart with `0` qty and `0` price.

### Steps to reproduce

1. Setup the multi-add functionality
2. Submit data with some quantities and some left as 0 or blank

Video of the bug: http://x.n43.me/2G1t0Y0L0d3Q

### Additional info

- Craft version: 3.0.2
- PHP version: 7.0
- Plugins & versions: Commerce 2.0.0-beta.2

**Comment by nfourtythree** [comment]
@lukeholder Have got a case for re-opening this issue.

With the update, you now can't submit a form that has rows with 0 `qty`. If you take the example code in the docs and tweak it 

```twig
<form method="POST">
  {{ csrfInput() }}
    <input type="hidden" name="action" value="commerce/cart/update-cart">

    {% for variant in product.variants %}
        <input type="hidden" name="purchasables[{{loop.index}}][id]" value="{{ variant.purchasableId }}">
        <input type="text" name="purchasables[{{loop.index}}][qty]" value="1">
        <input type="hidden" name="purchasables[{{loop.index}}][note]" value="1">
    {% endfor %}

    <input type="submit" value="Add all variants to cart">
</form>
```

Then change the first `qty` box to be 0. You get a cart error with the validation error being you can't submit something with a `qty` less than 1.

Which as a data validation rule is fine, but in practice would mean that building a project you would either need to disabled the 0 qty fields on submit, strip them from the post etc.

It would seem like in a multi-add form it is likely that qty data submitted would be a range from 0 upwards.

I know my pull request for this originally (#322) was far too simple but it was a way of not letting the data get to the point of validation.

Hope this helps, let me know if you need any more info. I came across this as my add to cart stopped working after updating

**Comment by nfourtythree** [comment]
@lukeholder any thoughts/updates on my previous comment? Wasn't sure if this was the best place to mention it or open a new issue?

**Comment by lukeholder** [comment]
Please open a new issue so I can more easily track. Thanks.
