### ISSUE TITLE
[4.3]: OrderQuery::withCustomer is useless

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#3211]
### Description
`OrderQuery::withCustomer` is pretty much useless since `Order::setEmail` already fetches the customer
```PHP
/**
 * Sets the orders user based on the email address provided.
 *
 * @param string|null $email
 * @throws Exception
 */
public function setEmail(?string $email): void
{
    if (!$email) {
        $this->_customer = null;
        $this->_customerId = null;
        $this->_email = null;
        return;
    }

    if ($this->_email === $email) {
        return;
    }

    $user = Craft::$app->getUsers()->ensureUserByEmail($email);
    $this->_email = $email;
    $this->setCustomer($user);
}
```
Because of that I have a bunch of duplicated queries and I'm not sure how to get rid of it

### Steps to reproduce

1. execute `Order::find()->customerId(1)->withCustomer()->all()`
2. think there should be none duplicate queries
3. see there are N duplicate queries for each order

### Expected behavior

1. no duplicates

### Solution to solve this:

1. do not execute `Craft::$app->getUsers()->ensureUserByEmail($email);` in case the customer is going to be eager loaded (maybe pass a parameter to the order) 

### Craft CMS version

4.x

### Craft Commerce version

4.x

### PHP version

8.2

**Comment by lukeholder** [comment]
Hi @Anubarak

This is true at the moment, you are correct, but with upcoming deprecation of setEmail this will no longer be the case. Please see the PR to follow along: https://github.com/craftcms/commerce/pull/3201

Thanks.

**Comment by Anubarak** [comment]
@lukeholder Well but the thing is: you call this function since the query for Orders still includes the email.
I can totally see what you mean but still it would be awesome if there was a way to disable this function in Commerce code.
Maybe a setting or so. Otherwise I would have to disable the line in my vendor folder in production System
