### ISSUE TITLE
[4.x]: Broken preview for products

### ISSUE THREAD

**Issue by bavodeclercq** [craftcms/commerce#3215]
### Description
The live preview feature for products in Craft Commerce is not functioning correctly. When accessing the preview, a blank screen is displayed, and in the network tab of the browser's developer tools, a 400 error is observed.

```
yii\web\BadRequestHttpException: Post request required in /var/www/html/vendor/craftcms/cms/src/web/Controller.php:465
Stack trace:
#0 /var/www/html/vendor/craftcms/commerce/src/controllers/ProductsPreviewController.php(43): craft\web\Controller->requirePostRequest()
#1 [internal function]: craft\commerce\controllers\ProductsPreviewController->actionPreviewProduct()
#2 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('preview-product', Array)
#5 /var/www/html/vendor/craftcms/cms/src/web/Application.php(304): yii\base\Module->runAction('commerce/produc...', Array)
#6 /var/www/html/vendor/craftcms/cms/src/controllers/LivePreviewController.php(121): craft\web\Application->runAction('commerce/produc...')
#7 [internal function]: craft\controllers\LivePreviewController->actionPreview('commerce/produc...', 1)
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('preview', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(304): yii\base\Module->runAction('live-preview/pr...', Array)
#12 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('live-preview/pr...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(289): yii\web\Application->handleRequest(Object(craft\web\Request))
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /var/www/html/web/index.php(12): yii\base\Application->run()
#16 {main}
```

This issue is not limited to my specific installation but can also be replicated in the "Spoke and Chain" demo. It's worth noting that the live preview of entries works correctly, indicating that the problem specifically affects the live preview of products.

### Steps to reproduce

1. Go to a product in the CP.
2. Click on the "Preview" button.

### Expected behavior
The live preview should display the product information correctly, allowing for a preview of how the product will appear on the website.

### Actual behavior
The live preview shows a blank screen, and the network tab in the browser's developer tools displays a 400 error.

### Craft CMS version

4.4.15

### Craft Commerce version

4.2.11

### PHP version

8.1.16

### Operating system and version

Linux 6.3.12

### Database type and version

MySQL 8.0.31

### Image driver and version

Imagick 3.7.0

### Installed plugins and versions

- Colour Swatches 4.3.0
- Cookies 4.0.0
- CP Field Inspect 1.4.4
- Craft Commerce 4.2.11
- Database Translations 2.2.1
- Default Dashboard 2.0.0
- Eager Beaver 4.0.2
- Elements Panel 2.0.0
- Embedded Assets 3.1.5
- Expanded Singles 2.0.1
- Feed Me 5.1.4
- Formie 2.0.32
- Hyper 1.1.8
- Image Resizer 3.0.6
- Knock Knock 2.0.10
- Mailchimp Transactional 2.0.1
- Maps 4.0.4
- Minify 4.0.0-beta.2
- Mollie for Craft Commerce 4.1.0.1
- Neo 3.8.0
- PDF Transform 2.0.1
- Preparse Field 2.0.2
- Retour 4.1.12
- Sentry SDK 2.0.1
- SEOmatic 4.0.28
- Sprig 2.6.2
- Style Inliner 3.0.3
- Super Table 3.0.9
- Typogrify 4.0.1
- Vite 4.0.6
- Vizy 2.1.6
- Sherlock 4.3.0

**Comment by bossanova808** [comment]
Yep seeing this too.  Error is: `Unable to verify your data submission.`  - live preview of everything else seems to be working fine, it's just products as far as I can determine.

**Comment by bossanova808** [comment]
Sounds about right, I've been away most of the last couple weeks but my staff mentioned they've been seeing it a while.  (Be handy if they'd told me earlier!)

Thanks Luke

**Comment by bossanova808** [comment]
What's going on with this one please?  Kind of an important piece of functionality we'd like to get working again ASAP...

**Comment by lukeholder** [comment]
Apologies for not responding here. We looked into it and this was fixed upstream in Craft CMS and the fix will be in the next Craft CMS release.

**Comment by lukeholder** [comment]
Fix is here:

https://github.com/craftcms/cms/commit/a987c99e38c93d97d5c4d7569fbbe7d5dd8ab1cb

**Comment by bossanova808** [comment]
No dramas - so the next point release, not 4.5, right?

**Comment by bossanova808** [comment]
Just confirming this is all working again for us with the latest Craft update...

**Comment by nfourtythree** [comment]
Thanks for updating us @bossanova808 !
