### ISSUE TITLE
[4.x]: 'Expiration date' blank in Subscriptions table on User

### ISSUE THREAD

**Issue by tommysvr** [craftcms/commerce#3222]
### Description
When viewing User with a subscription, the Expiration date column in the Subscriptions table of the Commerce tab is blank.

When viewing the Subscription belonging to the user, the Expiry displays properly.

Opened in the Commerce repo because it seems to be from here https://github.com/craftcms/commerce/blob/develop/src/templates/_includes/users/_customerTables.twig#L76

### Steps to reproduce

1. Subscribe to a Plan
2. Go to that User > Commerce tab > Subscriptions

### Expected behavior

Expiration date should show (assuming there is one?)

### Actual behavior

The Expiration date column is blank

![screenshot_2023_07_18 _12 12](https://github.com/craftcms/commerce/assets/867566/d02251cc-5362-4e6f-9c67-7f0c67e3edd3)

![screenshot_2023_07_18 _12 12](https://github.com/craftcms/commerce/assets/867566/d04fa5e7-fe96-418b-964a-86868a50d266)

### Craft CMS version

4.4.15

### Craft Commerce version

4.2.11

### Installed plugins and versions

- Stripe for Craft Commerce 3.1.1

**Comment by lukeholder** [comment]
This should be fixed in the latest release:

 https://craftcms.com/blog/commerce-4-3-stripe-4
