### ISSUE TITLE
[3.x]: Purchase Total Not Working

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#3223]
### Description
In the interface for Craft Commerce 3.X (and 4.X for that matter) there's a spot for **Purchase Total**.

Is this the number of line items or purchase total in dollars (or the current currency)?

![Screenshot 2023-07-18 at 9 47 21 AM](https://github.com/craftcms/commerce/assets/3707869/1f28dd0c-ace3-4083-b910-1d5135e93276)

I recently had a client setup a coupon code where they thought it was the item subtotal (in dollars) and complain that their coupon code wasn't applying.  But that doesn't seem to work. Commerce changed the value from 1500 to 1,500 which leads me to believe it's a number and not the value?

We ended up using the order condition formula for their minimum order spent and that worked.

So this is either a bug or the verbiage could stand to be a little more clear.

At least Craft Commerce 4 has the Rules builder which makes quick work of this but that same box still applies. 

### Craft CMS version

3.8

### Craft Commerce version

3.4

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @RitterKnightCreative 

Thank you for raising this point.

The Purchase Total input is localised to take into account the user's formatting preference set on their user account. This gives the user familiarity in entering a value in a format they are used to.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/nOuLXOXQ/9037d477-859f-4475-a168-4aa9b72b2d8d.png?v=f890d2220b4c5564be470355ede835c0)

In terms of the logic matching as you can see from these two sets of lines the purchase total is checked against the [item subtotal](https://github.com/craftcms/commerce/blob/develop/src/services/Discounts.php#L565-L567) (if there are no matching purchasables selected) or the against the [sum of the subtotal for the matching purchasables](https://github.com/craftcms/commerce/blob/develop/src/services/Discounts.php#L581-L593).

Hopefully, this makes sense, let us know if you need further clarification.

Thanks!

**Comment by RitterKnightCreative** [comment]
I just realized when you said matching purchasables, the client had forgotten to include another category in the match so their customer's order didn't make it over the minimum amount.

Going to close this since it's not a bug but appreciate the help @nfourtythree!
