### ISSUE TITLE
[4.4.14]: Purging pending users fails when pending users have Commerce orders

### ISSUE THREAD

**Issue by peteeveleigh** [craftcms/commerce#3239]
### Description
The Garbage Collection routine throes an Exception during the purge pending users phase if a pending user has an order.

### Steps to reproduce

1. Create and complete an order for a user who hasn't activated their account
2. Ensure the purge pending users schedule will catch this account 
3. Attempt to manually run garbage collection

### Expected behavior
The garbage collection (pending user purge) should log the problem, skip that user, and continue to purge pending users

### Actual behavior
The garbage collection (pending user purge) stops with an Exception. Thus no other pending users are purged.

### Craft CMS version

4.4.14

### Craft Commerce version

4.2.11

### PHP version

8.1.18

### Operating system and version

Linux 5.15.0-75-generic

### Database type and version

MariaDB 10.6.12

### Image driver and version

N/A

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Will tack this here: https://github.com/craftcms/cms/issues/13490
