### ISSUE TITLE
Error on saving a product that only exists for one site

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/commerce#324]
### Description
After I've programmatically created a product for only one of two sites, without propagation, like this:

`craft::$app->getElements->saveElement($product, true, false)`

... I get a `invalid product id: 165` error on saving the product from within the admin. I suppose that is because Commerce tries to save (thus, find) the product for both sites, and not finding the product for the site that it's not saved for.

I guess this comes down to the entire propagation setting not being there for Commerce product types, and therefore not needing logic that checks if a product even exists for a site.

And while we're at it, remove this dropdown on the product edit page if the product only exists for one site:

![schermafbeelding 2018-04-12 om 09 42 05](https://user-images.githubusercontent.com/6794819/38662973-ca50e790-3e35-11e8-95e3-e972c3620ce6.png)

### Steps to reproduce

1. Create two sites
2. Programmatically create a product for only one site, without propagation
3. Try to save the product from within Commerce admin section

### Additional info

- Craft version: 3.0.2
- Plugins & versions: Commerce beta.2

**Comment by lukeholder** [comment]
You can must have products that exist in all sites, you can only disable specific products in individual sites. This works the same way as categories.

do not programmatically turn off propagation when saving products.

**Comment by nilsenpaul** [comment]
Will this be possible in the future (as is the case with Craft's base element types)?

**Comment by lukeholder** [comment]
Possibly, at the moment products all belong to one store, so likely we will introduce more in-depth multi store support it will affect multi-site support.

**Comment by nilsenpaul** [comment]
Ok, thanks! Will remove `false` ;)
