### ISSUE TITLE
[4.x]: After upgrade to v4 with craft upgrade command, addresses are not transferred/saved correctly & consistently

### ISSUE THREAD

**Issue by hhentschel** [craftcms/commerce#3241]
### Description
I upgraded commerce to v4 and noticed that not all users address information is saved and transferred 
to the new address fields. 
There are some users, where everything is in the new address fields, some users have nothing. see examples.

Also what i noticed, phone numbers are not transferred at all. I know that it is not part of the new address model,
but does this mean, i have to copy all the phone numbers over by hand?
Or is there a way of having a bulk action or something similar?

correct
![Bildschirm­foto 2023-08-01 um 18 12 20](https://github.com/craftcms/commerce/assets/2101975/32ebcea0-dd27-4eb1-be1a-841370533b5d)

not correct/complete
![Bildschirm­foto 2023-08-01 um 18 11 31](https://github.com/craftcms/commerce/assets/2101975/764e5645-1301-4499-a757-32d5c89c3ba8)

### Steps to reproduce

1. after `php craft commerce/upgrade` i followed the prompts and created missing fields.

### Expected behavior

All Data should be in the new fields.

### Actual behavior

Some uers are transferred completly, some are not, only Names but no address information.

### Craft CMS version

4.4.16.1

### Craft Commerce version

4.2.11

### PHP version

8.1.1

### Operating system and version

Darwin 22.3.0

### Database type and version

MySql 5.7.34

### Image driver and version

Imagick 3.5.1 (ImageMagick 6.9.6-2)

**Comment by lukeholder** [comment]
Can you please send your pre-updated DB and compose.json and composer.lock with a list of plugins or custom modules you are using to support@craftcms.com

**Comment by lukeholder** [comment]
It is sorted through support.
