### ISSUE TITLE
[4.x]: If editor checks out with user email Craft removes permissions

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#3244]
### Description

An editor with user permissions and active Craft account checked out as guest with the his craft user email address. His account got messed up. He lost access to CP, permissions gone and account was in active.

### Steps to reproduce

1. Created a user with some permissions. Not an admin account.
2. Be signed in as the user
3. Checkout as guest using the same email as the user above.
4. Try to log in after this.
5) Log in with another account and see that the editor account is now "inactive" and no permission are set.

### Craft CMS version

4.4.13

### Craft Commerce version

4.2.9

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@philipboomy Sorry not quite understanding the steps to reproduce. How does the user checkout as guest while they are logged in?

**Comment by philipboomy** [comment]
We only do guest checkout meaning we do not create accounts after checkouts. The editor was logged in when he checked out so the email was pre-filled with his email address on the checkout page. Does that make sense? If not I can try to replicate locally.

**Comment by lukeholder** [comment]
Creating an account after checkout doesn't make it a guest checkout, guest checkout just means they are not logged in while checking out.

Please try to reproduce locally and let me know and I'll take a look.

**Comment by philipboomy** [comment]
Sorry. Was on holiday. I cannot replicate it. Tried both being logged in and not logged in but using the editor email address for the billing email. All I can do is to keep an eye on it. I know it happened as I had to recreate the permissions but there must have been something else happening at the same time as I cannot replicate it.
