### ISSUE TITLE
Unable to save products with SKUs that have been previously deleted

### ISSUE THREAD

**Issue by hellokv** [craftcms/commerce#325]
### Description

Problem: I'm receiving a validation error when creating a product with SKUs that are identical to products that have been deleted.

Expected Behavior: The unique SKU validation should only be checking against existing products, not ones that have been deleted.

### Steps to reproduce

1. Create a new product with a SKU (ex. 12345)
2. Delete the product
3. Create a new product with the same SKU (ex. 12345)
4. Receive a validation error that SKU must be unique

### Additional info

- Craft version: Craft 3
- PHP version: 7.0.28
- Database driver & version: MySQL 5.7.21
- Plugins & versions:
Algolia	1.0.0
Amazon S3	1.0.8
Asset Rev	6.0.0
Calendar	2.0.0-beta.9
Certificates	1.0.0
Craft Commerce	dev-develop
Environment Label	3.1.3
Field Manager	2.0.2
Flat Categories	2.0.0
Forms	dev-master
Freeform Pro	dev-master
Geo Cookie	1.1.1
Inlin	2.0.0
Inventory	1.0.0
Redactor	1.1.0
Sidebar Toggle	2.0.0
SimpleSentry	1.0.0
Super Table	2.0.5
Taxes	1.0.0
Twig Perversion	2.0.3

**Comment by nfourtythree** [comment]
+1 I have noticed the same issue.

**Comment by lukeholder** [comment]
@nfourtythree @hellokv working on a fix now.
