### ISSUE TITLE
[4.x]: How to reset order numbers before going live?

### ISSUE THREAD

**Issue by freder** [craftcms/commerce#3252]
### What happened?

what's the recommended procedure to reset orders before going into production? there's a bunch of test orders in the db right now and we want to have the numbering start at `1` again obviously.

there's https://github.com/craftcms/commerce/issues/581 but that won't reset the order numbers, as far as I can tell.

### Craft CMS version

4.4.17

### Craft Commerce version

4.2.11

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
You should be using the [order reference](https://craftcms.com/docs/commerce/4.x/orders-carts.html#order-reference-number) setting (that link has an example) along with the [seq](https://craftcms.com/docs/4.x/dev/functions.html#seq) function to generate a sequence number that you can reset easily.

You also have the [reset data ](https://craftcms.com/docs/commerce/4.x/console-commands.html#reset-data) command to delete all orders, subscriptions, payment sources, customers etc.
