### ISSUE TITLE
3D secure is redirecting back to home page [3.x]: 

### ISSUE THREAD

**Issue by kevadamson** [craftcms/commerce#3254]
### Description

I'm using Stripe Payment Intents

`{{ redirectInput(siteUrl ~ '' ~ entry.uri ~ '?payment=success#buy') }}`
`{{ cart.getGateway().getPaymentFormHtml({})|raw }}`

I test using the following card:

`4000000000003220` (3DS2)

It takes me to the test 3DS page, when I click authorise it takes me to my website root home page, rather than the redirect URL above. Redirect URL works when no 3DS used (for e.g. `4242424242424242`).

I'm testing on a development server with no password set for access.

### Craft CMS version

3.8.17

### Craft Commerce version

3.4.22.1

### Installed plugins and versions

- Stripe for Craft Commerce version: 2.4.4.1

**Comment by lukeholder** [comment]
Can you make sure `siteUrl ~ '' ~ entry.uri ~ '?payment=success#buy'` resolves to a working url?

**Comment by kevadamson** [comment]
@lukeholder Looks like this: `<input type="hidden" name="redirect" value="d84231cddea976a8a4d33395ccadc677309826ca71caee6a5d41febd53091f71https://thinkbigger.uk.com/courses-and-workshops/introducing-to-script-editing-with-philip-shelley?payment=success#buy">` < all good?

**Comment by kevadamson** [comment]
Is this something that is "fixed" in Craft 4 and associated plugins?

**Comment by clarisse-catacutan** [comment]
Wondering if this has been resolved? Experiencing it now after updating Stripe and Commerce. Our redirect URL looks like this `03d40e019a5b7db3028e29f3fbc44d031285830ef8bd1a6e57cba3fb330c53afhttps://stagingbiz.test.asia/shop/payment/event-credit?number=123abc&success=true`

**Comment by kevadamson** [comment]
@clarisse-catacutan Works if you include cancel input: `{{ hiddenInput('cancelUrl', '/what/evs'|hash) }}`

**Comment by lukeholder** [comment]
submitting a `cancelUrl` is required for a proper failed offsite redirect back to the correct page on your site (like the payment page).
