### ISSUE TITLE
[4.x]: Default Value of Number fields seems to be ignored

### ISSUE THREAD

**Issue by aeu** [craftcms/commerce#3262]
### Description
When a number field is created you can specify the default value.  When you add that field to a product, the default value isn't there, and instead the field is blank.

### Steps to reproduce

1. Create a new field of type Number
2. Set it's default value
3. Add that field to a Product Type
4. Go edit a product of that Type

### Expected behavior

The field should have the default value in it.

### Actual behavior

The field is blank in the admin.  If you dump it in the twig for the product on the front end, the default value isn't there either.

### Craft CMS version

Craft Pro 4.4.16.1

### Craft Commerce version

4.2.11

### PHP version

8.1.11

### Operating system and version

Linux 5.14.0-70.26.1.el9_0.x86_64

### Database type and version

MariaDB 10.5.17

### Image driver and version

GD 8.1.11

### Installed plugins and versions

Amazon S3 2.0.3
Craft Commerce 4.2.11
Formie 2.0.34.1
PayPal Checkout for Craft Commerce 2.1.2
Redactor 3.0.4

**Comment by lukeholder** [comment]
Default values on custom fields do not populate unless you save the element (product); this works the same way on Entries. You can resave all products with `php craft resave/products` which should populate the field's default.

**Comment by lukeholder** [comment]
Check out this guide: https://craftcms.com/knowledge-base/bulk-resaving-elements

It will walk you through setting a default value on the empty fields.
