### ISSUE TITLE
[4.x]: Payments controller actionPay() method does not return / use the posted redirect param in it's successful payment response

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3265]
### Description

Providing a valid redirect param as a part of the ajax request to the payments controller, results in an empty `redirect` property in the final success response, all the redirect logic for payment intents works correctly, but the final success response results in this:

<img width="795" alt="Screenshot 2023-09-06 at 17 55 31" src="https://github.com/craftcms/commerce/assets/1846063/a103eaee-1bf5-4f02-95b6-ed179b0f5550">

### Steps to reproduce

Include a redirect param in the post request to the `actionPay()` action, and although the `returnUrl` value is correctly set it is not included in the redirect property.

### Expected behavior

As per crafts new default, I would expect the asModelSuccess() method to return the provided redirect (returnUrl) values in the redirect property. For non ajax requests i would expect it to redirect to the provided redirect param and not the home page (as an empty string is provided).

### Actual behavior

Redirect string is empty.

Logic is here: https://github.com/craftcms/commerce/blob/41d24b82560acfb45c24ddbd66a75cf8e98a45ea/src/controllers/PaymentsController.php#L434

Not sure if this is the job of the gateway (we are using Stripe) or commerce (i should think the former), as if the gateway doesn't provide anything then commerce should fall back to the redirect value provided to the controller.

NB - Could possibly be down to the `asModelSuccess()` method being passed an empty string, rather than `null`, in which case it would try to grab the redirect value from the posted params.

### Craft CMS version

4.5.3

### Craft Commerce version

4.3 dev

### PHP version

8.2

### Installed plugins and versions

Abandoned Cart for Craft Commerce	2.0.4
Amazon S3	2.0.3
Craft Commerce	4.3.x-dev
Dumper	3.0.1
Elements Panel	2.0.0
Facebook Conversion	v1.2.2
Feed Me	5.2.0
Imager X	4.2.2
Linkit	4.0.4.1
Lists	4.0.1
Maps	4.0.4
Postmark	3.0.0
Ray	2.0
Redactor	3.0.4
Retcon	2.7.3
Retour	4.1.13
Scout	3.1.2
Servd Assets and Helpers	3.4.11
Sprig	2.6.2
Stripe for Craft Commerce	3.1.1
Upload	4.0.0

**Comment by lukeholder** [comment]
@samhibberd does this PR patch fix the issue? https://github.com/craftcms/commerce/pull/3269

which gateway are you using?

**Comment by samhibberd** [comment]
Perfect, that's a fix here.
We are using Stripe 3.1.1

Thanks!

**Comment by lukeholder** [comment]
@samhibberd This is now merged and will be in the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#8700421c4c0f975781b6a5fbe99ad8b808161855",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce `4.3.1` has now been released with these changes.
