### ISSUE TITLE
[4.x]: Dropdown custom field doesn't appear on an order when in "view" mode

### ISSUE THREAD

**Issue by angrybrad** [craftcms/commerce#3270]
### What happened?

* Create a Dropdown field and enter any label/value.
* Add that field to the Order field layout.
* Create an order
* When you're editing the order, the Dropdown field shows fine.

<img width="1501" alt="CleanShot 2023-09-07 at 11 33 40@2x" src="https://github.com/craftcms/commerce/assets/61869/1e1bcf9b-cce5-49f1-9b87-0cc7437004f7">

* When you're in non-edit/view mode, then Dropdown field doesn't display.

<img width="1498" alt="CleanShot 2023-09-07 at 11 39 04@2x" src="https://github.com/craftcms/commerce/assets/61869/008f0e6c-b05c-45c9-ae03-32a9dc918c6d">

### Craft CMS version

4.5.3

### Craft Commerce version

4.2.11

### PHP version

8.1

### Operating system and version

n/a

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

Just Commerce.

**Comment by jonleverrier** [comment]
related https://github.com/craftcms/commerce/issues/3258

**Comment by jonleverrier** [comment]
What would be a temporary fix for this? Create a custom asset bundle and loop through all select fields? This is causing our administrators a world of pain!

**Comment by brandonkelly** [comment]
Fixed via craftcms/cms#13754.

**Comment by brandonkelly** [comment]
Craft 4.5.7 is out now with that fix.
