### ISSUE TITLE
[4.x]: Shipping Method Options no longer allow extra properties/data

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#3271]
### What happened?

Referencing [this](https://github.com/craftcms/commerce/issues/1378) issue and the [Postie](https://github.com/verbb/postie/issues/112) plugin.

Postie registers shipping methods, that are attached with `ShippingMethods::EVENT_REGISTER_AVAILABLE_SHIPPING_METHODS`. We use our own `ShippingMethod` class that extends the Commerce `ShippingMethod` class. In this, we store information about the carrier used (like UPS), and for each rate and service returned from the API, we store additional information like estimated delivery - not just the price.

What Commerce does is grab all available shipping methods, and create `ShippingMethodOption` models. I'm not sure _why_ this is done, but it's been this way since Commerce 3.x I believe. Users then use `cart.availableShippingMethodOptions` on their shipping page.

The issue we have is that through this translation of `ShippingMethod` to `ShippingMethodOption`, we lose Postie's extra information. Despite `ShippingMethodOption` also extending from a `ShippingMethod` class, it's the _Commerce_ class that's extended, and not Postie's. As such, any reference to the extra things Postie does is lost.

Might I suggest recording the original `ShippingMethod` that was used to create the `ShippingMethodOption` be added? We could add the following [here](https://github.com/craftcms/commerce/blob/41d24b82560acfb45c24ddbd66a75cf8e98a45ea/src/elements/Order.php#L2004):

```php
$option->shippingMethod = $method;
```

Which would store Postie's shipping method against the `ShippingMethodOption` for people to access in their templates.

Other options are:
- Adding in an extra property like `data` for storing arbitrary data for a `ShippingMethodOption`
- Adding an event for creating a snapshot - similar to Products/Variants and line items

### Craft CMS version

4.5.3

### Craft Commerce version

4.2.11

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Fixed in 531a4d3c8019a87657b553d35273549d29acd7c2

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#531a4d3c8019a87657b553d35273549d29acd7c2",
  "...": "..."
}
```

Then run `composer update`.
