### ISSUE TITLE
[4.x]: Deleted shipping categories still appear in the Shipping dropdown on a product

### ISSUE THREAD

**Issue by petehjfd** [craftcms/commerce#3272]
### Description

After a shipping category has been deleted from Shipping > Shipping categories, it still appears as an option in the Shipping dropdown when adding or editing a product.

### Steps to reproduce

1. Start with a clean install of Craft 4.5.3 and Craft Commerce 4.2.11
2. Create a new product type
3. Create a new shipping category and make it available to the new product type
4. Create a new product to confirm that the new shipping category is available
5. Delete the shipping category
6. Create a new product and note that the shipping category is still available

### Expected behavior

The shipping category should no longer be available after it has been deleted

### Actual behavior

The shipping category is available after it has been deleted

### Craft CMS version

4.5.3

### Craft Commerce version

4.2.11

**Comment by nfourtythree** [comment]
Hi @petehjfd 

Thank you for bringing this to our attention.

We have pushed a fix which will be available in the next release of Commerce.

Thanks!

**Comment by nfourtythree** [comment]
Commerce `4.3.1` has now been released with these changes.
