### ISSUE TITLE
[4.x]: Delete action for edit product does not look to check permission via the Elements service to determine whether the delete button is shown in the cp

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3285]
### Description

<img width="541" alt="Screenshot 2023-09-29 at 11 12 57" src="https://github.com/craftcms/commerce/assets/1846063/fa19b38d-1caa-4e02-9c37-c7cc9da66fb0">

### Steps to reproduce

Hooked into Elements service `EVENT_AUTHORIZE_DELETE` and set`$e->authorized = false;`
`Event::on(Elements::class, Elements::EVENT_AUTHORIZE_DELETE, [ElementsHandler::class, 'authorizeDelete']);`

### Expected behavior

Delete button is hidden from the cp action menu

### Actual behavior

Delete button is not hidden from the cp action menu

PS: Works as expected with craft elements eg Entries, Categories
PPS: It does correctly enforce the permission when hitting delete

### Craft CMS version

4.5.6.1

### Craft Commerce version

4.3.0

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks. Fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#25aff01e95b575b9f93af39d2a965fde270c5233",
  "...": "..."
}
```

Then run `composer update`.

**Comment by lukeholder** [comment]
@samhibberd good catch on using the service. Will fix.

**Comment by lukeholder** [comment]
Updated the fix to use the service. Updated to commit b2d5f6d2b3eaa5f31abd2e05748b4f3681667c84 in the composer guide above.

**Comment by samhibberd** [comment]
Thanks @lukeholder

**Comment by nfourtythree** [comment]
Commerce `4.3.1` has now been released with these changes.
