### ISSUE TITLE
[4.x]: Unable to use the Customer order condition in the CP when there are large numbers of users

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3291]
### What happened?

Select the Customer condition anywhere you can filter orders and the request to load in the condition settings fails.

This is on a site with 180k+ users and caused by the `CustomerConditionRule::options()` method trying to load them all at once.

An ajax select / dropdown or User(s) element select (like used  in the Related To condition) would be great.

<img width="971" alt="Screenshot 2023-10-04 at 21 59 49" src="https://github.com/craftcms/commerce/assets/1846063/b2430a0c-214b-4d7d-b3cd-df00d6c96206">

### Craft CMS version

4.5.6.1 

### Craft Commerce version

4.3

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@samhibberd Thanks for reporting, the fix will be in the next release. We will let you know once it is out!

**Comment by nfourtythree** [comment]
Commerce `4.3.1` has now been released with these changes.
