### ISSUE TITLE
Slashes stripped from webhook URL

### ISSUE THREAD

**Issue by Stalex89** [craftcms/commerce#3299]
### Description

I'm getting the following error while using the commerce-mollie plugin with example templates for craft commerce: 
<img width="1243" alt="Screenshot 2021-01-06 at 13 27 16" src="https://user-images.githubusercontent.com/23526237/103768514-ef5ea700-5022-11eb-908b-80e0be3ef771.png">

As I see I cannot correct the webhook URL neither in CP not in config file:
<img width="1199" alt="Screenshot 2021-01-06 at 13 14 54" src="https://user-images.githubusercontent.com/23526237/103768647-2f258e80-5023-11eb-8135-782c1cd3c099.png">

The webhook URL seems strange as it missing '/' characters, also I have a different subdomain for CP and template, so I would like to change the subdomain for the webhook. 

Can you please make it possible to configure webhook URL? Thank you

### Info

PHP version: 7.3.22
Database driver & version: MySQL 5.5.46
Craft edition & version: Craft Pro 3.5.17.1

Plugins:
Craft Commerce: 3.2.13.2
Mollie for Craft Commerce: 2.1.2

**Comment by lukeholder** [comment]
@Stalex89 Thanks for that, we have fixed this in 8b892a and it will be in the next release due out soon! We will update this issue once the release is out! Thanks.

**Comment by lukeholder** [comment]
@Stalex89 This is now fixed in 4.3.1 out now. Thanks!
