### ISSUE TITLE
[4.x]: Server error triggered when trying to view trashed orders

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#3308]
### Description

When I delete an order, then try and view it in "Trashed" orders, a "Server error occurred" toast notification appears and I cannot view my trashed orders. The checkboxes next to each order become non interactive after the toast notification appears.

This process triggers an error in my log file:

```
[yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 4617 in /var/www/html/craft/vendor/craftcms/cms/src/elements/Address.php:303
```

Running `./craft gc/run` from the terminal fixes the issue, but also removes my trashed orders.

### Steps to reproduce

1. Go to Orders in Commerce
2. Delelate an order
3. Next to the search bar on the left, Change the dropdown from "All" to "Trashed"
4. A server error occurred  toast notification is triggered
5. Try selecting an order using a checkbox
6. Notice it's not possible todo this
7. Run `./craft gc/run` from the terminal and the problem is resolved

### Expected behavior

For a server error not to be triggered

### Actual behavior

A server error is triggered

### Craft CMS version

4.5.7

### Craft Commerce version

4.3.0

### PHP version

8.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @jonleverrier 

Thank you for reporting, we have been able to replicate this issue and will look to get this fixed.

We will post any updates to this issue.

Thanks!

**Comment by nfourtythree** [comment]
Hi @jonleverrier 

Again, thank you for reporting. 

We have pushed a fix to Commerce that solves this issue, the fix will be included in the next release.

It is also worth noting that there is a related fix in Craft for this as well: https://github.com/craftcms/cms/commit/6502b05e99fa588127edf55ec457ba516e896d4a

Thanks!
