### ISSUE TITLE
[4.3.1]: Calling unknown method: craft\commerce\stripe\gateways\PaymentIntents::getOldPaymentFormHtml()

### ISSUE THREAD

**Issue by joelzerner** [craftcms/commerce#3315]
### Description

When trying to "Make a Payment" for an order in the control panel, the modal shows the error below:

"Calling unknown method: craft\commerce\stripe\gateways\PaymentIntents::getOldPaymentFormHtml()"

We have Stripe payment gateways set up as well as a Manual EFT gateway.

I believe it relates to lines 916-930 of OrdersController.php. I've been able to work-around it by forcing it to always use the getPaymentFormHtml function rather than the getOldPaymentFormHtml function.

### Craft CMS version

4.5.9

### Craft Commerce version

4.3.1

### Installed plugins and versions

- Craft Commerce Stripe 4.0.1

**Comment by lukeholder** [comment]
@joelzerner Just pushed out a fix in commerce-stripe 4.0.1.1, please update the Stripe plugin which will resolve the issue. Thanks.
