### ISSUE TITLE
Guest customer orders are not being 'transferred' after customer registration

### ISSUE THREAD

**Issue by Totemika** [craftcms/commerce#332]
### Description
In the docs it says:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/4906291/39368282-14f182f8-4a31-11e8-82d6-be5764c2b539.png">

### Customer side: 
I understand that if in the template output 
` craft.orders.customer(craft.commerce.customers.customer).isCompleted(true).all()` 

I should get the customer's orders both when she was a guest and after registering but I only see the ones after registering.

**Possible solution?**: If I query by email instead, I can see the customer orders both as guest and as registered user:

` craft.orders.email(craft.commerce.customers.customer.email).isCompleted(true).all()` 

### CP side:
Also in the Control Panel, I understand the completed orders by jenny@email.com as guest should be merged (transferred) to the orders by jenny@email.com as registered user. But they are still separated users.

### Steps to reproduce

1. Checkout as jenny@email.com (guest)
2. Register user with jenny@email.com email
3. Checkout as jenny (logged in)
4. They are treated as different users, the orders are not **transferred** as the documentation says.

### Additional info

- Craft version: 3.0.3.1
- PHP version: 7.0
- Database driver & version:
- Plugins & versions: commerce 2.0.0-beta.3, commerce-stripe dev-master

Thank you

**Comment by lukeholder** [comment]
Guest orders with the same email are only merged with the customer whenever that customer logs in. Are you saying this issue persists, even after the user logs in?

**Comment by Totemika** [comment]
Yes, I think so. Another scenario:
I am already a User, Luke, with email luke@mysite.com.
1. I buy items and checkout as guest with the email luke@mysite.com
2. When I go to Luke's orders I can only see the orders Luke paid when he was logged in, but not as a guest with his email.
Does it make sense?

**Comment by lukeholder** [comment]
Yes, it makes sense. The guest orders you make while logged out are not automatically assigned to the user until that user logs in again.

If you want to manually consolidate orders at any time you can call: https://github.com/craftcms/commerce/blob/develop/src/services/Customers.php#L283
