### ISSUE TITLE
[4.x]: Limited Use Coupon Code Works With Guest Checkout

### ISSUE THREAD

**Issue by smockensturm** [craftcms/commerce#3326]
### Description

Per User Discount Limit is not honored on guest checkout.

>Limit how many times, per user, the discount is allowed to be applied. This requires a user to be logged in; guests users will not be able to use the discount.

Doesn't appeart o be true at the moment.

### Steps to reproduce

1. Check out as a guest and enter a coupon code where Per User Discount Limit is set to 1

### Expected behavior

Shouldn't be applied if Per User Discount Limit is set to 1

### Actual behavior

Discount is applied.

### Craft CMS version

Pro 4.5.9

### Craft Commerce version

4.3.1

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
I have a potential fix for this in ##3327 but will let you know once its in a release. Thanks!
