### ISSUE TITLE
Variant Modal picker

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#333]
### Description
Can we display the product title as well as the variant title in the variant model please.

If you allow to show variant titles, then you don't really know which product it belongs to. ANd if you have multiple products with variants that use the same naming format, then there is no way to tell the difference

### Additional info

- Craft version: Craft Pro 3.0.4
- PHP version: 7.1.16
- Database driver & version: MySQL 5.5.5-10.2.14-MariaDB
- Plugins & versions:

**Comment by Totemika** [comment]
can't you access the product title from the variant?
If you need a specific viewmodel you can code it in a module... Or did I misunderstand your question?

**Comment by lukeholder** [comment]
Agree in variant custom field relation modals, the product information should be shown to make it clearer which product the variant belongs to.

**Comment by AugustMiller** [comment]
If it's a simple addition here, it'd be great for the chiclets that appear in Variant relation fields (after selection) to include the Product title, as well.
