### ISSUE TITLE
[3.x/4.x]: 'Qty must be no less than 1.' reported twice for low quantity

### ISSUE THREAD

**Issue by msbit** [craftcms/commerce#3334]
### Description

Due to the rule being applied in two places:

`LineItem::defineRules`
https://github.com/craftcms/commerce/blob/3.4.23/src/models/LineItem.php#L465
https://github.com/craftcms/commerce/blob/4.3.2/src/models/LineItem.php#L420

`Variant::getLineItemRules()`
https://github.com/craftcms/commerce/blob/3.4.23/src/elements/Variant.php#L820
https://github.com/craftcms/commerce/blob/4.3.2/src/elements/Variant.php#L826

at validation time, the error is added twice.

I haven't tested the 4.x branch, but the code appears to be the same.

### Steps to reproduce

```
$lineItem = new \craft\commerce\models\LineItem([
    'purchasableId' => Craft::$app->getElements()->createElementQuery(\craft\commerce\elements\Variant::class)->scalar(),
    'qty' => 0,
]);
$lineItem->validate();
var_dump($lineItem->getErrors('qty'));
```

### Expected behavior

```
array(1) {
  [0] =>
  string(27) "Qty must be no less than 1."
}
```

### Actual behavior

```
array(2) {
  [0] =>
  string(27) "Qty must be no less than 1."
  [1] =>
  string(27) "Qty must be no less than 1."
}
```

### Craft CMS version

"craftcms/cms": "3.9.5"

### Craft Commerce version

"craftcms/commerce": "3.4.23"

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks. This is fixed for the next release of Commerce 4.x. I will let you know once it is released.
