### ISSUE TITLE
[4.x]: Should you be able to delete discounts / coupon codes that have been used?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3337]
### What happened?

Unless i'm missing some new logic in Craft 4, once a discount or any of the coupon codes listed for a discount are deleted, then you are unable to retrieve the discount associated with an order by the `$order->couponCode` value via the Discounts service as follows:

```Commerce::getInstance()->getDiscounts()->getDiscountByCode($order->couponCode)```

We use this to identify the specific discount adjustments (separate to any other discounts) that are related to an order coupon code, allowing us to display the discount amounts on a lineitem and order level. 

Feels like either the code that was used should be stored in the adjustment snapshot along with the `discountUseId`?

NB. Craft 3 used to store the `code` value which is how we identified this previously.

### Craft CMS version

4.5.10

### Craft Commerce version

4.3.2

### PHP version

8.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @samhibberd 

Thank you for your report. I apologise but I am not sure I follow what you are trying to achieve here.

The coupon code for a discount is stored directly on an order when it is used/completed. If you subsequently delete the coupon or discount then because the data is gone you will be unable to retrieve it.

As shown in the screenshot below this won't affect the integrity of the data on the order(s) that used it.

![CleanShot 2023-11-21 at 09 19 46@2x](https://github.com/craftcms/commerce/assets/266453/d100490c-18f2-422a-bd9d-6f84f0dda8b1)

Please let me know if there is further information that might help us with the scenario you are seeing.

Thanks.

**Comment by samhibberd** [comment]
We run a marketplace, and as such need quite a lot of control of adjusments, we have various custom ones. It might have been late when i was working through this and thus over complicating, but we use the following logic to grab all coupon code adjustments and the total for an order:

```php
public function getCouponCodeAdjustments()
{
    $order = $this->owner->order ?? $this->owner;
    if (
        !$order->couponCode ||
        !$discount = Commerce::getInstance()->getDiscounts()->getDiscountByCode($order->couponCode)
    ) {
        return [];
    }

    return ArrayHelper::where($this->owner->getAdjustments(), function($adjustment) use ($order, $discount): bool {
        return (
            $adjustment->type === 'discount' &&
            (
                $discount->id == ($adjustment->sourceSnapshot['discountUseId'] ?? null) ||
                $order->couponCode === ($adjustment->sourceSnapshot['code'] ?? null)
            )
        );
    });
}

public function getCouponCodeAdjustmentsTotal()
{
    return Adjusters::total($this->getCouponCodeAdjustments());
}
```

Would it be safe to assume that if an adjustments `sourceSnapshot` has a `discountUseId` value or (`code` for backwards compatibility with Craft 3) then it is a coupon code adjustment, so:

```php
public function getCouponCodeAdjustments()
{
    $order = $this->owner->order ?? $this->owner;
    if (!$order->couponCode) {
        return [];
    }

    return ArrayHelper::where($this->owner->getAdjustments(), function($adjustment): bool {
        return (
            $adjustment->type === 'discount' &&
            (
                isset($adjustment->sourceSnapshot['discountUseId']) ||
                isset($adjustment->sourceSnapshot['code'])
            )
        );
    });
}
```

**Comment by nfourtythree** [comment]
Hi @samhibberd 

Thank you for your response this gave me a great understanding of what you are trying to achieve.

Internally we have some thoughts on how discounts and adjustments may evolve in the future and along with the fact that the `sourceSnapshot` could be manipulated by any code or plugin we are likely not to make any changes to the core code right at this moment.

That does not mean that all is lost. 

For your instance you could look at adding to the `sourceSnapshot` when the discount order adjuster is added. A rough example to get you were you need to be would be something along the lines of the following:

```php
use craft\base\Event;
use craft\commerce\adjusters\Discount;
use craft\commerce\Plugin;
use craft\commerce\records\OrderAdjustment;
use craft\helpers\Json;
use yii\base\ModelEvent;

// ...

Event::on(OrderAdjustment::class, OrderAdjustment::EVENT_BEFORE_INSERT, function(ModelEvent $event) {
    /** @var OrderAdjustment $orderAdjustment */
    $orderAdjustment = $event->sender;
    $order = Plugin::getInstance()->getOrders()->getOrderById($orderAdjustment->orderId);
    if ($orderAdjustment->type !== Discount::ADJUSTMENT_TYPE || !$order || !$order->couponCode) {
        return;
    }

    $sourceSnapshot = Json::decodeIfJson($orderAdjustment->sourceSnapshot);
    if (!isset($sourceSnapshot['id'])) {
        return;
    }

    $discount = Plugin::getInstance()->getDiscounts()->getDiscountById($sourceSnapshot['id']);

    if (!$discount || empty($discount->getCoupons())) {
        return;
    }

    $sourceSnapshot['code'] = $order->couponCode;
    $event->sender->sourceSnapshot = $sourceSnapshot;
});

```

Hope this helps, thanks!

**Comment by samhibberd** [comment]
Thanks @nfourtythree we utilise this already for other logic and hadn't thought to use for this 👍 

Good to hear that the sourceSnapshot isnt going to be changing any time soon, we use it extensively for our custom discount adjusters. Since you deprecated custom adjuster types we store our custom adjuster type within the snapshot as we felt it would be the most future proof thing as it stands.
