### ISSUE TITLE
Why is no Asset data in the Cart Object

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/commerce#334]
We want to build our checkout with Vue. Looks all fine but we found nothing to handle images. 

```
{
  cart: {
    lineItems: {
      snapshot: {
        imageField: "#### NO IMAGE STUFF INSIDE ###"
      }
    }
  }
}
```

Any suggestions how to handle a way like this?

**Comment by davidhellmann** [comment]
It looks like the same Problem like this: https://craftcms.stackexchange.com/questions/17579/displaying-assets-from-crafts-cart-ajax-response

**Comment by fabianhijlkema** [comment]
I'm also working on a Vue project where I wanted to have control over the response object that Craft Commerce is sending back after a order update, I've ended up extending the CartArray as defined in the BaseFrontendController, giving me the option to add all the necessary data I need, see link...

https://craftcms.stackexchange.com/questions/25907/overriding-basefrontendcontroller-in-craft-commerce

I'm not sure if it is the best way, but it works for me, maybe somebody from the Commerce team can weigh in on this.

**Comment by lukeholder** [comment]
@davidhellmann are you using craftql?

**Comment by davidhellmann** [comment]
@lukeholder atm not. @martinherweg helped me out and we've build a module to extend the cart.

**Comment by martinherweg** [comment]
@fabianhijlkema @lukeholder This is the essential part of the Module to extend the Snapshot in the Response.

https://gist.github.com/martinherweg/1e45c09e20f3faa29306fe6523b45d85

**Comment by lukeholder** [comment]
You can also add to the snapshot as share above, but best to access the original product itself from the line item. the snapshot only exists in-case the product was deleted.

```twig
{{ lineItem.purchasable.customAssetField.url }}
```

**Comment by martinherweg** [comment]
@lukeholder The Problem is only when using AJAX, in Twig there isn't any problem :)

**Comment by lukeholder** [comment]
Right, I understand now.

Unfortunately, there is no way to encode all custom fields in json within craft in a consistent way at the moment (think matrix fields for example, and/or relation fields like entries or assets). The snapshot just does a simple call to `getSerializedFieldValues()` on the purchasable's fields for the snapshot at the moment.

Best advice for now is to use the element API (with an additional ajax request) to retrieve product information in the format you need based on the `purchasableId` (element ID) on the line item.
