### ISSUE TITLE
[4.x]: PDF attached to email shows error msg when first sent

### ISSUE THREAD

**Issue by tigerchick** [craftcms/commerce#3340]
### Description
If an order is made then the email that is sent to the customer has a pdf attached. When the order is first made, this pdf only displays "An error occurred while generating this PDF."  
If the email is then subsequently sent again through the CP then the pdf is generated correctly. 
The pdf is also generated correctly if the "Download PDF" button is clicked in the order backend CP.
The problem only manifests in the automated email sent out when an order is newly created.
I am using Oliver Stark's AsyncQueue plugin (v3.1.0) but I have also tested without (same result).

### Craft CMS version

4.5.11

### Craft Commerce version

4.3.2

### PHP version

8.2.12

### Operating system and version

Linux 4.15.0-192-generic

### Database type and version

MySQL 5.7.42

### Image driver and version

GD 8.2.12

### Installed plugins and versions

-

**Comment by stefanfriedrich** [comment]
Same error here, Craft 4.5.9, Commerce  4.3.2

**Comment by stefanfriedrich** [comment]
@tigerchick Did you set runQueueAutomatically to false? Seems to work for us.

**Comment by tigerchick** [comment]
> @tigerchick Did you set runQueueAutomatically to false? Seems to work for us.

Hi @stefanfriedrich , thanks for the suggestion - I have tried that just now but it doesn't seem to have made a difference.
