### ISSUE TITLE
[3.x/4.x]: `Order::addLineItem()` doesn't propagate a dissenting `EVENT_BEFORE_ADD_LINE_ITEM` handler

### ISSUE THREAD

**Issue by msbit** [craftcms/commerce#3341]
### Description

If an event handler for `Order::EVENT_BEFORE_ADD_LINE_ITEM` marks `AddLineItemEvent::isValid` false, `Order::addLineItem` [just][1] [returns][2] after triggering the event, with no indication to the caller that the the adding has failed. This is [most][3] [problematic][4] [when][5] [called][6] [from][7] `CartController::actionUpdateCart`, as the response (when accepting JSON) is something like the following:

```json
{
    "success": true,
    "cart": {
        ...
        "lineItems": [], 
        ...
    },
    "message": "Cart updated.",
}
```

[1]: https://github.com/craftcms/commerce/blob/3.4.23/src/elements/Order.php#L1690
[2]: https://github.com/craftcms/commerce/blob/4.3.2/src/elements/Order.php#L1806
[3]: https://github.com/craftcms/commerce/blob/3.4.23/src/controllers/CartController.php#L121
[4]: https://github.com/craftcms/commerce/blob/3.4.23/src/controllers/CartController.php#L166
[5]: https://github.com/craftcms/commerce/blob/3.4.23/src/controllers/CartController.php#L184
[6]: https://github.com/craftcms/commerce/blob/4.3.2/src/controllers/CartController.php#L140
[7]: https://github.com/craftcms/commerce/blob/4.3.2/src/controllers/CartController.php#L191

### Steps to reproduce

```php
\yii\base\Event::on(
    \craft\commerce\elements\Order::class,
    \craft\commerce\elements\Order::EVENT_BEFORE_ADD_LINE_ITEM,
    fn ($event) => $event->isValid = false,
);
```

### Expected behavior

Some kind of error response to `commerce/cart/update-cart`.

### Actual behavior

No error response to `commerce/cart/update-cart`.

### Craft CMS version

"craftcms/cms": "3.9.5"

### Craft Commerce version

"craftcms/commerce": "3.4.23"

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @msbit 

Thank you for your message.

If a developer is using an event to prevent the adding of an item to the cart in a custom module, it is also up to them to add any errors.

As an example event if you did the following: 

```php
Event::on(Order::class, Order::EVENT_BEFORE_ADD_LINE_ITEM, function(AddLineItemEvent $event) {
    $order = $event->sender;
    $event->isValid = false;

    $order->addError('lineItems', sprintf('%s Not added', $event->lineItem->getDescription()));
});
```

An error will be returned due to the fact the validation checks will have failed based on your added error.

Hope this helps, thanks!

**Comment by msbit** [comment]
Hey @nfourtythree thanks for that information. Adding the error to the event sender does work.
