### ISSUE TITLE
[4.x]: Delete variant does not respect Elements::EVENT_AUTHORIZE_DELETE

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3342]
### What happened?

Similarly to https://github.com/craftcms/commerce/issues/3285, the delete action still shows for variants / purchasable where delete has not been authorized via the Elements authorize event:

<img width="592" alt="Screenshot 2023-11-20 at 16 44 32" src="https://github.com/craftcms/commerce/assets/1846063/4717e22c-266b-4dca-a613-302cd6bebe0b">

### Craft CMS version

4.5.11

### Craft Commerce version

4.3.2

### PHP version

8.2.11

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @samhibberd 

Thanks for your question.

At the moment there is no specific variant related permissions and that is why you wont see this event raised when deleting a variant as it is all handled by the product. 

Inherently if you have permission to delete or edit the product you can delete a variant.

If you would like to extend this you can add to the product's validation and add a new rule to the `variants` attribute. In this rule you can query the product's variants and check those against the variants on the product in memory to see if there is any difference and raise an error as you see fit.

This functionality will change in Commerce 5 with the fact that variants will become nested elements on the product and therefore have slightly more specific authorship.

Hope this helps, thanks!

**Comment by samhibberd** [comment]
Ok thanks for the explanation, but doesn't that mean if you don't have permission to delete the product then the delete action at a variant level should be hidden / disabled? Seems wrong that you are not allowed to delete the product but see the delete variants action. 

We have extended things (at a product save level) to prevent removal of variants (under certain conditions) but having the delete action there is quite counter intuitive?

**Comment by nfourtythree** [comment]
Thank you for your reply.

As I mentioned in my previous comment, if you have permission to edit or delete the product you have permission to delete the variants. 

Thanks!

**Comment by samhibberd** [comment]
Hi @nfourtythree, sorry if I’m missing something, but it’s if you don’t have permission to edit or delete the product that I’m asking about. 

As in does the reverse of this apply:

> Inherently if you have permission to delete or edit the product you can delete a variant.

In that case would it be expected that the delete button to be disabled / hidden at both product and variant level? Maybe not 🤔. I guess adding and removing variants could be considered editing. 

Seems simpler in craft 5 :)

**Comment by nfourtythree** [comment]
Hi @samhibberd 

This is correct, adding and removing of variants is currently considered under the editing banner of permissions.

Hope that helps, thanks!
