### ISSUE TITLE
[4.x]: Discount performance in CP

### ISSUE THREAD

**Issue by ragnarfrosti** [craftcms/commerce#3347]
### What happened?

I have a couple of points about the handling of Discounts in the Control Panel:

**1) The Discounts overview**

The Commerce > Promotions > Discounts view has very poor performance when there are many discounts in the system. This problem existed in Commerce 3 and is still an issue in Commerce 4. Our client has ~16.000 discounts in the system at the moment and the Discounts view lists all discounts on the same page which makes the browser either crash or lock up for a couple of minutes.

We were forced to build a custom plugin for the customer with pagination search/filter to be able to list and handle the discounts since that is not possible in Craft with a large number of discounts.

<img width="1505" alt="Screenshot 2023-12-05 at 10 39 12" src="https://github.com/craftcms/commerce/assets/4622136/c3820e9b-ef18-4583-b7cb-99e45d2b7e08">

Being able to handle all discounts should work in Commerce out of the box, and some filter/searching would also be a nice feature.

**2) Coupons on a Discount: Generating codes**

I love that you can add multiple coupons on a single discount, that is a huge step forward from Commerce 3. But why is there a limit of only creating 400 coupons on a single discount?

<img width="529" alt="Screenshot 2023-12-05 at 10 46 11" src="https://github.com/craftcms/commerce/assets/4622136/0cfb5269-6bfd-43b6-b82b-5db03279ff3a">

Is this a Craft limitation because it can't handle calculating the order adjustments when there are too many coupons on a discount or is it because of something else?

In Commerce 3 our customers often create 5000 unique coupons at each time and it would be nice to be able to add ~5000 codes on each discount instead of creating new discounts for each code or needing to split it between multiple discounts.

Importing codes to a discount would also be a nice to-have function ;)

Running the code generator twice with 400 codes each is possible but 800 rows in the table messes up the browser performance so this would need some kind of pagination as well.

**3) Coupons on a Discount: Administration of codes**

It is great that you can generate multiple codes on a single discount but if you create 100 codes on a discount there is no way to export/copy a list of the codes so you would need to copy each code manually to send it to the customer or to export it to another system.

And same thing applies to the "Max uses"-field. There is no way to add a maximum use for all the codes at the same time (not even when creating those) so this requires manually changing the "max use" for one code at a time.

We've extended the Discount view with a basic "Copy codes"-button below the table that copies all the codes to the clipboard and a field that helps update the maximum use for all the codes at the same time. But this is something that should be there out of the box in my opinion.

<img width="1194" alt="Screenshot 2023-12-05 at 10 58 07" src="https://github.com/craftcms/commerce/assets/4622136/3443475e-d395-478d-9122-ea2b868d15df">

Our client uses discounts quite a lot for different purposes but at the moment the discount part of Craft is not up to standard and hasn't been for quite some time, so I hope that this is something that you can improve pretty soon. The functionality for using Discounts and codes is already in place but it just seems that you have disregarded the idea of people having more than just a few codes. That can't be the real scenario for a larger site.

Unfortunately, it also makes it hard for us to sell Craft Commerce as a great platform for our customers when the business expands.

How does your timeline look for the above issues?

### Craft CMS version

4.5.11.1

### Craft Commerce version

4.3.2

### PHP version

8.1

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@ragnarfrosti Thanks for the information and feedback. 

We have spent some time as a team looking into improving the performance of discount listings and coupon listings, and have some solutions in the works that we will share here soon. Thanks.

**Comment by nfourtythree** [comment]
Hi @ragnarfrosti 

Thank you for raising this.

Commerce `4.4.0` has just been released which includes improvements to the coupons table as well as a paginated and searchable index for discounts.

Thanks!
