### ISSUE TITLE
[3.x]: Order field layout from project config does not get applied

### ISSUE THREAD

**Issue by eablokker** [craftcms/commerce#3348]
### Description
When creating a field layout for "Order Fields", and it is saved to the project config, applying the config to another site does not apply the field layout. Order Fields remains blank.

### Steps to reproduce

1. Go to Commerce -> System Settings -> Order fields
2. Create a new Tab and drag a custom field into it (I used a Plain Text field)
3. I also added a "Tip" field from the UI Elements
4. Commit project config changes to Git and push
5. Pull git changes on target site
6. On target site, go to Utilities -> Project Config in Craft
7. You will see the YML changes to the field layout listed there
8. Click Apply Changes Only
9. Go to Commerce -> System Settings -> Order fields on target site
10. Field layout will be blank

Also if you already had an order field layout on the target site, the field layout will be completely deleted if you apply the project config

### Expected behavior

Same order field layout from source site should appear on the target site

### Actual behavior

Order field layout becomes totally blank

### Craft CMS version

3.9.5

### Craft Commerce version

3.4.23

### PHP version

7.4.3 

### Operating system and version

macOS 11.7.10 and Ubuntu 20.04.1 LTS

### Database type and version

MySQL 5.7.39 and 8.0.35

### Installed plugins and versions

- Element API 2.8.6.1
- Feed Me 4.7.0
- Many to Many 2.0.3
- Postie 2.4.25
- Redactor 2.10.12
- Stripe for Craft Commerce 2.4.4.1

**Comment by lukeholder** [comment]
I cant reproduce on the latest cms 3.x and commerce 3.x:

screencast: https://share.cleanshot.com/8GWw9hP2

Could it be that it's a different field layout UID on production vs local development?

If so you would need to make sure that you have made sure all developers have started with the production project config and production database following this guide: https://craftcms.com/docs/4.x/project-config.html#adopting-project-config

Will reopen if there is more information you can give me to reproduce?
