### ISSUE TITLE
[4.x]: Duplicate entry in searchindex after new Order

### ISSUE THREAD

**Issue by krizzzly** [craftcms/commerce#3350]
### Description
i just migrated commerce from 2 -> 3 and then from 3->4.
Now with every order coming in i have failing tasks in my Queue. 3 for each order.

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '225995-skus-0-1' for key 'k4_searchindex.PRIMARY' The SQL being executed was: INSERT INTO `k4_searchindex` (`elementId`, `attribute`, `fieldId`, `siteId`, `keywords`) VALUES (225995, 'skus', 0, 1, ' mobile s sim karte aufschaltgebuehr 657 classic trio internet iptv classic 1 ')
`

### Craft CMS version

Craft Pro 4.5.11.1

### Craft Commerce version

4.3.2

### PHP version

8.0

### Operating system and version

Linux 5.4.0-153-generic

### Database type and version

MySQL 8.0.35

### Installed plugins and versions

Control Panel Body Classes	2.3.0
Control Panel CSS	2.6.0
Control Panel JS	2.6.0
Cookies	4.0.0
CP Clear Cache	1.3.0
Craft Commerce	4.3.2
Feed Me	5.3.0
Freeform	4.1.13
Kint	3.1.1
MatrixMate	2.1.4
Preparse Field	2.0.2
QRCode	2.1.0
Redactor	3.0.4

**Comment by nfourtythree** [comment]
Hi @krizzzly 

Thank you for your message, do you have a full stack trace for this issue?

If you go into the control panel and go to `/admin/edit/225995`, does the element load correctly? Notice anything odd or different about it?

Thanks.

**Comment by nfourtythree** [comment]
Closing this issue for now as it seems to be stale.

If you have any further information please let us know and we can reopen the issue.

Thanks!
