### ISSUE TITLE
[4.x]: If title is used for first name it is stripped when outputting first name

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#3356]
### Description
When outputting first name like this `$order->billingAddress->firstName` it comes out with "null" if the first name is for example "Miss"

Since we are not blocking the user from entering "Miss" as first name frontend we need it to output "Miss" when using `$order->billingAddress->firstName` otherwise we end up with empty variables when sending order data to for example shipping fulfilment.

The above is just my opinion. Happy to be proven wrong. Just seeking a solution.

### Expected behavior
Output "Miss"

### Actual behavior
Output "null"

### Craft CMS version

4.5.12 

### Craft Commerce version

4.3.2

### Installed plugins and versions

-

**Comment by rbrv** [comment]
We're having the same problem, preventing a commerce customer from paying the order.

**Comment by lukeholder** [comment]
Please make sure you are on at least 4.9 and read this issue and it's solutions:

https://github.com/craftcms/cms/issues/14665

Note also this option: https://craftcms.com/docs/5.x/reference/config/general.html#showfirstandlastnamefields
