### ISSUE TITLE
[4.x]: Selecting Cart address duplicates the address

### ISSUE THREAD

**Issue by ineghi** [craftcms/commerce#3366]
### What happened?

Maybe relates to https://github.com/craftcms/commerce/issues/3238

### Description
Freshly migrated from v3, when a logged in user creates a new cart, the new cart address will be set based on the primary adress (as expected), but with a new ID (which probably means an orphan address is created).
Each time there is a cart/update-cart with a other user address id, a new address is created on the cart, incrementing the ID each time.

### Steps to reproduce

1. Log in with a user having a primary address set.
2. create a cart
3. cart has a shippingAddress, but with a different ID than the primary address

### Expected behavior

If I update the cart with the shippingAddressId (value=1), the cart shippingAddressId should be 1, not 2.
Quite like in Commerce 3, cart addresses should be references to the user's address.

### Actual behavior

A new orphan address is created each time.

### Craft CMS version

^4.5.0

### Craft Commerce version

^4.3.3

### PHP version

8.0.2

### Operating system and version

craftcms/nginx:8.2-dev

### Database type and version

mariadb:10.5

### Installed plugins and versions

       "bitmatrix/craft-omnisearch": "2.0.0",
        "craftcms/cms": "^4.5.0",
        "craftcms/commerce": "^4.3.3",
        "craftcms/commerce-mollie": "4.1.0.1",
        "craftcms/commerce-multisafepay": "4.0.0",
        "craftcms/commerce-omnipay": "^4.0.0",
        "craftcms/contact-form": "3.0.1",
        "craftcms/element-api": "3.0.1.1",
        "craftcms/mailgun": "3.0.0",
        "craftcms/redactor": "3.0.4",
        "ether/logs": "4.0.0",
        "mailgun/mailgun-php": "4.0.0",
        "mmikkel/incognito-field": "1.3.0",
        "nystudio107/craft-seomatic": "4.0.37",
        "nystudio107/craft-twigpack": "4.0.0-beta.4",
        "picqer/sendcloud-php-client": "^2.4",
        "pierrestoffe/craft-language-redirector": "2.0.1",
        "sebastianlenz/linkfield": "2.1.5",
        "topshelfcraft/wordsmith": "4.4.0",
        "verbb/gift-voucher": "3.0.10",
        "vlucas/phpdotenv": "^3.4.0"

**Comment by lukeholder** [comment]
As far as I understand the issue you have posted, this is expected behaviour in Commerce 4. See the docs here: https://craftcms.com/docs/commerce/4.x/addresses.html#updating-cart-addresses

Specifically, note that the address you submit to the cart will be found on the `sourceShippingAddressId`, but it is duplicated to the `shippingAddressId` as to relate _only_ to the cart (this new address _belongs_ to the cart).

Let me know if you have any other questions.
