### ISSUE TITLE
[3.x]: Adding lots of shipping methods slows down fetching cart

### ISSUE THREAD

**Issue by joostwaaijer** [craftcms/commerce#3370]
### Description

For a customer we've imported over 750+ shipping methods. After these shipping methods were imported (Even when disabled) the duration of fetching the cart takes significantly more time, so page loads are also slowed down massively, after deleting these shipping methods, the page speed returned to normal. The imported shipping methods only used the standard shipping methods / rules. Please not that we have the option `autoSetCartShippingMethodOption` turned on, this probably affects the performance.

Digging some deeper into the code, I see that `getAllShippingMethods` from the `ShippingMethods` service are actually fetching all shipping methods, including disabled ones, I think this could actually use filter on enabled, otherwise create a new `getAllEnabledShippingMethods` and use that for automatically setting the shipping method.

### Steps to reproduce

1. Turn on autoSetCartShippingMethodOption in craft settings
2. Add 750+ shipping methods
3. Fetch cart on pages

### Expected behavior

Fetching cart should not be impacted by disabled shipping method options.

### Actual behavior

Fetching cart is negatively impacted by disabled shipping method options.

### Craft CMS version

Craft Pro 3.9.10

### Craft Commerce version

3.4.23

### PHP version

8.3.1

### Database type and version

Postgresql

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Could you please send your DB backup (that contains many shipping methods) to support@craftcms.com so we can reproduce the performance issue? 

Please reference this issue in your email. Thanks

**Comment by lukeholder** [comment]
We recommend upgrading to Commerce 5 to get the many performance improvements that have been released since v3. Thanks.
