### ISSUE TITLE
[4.x]: Upgraded from Commerce 3 and CP order details page shows addresses with label "Address" instead of "Shipping / Billing Address"

### ISSUE THREAD

**Issue by moldedjelly** [craftcms/commerce#3387]
### Description
Upgraded from Commerce 3 to 4 and Control Panel order details page shows Shipping and Billing addresses with label "Address" instead of distinguishing "Shipping / Billing Address" as the new orders do.

### Steps to reproduce

1. Upgrade a site with existing orders from Commerce 3 to Commerce 4.

### Expected behavior
Old orders to show addresses labelled as "Shipping Address" and "Billing Address"

### Actual behavior
Old orders only show addresses labelled as "Address" and "Address"

### Craft CMS version

4.7.2

### Craft Commerce version

4.4.1.1

### PHP version

8.0.30

### Operating system and version

docker - craftcms/nginx:8.0

### Database type and version

docker - mariadb:10.3

**Comment by lukeholder** [comment]
You can fix this by running the following SQL commands on 4.x

```sql
UPDATE content
SET title = 'Shipping Address'
WHERE elementId IN (
    SELECT shippingAddressId
    FROM commerce_orders
);
```

```sql
UPDATE content
SET title = 'Billing Address'
WHERE elementId IN (
    SELECT billingAddressId
    FROM commerce_orders
);
```

if you use a db table prefix, you would need to add the prefix to the table names in the above commands: `xxx_commerce_orders` and `xxx_content`

We will add a migration in the future that will clean this up.

**Comment by Saboteur777** [comment]
Hi @lukeholder ! I am in the middle of a migration from Commerce 3 to 4, and while running the `commerce/upgrade` command, the `_relabelOrderAddresses` function takes a "lot of time" (15 minutes) to finish, even with an almost empty (33 rows) Orders table. Is this the expected behavior?
