### ISSUE TITLE
Duplicate Order Number Assigned

### ISSUE THREAD

**Issue by smockensturm** [craftcms/commerce#3391]
### Description

A customer was assigned an order number that was previously assigned to a different user.

Days apart. Why?

![image](https://github.com/craftcms/commerce/assets/6586518/f7a7487b-fa43-49a1-b232-b7decf1f309d)

### Craft CMS version

Pro 4.6.0

### Craft Commerce version

4.4.0

### PHP version

8.2.11

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@smockensturm Can you confirm the full number is the same and not just the short number?

Did you recently upgrade?

**Comment by smockensturm** [comment]
@lukeholder thank you. i can confirm they are NOT. good call.

yes we did recently upgrade.

Thing is, ShipStation will not process the second order CC: @johnnynotsolucky at Foster Commerce

**Comment by lukeholder** [comment]
Sorry, just to clarify the full number is not the same between the 2 orders? Shipstation or any external integration should use the full number to ensure it is unique. Can I close this ticket?

**Comment by lukeholder** [comment]
the `number` column on the Orders table has a unique constraint, so this should be impossible. Closing the ticket. Let me know if you have any questions.
