### ISSUE TITLE
[4.x]: New discount order adjustments revert to a value of "0" when saved.

### ISSUE THREAD

**Issue by Kent-N** [craftcms/commerce#3392]
### Description

When adding a discount to a completed order (didn't test with incomplete orders), the total value doesn't update on the order. After saving, the discount is present but with a value of 0.

Also, there seems to be an issue with saving anything beyond a single change to any order adjustment. The order total updates on the first change but afterwards remains the same. In the same vein, that first change will "take" and get saved, but any other changes won't.

### Steps to reproduce

Adding a new discount saves as a 0 value discount.

1. Click "edit adjustments" on a completed order.
2. Click "Add an adjustment" and select "Discount".
3. Type a number in the "amount" field (note that order total doesn't update)
4. Save the order.

Only one adjustment amount change per save:

1. Click "edit adjustments" on a completed order.
2. Modify the amount of any type of adjustment to X.
3. The order total updates and the value of X is reflected in it. The order can also be saved correctly.
4. Modify X to Y or modify any other "amount" field in a different adjustment.
5. The order total doesn't update.
6. When saving the order, only the first change is saved, all the others aren't.

### Expected behavior

Adding or changing an adjustment should update the order total and save correctly to the order.

### Bonus UI bug

When deleting an order adjustment, the adjustment line below can inherit the deleted lines adjustment amount.

![firefox_bhrVTL9v7x](https://github.com/craftcms/commerce/assets/62756920/cf0b5baf-549e-4030-93b7-b167ce3677e4)

### Craft CMS version

Craft Pro 4.7.2.1

### Craft Commerce version

4.4.1.1

### PHP version

8.1.27

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MariaDB 10.3.39

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @Kent-N 

Thank you for bringing this to our attention. We managed to replicate the issue and push a fix.

The fix will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "dev-develop#a4d170b757c82ffa49752afbd093e655b9538d65 as 4.5.1",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce version `4.5.1.1` has now been released with this fix included.

Thanks!
