### ISSUE TITLE
[5.x]: Internal Server error on product overview 

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#3395]
### Description
When navigating to the Product overview, a server error occur.

When selected a product type in the sidebar and trying to create a product, clicking the `New product` button also triggers this error and you are unable to create a product.
When selecting All products, the `New product` button does work

This same error occurs when on the product detail page, I guess coming from the variants overview. (The `New product variant` button is also disabled)

```
yii\web\BadRequestHttpException: Request missing required param in /var/www/html/vendor/craftcms/cms/src/web/Request.php:1110
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/controllers/BaseElementsController.php(48): craft\web\Request->getRequiredParam('elementType')
#1 /var/www/html/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(112): craft\controllers\BaseElementsController->elementType()
#2 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(176): craft\controllers\ElementIndexesController->beforeAction(Object(yii\base\InlineAction))
#3 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('get-elements', Array)
#4 /var/www/html/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('element-indexes...', Array)
#5 /var/www/html/vendor/craftcms/cms/src/web/Application.php(651): craft\web\Application->runAction('element-indexes...', Array)
#6 /var/www/html/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/html/web/index.php(12): yii\base\Application->run()
#9 {main}
```

### Steps to reproduce

1. Setup a product Type
2. Go to the Products page
3. Error occurs

1. Create a product
2. when on the edit page the error occurs

### Expected behavior
No error should occur

### Craft CMS version

5.0.0-beta.4

### Craft Commerce version

5.0.0-beta.1

### PHP version

8.3

### Operating system and version

Ubuntu 22.04

### Database type and version

mysql 8.0.32

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

Thank you for reporting.

Are you seeing a dropdown when you click the New Product button with the available product types? As shown in this screenshot:

![](https://media.cleanshot.cloud/media/72621/tneuJHnfMw763Yt4m0ElYXkVnohwOjw1a6ECnvA9.jpeg?Expires=1709303559&Signature=fq6udArKljx79Z1grsxD5-XqFjHTV~lysLIyGVEdr4zjD-mrj3fuTMv6ogB-LVmn-sg90XO4vOs9XboHKTIKIllvJIt2vERDuf3oYJdabRUUSTXWLUd0DX~7yYBkbZ6HkEIVCjyNS2WKOgHL7M3B6997qu8h6vXtjES78eXdfgL7I1VfsKOiuko5G8G9ooeV5m1Fmv7yL3Wgzg1-Hb47BoJrOrCk-XhIq9lRyHad5ezyuCeAL8U6c0Acihr2Xth2Ld702MUur87k786-3qvf7lSl2~Ea7XZJMjK05~Eruy7hM4IP~4T0FWlZyBmrIF4OBE4aHeZPUQEDXJzEUW3q5Q__&Key-Pair-Id=K269JMAT9ZF4GZ)

Can you try clearing your caches and seeing if that helps?

Thanks!

**Comment by WHITE-developer** [comment]
Clearing cache didn't work, but it seems it's a global Craft bug I get it on the entries as well after updating to craftcms/cms:5.0.0-beta.4, when downgrading to beta.3 it works again
