### ISSUE TITLE
[4.x]: No badge count in the order overview

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#3397]
### Description
Since Craft CMS 4.8.0 the order overview is not showing order counts anymore.

https://github.com/craftcms/cms/commit/2aacf09e4a62d7aa8ec0a7d278286c8f8dbf52a9#diff-bc910fdbfcae9f65762d61fde137e949b37fffb56be2d4fccd68b0e5cbaedb20

Default the badgeCount is `0` so the label isn't rendered and because of this it also can't be updated https://github.com/craftcms/commerce/blob/develop/src/web/assets/commercecp/src/js/CommerceOrderIndex.js#L107

### Craft CMS version

4.8.0

### Craft Commerce version

4.5.1.1

### PHP version

8.2.10

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

Thank you for reporting, we have just pushed a fix for this which will be included in the next release of Commerce.

We will look to get this release out as soon as possible.

Thanks!

**Comment by nfourtythree** [comment]
Version `4.5.2` has now been released which includes this fix.

Thanks!
