### ISSUE TITLE
[5.x]: Unable to change primary store

### ISSUE THREAD

**Issue by johnnynotsolucky** [craftcms/commerce#3398]
### Description

Attempted to change the primary store, but saving didn't update it.

### Steps to reproduce

1. Using the spoke&chain demo site, add 2 more sites;
2. Create 2 new stores associated with each new site;
3. Attempt to set the primary store to a site other than the original primary;
4. Note that the primary store has not changed.

### Expected behavior

The primary store should change.

### Actual behavior

Primary store does not change.

### Craft CMS version

5.0@beta.4

### Craft Commerce version

5.0@beta.1

### PHP version

8.2

### Database type and version

MySQL

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @johnnynotsolucky 

Thank you for raising this issue, we have just [pushed a fix](https://github.com/craftcms/commerce/pull/3399) for this which will be included in the next Commerce 5 beta.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.0.x-dev#fc1ecb318ffe5144a68a241fad34c23d744df14b as 5.0.0-beta.1",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
