### ISSUE TITLE
Integrity constraint violation: 1048 Column 'isArchived' cannot be null

### ISSUE THREAD

**Issue by efatsi** [craftcms/commerce#340]
### Description

Getting integrity constraint violation when trying to update an existing Gateway.

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'isArchived' cannot be null
The SQL being executed was: UPDATE `craft_commerce_gateways` SET `isFrontendEnabled`=1, `isArchived`=NULL, `dateUpdated`='2018-05-09 17:59:52' WHERE `id`=1
```

### Steps to reproduce

1. Add a Gateway via /admin/commerce/settings/gateways/new
2. Click in to the Gateway's edit page
3. Click save

Looks like defining `public $isArchived = false;` in commerce/src/base/Gateway.php is a potential fix.

**Comment by andris-sevcenko** [comment]
Is this a fresh Commerce install or an update from 1.x?

**Comment by efatsi** [comment]
upgrade from 1.x

**Comment by lukeholder** [comment]
Thanks, should be fixed for next release.
