### ISSUE TITLE
[5.x]: Fetching variants per site returns extra records

### ISSUE THREAD

**Issue by johnnynotsolucky** [craftcms/commerce#3401]
### Description

Potentially not Commerce related, but Craft related.

When attempting to fetch variants for more than one site, the results return the variantCount * sites * sites.

```bash
> \craft\commerce\elements\Variant::find()->site(['default'])->count();
= "91"

> \craft\commerce\elements\Variant::find()->site(['default', 'siteA'])->count(); // 91 * 2 * 2
= "364"

> \craft\commerce\elements\Variant::find()->site(['default', 'siteA', 'siteB'])->count(); // 91 * 3 * 3
= "819"
```

The data returned seems to be duplicated:

```bash
> array_map(fn ($x) => ['variantId' => $x->id, 'siteId' => $x->site->id], \craft\commerce\elements\Variant::find()->id(579742)->site('*')->all());
= [
    [
      "variantId" => 579742,
      "siteId" => 3,
    ],
    [
      "variantId" => 579742,
      "siteId" => 2,
    ],
    [
      "variantId" => 579742,
      "siteId" => 1,
    ],
    [
      "variantId" => 579742,
      "siteId" => 3,
    ],
    [
      "variantId" => 579742,
      "siteId" => 2,
    ],
    [
      "variantId" => 579742,
      "siteId" => 1,
    ],
    [
      "variantId" => 579742,
      "siteId" => 3,
    ],
    [
      "variantId" => 579742,
      "siteId" => 2,
    ],
    [
      "variantId" => 579742,
      "siteId" => 1,
    ],
  ]
```

As the `count` example above suggests, if I just fetch a variant for single site then it correctly returns a single record.

### Steps to reproduce

1. Tested with above snippets in craft shell

### Expected behavior

The query `Variant::find()->id(579742)->site('*')->all()` returns a single Variant for each site.

### Actual behavior

See above.

### Craft CMS version

5.0@beta.5

### Craft Commerce version

Branch 5.0

### PHP version

8.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
hi @johnnynotsolucky 

Thank you for reporting this, we have pushed a fix for this which will be included in the next beta release of Commerce 5.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.0.x-dev#1cc5594bde04e94b77437145851c08c4ca044e61 as 5.0.0-beta.1",
  "...": "..."
}
```

Then run `composer update`.
