### ISSUE TITLE
[5.x]: Some bugs / improvments  

### ISSUE THREAD

**Issue by wmdhosting** [craftcms/commerce#3405]
### Description

![Snag_12a43c81](https://github.com/craftcms/commerce/assets/76176291/9895723b-bfe2-467b-b05b-c8aae159e064)

![Snag_12a47ce5](https://github.com/craftcms/commerce/assets/76176291/b1b552c0-4670-419e-a4e8-7d2f2990b482)

### Craft CMS version

5

### Craft Commerce version

Beta1

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for reporting this. Discussing internally some of those issues and will let you know how we can improve things in relation to the variant edit links. The inventory and price issues will be fixed soon.

**Comment by nfourtythree** [comment]
Hi @wmdhosting 

Thank you for your message and giving us your feedback. I have distilled it into the following items:

1. Variant title link: This has now been [fixed](https://github.com/craftcms/commerce/issues/3431#issuecomment-2011670908)
2. Variant new window button: This has now been [fixed](https://github.com/craftcms/commerce/issues/3431#issuecomment-2011670908)
3. Price list currency: This has now been [fixed](https://github.com/craftcms/commerce/commit/e78a250ec11b90691b131b31d80a3c38fcf2d9b7)
4. Updating inventory amount: We have created a specific issue for this, you can follow along the progress here: https://github.com/craftcms/commerce/issues/3437

Thanks!
