### ISSUE TITLE
[5.x]: Unable to set a stores primary currency

### ISSUE THREAD

**Issue by phillmorgan28** [craftcms/commerce#3425]
### Description
We are currently unable to set a store's primary currency. The option to set a new currency as primary is not available in the control panel

### Steps to reproduce

1. Setup a new currency
2. Look around for the option to set a new primary

### Expected behavior
A button available to mark the new currency as primary

### Actual behavior
No option

### Craft CMS version

5.0.0-beta.6

### Craft Commerce version

5.0.0-beta.1

### PHP version

8.3

### Operating system and version

Ubuntu Linux

### Database type and version

MariaDB 11.3.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @phillmorgan28 

Thank you for your message.

You should be able to set a store's primary currency when creating a new store. If you wish to change a current store's primary currency you must first make sure there are no orders or carts in that store.

Hope this helps, thanks!

**Comment by phillmorgan28** [comment]
Hi @nfourtythree. Thanks for the response. I did consult the documentation and found this already. This installation is brand new, with zero orders and no active or inactive carts in existence, and I cannot find an option to change an existing stores primary currency.

Thanks

**Comment by phillmorgan28** [comment]
Please see below screenshots showing no option available

![Screenshot 2024-03-12 155944](https://github.com/craftcms/commerce/assets/13579386/389cb55e-866c-4dcd-9c89-38093d27bc75)
![Screenshot 2024-03-12 155955](https://github.com/craftcms/commerce/assets/13579386/f453e440-cdd0-4545-95f0-71c8e9fd54af)
![Screenshot 2024-03-12 160001](https://github.com/craftcms/commerce/assets/13579386/8ff0bb2d-2a1d-4a08-9572-95c1c7ac548a)
![Screenshot 2024-03-12 160008](https://github.com/craftcms/commerce/assets/13579386/b6b26eb4-e43c-446c-b8d0-2e2f7b960b38)
![Screenshot 2024-03-12 160020](https://github.com/craftcms/commerce/assets/13579386/7bd3e5ff-d307-4aab-9c6a-2b68e2326f30)

**Comment by nfourtythree** [comment]
Hi @phillmorgan28 

Thank you for your reply, if you head to the Stores section of the settings, click on your store and you should see a dropdown for currency where you will be able to change it.

Payment currencies are the alternate currencies that the store can take payment in on top of its base currency.

<img width="1270" alt="CleanShot 2024-03-12 at 16 01 59@2x" src="https://github.com/craftcms/commerce/assets/266453/d6a442fa-8b94-4d48-bffe-609d13ba4417">

Thanks!

**Comment by phillmorgan28** [comment]
HI @nfourtythree This option is not available to me

![image](https://github.com/craftcms/commerce/assets/13579386/ef05acca-061a-4ea6-9a61-8203eaa0f2e4)

**Comment by nfourtythree** [comment]
Hi @phillmorgan28 

If you have deleted any carts or orders, be sure to run garbage collection to make sure they have been fully removed.

This can be done via the garbage collection CLI command.

```
./craft gc/run
```

Thanks

**Comment by phillmorgan28** [comment]
Perfect! It was due to the single deleted cart that was created when I installed Commerce!

Many thanks!

As a suggestion, perhaps rather than removing the setting from view completely, present a disabled drop-down with some guidance? Although it's in the documentation to delete these items, it may not be clear that the trashed items must also be deleted to enable the ability to switch.

**Comment by nfourtythree** [comment]
Great that it is working!

And we will definitely take this feedback on board as we look to make improvements. 

Thanks!
