### ISSUE TITLE
When moving a disabled product variant to the first position it gets enabled.

### ISSUE THREAD

**Issue by Totemika** [craftcms/commerce#343]
### Description

When I have a set of disabled variants and I want to reorder without enabling them, the one I put in the first place gets enabled (and it's not the `default` variant)

### Steps to reproduce

![enabled-when-reordering](https://user-images.githubusercontent.com/4906291/40019908-82553fd0-57b8-11e8-9330-c1347e1e36c3.gif)
*Note: (I hit ⌘ + S to save and continue editing)*

### Additional info

- Craft version: Craft CMS 3.0.7
- PHP version: 7.X
- Database driver & version: mysql ?
- Plugins & versions: Commerce 2.0.0-beta.4.1

**Comment by lukeholder** [comment]
I can reproduce the issue. Looking into a fix now.
