### ISSUE TITLE
[5.x]: clicking a variant title in the variants field just reloads the page

### ISSUE THREAD

**Issue by bartrylant** [craftcms/commerce#3431]
### Description
When clicking a variant title in the variants field on a product page, it just reloads the page

### Steps to reproduce
1. go to a product entry
2. click a variant title

### Expected behavior
Edit the variant

### Actual behavior
Page reloads

### Craft CMS version

5

### Craft Commerce version

5

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @bartrylant 

Thank you for your message. We have pushed a fix for this which will be included in the next release of the Commerce 5 beta.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.0.x-dev#540793a07ab2ca264c6ba216dac7878424b96e12 as 5.0.0-beta.1",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
