### ISSUE TITLE
[5.x]: Column not found when trying to edit store settings

### ISSUE THREAD

**Issue by vnali** [craftcms/commerce#3433]
### Description
Trying to edit a store settings via commerce/settings/stores in latest dev, throws `column not found` -because the query doesn't properly add prefix table-
```
Unknown column 'elements.dateDeleted' in 'where clause'
The SQL being executed was: SELECT EXISTS(SELECT *
FROM `c5_commerce_orders`
LEFT JOIN `c5_elements` ON `elements`.`id` = `commerce_orders`.`id`
WHERE (`storeId`=2) AND (`elements`.`dateDeleted` IS NULL))
```

### Craft CMS version

5.0.0-beta.10

### Craft Commerce version

5.0.x-dev

### PHP version

8.2

### Database type and version

MariaDB 10.6.7

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
HI @vnali 

Thank you for bringing this to our attention. We have pushed a fix for this which will be included in the next release of Commerce 5 beta.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.0.x-dev#3d0ab9eca6d9eee5ef2f0c75897e338bfd3e0bb6 as 5.0.0-beta.1",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
