### ISSUE TITLE
[4.x]: Order reference not included in search index update

### ISSUE THREAD

**Issue by bjerringgaard** [craftcms/commerce#3436]
### What happened?

What happened?
- Since updating to Craft 4.8 & Commerce 4.5 New orders no longer get the reference indexed.
- If I resave / Update old orders, the reference dissapears.

Notes:
I have a couple og programatically saveElements, but non of them disables search indexing.

Files:
![before](https://github.com/craftcms/commerce/assets/36016260/b2651f7a-c6fd-4ae7-9698-1183e04a2aec)
![after](https://github.com/craftcms/commerce/assets/36016260/cdbad9b3-5ce8-4fd3-97a0-267197d29e13)

### Craft CMS version

4.8.4

### Craft Commerce version

4.5.2

### PHP version

8.1.27

### Database type and version

MariaDB 10.6.14

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @bjerringgaard 

Thank you for your message, I have just tested this and I can see that the references are getting added to the search index.

This is with the latest version of Craft and Commerce. They should be under the `reference` attribute if you look in the `searchindex` table in the database, as shown here:

<img width="748" alt="CleanShot 2024-03-20 at 13 54 48@2x" src="https://github.com/craftcms/commerce/assets/266453/b4614ecc-c66c-443d-98dd-454abb43d3f5">

It is still [listed as a searchable attribute](https://github.com/craftcms/commerce/blob/c5cf19b7c62c1159ca3dfef1934ed0e0ea44032d/src/elements/traits/OrderElementTrait.php#L244). After saving an old order does the reference still show as expected when you view the order in the order index or the edit order page in the control panel?

Are you hooking into the `EVENT_REGISTER_SEARCHABLE_ATTRIBUTES` event at all?

Thanks.

**Comment by bjerringgaard** [comment]
Hi @nfourtythree 

Thank you for taking the time to reply, I have tried updating one of our other sites, and have no issue there either.

After doing some digging, i found out that a plugin we are using (craft-relax) is removing all numeric indexes, including the order reference.
