### ISSUE TITLE
[5.x]: Inventory available amounts do not update when editing a variant

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#3437]
### Description

When editing a variant and editing an available inventory amount the inventory table does not update after editing.

<img width="1055" alt="CleanShot 2024-03-21 at 08 59 10@2x" src="https://github.com/craftcms/commerce/assets/266453/eec7556d-5ed5-433d-96ff-cd5606e7f907">

### Craft CMS version

5 beta

### Craft Commerce version

5 beta

### PHP version

8.2

**Comment by lukeholder** [comment]
Should be fixed now, thanks.
