### ISSUE TITLE
[4.x]: Craft commerce - Can't delete shipping option via dialog menu

### ISSUE THREAD

**Issue by Codesesh** [craftcms/commerce#3444]
### Description

When trying to delete a shipping option via Shipping menu in craft commerce it is not allow it using the dropdown dialog.

Video here showing it in action:

https://app.screencastify.com/v3/watch/MiAHTSQEz5QZUs4v2KJe

### Steps to reproduce

Video: https://app.screencastify.com/v3/watch/MiAHTSQEz5QZUs4v2KJe

### Expected behavior

Should delete the option

### Actual behavior

Nothing happening, option remains undeleted

### Craft CMS version

Craft Pro 4.8.6 & Craft Commerce	4.5.2

### PHP version

	8.2.10

### Operating system and version

Linux 5.4.0-155-generic

### Database type and version

MySQL 5.7.37

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Admin Bar	4.3.0
Algolia	4.0.0
Complete Cookie Consent	1.1.1
Craft Commerce	4.5.2
Feed Me	5.4.0
Formie	2.1.7
MailerSend	1.0.1
Payment Express for Craft Commerce	2.0.0
Postie	3.1.6
Redactor	3.0.4
Retour	4.1.16
Scout	4.0.0
SEOmatic	4.0.45
Sprig	2.8.0
Super Table	3.0.12
Vite	4.0.9

**Comment by lukeholder** [comment]
@Codesesh Can you confirm you are on the latest version. I only see delete buttons on the row (see screenshot) and no delete action for the table:

![CleanShot 2024-04-02 at 13 55 52@2x](https://github.com/craftcms/commerce/assets/133571/2d492028-5195-4ac5-87d3-ee2e1c029ee8)


Can you let me know if the delete button on the row works for you?

**Comment by Codesesh** [comment]
@lukeholder - Currently sitting on Craft Pro 4.8.6 and commerce 4.5.2. Will get devs to update to latest and see if that fixes it.

**Comment by lukeholder** [comment]
@Codesesh any updates?

**Comment by nfourtythree** [comment]
Hi @Codesesh 

Thank you for raising this with us. We are pushing a fix for the issue, there is an update required for both Commerce and Craft to fix the issue.

We will let you know when the fixes have been released.

Thanks!

**Comment by brandonkelly** [comment]
Craft CMS 4.9.0 and Craft Commerce 4.6.0 are out now, with the fix for this.
