### ISSUE TITLE
[5.x]: Users with restricted site access rights can see all orders for all sites

### ISSUE THREAD

**Issue by gopeter** [craftcms/commerce#3446]
### Description

Users with restricted site access rights can see all orders for all sites.

### Steps to reproduce

1. Create two sites (A & B) and two shops (1 & 2) and assign them like a 1:1 relation: A --> 1 and A --> 2
2. Create an user and restrict access to site A
3. Create an order on site B
4. Login as this user and view orders
5. The user now is able to see the order that is placed on site A even if he has just access for site B

### Expected behavior

The user should see just the orders that where placed on the site he has rights for.

### Actual behavior

The user can view all orders, regardless of his access rights.

### Craft CMS version

5.0.1

### Craft Commerce version

5.0.0-beta.2

### PHP version

8.2.13

### Installed plugins and versions

- Craft Commerce: `5.0.0-beta.2`
- Gift Voucher: `4.0.0-beta.2`
- Mollie for Craft Commerce: `4.2.0`

**Comment by nfourtythree** [comment]
Hi @gopeter 

Thank you for bringing this to our attention. We have just pushed up a fix for this issue which will be included in the next released of the Commerce 5 beta.

Thanks!

**Comment by brandonkelly** [comment]
Commerce 5.0.0-beta.3 is out with that fix. Thanks again @gopeter!

**Comment by gopeter** [comment]
Hi @nfourtythree and @brandonkelly, it seems that this happens again. I'm on Craft Pro 5.2.8 and Commerce 5.0.14.

**Comment by nfourtythree** [comment]
Hi @gopeter 

I can't seem to replicate this or perhaps I am not taking the same steps you are? Below are two examples, the first is a user with access to everything and the second is a user that only has access to one site. As you can see the second user cannot select the site that they do not have access to.

![CleanShot 2024-08-09 at 08 00 29](https://github.com/user-attachments/assets/7bc045e5-bec1-4144-aa73-6bf7a7349d47)

![CleanShot 2024-08-09 at 08 04 04](https://github.com/user-attachments/assets/c54e9b39-6350-4a66-a91a-2300d9d964ae)

Please let me know if there are different steps to take to reproduce the issue, thanks!

**Comment by gopeter** [comment]
Hi @nfourtythree,

strange. Here's a screenshot from a user who has access to a few sites only, but he sees all orders that we have in the system:

![image](https://github.com/user-attachments/assets/9318483c-478e-4290-adfc-24bb644bfef6)

Like this one:

![image](https://github.com/user-attachments/assets/c13318ec-7b19-46dc-941d-4e00efd5c22e)

I'm not sure what you may need to reproduce this on your side 🤔

**Comment by gopeter** [comment]
I created a fresh Craft installation, created a Order on site A, created another user with access to site B only. But when I login as user B, I can see the order from site A though (see last column "Bestellseite"/"Order Site" ).

![image](https://github.com/user-attachments/assets/52d85ac2-9dcb-461e-96a6-8d59f687f706)

**Comment by gopeter** [comment]
I've just tried the latest beta of Craft Commerce 5.1, but the issue still exists.
My user, who is access to the Italy sites only, can see orders that were made on the Belgium sites:

![image](https://github.com/user-attachments/assets/5fb0da59-109c-4b41-b74d-bef098f3d253)

**Comment by gopeter** [comment]
Could it be that this is limited to the stores? Because I have one store which is activated for all sites. Do you have one store per site active on your Spoke & Chain demo? Then this may be the problem?

# Update

Yes, it's like it thought: https://github.com/craftcms/commerce/blob/5.x/src/elements/traits/OrderElementTrait.php#L306
