### ISSUE TITLE
[4.x]: commerceCurrency formatting "?" instead of "."

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#3447]
### Description
We are using commerceCurrency twif filter for formatting the order price. But in the french language the "." is removed. In the order invoice PDF the "." is replaced by a "?".
PDF behavior:
 ![image](https://github.com/craftcms/cms/assets/22771556/ef373e72-e031-45fd-a4f9-acfdf0f00d05)
Cart behavior:
 ![image](https://github.com/craftcms/cms/assets/22771556/33b496b1-a259-4c27-9aea-18882818cfb3)

### Steps to reproduce

1. {{ order.total|commerceCurrency(order.currency) }}
2. "order.currency" is "EUR"
3. language is french 

### Expected behavior
Displaying the price in the french language as X.XXX,XX€

### Actual behavior
The price is displaying in the french language as X?XXX,XX€

### Craft CMS version

4.8.0

### Craft Commerce version

4.5.2

### PHP version

8.2.10

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

Thank you for your message, I have just added a test for this to see what might be happening: https://github.com/craftcms/commerce/commit/ff0563d370006b694e509e862c090e53b3fbe594

I think this could be an issue with a non-breaking space character. The `i18n` formatter seems to return the values with those characters for the French language, which does make sense as you wouldn't want the string wrapping when output.

Guessing here, a combination of the font and the PDF rendering is causing the character to show differently?

Could you try stripping/replacing those characters in the PDF template?

Thanks

**Comment by WHITE-developer** [comment]
Hi @nfourtythree,

Thanks for the help!
We have found the problem "Dompdf" used to format a "narrow nsbp;" to a "&nsbp;" and in the newer version it leaves a "narrow nsbp;" our pdf font does not support it and when we changed font, it displayed correctly.
