### ISSUE TITLE
[5.x]:  Few things

### ISSUE THREAD

**Issue by wmdhosting** [craftcms/commerce#3455]
### What happened?

1. When adding  new  Location.  it says **add address after**.. but then you need to go to totaly different  page and click on that location.. to add adddress.. but first you need to knwo that there is option for that.. 
![Snag_16180bff](https://github.com/craftcms/commerce/assets/76176291/20d330ba-4e16-4ea5-a3eb-964ab38ae4f1)

2. When changing stock in Product Entry   Manage or any option need to be Slide in..  like this you get lost. pretty quick.. 

![Snag_1616e5fd](https://github.com/craftcms/commerce/assets/76176291/89ba141f-245e-489d-9857-d7f54c367fb0)

### Craft CMS version

5.0.4

### Craft Commerce version

Beta 3

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @wmdhosting 

Thank you for bringing this to our attention.

We have made some improvements around the management and assignment of inventory locations. We have pushed these updates and they will be included in the next release of the Commerce beta.

Thanks!
