### ISSUE TITLE
Provide Example on Creating Dynamic Shipping Rule + Method

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#346]
Can you provide an example of how you would create a dynamic shipping method and rule?

It looks like rates were removed from shipping methods in Craft 2 and are now included in the rules themselves.

We're essentially querying an outside service to determine dynamic shipping rates and would need to create a method and rule based on the results of that query.

Thank you!

**Comment by lukeholder** [comment]
@bryantAXS in Commerce 2?

**Comment by lukeholder** [comment]
The price was always returned by a shipping rule that belongs to a shipping method.

I will document making shipping methods/rules in the docs and will update here once complete.

**Comment by lukeholder** [comment]
Did the initial documentation creation here (WIP):

https://github.com/craftcms/commerce-docs/blob/v2/en/shipping-methods.md

It should get you going.
