### ISSUE TITLE
[5.x]: Sending email for order hangs

### ISSUE THREAD

**Issue by atelierbim** [craftcms/commerce#3476]
### Description

Sending email for order hangs forever in pending state and never gets sent.

### Steps to reproduce

1. Place an order

### Expected behavior
Orders email where always immediately sent.

### Actual behavior

this can never gets sent:

<img width="991" alt="Capture d’écran 2024-05-01 à 15 01 04" src="https://github.com/craftcms/commerce/assets/64537972/41f61d19-1389-4e23-84e1-72bd2ab6a9d6">

### Craft CMS version

5.1.0

### Craft Commerce version

5.0.1

### PHP version

8.2

### Operating system and version

craft cloud

### Database type and version

mysql 8

### Installed plugins and versions

-
mailgun 3.1.0

**Comment by lukeholder** [comment]
Thanks for reporting. This has been fixed for the next release.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#2acf82f43928eddd2b9b4675a91373fdb2cd8243 as 5.0.1",
  "...": "..."
}
```

Thanks

**Comment by lukeholder** [comment]
@atelierbim We will update this issue when it's included in an official release.

**Comment by lukeholder** [comment]
Commerce 5.0.2 is now out with this fix.
