### ISSUE TITLE
[5.x]: "Download PDF" in orders overview does not work

### ISSUE THREAD

**Issue by MatthiasBrodelet** [craftcms/commerce#3477]
### Description
The "Download PDF" button in the orders overview does not work.
It does show the modal where you can choose which PDF and download type you would like but the download button itself does not do anything.
In comparison to Craft 4 there is no form element present in the element action.
By extension the javascript which submits the form does not do anything.

### Steps to reproduce
1. Create an order
2. Select one or more orders
3. Click the "Download PDF" button and click "Download"

### Expected behavior
It should submit a form that triggers the performAction method in the element action.
This then should download a ZIP or PDF file.

### Actual behavior
The modal opens but nothing is being downloaded.

### Craft CMS version

Craft Pro 5.1.0

### Craft Commerce version

5.0.2

### PHP version

8.2.17

### Operating system and version

Linux 6.3.13-linuxkit

### Database type and version

MySQL 8.0.19

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Craft commerce

**Comment by nfourtythree** [comment]
Hi @MatthiasBrodelet 

Thank you for raising this issue.

We have pushed a fix which will fix the problem, this fix will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#c278b5cccdf794f2e2a83dac89668a7c3fdc80c5 as 5.0.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce `5.0.3` has been released with this fix included.

Thanks!
