### ISSUE TITLE
[5.x]: Commerce slows down Craft  for 300-400%

### ISSUE THREAD

**Issue by wmdhosting** [craftcms/commerce#3481]
### Description

Testing Commerce.. now  and what i see when i enable Commerce  
All Pages non related to Commerce , Section index pages. entries and so on.. 
load much slower  300-400% .. than without commerce..

![2024-05-06_09-45-33](https://github.com/craftcms/commerce/assets/76176291/da489e07-d578-4288-a261-8a2856d78cfb)
![2024-05-06_09-48-43](https://github.com/craftcms/commerce/assets/76176291/a12a67b6-cc9c-4591-ae5e-33707b547bfa)

when i disable commerce it.. all pages load quite fast...

### Craft CMS version

5.1.1

### Craft Commerce version

5.0.3

### PHP version

8.2.16

### Operating system and version

CloudLinux v8.9.0

### Database type and version

MySQL 8.0.36

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
I have just attempted to reproduce and couldn't see much difference: 

![CleanShot 2024-05-06 at 16 22 37@2x](https://github.com/craftcms/commerce/assets/133571/9bdaebfa-8666-43a8-9c0a-737ab455151b)

![CleanShot 2024-05-06 at 16 24 34@2x](https://github.com/craftcms/commerce/assets/133571/6a884884-bdc1-433a-85e4-7ee9ec29d136)

But my site could be totally different to yours.

Could you possibly send to support@craftcms.com the following:

DB backup
composer.json
composer.lock
config/project

...and we will see if there is anything obvious going on. Thanks.

**Comment by nfourtythree** [comment]
Hi @wmdhosting 

Thank you for reporting this. We managed to track down a performance improvement using the files you sent.

We have pushed a fix for this which will be included in the next release of Commerce 5.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#3815a75e8e9f4c515a7c098a547282a42ca3425d as 5.0.6",
  "...": "..."
}
```

Then run `composer update`.

**Comment by lukeholder** [comment]
5.0.7 is now out with this fix! Thanks.
