### ISSUE TITLE
[5.x]: Unknown column 'commerce_products.promotable' in 'where clause'

### ISSUE THREAD

**Issue by stanislavprokopov** [craftcms/commerce#3483]
### Description

Using this in twig:

`{% set sale = craft.products().hasVariant({ hasSales: true }).all() %}`

Causes:

`Column not found: 1054 Unknown column 'commerce_products.promotable' in 'where clause'`

Caused by this line https://github.com/craftcms/commerce/blob/37c8af23fde9a6312812f19d296a5cd57ec05b8f/src/elements/db/VariantQuery.php#L493

### Steps to reproduce

Add example to twig and refresh page.

### Expected behavior

Should work i guess or should be another way of getting products/variants on sale.

### Craft CMS version

5.1.1

### Craft Commerce version

5.0.3

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for reporting.

This has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#d3f822b6a0e898b06a7590432f1acb22e9a38530 as 5.0.3",
  "...": "..."
}
```

Then run `composer update`.

I will let you know here once the release is out.
