### ISSUE TITLE
[5.x]: Discounts and Pricing Rules locations in CMS

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/commerce#3484]
### Description
We usually don't give clients access to the Store Management page, as we set this up for them. Since Commerce 5 the `Discounts` and `Pricing` Rules have moved over to the Store Management page, requiring us to give clients access to the tab. 

My initial thought was to give users access to this area, without all other options there, but by doing so, you automatically also have access to the `Currency` and `General` settings because those don't have specific permission settings to them, which is not something we want.. In addition to that, when setting it up this way, the CMS still shows the other sidebar heading (shipping and tax), even though there are no items for that user under those.

It would be great if we could revert this move, and just have 'promotions' in the sidebar again, like how it worked before.

### Craft CMS version

5.1.1

### Craft Commerce version

5.0.3

**Comment by lukeholder** [comment]
Agree this is not ideal. Will make some improvements soon. More than likely the store management permission will remain, but that will just give you access to the store management, and we will do a better job with showing and hiding the nav items you have access to in there.

**Comment by lukeholder** [comment]
This will be resolved along with new permissions in 5.1 Thanks!

**Comment by lukeholder** [comment]
@mikesnoeren  5.1 is now out!
