### ISSUE TITLE
Quantity counted twice in getLineItemRules? (Craft Commerce 2)

### ISSUE THREAD

**Issue by bleepsandblops** [craftcms/commerce#349]
### Description
Whenever I have an item with a stock of 1, the add to cart fails because the rule tries to validate an addition of 2 items.

I'm a bit out of my depth but it looks like it's due to this bit in Variant.php:
```
// count new line items
if ($lineItem->id === null) {
    $qty[$item->purchasableId] = $lineItem->qty;
}
if ($item->id == $lineItem->id) {
    $qty[$item->purchasableId] += $lineItem->qty;
} else {
    // count other line items with same purchasableId
    $qty[$item->purchasableId] += $item->qty;
}
```
If it's a new line item, the second if test should be skipped:
```
// count new line items
if ($lineItem->id === null) {
    $qty[$item->purchasableId] = $lineItem->qty;
} else {
  if ($item->id == $lineItem->id) {
      $qty[$item->purchasableId] += $lineItem->qty;
  } else {
      // count other line items with same purchasableId
      $qty[$item->purchasableId] += $item->qty;
  }
}
```

### Steps to reproduce

1. Make a variant with a stock of 1
2. Try to add it to the cart

### Additional info

- Craft version: 3.0.8
- PHP version: 7.2.5
- Database driver & version: mysql 5.6.24
- Plugins & versions: Craft Commerce 2.0.0-beta.4.1

**Comment by lukeholder** [comment]
Thanks for reporting. Will be fixed in the next release.
