### ISSUE TITLE
[5.x]: HTTP 404 when deleting shipping method rule or saving as new

### ISSUE THREAD

**Issue by stanislavprokopov** [craftcms/commerce#3490]
### Description
Try to delete a shipping method rule or try to save as new rule, after clicking Yes in the confirmation popup you will be redirected to `admin/commerce/shipping/shippingmethods/1`, this path is not correct, correct one should be `admin/commerce/store-management/primary/shippingmethods/1`.

https://github.com/craftcms/commerce/blob/323ac6403f8a91812af074811fab37fb5e021e93/src/templates/store-management/shipping/shippingrules/_edit.twig#L35

### Craft CMS version

5.1.1

### Craft Commerce version

5.0.3

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for reporting that. We have fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#c8f52cf550b37ac0295770301b2403ebdd7a0632 as 5.0.5",
  "...": "..."
}
```

Then run `composer update`.

We will update this issue once the release is out.
