### ISSUE TITLE
[5.x]: Migration m221122_055724_move_general_settings_to_per_store_settings fails

### ISSUE THREAD

**Issue by TheFunkyMonk** [craftcms/commerce#3492]
### Description
Migration `m221122_055724_move_general_settings_to_per_store_settings` fails when updating from Commerce 5.0.3 to 5.0.4 with the following error:
```
add column autoSetNewCartAddresses boolean NOT NULL DEFAULT FALSE to table {{%commerce_stores}} ...Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'autoSetNewCartAddresses' 
```

Database backup and composer files have been sent to support@craftcms.com for reference.

### Craft CMS version

5.1.2

### Craft Commerce version

5.0.3

### PHP version

8.2.15

### Operating system and version

Linux 6.5.0-15-generic

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

"craftcms/ckeditor": "4.0.4",
"craftcms/commerce": "5.0.3",
"craftcms/commerce-paypal-checkout": "3.0.0",
"craftcms/commerce-stripe": "5.0.1",
"craftpulse/craft-colour-swatches": "5.0.0",
"doublesecretagency/craft-cpcss": "3.0.0",
"mmikkel/retcon": "3.0.0",
"nystudio107/craft-imageoptimize": "5.0.0",
"nystudio107/craft-retour": "5.0.0",
"nystudio107/craft-seomatic": "5.0.2",
"putyourlightson/craft-sprig": "3.0.1",
"servd/craft-asset-storage": "4.0.3",
"spicyweb/craft-neo": "5.0.0-beta.10",
"verbb/default-dashboard": "3.0.0-beta.1",
"verbb/field-manager": "4.0.0-beta.1",
"verbb/image-resizer": "4.0.0-beta.1",
"vlucas/phpdotenv": "^5.4.0",
"wbrowar/guide": "4.0.0-beta.1"

**Comment by AndrewMac** [comment]
Same error with me …

**Comment by lukeholder** [comment]
Apologies, 5.0.5 is now out with a fix for that migration.
