### ISSUE TITLE
[5.x]: `Show the Dimensions and Weight fields for products of this type ` switch not working

### ISSUE THREAD

**Issue by lukas-jansen** [craftcms/commerce#3493]
### Description
The `Show the Dimensions and Weight fields for products of this type` setting on product types does not work. The fields are always shown even when the switch is disabled

### Steps to reproduce

1. create a product type
2. disable the `Show the Dimensions and Weight fields for products of this type` lightswitch
3. dimension fields are still shown

### Expected behavior
the dimension and weight fields should not been shown

### Actual behavior
fields keep showing

### Craft CMS version

5.1.2

### Craft Commerce version

5.0.5

### PHP version

8.3.6

### Operating system and version

ubuntu 24.04

### Database type and version

mysql 8.0

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks, this is fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#38e245dee6eed61cfe63066dce4925003a6cf310 as 5.0.5",
  "...": "..."
}
```

Then run `composer update`.

We will also update this ticket once the release is out.

**Comment by lukeholder** [comment]
Craft Commerce 5.0.6 is now out!
