### ISSUE TITLE
[Commerce 2] Entry Template not recognizing Product ID when logged in

### ISSUE THREAD

**Issue by pixelbeatcreative** [craftcms/commerce#350]
### Description
I have a standard `_entry` template with standard fields (ie. variants, title, assets, etc) for products. As long as I'm not logged into Craft, everything works as should. Meaning if I navigate to a product, it takes me to the `_entry` template, and the correct info for that product is rendered. However, if I log **into** Craft and then navigate my products on the frontend, the URL will update correctly `website.com/product/002` but the `_entry` template will only render the very first product that was entered into Craft. No matter what product is navigated to on the frontend, even though the URI will be correct, the content will stay the same.

When I enter `{{ product.id }}` in the template, I can see that for some reason, it keeps rendering the product id of that very first product entry.

### Steps to reproduce
Stated above.

### Additional info
- Craft version:  3.0.8
- PHP version:  7.2.1
- Database driver & version:  MySQL 5.6.38
- Plugins & versions:  Commerce 2 (beta 4.1)

**Comment by lukeholder** [comment]
Hi @pixelbeatcreative could you share your templates? If not wanting to share here, please send to support@craftcommerce.com

**Comment by pixelbeatcreative** [comment]
Sure thing @lukeholder ! I just emailed everything to you. Please let me know if you need anything else from me. Thanks!

**Comment by lukeholder** [comment]
This was resolved as a template issue where the `product` variable was being overridden in the parent templates.
