### ISSUE TITLE
[5.x]: ->hasVariant(['hasStock' => true]) throws a DB error of Unknown column 'purchasables_stores.hasUnlimitedStock'

### ISSUE THREAD

**Issue by sunscreem** [craftcms/commerce#3505]
### Description

When running the following query:

```php

\craft\commerce\elements\Product::find()->status(Product::STATUS_ENABLED)->hasVariant(['hasStock' => true])->all()

```

The following error is thrown:

```txt

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'purchasables_stores.hasUnlimitedStock' in 'where clause'
The SQL being executed was: SELECT COUNT(*)
FROM `elements` `elements`
[rest of query]

```

### Steps to reproduce

1. Clean install Craft 5 & Craft Commerce.
2. Create somewhere to run the above code (I used a module)
3. Run the query above.

### Expected behavior

Return an array of "in stock" products.

### Actual behavior

Throws the above error.

### Craft CMS version

5.1.4

### Craft Commerce version

5.0.6

### PHP version

8.2

### Database type and version

mysql

### Installed plugins and versions

- none

**Comment by lukeholder** [comment]
Thanks for reporting this!

We have fixed the error.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#5348e43b58a9ee2b0335de999337bdb9cdbeff68 as 5.0.6",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the next release is out.

Thanks!

**Comment by sunscreem** [comment]
@lukeholder Thank you - That's it working with the fix.

**Comment by lukeholder** [comment]
5.0.7 is now out with this fix! Thanks.
