### ISSUE TITLE
[5.x]: Migration error when upgrading from Commerce 4

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#3506]
### Description

See https://github.com/craftcms/commerce/issues/3488#issuecomment-2106813410

### Craft CMS version

5

### Craft Commerce version

5

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
This should be fixed in 5.0.6

**Comment by lukeholder** [comment]
Let me know if it continues, but the commit cf03b5111e672d0fdad83c6365ea8513e99d97fa fixed this in 5.0.6
