### ISSUE TITLE
CreditCardPaymentForm::setAttributes wipes 'number' if not passed

### ISSUE THREAD

**Issue by nateiler** [craftcms/commerce#351]
https://github.com/craftcms/commerce/blob/ae4a6c2bdb3b3df0d6846f8866c23619af19d7d0/src/models/payments/CreditCardPaymentForm.php#L78

Not sure if this is by design, but attempting to set attributes (which does not include 'number') results in the number getting wiped.  My assumption would be to check if set (similar to 'expiry').

Since we don't 100% know the attributes on a 'PaymentForm' the `setAttributes()` method is a handy way to set multiple attributes without throwing an exception if one doesn't exist.

```
        Craft::configure(
            $paymentForm,
            [
                'firstName' => $user->firstName,
                'lastName' => $user->lastName,
                'foo' => 'bar'
            ]
        );
```
-vs-

```
        $paymentForm->setAttributes([
            'firstName' => $user->firstName,
            'lastName' => $user->lastName,
            'foo' => 'bar'
        ], false);
```

**Comment by lukeholder** [comment]
@nateiler You should really know the attributes expected on a payment form though. In this case, the credit card form is expecting the `number` param to be submitted. The `{{gateway.getPaymentFormHtml()}}` will output a working form for the gateway with the correct fields.

**Comment by nateiler** [comment]
Understood.  Breaking the rules typically ends up in scenarios like this...

Event's will need to understand that the number gets wiped if any additional setAttributes are made alterations.  I find it odd that setting additional attributes will unset others.

For what it's worth, we're not allowing the firstName and lastName to be submitted via form submission and apply it after the fact based on the logged in user ... which is where this came into play.
