### ISSUE TITLE
[5.x]: Example templates not correctly checking stock

### ISSUE THREAD

**Issue by TheFunkyMonk** [craftcms/commerce#3510]
### Description
In the Commerce 5 example templates, I noticed most of our products were showing "out of stock" on the front end. If I'm understanding the stock setup correctly, having the "Inventory" toggle turned off for a variant is used to indicate unlimited/infinite stock (which also is what displays the ∞ in the table column).

Looking at the check in `products/_includes/grid.twig`, I see it's using `variant.stock` as the check for whether a variant is in stock, but looking at the docs it seems [variant.hasStock()](https://craftcms.com/docs/commerce/5.x/system/inventory.html#stock) is the correct way to check now (which functions as I'd expect in my template).

### Craft CMS version

5.1.4

### Craft Commerce version

5.0.6

**Comment by lukeholder** [comment]
Thanks this is fixed for the next release. You can use this in your templates in the meantime:

```twig
{% if variant.inventoryTracked %}({{ variant.stock ? variant.stock ~ ' available' : 'out of stock'}}){% endif %}
```

**Comment by lukeholder** [comment]
5.0.7 is now out and fixes this issue. Thanks!
