### ISSUE TITLE
[5.x]: Pricing rules can't be disabled

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/commerce#3515]
### Description
When disabling a pricing rule by either settings it's status to disabled, or unchecking "Enable this rule", the pricing rule is still active. Both in the CMS, and in the front-end.

### Steps to reproduce

1. Create Pricing Rule (-10%)
2. Check if pricing rule works
3. Disable pricing rule in CMS
4. Check in CMS, or on front-end, to see the pricing rule is still on.

### Craft CMS version

5.1.4

### Craft Commerce version

5.0.6

### PHP version

8.2.15

### Operating system and version

Linux 6.7.10-orbstack-00140-g04c64cb35a2e

### Database type and version

MySQL 8.0.33

### Image driver and version

GD 8.2.15

**Comment by nfourtythree** [comment]
Hi @mikesnoeren 

Thank you for bringing this to our attention, we have pushed a fix which will be included in the next release of Commerce 5.

Thanks!

**Comment by nfourtythree** [comment]
Commerce `5.0.7` has been released with this fix.
