### ISSUE TITLE
Register elements with EVENT_REGISTER_ELEMENT_TYPES

### ISSUE THREAD

**Issue by sjelfull** [craftcms/commerce#352]
### Description

The Commerce element types isn't registered with `EVENT_REGISTER_ELEMENT_TYPES`, which means they are not available via `getAllElementTypes()`.

### Steps to reproduce

1. Check for any references to `EVENT_REGISTER_ELEMENT_TYPES` in the codebase.

### Additional info

- Craft version: 3.0.8
- PHP version: 7.1
- Plugins & versions: 2.0.0-beta.4.1

**Comment by lukeholder** [comment]
Thanks for reporting, fixed in the next release.
