### ISSUE TITLE
[5.x]: store location edit button does not open slideout by default

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#3536]
### Description

In store management/general we have list of locations. After clicking three dots next to the location and selecting "edit" i expected slideout to open. But instead i was moved to separate page.

### Craft CMS version

5.1.1.0

### Craft Commerce version

5.0.9

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Thank you for your message.

Is this for editing the store location or the inventory locations associated to the store?

Thanks.

**Comment by piotrpog** [comment]
This would be store locations - store managment/general, clicking three dots and selecting "edit". I expected this should trigger slideout.

![image](https://github.com/craftcms/commerce/assets/42622545/33a09393-3c24-4132-89ab-a9936f0c2dd8)

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Clicking edit next to Store Location (as you said in your message) seems to work as expected for me.


https://github.com/craftcms/commerce/assets/266453/8e02c65a-e6ac-4d35-8721-1b5df425b92e

Thanks

**Comment by piotrpog** [comment]
@nfourtythree 
How about on the bottom of this page, under "inventory locations" header, in "default" tile?

**Comment by nfourtythree** [comment]
HI @piotrpog 

Ah so you are looking at the inventory locations.

These are specifically designed to not open in a slide out. This is the same reason why they have their own side bar navigation item.

Inventory locations are not owned by any one particular store but rather just associated with which ever stores used them. For this reason we opted not to have a slide out to avoid any confusion to when editing this data, by taking the user to the specific edit page this is to show that the changes you are making are not for one specific store but global across the system.

Hope this helps, thanks!

**Comment by piotrpog** [comment]
@nfourtythree 
Thank you for the explanation.
