### ISSUE TITLE
[5.x]: Can't delete currency

### ISSUE THREAD

**Issue by gopeter** [craftcms/commerce#3548]
### Description

I want to delete a currency in this screen.

![image](https://github.com/craftcms/commerce/assets/1242960/95a68a85-6751-455d-a0ae-4cfb546b16f3)

But once I click on the delete button, I get "Couldn’t delete “CHF”."

That's because the ID of the currency isn't sent:

![image](https://github.com/craftcms/commerce/assets/1242960/4a0b0dd4-c198-469a-bd8a-372ab101ea08)

![image](https://github.com/craftcms/commerce/assets/1242960/5b30d892-8c18-43d3-adc5-90904691dbd3)

### Craft CMS version

5.2.2

### Craft Commerce version

5.0.11

**Comment by lukeholder** [comment]
Thanks for reporting. This has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#c76b7cea4a70d202ba846dbf437382725c6352c5",
  "...": "..."
}
```

Then run `composer update`.

We will update this issue once the release it out.

**Comment by nfourtythree** [comment]
Hi

Commerce version `5.0.12` has been released with this update included.

Thanks!
