### ISSUE TITLE
[5.x]: Required custom order field not validated when posting to /commerce/cart/update-cart

### ISSUE THREAD

**Issue by MatthiasBrodelet** [craftcms/commerce#3552]
### Description
I have created a custom order field with handle telephoneNumber.
This has been set to required in the field layout.
However when posting from the front end the field does not throw any errors when left empty.
If I enter a value it does save correctly to the cart / order so that part seems to work fine.

### Steps to reproduce

1. Create custom order field
2. Set as required
3. Add it to the HTML with name fields[telephoneNumber]
4. Post form to /commerce/cart/update-cart

### Expected behavior
The field should be validated

### Actual behavior
I am able to bypass the required field

### Craft CMS version

Craft CMS 5.2.3

### Craft Commerce version

5.0.11.1

### PHP version

8.2.17

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Make sure the [validateCartCustomFieldsOnSubmission](https://craftcms.com/docs/commerce/5.x/configure.html#validatecartcustomfieldsonsubmission) setting is set to true.
