### ISSUE TITLE
[3.x]: hasSales attribute not filtering out items that are not promotable

### ISSUE THREAD

**Issue by mcclaskiem** [craftcms/commerce#3553]
### Description

I have a weird issue where items that are not promotable are showing up when I use the hasSales attribute set to true on a variant query:

    {% paginate craft.products({
        relatedTo: params,
        limit: 15,
        order: 'sku asc',
        with: [['frontImage', {withTransforms: ['viewAll']}]],
        hasVariant: variantQuery
    }) as pageInfo, products %}

     {% set variantQuery = {
        hasStock: true,
        hasSales: saleItems ? true : false
    } %}

I have a query parameter that is being passed from the frontend to determine if the user is looking for on sale items or not

### Steps to reproduce

1.

### Expected behavior
Expect that returned results will all have active sales when user requests "sales items"

### Actual behavior

Showing all items related to their filtered query

### Craft CMS version

3.9.5

### Craft Commerce version

3.4.23

### PHP version

7.4

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
I was ~able~ unable to reproduce this issue:

{% paginate craft.products.hasVariant({hasSales: true}).limit(100) as pageInfo, pageProducts %}

this showed items on sale, and passing false showed items not on sale.

Should the `variantQuery` variable be set before you pass it into the pagination query?

**Comment by mcclaskiem** [comment]
The variantQuery variable is set before being passed I just pasted both
code snippets in no particular order.

To add some more context:

I have a sale that is applied to certain category of products, basically a
specific designer. We don’t want all of the products from that designer to
be on sale so I have some set with “promotable” disabled however those
products still show up on the sale page.

**Comment by lukeholder** [comment]
I made a typo on my last response. I was UNable to reproduce. Could you send you database backup, composer.json and composer.lock to support@craftcms.com so we can take a look. Please reference this issue when you submit the support ticket. Thanks.

**Comment by mcclaskiem** [comment]
@lukeholder Just sent it over via email. Thanks for taking a look!

**Comment by nfourtythree** [comment]
Hi @mcclaskiem 

We have just released Commerce `3.4.24` which has a fix for this included.

Please update to this version and let us know if you have any further issues.

Thanks!

**Comment by terryupton** [comment]
I have two craft commerce 3 websites and there is an updated `3.4.24`
I have tried to run this on both sites using `composer update`

The composer requirement looks like this;
` "craftcms/commerce": "^3.4.23",`

But it keeps telling me there is an update `3.4.24` in the backend.
But it looks like it is installed to `3.4.24`

Any ideas?

Thanks.

**Comment by nfourtythree** [comment]
Hi @terryupton 

Apologies for this, looks like there was a mismatch of version number in the `composer.json`.

We have pushed version `3.4.25` which should fix this issue.

Thanks!
