### ISSUE TITLE
Separate Adjustment `type` from user-facing “Label”

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#356]
### Description

This is an observation and feature request, regarding Adjusters.

> The `ADJUSTMENT_TYPE` seems like it ought to be a handle-like string, but we should have a secondary option, like `ADJUSTMENT_LABEL` that is intended for human-readability. Currently, the string is coerced into snake-pascal-case in the admin, unless provided exactly as intended—which somehow feels fragile? It's also appended with ` Adjustment`, which is less-than-ideal.
> 
> _Come to think of it… I suppose it doesn't really matter what it is, since these are basically re-calculated on-demand._

### Steps to reproduce

1. Create a simple plugin and register custom Adjuster with generous criteria (just to get to to apply to a line item or order)
3. Set `ADJUSTMENT_TYPE` constant on Adjuster class to something handle-like, i.e. `license-type`
4. View adjustment name in Commerce admin

### Additional info

- Craft version: 3.0.9
- PHP version: 7.1.16
- Database driver & version: Postgres, 
- Plugins & versions: Commerce, 2.0.0-beta.4.1

_Edit: The Adjustment `title` and `description` attributes basically satisfy this! Figured I'd submit, in the event it seems like an easy-enough UX improvement for merchants._

**Comment by lukeholder** [comment]
Type is a system level identifier. Use title and description to know details of the adjustment.

The `type` may change to a class name in the future.
