### ISSUE TITLE
[4.x]: Can't see custom address fields when viewing order in control panel

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce#3562]
### Description
We recently upgraded a site from Commerce 3 to 4 and migrated all the fields as per the guide.
We have a custom phone number field which is storing data as expected.

This field is not shown on the address when viewing the order in the control panel.

The only way you can view it is to edit the order and edit the address.

The phone number is very important and should be shown, is there 

### Craft CMS version

4.10.3

### Craft Commerce version

4.6.3.1

### PHP version

8.3.8

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
You can follow the example in the PR here to add custom fields to the default html formatted output in the CP:

https://github.com/craftcms/cms/pull/13242

See also: https://craftcms.com/docs/5.x/reference/element-types/addresses.html#customizing-the-formatter

**Comment by andrewhawkes** [comment]
> You can follow the example in the PR here to add custom fields to the default html formatted output in the CP:
> 
> [craftcms/cms#13242](https://github.com/craftcms/cms/pull/13242)
> 
> See also: https://craftcms.com/docs/5.x/reference/element-types/addresses.html#customizing-the-formatter

Thanks - that has worked.

I do feel it would be a good option to have this in settings if at all possible. Seems a bit bonkers having to write a module to replace functionality that used to exist.
