### ISSUE TITLE
[5.x]: Setting new default variant does not remove existing default

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/commerce#3565]
### Description

I'm trying to set a different default variant for a product, but when I do, the existing default variant still shows as default (both items now showing default).

### Steps to reproduce

1. Select a different variant than the default product variant
2. In the dropdown, select "Set default variant"

### Expected behavior

Existing variant is de-selected as default and selected variant is the new default

### Actual behavior

Both variants now show as default in the "Default" column

### Craft CMS version

5.2.5

### Craft Commerce version

5.0.11.1

### PHP version

8.2.19

### Operating system and version

Linux 6.5.0-15-generic

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor 	4.1.0
Colour Swatches 	5.0.0
Control Panel CSS 	3.0.0
Craft Commerce 	5.0.11.1
Default Dashboard 	3.0.0
Element Relations 	3.0.4
Field Manager 	4.0.1
Guide 	4.0.0-beta.1
ImageOptimize 	5.0.2
Image Resizer 	4.0.0
Multi Translator 	2.5.2
Neo 	5.0.5
No-Cache 	3.0.2
PayPal Checkout for Craft Commerce 	3.0.1
Redirects 	5.0.2
Retcon 	3.2.0
SEO 	5.0.4
Servd Assets and Helpers 	4.0.3
Stripe for Craft Commerce 	5.0.1.1

**Comment by lukeholder** [comment]
@turnstylerj This should be fixed in 5.0.13! Thanks.
