### ISSUE TITLE
[5.x]: Custom address fields are not displayed on inventory location page

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#3569]
### Description
Inventory locations contain addresses, but no custom fields assigned to address field layout are show there.

![image](https://github.com/craftcms/commerce/assets/42622545/a2138009-0c53-4c2b-b873-e364c30505de)

However in the store location address slideout, these fields show correctly.

![image](https://github.com/craftcms/commerce/assets/42622545/9bf544c8-a2da-4405-99ca-9f76201da1c9)

### Craft CMS version

5.2.5

### Craft Commerce version

5.0.11.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Thank you for your feedback, we can replicate the issue you mentioned and we will look into it.

Thanks!

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Just an update, we have pushed a fix which resolves this issue.

It will be included in the next release of Commerce.

Thanks!

**Comment by piotrpog** [comment]
Thanks a lot.

**Comment by nfourtythree** [comment]
Hi

Commerce version `5.0.12` has been released with this update included.

Thanks!
