### ISSUE TITLE
Update multiple cart items

### ISSUE THREAD

**Issue by neybox** [craftcms/commerce#357]
### Feature request
It would be great if there was a way to update multiple cart items in one go instead of having to hit update for each cart item. A single button to update the cart instead of an "update" button for each item would much more friendly.
Hopefully, that's a feature already on your list.

**Comment by bossanova808** [comment]
Just to help anyone still using Commerce V1 - MultiAdd has this feature - https://github.com/verbb/multi-add

**Comment by lukeholder** [comment]
This functionality has now been added. Look out for it in the next release. The example templates have also been updated.
