### ISSUE TITLE
[5.x]: Moving default variant fields in new tab is not applied to edit UI

### ISSUE THREAD

**Issue by mandrasch** [craftcms/commerce#3570]
### Description

I wanted to hide the commerce default fields - since I can't remove them, I moved them to a new tab "Commerce Default":

![image](https://github.com/craftcms/commerce/assets/777278/1850f6c9-ffb8-41c1-a30f-a45e43b01f78)

When I add a new product variant, the fields are still shown in the default tab:

![image](https://github.com/craftcms/commerce/assets/777278/5f1694e0-ed75-46e3-8b96-4062ec27be99)

They are shown as well in the new tab:

![image](https://github.com/craftcms/commerce/assets/777278/24421b0d-aa73-485a-9951-00300327769c)

### Steps to reproduce

1. Move fields like `weight` into new tab in Product Types > Product Type > Variant Fields
2. Add Product -> Add variant

### Expected behavior

Moving fields to a new tab hides them in the regular tab 

### Actual behavior

Fields are shown in both tabs

### Craft CMS version

5.2.4.1

### Craft Commerce version

5.0.11.1

### PHP version

8.2.20

### Operating system and version

OSX/DDEV

### Database type and version

MySQL 8.0

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @mandrasch 

Thank you for bringing this to our attention, we have pushed up a fix for this which will be included in the next release of Commerce.

Thanks!

**Comment by nfourtythree** [comment]
Hi

Commerce version `5.0.12` has been released with this update included.

Thanks!
