### ISSUE TITLE
[5.x]: New products/variants are not promotable by default

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/commerce#3571]
### Description
As per [the documentation](https://craftcms.com/docs/commerce/5.x/system/discounts.html#discount-matching-items), the promotable option should be enabled by default. In Craft 5 + Commerce 5 this is not the case.

### Steps to reproduce

1.Make a product
2.See see the lightswitch is not flipped by default.

### Craft CMS version

 5.2.5

### Craft Commerce version

5.0.11.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @mikesnoeren 

Thank you for reporting this. We have made an [issue in the docs](https://github.com/craftcms/docs/issues/631) to be updated to make sure they explain how the system is working.

We have also added the `promotable` property to the options for showing in the variant index. This will allow you to have better visibility over which variants have been set to be profitable. This change will be included in the next release of Commerce.

We will take the feedback on board and see if there is a way (maybe a setting) to change the behaviour for whether a new variant is promotable by default.

Thanks!

**Comment by mikesnoeren** [comment]
Hi @nfourtythree, thanks for creating the issue in the docs.

From my perspective, enabling the promotable property by default would be the most effective approach. Any necessary (conditional) rules for promotions should, in my opinion, be managed within the promotion itself.

Introducing this setting seems to add unnecessary complexity to the already intricate promotions functionality. 

Additionally, I find it quite unconventional to restrict certain products from being eligible for promotions. Having worked on multiple webshops, we have never encountered a need for this restriction.

**Comment by nfourtythree** [comment]
Hi @mikesnoeren 

Again, thank you for this feedback. We will take it on board when making decisions regarding this functionality.

Thanks!

**Comment by philipboomy** [comment]
My editors are also asking for "Promotable" to be on as default. 99.5% of the time they create a product/variant it is promotable.

**Comment by lukeholder** [comment]
Craft Commerce 5.4 is now out with this fix/improvement. You can now edit the field settings in the layout to set the default value!

 Thanks!

https://plugins.craftcms.com/commerce/changelog?craft5
