### ISSUE TITLE
[5.x]: Saving a variant using CTRL/CMD+S (macOS) generates an error.

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/commerce#3572]
### Description
When changing any setting on any variant using the side editor window, and saving using CTRL/CMD+S gives you the messages `A server error occurred.` and `Showing your unsaved changes.`, as if it is a draft.

Saving did actually work, as when you refresh or reopen the side editor, you will see your changes.
Note: This issue does not happen when you manually click the red 'save' button.

### Steps to reproduce
1. Double click any variant
2. Change a random field
3. Press CTRL/CMD+S
4. See the error.

### Craft CMS version

5.2.5

### Craft Commerce version

5.0.11.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @mikesnoeren 

Thank you for reporting, this was fixed in Craft itself as part of this fix: https://github.com/craftcms/cms/commit/260dce5c3d7b7b9e60f50a1f2c4597d9a5a5bdd4

It will be included in the next release of Craft `5.x`

Thanks!
