### ISSUE TITLE
[5.x]: Shipping rule description not shown

### ISSUE THREAD

**Issue by white-lukas** [craftcms/commerce#3580]
### Description
After creating a shipping rule, the description is not shown anymore.
After the first save the description is saved in the database.
So looks only a bug in retrieving the description.

### Steps to reproduce

1. Create a shipping rule
2. Add a description
3. save
4. Description is not shown on the shipping methods page or on the edit page (It is saved in the database)
5. after editing the shipping rule the description is removed again

### Expected behavior
Description should be shown, and not getting removed after a resave

### Actual behavior
Description is never show

### Craft CMS version

5.2.5

### Craft Commerce version

5.0.11.1

### PHP version

8.3.8

### Operating system and version

Ubuntu 24.04

### Database type and version

mysql 8.0

**Comment by lukeholder** [comment]
Thanks for reporting, we have fixed for next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#e7b37482a39d3287cccd278a569b5c13c5dd1208 as 5.0.12.1",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release it out.

**Comment by nfourtythree** [comment]
Commerce `5.0.12.2` has now been released with this fix included.

Thanks!
