### ISSUE TITLE
[5.x]:  Failed migration on update

### ISSUE THREAD

**Issue by teachmeter** [craftcms/commerce#3581]
### Description
After running `craft update all` migrations for commerce fail.

### Steps to reproduce

1. run craft update all
2. wait for the migrations step

### Expected behavior
Migrations for commerce are applied

### Actual behavior
Migrations failing with prompt to restore database backup and revert composer changes.

**Log of the command process** 
[failed-migration.log](https://github.com/user-attachments/files/16193288/failed-migration.log)

### Craft CMS version

Craft Pro 5.2.4.1

### Craft Commerce version

5.0.11.1

### PHP version

8.2.3

### Operating system and version

DDEV Linux 5.15.49-linuxkit

### Database type and version

MySQL 8.0.31

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Blitz - 5.3.3
- CKEditor - 4.1.0
- Craft Commerce - 5.0.11.1
- Feed Me - 6.1.0
- Formie - 3.0.0-beta.16
- Hyper - 2.0.2
- Navigation - 3.0.1
- Ray - 2.1.1
- Retcon - 3.2.0
- SEO - 5.0.4
- Sprig - 3.0.2

**Comment by nfourtythree** [comment]
Hi @teachmeter 

Thank you for reporting this. We have pushed a fix to rectify this issue, it will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#bba8e1ceaf43ced94b2b5ab510e76def9754b660 as 5.0.12.1",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce `5.0.12.2` has now been released with this fix included.

Thanks!
