### ISSUE TITLE
[5.x]: Unable to view/edit payment currency

### ISSUE THREAD

**Issue by white-lukas** [craftcms/commerce#3582]
### Description
After creating a payment currency, you can't edit the currency anymore.
The links on the `/admin/commerce/store-management/primary/payment-currencies` don't pass in an ID of the payment currency.
And when going to `/admin/commerce/store-management/primary/payment-currencies/1` it also doesn't work.
The returned paymentcurrency [here](https://github.com/craftcms/commerce/blob/5.x/src/services/PaymentCurrencies.php#L84) doesn't get the ID set:
![image](https://github.com/user-attachments/assets/f311b96c-9259-4161-a88c-9eab505775a8)

### Craft CMS version

5.2.5

### Craft Commerce version

5.0.11.1

### PHP version

8.3.8

**Comment by nfourtythree** [comment]
Hi @white-lukas 

Unfortunately, we are unable to replicate this issue (see video).

https://github.com/user-attachments/assets/3d95c00f-f25a-4700-aae3-11774f01bff1

Is this the same for all of your Commerce 5 projects?

Thanks

**Comment by white-lukas** [comment]
After starting with a clean DB, I'm now also able to view the page.

Probably just some conflicts with switch branches and re-applying configs I guess than as the currencies do work in the front end
