### ISSUE TITLE
[5.x]: Unable to specify supported states for store

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/commerce#3584]
### Description

I'm updating a site from Commerce 2 to a new Commerce 5 build, and the store has multiple supported states available for different countries. In Commerce 2, there's a "States" option:
![2024-07-12 at 15 24 12](https://github.com/user-attachments/assets/523e2cfb-ccde-4dd5-9da0-00a1c06aeb51)

But in Commerce 5, I'm only seeing Countries available as a multi-select. If I use Order Address Conditions for the supported states like so:
![2024-07-12 at 15 22 47](https://github.com/user-attachments/assets/729f71a7-fb53-4d64-82c6-b29d061795fb)

They apply as "and" conditions rather than "or". I want to be able to specify that within x country, these states/regions are supported. Is this possible in Commerce 5?

### Craft CMS version

5.2.6

### Craft Commerce version

5.0.12

### PHP version

8.2.19

### Operating system and version

Linux 6.5.0-15-generic

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor 	4.1.0
Colour Swatches 	5.0.2
Control Panel CSS 	3.0.0
Cookies 	5.0.0
Craft Commerce 	5.0.12
Default Dashboard 	3.0.1
Element Relations 	3.0.4
Field Manager 	4.0.1
GeoMate 	3.0.0-beta.2
ImageOptimize 	5.0.2
Image Resizer 	4.0.0
Multi Translator 	2.6.0
Neo 	5.0.5
No-Cache 	3.0.2
PayPal Checkout for Craft Commerce 	3.0.1
Redirects 	5.0.2
Retcon 	3.2.0
SEO 	5.0.4
Servd Assets and Helpers 	4.0.3
Stripe for Craft Commerce 	5.0.1.1

**Comment by lukeholder** [comment]
Hi @turnstylerj 

The administrative area is now a string value and not an ID, so any value can be put into the state list (including typing your own).

The country selector is just a way to get to add additional values to the list. The country is not used in the order condition (you would need to add a country condition if you wanted to limit by country).

When you change the country the values from the previously selected country are still there, so you can add multiple states from across countries.

I know the UX needs improvement as this is not ergonomic, I will raise this issue with the CMS team (where addresses and address conditions are maintained).
