### ISSUE TITLE
[5.x]: Failed to instantiate component or class "craft\behaviors\CustomFieldBehavior".

### ISSUE THREAD

**Issue by BenParizek** [craftcms/commerce#3585]
### Description

I'm struggling to have a clear ticket here but I'll say what I can. Seems potentially related to https://github.com/craftcms/commerce/issues/3503

The issue taking place is that when I perform certain actions in my plugin with Craft Commerce installed, all of a sudden the page fails to load with the error: `Failed to instantiate component or class "craft\behaviors\CustomFieldBehavior".` In my case, I can load an Element Index page fine. But when I try to create a new custom Form Element the error occurs. I've tested creating a new Entry Element and that works fine.

I've tried to rule out my code as the problem by commenting it out and changing assumption, but I think it has something to do with the relationship between the two. 

### Steps to reproduce

1. Install Commerce
2. Register an event in a custom module using: `craft\web\Application::EVENT_INIT`
3. Perform an Element Query (I've tried multiple custom Elements but this also fails with the same error if I just use a Craft Entry query: `Entry::find()->all();`

Here's an example of the logging that happens if I just run the request that causes the issue: [example.log](https://github.com/user-attachments/files/16202278/example.log)

In my tests, commenting out the `$currentUser = Craft::$app->getUser()->getIdentity();` block of code (specifically the getIdentity call) in the `EVENT_DEFINE_NATIVE_FIELDS` seems to get things working again. https://github.com/craftcms/commerce/blob/27ccca58f6486aac05e15332783073e9e0946679/src/Plugin.php#L1084-L1090

Clearly not a solution, but it's the best I can come up with to try to point to where the issue might be at the moment. Happy to test something out on my end if helpful to troubleshooting.

Once the error happens, all CP pages fail to load. After I refresh a front-end page of the website I can return to the CP and access pages again, until this issue recurs.

Disabling the Craft Commerce plugin also resolves the issue.

### Craft CMS version

5.2.6

### Craft Commerce version

5.0.12.2

### PHP version

8.2

### Operating system and version

Sonoma 14.5

### Database type and version

MySQL 8

### Installed plugins and versions

- Several, this is happening in my Sprout development project after I install Commerce.

**Comment by nfourtythree** [comment]
Hi @BenParizek 

Anything that is going to use or instantiate an element query must go inside the `Craft::$app->onInit(function() { //... });` function when being used in a plugin or module's init method. Making sure that the application is fully loaded and plugins have all had their chance to register whatever code they need.

Hopefully, this helps point you in the right direction, thanks!

**Comment by janhenckens** [comment]
Hey @BenParizek, would you happen to have Scout installed in your test install? I have an open issue on Craft 5 to fix this there.

**Comment by thom-moresoda** [comment]
hey @janhenckens do you mind linking to your open scout issue?

I've been having very similar "craft\behaviors\CustomFieldBehavior" issues on my site & disabling scout seems to fix the problem for me (found after about 2 days of debugging)

**Comment by nfourtythree** [comment]
Hi all

With no update on this and believing it is an issue not related to Commerce we are going to close this for now. 

If you have further info please post it here and we can reopen the issue and investigate. 

Thanks!

**Comment by hatyi** [comment]
> Hey @BenParizek, would you happen to have Scout installed in your test install? I have an open issue on Craft 5 to fix this there.

Hi! Thanks for this I was facing the same issue and can confirm that after disabling Scout the error is gone.

**Comment by janhenckens** [comment]
@hatyi There's an update out for Scout that fixes this so once you upgrade to 5.0.0 you should be good again!

**Comment by hatyi** [comment]
@janhenckens  Thanks a lot for this! I've just installed the Scout package 2 days ago, didn't know there's a new version already, will definitely try it! 🫠
