### ISSUE TITLE
[5.x]: Unable to reorder Variants

### ISSUE THREAD

**Issue by tommysvr** [craftcms/commerce#3589]
### Description
On a fresh Commerce 5 install, the order of variants reverts after saving a product. This appears to be due to the presence of a `sortOrder` column in the `commerce_variants` that's not in a 4->5 upgrade: https://github.com/craftcms/commerce/blob/5.x/src/migrations/Install.php#L995

Removing that column resolves the issue.

### Steps to reproduce

1. Install a fresh version of Craft & Commerce 5
2. Create a product with multiple variants
3. Drag and drop to rearrange the order
4. Save the product

### Expected behavior
Rearranged variant order is saved

### Actual behavior
Variant order reverts back to the original order when variants were first created

![screenshot_2024_07_17 _17 36](https://github.com/user-attachments/assets/95ef7821-20c2-4442-8920-9be246e73667)

### Craft CMS version

5.2.7

### Craft Commerce version

5.0.12.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@tommysvr This should be fixed in 5.0.13. Thanks!
