### ISSUE TITLE
Error while Deleting Saved address

### ISSUE THREAD

**Issue by golivermtl** [craftcms/commerce#359]
### Description
After login to the website and go to "shop/customer/addresses"  You can see the option to delete the Address.  When we hit the delete button we get an error "Call to a member function getEmail() on null"   Refer Screenshot ![image](https://user-images.githubusercontent.com/26368713/40632401-bb11410a-62b4-11e8-8c51-e4872123aba0.png)  

### Steps to reproduce

1. Login to the Front end of the website
2. Goto My Address ( Ex: http://localhost/shop/customer/addresses )
3. Delete existing address using the "Delete" button ( add new address if not done earlier  ) 
4. Getting an error "Call to a member function getEmail() on null  in \vendor\craftcms\commerce\src\elements\Order.php"
5. See attached screenshot for more details.

### Additional info

- Craft version:Craft Pro 3.0.9
- PHP version: 7.2.1
- Database driver & version: MySQL 5.7.19

- Plugins & versions: Craft Commerce 2.0.0-beta.4.1

**Comment by krizajb** [comment]
Having similar problem, but the issue only applies to cart address i.e.  `cart.shippingAddress`.

**Comment by lukeholder** [comment]
Duplicate of #379
