### ISSUE TITLE
Wrong Shipping Category Conditions

### ISSUE THREAD

**Issue by bartrylant** [craftcms/commerce#360]
### Description
When making a new shipping rule, when you set conditions to "Shipping Category Conditions" (like disallow), the conditions get saved to the wrong shipping categories.

### Additional info
- Craft version: Craft Pro 3.0.9
- PHP version: 7.1.17
- Database driver & version: MySQL 5.5.60
- Plugins & versions: Craft Commerce | 2.0.0-beta.4.1

**Comment by lukeholder** [comment]
Fixed in beta.5 released less than an hour ago.
