### ISSUE TITLE
[5.x]: HTML Entity Issue in Shipping Method Name with Ampersand (&)

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/commerce#3606]
### Description
On `/admin/commerce/store-management/primary/shippingmethods`, if I add a new shipping method with an ampersand (&) in the title, the title is displayed as `&amp;`.

### Steps to Reproduce

1. Go to `/admin/commerce/store-management/primary/shippingmethods`.
2. Add a new shipping method.
3. Include an ampersand (&) in the shipping method title.
4. Observe the displayed title.

### Expected Behavior
The shipping method title should display the ampersand character (&) correctly.

### Actual Behavior
The shipping method title displays the ampersand as `&amp;`.

<img width="1693" alt="Capture d’écran 2024-07-29 à 15 35 03" src="https://github.com/user-attachments/assets/019abf1a-8026-4e9e-8bfe-db0d349ac01e">

### Craft CMS version

5.2.8

### Craft Commerce version

5.0.14

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Fixed for the next release. 

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "4.x-dev#e066c9d928249fe7df397861e09380531a8b5ea2 as 4.6.8",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by robzor** [comment]
Hi there, sorry for the thread resurrection but this also applies on Product Types: `/admin/commerce/settings/producttypes`

<img width="1439" height="362" alt="Image" src="https://github.com/user-attachments/assets/e397d32b-0cd1-430a-913b-5a61b69eb7bc" />
