### ISSUE TITLE
[5.x]: Unable to create sale or discount for product

### ISSUE THREAD

**Issue by wanze** [craftcms/commerce#3611]
### Description

Creating a sale or discount from a product does not seem to work.

<img width="1154" alt="Screenshot 2024-08-01 at 07 13 38" src="https://github.com/user-attachments/assets/32010528-bf2f-4a1b-af36-61444fc942a9">

### Steps to reproduce

1. Select a product via checkbox
2. From the actions, choose either "Create sale..." or "Create discount..."
3. The loading spinner shows, but nothing happens
4. Note the javascript errors in the console. This error already appears when selecting the product, so not sure if it's relevant for the issue.

<img width="410" alt="Screenshot 2024-08-01 at 07 15 04" src="https://github.com/user-attachments/assets/f47dd260-8b8c-4775-8fe1-348d5c4cfd3c">

### Expected behavior

It should be possible to create a sale or discount from a product.

### Craft CMS version

5.2.9

### Craft Commerce version

5.0.15

### PHP version

8.3

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for reporting. We will have this fixed in the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#5d6db4707bbe3fad11a5b302931819d2b39887aa as 5.0.15",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by lukeholder** [comment]
Craft Commerce 5.0.16 is now out this this fix. Thanks!
