### ISSUE TITLE
[5.x]: Discounts not translatable for multi-site installations

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/commerce#3613]
### Description

On a multi-site with different languages, Commerce Discounts are not translatable if we'd like to output the Name/Description to the user on the front end.

![2024-08-06 at 11 54 23](https://github.com/user-attachments/assets/a45598f8-2d77-41b8-8097-e337c508f305)

### Craft CMS version

5.2.9

### Craft Commerce version

5.0.15

### PHP version

8.2.21

### Operating system and version

Linux 6.5.0-15-generic

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor 	4.1.0
Colour Swatches 	5.0.2
Control Panel CSS 	3.0.0
Cookies 	5.0.0
Craft Commerce 	5.0.15
Default Dashboard 	3.0.1
Element Relations 	3.0.4
Field Manager 	4.0.2
GeoMate 	3.0.0-beta.2
ImageOptimize 	5.0.2
Image Resizer 	4.0.0
Multi Translator 	2.6.0
Neo 	5.1.2
No-Cache 	3.0.2
PayPal Checkout for Craft Commerce 	3.0.1
Redirects 	5.0.2
Retcon 	3.2.0
SEO 	5.1.1
Servd Assets and Helpers 	4.0.6
Stripe for Craft Commerce 	5.0.1.1

**Comment by lukeholder** [comment]
@turnstylerj Unfortunately discounts are translatable like entries. You would need to find a workaround like creating an associated entry for the discount to store localized information about the discount. 

See the discussion here (where you can add your voice): https://github.com/craftcms/commerce/discussions/2802

We are looking at improving this in the future, but can't give a timeline sorry.
