### ISSUE TITLE
[5.x]: Order Element getOrderStatus returns empty result

### ISSUE THREAD

**Issue by stanislavprokopov** [craftcms/commerce#3615]
### Description

The `getOrderStatus` method of Order element returns empty result altho `orderStatusId` is set.
The issue is that `getOrderStatusById($this->orderStatusId)` has an optional second argument `storeId` and if its not set then it defaults to current store, and in some cases this might not be the same store that the order was created in, resulting in empty order status.

### Steps to reproduce

1. Setup two stores, with several order statuses
2. Create an order in each store
3. Find both orders by id `Order::find()->id(X)->one();`
4. Now dump `$order->orderStatusId` and `$order->orderStatus`

In one case you will have both values and in the order you will only have ID.

### Expected behavior

Should get correct order state regardless of current active store.

### Actual behavior

State is null

### Fix

`getOrderStatusById($this->orderStatusId)` should also pass `$this->storeId` as the last argument so that `getOrderStatusById` method uses the correct store to fetch statuses.

### Craft CMS version

5.3.1

### Craft Commerce version

5.0.15

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for reporting that. We have fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#af2aafd800a87cc569fbfc73448f701b137ba950 as 5.0.15",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by lukeholder** [comment]
Craft Commerce 5.0.16 is now out this this fix. Thanks!
