### ISSUE TITLE
billingSameAsShipping doesn't persist through the cart/order

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#362]
### Description
Submitting a field of `<input name="billingAddressSameAsShipping" value="1">` works and sets the billing to be the same as the shipping.

However checking the value `billingSameAsShipping` (as per documented in the model/element) just returns `NULL`. 

### Additional info

- Craft version: 3.0.8
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: Commerce 2.0 beta 5

**Comment by davist11** [comment]
I'm experiencing this same issue as well. `cart.billingSameAsShipping` also seems to be `NULL`

**Comment by davist11** [comment]
Any idea when can we expect a bugfix for this?

**Comment by lukeholder** [comment]
`billingSameAsShipping` and `shippingSameAsBilling` is only used on the request from the front end and is only set for the life of that request, it is not a persisted attribute. If you want to know if they are the same address after that simply compare the `billingAddressId == shippingAddressId`.
