### ISSUE TITLE
[5.x]: Can't remove status email from Order Status

### ISSUE THREAD

**Issue by MatthiasBrodelet** [craftcms/commerce#3621]
### Description
I have previously set an email to an order status in the interface (Commerce => System Settings => Order Statusses).
Now I need to remove it again so there are 0 emails for this status.
It does not remove the email when removing it from the field and saving the status.
There are also no error messages

<img width="1019" alt="Screenshot 2024-08-09 at 11 25 54" src="https://github.com/user-attachments/assets/dd495f59-3d83-42a1-8003-fecf36cba888">

### Steps to reproduce

1. Assign an email to an order status and save it
2. Open the order status again and remove the email

### Expected behavior
The email should be removed.

### Actual behavior
The email is not removed.

### Craft CMS version

Craft CMS PRO 5.3.1

### Craft Commerce version

5.0.15

### PHP version

8.2

**Comment by lukeholder** [comment]
@MatthiasBrodelet ~I can't seem to reproduce this. Are there any javavscript errors in the browser console?~

**Comment by lukeholder** [comment]
@MatthiasBrodelet I can reproduce this. Looking to make a fix now. Thanks!

**Comment by lukeholder** [comment]
Thanks, this is fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#e8eb157052f4fa670e41a30dd086f85c36fe20da",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by lukeholder** [comment]
Craft Commerce 5.0.16 is now out with this fix! Thanks.
