### ISSUE TITLE
Manual Sorting of Products

### ISSUE THREAD

**Issue by sandrodunkel** [craftcms/commerce#3630]
### What happened?

I know this is not the right place for this, and I'm sorry for this, but seeing how the discussion #2302 has seemingly been left abandoned by the devs for several years, I really don't see any other way to voice my concerns. The discussion exists since 2018.

Not being able to sort products is a dealbreaker not only for us as devs, but also for our clients. This needs to be part of the native functionality of Commerce. I don't see there being any excuses why this issue has been ignored for so long. It becomes increasingly difficult justifying a $1200 license to our clients if they end up not even being able to sort their products.

I know that in your [knowledge base](https://craftcms.com/knowledge-base/manually-sorting-commerce-products) you explain how to achieve a similar effect with a custom field and a module, but this just can't be you long term solution.

### Craft CMS version

any

### Craft Commerce version

any

**Comment by aeu** [comment]
Hi @sandrodunkel - we get around this limitation by putting a Matrix on the collection page (example: shirts, pants, shoes, whatever) and in that Matrix is an entry type which includes a product.  Thus product ordering can be achieved.  No module necessary, no custom field, just standard Craft containers.

**Comment by wmdhosting** [comment]
OK but structure is allready native part of Craft..  so why doit in other way

**Comment by aeu** [comment]
> OK but structure is allready native part of Craft.. so why doit in other way

He's talking about ordering Products for craft commerce.  Not the same as Structures, which are ordered collections of Entries.

**Comment by wmdhosting** [comment]
yes i know :) why not add structure option to products.. 
so all works same way

**Comment by aeu** [comment]
> yes i know :) why not add structure option to products.. so all works same way

Yeah, that would be nice.  For now the Matrix is the only thing that works without custom code.

**Comment by wmdhosting** [comment]
As how things works now.. as much i see>>   its all the same as Sections .. just here we have commerce field
So this can be part of Entrification thing too .. so all works same..

**Comment by masiorama** [comment]
I would like to know also if it is possibile to sort products in different ways depending on some logics, like, for instance, different order depending on category pages the products are linked to.
For example, I have seasonal catalogs which should show the same product in different position depending on the catalog.

This order thing (even just a basic implementation) is really important for my clients.

**Comment by BrandKits** [comment]
My client requested this also (as they were used to it with Shopify). I setup the manual field method but it's super clunky (and hard to drag products into place when there are a lot of them). 

We also have to have multiple queries depending on whether it's native or a product field which is unnecessary complexity. Hope a native solution can be added soon.

**Comment by lukeholder** [comment]
We now have this feature within a PR slated being a part of 5.2 https://github.com/craftcms/commerce/pull/3663

Will update this ticket once 5.2 is out. We don't have a public timeline for this at the moment.

Thanks

**Comment by lukeholder** [comment]
This was released in 5.2! Thanks all!
