### ISSUE TITLE
[4.6.8]: Latest version changed the order of shipping method causing the default method to have changed.

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce#3631]
### Description
Updated from 4.6.2 to 4.6.8 and the order of the shipping methods has changed. This means the default shipping method has changed. How can I fix this? Can I set a default shipping method?

It is causing issues as when adding to the basket before even selecting shipping the customer now see a shipping charge when not really needed.

![4 6 8](https://github.com/user-attachments/assets/e2e78417-a080-47d8-b570-dc144e9f41df)
![4 6 2](https://github.com/user-attachments/assets/1cb4dfb0-a024-46a2-bd22-51158aa75db1)

### Craft CMS version

4.11.3

### Craft Commerce version

4.6.8

### PHP version

8.2.20

### Database type and version

MySQL 5.7.44

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for reporting this. The fix will be included in the next 4.x release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "4.x-dev#6afeb3424086bd72ae0f889b050c8675b7035a13 as 4.6.8",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.
