### ISSUE TITLE
[5.x]: Issues with permissions

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/commerce#3639]
### What happened?

Description
We're nearly ready to launch a webshop built with Craft 5 and Commerce 5, but we're encountering several issues with setting up the permissions. Please see the details below:

1. Manage Promotions - Sales
**Issue**: It is unclear what is considered a "sale" in Commerce 5. Regardless of this setting, I am able to see and create Discounts/Pricing Rules or set promotional prices on individual products.
**Question**: What does this setting actually control?

2. Manage Promotions - Catalog Pricing Rules
**Issue**: Catalog pricing rules are not editable by non-admins, even when the correct permissions are set. The button to add these rules is always missing.

3. Donations Page Visibility
**Issue**: The Donations page is always visible. This page should be hidden based on user permissions.

4. Manage Store Settings Required for Managing Promotions
**Issue**: The "Manage Store Settings" permission is required to manage promotions (Discounts and Pricing Rules). However, granting this permission also provides access to critical store settings, such as currencies and allowed countries.

### Craft CMS version

5.3.4

### Craft Commerce version

5.0.16.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
We have recently released 5.1.0-beta.2 which addresses all of these issues. Feel free to try it out.

![CleanShot 2024-08-20 at 19 20 06@2x](https://github.com/user-attachments/assets/e9da8007-52fb-4af8-b7a6-7291bed5f89c)

As for sales, they only show up when you migrate to Commerce 5 for a single store. You need to remove all sales and then begin using pricing rules. They cant be used concurrently. You can not use sales and add a second store.

I will update this ticket once 5.1 is out officially. Thanks!

**Comment by mikesnoeren** [comment]
Thanks! Good to hear. 

Do you have an ETA on 5.1 release date? 
It would be great if we could communicate a date to our client.

**Comment by lukeholder** [comment]
We dont have an exact timeline but within 2-3 weeks if not earlier.

**Comment by mikesnoeren** [comment]
I tried installing 5.1.0-beta.2, and while the permissions are somewhat better now, the 'create catalog pricing rules' permission is still broken. You can't add pricing rules unless you're an admin.

On top of that, there's an even bigger problem with this beta update: adding any product to my cart randomly adds a completely unrelated product as well.

I couldn’t figure out what’s causing it—everything I’m posting seems correct. Downgrading back to 5.0.16.2 fixes the issue.

**Comment by lukeholder** [comment]
@mikesnoeren thanks for trying the beta.

We will look into the pricing rule permissions now, but as for the other issue, could you send us your DB backup with composer.json and composer.lock to support@craftcms.com - thanks!

**Comment by mikesnoeren** [comment]
Hi @lukeholder,

Thanks for the fast communication.
I've send the requested files, if you require anything else, please let me know.

**Comment by lukeholder** [comment]
5.1.0-beta.3 is now out and fixes both of the issues you were seeing. Thanks!
