### ISSUE TITLE
Search variant by price

### ISSUE THREAD

**Issue by mcjackson18** [craftcms/commerce#364]
### Description
You can no longer search for a variant by price (which was available in commerce 1)

The attached image shows the code updates in commerce 1.

<img width="864" alt="craft-commerce" src="https://user-images.githubusercontent.com/39083512/40833974-4de4b30c-6587-11e8-851f-10c1e6d46009.png">

Thanks

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
