### ISSUE TITLE
[4.x]: Update cart action with clear address params will break next address update with logged in user

### ISSUE THREAD

**Issue by Braedan** [craftcms/commerce#3641]
### Description
When the config `autoSetNewCartAddresses` is set to `true` (default) Commerce seems to aggressively attempt to apply an existing user address onto orders if an address is missing, regardless if the cart is new. This can cause issues when trying to clear cart addresses before applying new ones.

Causes error:
`Calling unknown method: craft\\commerce\\elements\\Order::getPrimaryBillingAddressId()`

I've managed to work around this issue by ensuring that I provide the params `CustomerAddressBehavior::rules()` is expecting with my request:
```
isPrimaryShipping: false,
isPrimaryBilling: false,
```

### Cause
CartController::actionUpdateCart() calls getCart() from the Carts service. This causes [autoSetAddresses()](https://github.com/craftcms/commerce/blob/5.x/src/services/Carts.php#L142-L145) to run, which will set the _shippingAddress back to the user’s primary address if the order address is empty. The address now has the [CustomerAddressBehavior](https://github.com/craftcms/commerce/blob/5.x/src/behaviors/CustomerAddressBehavior.php). Later in actionUpdateCart() setShippingAddress() correctly uses the provided address params, but [due to this conditional](https://github.com/craftcms/commerce/blob/5.x/src/elements/Order.php#L3018) will incorrectly use the Address with CustomerAddressBehavior attached. Validating this address will fail.

### Steps to reproduce
Front end example (address in this context can be either shipping or billing):
1. User has an order with address auto applied
1. User clears address from order (provide param(s) `clearShippingAddress`, `clearBillingAddress`, `clearAdresses` to `commerce/cart/update-cart`)
1. User attempts to apply new address to order (this will error)

### Expected behavior
When logged in, providing an order that has no billing / shipping address data with address params, Commerce should either not apply the customer's primary address back onto the order, or ensure that the behavior isn't put onto the new address.

### Craft CMS version

4.9.5

### Craft Commerce version

4.6.2 (problem also exists on 5.x)

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
I believe this is due to us setting the `ownerId` on the duplicated element, and not the whole owner object (which will also set the ID).

I have pushed a quick fix to the 4.x branch: c02ad47ed3a6f14378282c96c9f71e8d9896e3d4 which would be in our next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "4.x-dev#c02ad47ed3a6f14378282c96c9f71e8d9896e3d4 as 4.6.9",
  "...": "..."
}
```

Then run `composer update`.

@Braedan Could you let me know how you go with this fix?

We will update this ticket once the release is out.

**Comment by nfourtythree** [comment]
Commerce versions `4.6.10` and `5.0.18` have now been released with this fix included.

Please run `composer update` in your project to get the latest changes.

Thanks!

**Comment by Braedan** [comment]
Thanks for the fast fix, this works perfectly 👍
