### ISSUE TITLE
[5.x]: 'You need to be on at least Craft Commerce 3.4.11 before you can update to Craft Commerce 5.0.17.'

### ISSUE THREAD

**Issue by mike-niemand** [craftcms/commerce#3642]
### Description

I'm trying to install commerce on my Craft Pro 5.3.5 installation 

### Steps to reproduce

1.

### Expected behavior

Installs

### Actual behavior

'You need to be on at least Craft Commerce 3.4.11 before you can update to Craft Commerce 5.0.17.'

### Craft CMS version

5.3.5

### Craft Commerce version

5.0.17

### PHP version

8.2.22

### Operating system and version

Linux 5.14.0-427.24.1.el9_4.x86_64

### Database type and version

MySQL 8.0.39

### Image driver and version

GD 8.2.22

### Installed plugins and versions

CKEditor	4.1.0
Linkit		5.0.0
Neo		5.1.3
Wheel Form	4.0.2

**Comment by lukeholder** [comment]
Did you have Commerce installed previously? Is there any remnants of Commerce in your project config or database?
