### ISSUE TITLE
[5.1.0-beta.3]: SQL Error when attempting to set transfer quantity

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#3643]
### What happened?

If I put a "very large" number into a new Transfer, Commerce lets the integer go to the database and triggers an SQL error:

```
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'quantity' at row 1
The SQL being executed was: UPDATE `commerce_transferdetails` SET `quantity`=999999999999 WHERE `id`=3
```

![Screenshot 2024-08-23 at 16 20 15](https://github.com/user-attachments/assets/c2aa58ae-6c58-41ae-8174-9d124ab3f711)

My expectation would be that this value is validated/capped at the source location’s "available" or "on hand" for that inventory item… and therefore maybe not allowed to be saved at all?

### Craft CMS version

5.3.2

### Craft Commerce version

5.1.0-beta.3

### PHP version

8.2.20

**Comment by lukeholder** [comment]
Fixed for next beta release. Thanks.
