### ISSUE TITLE
[5.x]: No permissions for "Donations" page

### ISSUE THREAD

**Issue by MatthiasBrodelet** [craftcms/commerce#3647]
### Description
I have some user roles that just need to handle the products so I have only enabled this permission for this role but the donations page still is accessible in the sidebar under "Commerce". 
Can this also be added as a permission?
My editors are confused and can now enable or disable donations while we don't use them.

[
![Screenshot 2024-08-29 at 10 40 37](https://github.com/user-attachments/assets/c1ff8cec-bce4-448f-9416-0556e2e83709)
](url)

### Steps to reproduce

1. Try to remove the permissions for the donations page

### Expected behavior
Donations should not be shown in the sidebar if the permission is not given.

### Actual behavior
Everyone can see the donations page in the sidebar when they have 1 or more Commerce permission

### Craft CMS version

5.x

### Craft Commerce version

5.x

### PHP version

8.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
This is fixed in Craft Commerce `5.1.0-beta.3`.

The proper 5.1 release will be out of beta within a few days. Thanks!
