### ISSUE TITLE
Get Cart via AJAX without updating

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#365]
### Description

Would be nice to be able to fetch cart details without having to issue a POST request. This came up in the context of a Vue-based cart—it'd be useful to instantiate it via an AJAX request, without suggesting to the app that it's being updated.

### Steps to reproduce (here, potential implementation)

1. Client makes a request to `commerce/carts/cart`
2. Craft issues payload via `_returnCart`? Not sure what a non-JSON response would look like.

### Additional info

❤️

**Comment by olsp** [comment]
In the release notes for 2.0.0-beta.7 it says: 

> The cart can now be retrieved as JSON with the commerce/cart/get-cart action.

But I can't get it working and I haven't found anything in the docs about it yet.

**Comment by AugustMiller** [comment]
This may have more to do with the underlying Yii `getIsAjax` implementation, than Commerce:

https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L462

Basically, you must ensure the `X-Requested-With` header is set to `XMLHttpRequest`, or it won't acknowledge it as an "AJAX" request. jQuery sends this by default, as do a few other libraries—seems like they made a pretty big assumption. Tends to get people pretty often!

**Comment by olsp** [comment]
This is the code I've tried:

```
var csrf = document.querySelector('input[name=CRAFT_CSRF_TOKEN]').value;
var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function( ) {
    if (this.readyState === 4 && this.status === 200) {

        console.log( this.responseText );

    }
};
xhttp.open("POST", "/", true);
xhttp.responseType = 'json';
xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
xhttp.send("action=commerce/cart/get-cart&CRAFT_CSRF_TOKEN="+ csrf );
```

The response is a 400 (Bad Request) Error

**Comment by lukeholder** [comment]
Something like this works in jQuery:

```
    $.ajax({
        url: '',
        data: {
            '{{ craft.config.csrfTokenName|e('js') }}': '{{ craft.request.csrfToken|e('js') }}',
            'action': 'commerce/cart/get-cart'
		},
        success: function(data)
		{
			console.log(data);
		},
        dataType: 'json'
    });
```

**Comment by knynkwl** [comment]
@lukeholder can you help with how this would be structured using the fetch api?

**Comment by lukeholder** [comment]
Craft 5 and Commerce 5

```javascript
function getCart() {
    const csrfTokenName = '{{ craft.app.config.general.csrfTokenName|e('js') }}';
    const csrfToken = '{{ craft.app.request.csrfToken|e('js') }}';

    const formData = new FormData();
    formData.append(csrfTokenName, csrfToken);
    formData.append('action', 'commerce/cart/get-cart');

    fetch('', {
      method: 'POST',
      body: formData,
      headers: {
        'Accept': 'application/json',
      },
    })
      .then(response => {
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        return response.json();
      })
      .then(data => {
        console.log(data);
      })
      .catch(error => {
        console.error('Error fetching cart:', error);
      });
  }
  ```

**Comment by AugustMiller** [comment]
Noting that Luke's example reflects our recommendations in the **Ajax** section of our [Forms documentation](https://craftcms.com/docs/5.x/development/forms.html#ajax)! If your request is initiated by a script that isn't part of a Twig template, you can chain multiple `fetch()` calls together to grab the CSRF info, dynamically.
