### ISSUE TITLE
[5.x]: Variants OrderBy product field 

### ISSUE THREAD

**Issue by masiorama** [craftcms/commerce#3651]
### Description
To be able to sort manually products (I know that the ordering feature is well discussed) I tried adding a lightswitch field (_featuredProduct_) on products, which should help me put products which are selected before all the others.
My issue is that since I display on page grids of variants (not products) I should be able to do something like 
```
craft.variants.orderBy('featuredProduct DESC, postDate DESC, sortOrder ASC, score')
```
I tried _featuredProduct DESC_, or _product.featuredProduct DESC_, or _variant.product.featuredProduct DESC_, but no luck.
Probably I am unaware of something well documented, but I searched documentation, stackexchange and here with no luck.

### Craft CMS version

5.3.5

### Craft Commerce version

5.0.17

### PHP version

8.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @masiorama 

Thank you for your message.

As you are doing a variant query you are unable to order by a custom field that exists on the product. In the example you gave `featuredProduct` would have to be a custom field on the variant.

Just as an example if you tried `craft.products.orderBy('featureProduct DESC')` you will likely see that the products will be in an order you expect.

Hope this helps, thanks!

**Comment by masiorama** [comment]
Hi @nfourtythree  thanks for your reply.
I guess that would work, but I sense it as a bit clunky from the panel admin point of view. 

I mean, from one side it would help handle things with a more granular approach, but from the other point of view, for products with 20+ variants, the admin is forced to click all 20+ lightswitch to show the entire product selection of variants as featured.

I tought using a product field also because natively it is already possibile to sort variants from the panel with drag and drop (like a structure) while there is no native way to sort products.

If there is no other solution I guess we will have to apply the field to variants directly, but I think it would be a nice feature to access product data from a variant query somehow.
What do you think?
Thanks!

**Comment by nfourtythree** [comment]
Hi @masiorama 

> I guess that would work, but I sense it as a bit clunky from the panel admin point of view.
>
> I mean, from one side it would help handle things with a more granular approach, but from the other point of view, for products with 20+ variants, the admin is forced to click all 20+ lightswitch to show the entire product selection of variants as featured.

You are correct this could seem awkward from the store admin's perspective. 

To solve this you could: 
- have the lightswitch on both product and variant field layouts
- conditionally hide it for the store admins on the variant field layout
- add code to a module that uses the product after save event
- in that code to keep that variants' lightswitch field in sync with value from the product 

In theory, that means there is no more work for the store admin, they don't see it on the variant and only have to worry about the field on the product. But gives you, the developer, the data in the right location to make the query.

> I thought using a product field also because natively it is already possible to sort variants from the panel with drag and drop (like a structure) while there is no native way to sort products.

The [manual sorting of products](https://github.com/craftcms/commerce/issues/3630) is something we are looking at for the future of Commerce.

> If there is no other solution I guess we will have to apply the field to variants directly, but I think it would be a nice feature to access product data from a variant query somehow.

This is something we could look into, but there are a lot of performance implications that come with this. Commerce follows Craft's methodology of variants being nested elements of products. And in Craft nested elements do not have the feature of querying by their owner's data.

It is worth noting that the Variant query has a `hasProduct()` method that accepts criteria or a Product query. Similarly, the Product query has a `hasVariant()` method that accepts criteria or a Variant query. These two things can help you target either products or variants more specifically.

Hope this helps, thanks!

**Comment by lukeholder** [comment]
We now have this feature within a PR slated being a part of 5.2 https://github.com/craftcms/commerce/pull/3663

Will update this ticket once 5.2 is out. We don't have a public timeline for this at the moment.

Thanks
