### ISSUE TITLE
[5.x]: Unable to Modify salePrice Dynamically in Craft Commerce 5

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/commerce#3662]
### Description

I am trying to dynamically modify the prices before the checkout step in Craft Commerce 5.

I followed the documentation: [Dynamically Customizing Line Item Prices](https://craftcms.com/knowledge-base/dynamically-customizing-line-item-prices)

However, when I attempt to modify the `salePrice` property, I receive an error. Here's the code that I used:

```php
use craft\commerce\events\LineItemEvent;
use craft\commerce\services\LineItems;
use yii\base\Event;

Event::on(
    LineItems::class,
    LineItems::EVENT_POPULATE_LINE_ITEM, 
    function(LineItemEvent $event) {
        /** @var LineItem **/
        $lineItem = $event->lineItem;

        $lineItem->salePrice = 123.45;
        $lineItem->price = 123.45;
    }
);
```

### Steps to reproduce

1. Implement the code above to dynamically modify the `salePrice` and `price` in Craft Commerce 5.
2. Trigger the `LineItems::EVENT_POPULATE_LINE_ITEM` event.

### Expected behavior

The `salePrice` and `price` should both be updated dynamically for the line item without any errors.

### Actual behavior

The following error is thrown when attempting to modify the `salePrice` property:

```
Setting read-only property: craft\commerce\models\LineItem::salePrice
```

This error only occurs for `salePrice`, while `price` can be modified without issues.

For context, here's my adapted code where I am dynamically adjusting the price and updating the stock based on an external API (this issue relates to this discussion on StackExchange: [Craft Commerce 5: Dynamically Update Variant Price and Stock](https://craftcms.stackexchange.com/questions/41938/craft-commerce-5-dynamically-update-variant-price-and-stock)):

```php
/**
 * Register event handler to dynamically adjust price and inventory levels
 */
private function registerPopulateLineItemEvent(): void
{
    Event::on(
        LineItems::class,
        LineItems::EVENT_POPULATE_LINE_ITEM,
        function (LineItemEvent $event) {
            // @var LineItem $lineItem
            $lineItem = $event->lineItem;

            // @var bool $isNew
            $isNew = $event->isNew;

            // Get the purchasable item (variant, product, etc.)
            $purchasable = $lineItem->getPurchasable();

            // Check if the custom field 'code' is available
            $code = $purchasable->getFieldValue('code');

            // If the custom 'code' field is empty, use the SKU
            $sku = !empty($code) ? $code : explode(' ', $purchasable->sku)[0];

            // Fetch external API data for the SKU
            $response = Craft::$app->apiService->sendRequest("/articles/{$sku}");
            $status = $response['status'] ?? null;

            if (!empty($response) && $status !== 'NOT_FOUND') {
                // Update price temporarily for the line item
                $taxCategoryId = $purchasable->taxCategoryId;
                $taxRate = Commerce::getInstance()->getTaxRates()->getTaxRateById($taxCategoryId);
                $isTaxIncluded = $taxRate->include ?? false;
                $priceToCompare = $isTaxIncluded ? $response['unitPriceTTC'] : $response['unitPriceHT'];

                // Set both the price and salePrice for this specific LineItem
                $lineItem->salePrice = (float) $priceToCompare;
                $lineItem->price = (float) $priceToCompare;

                // Handle stock update using inventory levels
                if (isset($response['stock'])) {
                    $apiStock = (int) $response['stock'];

                    // Get the current inventory levels for the variant
                    $commercePlugin = Commerce::getInstance();
                    $inventoryItem = $commercePlugin->getInventory()->getInventoryItemByPurchasable($purchasable);
                    $firstInventoryLevel = $commercePlugin->getInventory()->getInventoryLevelsForPurchasable($purchasable)->first();

                    if ($inventoryItem && $firstInventoryLevel && $firstInventoryLevel->getInventoryLocation()) {
                        // Prepare an inventory update
                        $updateInventoryLevels = UpdateInventoryLevelCollection::make();
                        $updateInventoryLevels->push(new UpdateInventoryLevel([
                            'type' => \craft\commerce\enums\InventoryTransactionType::AVAILABLE->value,
                            'updateAction' => \craft\commerce\enums\InventoryUpdateQuantityType::SET,
                            'inventoryItem' => $inventoryItem,
                            'inventoryLocation' => $firstInventoryLevel->getInventoryLocation(),
                            'quantity' => $apiStock,
                            'note' => 'Stock update from external API',
                        ]));

                        // Execute the inventory update
                        $commercePlugin->getInventory()->executeUpdateInventoryLevels($updateInventoryLevels);
                    }
                }
            }
        }
    );
}
```

**Question:**
How can I modify the `salePrice` property without encountering the "read-only" error?

**Open question:**

Why is it possible to update stock in real-time, but not the price? It seems limiting that inventory can be updated directly via my API, while updating prices requires periodic adjustments through a tool like FeedMe. Is there a reason for this distinction, and are there any plans to allow dynamic price updates similar to inventory changes? 

### Craft CMS version

5.4.2

### Craft Commerce version

5.1.0.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @romainpoirier 

Just yesterday we updated the [Dynamically Customising Line Item Prices](https://craftcms.com/knowledge-base/dynamically-customizing-line-item-prices) article. So hopefully this will point you in the right direction.

To summarise in your specific example `salePrice`, as of Commerce 5, is a computed property. This means it is the lowest value from `price` and `promotionalPrice` on the line item. These values are populated from the purchasable (variant) and can be altered using the events shown in the article. 

In your first code example you can simply remove the `$lineItem->salePrice = 123.45;` line and things should work.

Hope this helps, thanks!

**Comment by romainpoirier** [comment]
Thank you, I'll look into it.

Just a quick note to inform you that this comment is incomplete:
> // Create a 
> $addOnItem = Commerce::getInstance()->getLineItems()->create($order, [
>     'purchasableId' => $fee->id,
> ]);
