### ISSUE TITLE
[5.x]: hasStock: true not working correctly on all products

### ISSUE THREAD

**Issue by bartrylant** [craftcms/commerce#3668]
### Description
I'm running
```
{% craft.products().hasVariant({hasStock: true}).all() %}
```
However, some products that do have stock, are not shown. I have absolutely no idea why and I cannot see anything those products have in common. If I go through all variants and get the stock for every variant with `variant.stock`, I get the corrects numbers. It just seems like the `hasStock: true` parameter doesn't work as it should.

### Steps to reproduce

1. Run {% craft.products().hasVariant({hasStock: true}).all() %}

### Expected behavior
Show products that have variants with stock

### Actual behavior
Some products that have variants with stock, don't get shown.

### Craft CMS version

5.4.2

### Craft Commerce version

5.1.1

### PHP version

8.3.8

### Installed plugins and versions

-

**Comment by bartrylant** [comment]
I noticed this happens with products/variants that are imported with Feed Me. If stock was edited with Feed Me, you have to run `craft resave/products` to get the correct stock on the front-end.

**Comment by lukeholder** [comment]
Thanks for reporting this. We have fixed this for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#dabeeb5470c4db92e2f5ec75b5f05b99efc0123d as 5.1.1",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by lukeholder** [comment]
Please note, you will still need to resave you products, but this will fix the issue going forward as stock is updated.

**Comment by nfourtythree** [comment]
Commerce `5.1.2` has now been released with this fix included.

Thanks!
