### ISSUE TITLE
[5.x]: Missing changelog for Craft Commerce 5.1.1 release

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/commerce#3669]
### Description
The latest release of Craft Commerce, version 5.1.1, does not include a changelog. It is important for administrators and developers to understand the changes, fixes, or improvements in each version. Could you please clarify what has changed in this release and update the changelog accordingly?

### Steps to reproduce
1. Navigate to the [release page](https://github.com/craftcms/commerce/releases).
2. Check the release notes for version 5.1.1.

### Expected behavior
The changelog for version 5.1.1 should be available and provide details on changes, fixes, or new features introduced.

### Actual behavior
The release does not contain any changelog or description of the changes.

### Craft CMS version

5.4.3

### Craft Commerce version

5.1.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @romainpoirier 

Thank you for your feedback.

The release description should have been automatically generated from the [CHANGELOG.md](https://github.com/craftcms/commerce/blob/5.1.1/CHANGELOG.md#511----2024-09-10) but it seems something must have gone wrong even though it existed in the file.

We have [updated the 5.1.1 release description](https://github.com/craftcms/commerce/releases/tag/5.1.1) with the correct changelog item.

Hope this helps, thanks!
