### ISSUE TITLE
Accessing cart recalculates adjustments and re-saves all line items

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#367]
### Description

Trying to chase down the culprit for a high query-count on a cart page, and came to realize that whenever a cart is accessed via `craft.commerce.carts.cart`, its line items and adjustments are all re-saved.

This is actually really handy for development (as the criteria for custom adjustments are updated), but in production, I was wondering whether it's possible to avoid this under any circumstances?

Our particular use case—and, I suppose Taxes + Discounts—are all complicated by the fact that the math for an adjustment might change underneath an order, so without some sophisticated `cache`-tag-like dependency watcher or an all-too-eager "recalculate all adjustments" trigger, I understand that this might just not be a reasonable ask.

For testing, I removed all registered adjusters, and compared the number of queries for an essentially empty template, and again with a single call to `craft.commerce.carts.cart`. I've disabled a business-logic plugin that registers some custom adjusters, so this should be only native functionality represented, here:

Bare: 9 queries
With cart call: 286
Line items in cart: 11

Note that the "with cart call" above is _just fetching the cart via Twig, not outputting anything about the cart itself_.

### Steps to reproduce

Beforehand: Add purchasables to your cart.

1. View `commerce_orderadjustments` and `commerce_lineitems` tables, sorted with the most recently updated records at the top;
2. Access any route that calls `Commerce\Carts::getCart()`. 👀 a the number of DB queries;
3. Refresh the tables, and notice that the rows have new timestamps.

### Additional info

- Craft version: 3.0.9, Commerce 2.0.0-beta.5
- PHP version: 7.1.16
- Database driver & version: Postgres 10.3
- Plugins & versions: Commerce, Stripe, Redactor, Typogrify, custom business logic plugin implementing some adjusters.

**Comment by lukeholder** [comment]
Thanks for the report. 

When getting the cart with `craft.commerce.carts.cart` or `Commerce\Carts::getCart()` the cart only saves when it meets one of these conditions:

```php
if ($changedCurrency || $changedOrderLanguage || $changedIp || $changedCustomerId || $newOrder) {
        Craft::$app->getElements()->saveElement($this->_cart, false);
}
```

It saves if it is new, but shouldn't save unless something else about the environment changed, like the user.

Happy to look into not re-saving line items and adjustments unnecessarily.

**Comment by AugustMiller** [comment]
Quick update—looks like `orderLocale` is not comparing correctly.

Here's the odd bit: all the order locales are getting saved in the database as a space-padded string, rather than a trimmed one. ~The `Install` migration sets up the `orderLocale` column as `char(12)`, which is curious.~

Ok, so realized in the process that this may have been patched out in Beta 5.

Check this out! https://github.com/craftcms/commerce/issues/363

Turns out the extra spaces were causing the comparison to fail, but even after reassignment and saving, they reappeared, likely because of the column type?

I imagine we're good here, but I haven't been able to pull down Beta 5 to confirm.

**Comment by lukeholder** [comment]
Thanks, I believe #363 fix should fix the issue. Thanks.
