### ISSUE TITLE
[4.x]: Using Address ID in subscription fields - how we can we update them all as part of the Craft 3 -> 4 Migration

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce#3671]
### Description
In a craft 3 commerce we have subscriptions and these generate new orders based on a schedule.
As part of this process, we currently store the address ID for billing and shipping addresses so that we can assign these when building new orders.

<img width="1111" alt="Screenshot 2024-09-12 at 17 11 11" src="https://github.com/user-attachments/assets/06258696-1bbb-4c9b-8b75-44d463609669">

With the  Craft 3 to 4 Migration - all the addresses are migrated and created with new ID's,
so our old iDs stored against each subscription would now be dead/broken.

What is the solution for this?
Can we hook into the migration scripts or create our own to handle this?
Does Craft keep a log of old address IDS and new ones it migrates them to? 
Is there a list of the original ID in the database? 

We really need a solution as there are over 2 thousand subscriptions and each will have a Billing and Shipping ID. 
It is a potentially blocker from upgrading at the moment, and I cannot see an easy path out of this. 

As an example.
Previous address is: 190257 is now 311096
Previous address is: 135 is now 177320

There is no pattern to the new ID vs the old id (it hasn't increased by X amount for example).

Thanks.
Terry Upton

### Craft CMS version

Craft Pro 4.12.2

### Craft Commerce version

4.6.11

### Installed plugins and versions

-

**Comment by terryupton** [comment]
Further issues regarding this address stuff, is that any existing orders built for subscriptions have no address data associated with them. I am unsure why this is? As they are still normal orders, but it must be something to do with the migration process and how Craft migrations run and re-link address information for orders.


<img width="1626" alt="Screenshot 2024-09-13 at 14 27 03" src="https://github.com/user-attachments/assets/5034f198-e44d-4c00-be54-091a4c5538e1">

**Comment by lukeholder** [comment]
Communicating about this issue in support channels.

**Comment by terryupton** [comment]
On further investigation, orders with the following status **DID** migrate the addresses for Subscription orders.

- Cancelled
- Full Refund
- Partial Refund

It would appear that only orders with the 'Shipped' status did not migrate all the addresses, which is the status with the majority of the orders. is there any known bug around why certain status would not migrated addresses for Subscription orders? The addresses are migrated for manual orders. This is a real blocker at the moment and I can't upgrade without a solution or fix.

Issue has been reported to Pixel and Tonic and I am awaiting feedback.
Any thoughts on this @lukeholder ?

**Comment by lukeholder** [comment]
Custom code was creating orders and the same address ID was applied to each order. Order should have address IDs that are unique to the order. Responded over support.
