### ISSUE TITLE
[5.x]: Cannot add user's saved address when creating order

### ISSUE THREAD

**Issue by apitel** [craftcms/commerce#3673]
### Description
When creating a Craft Commerce Order in the control panel and selecting a user that has saved addresses, the default address does not auto-populate and Select Address is disabled. 

### Steps to reproduce

1. Create a User
2. Add a saved address for that User
3. Create an order and select that User
4. Try to add an address

### Expected behavior
Default shipping and billing addresses should auto-populate. Select Address should be available to select a non-default saved address. 

### Actual behavior
![CleanShot 2024-09-13 at 09 31 11@2x](https://github.com/user-attachments/assets/e869a96a-fa2a-4aec-a524-8fa562a190a7)

### Craft CMS version

Craft Pro 5.4.3

### Craft Commerce version

5.1.1

### PHP version

8.3.10

### Operating system and version

Linux 5.15.0-117-generic

### Database type and version

MySQL 8.0.39

### Image driver and version

GD 8.3.10

**Comment by nfourtythree** [comment]
Commerce `5.1.2` has now been released with this fix included.

Thanks!
