### ISSUE TITLE
[4.x]: How to search into variant custom field

### ISSUE THREAD

**Issue by philippe-leeroy** [craftcms/commerce#3674]
### Description
We have created a field - oldSku - that is searchable, that is put into a product type as a variant field. 
And when, we use the .search the product with the exact old sku the product is not found.

In the web interface, we only a search field and we use it to search into the products.
![image](https://github.com/user-attachments/assets/9427a804-761a-4454-8e15-ff55cce61c04)

Just so you know, this is working well with the sku field.

### Steps to reproduce

1. We have a variant product field that is called "oldSku". This field is setup with the searchable option checked
![image](https://github.com/user-attachments/assets/804f18f1-541d-4340-a65d-6d047c1c0e8a)

2. It's added into the product type settings as a variant field.
![image](https://github.com/user-attachments/assets/fb400a6f-8836-43b4-8d49-deed00da101f)

3. Then, in the twig template, we call 
```
craft.products().type('products').orderBy('ordreAffichage ASC, id **DESC').siteId(currentSite.id).search(searchParam)
```

### Expected behavior
At least we could use the field handle to find product with the old sku, like that :
```
craft.products().type('products').orderBy('ordreAffichage ASC, id **DESC').siteId(currentSite.id).search("oldsku:TEST1234")
```
But it does not work at all...

### Actual behavior
We looked into the db with this query :
```
SELECT distinct attribute FROM db.searchindex;
```
 and we did not found any "oldsku" value

Is there something missing in the process... please help us :pray: 

### Craft CMS version

4.10.4

### Craft Commerce version

4.6.3.1

### PHP version

8.2.22

### Operating system and version

Linux 6.8.0-40-generic

### Database type and version

MySQL 8.0.36

### Image driver and version

 	Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by nfourtythree** [comment]
Hi @philippe-leeroy 

Thank you for your message.

I see that you added the custom field to the variant. With that being the case you will need to ensure you are searching for the data on the variant element. If you want to do that from the product perspective you can use the `hasVariant()` method on the product query.

I have updated the query you specified with this method, the following should work for you

```twig
{% set products = craft
  .products()
  .type('products')
  .orderBy('ordreAffichage ASC, id **DESC')
  .siteId(currentSite.id)
  .hasVariant(craft.variants.search(searchParam))
  .all() %}
```

Hope this helps, thanks!

**Comment by philippe-leeroy** [comment]
Thank you very much !

**Comment by philippe-leeroy** [comment]
I realized that it's not possible to filter product with custom variant field in the control panel. 

Do you think, that it could be implemented ?

**Comment by nfourtythree** [comment]
Hi @philippe-leeroy 

Thank you for your response.

The way we would need to fully support the feature you mentioned would require us to look at adding nested condition builders into the core of Craft. This undertaking would require a careful, planned approach due to its complexity. We want to assure you that this matter is on our radar, and we are actively discussing it internally.

In the meantime, we have decided to implement a new "Variant Search" condition rule within Commerce (for product conditions). This feature will enable search terms to be utilised in a variant query, effectively refining the products returned.

You can track the progress of this feature here: https://github.com/craftcms/commerce/issues/3689.

Thanks!

**Comment by philippe-leeroy** [comment]
I think it could helps, thanks.

Looking forward to seeing this!
