### ISSUE TITLE
[5.x]: Shipping methods with same name in multi store

### ISSUE THREAD

**Issue by white-lukas** [craftcms/commerce#3676]
### Description
When creating a multi store shop, you are unable to create shipping methods with the same name in the different stores, handles do can be the same, this feels a bit strange as they are completely separate and  you might have the same shipping methods between stores

### Steps to reproduce

1. create a multi store
2. Add a shipping method to the first store (eg. pickup)
3. Try to add the same shipping method to the second store
4. You get `Name "pickup" has already been taken.` 

### Expected behavior

Name and handles of shipping methods should be separate between stores

### Craft CMS version

5.4.3

### Craft Commerce version

5.1.1

### PHP version

8.3.11

### Operating system and version

Ubuntu 24.04

### Database type and version

mysql 8.0

**Comment by lukeholder** [comment]
Thanks for reporting, this has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#ff3994c915cea65e287bb65f50e85e0d9aca4857 as 5.1.1",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by nfourtythree** [comment]
Commerce `5.1.2` has now been released with this fix included.

Thanks!
