### ISSUE TITLE
[5.x]: Deleting a variant results in error 500 when viewing orders

### ISSUE THREAD

**Issue by gopeter** [craftcms/commerce#3677]
### Description

If I place (and complete) an order with a variant which I delete afterwards, I can't open the order anymore, because it throws an error 500. I'm not really sure if this is a bug or intentional behavior, but I can't really imagine that you want to run backend users in such errors if this happens.

### Steps to reproduce

1. Create product with variants
2. Buy this variant
3. Delete this variant from the product
4. Open the order in the backend

### Expected behavior

It should be possible to open the order anyway.

### Actual behavior

I get an error 500:

![image](https://github.com/user-attachments/assets/0b5d3f71-a0cf-4784-9b7a-b3cce9680268)

### Craft CMS version

Craft Pro 5.4.3

### Craft Commerce version

5.1.1

### PHP version

8.2.20

**Comment by nfourtythree** [comment]
Commerce `5.1.2` has now been released with this fix included.

Thanks!
