### ISSUE TITLE
[4.x][5.x]: Tidy up UserException thrown during pending user purge?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3686]
### What happened?

Could the UserException thrown during the pending user purge be reworked, we use sentry to monitor exceptions and this has added ~100k issues to our usage:

https://github.com/craftcms/commerce/blob/8f6a112deb4e01536d528dadc4e6351b9fc8f075/src/services/Orders.php#L188-L200

As the user is correctly not being deleted as the user (customer) has an order, could this not be handled - the activation code / state be removed, or event added to the user purge logic so commerce could hook into that and exclude users that have an order?

Also is there a reason you don't return the`isValid = false` and intead throw the excpetion?

>You may set [[\yii\base\ModelEvent::$isValid]] to `false` to prevent the element from getting deleted.

Impacts both 4.x and 5.x

### Craft CMS version

4.10.8

### Craft Commerce version

4.6.7

### Installed plugins and versions

-

**Comment by samhibberd** [comment]
Craft has fixed this now, so just a case of awaiting the release and then we can archive off the Sentry issue

**Comment by samhibberd** [comment]
Thanks @nfourtythree @lukeholder

**Comment by nfourtythree** [comment]
Hi @samhibberd 

Commerce versions `4.6.13` and `5.1.3` have now been released with this fix included.

Thanks!

**Comment by samhibberd** [comment]
Actually @lukeholder @nfourtythree thinking about it, this doesn't change much for us (as in we still push craft errors to Sentry).

Would it be fair to argue in this case that this is not actually an error, or a warning, it's doing exactly what it should, prevent the deleting of an user that has an order. Should the logging level not be set to info?

**Comment by peteeveleigh** [comment]
Agree with @samhibberd. This shouldn't be logged as an Error. It's Info or, at worst, a Warning.

**Comment by lukeholder** [comment]
@peteeveleigh @samhibberd is is logged as info now: https://github.com/craftcms/cms/pull/13494/files#diff-b306bfe80cb67a6f20bb99a1019385d006e706dc7033449406686bf8a83f3026R1246

Let me know if you have any other questions.

Thanks

**Comment by lukeholder** [comment]
Sorry just realised you were referring to our logging in Commerce.

I have gone ahead and fixed that for the next release in 5.3.x

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#5a31da5714f7442f5fd864274ebaccbf51a95db3 as 5.3.0.2",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by nfourtythree** [comment]
Commerce version `5.3.1` has now been released with this fix included.

Thanks!

**Comment by samhibberd** [comment]
Will this make it into the 4.x branch @nfourtythree ?

**Comment by nfourtythree** [comment]
HI @samhibberd 

Yes this is in the `4.x` branch with this commit: fee301fbf450274b81c0c946234674a1ef4cd2fb

It will be included in the next release of Commerce 4.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "4.x-dev as 4.8.0.1",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Hi 

This update has now been back ported to Commerce 4 in version `4.8.1` which has just been released.

Thanks!
