### ISSUE TITLE
[5.x]: Wrong shipping categories in variant

### ISSUE THREAD

**Issue by gopeter** [craftcms/commerce#3690]
### Description

I have two shops: an EUR and a CHF store, both with just default shipping categories. But I can't select the default shipping category of the CHF store since it shows just the EUR one.

![image](https://github.com/user-attachments/assets/0dc1a4d6-4899-49bf-b52f-919be745865c)

![image](https://github.com/user-attachments/assets/ff311350-57af-4f51-a644-fd1354a61d4b)

![image](https://github.com/user-attachments/assets/d1937d7c-8d1b-483a-866d-f2ffe1f161ce)

### Steps to reproduce

1. Create two sites and two stores, connect one store with one site
2. Create a product and a variant
3. Create a default shipping category for each store (should be done automatically I think?)

### Expected behavior

Just the shipping categories for the store of the current site should be visible.

### Actual behavior

The shipping categories of the default site (I think?) are available.

### Craft CMS version

Craft Pro 5.4.4

### Craft Commerce version

5.1.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@gopeter Did you make sure to make the shipping category available to the product type?

![CleanShot 2024-09-24 at 18 09 27@2x](https://github.com/user-attachments/assets/0c19363c-a335-4fd7-a199-fad046ef1772)

**Comment by gopeter** [comment]
Yes, tried this also. Now it shows shipping categories from other shops as well:

![image](https://github.com/user-attachments/assets/968db32d-b29a-4720-b92f-0852919ab413)

**Comment by lukeholder** [comment]
Thanks. I see the issue. Will get a fix out tonight. Thanks.

**Comment by gopeter** [comment]
Great, thanks a lot! It seems that this happens to taxes also, where my line items where taxed with rates that I've created in different shops.

**Comment by lukeholder** [comment]
Thanks for reporting. This has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#0a27b4b204d59c6b1412bd1b5effab0e95095d02 as 5.1.2",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

As for Tax Categories, these are global across all stores but there was a bug where they were showing up for product types that were not selected for that product. This was also fixed.

**Comment by gopeter** [comment]
Great, thanks a lot!

**Comment by nfourtythree** [comment]
Commerce version `5.1.3` has now been released with this fix included.

Thanks!
