### ISSUE TITLE
[5.x]: If an error occurs during 'send email' via the orders page, there is no feedback to the admin user

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [craftcms/commerce#3693]
### Description
If an error occurs during mail transport, there is no error indicated to the admin user, just an infinite spinner. The error does get logged in the javascript console.

<img width="1414" alt="Screenshot 2024-09-26 at 16 28 20" src="https://github.com/user-attachments/assets/29369a98-ad62-41ae-b65a-99438be0c989">

<img width="284" alt="Screenshot 2024-09-26 at 16 29 02" src="https://github.com/user-attachments/assets/4a6ec92d-1d2d-47a3-b1c5-48563d17a0c2">

### Steps to reproduce

1. Provide invalid mail settings in email settings, e.g. SMTP transport with invalid host, or some custom transport with invalid API key.
2. Try to send a commerce email from the order detail page.

### Expected behavior

1. An in page notification telling the admin an error has occurred.

### Actual behavior

1. Infinite spinner and javascript console error.

### Craft CMS version

5.4.4

### Craft Commerce version

5.1.1

### PHP version

8.3.9

### Operating system and version

Darwin 22.6.0

### Database type and version

MySQL 8.3.0

### Image driver and version

GD 8.3.9

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @jlawrence-yellostudio 

Thank you for reporting this issue.

We have pushed a fix for this which will be included in the next release of Commerce.

Thanks!

**Comment by lukeholder** [comment]
This is now fixed in [5.1.4](https://github.com/craftcms/commerce/releases/tag/5.1.4), thanks!
