### ISSUE TITLE
[5.x]: Can't edit SKU

### ISSUE THREAD

**Issue by AndrewMac** [craftcms/commerce#3697]
### What happened?

Pretty simple, really. I have a product with an SKU. I try to change the SKU. Commerce says the Product Variant has been saved, but the SKU hasn't changed. I have multi-store, but I'm not sure if that's part of the issue. I think I might remember changing SKUs successfully when it was just a single store …

That was editing via the slideout, by the way. So I tried the "View in a new tab" command, to see if that helped. But that just gave an error:

HTTP 400 – Bad Request – yii\web\BadRequestHttpException
Invalid data received for parameter "template".

### Craft CMS version

Pro 5.4.6

### Craft Commerce version

Pro 5.1.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Hi Andrew, 

The first one about the SKU not saving. I just tried to reproduce and couldn't see this occur:

https://github.com/user-attachments/assets/9f1dbab9-0ae4-4c4a-91e8-dba9e4f6b24c

I have multi-store set up and the sku is changing as expected based on the video. It takes a second for the variant listing in the product to refresh though.

As for the second error with viewing, can you make sure you have a template path set up for your product type:

![CleanShot 2024-09-30 at 15 43 55@2x](https://github.com/user-attachments/assets/2348afc9-1a23-4fca-a215-dccbc5ef91b5)

Can you double check the SKU is not saving and let me know if adding a template path to the product type fixes that other error?

By the way, you are reporting 2 issues in the same ticket, it might make it easier to help if you report things separately. Thanks!

**Comment by AndrewMac** [comment]
Hi Luke, and sorry. I'm sick at the moment but have to work on this. So I'm not in a great mood. You're right about the template, and that's my fault. I was actually testing, and replicating, the SKU issue on a test installation I have set up to test plugins before installing on any of my client's project sites. So it's not as well set up as it should be, and on the main site it is indeed working okay. Also, my mistake: I was actually trying to test by editing the variant in a dedicated screen rather than in the slide-out, and forgot that the "View in new tab" command is for looking at the product. I think my brain is dead.

If the SKU is not an issue for you, I will set up a very basic Craft/Commerce test site now, to check it's working okay and to try and isolate the issue to see if it's a plugin that's causing the problem. Since I can replicate the issue on two sites, if the 'vanilla' install works okay then I need to do more testing.

Again, sorry for the lack of clarity. I think I need to stop working on this project and get some rest, then come back to things when I've recovered from this illness.

**Comment by AndrewMac** [comment]
Hi Luke, and sorry. I'm quite sick at the moment but have to work on this project. So I'm not in the best of conditions and moods for dealing with problems … 

You're right about the template, and that's my fault. I was testing, and replicating, the SKU issue on a test installation I have set up to test plugins before installing on any of my client's project sites. So it's not as well set up as it should be, and on the main site it is indeed working okay. Also, my mistake: I was actually trying to test by editing the variant in a dedicated screen rather than in the slideout, and forgot that the "View in new tab" command is for looking at the product. I think my brain is dead. But that second install did at least confirm that it's a repeatable issue.

But thanks for testing, and since editing the SKU is working okay for you, I will set up a very basic Craft/Commerce test site now, to confirm it's working okay and to then try and isolate the issue to see if it's one of the installed plugins that is causing the problem. Since I can replicate the issue on two sites, if the 'vanilla' install works okay then I need to do more testing.

Again, sorry for the lack of clarity. I think I need to stop working on this project and get some rest, then come back to things when I've recovered from this illness.

**Comment by AndrewMac** [comment]
Hi Luke. I've set up a brand new test install and the SKU is updating as it should. So I will close this issue now and assume it's a plugin that's causing things to go wrong. I will decide what to do when I work that out. Thanks for your help with this.

**Comment by lukeholder** [comment]
Glad it was sorted!
