### ISSUE TITLE
[5.x]: Catalog Pricing Rule Description Not Displaying in CP or Front-End

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/commerce#3699]
### Description

In Craft CMS version 5.4.6 and Craft Commerce version 5.1.2, I am encountering an issue with the Catalog Pricing Rule. The content of the **Description** field does not display in the Control Panel (CP) nor on the front-end. However, when I check the pricing rule in the `commerce_catalogpricingrules` table, the `description` column is correctly populated.

<img width="1696" alt="Capture d’écran 2024-09-30 à 16 02 57" src="https://github.com/user-attachments/assets/9673c86d-4a1f-4ccf-bd4f-70bcea772435">
<img width="1567" alt="Capture d’écran 2024-09-30 à 16 03 12" src="https://github.com/user-attachments/assets/9b29ae40-0d84-4223-9c53-72fb6a26b0f6">

### Steps to reproduce

1. Create a Catalog Pricing Rule in Craft Commerce.
2. Fill in the **Description** field.
3. Save the rule.
4. View the rule in the CP and the front-end.

### Expected behavior

The content of the **Description** field should be displayed in both the CP and the front-end.

### Actual behavior

The content of the **Description** field is not visible in either the CP or the front-end, despite being correctly stored in the database.

### Craft CMS version

5.4.6

### Craft Commerce version

5.1.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @romainpoirier 

Thank you for your feedback and for bringing this to our attention.

We have pushed a fix for this issue which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.1.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by romainpoirier** [comment]
Thank you! As the site needs to go live very soon and I prefer not to use a dev version in production, when is the next release planned (approximately)?

**Comment by nfourtythree** [comment]
Commerce version `5.1.3` has now been released with this fix included.

Thanks!

**Comment by dennis-vdw** [comment]
Hi @romainpoirier @nfourtythree 

Maybe off-topic, but any idea how to display the description of a catalog pricing rule on the frontend? So I can show it in labels?

Craft CMS version: 5.6.10.2
Craft Commerce version: 5.3.4

**Earlier, this was working before the Craft 5 upgrade:**

{% set sale = node.salePrice ?: false %}

{% if sale %}
     {{ sale.description ? sale.description : 'Korting' }}
{% endif %}

When I dump this, the description is achievable..
{{ dump(craft.commerce.catalogpricingrules.allActiveCatalogPricingRules) }}

**Comment by nfourtythree** [comment]
Hi @dennis-vdw 

Thank you for your message.

Just to get an understanding of what you are trying to achieve. Is this when you are looping through line items to show which promotional prices are being applied?

Thanks

**Comment by dennis-vdw** [comment]
Hi @nfourtythree,

Thanks for your repsonse!

Yes, I want to display the description of the catalog pricing rule for each simple/variant product that has one applied.

I think I have the fix for this, but in my opinion, it is rather “unwieldy”.

---

{% set defaultVariant = node.defaultVariant %}

{% set catalogPricingRuleId = craft.commerce.catalogPricing.createCatalogPricesQuery().andWhere({purchasableId: variant.id}).andWhere(["not", {catalogPricingRuleId: null,}]).addSelect("catalogPricingRuleId").addGroupBy("catalogPricingRuleId").collect().pluck("catalogPricingRuleId").first() %}

{% set catalogPricingRule = catalogPricingRuleId ? craft.commerce.catalogPricingRules.getCatalogPricingRuleById(catalogPricingRuleId) : null %}

{% if catalogPricingRule %}
   <div class="o-label">{{ catalogPricingRule.description ? catalogPricingRule.description : 'Sale' }}</div>
{% endif %}

**Comment by nfourtythree** [comment]
Hi @dennis-vdw 

Thank you for your response.

You are correct this is a long winded way of getting that data. This is something we should make easy in the core of Commerce.

I have created an issue to follow along the progress: https://github.com/craftcms/commerce/issues/3910

Below is also an example of how you could populate this data on to a line item's snapshot so it is easily accessible when looping over items in the cart.

```php
Event::on(LineItems::class, LineItems::EVENT_POPULATE_LINE_ITEM, function(LineItemEvent $event) {
    if (!Plugin::getInstance()->getCatalogPricingRules()->canUseCatalogPricingRules()) {
        return;
    }

    if ($event->lineItem->type !== LineItemType::Purchasable) {
        return;
    }

    $catalogPricingRuleIds = (new Query())
        ->select([
            'cp.catalogPricingRuleId',
        ])
        ->from(Table::CATALOG_PRICING . ' cp')
        ->leftJoin(Table::CATALOG_PRICING_RULES . ' cpr', '[[cpr.id]] = [[cp.catalogPricingRuleId]]')
        ->where(['cp.purchasableId' => $event->lineItem->purchasableId])
        ->andWhere(['cp.storeId' => $event->lineItem->getOrder()->getStore()->id])
        ->andWhere(['not', ['cp.catalogPricingRuleId' => null]]);

    if ($event->lineItem->getOnPromotion()) {
        $catalogPricingRuleIds->andWhere(['cp.isPromotionalPrice' => true]);
        $catalogPricingRuleIds->andWhere(['cp.price' => $event->lineItem->promotionalPrice]);
    } else {
        $catalogPricingRuleIds->andWhere(['cp.isPromotionalPrice' => false]);
        $catalogPricingRuleIds->andWhere(['cp.price' => $event->lineItem->price]);
    }

    $catalogPricingRuleIds = $catalogPricingRuleIds->column();

    if (empty($catalogPricingRuleIds)) {
        return;
    }

    $activePricingRules = Plugin::getInstance()->getCatalogPricingRules()->getAllActiveCatalogPricingRules($event->lineItem->getOrder()->storeId);

    if ($activePricingRules->isEmpty()) {
        return;
    }

    $rule = $activePricingRules->filter(function(CatalogPricingRule $cpr) use ($catalogPricingRuleIds, $event) {
        $userIds = $cpr->getUserIds();

        if (!empty($userIds) && !$event->lineItem->getOrder()->getCustomer()?->id) {
            return false;
        }

        if (!empty($userIds) && !in_array($event->lineItem->getOrder()->getCustomer()->id, $userIds)) {
            return false;
        }

        return in_array($cpr->id, $catalogPricingRuleIds);
    })->first();

    if (!$rule) {
        return;
    }

    $snapshot = $event->lineItem->getSnapshot();
    $snapshot['catalogPricingRule'] = $rule;

    $event->lineItem->setSnapshot($snapshot);
});
```

We will take a look at making the above mentioned improvement, thank you for bringing this to our attention!

Thanks!

**Comment by dennis-vdw** [comment]
Hi @nfourtythree,

Thanks again for your quick response and for taking the time to look into it further!
