### ISSUE TITLE
Can't save Store Location

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#370]
Database driver & version: MySQL 5.7.21
Craft CMS: Craft Solo 3.0.10.2
Craft Commerce: 2.0.0-beta.5
Redactor: 2.1.0

Simple enough, when I try to save the store location, I get a "Can't save" error message at the top. I saw someone with the same issue on the Slack Channel.

After some tests, it looks like First and Last name are required, even though the * is not there. Most of the time, it would only be a company name in there so it should not be required.

**Comment by lukeholder** [comment]
Fixed in 0a1a5d9358cec0944941b1da55e9b4969fd284af
