### ISSUE TITLE
[5.x]: Pring Rules - Customer condition without matching customer

### ISSUE THREAD

**Issue by thibaultjadoul** [craftcms/commerce#3700]
### Description

I am encountering an issue with **Catalog Pricing Rules** in Craft Commerce 5 using the following versions:

- "craftcms/cms": "5.4.6"
- "craftcms/commerce": "5.1.2"

I have a series of **Pricing Rules** that are configured with conditions based on a **Product** (custom field related to a product category) and a **Customer** category (using a related-to-category condition for the customer).

The issue occurs when no users exist in the database for a specific **Customer Category**. In this scenario, the Pricing Rule applies to all other users, including anonymous users, who then receive unintended discounts. I had to resolve this issue temporarily by creating fake users for each of my **Customer Discount Group** categories to prevent anonymous users from receiving these discounts.

### Steps to reproduce

1. Create a **Catalog Pricing Rule** with conditions on:
   - Product (based on a custom field related to a product category).
   - Customer (based on a related category condition).
2. Ensure that no users exist in the database that match the **Customer Category** condition.
3. Check how the Pricing Rule is applied to anonymous or other users.

### Expected behavior

If no users exist in the database for the specified **Customer Category**, the Pricing Rule should not be applied to any other users, including anonymous users.

### Actual behavior

If no users match the **Customer Category** condition, the Pricing Rule is applied to all other users, including anonymous users, who receive significant discounts they are not supposed to be eligible for. This forces the creation of fake users to bypass the issue.

### Craft CMS version

5.4.6

### Craft Commerce version

5.1.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @thibaultjadoul 

Thank you for your feedback and for reporting this issue.

We have addressed the problem and pushed a fix which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.1.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks

**Comment by nfourtythree** [comment]
Commerce version `5.1.3` has now been released with this fix included.

Thanks!
