### ISSUE TITLE
[5.x]: Amount and duration of Catalog Pricing jobs when doing bulk edit/imports

### ISSUE THREAD

**Issue by white-lukas** [craftcms/commerce#3709]
### Description
When importing or editing a lot variants the queue is filled with a big amount of generating catalog pricing jobs. which each takes around ~2-3 seconds, if you than have an import that updates ~2000 variants, the queue is blocked for around 1h with all those jobs, while if you could do them in bulk like the `commerce/pricing-catalog/generate` cli command it would be done also be done in 3 seconds and the prices would be directly up-to-date ![Image](https://github.com/user-attachments/assets/1e22edfe-21b8-4d40-bbe6-9e7592e0a554)

Guess it would be a good improvement if it could for example take the bulk operations into account to combine all updated purchasable and generate the catalog prices in 1 job?

### Craft CMS version

5.4.6

### Craft Commerce version

5.1.3

### PHP version

8.3

**Comment by nfourtythree** [comment]
Hi @white-lukas 

Thank you for your message.

You can always prevent the job from being pushed to the queue. If you register the event handler before you start importing then the job won't be added to the queue. 

You can then call the CLI command or the service method yourself.

An example of the vent code would be:


```php
use craft\commerce\queue\jobs\CatalogPricing;
use yii\queue\PushEvent;
use yii\queue\Queue;

// ...

Event::on(Queue::class, Queue::EVENT_BEFORE_PUSH, function(PushEvent $event) {
    if ($event->job instanceof CatalogPricing) {
        $event->handled = true;
    }
});
```
