### ISSUE TITLE
[4.x]: Subscribing with a return url throws a warning if payment fails

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/commerce#3710]
### Description

When subscribing on the action `site/commerce/subscribe` with a parameter `returnUrl` and a declined payment method, the controller throws a warning which makes the request fail :

```
"name":"PHP Warning",
"message":"Attempt to read property \"id\" on null",
"code":2,
"error":"Attempt to read property \"id\" on null",
"exception":"yii\\base\\ErrorException",
"file":"/var/www/html/vendor/craftcms/commerce/src/controllers/SubscriptionsController.php",
"line":241
```

When using a return url the code doesn't check that the subscription was actually created there : https://github.com/craftcms/commerce/blob/4.x/src/controllers/SubscriptionsController.php#L239

Replacing that line with `if (!$error && $returnUrl) {` fixes the issue.

### Steps to reproduce

1. Create a request to  `site/commerce/subscribe` with a parameter `returnUrl`

### Expected behavior

The response sends a 422 or something

### Actual behavior

A warning is thrown

### Craft CMS version

4.12.4

### Craft Commerce version

4.6.12

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
The proper param is the `redirect` param using the redirect input `{{ redirectInput('my-page') }}`.

Having said that I see the issue if the subscription fails.

Thanks for reporting. This is fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#1b3642624244dadaf9ed008cfa7bccb63b379dbc as 4.6.13",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by nfourtythree** [comment]
Hi @ryssbowh 

Commerce `4.6.14` has now been released with this fix included.

Thanks!
