### ISSUE TITLE
[5.x]: |commerceCurrency('EUR',stripZeros=true) does not strip zeros

### ISSUE THREAD

**Issue by bartrylant** [craftcms/commerce#3716]
### Description
I'm using the `|commerceCurrency('EUR',stripZeros=true)` filter. However, prices still get shown as €XXX.00

### Craft CMS version

Craft Pro 5.4.6

### Craft Commerce version

5.1.3

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @bartrylant 

Thank you for bringing this to our attention.

We have pushed a fix for the issue which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.1.3",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Hi @bartrylant 

Commerce `5.1.4` has now been released with this fix included.

Thanks!
