### ISSUE TITLE
[5.x]: Permission group setup results in error "Call to a member function getStore() on null" when accessing dashboard

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/commerce#3732]
### Description:
I am trying to configure a permission group for administrators who should only have access to Craft Commerce orders and the users linked to those orders. 

Here is the permission group configuration I defined:

**General**:
- Access the control panel
- Access Craft Commerce

**Craft Commerce**:
- Manage orders
  - Edit orders
  - Delete orders
  - Capture payment
  - Refund payment

After logging in, the administrators encounter the following error when trying to access the dashboard:

```
Error: Call to a member function getStore() on null in /var/www/html/vendor/craftcms/commerce/src/widgets/AverageOrderTotal.php:50
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\commerce\widgets\AverageOrderTotal->init()
#1 /var/www/html/vendor/craftcms/cms/src/base/Model.php(87): yii\base\BaseObject->__construct()
#2 [internal function]: craft\base\Model->__construct(Array)
#3 /var/www/html/vendor/yiisoft/yii2/di/Container.php(411): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\commerce\\...', Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\commerce\\...', Array, Array)
#6 /var/www/html/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject(Array, Array)
#7 /var/www/html/vendor/craftcms/cms/src/helpers/Component.php(142): Craft::createObject(Array)
#8 /var/www/html/vendor/craftcms/cms/src/services/Dashboard.php(129): craft\helpers\Component::createComponent(Array, 'craft\\base\\Widg...')
#9 /var/www/html/vendor/craftcms/cms/src/controllers/DashboardController.php(75): craft\services\Dashboard->createWidget(Array)
#10 [internal function]: craft\controllers\DashboardController->actionIndex()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('dashboard/index', Array)
#15 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(318): yii\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/html/htdocs/index.php(12): yii\base\Application->run()
#19 {main}
```

Is the current permission group setup sufficient to achieve the expected behavior?

### Steps to reproduce

1. Configure the permissions as listed above.
2. Log in as an administrator.
3. Attempt to access the dashboard.

### Expected behavior

Administrators should only have access to orders and related users without any errors.

### Actual behavior

The following error is thrown upon accessing the dashboard:  
`Call to a member function getStore() on null in /var/www/html/vendor/craftcms/commerce/src/widgets/AverageOrderTotal.php:50`.

### Craft CMS version

5.4.8

### Craft Commerce version

5.1.3

**Comment by lukeholder** [comment]
Hi @romainpoirier 

To access the orders, you are expected to be able to access at least one sites so that we know what stores you can access.

To fix the error, simply permit at least one site:

![Image](https://github.com/user-attachments/assets/254bba66-07ac-42f0-b302-22ccc260ca33)

This will fix the error. 

We will look to make this experience better and will leave the ticket open.

Thanks.

**Comment by romainpoirier** [comment]
Thank you, it's working. Indeed, an error message would be appreciated to make the requirement clearer.

However, I'm encountering an additional issue. This user group should only have access to orders and customers in Craft Commerce.

To grant access to customers, the group must be given the "Users > Edit users" permission. However, this permission is too broad—it allows lower-level users to modify admin information, which is not acceptable.

How can I restrict this group to view-only access to customer information without giving them full edit rights?

**Comment by lukeholder** [comment]
@romainpoirier when you say "Craft Commerce orders and the users linked to those orders", what do you want to be able to do to those users? On the order screen you can select users without needing to edit them.

**Comment by lukeholder** [comment]
Please make a request to the cms repo for view user permission support. Thanks.

**Comment by romainpoirier** [comment]
> @romainpoirier Regarding "Craft Commerce orders and the users linked to those orders," could you clarify what specific actions you'd like to enable for those users? Note that on the order screen, you can select users without needing to edit them.

For example, when viewing an order at `/admin/commerce/orders/{id}`, under "Client," there is a "View customer" link. If I click this link without having User moderation permissions, I encounter the following error:

```
[HTTP 403 – Forbidden](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#403) – [yii\web\ForbiddenHttpException](https://www.yiiframework.com/doc-2.0/yii-web-forbiddenhttpexception.html)  
User is not authorized to perform this action.
```

Ideally, I’d like to enable a restricted user group to view the details of users who are solely customers. This would allow them to access specific custom fields with personal information and preferences, along with addresses. However, it’s essential that these users can only view this information and are not able to edit it. Additionally, they should not be permitted to access or modify the details of other site administrators (who are not customers).

I believe this request is reasonable and would help improve user access management within Craft Commerce.

**Comment by lukeholder** [comment]
This should now work with Craft 5.6’s "View user" permission.
