### ISSUE TITLE
[5.x]: Completing order with Custom Line item throws an error

### ISSUE THREAD

**Issue by alex-brukhty** [craftcms/commerce#3733]
### Description
When requesting `/actions/commerce/payments/complete-payment?commerceTransactionHash=<hash>` to complete order that has Custom Line items, getting an error: `Cannot get a purchasable for a custom line item`

```
exception: "yii\\base\\InvalidConfigException"
file: "/var/www/html/vendor/craftcms/commerce/src/models/LineItem.php"
line: 821
message: "Cannot get a purchasable for a custom line item"
name: "Invalid Configuration"
```

### Steps to reproduce

1. Create custom line item and add to cart:
```
$lineItem = Commerce::getInstance()->getLineItems()->create($cart, [
    'price' => (float)$this->request->getRequiredBodyParam('amount'),
    'taxCategoryId' => Commerce::getInstance()->getTaxCategories()->defaultTaxCategory->id,
    'isShippable' => true,
    'shippingCategoryId' => Commerce::getInstance()->getShippingCategories()->getShippingCategoryByHandle('general')->id,
], LineItemType::Custom);
$cart->addLineItem($lineItem);
```
2. Make a payment
3. Request `/actions/commerce/payments/complete-payment?commerceTransactionHash=<hash>` to complete oreder

### Expected behavior

Complete order without errors

### Actual behavior

Order is marked as completed but throws an error

### Craft CMS version

5.4.8

### Craft Commerce version

5.2.0

### PHP version

8.3

### Operating system and version

ddev

### Database type and version

mysql 8

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @alex-brukhty 

Thank you for reporting this.

We have pushed a fix which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.2.0",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce `5.2.1` has now been released with this fix included.

Thanks!
