### ISSUE TITLE
[5.x]: Product tab not available in menu when not enabled for current site

### ISSUE THREAD

**Issue by bartdigitalpulse** [craftcms/commerce#3735]
### Description

I have a multisite setup. 2 sitegroups, one for a standard frontend site and another group for the shop. The first site group with the primary site doesn't have products enabled. Only the 3 sites in the shop sitegroup. 

The products tab in the menu isn't visible. If I want to see the products tab I need to go to orders and switch the site to one of the shop sites. A bit cumbersome.

Attached screens.

![Image](https://github.com/user-attachments/assets/998d8403-2b6c-4dcb-bb7e-d546c1eb25d6)
![Image](https://github.com/user-attachments/assets/d9ceaa02-b603-4d4a-8070-f126525ea0cb)

### Steps to reproduce

1. Don't have products enabled for the primary site
2. Current active site in the CP doesn't have products
3. Product tab is not visible in the menu on the left

### Expected behavior

Always show menu when for a least one site products are enabled

### Actual behavior

Menu only visible when current CP site is one with products enabled

### Craft CMS version

Craft Pro 5.4.8

### Craft Commerce version

5.2.0

### PHP version

8.2.22

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@bartdigitalpulse , thanks for reporting. This has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#53d4a16be6580b889a1d9cc06055fe5aab009803 as 5.2.0",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by nfourtythree** [comment]
Hi @bartdigitalpulse 

Commerce `5.2.1` has now been released with this fix included.

Thanks!
