### ISSUE TITLE
[4.x]: Only Primary Site Entries availables on Discount RelatedTo Entry Conditions

### ISSUE THREAD

**Issue by svondervoort** [craftcms/commerce#3739]
### Description
We have a multi-site Craft project with a portion of the sites being a webshop.
We have created some entries that an be related to a user for certain discount groups.
Now in the condition `Match Customer` `Realted To -Entry` it seem you can only pick sections and entries from the **Primary Site**.

We changed to propagation method to create entries on all sites enabled for the section, but it clutters the sections for the sites that don't really need the Entry Section.

### Steps to reproduce

1. Create at least 2 sites, each with a different set of sections.
2. Create a discount with `Match Customer` `Realted To -Entry` and see only the sections of the **Primary Site** are visible

### Expected behavior
Ability to pick from a specific site.

### Actual behavior
Only able to pick entries from the **Primary Site**.

### Craft CMS version

4.12.8

### Craft Commerce version

4.7.0

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Craft 5.5.0 is now out and supports selecting the site in the related to modal. Thanks!

**Comment by svondervoort** [comment]
@lukeholder and what about Craft 4 & Commerce 4? Is it also possible to fix it there? Or is this a Craft 4 restriction?

**Comment by lukeholder** [comment]
@svondervoort Yes I believe so, we recommend you upgrade. Thanks!
