### ISSUE TITLE
`ShippingMethod` requires handle and storeId property to be defined

### ISSUE THREAD

**Issue by soerenmeier** [craftcms/commerce#3747]
I want to implement a custom shipping method.
After implementing a basic Shipping method, it did not get returned from `Order::getAvailableShippingMethodOptions`:
```php
<?php

namespace modules\schwab\shippingmethods;

use craft\commerce\base\ShippingMethod;
use modules\schwab\shippingmethods\DistanceBasedShippingRule;
use Illuminate\Support\Collection;

class DistanceBasedShippingMethod extends ShippingMethod
{
	public function getType(): string
	{
		return "distanceBasedShippingMethodId";
	}

	public function getId(): ?int
	{
		return null;
	}

	public function getName(): string
	{
		return "Distance Based Shipping";
	}

	public function getHandle(): string
	{
		return "distanceBasedShippingMethod";
	}

	public function getCpEditUrl(): string
	{
		return "";
	}

	public function getShippingRules(): Collection
	{
		return collect([new DistanceBasedShippingRule()]);
	}

	public function getIsEnabled(): bool
	{
		return true;
	}
}

```

After investigating the code i found out that the property `handle` was required in this code snipped:

https://github.com/craftcms/commerce/blob/272475a8b385896e21282e691ec764387b03b191/src/elements/Order.php#L2126

After adding that, i got the following error: 
```
{"name":"Invalid Configuration","message":"Store ID is required"
```

I think this comes from `ShippingMethodOrderCondition`.

After setting the storeId property. The method is now returned from `getAvailableShippingMethodOptions`.

I think this might need to be documented better, because in the docs it's only stated that the interface needs to be implemented:
https://craftcms.com/docs/commerce/5.x/extend/shipping-methods.html

**Comment by lukeholder** [comment]
@soerenmeier unless you are trying to replace existing shipping methods in the app container, you shouldn
t be extending the base ShippingMethod. Make a plain class that implements the [shipping method interface](https://docs.craftcms.com/commerce/api/v4/craft-commerce-base-shippingmethodinterface.html):

```php

class DistanceBasedShippingMethod implements \craft\commerce\base\ShippingMethodInterface

```

Let me know if you have any problems.
