### ISSUE TITLE
Saving Order element through Jobs Queue Fails

### ISSUE THREAD

**Issue by pdaleramirez** [craftcms/commerce#375]
https://github.com/craftcms/commerce/blob/ce6ba2bed13e3b15ab6c366b021311eea4f810bf/src/services/OrderHistories.php#L101

This specific code `Plugin::getInstance()->getCustomers()->getCustomerId()` makes saving of order element through Jobs fail.

Currently creating an importing plugin that imports Commerce Orders and runs through jobs queue. Fixing the issue would allow us to add Commerce Orders import feature

**Comment by lukeholder** [comment]
Are you running this job from the command line? Are you setting a real customerId on the order?

**Comment by BenParizek** [comment]
@lukeholder (cc: @pdaleramirez) This issue still exists for us and Sprout Import. Can we can re-open and discuss and confirm if this is an issue with Craft Commerce or just a mistake on our end?
