### ISSUE TITLE
[5.x]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'commerce_purchasables.id'

### ISSUE THREAD

**Issue by klick** [craftcms/commerce#3763]
### Description

Out of the blue I am not able to create or edit product variants from the variant flyout. Inline editing of variants works though.
Noted I have imported existing products with feed me without problems.

No migrations, this is a fresh install of Craft/Commerce.

### Steps to reproduce

1. Click on new variant or double click on existing variant to add/edit variant.
2. Edit Data
3. Click „Save Variant“
4. Error appears in error flyout bottom left.

### Expected behavior
Add or edit variant.

### Actual behavior
Errors out, no variant gets added/edited.

Full Error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'commerce_purchasables.id' in 'on clause' The SQL being executed was: SELECT EXISTS(SELECT `craft_commerce_purchasables`.* FROM `craft_commerce_purchasables` INNER JOIN `craft_elements` `element` ON `craft_commerce_purchasables`.`id` = `element`.`id` LEFT JOIN `craft_elements` `elements` ON `elements`.`id` = `commerce_purchasables`.`id` WHERE (`element`.`dateDeleted` IS NULL) AND (`craft_commerce_purchasables`.`sku`='tk-2017-04') AND ((`elements`.`revisionId` IS NULL) AND (`elements`.`draftId` IS NULL)) AND (NOT (`craft_commerce_purchasables`.`id`=51)))

### Craft CMS version

5.4.10.1

### Craft Commerce version

5.2.2.1

### PHP version

8.2

### Operating system and version

MacOS 13.6.7

### Database type and version

MYSQL 8.0

### Installed plugins and versions

-

**Comment by klick** [comment]
Added Info:

- Removing and reinstalling Commerce does not resolve this issue.
- Deactivating and then saving a variant saves the variant without error.
- The purchasable with that id does exist in the db, even new ones get created in that table.

**Comment by klick** [comment]
Removing the db prefix `craft_` from my .env and from the tables in the db seem to resolve this issue. I can now edit and create variants. Static query alias somewhere in the commerce source?

**Comment by lukeholder** [comment]
Thanks for reporting. This has been fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#c31d5a30833e3a078e183e393378d0dd790e6bbf as 5.2.3",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by nfourtythree** [comment]
Hi @klick 

Commerce `5.2.4` has been released with this fix included.

Thanks!

**Comment by klick** [comment]
Thanks. You rock.
