### ISSUE TITLE
[5.x]: wrong decimal position for product variant between read and edit panel page

### ISSUE THREAD

**Issue by masiorama** [craftcms/commerce#3768]
### Description
It seems that variant pricing has an issue on read and on edit (wrong decimal separator position

Reading the product variants:

### Craft CMS version

5.4.6

### Craft Commerce version

5.0.17

### PHP version

8.1

### Installed plugins and versions

![Image](https://github.com/user-attachments/assets/b4822945-91f5-49fd-ab38-84cd9a1a1caa)
![Image](https://github.com/user-attachments/assets/7334bdcc-01c3-4562-87d7-4c32b91d0e5a)
-

**Comment by nfourtythree** [comment]
Hi @masiorama 

Unfortunately, I am unable to replicate this issue on the latest version of Craft and Commerce.

Could you please try updating and then letting us know if the issues persists.

Thanks!

**Comment by masiorama** [comment]
hi @nfourtythree sure, I planned to do it tomorrow (UTC+1). I'll keep you posted.
edit: gonna check next thursday.

**Comment by masiorama** [comment]
Hi @nfourtythree I just upgraded craft and commerce to the last available versions and the issue is still there.

I have installed the following plugins (all updated):  Brevo, CKEditor. Incognito Field, Navigation, PDF Generator and Wheel Form.

I have to say that I see the error only in production, not on dev env. I' gonna try to dump the db on dev env and investigate. Keep you posted.

**Comment by masiorama** [comment]
@nfourtythree I imported on dev env and I have the same exact issue.
It's ok on variants list view and on panel edit view, but on fast-edit on list view there is some issue.
OK
![Image](https://github.com/user-attachments/assets/e2436482-e2b5-4c93-b095-9f129175ffd2) 
OK
![Image](https://github.com/user-attachments/assets/171234f3-3378-45d0-865d-330d8317d452)
WRONG
![Image](https://github.com/user-attachments/assets/65c423cd-450e-494b-8050-de090759eeed)

**Comment by nfourtythree** [comment]
Hi @masiorama 

Thank you for the update. As I can't seem to replicate this with various combinations are you able to send your composer files and DB backup to support@craftcms.com referencing this ticket?

We can then investigate the issue further.

Thanks

**Comment by masiorama** [comment]
@nfourtythree done. Thanks!

**Comment by nfourtythree** [comment]
Hi @masiorama 

Thank you for sending the files over to support it was really helpful to get to the bottom of the issue.

We have pushed a fix for the issue which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.2.5",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce `5.2.6` has now been released with this fix included.

Thanks!
