### ISSUE TITLE
[5.x]: "Max Levels" are not taken into account for structured product types

### ISSUE THREAD

**Issue by HigumaSan4050** [craftcms/commerce#3785]
### Description
Enabled lightswitch for "Enable structure for products of this type" and "Max Levels" set to 1 has no effect on the product lists.You can still move products under other products

### Steps to reproduce

1. create a "Product Type" with "Enable structure for products of this type" enabled and "Max Levels" set to 1
2. Create 2 Products in this Product Type
3. You can move one of the products unter the other product

### Craft CMS version

5.5.3

### Craft Commerce version

5.2.5

### PHP version

8.3

**Comment by nfourtythree** [comment]
Hi @HigumaSan4050 

Thank you for reporting this, we were able to reproduce the issue and are working on a fix.

Thanks

**Comment by nfourtythree** [comment]
Hi @HigumaSan4050 

We have pushed a fix for this issue which will be included in the next release of Commerce

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.2.6",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
