### ISSUE TITLE
[5.x]: Manual transaction converts number incorrect when the account is set to Dutch

### ISSUE THREAD

**Issue by MatthiasBrodelet** [craftcms/commerce#3789]
### Description
When manually adding a transaction to the order the amount to pay in the input field gets converted wrong.
489,75 euro becomes 48.975,00.
The amount next to the input field is correct.

### Steps to reproduce

1. Set account language to dutch
2. Add new transaction in the CP

### Expected behavior
The number should be formatted correctly.

### Actual behavior
489,75 euro becomes 48.975,00.

![Image](https://github.com/user-attachments/assets/b7bea1b5-a04f-4fe7-9e8e-bc55ac22293e)

### Craft CMS version

5.5.3

### Craft Commerce version

5.x

### PHP version

8.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for reporting. We have fixed this for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#4c12360d9cf84f6c5a29ff5935287a7ddfdc292d as 5.2.7",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by brandonkelly** [comment]
Craft Commerce 5.2.8 is out with that fix. Thanks again!
