### ISSUE TITLE
Deleting a Customer's primary Shipping/Billing address deletes the customer as well

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#379]
### Description

This seems to be an issue in the DB schema, with a `CASCADE` being set up [on one or more of the `primaryShippingAddressId` or `primaryBillingAddressId` columns](https://github.com/craftcms/commerce/blob/develop/src/migrations/Install.php#L929-L932)?

Happy to provide a backup of a site that makes it relatively easy to test this.

For the time being, we (@builtbybrad, the initial reporter in Slack, and I) can just disable the ability for customers to remove primary addresses, in the front-end, so nothing scary happens to customers. Still potentially dangerous for an admin to do so, as there's no indication about which is the primary/default, from the admin.

### Steps to reproduce

1. Register a new user/customer, and add an address to them;
2. Ensure address is selected as their primary billing or shipping address (should be this way, as their only address);
3. Let customer delete the address from the front-end;
4. Customer record is destroyed. 😢 

### Additional info

- Craft version: Pro, 3.0.12
- Commerce Version: 2.0.0-beta.5
- PHP version: 7.1.16
- Database driver & version: Postgres, 10.3
- Plugins & versions:
  - Cookies: 1.1.9
  - Craft Commerce 2.0.0-beta.5
  - Redactor: 2.1.0
  - Stripe for Craft Commerce: 1.0.3
  - Typogrify: 1.1.10
  - Utils: 0.1 (Custom)
  - Fonts: 0.1 (Custom)

**Comment by lukeholder** [comment]
Fixed for the next release. Thanks.

**Comment by krizajb** [comment]
In which release was this resolved? Change log doesn't mention anything about it.

**Comment by lukeholder** [comment]
beta 6

https://github.com/craftcms/commerce/commit/389f051a9c7fd9f1f88ca5ab1b8bf1f68de81d2a#diff-c3799a2995116ea9f4ee0c45c9cbf288R12

**Comment by lukeholder** [comment]
beta6:

https://github.com/craftcms/commerce/commit/389f051a9c7fd9f1f88ca5ab1b8bf1f68de81d2a#diff-c3799a2995116ea9f4ee0c45c9cbf288R12
