### ISSUE TITLE
[5.x]: Product name of a line item isn't clickable in CP

### ISSUE THREAD

**Issue by maxpdesign** [craftcms/commerce#3792]
### Description
I have upgraded a commerce website from v4 to v5 and we are no longer able to click on the product name of a line item on the order page in the control panel. We were able to do this in v4. I am also experiencing the same issue on a new website I am building with Commerce 5.

### Steps to reproduce

1. Open an order in the control panel
2. Try to click on product name of a line item
3. Nothing happens (because this not a link anymore)

### Expected behavior
When I click the name of a line item, the control panel page of that product should open.

### Actual behavior
Nothing happens when I click the name of a line item because this is not a link anymore.

### Craft CMS version

5.5.3

### Craft Commerce version

5.2.6

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft Commerce 5.2.8 is out with a fix.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft Commerce 5.2.8 is out with a fix.
