### ISSUE TITLE
[4.x]: Billing address failing validation before it is even selected

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/commerce#3796]
### Description

Certain users with faulty addresses on their accounts cannot even add anything to their cart because an address isn't passing validation. Fixing the address on their account doesn't fix the issue due to the invalid address still being associated with their cart though it was never deliberately selected.

### More Detailed Description

I found [this old issue](https://github.com/craftcms/commerce/issues/2914) and the client that we just recently upgraded to Craft 4 and Commerce 4 (now on v4.7.0) is being bit hard by this one and it took me forever just to figure out that this is why numerous accounts can't add items to their carts.

For whatever reason, many addresses didn't migrate correctly and the State value was lost during the commerce/upgrade console command execution. We've taken various steps to correct as many as we can and we will continue to do so but they have thousands of users/customers.

We added a note to the site to suggest that users review and fix their addresses but that notice is _during_ the checkout process when the user is prompted to select a billing address and they can't even get that far because they can't add anything to their cart. Is Commerce selecting the user's first account address by default? Otherwise, we don't know why/how there is already an address associated with the user's cart and even if the address gets corrected on their _account_, they still can't add anything to the cart because the address on the _cart_ doesn't pass validation.

I had to add some code into the Commerce code just to figure out what was going on because all I could ever get back was "Unable to update cart". I added the following line to log validation errors to a custom module log because the "failMessage" was apparently not getting populated:

```
 // Do not clear errors, as errors could be added to the cart before _returnCart is called.
 if (!$this->_cart->validate($attributes, false) || !Craft::$app->getElements()->saveElement($this->_cart, false, false, $updateCartSearchIndexes)) {
    $error = Craft::t('commerce', 'Unable to update cart.');
    $message = $this->request->getValidatedBodyParam('failMessage') ?? $error;
    // This is the line I added
    \modules\client\ClientModule::getInstance()->orders->log(print_r($this->_cart->getErrorSummary(true),true));
```

The logged array shows "State cannot be blank".

I am not sure how to proceed with this.

### Expected behavior

Users should be able to add items to their cart then select (and/or edit) a billing address during the checkout flow. By all appearances, it works just like this as long as the user already has a good address.

### Actual behavior

Users can't add any items to the cart or proceed with the checkout process due to old address information not passing validation when adding an item to the cart.

### Craft CMS version

4.12.9

### Craft Commerce version

4.7.0

### PHP version

8.0.30

### Operating system and version

Linux 5.4.0-193-generic

### Database type and version

MariaDB 10.4.34

### Image driver and version

GD 8.0.30

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
> Fixing the address on their account doesn't fix the issue due to the invalid address still being associated with their cart though it was never deliberately selected.

Is this because you have `autoSetNewCartAddresses` set to true? Could you not have the autoset, and allow them to select valid addresses or addresses that they can update/fix before adding it to the order. 

Alternatively could you follow this guide https://craftcms.com/knowledge-base/removing-commerce-address-validation to remove validation for addresses during checkout and do your own validation of the address and allow them to update the invalid address?

**Comment by benjaminkohl** [comment]
Thank you. I did end up setting `autoSetNewCartAddresses` to false yesterday and I also shortened the lifespan of inactive carts so the garbage collection will clean them up more frequently.

After some mass-updating queries, they are down to about 300 addresses that they will correct manually and things should just sort themselves out.
