### ISSUE TITLE
Variants of disabled products showing in craft.variants query

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#380]
### Description

On a search page, we are trying to retrieve variants that match by sku. Variants of disabled products are still appearing:

```
{% set products = craft.variants({
	search: 'sku:' ~ searchParam,
	orderBy: 'score',
}).all() %}
```

I even tried explicitly setting the `status` param:

```
{% set products = craft.variants({
	search: 'sku:' ~ searchParam,
	orderBy: 'score',
	status: 'enabled',
}).all() %}
```

But the disabled product/variant still appeared.

### Steps to reproduce

1. Disable a product
2. Retrieve all variants and the variant of the disabled product should still appear

### Additional info

- Craft version: Craft Pro 3.0.11
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

<table class="data fullwidth fixed-layout">
        <tbody>
                            <tr>
                    <th class="light">Algolia</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Amazon S3</th>
                    <td>1.0.8</td>
                </tr>
                            <tr>
                    <th class="light">Asset Rev</th>
                    <td>6.0.0</td>
                </tr>
                            <tr>
                    <th class="light">AsyncQueue</th>
                    <td>1.3.2</td>
                </tr>
                            <tr>
                    <th class="light">Audit</th>
                    <td>2.0.1</td>
                </tr>
                            <tr>
                    <th class="light">Automatic Site Switch</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Calendar</th>
                    <td>2.0.3</td>
                </tr>
                            <tr>
                    <th class="light">Category Utilities</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Certificates</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Converge</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Craft Commerce</th>
                    <td>dev-master</td>
                </tr>
                            <tr>
                    <th class="light">Environment Label</th>
                    <td>3.1.4</td>
                </tr>
                            <tr>
                    <th class="light">Feed Me</th>
                    <td>3.0.0-beta.15</td>
                </tr>
                            <tr>
                    <th class="light">Field Manager</th>
                    <td>2.0.2</td>
                </tr>
                            <tr>
                    <th class="light">Flat Categories</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Forms</th>
                    <td>2.0.4</td>
                </tr>
                            <tr>
                    <th class="light">Freeform Pro</th>
                    <td>2.0.4</td>
                </tr>
                            <tr>
                    <th class="light">Geo Cookie</th>
                    <td>1.1.2</td>
                </tr>
                            <tr>
                    <th class="light">Hamilton Utility</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Importer</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inlin</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inventory</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">OrderExporter</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Redactor</th>
                    <td>2.1.0</td>
                </tr>
                            <tr>
                    <th class="light">Sidebar Toggle</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">SimpleSentry</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Super Table</th>
                    <td>2.0.7</td>
                </tr>
                            <tr>
                    <th class="light">Taxes</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Twig Perversion</th>
                    <td>2.0.3</td>
                </tr>
                    </tbody>
    </table>

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
