### ISSUE TITLE
[5.x]: `Cannot parse "3.6379788070917E-12" to Money` error

### ISSUE THREAD

**Issue by tommysvr** [craftcms/commerce#3802]
### Description
[From support]

Getting a `Cannot parse "3.6379788070917E-12" to Money` error when loading a particular order. It looks to be coming from here:

https://github.com/craftcms/commerce/blob/bf0c75fe823d556bc08e58bd9e174c5bcc17b374/src/elements/Order.php#L2671-L2685

`$this->getItemSubtotal()` and `$this->getAdjustmentsTotal()` return a rounded amount but the `$total = $this->getItemSubtotal() + $this->getAdjustmentsTotal()` calculation returns a wild float like '3.6379788070917E-12'.

### Craft CMS version

5.5.5

### Craft Commerce version

5.2.8

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
This is fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#af17df6b7b61ab18646ca9d01ec95e122f3d8267 as 5.2.8",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by nfourtythree** [comment]
Commerce `5.2.9` has been released with this fix included.

Thanks!
