### ISSUE TITLE
[5.x]: 'Inline-Editable' Matrix Field cannot save from Product Variant.

### ISSUE THREAD

**Issue by bryantwells** [craftcms/commerce#3805]
Color matrix fields assigned to a product variant's field layout and edited inline are lost. Only the default values are maintained after a variant is saved. 

### Steps to reproduce
1. Create color type field `color`
2. Create entry type `color` (containing only the `color` field)
3. Create matrix type field `colors` with inline-editable blocks view mode
4. Add `colors` field to product variant field layout
5. Make inline edit to the `colors` field on a variant 
6. Save

### Expected behavior
After save, the matrix block should be maintained along with it's `color` field value.

### Actual behavior
After save, the matrix block is maintained, but it's value is reset to the field default (in my case #000000). The field's value is only maintained if the `colors` matrix 'entry' is opened in a new tab and saved via the 'create entry' button. This bug/behavior is not present in base Craft CMS install (tested with a nested matrix type field `colorsNest`).

### Craft CMS version

5.5.5

### Craft Commerce version

5.2.8

### PHP version

8.2.15

### Operating system and version

Linux 6.11.9-orbstack-00279-g4cf512143f2e

### Database type and version

MariaDB 10.4.32

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

```
"craftcms/ckeditor": "4.4.0",
"craftcms/commerce": "^5.0.0",
"craftcms/commerce-stripe": "5.0.4.3",
"vaersaagod/dospaces": "3.0.0",
"verbb/postie": "5.0.7"
```

**Comment by nfourtythree** [comment]
Hi @bryantwells 

Thank you for bringing this to our attention.

We have pushed a fix which will be included in the next release of Commerce

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.2.8",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce `5.2.9` has been released with this fix included.

Thanks!

**Comment by bryantwells** [comment]
thanks @nfourtythree !
