### ISSUE TITLE
[5.x]: Can't save product variants after upgrade from C4

### ISSUE THREAD

**Issue by ZapaNOR** [craftcms/commerce#3806]
### Description
After upgrading to C5 and letting all the resaving products queue finish, I stil cant update the price for any product variant, getting the error `Setting read-only property: craft\\commerce\\elements\\Variant::stock`
The variant has been added to the default inventory during the upgrade, and Im not trying to change the stock at all.
All products has inventory disabled atm, even if I enable it, I cant save the variant.

### Steps to reproduce

1. Open up any product
2. Click variant
3. Change price
4. Press save

### Expected behavior

Product is saved

### Actual behavior
![Image](https://github.com/user-attachments/assets/c9883579-c737-4595-92a6-6187dc14552a)

### Craft CMS version

5.5.5

### Craft Commerce version

5.2.8

### PHP version

8.2

### Operating system and version

MacOS

### Database type and version

Mariadb

**Comment by nfourtythree** [comment]
Hi @Mathias-Syversen 

Do you have any other plugins installed or custom modules that might be interacting with variants?

Are you able to retrieve the full stack trace of the error from the logs?

Thanks!

**Comment by ZapaNOR** [comment]
I have a module that adds an image to the product snapchot (for use in ajax cart):
``   private function attachEventHandlers(): void
    {
        Event::on(Variant::class, Variant::EVENT_AFTER_CAPTURE_PRODUCT_SNAPSHOT, function ($e) {
            $product = $e->product;
            $data = $e->fieldData;
            $image = $product->product_images->one();
            $data['image'] = $image ? $image->getUrl('cart') : '';
            $e->fieldData = $data;
        });
    }``

And I have the following plugins:
craftcms/ckeditor: 4.4.0,
craftcms/commerce: 5.2.8,
craftcms/feed-me: 6.6.1,
ether/simplemap: 5.0.4,
nystudio107/craft-retour: 5.0.3,
nystudio107/craft-seomatic: 5.1.7,
putyourlightson/craft-blitz: 5.9.6,
spacecatninja/imager-x: 5.1.0,
spicyweb/craft-embedded-assets: 5.4.0,
spicyweb/craft-neo: 5.2.19,
verbb/expanded-singles: 3.0.1,
verbb/formie: 3.0.14,
verbb/image-resizer: 4.0.1,
verbb/navigation: 3.0.5,
verbb/super-table: 4.0.2,
wrav/oembed: 3.1.1

I found this in the logs:
```2024-12-09 12:27:22 [web.ERROR] [yii\base\InvalidCallException] yii\base\InvalidCallException: Setting read-only property: craft\commerce\elements\Variant::stock in /Users/mathias/Sites/ferno-5/vendor/yiisoft/yii2/base/Component.php:214
Stack trace:
#0 /Users/mathias/Sites/ferno-5/vendor/craftcms/cms/src/base/Element.php(2518): yii\base\Component->__set('stock', 0)
#1 /Users/mathias/Sites/ferno-5/modules/ferno/Module.php(40): craft\base\Element->__set('stock', 0)
#2 [internal function]: modules\ferno\Module->modules\ferno\{closure}(Object(craft\events\ModelEvent))
#3 /Users/mathias/Sites/ferno-5/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ModelEvent))
#4 /Users/mathias/Sites/ferno-5/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger('craft\\commerce\\...', 'beforeSave', Object(craft\events\ModelEvent))
#5 /Users/mathias/Sites/ferno-5/vendor/craftcms/cms/src/base/Element.php(6008): yii\base\Component->trigger('beforeSave', Object(craft\events\ModelEvent))
#6 /Users/mathias/Sites/ferno-5/vendor/craftcms/commerce/src/elements/Variant.php(1164): craft\base\Element->beforeSave(false)
#7 /Users/mathias/Sites/ferno-5/vendor/craftcms/cms/src/services/Elements.php(3503): craft\commerce\elements\Variant->beforeSave(false)
#8 /Users/mathias/Sites/ferno-5/vendor/craftcms/cms/src/services/Elements.php(1303): craft\services\Elements->_saveElementInternal(Object(craft\commerce\elements\Variant), true, true, NULL, NULL, false, false, false)
#9 /Users/mathias/Sites/ferno-5/vendor/craftcms/cms/src/controllers/ElementsController.php(1260): craft\services\Elements->saveElement(Object(craft\commerce\elements\Variant), true, true, NULL, false, false)
#10 [internal function]: craft\controllers\ElementsController->actionSave()
#11 /Users/mathias/Sites/ferno-5/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/mathias/Sites/ferno-5/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /Users/mathias/Sites/ferno-5/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save', Array)
#14 /Users/mathias/Sites/ferno-5/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('elements/save', Array)
#15 /Users/mathias/Sites/ferno-5/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction('elements/save', Array)
#16 /Users/mathias/Sites/ferno-5/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /Users/mathias/Sites/ferno-5/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/mathias/Sites/ferno-5/web/index.php(13): yii\base\Application->run()
#19 {main} {"memory":5253608,"exception":"[object] (yii\\base\\InvalidCallException(code: 0): Setting read-only property: craft\\commerce\\elements\\Variant::stock at /Users/mathias/Sites/ferno-5/vendor/yiisoft/yii2/base/Component.php:214)"} ```

**Comment by nfourtythree** [comment]
Thank you for the info @Mathias-Syversen .

Looking at the stack trace it appears the issue is coming from the file `modules/ferno/Module.php` on line `40`.

**Comment by ZapaNOR** [comment]
Thats the first line (declaration) of this function:

```
(40) private function attachEventHandlers(): void
    {
        Event::on(Variant::class, Variant::EVENT_AFTER_CAPTURE_PRODUCT_SNAPSHOT, function ($e) {
            $product = $e->product;
            $data = $e->fieldData;
            $image = $product->product_images->one();
            $data['image'] = $image ? $image->getUrl('cart') : '';
            $e->fieldData = $data;
        });
    }
```

I guess $e->fieldData contains stock: 0 (from commerce 4?) and that throws the error when I try to set it at the last line?

I tried setting it to this instead to avoid passing the entire fieldData back, but it throws the same error and stack:

```
    private function attachEventHandlers(): void
    {
        Event::on(Variant::class, Variant::EVENT_AFTER_CAPTURE_PRODUCT_SNAPSHOT, function ($e) {
            $product = $e->product;
            $image = $product->product_images->one();
            $e->fieldData['image'] = $image ? $image->getUrl('cart') : '';
        });
    }
```

Also: this should in theory not affect a variant save at all? Since its hooked into EVENT_AFTER_CAPTURE_PRODUCT_SNAPSHOT

**Comment by ZapaNOR** [comment]
Update: tried removing everything inside attachEventHandlers() and leaving it blank, but the error remains..

The module looks like this, generated with generator:
```

<?php

namespace modules\commerce;

use Craft;
use yii\base\Event;
use yii\base\Module as BaseModule;
use craft\commerce\elements\Order;
use craft\commerce\elements\Variant;
use craft\commerce\events\LineItemEvent;
use craft\commerce\services\LineItems;
use craft\events\ModelEvent;

/**
 * commerce module
 *
 * @method static Module getInstance()
 */
class Module extends BaseModule
{
    public function init(): void
    {
        Craft::setAlias('@modules/commerce', __DIR__);

        if (Craft::$app->request->isConsoleRequest) {
            $this->controllerNamespace = 'modules\\commerce\\console\\controllers';
        } else {
            $this->controllerNamespace = 'modules\\commerce\\controllers';
        }

        parent::init();

        $this->attachEventHandlers();

        Craft::$app->onInit(function() {
            
        });
    }

    private function attachEventHandlers(): void
    {

    }
}

```

Maybe its the name, commerce, that interfers with something..

**Comment by ZapaNOR** [comment]
Edit: Its a completely other module from our C3 -> 4 era where we imported a bunch of products but feed-me didnt import null values, so it set it to 0 in an event. 

Completely my own doing, regard this issue as solved.

**Comment by lukeholder** [comment]
Glad you're sorted!
