### ISSUE TITLE
[5.x]: Product overview shows price in current store's currency, but with primary store's value.

### ISSUE THREAD

**Issue by ZapaNOR** [craftcms/commerce#3807]
### Description
I've set up a test-site for Commerce 5 to test some multi-store and multi currency functionality.
While testing I noticed that the product price is shown in the currents store's currency, but the price value comes from the primary store.

### Steps to reproduce

1. Make two stores
2. Add a new product
3. Set one value in store 1, and a completely different value in store 2

Here is the site / store setup:
![Image](https://github.com/user-attachments/assets/a3e905b9-64ec-4b87-939d-2f0b9b1de0fe)

Her you can see the price is set to USD 5 and NOK 50:
![Image](https://github.com/user-attachments/assets/b303aa3b-52a3-4fef-9c07-09395a3c0bf7)
![Image](https://github.com/user-attachments/assets/a878a78d-6162-44c3-a4dd-5fcea3f01dc0)

You can see here that the price is 5 for both sites, even tho the norwegian price should be NOK 50:
![Image](https://github.com/user-attachments/assets/87424364-8c93-4a00-a088-fb5467d49eb4)
![Image](https://github.com/user-attachments/assets/63de932f-0c43-45ce-9599-944505c65bc5)

### Expected behavior
Price and currency follows current store (inherited from the current site we have chosen in the control panel).

### Actual behavior
Price comes from primary store, not current store.

I have also noted that the price / currency does not seem to follow the current site when using the ajax cart front-end aswell, this might be a spereate issue, but worth mentioning. I would expect cart.currency to be whatever the current store has, not what the primary store has.

### Craft CMS version

5.5.5

### Craft Commerce version

5.2.8

### PHP version

8.2

### Operating system and version

Macos

### Database type and version

Mariadb

### Installed plugins and versions

craftcms/ckeditor: 4.4.0,
craftcms/commerce: 5.2.8,
craftcms/feed-me: 6.6.1,
ether/simplemap: 5.0.4,
nystudio107/craft-retour: 5.0.3,
nystudio107/craft-seomatic: 5.1.7,
putyourlightson/craft-blitz: 5.9.6,
spacecatninja/imager-x: 5.1.0,
spicyweb/craft-embedded-assets: 5.4.0,
spicyweb/craft-neo: 5.2.19,
verbb/expanded-singles: 3.0.1,
verbb/formie: 3.0.14,
verbb/image-resizer: 4.0.1,
verbb/navigation: 3.0.5,
verbb/super-table: 4.0.2,
wrav/oembed: 3.1.1

**Comment by nfourtythree** [comment]
Hi @Mathias-Syversen 

Thank you for reporting this issue.

We have pushed up a fix which will be included in the next release of Commerce

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.2.8",
  "...": "..."
}
```

Then run `composer update`.

Thanks

**Comment by nfourtythree** [comment]
Commerce `5.2.9` has been released with this fix included.

Thanks!

**Comment by ZapaNOR** [comment]
Hey,

I found a very similar bug, so decided to try updating here instead of creating a completely new issue.
The currency is also stuck to primary on the order view, for line items. The price is correct, but its showing EUR when NOK should be the correct currency.

Total is correct:

![Image](https://github.com/user-attachments/assets/413721fc-b60f-443e-aa34-3f4f1bd9d476)

**Comment by lukeholder** [comment]
@Mathias-Syversen could you please raise a new issue so we can track this. Please also go into more detail on the stores/sites/languages you have set up.

Thanks.
