### ISSUE TITLE
[5.x]: Unable to edit product variants due to faulty chip element template

### ISSUE THREAD

**Issue by mgambella** [craftcms/commerce#3813]
### Description
After upgrading Craft Commerce to version 5.2.8, the product variant edit feature didn't work anymore when you clicked on the variant name.

### Steps to reproduce

1. Have some products with variations loaded in the database
2. upgrade from Craft Commerce 5.2.7 to 5.2.8
3. try to edit a product variation by clicking on the variant name

### Expected behavior
The expected behavior is that when I click on the variant name in the chip element then a modal with open in the right 

### Actual behavior
Then you click on the variant name it mistakenly redirects you to the product page itself.

### Craft CMS version

5.5.6.1

### Craft Commerce version

5.2.8

### PHP version

8.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @mgambella 

Thank you for reporting this.

We have pushed a fix for the issue which will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.2.9.1",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce 5.2.10 has been released with this fix included.

Thanks!

**Comment by mgambella** [comment]
hello @nfourtythree,  thank you for the fix! it works correctly
