### ISSUE TITLE
[5.x]: Eager loading "owner" fields on Variants doesn't work

### ISSUE THREAD

**Issue by webrgp** [craftcms/commerce#3817]
### Description

When trying to eager load the `owner` field on a Variant:

```php
$variants = Variant::find()
    ->with([
        'owner.images',
    ])
    ->all();
```

Results in the following error:

```text
craft\commerce\elements\Variant::setOwner(): Argument #1 ($owner) must be of type ?craft\base\ElementInterface, bool given, called in /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php on line 288
```

Replacing `owner` with `product` works as expected:

```php
$variants = Variant::find()
    ->with([
        'product.images',
    ])
    ->all();
```

### Craft CMS version

5.3.6

### Craft Commerce version

5.2.1

### PHP version

8.2.26

### Operating system and version

Linux 6.10.14-linuxkit

### Database type and version

MySQL 8.0.32

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by lukeholder** [comment]
Thanks for reporting. We have fixed this for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.2.9.1",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by nfourtythree** [comment]
Commerce 5.2.10 has been released with this fix included.

Thanks!
