### ISSUE TITLE
[4.x]: Duplicate action for edit product does check permission via the Elements service to determine whether the Save as new product button is shown in the cp

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#3819]
### Description

Running into this issue (https://github.com/craftcms/commerce/issues/3285) with the Duplication logic, needs hooking up i think:

![Image](https://github.com/user-attachments/assets/faad6d21-7226-48b4-a2ba-b7b7c2d0c3fb)

### Steps to reproduce

1. Set `$e->authorized = false` via the `Elements::EVENT_AUTHORIZE_DUPLICATE`

### Expected behavior

Should hide: Save as new product

### Craft CMS version

4.12.5

### Craft Commerce version

4.6.13

### Installed plugins and versions

-

**Comment by samhibberd** [comment]
More importantly it doesn't currently prevent duplication / throw an exception in the case that the duplicate action is called and the action is not authorized. Need to ensure it calls the Elements service to hook into the service level authorization events.

**Comment by nfourtythree** [comment]
Thanks for reporting @samhibberd!

We have pushed a fix for this which will be included in the next release of Commerce 4.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "4.x-dev as 4.7.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by samhibberd** [comment]
Hey @nfourtythree thanks for fixing, one thing, did you also fix the issue with the 'Save as new product' action item showing even if the without permission to duplicate? (On my phone so sorry if I missed it, but I couldn't see any changes in the commit related to it).

**Comment by nfourtythree** [comment]
Hi @samhibberd 

Here is that change in the merge commit: https://github.com/craftcms/commerce/commit/35e765d533af7ae0a973970489de9ffb470dce28#diff-13c25db9415da0850f3aab0e6b303c2e5ff8f2531544be953ee5f92edcc52742R26-R32

Thanks!

**Comment by samhibberd** [comment]
Been a long Christmas :)

**Comment by nfourtythree** [comment]
Commerce 4.7.3 has been released with this fix included.

Thanks!
