### ISSUE TITLE
Product Type > Site Settings should have Default Status

### ISSUE THREAD

**Issue by chanwhab** [craftcms/commerce#382]
### Description
On each product, similar to section/entry, it can be set enable/disable per site.
<img width="313" alt="screen shot 2018-06-21 at 00 02 38" src="https://user-images.githubusercontent.com/7658690/41670302-745fcf58-74e6-11e8-8074-f6a8279f281b.png">

Then similarly, the product type's site settings can also have default status toggle. That would make the whole user experience on configuring site view more consistent.

<img width="986" alt="screen shot 2018-06-20 at 23 56 09" src="https://user-images.githubusercontent.com/7658690/41669965-a311807c-74e5-11e8-93b2-a29061a1fbf1.png">

<img width="1400" alt="screen shot 2018-06-20 at 23 58 59" src="https://user-images.githubusercontent.com/7658690/41670087-eb7668d2-74e5-11e8-967c-d2c4c139839f.png">

**Comment by lukeholder** [comment]
Moved under #37 as this will only be possible once we move to multi-store/multi-site
