### ISSUE TITLE
Error updating cart with duplicate product + options

### ISSUE THREAD

**Issue by cwmanning** [craftcms/commerce#384]
### Description

Unable to add more than one of the same item with duplicate options to the cart.

### Steps to reproduce

1. Add a product to the cart with line item options specified. This redirects to the cart view with a new line item present.
2. Go back and add the same product from step 1 to the cart with the exact same line item options.
3. **Expected Result**: Updates the quantity of the item already in the cart. Redirects to the cart view. **Actual Result**: Fails to update the cart. Does not redirect to the cart view. 

Error output, via `{{ dump(cart.getErrors()) }}` on the product template: 

```
array(1) {
  ["lineItems.1.optionsSignature"]=>
  array(1) {
    [0]=>
    string(10) "Not Unique"
  }
}
```

### Additional info

via `POST commerce/cart/update-cart`

Possibly relevant docs link: https://github.com/craftcms/commerce-docs/blob/d4ed6d738279c0c6864ba49cde4cef0fb4535920/en/adding-to-and-updating-the-cart.md#options-uniqueness

- Craft version: Craft Pro 3.0.11
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

<table>
        <tbody>
                            <tr>
                    <th>Algolia</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Amazon S3</th>
                    <td>1.0.8</td>
                </tr>
                            <tr>
                    <th>Asset Rev</th>
                    <td>6.0.0</td>
                </tr>
                            <tr>
                    <th>AsyncQueue</th>
                    <td>1.3.2</td>
                </tr>
                            <tr>
                    <th>Audit</th>
                    <td>2.0.1</td>
                </tr>
                            <tr>
                    <th>Automatic Site Switch</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Calendar</th>
                    <td>2.0.3</td>
                </tr>
                            <tr>
                    <th>Category Utilities</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Certificates</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Converge</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Craft Commerce</th>
                    <td>dev-master</td>
                </tr>
                            <tr>
                    <th>Environment Label</th>
                    <td>3.1.4</td>
                </tr>
                            <tr>
                    <th>Feed Me</th>
                    <td>3.0.0-beta.15</td>
                </tr>
                            <tr>
                    <th>Field Manager</th>
                    <td>2.0.2</td>
                </tr>
                            <tr>
                    <th>Flat Categories</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th>Forms</th>
                    <td>2.0.4</td>
                </tr>
                            <tr>
                    <th>Freeform Pro</th>
                    <td>2.0.4</td>
                </tr>
                            <tr>
                    <th>Geo Cookie</th>
                    <td>1.1.2</td>
                </tr>
                            <tr>
                    <th>Hamilton Utility</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Importer</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Inlin</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th>Inventory</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>OrderExporter</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Redactor</th>
                    <td>2.1.0</td>
                </tr>
                            <tr>
                    <th>Sidebar Toggle</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th>SimpleSentry</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Super Table</th>
                    <td>2.0.7</td>
                </tr>
                            <tr>
                    <th>Taxes</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th>Twig Perversion</th>
                    <td>2.0.3</td>
                </tr>
                    </tbody>
    </table>

**Comment by lukeholder** [comment]
Hi @cwmanning, I just tried to reproduce with the example templates and could not get the same error. Can you get the error with the example templates?

**Comment by lukeholder** [comment]
Also, try using `dev-develop` to get the latest changes and bug fixes in Commerce.

**Comment by cwmanning** [comment]
Works as expected after switching to the `develop` branch (using our templates, too). Thanks, @lukeholder!
