### ISSUE TITLE
Facebook Shop/Instagram Product Tagging

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce#385]
Built-in Instagram product tagging integration.

https://help.instagram.com/1108695469241257

**Comment by sjcallender** [comment]
This is more a Facebook catalog feed issue, isn't it? As far as I understand, you can't tag products on Instagram without a Facebook business account with an approved catalog feed.

https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog/

**Comment by lukeholder** [comment]
Duplicate of #294
