### ISSUE TITLE
Unable to apply Free (0 costs) shipping to the cart

### ISSUE THREAD

**Issue by krizajb** [craftcms/commerce#387]
### Description
If shipping doesn't cost anything (0) the cart doesn't get updated. The controller returns (test ajax) cart without shipping method being updated. If shipping method isn't free, the method successfully applies to the cart.

Checking at the controller source, the cart `shippingMethodHandle` is set but get's reverted during `saveElement` call.

Using default shop templates and latest commerce (2.0.0-beta.5) reproduces the mentioned behavior.

### Steps to reproduce

1. Add shipping method without costing anything or use the default commerce 2 shipping method.
2. Attempt to apply free shipping method to the cart.
3. Shipping method not applied to the cart.

### Additional info

- Craft version: Craft Pro 3.0.11
- PHP version: 7.1.7
- Database driver & version: MySQL 5.6.34
- Plugins & versions:
  - Craft Commerce  2.0.0-beta.5
  - Mollie for Craft Commerce  1.0.0

**Comment by lukeholder** [comment]
I just pull in this fix: https://github.com/craftcms/commerce/pull/388

Does that pull request change fix your issue? Monkey patch the file to test. Thanks.

**Comment by krizajb** [comment]
Unfortunately that doesn't solve this issue.

**Comment by lukeholder** [comment]
Thanks for reporting will be fixed in the next release. Switch to `dev-develop` in your composer for commerce if you need the changes sooner. Thanks.

**Comment by krizajb** [comment]
Will do, thank you! Can confirm the fix solves the issue. When are you planning to make a new version update?
