### ISSUE TITLE
Transaction model in EVENT_AFTER_CREATE_TRANSACTION doesn't have "type" set

### ISSUE THREAD

**Issue by benface** [craftcms/commerce#396]
### Description

In the following code:
```
Event::on(Transactions::class, Transactions::EVENT_AFTER_CREATE_TRANSACTION, function(TransactionEvent $event) {
    Craft::info('Transaction type: ' . $event->transaction->type);
});
```
`$event->transaction->type` is empty.

### Additional info

- Craft version: 3.0.12
- PHP version: 7.1.13
- Database driver & version: ?
- Plugins & versions: Commerce 2.0.0-beta.5

**Comment by lukeholder** [comment]
This has been fixed in https://github.com/craftcms/commerce/blob/master/CHANGELOG-v2.md#200-beta8---2018-08-22
