### ISSUE TITLE
Ability to change product type.

### ISSUE THREAD

**Issue by oadslug** [craftcms/commerce#398]
Feature request: 
It would be great to have the ability to change the 'product type' of a product, after it is created — in the same way that you can change the 'entry type' for an entry. This can currently be done by changing the `typeId` in the 'commerce_products' table directly, but don't see any reason not to allow this via CMS as well. Obviously, there may be complications that I am not aware of (i.e.  if one product type has variants and another does not, for example). But currently, it would be impossible to reorganize/split products between types, and add fields/options to one set and not another, etc.

**Comment by lukeholder** [comment]
This is not possible in Craft sections and not happening in Commerce either. 

Look to export and import with the FeedMe plugin: https://plugins.craftcms.com/feed-me
