### ISSUE TITLE
Timeout error on Resaving product elements

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#400]
### Description
When making changes to the field layout for products I am getting  `max_execution_time` errors on the queue tasks for resaving the products across the sites. Even with this set to something like 240 or 300 seconds, it is still timing out.

Is there any way to make this more efficient/stop it from timing out?

### Additional info

- Craft version: 3.0.12
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: Commerce 2.0.0-beta.5

**Comment by angrybrad** [comment]
@nfourtythree any chance you could reproduce that with devMode enabled, then share your `craft/storage/logs/queue.log` and `craft/storage/logs/web.log` file?  You can send to support@craftcms.com if you don't want to share here.  And if you go that route you might as well send a database dump as well. :)
