### ISSUE TITLE
Calling Craft::$app->urlManager->getMatchedElement() in plugin results in 404

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#401]
### Description
We have a plugin that is checking to see if the element is available in other languages, so we are calling

```$element = Craft::$app->urlManager->getMatchedElement();```

Anytime I visit a product element url, I get a 404 error. Other element types appear to work fine.

### Steps to reproduce

1. Create a plugin and drop `$element = Craft::$app->urlManager->getMatchedElement();` into the `init()` method
2. Visit a product element url

### Additional info

- Craft version: Craft Pro 3.0.11
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

<table class="data fullwidth fixed-layout">
        <tbody>
                            <tr>
                    <th class="light">Algolia</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Amazon S3</th>
                    <td>1.0.8</td>
                </tr>
                            <tr>
                    <th class="light">Asset Rev</th>
                    <td>6.0.0</td>
                </tr>
                            <tr>
                    <th class="light">AsyncQueue</th>
                    <td>1.3.2</td>
                </tr>
                            <tr>
                    <th class="light">Audit</th>
                    <td>2.0.1</td>
                </tr>
                            <tr>
                    <th class="light">Automatic Site Switch</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Calendar</th>
                    <td>2.0.3</td>
                </tr>
                            <tr>
                    <th class="light">Category Utilities</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Certificates</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Converge</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Craft Commerce</th>
                    <td>dev-master</td>
                </tr>
                            <tr>
                    <th class="light">Environment Label</th>
                    <td>3.1.4</td>
                </tr>
                            <tr>
                    <th class="light">Feed Me</th>
                    <td>3.0.0-beta.15</td>
                </tr>
                            <tr>
                    <th class="light">Field Manager</th>
                    <td>2.0.2</td>
                </tr>
                            <tr>
                    <th class="light">Flat Categories</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Forms</th>
                    <td>2.0.4</td>
                </tr>
                            <tr>
                    <th class="light">Freeform Pro</th>
                    <td>2.0.4</td>
                </tr>
                            <tr>
                    <th class="light">Geo Cookie</th>
                    <td>1.1.2</td>
                </tr>
                            <tr>
                    <th class="light">Hamilton Utility</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Importer</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inlin</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inventory</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Locale Redirector</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">OrderExporter</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Redactor</th>
                    <td>2.1.0</td>
                </tr>
                            <tr>
                    <th class="light">Sidebar Toggle</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">SimpleSentry</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Super Table</th>
                    <td>2.0.7</td>
                </tr>
                            <tr>
                    <th class="light">Taxes</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Twig Perversion</th>
                    <td>2.0.3</td>
                </tr>
                    </tbody>
    </table>

**Comment by davist11** [comment]
Looks like this actually may be related to https://github.com/craftcms/cms/issues/3028

**Comment by lukeholder** [comment]
Let us know if the issue persists and we can look to reopen,.
