### ISSUE TITLE
Dropping last decimal place in variant/product price on edit & save

### ISSUE THREAD

**Issue by anchovy** [craftcms/commerce#402]
### Description
Craft stores the product/variant price with 4 decimal places, but only displays to 3 decimal places when editing a product/variant. So editing a product and saving can change the price when this is not wanted resulting in incorrectly priced products/variants.

### Steps to reproduce

1. Add a new product with the price 1.9999 & save.
2. Edit the product, price value is now displayed as 1.999
3. Save the product without touching the price.
4: Price has now been changed to 1.999 in the database.

### Additional info

- Craft version: Craft Pro 3.0.11
- PHP version: 7.2.1
- Database driver & version: MySQL 5.7.22
- Plugins & versions: Craft Commerce | 2.0.0-beta.5

**Comment by lukeholder** [comment]
This has been fixed on `develop` branch. Will be in the next release. Fixed in 04dd1954c00b31a76ddcf804c7

**Comment by lukeholder** [comment]
@anchovy what currency?

**Comment by lukeholder** [comment]
@anchovy also, why are you entering the price in 3 decimal places when the currency uses 2?

**Comment by anchovy** [comment]
We’ve got products that have 3 or 4 decimal places for their (unit) price.

Commerce is set up to save & store 4 decimal places, so it should return this on edit.

**Comment by lukeholder** [comment]
The database supports it because some currencies have more than 2 decimal places.

It feels like more of a bug that the we have allowed the price to be entered in more decimal places than the minor units that the currency allows.

What is your use case? Also, the line item has always rounded when saving a line items price (after calc'ing `qty * price`) so I am guessing you are happy to have the rounding to 2 decimal places there?

@anchovy

**Comment by nfourtythree** [comment]
Just dropping my thoughts in here it would be useful in a project I am working on to store the price in more decimals than the end price that is paid.

Similar to @anchovy I need to store the price with 4 decimal places (and I am ok having it rounded after the `qty * price` calculation).

As the only issue seems to be the rounding on the output of the variants form in the CP https://github.com/craftcms/commerce/blob/develop/src/templates/products/_fields.html#L151
Maybe a general setting could be added, or a per product type setting?
