### ISSUE TITLE
Create Cart when first product added to Cart

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/commerce#403]
### Description
We have the problem that we integrate the shop fully in our website. In the `_master.html` layout we do this:

```
{% if cart is not defined %}
    {% set cart = craft.commerce.carts.cart %}
{% endif %}
```

But now we run into the problem that every user that comes to our site creates an empty cart and every cart means a order number was burned. We have a specification from our client how the order numbers must looks like and this format is just six digits long. So, we run out of numbers and that's a huge problem. 

Currently it looks like this (and there are thousands of this):
![image](https://user-images.githubusercontent.com/764292/42019162-b42fefea-7ab4-11e8-8b13-3be9f3d244c8.png)

Is there a smarter way do handle that? 
We have a very modular twig structure and we use in many modules the `cart` variable. Think that's maybe another problem but for us it would be nice to have a solution, that the cart creates just when someone click the add to cart button. 

We tried it with axios but there is no action to create a cart?
Are there ways to fix our order number problem?

### Additional info

- Craft version: latest
- PHP version: 7.2
- Database driver & version: MySQL

**Comment by lukeholder** [comment]
looks like this is a bug. We shouldn't be creating the cart unless there is some type of change being made to it. Will look into a fix soon.
