### ISSUE TITLE
Unable to delete initial Clothing products without disabling first

### ISSUE THREAD

**Issue by gioppe** [craftcms/commerce#405]
### Description
Upgraded existing Craft 2 installation (without Commerce) and installed Commerce 2. Tried removing existing products, got a "unknown error" alert. From the log:

[error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Variant is missing its product 

But if I first disable the products, then they can be removed without problems.

### Additional info

- Craft version: 3.0.13.2
- PHP version: 7.0.27
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
Commerce 2.0.0-beta.5

**Comment by lukeholder** [comment]
Were you using multi-site by chance?

**Comment by gioppe** [comment]
Yes I am, multi-site and multi-language.

**Comment by lukeholder** [comment]
Can you please resave all product types, which will force a resave of all products. Then let me know if this issue persists.

**Comment by angrybrad** [comment]
@lukeholder i was able to reproduce this on a simple fresh Commerce install.

**Comment by chrissam42** [comment]
I also experience this on a fresh install of Craft 3 / Commerce 2.

**Comment by lukeholder** [comment]
Thanks everyone, looking into it.

**Comment by SystemsAlex** [comment]
I am currently suffering a similar issue.  It seems somewhere in the process of adding and removing fields from a Product Type layout that it has caused all Products to become undeleteable.
