### ISSUE TITLE
Error when creating a product type with a handle that already exists

### ISSUE THREAD

**Issue by anchovy** [craftcms/commerce#409]
### Description
Creating a new product type using a handle that already exists throw as generic 500 internal server error rather than gracefully handling the issue.

### Steps to reproduce

1. Add a product type with a handle of 'noDupes'
2. Add a new product with the handle of 'noDupes'
3. See generic 500 error page, in logs the error is:
`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'noDupes' for key 'commerce_producttypes_handle_unq_idx' in /.../vendor/yiisoft/yii2/db/Command.php:1258`

### Additional info

- Craft version: Craft Pro 3.0.11
- PHP version: 7.2.1
- Database driver & version: MySQL 5.7.22
- Plugins & versions: 
  - Craft Commerce: 2.0.0-beta.5

**Comment by lukeholder** [comment]
Thanks for reporting, will be fixed in the next release.
