### ISSUE TITLE
Programatically re-send specific email for given order via another model

### ISSUE THREAD

**Issue by anchovy** [craftcms/commerce#416]
### Description
Need to be able to resend a (custom) email for a given order id. i.e. 
`craft.commerce.resendEmail('email_` handle',ORDER_ID)`

### Example Use case 
When orders need to be pushed via email to an external 3rd party for extra processing; if this fails for any reason (network issues etc) we need to be able to re-trigger the email send.
eg: cron checks for 3rd party response and updates order status. if no response after 3 hours, email is re-sent.

### Additional info

- Craft version: 3

**Comment by lukeholder** [comment]
In Craft 3, all service methods are exposed so you can do that if you want:

```twig
{% set email = craft.commerce.emails.getEmailById(ID_HERE) %}
{% set order = craft.commerce.orders.getOrderById(ID_HERE) %}
{% set orderHistory = order.getHistories()|first %}
{% do craft.commerce.emails.sendEmail(email,order,orderHistory) %}
```
