### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#42]
Just use twig templates for report with dompdf ?

Also provide system level widgets for basic charts. (Not inventing own dashboard)

Possible report: #247

**Comment by lukeholder** [comment]
- [ ] #1090

**Comment by lukeholder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reporting Stats](https://trello.com/c/q0q7qadb/4-reporting-stats)
