### ISSUE TITLE
Quick-save shortcut on Order page results in 404

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#425]
### Description
Using the normal save button works as expected—we're directed back to the order index.

When using the quick-save method (<kbd>Command + S</kbd>), the quick-save redirect URL is set as `$order->number` instead of `$order->id`.

### Steps to reproduce

1. Visit an order page in the Admin
2. Press <kbd>Command/Ctrl + S</kbd>
3. Inspect URL bar to see order number

### Additional info

- Craft version: Craft Pro 3.0.16
- PHP version: 7.0.30
- Database driver & version: PostgreSQL 9.5.12
- Plugins & versions: Commerce 2.0.0-beta.6

**Comment by AugustMiller** [comment]
Nevermind, I see this is fixed by https://github.com/craftcms/commerce/commit/145a4bc091e7b95edee466c8e88282e2a90117d2#diff-c3799a2995116ea9f4ee0c45c9cbf288R9

Thanks!

**Comment by lukeholder** [comment]
Yes sorry, the wrong issue was referenced in the commit.

**Comment by lukeholder** [comment]
Thanks.
