### ISSUE TITLE
Gateway not allowed.

### ISSUE THREAD

**Issue by johnj24** [craftcms/commerce#432]
### Description
Getting things converted over after upgrading from Craft 2 and Commerce 1. I'm currently at the checkout page and after hitting the payment form submit, I get hit with "Gateway not allowed."

I only have Dummy and Manual gateways showing in my gateway settings. I've disabled Dummy so that I can use Manual exclusively to checkout without a credit cart or a price.

I read that you need to install gateways now in Commerce 2, but I can't find a Manual gateway plugin so I assume this is one that comes pre installed?

### Steps to reproduce

1. Upgrade from Commerce 1
2. Enable Manual gateway
3. Hit submit button on front-end payment form.

### Additional info

- Craft version: 3.0.17.1
- PHP version: 7.1.12
- Database driver & version: mysql
- Plugins & versions:

**Comment by AugustMiller** [comment]
When "enabling" the gateway, did you also select `Enabled for customers to select during checkout?`?

**Comment by lukeholder** [comment]
Both manual and dummy are included with Commerce.

The `Gateway not allowed` error is shown when the gateway is not `frontEndEnabled`. Can you confirm it is enabled?

**Comment by johnj24** [comment]
Manual is indeed checked as enabled under Commerce > Settings > Gateways. 

Here is my payment form:
```
<form method="POST">
  <input type="hidden" name="action" value="commerce/payments/pay">
  <input type="hidden" name="redirect" value="{{ 'purchase/confirm?number={number}' }}">
  <input type="hidden" name="cancelUrl" value="">
  {{ csrfInput() }}

  <button class="c-button c-button--primary u-rounded-none u-w-1/1">Purchase with credits</button>
</form>
```
Two questions: 1) Is it required to have `paymentMethodId` as an input? 2) If I just want to checkout for free, do I need the card fields? The products do have a price on them, but my understanding was the Manual gateway will allow checkouts no matter what.

**Comment by johnj24** [comment]
Ok, truly bizarre. I didn't change a thing (that I can remember), but now the transaction is going through as I check on it this morning. One thing to note: After the transaction, I'm being redirected to my homepage and not where `<input type="hidden" name="redirect" value="{{ 'purchase/confirm?number={number}' }}">` should take me.

**Comment by lukeholder** [comment]
> 1) Is it required to have paymentMethodId as an input?

Yes, you need to pass the `gatewayId` param with the ID of the gateway (renamed from `paymentMethodId` in commerce 2)

>2) If I just want to checkout for free, do I need the card fields?

Depends on the gatewayId you submit. Some gateways like manual dont need any payment form data.
