### ISSUE TITLE
Coupon codes don't appear in cart.orderAdjustments

### ISSUE THREAD

**Issue by builtbybrad** [craftcms/commerce#434]
If I apply a coupon code to my cart the coupon code discount doesn't appear in `cart.orderAdjustments`. If I directly call `cart.getAdjustmentsTotalByType('discount')` then the amount of discount that the coupon applies is returned. I'd expect this to also be returned in `cart.orderAdjustments` so that I can display a breakdown of all applied discounts including coupon codes and their descriptions.

### Additional info

- Craft version: 3.0.17.1
- PHP version: 7.0.11
- Database driver & version: MySQL 5.5.50
- Plugins & versions: 

Craft Commerce | 2.0.0-beta.6

**Comment by lukeholder** [comment]
@builtbybrad 

I think you are looking for all adjustments then that is`order.adjustments`. This returns ALL adjustments made to the order.

`order.orderAdjustments` just returns the adjustments made to the order, and not any particular line items.

My guess is that your discount was applied to a particular line item, so you could also see it by looping over `order.lineItems` and get `item.adjustments`.

Let me know if that's not it.

**Comment by bartrylant** [comment]
I understand that certain adjustments are applied to line items. But suppose I have two coupon codes that both work together:

`FREESHIPPING` removes the shipping cost
`FIRSTORDER` gives 10% discount on full priced items

I would like to be able to display those two used codes/discounts in my order overview (+ the ability to remove one of the codes). At this moment, only the last used code shows, and there is just the total discount amount. + I can't give users the ability to remove just 1 of the used coupons.
