### ISSUE TITLE
Decouple Session from getCart

### ISSUE THREAD

**Issue by henrypenny** [craftcms/commerce#435]
### Description

Feature request: Commerce 2 plugin.

It would be nicer IMO to be able to retrieve a cart from the `craft\commerce\services\Carts` without needing a session. Currently the session is tightly coupled to this functionality which kills the flexibility of this api. Can I create a CLI command that calls this function? No - there's no session on the CLI.

If this were my plugin, I'd handle all HTTP related issues such obtaining a cart id from the session and IP tracking in `CartController` and keep the Cart service clear of any thing HTTP related.

`getCart` could take the cartId as an argument.

You could add a `getCartFromSession(Session $session)` function if you really need it. But at least make the session optional.

I have the same general complaint about the tight coupling of the Request as well. But this would be a start.

**Comment by lukeholder** [comment]
Hi @henrypenny thanks for the feedback.

The carts service is definitely tied to the customers session. That's kinda the purpose of it. 
i.e `getSessionCartNumber()`, `forgetCart()` etc.

Carts are just orders, so if you want a new cart without any of the session stuff, simply do:

`$cart = new \craft\commerce\elements\Order();`

Is there anything in the carts service that you need apart from getting the Cart?

**Comment by lukeholder** [comment]
Taking a look at the `actionUpdateCart()` controller action for adding to a cart. There shouldn't be anything session related in that.

Take a look at the cart controllers `_getCart()` method to see how we get the cart when you know the cart you want to modify `$cart = Order::find()->number($orderNumber)->isCompleted(false)->one();` That isn't using the cart service at all.

Hope that helps.

**Comment by henrypenny** [comment]
Thanks @lukeholder
