### ISSUE TITLE
Inventory management

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#44]
- Manage stock on a per-location basis 
- Allow backorders
- Stock screen tracks adding and deduction of stock.
- Allow Bulk updating of stock.
- Track number of purchasable sales over a period of time.
- Allow reservation of stock while items are in the cart. ?
- Change 'unlimited stock' to 'track stock' ?
- Update stock when manually editing the order on order edit page.
- Update stock option when deleting an order.

**Comment by MichaelWheldon** [comment]
Just checking on the status of `Out of stock threshold #50`. This would be a great feature.

**Comment by meinhard-meintjes** [comment]
Hello everyone, I'm also currently trying to figure out how to handle the lack of this feature. Any updates on the status? If it's still a long time away from being ready, is the easiest/best solution writing a plugin or running a separate instance/DB (in this case 2 instances would be enough) in your opinion? Thanks!

**Comment by jacobrussell** [comment]
@lukeholder @brandonkelly Can you provide any update on the status of this issue?  Is it in your pipeline or still future development?

**Comment by lukeholder** [comment]
@jacobrussell Was and is, but we can't give a timeline on it sorry. Should be in Commerce 4.

**Comment by denisyilmaz** [comment]
Is there a plan to have the backorder-feature arriving in Commerce 3?

**Comment by lukeholder** [comment]
@denisyilmaz no plan in Commerce 3 sorry.

**Comment by denisyilmaz** [comment]
is there any update on a timeline when commerce 4 will be available? some of these features are urgently requested by some projects and it would be very nice to give the project-owners a idea of when these features can be revisited / or if a solution must be found in any other way.

**Comment by jacobrussell** [comment]
@lukeholder Can you provide any update here?  Is this expected at some point this year?  Solid inventory management is a core e-commerce feature that's hard to backfill with custom solutions well.  Would be very helpful to know if we can still expect this with Commerce 4.0, and if that's coming soon.

**Comment by lukeholder** [comment]
@denisyilmaz @jacobrussell we are beginning work on multi-store support, and stock/inventory system to support each store is a core feature. Sorry for the delay but we are working on it. Sorry I can't give a timeline.

**Comment by CMeldgaard** [comment]
@lukeholder Is creating a custom stock-field the only fix to make backorder possible in Commerce 3 ?

**Comment by mediabeastnz** [comment]
👀
