### ISSUE TITLE
"Enter stock" label not completely hidden 

### ISSUE THREAD

**Issue by gioppe** [craftcms/commerce#440]
### Description
When setting Stock to "unlimited" in a Variant block the "Enter stock" label remains faintly visible.

![immagine](https://user-images.githubusercontent.com/1929797/43882424-e518c0ca-9baf-11e8-8b2a-d2f24dcb8351.png)

(Enhanced contrast below)

**Comment by lukeholder** [comment]
Which browser and version?

**Comment by gioppe** [comment]
Firefox 61.0.1 / Mac
