### ISSUE TITLE
SKU with comma in it cannot be queried with the sku helper

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/commerce#441]
### Description
I have an import script witch imports the products from my crm.
But when doing so, i try to find the variantelement with an sku, but if the sku contains special characters like a comma, `200-0448-88,4 R` it won't find the variant, even though it is in the database.

Like so:
 $variant = VariantElement::find()->sku($row['Articlecode'])->one();
Results into NULL

But this
$variant = VariantElement::find()->where(['defaultSku' => $row['Articlecode']])->one()
Results into the product being found.

**Comment by lukeholder** [comment]
@lenvanessen 

You are running into a feature of all elements including, entries, categories etc

If you pass a comma separated string to a param, it treats the condition as an array.

To stop this from happening you need to escape the comma:

```
{% set variant = craft.variants.sku("one\\,two").one() %}
{{ variant.id }}
```
The above will return the ID of the variant with the SKU of `one,two`.
