### ISSUE TITLE
Shipping method exclude or include multiple zones

### ISSUE THREAD

**Issue by mrksmts** [craftcms/commerce#443]
### Description
We have a few different shipping zones:
- Netherlands
- Europe (complete Europe except for Netherlands)
- Worldwide (rest of the world excluding Netherlands and Europe)

To create worldwide we had to add all the countries that were not in the other two zones manually.

### Suggestion
Ability to exclude zones when making a Shipping method rule.

### Examples
- Everywhere, but exclude the zones Europe and Netherlands
- Instead of creating a zone that does not include country X; Include zone Europe and exclude zone Netherlands

**Comment by j-greig** [comment]
+1 for this request, thanks :)

**Comment by lukeholder** [comment]
Duplicate of #200
