### ISSUE TITLE
Error when updating Order Status

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#447]
### Description

When updating an existing order status with at least one Email selected, a foreign key constraint error is produced

### Steps to reproduce

1. Create an _Email_;
2. Create an _Order Status_;
3. Edit the _Order Status_ from Step 2;
4. Attach an Email to the _Order Status_;
5. Save the _Order Status_.

This should produce the SQL error, suggesting that the join table `commerce_orderstatus_emails` doesn't contain an expected row?

### Additional info

- Craft version: 3.0.20
- PHP version: 7.1.16
- Database driver & version: PostgreSQL 10.3
- Plugins & versions: Commerce 2.0.0-beta.7

**Comment by lukeholder** [comment]
@AugustMiller Hi, I can't reproduce this on a clean install of commerce on postgres. I followed your steps.

Could you confirm and I will reopen.
