### ISSUE TITLE
Very impractical json errors in the cart update json

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#449]
### Description

I am trying to get an Ajax cart up and running and I'm seeing some very hard to use error template being use.

```
errors:
  lineItems.1.qty:Array(1)
    0:"There are only 1 " Ticket to Ride: First Journey (Europe)" items left in stock"
    length:1
```

The use of that very specify `lineItems.1.qty` makes it very hard to use in javascript.  The use of an array that we could loop through would be very good, maybe using the lineItem id instead of the arbitrary loop index.

### Steps to reproduce

Use a json call to get to `commerce/cart/update-cart`.
The easiest way to get an error is to try and add more items to your cart than it is available in the stock.

### Additional info
- Craft version: 3.0.20
- PHP version: 7.2
- Plugins & versions: Craft Commerce 2.0.0-beta.6

**Comment by echantigny** [comment]
I see now that this might be starting to shape up in beta.7.  The weird errors array is still there, but you are now inserting the errors in the lineItems array.

This in turn creates a more problematic issue of not being able to properly loop through the lineItems array and worst the totalLineItems is now counting everything in that array, making my 1 item cart go up to 2.

**Comment by lukeholder** [comment]
The errors placed on an order are keyed by the attribute name.

If the attribute is inside a nested child model like line items, the key is generated using dot syntax (like a path) and the error is added to the parent object (in this case the order/cart).

This is a feature of Craft
https://docs.craftcms.com/api/v3/craft-base-model.html#method-addmodelerrors

This means only a single array of errors is returned for the top level order, compatible with the Yii model errors array.

We were always showing errors on the line items also, which was accessible in twig through `item.getErrors()`. In beta-7 we made sure those errors with on the line item JSON.

The issue you are hitting with the totalLineItems, is that the cart with it's errors is returned. This includes all wrong values and totals based on the previous submission. If you want a clean cart with no errors, do a GET to `commerce/cart/get-cart`
