### ISSUE TITLE
Manually setting order Paid/Unpaid Status

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#450]
We have a custom plugin to handle some order management, as it relates to subscriptions we have set up on the site. 

In short, after the `Subscriptions::EVENT_RECEIVE_SUBSCRIPTION_PAYMENT` fires we're dynamically creating a new order, assigning the customer, adding a line item, and marking the order as complete. The problem though is that the Paid Status is set to `Unpaid` is Total Paid is set to `$0.00`

Doing a little digging, it looks like the only way to update those fields is to create an actual transaction with the payment gateway, and it's not possible to set them manually. Is that the case?

What's the best method here for manually updating those fields?

**Comment by lukeholder** [comment]
So you are wanting a new order for every subscription payment?

**Comment by bryantAXS** [comment]
Right, in our use case a subscription is a recurring order of the same products, and each time a subscription payment happens, we'd like to queue up another order and mark it as paid.

**Comment by lukeholder** [comment]
Yes best to create a transaction - probably best use the 'manual' gateway for the `transaction->gatewayId`. Although, if it represents a Stripe transaction, maybe build a transaction in Commerce with reference to the transaction in stripe.

https://craftcms.stackexchange.com/questions/27391/mark-a-commerce-order-as-paid-via-a-custom-plugin
