### ISSUE TITLE
Variant with automatic SKU format with title throws exception instead of validation message

### ISSUE THREAD

**Issue by tomdeleu** [craftcms/commerce#452]
### Description

I have a product type setup with variants, and the following automatic SKU format:
{product.slug|upper}-{title|kebab|upper}

When trying to save without filling in the variant title, I get an exception instead of a nice input validation message. 

Exception: https://cl.ly/0R3G3F1P3L0q

I know it's because of the auto SKU format and the title not being available, but wouldn't it be nicer to show a nice input validation message like "SKU cannot be calculated because of xxx" or so?

### Steps to reproduce

1. Product with variants and automatic SKU with variant title
2. Do not fill in title and save
3. No input validation but throws exception

### Additional info

- Craft version: Craft Solo 3.0.20
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23

**Comment by lukeholder** [comment]
Hi Tom,

I cant reproduce with a blank title: https://jmp.sh/A3j98jy

Let me know if you have any other info.
