### ISSUE TITLE
Incorrect amount of subscription plans in list

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce#453]
### Description

I've created 11 subscription products in Stripe, but in Craft when I'm creating the Subscription Plans I can only seem to see 3 plans. I've hit refresh a lot and they don't seem to pull through.

<img width="500" alt="screen shot 2018-08-20 at 14 45 58" src="https://user-images.githubusercontent.com/522877/44344414-92c9b400-a488-11e8-993e-a33ec4046a64.png">

<img width="691" alt="screen shot 2018-08-20 at 14 46 11" src="https://user-images.githubusercontent.com/522877/44344419-952c0e00-a488-11e8-8f32-b39d9df8ad1a.png">

### Additional info

- Craft version: 3.0.20
- PHP version: 7.0.31
- Database driver & version: MySQL 5.6.40
- Plugins & versions: 2.0.0-beta.7

**Comment by andris-sevcenko** [comment]
Any chance you have created subscription plans/products on Stripe Test mode, but your gateway is set to use live mode or vice-versa?

**Comment by bymayo** [comment]
I did check this. The version we're running at the moment is a staging version but has Live API keys in, which is picking up the correct (But only 3) Live products/subscriptions from Stripe.

The Test products/subscriptions I created originally in Stripe... I deleted so it shouldn't be showing anything.

My only thought here is that when I look in the MySQL for the plans, I see a plan called 'Biology' but it's set to `isArchived` 1. So when I create a new Subscription called 'Biology' it says the handle already exists and suspiciously, Biology product/subscription doesn't appear in the 'Gateway Plan' list.

Could this be a connection?

**Comment by andris-sevcenko** [comment]
Okay, so, even though the plugin's API is set to a specific version, recent changes affect the data returned and how it's structured, so there's definitely some work required.

By the way, are you using one pricing plan per product on Stripe's end?

**Comment by andris-sevcenko** [comment]
@bymayo does updating to https://github.com/craftcms/commerce-stripe/commit/cb813e778968e25f9f889757135fc3a26885ec84 *and* switching to the API version `2018-07-27` in Stripe dashboard fix this for you?

**Comment by bymayo** [comment]
@andris-sevcenko Okay so I've updated and changed the API settings and they all pull through now... Except one. The 'Biology' subscription.

Theres not a limit on the amount of plans that can pull through is there into the Gateway Plan field? 

As it seems to cap at 10...

I created another (12 subscription products) and it still only shows 10, but now Biology and Chemistry are missing.

Yeah, I'm only using one pricing plan per product which is 'Yearly'.

**Comment by andris-sevcenko** [comment]
[Now that you mention it...](https://stripe.com/docs/api/php#list_plans-limit)

I'll patch that up, test all the other stuff with the new API version and cut a Stripe plugin release most likely tomorrow for this.

**Comment by bymayo** [comment]
@andris-sevcenko Perfect! Thanks, i'll wait for the update then 💯 Thanks for looking in to this so quickly 🥇

**Comment by bymayo** [comment]
Seems to have fixed the issue, thanks! 💯

**Comment by lukeholder** [comment]
This has been fixed in https://github.com/craftcms/commerce/blob/master/CHANGELOG-v2.md#200-beta8---2018-08-22
