### ISSUE TITLE
Product Element return disabled variants

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce#454]
### Description
When getting a product or view a product page the product element returns disabled variants. 
[Video Example](http://x.n43.me/2H342z1q3H2I)

I tracked this down to the `getVariants` call (https://github.com/craftcms/commerce/blob/develop/src/elements/Product.php#L383-L407) and therefore subsequently `getVariantsByProductId` (https://github.com/craftcms/commerce/blob/develop/src/services/Variants.php#L36-L41) which doesn't has stats of `null`.

It is ok if that is as designed it is just a little confusing as Craft in other instances doesn't do this, for example a Matrix field, disabled blocks are not returned.

Just wondering if this is likely to change, or if it will be required in templates to checked the enabled attribute before output?

FYI - this was the test template I used:
```twig
{% set product = craft.products.one() %}

<h1>Product: {{ product.title }}</h1>

<h3>Variants</h3>
<ul>
  {% for variant in product.variants %}
    <li>{{ variant.title }} - {{ variant.enabled ? '<strong style="color: green;">Enabled</strong>' : '<strong style="color: red;">Disabled</strong>' }}</li>
  {% endfor %}
</ul>
```

**Comment by lukeholder** [comment]
`product.variants` does not return an element query - it gets all variants regardless of status. The link looks like matrix in the UI, but it is not a relation custom field (which returns an element query).

If you want to get variants through an element query (which does default to enabled only) you could do:

```twig
{% set product = craft.products.one() %}
{% set variants = craft.variants.product(product).all() %}

<h1>Product: {{ product.title }}</h1>

<h3>Variants</h3>
<ul>
  {% for variant in variants %}
    <li>{{ variant.title }} - {{ variant.enabled ? '<strong style="color: green;">Enabled</strong>' : '<strong style="color: red;">Disabled</strong>' }}</li>
  {% endfor %}
</ul>
```

**Comment by nfourtythree** [comment]
Hey @lukeholder 

Thanks for your response, as I mentioned above it was just a bit of a strange one as (having used Craft since 2013) this behaviour wasn't quite as expected.

However knowing is half the battle, and now I can update the templates with the knowledge that there could be disabled variants returned by `product.variants`. I think it could be worth updating the docs to state that all variants are returned regardless of status as it could trip up others.

Thanks for your template suggestion, and input!
