### ISSUE TITLE
Making Purchasable _loadSales() extendable

### ISSUE THREAD

**Issue by gijsstegehuis** [craftcms/commerce#455]
I am currently implementing a custom Purchasable element allowing me to apply some business logic to the sale part. Because [_loadSales()](https://github.com/craftcms/commerce/blob/develop/src/base/Purchasable.php#L258) is a private method, it's currently impossible to extend the default behavior:

Consider making this method `protected` to allow plugins to extend the default behavior.

**Comment by lukeholder** [comment]
Changing how sales work, using a catalog pricing system. See #1041
