### ISSUE TITLE
POS integrations

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#46]
Could be done with a general purpose card reader (e.g. https://www.magtek.com/product/pin-pads), and/or we can integrate with Square (https://squareup.com/developers, https://docs.connect.squareup.com/api/connect/v1/#navsection-transactions) - probably as a separate plugin, since the workflow/settings involved in integrating Square webhooks will be more complex than normal gateways.

**Comment by brandonkelly** [comment]
[Stripe Terminal](https://stripe.com/terminal) may also be an option, which is now out of beta.

**Comment by j2is** [comment]
Commonly asked for synchronising inventory between online purchases and in-store, and being able to look up online or physical orders in Craft CMS. Smaller requests: putting gift cards or refunds through on a POS  and having that reflected in Craft. Square might be complex for sure, I'd vote for Stripe terminal

**Comment by lindseybradford** [comment]
I don't want to assume that because this is an open issue, that it's on the roadmap: is POS inventory management a feature that's underway, and if so, roughly when could we expect to see it drop?

**Comment by lukeholder** [comment]
@lindseybradford No timeline sorry, but not in the immediate future.

**Comment by j2is** [comment]
This one would be a game changer. Patiently await the day this becomes a reality

**Comment by aeu** [comment]
Hi, it's been approximately a year since the last comment on this thread.  Is anything in the works as far as integrating Craft Commerce & POS ?

**Comment by nfourtythree** [comment]
Hi All

There are a lot of variations when it comes to POS, especially when it comes to what people would like to see Commerce handle and how gateways/POS service providers handle things.

It would be great if people could outline what they are looking for in terms of this feature.

- POS feature you would like to see in Commerce
- Third party POS services/gateways to integrate with
- Any other POS information

This will give us more information on what a POS feature in Commerce could look like.

Thanks!

**Comment by stevenjwright** [comment]
@nfourtythree I have a client who's seeking this feature in the next 12 months. 

**Use Case**
- Single Brick & Mortar store with international E-Comm presence.  
- Current POS lacks API functions to keep stock in sync with site
- Primary reason for this is the ability for in-sync stock between Site & Phycical Store.
- E-Comm uses Stripe, Physical Store uses WorldPay Terminal & Cash

**Would be nice Features**
- Multi-(Physical) Store Stock / Inventory
- Sales Reporting (Breakdown per store/location/online v physical)
- Some Products to be POS-Only not online, and other way around (though could be a custom field)
- Some ability for a USB-based Barcode Scanner
- Email/SMS Receipts

Hope that helps!
