### ISSUE TITLE
property resaveAllCustomerOrdersOnCustomerSave undefined

### ISSUE THREAD

**Issue by borducks** [craftcms/commerce#460]
### Description
After update to Commerce 1.2.1363, creating a new user gives this error:
Property "Craft\Commerce_SettingsModel.resaveAllCustomerOrdersOnCustomerSave" is not defined. 

### Steps to reproduce

1. Update to Commerce 1.2.1363 via admin UI update
2. Create a new user. Fill out only required info on first tab.
3. Click save and enter your admin password when prompted

### Additional info

- Craft version: 2.7.0
- PHP version: 7.0.28-0ubuntu0.16.04.1 
- Database driver & version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $ 
- Plugins & versions: 
Authorize Accept.js Gateway 1.0.0
  Marion Newlevant  View Documentation  
Enabled 
  
Commerce 1.2.1363
An amazingly powerful and flexible e-commerce platform for Craft CMS.
  Pixel & Tonic   View Documentation  
Enabled 
  
Contact Form 1.9.0
  Pixel & Tonic   View Documentation  
Enabled 
  
Convert Legacy Members 1.0
Search legacy member accounts and convert them to new system.
  Thoughtprocess Interactive  —   
Enabled 
  
Kint 1.1.0
Adds Kint, an in-app PHP debugger, for use in Twig and PHP.
  Mildly Geeky  View Documentation  
Enabled 
  
Kssp Member Import Plugin 1.0
  Thoughtprocess Interactive  —   
Enabled 
  
Kssp Plugin 1.0
  Thoughtprocess Interactive  —   
Enabled 
  
Legacy Login 0.0.4
User-base migration made simple.
  Top Shelf Craft   View Documentation  
Enabled 
  
Member Import Plugin 1.0
  Thoughtprocess Interactive  —   
Enabled 
  
Patrol 1.4.2
  Selvin Ortiz  View Documentation  
Enabled 
  
reCAPTCHA for Craft 1.0
  Aaron Berkowitz   —   
Enabled 
  
Redactor Extras 1.3.2
  Elliot Lewis  View Documentation  
Enabled 
  
Shortlist 1.1.1
  Top Shelf Craft   —   
Enabled 
  
Tag Manager 0.2.0
  Bob Olde Hampsink   —   
Enabled 
  
TPI Tools 1.0
  TPI   —   
Enabled 
  
![screen shot 2018-08-23 at 4 58 44 pm](https://user-images.githubusercontent.com/5326423/44554351-34a20880-a6f6-11e8-8dda-df4950d4b5a1.png)

**Comment by borducks** [comment]
Looks like maybe a typo when calling resaveAllCustomerOrdersOnCustomerSave method vs. property?

**Comment by borducks** [comment]
Looks like Commerce_SettingsModel has no such property.

**Comment by lukeholder** [comment]
I, thanks for reporting. This has been fixed for the next release out soon.

**Comment by lukeholder** [comment]
https://craftcommerce.com/changelog#build1364
