### ISSUE TITLE
Payment Gateway Used in Control Panel Still Requires Being Enabled in Frontend

### ISSUE THREAD

**Issue by sbossarte** [craftcms/commerce#461]
### Description

Setting a Payment Gateway to not be allowed in the frontend and then attempting to use that payment gateway manually to mark an order on the backend as paid (especially in the case of the Manual gateway) prevents use of the gateway, because it still requires being enabled for frontend use.

In this kind of case I would expect Craft to distinguish that the payment request is coming from the backend and allow using the 'hidden' gateway.

Edit: It's worth mentioning that this isn't happening presently, using the same method, so it must be some interaction with something else going on.

```
yii\base\InvalidConfigException: Gateway not allowed. in /xxxxx/vendor/craftcms/commerce/src/elements/Order.php:1345
Stack trace:
#0 /xxxxx/vendor/craftcms/commerce/src/controllers/PaymentsController.php(157): craft\commerce\elements\Order->getGateway()
#1 [internal function]: craft\commerce\controllers\PaymentsController->actionPay()
#2 /xxxxx/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /xxxxx/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /xxxxx/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('pay', Array)
#5 /xxxxx/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('pay', Array)
#6 /xxxxx/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('commerce/paymen...', Array)
#7 /xxxxx/vendor/craftcms/cms/src/web/Application.php(538): craft\web\Application->runAction('commerce/paymen...', Array)
#8 /xxxxx/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /xxxxx/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /xxxxx/web/index.php(21): yii\base\Application->run()
#11 {main}
```

### Steps to reproduce

1. Make a Manual payment gateway
2. Mark it as not allowed on the frontend
3. Find an order/cart
4. Attempt to create a transaction on the order using said gateway.

### Additional info

- Craft edition & version: Craft Pro 3.0.21
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.19
- Craft Commerce: 2.0.0-beta.8

**Comment by lukeholder** [comment]
@sbossarte is this still an issue? You edited with:

> It's worth mentioning that this isn't happening presently

Will re-open if so.

**Comment by sbossarte** [comment]
Haven't noticed it again, so perhaps it's been cleaned up since.
