### ISSUE TITLE
max_input_vars error when saving product

### ISSUE THREAD

**Issue by oadslug** [craftcms/commerce#463]
### Description

When saving some products, I am getting an error:

`Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini.`

The product in question is fairly large — 10 custom fields, and 46 variants with 20 custom fields — but I wouldn't think that I should need to increase the input vars. Not sure what is causing this. Is there something else going on perhaps? 

### Additional info

- Craft version: Craft CMS 3.0.21
- PHP version: 7.0.13
- Database driver & version: MySQL 5.6.34
- Plugins & versions: Commerce 2.0.0-beta.8 (there are some other plugins as well, but nothing that should impact saving products)

**Comment by angrybrad** [comment]
You could easily hit that 1000 default max_input_vars limit with that setup.  Depending on the fields, you might end up need to bump post_max_size as well.

**Comment by lukeholder** [comment]
@oadslug thanks for the suggestion, please submit it as a separate issue and lets see if anyone else 👍's it.
