### ISSUE TITLE
Change `commerce_orders.message` column to `text`, or increase `varchar` limit

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#465]
Would love to be able to include Order messages of more than 255 characters.

Discovered after trying to import some legacy orders that included loooong order instructions.

Currently, this means that the first order status message, applied via `order.message`, can only be 255 characters, but you can supply more when updating an order's status (as the actual `commerce_orderhistories.message` column uses the `text` type, and can contain much longer messages.

**Comment by lukeholder** [comment]
Will do
