### ISSUE TITLE
Trying to get property 'foreignKeys' of non-object on plugin update

### ISSUE THREAD

**Issue by colinmeinke** [craftcms/commerce#466]
### Description

We are attempting to update Craft Commerce from 2.0.0-beta.3 to 2.0.0-beta.8.1.

However, we are receiving `Trying to get property 'foreignKeys' of non-object` errors during migration because we are missing the table `commerce_producttypes_i18n` in our database.

Should this table exist? This was a fresh Commerce install on Craft 3, so I'm not sure what could have gone wrong here. How can we recover from this situation?

### Additional info

- Craft version: 3.x
- PHP version: 7.2.7
- Database driver & version: MySql 5.7.21

**Comment by lukeholder** [comment]
Please send your beta.3 DB backup to support@craftcommerce.com

**Comment by fantasticmachine** [comment]
I'm having this same problem. What was the upshot?
