### ISSUE TITLE
Create sales for the entire product type with category filtering also

### ISSUE THREAD

**Issue by matt-adigital** [craftcms/commerce#467]
### Description
More of a feature request than an issue but currently when creating a new sale, you can select product variants and categories. If a user wants to apply a sale to an entire product type and then restrict it to a particular category on top of this, they would have to select all of the variants individually that this sale applies to.

It would be great to see a product type field so that we could select all of the "Clothing" product type with a category of "Jumpers" as a basic example for sites with a very large catalogue of products. This sale would then only apply to the products within Clothing which also have a category of Jumpers.

The reason we can't just use the category to apply this sale, is because in our use case we have a number of categories which will be used across multiple product types due to the format of the product catalogue we've been provided with. We also have retail and wholesale pricing depending on the logged in members user group.

### Additional info

- Craft version: 3.0.21
- Commerce version: 2.0.0-beta.8.1

**Comment by lukeholder** [comment]
This would need to come whenever we expose more promotion condition options to purchasables.

No plans for this in the short term.

**Comment by matt-adigital** [comment]
Thank you for the response Luke, I look forward to this becoming available longer term. Until then I'll look into a way of doing something custom via a plugin/module to achieve this. Cheers.

**Comment by lukeholder** [comment]
Related to #80
