### ISSUE TITLE
Add user-specific discount option

### ISSUE THREAD

**Issue by sjcallender** [craftcms/commerce#470]
The ability to assign a coupon code to a specific email address would be incredibly helpful for serious ecommerce brands.

Bonus would be the ability for a user to claim that discount (add it to the cart) via hash or other direct linking option. Or something in the API so we can do it in a bespoke manner.

**Comment by lukeholder** [comment]
Need to add 2 new conditions to discounts:

1. User condition (Select a user/users)
2. Email Address condition.

**Comment by nfourtythree** [comment]
3.1 introduces discount condition formula which will allow you to limit a discount to a user or email address.

For a fully-featured implementation, this will be part of #80
