### ISSUE TITLE
On a multisite installation of Craft, I can't programmatically save an order

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/commerce#473]
### Description
I have a Craft installation with two sites. I also have a module that changes order fields on certain events. For the first site, this is no problem. For the second site, this is not allowed, as the site is not in the list of 'supported sites' for the Order element.

As long as Commerce is not (really) multisite-savvy, I would propose adding a getSupportedSites() method to the Order element, that returns all sites:

     public function getSupportedSites(): array
     {
         $sites = [];
     
         foreach (Craft::$app->getSites()->getAllSites() as $site) {
             $sites[] = [
                 'siteId' => $site->id,
                 'enabledByDefault' => true
             ];  
         }
 
         return $sites;
     }

### Steps to reproduce

1. Create two sites
2. Try to programmatically save a field value (in my case, a Matrix field value) to an order

### Additional info

- Craft version: 3.0.22
- Commerce version: 2.0.0-beta.8.1

**Comment by lukeholder** [comment]
Would testing for `Order::isLocalized()` (which is an element interface method) be enough? It returns `false` for orders.

**Comment by lukeholder** [comment]
Also check out `ElementHelper::supportedSitesForElement($order);`
