### ISSUE TITLE
Add a full name field to Address

### ISSUE THREAD

**Issue by sjcallender** [craftcms/commerce#474]
Given the international abilities of Commerce, which will be expanded with newer features, the default required First Name and Last Name fields is not always ideal. Plus, usability studies show that customers think in terms of "Full Name." Source: https://baymard.com/blog/mobile-form-usability-single-input-fields#issue-3-perception

Can you make it so that we can have one required name field with the option to give it a custom label? Or even better, give us the ability to define address fields and set which of them are required.

**Comment by sjcallender** [comment]
Essentially the same as https://github.com/craftcms/commerce/issues/163

**Comment by lukeholder** [comment]
First Name and Last Name could populate Full Name.

**Comment by lukeholder** [comment]
Dup of #163
