### ISSUE TITLE
Order status default state is removed on save

### ISSUE THREAD

**Issue by MartyWallace** [craftcms/commerce#476]
### Description

When visiting an order status in Commerce settings which is a default, then saving it, the default state is removed. The default state can be re-attached by visiting the status again and checking `New orders get this status by default`. This can be replicated by doing the same thing (visiting the status which is now considered the default, saving it).

### Steps to reproduce

1. Navigate to an order status which is considered the default e.g. `/admin/commerce/settings/orderstatuses/1`.
2. Save it without making any modifications.
3. The default state should be removed.

### Additional info

- Craft version: 3.0.22
- PHP version: 7.2.8
- Database driver & version: PostgreSQL 10.4

Plugins & versions:

```
Craft Commerce 2.0.0-beta.8.1
Digital Ocean Spaces Volume v1.0.0
Feed Me 3.0.0-beta.21
Feed Me Pro 3.0.4
Mandrill 1.2.0
Redactor 2.1.6
```

**Comment by MartyWallace** [comment]
This is pretty severe behaviour because updating orders after a successful transaction completely breaks (you receive an "order does not have a default status" exception, the transaction is marked successful but the order stays in "active carts").

**Comment by lukeholder** [comment]
Thanks this is fixed. Looks like this is only affecting PostgreSQL due to the way they handle DB transactions.

**Comment by MartyWallace** [comment]
Nice one thanks - nice and quick 👍
