### ISSUE TITLE
Feature request for commerce 2, error handling process when commerce user proceed as a guest

### ISSUE THREAD

**Issue by xhuang9** [craftcms/commerce#478]
### Description
This is a feature request for craft 3 commerce 2 plugin.

In 

https://github.com/craftcms/commerce/blob/84a97315a6e86d4444156f85155a90f671949e03/src/controllers/CartController.php#L236-L239
Where set the guest user email.

Is that possible to add some error handling process. When user enter an invalid or existing user email, It will return some errors. Just like the craft login action.

**Comment by lukeholder** [comment]
A user can create an order as a guest with the email of an existing user. when they log in to their account next time, any guest orders will be assigned to that user.

I could add an email address format validator?

**Comment by xhuang9** [comment]
Yeah, a format validator would be great. 
My use case is that user can enter a empty email address and still post the form, proceed to the 
next step of checkout. Although next page would request user to enter their email, if it is empty. But to my client they think that is very unecessary. I could write a jquery validate, but I figured its better trying to mention this to you guys first. Then, think of other solution.

The following point is not my issue, but worth to memtion:
And as you memtioned, a guest user would place an order using a email of existing user. What about the  billing and shipping address he/she entered when making the order? If it shows 
My solution was, 
Checking the email address registered as a existing user, if exist pop up a message to remind user to login.

**Comment by lukeholder** [comment]
@xhuang9 You are probably correct to put a sign up form in place if the carts email matches an existing user, encouraging them to log in.

I will close this ticker once I have added email format validation to orders.

Thanks

**Comment by lukeholder** [comment]
@xhuang9  Looking at the order element rules, there is already a email validator. So this should already be working. is email validation not working for you?

**Comment by xhuang9** [comment]
My case is when email is empty, user can still submit the form. I guess the email validator doesn't handle empty value.

**Comment by lukeholder** [comment]
The email can be blank while building the order, so we can't validate required.

We do validate the email address exists when submitting/paying the order.

It would be up to you to test if the email exists and redirect back to the email entry screen.

**Comment by xhuang9** [comment]
Thank for your time, I understand now. I will apply a jquery validator for that
