### ISSUE TITLE
Allow backorders

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#48]

**Comment by andrewhawkes** [comment]
@brandonkelly are there any updates on this being added? I'm in desperate need of negative stock values to allow back ordering. Are there any workarounds to allow items out of stock to be added to an order?

**Comment by andrewhawkes** [comment]
@brandonkelly @lukeholder do you have any plans for this?

**Comment by andrewhawkes** [comment]
![2Abs](https://user-images.githubusercontent.com/4975742/62301051-c28e8380-b46f-11e9-9154-76a4e0162506.gif)

**Comment by lukeholder** [comment]
@andrewhawkes there are plans for it, but was put on hold until we move to a proper inventory system which we plan to get into Commerce 3: https://github.com/craftcms/commerce/issues/44

We haven't had many people ask for it.

So, In the meantime, you have 2 options:

- (a little less hack) Enable unlimited stock for variants, and then listen to the 'on order complete' event with your own PHP handler, and deduct a qty from a variant custom field or your own SQL table counter per purchasable.

- (a hack) Set your stock count to `1000+COUNT`, the count is the actual count. Anything below 1000 would be how many back-ordered items you have. 

Hoping we could get the inventory improvements started soon.

**Comment by andrewhawkes** [comment]
@lukeholder okay, thanks for getting back. I think a custom field is going to be the better option for now. Do you have a roadmap for features and Commerce 3 etc?

**Comment by lukeholder** [comment]
Moved to discussion in #44
