### ISSUE TITLE
PayPal button suddenly included, which breaks layout/functionality.

### ISSUE THREAD

**Issue by 23d1** [craftcms/commerce#484]
### Description
The PayPal button is suddenly included below the dropdown for gateways when PayPal Express is the selected gateway.
Is there a simple way to NOT include it without hiding the whole thing with CSS?

PS.
It doesn't get included when using AJAX for some reason, which is fine, but when the page is reloaded it's there.

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.0.23.1
- PHP version: 7.2
- Database driver & version: MySQL 8.0.11
- Plugins & versions: Commerce 2.0.0-beta.9

**Comment by andris-sevcenko** [comment]
PayPal Express essentially *is* a payment button, so I'm not sure what you'd be expecting here. Either way, you simply can just not call the Gateways `getPaymentForm()` method and just supply your own code, if you want. If you're using the example templates (which should be used for getting the hang of Craft Commerce, really), it would be this line: https://github.com/craftcms/commerce/blob/develop/templates/shop/checkout/payment.html#L66

For future reference, could you please post payment gateway specific issues in the appropriate repository, so it's easier to keep track of them? For PayPal it would be the `craftcms/commerce-paypal` repository.
