### ISSUE TITLE
Can't save store location

### ISSUE THREAD

**Issue by outline4** [craftcms/commerce#486]
### Description

When I try to save the store address in "/commerce/settings/location" it just displays "Couldn’t save Store Location." at the top of the page. 
Even if I fill in all the fields (I don't have any regions). 

### Additional info

- Craft version: Craft CMS 3.0.24
- PHP version: 7.1.x
- Plugins & versions: Commerce 2.0.0-beta.9

**Comment by lukeholder** [comment]
What database (mysql or postgres) and also, do you see the error in your logs?, it might have more information.

**Comment by outline4** [comment]
Hi, 
I use mysql and didn’t spot any errors in my logs. 
I even added a region, it didn’t change…

**Comment by lukeholder** [comment]
Please email your database dump/backup to support@craftcommerce.com

**Comment by outline4** [comment]
sent via dashboard. thanks for looking into it.

**Comment by lukeholder** [comment]
Hi, I just downloaded your database and was able to save the store address without any errors using your database and Commerce 2 beta.10. I also can't find the error in the logs.

Can you give steps to reproduce.

**Comment by outline4** [comment]
Hi Luke, 

I’ve updated to beta 10. I’ve even tried to switch the language to english, I’ve added a second country.  
It always throughs an error. 



In the future, when it’ll be running: How do you use this data in the templates? 

How could I proceed if I wanted to apply a default shipping rate based on the store’s address? 

Where could I enter the store address in the database? 

Cheers  
Stefan

**Comment by lukeholder** [comment]
`craft.commerce.addresses.storeLocation` to get the store address in twig.

The store address is not updated from the front-end. The store location is not used in the built in shipping rates calculator, it is there to display on the front end or for shipping plugins to use as the origin for shipping. 

The built in shipping rules you create presume you are sending from a single location.

The address is stored in the database with all other addresses in the `commerce_addresses` table, with the store location flag set to true.

**Comment by outline4** [comment]
Hi Sorry to reopen this, but I didn’t understand some things of the answer…

> craft.commerce.addresses.storeLocation to get the store address in twig.

Thanks. 

> The store address is not updated from the front-end.
> 
That was clear for me. But I can’t save it in the backend settings.

> The store location is not used in the built in shipping rates calculator, it is there to display on the front end or for shipping plugins to use as the origin for shipping.
> 
One day: Will this be used as a default shipping cost? 


> The built in shipping rules you create presume you are sending from a single location.
> 
What does that mean in regard to the store address? 

> The address is stored in the database with all other addresses in the commerce_addresses table, with the store location flag set to true.
> 
Thanks. 
So I’ve edited an existing address in the database and set the flag to 1… Now it works. I can change the address from the backend settings and it’s saved correctly. 

What I was after: 
Why, in the first place can’t I store the shipping address from the backend?
