### ISSUE TITLE
Use rules to stop an email being sent automatically from an order status change.

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#49]
Currently all emails are sent for that status on an order status change. 

Would be good to allow the user to use twig to return true or false on whether to send that email.

This would be useful for things like order stock thresholds. A user could only send the email if the stock has fallen below a limit they have set for items on the order.

**Comment by lukeholder** [comment]
Will use expression language to enable this.

**Comment by lukeholder** [comment]
The `\craft\commerce\services\Emails::EVENT_BEFORE_SEND_MAIL` event allows you to cancel an email from being sent since Commerce 2. You have access to the order, and order history to determine if the email should be stopped by setting the event's `isValid` param to false.
