### ISSUE TITLE
The need for more hooks

### ISSUE THREAD

**Issue by nordentwickler** [craftcms/commerce#491]
### Description

Hello, 

there is real need for more hooks in the commerce CP - could you please add some?

![Image of hookwishes](https://www.evernote.com/shard/s7/sh/dea8aff6-6e0c-408b-adfb-059e5e0d32f0/8021f22fcb8c6e88/res/16e973f9-c6af-41db-a18c-e201472ab562/skitch.png)

For example, in Germany you need to generate a "refund receipt" for every single refund you do. So there should be the possibility to add a button for such file at the transaction section file.

Or most shops need "delievery-note-pdfs" which need to be generated after for example a statuts change. Or button for downloading (generating) them would be nice next to the receipt button.

Are there any plans for more hooks?

### Additional info

- Craft version: 3.0.22, 
- Commerce: 2.0.0-beta.9

**Comment by lukeholder** [comment]
Duplicated of #138
