### ISSUE TITLE
"Per Email Address Coupon Limit" feature is broken due to unique constraint on `discountId` column in `commerce_email_discountuses` table

### ISSUE THREAD

**Issue by benface** [craftcms/commerce#492]
### Description

See title.

### Steps to reproduce

1. Create a discount with a coupon code. Set "Per Email Address Coupon Limit" to 1.
2. Check out with the coupon (complete the order).
3. Check out with the coupon again (another order)
4. Boom:
```
Integrity constraint violation: 1062 Duplicate entry '4' for key 'commerce_email_discountuses_discountId_unq_idx'
The SQL being executed was: INSERT INTO `commerce_email_discountuses` (`email`, `discountId`, `uses`, `dateCreated`, `uid`, `dateUpdated`) VALUES ('**********@gmail.com', 4, 1, '2018-09-18 00:53:02', 'e7cb8899-5849-4b18-b517-6608ff5db511', '2018-09-18 00:53:02')
```

### Additional info

- Craft version: 3.0.24
- PHP version: 7.2.7
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 2.0.0-beta.9

**Comment by lukeholder** [comment]
Thanks for reporting, fixed for the next release.
