### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by olsp** [craftcms/commerce#495]
The german translations for the product interface are partly wrong or missing.

The label for "Allowed Qty" is in German "Höchstmenge" - which translates to Maximum Qty. This is confusing/misleading, since there are two inputs then (for minimum and maximum)
Then there is "Aktualisierüngsdatüm" which should be Aktualisierungsdatum.
Some error messages are not translated yet.

**Comment by angrybrad** [comment]
We'll order professional translations for all of the languages that Commerce 2 supports a week or so before it launches to ensure we have the latest strings.  Even then, we always accept pull requests to improve accuracy, etc.  Here's the German file: https://github.com/craftcms/commerce/tree/develop/src/translations/de
