### ISSUE TITLE
Workflow issues with free-only manual gateway

### ISSUE THREAD

**Issue by lazlo-bonin** [craftcms/commerce#501]
### Description

I've been implementing the new free option on the manual gateway but I've run into some issues.

- If the "free" gateway is the first in the list, I can't add any item to a new cart. I'm presuming this is because Commerce recognizes the order is above $0, and therefore the default gateway assigned to it cannot handle it. The cart gets emptied after a "Unable to update cart." flash error.

- If a user selects the free gateway on the payment page, Craft will throw a nasty exception instead of a form error or a flash error. 

From what I understand, the free check is currently implemented as a "is gateway compatible with order" check. I would suggest this check happens too early: it should only happen when the user hits "Pay" at the very end of the process, not any moment sooner. This would allow for different store workflows and templates (even though the provided example template also fails at this point).

I've alleviated some of the issue by moving the free gateway to the end of the list so it doesn't get defaulted, and hiding it from the payment page on non-zero orders. It isn't ideal, though!

### Steps to reproduce

1. Create a manual gateway and enable it only for free orders
2. Put it first in the list of gateways so it gets selected by default
3. Start a new checkout process with the example templates

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by lukeholder** [comment]
Thanks, this should now be fixed for the next release. The check is only made at the time of payment.
