### ISSUE TITLE
Can't add purchasable when options are set through an event

### ISSUE THREAD

**Issue by rjgux** [craftcms/commerce#506]
### Description

I'm listening to the `EVENT_POPULATE_LINE_ITEM` event, and setting the line item options with the following -

```
$e->lineItem->options = [
	'time' => time()
];
```

This works fine for the first purchasable I add to basket, but then if I add the same purchasable again, I get the following error -

```
Integrity constraint violation: 1062 Duplicate entry 'XXX' for key 'craf_commerc_lineitem_orderI_purchasableI_optionsSignatu_unq_idx'
```

If I add a **different** purchasable to the basket, all line items in the basket are given the same options (latest time) rather than keep the unique time when they were added to basket...

### Steps to reproduce

1. Listen to EVENT_POPULATE_LINE_ITEM event
2. Set options via `$e->lineItem->options`
3. Add multiple purchasables to the basket

### Additional info

- Craft version: 3.0.25
- PHP version: 7.2

**Comment by lukeholder** [comment]
Every time the order recalculates, the line items repopulate. This is why the time changes.

You are getting a uniqueness constraint error as you are adding the same purchasables to the cart and the optionsSignature of the 2 line items is the same.
