### ISSUE TITLE
Possibility to skip certain shipping categories for shipping rules

### ISSUE THREAD

**Issue by peirix** [craftcms/commerce#507]
It'd be nice to have certain rules apply to only one shipping category. So in addition to `allow`, `disallow` and `require`, it would help to have a fourth option called something like `skip`, so it wouldn't apply to products in those categories.

**Comment by lukeholder** [comment]
Not sure what you mean, only one rule can apply per shipping method, so skip would skip the whole rule for all the other shipping categories.
