### ISSUE TITLE
afterSave event from Order model is not triggered all the time

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/commerce#510]
### Description
So I ran into a strange issue. We use a OrderAdjuster to add some client specific discounts. This works, but only when the lineItemQty is lower than 2, anything greater will not trigger the event anymore.

So this is how we trigger our adjuster, we've added a die for testing purposes. If the qty changes to anything greater than 2, no die is triggered, no event is called. 

Steps:
Put the die in the eventlistener, try and increment the cart page from 1 to 2, a white screen appears, so the event is triggered.

Lets try 2 to 3
Comment `die` (otherwise you won't see the cart page)., refresh and now uncomment the `die`. Try and increment 2 to 3, it doesn't trigger anymore and you can increment as high as you like, but not lower than 2 because the die is triggered again.  

I've followed the event all the way to the afterSave event of the Order model, same happens here, any line item qty under 2 triggers the event, but anything higher the afterSave isn't triggered anymore, resulting in the adjuster not working properly 

```
    // Register order adjuster to update the order pricing
        Event::on(OrderAdjustments::class, OrderAdjustments::EVENT_REGISTER_ORDER_ADJUSTERS, function(RegisterComponentTypesEvent $e) {
            die;
            $e->types[] = Afas::class;
        });
```

Any idea where this strange behaviour is coming from?
### Additional info

- Craft version: 3.0.25
- PHP version: 7

- Plugins & versions: 
Commerce 2.0.0-beta.11

**Comment by lenvanessen** [comment]
Whoops, I know why, the item stock is set to 2..

**Comment by lenvanessen** [comment]
Still seems strange though that the adjusters would stop working then, because even for back-order products you should still have the same discounts in most cases

**Comment by lenvanessen** [comment]
Displaying the flash-messages actually says unable to update cart, but then it just goes ahead and updates the cart. 

Seems there is something off about the way the stock is handled in the cart. If there is no more stock you should get a more clear message, stating that that's the issue. Also I would think it would not still go ahead and update half of the cart (totals are updated fine,qty as wel,  discounts not)

**Comment by lenvanessen** [comment]
Hi Luke,

Sorry for the chaotic way of bringing this, i'll try to summarize:

You can start out by registering an event listener, for example the OrderAdjustments

```
 Event::on(OrderAdjustments::class, OrderAdjustments::EVENT_REGISTER_ORDER_ADJUSTERS, function(RegisterComponentTypesEvent $e) {
            die;
            $e->types[] = Afas::class;
        });
```

This order adjustment is called every time the cart is updated. But if you try to update an item, let's say a pair of socks, that has a stock qty of 2, and you try to set the qty to 3 in your cart, the behaviour of this orderadjuster is a bit strange (at least i think it is).

If the requested qty is higher than the stock qty, the OrderAdjuster is not called anymore, and so my custom discounts are not applied anymore. 

How can I make sure that the orderadjuster event is always fired, even when the stock isn't available?

**Comment by lukeholder** [comment]
All adjusters are not called if the cart
Is in an invalidate state. The user would
Need to reduce the qty and submit the cart again. When the cart is valid, the adjusters are run and the cart is saved. Does that make sense?

**Comment by lenvanessen** [comment]
Hi Luke,

What about backorders? We allow stock quantities to be exceeded in a order, and add a notice. In this case we'd always want the adjusters to be called, since they adjust the price.

What is the reason for not calling adjusters on an invalid cart? In our case it will become just "more invalid" than it already is, since the prices are reset to normal ones as wel (instead of the price without the discount)

**Comment by lukeholder** [comment]
Hi @lenvanessen 

Backorders are not possible in Commerce at the moment. You can only order an item if there is stock, or the stock is marked as unlimited.

The cart is validated after the user submits the changes and errors are added to the cart, and in that state, the submitted changes to the cart could make no sense.  But the cart is never saved in an invalid state, it is just returned to the user for them to make changes and attempt to save the cart again. If they reload the page, the cart is back to its original state.

You wouldn't show the totals and prices when the cart is in an invalidated state. The example templates do not show the prices when the cart is invalid.

**Comment by lenvanessen** [comment]
Hi Luke,

Makes sense. Thanks.
Just a quick question though, since this means we'll be writing our own stock-manager, two questions:
- Is there a way we can listen to a cart updated type of event so that we can make the assertions on the stock?
- We can just add the error message by calling ` Craft::$app->getSession()->setNotice(Craft::t('commerce', 'Your delivery will be delayed due to the stock levels.'));` right?

**Comment by lukeholder** [comment]
@lenvanessen 

Listening to cart update events would be the save as listening to cart (order element) save events.

Yes, you can add an error message to the session like that.
