### ISSUE TITLE
Ability to display applicable shipping options based off "estimator" address

### ISSUE THREAD

**Issue by sjcallender** [craftcms/commerce#514]
### Description
Currently, we can only get the applicable shipping methods for a cart after setting the shipping address for the cart. In order to better present accurate shipping costs _before_ a shopper adds an address (i.e., via a shipping cost calculator on a product detail page), can we have something like an `estimate shipping address` that doesn't save to the customer, just to the cart or session?

**Comment by jonathanmelville** [comment]
Yes please!

**Comment by janhenckens** [comment]
Would be super useful!

**Comment by nickcobley** [comment]
@lukeholder 
I mentioned on twitter the other day that I would like to see option to get shipping costs prior to full address being supplied. You asked me to add it in github, this FR is pretty much what I'm asking for.

In my case I have pretty simple shipping rules that mean the address is of no value to the shipping calculation, but we wanted to give pricing in the cart to maximise conversions.

Our crude workaround was to submit placeholder First and Last Name along with country ID, as we only ship to one country. 

This would give us enough to issue a shipping price in the cart. I then use conditionals to detect and remove these placeholders on the shipping page. It's far from ideal though.

Something that would allow more flexibility would be good, that allows you to provide enough information to provide the quote, Country and Postcode for example, then use it to provide a price either on the product page or in the cart. 

For me, I think this is the absolute biggest must-have feature missing from Commerce.

**Comment by lukeholder** [comment]
Current thinking is to add the following to the order model:

- EstimatedCountryId
- EstimatedStateId
- EstimatedZipCode

In the adjuster, if no address is set, then create an address model in memory based on those estimated attributes above on the order. Use that address to match the order.

Should we also use the estimated attributes for tax adjustments.

**Comment by sjcallender** [comment]
> Should we also use the estimated attributes for tax adjustments?

That would be a welcome and helpful addition, yes.

**Comment by lukeholder** [comment]
Should put an 'estimated' label on any adjustments that come from this method.
