### ISSUE TITLE
Error removing Order Statuses

### ISSUE THREAD

**Issue by DiederikVanHoorebeke** [craftcms/commerce#517]
### Description
When removing Order Statuses (`/commerce/settings/orderstatuses`), you get an error if the order status is present in the Order Status History.

### Additional info
- Craft version: 3.0.26.1
- Commerce version: 2.0.0-beta.11

**Comment by lukeholder** [comment]
Looks like we need to save the order history label and allow the relation constraint to set history status ID to null.

**Comment by lukeholder** [comment]
This should be fixed in Commerce 2. Let me know if not.
