### ISSUE TITLE
"Times Coupon Used" should work even when there's no total coupon use limit

### ISSUE THREAD

**Issue by benface** [craftcms/commerce#521]
When creating a discount with a coupon, the description for the "Times Coupon Used" field reads:

> How many times this coupon has been used, if a total coupon usage limit has been set.

It would be helpful if this field indicated how many times the coupon has been used regardless of whether a total coupon use limit has been set.

**Comment by benface** [comment]
No, I can confirm that at the moment, it only counts uses if “total coupon uses limit” is > 0 (0 being unlimited).

**Comment by nfourtythree** [comment]
Hey @benface and @importantcoding 

I have pushed an update to fix this behaviour. We are also looking to update how this works in `3.0` #1059 

This functionality will be included in `2.2`.

**Comment by nfourtythree** [comment]
Also /cc @tobyjug, sorry for forgetting to tag you!
