### ISSUE TITLE
Make trial days optional or provide method independent of plan UID

### ISSUE THREAD

**Issue by bwlng** [craftcms/commerce#524]
### Description

I have a subscription form where I'd like the user to be able to select different subscription plans. To do this, I have radio buttons w/ the plan ID.

```
<form method="POST">
    <input type="hidden" name="action" value="commerce/subscriptions/subscribe">
    {{ redirectInput('') }}
    {{ csrfInput() }}
    
    {% for plan in plans %}
        {% set fieldId = "f-#{plan.id}" %}

        <input type="radio" name="planId" id="{{ fieldId }}" value="{{ plan.id|hash }}">
        <label for="{{ fieldId }}">{{ plan.name }}</label>
    {% endfor %}
</form>
```

The above seems to work for my needs, except if I submit the form without the plan's hashed UID and 0 days for a trial, I get an error on submission.

```
2018-10-11 21:59:56 [-][2645][68e90f68cce1945cf6fcd85c39efa00c][error][TypeError] TypeError: Argument 1 passed to craft\helpers\StringHelper::countSubstrings() must be of the type string, null given, called in vendor/craftcms/commerce/src/controllers/SubscriptionsController.php on line 137 and defined in  vendor/craftcms/cms/src/helpers/StringHelper.php:117
Stack trace:
#0  vendor/craftcms/commerce/src/controllers/SubscriptionsController.php(137): craft\helpers\StringHelper::countSubstrings(NULL, ':')
#1 [internal function]: craft\commerce\controllers\SubscriptionsController->actionSubscribe()
```

After adding trialDays, it submits fine:

```
<input value="{{ (plan.uid~':0')|hash}}" name="trialDays" />
```

Is there a way to work around this if I'd like the user to be able to select their own plan and I'm not offering trials? Or if all plans can have the same number of trial days?

### Additional info

- Craft version: 3.0.25
- PHP version: 7.1.20
- Database driver & version: MySQL
- Plugins & versions: Commerce 2 Beta 11

**Comment by andris-sevcenko** [comment]
Oops. Should have been possible to omit trialDays parameter. Should work now!
