### ISSUE TITLE
Unable to install dev-develop alongside other Craft plugins

### ISSUE THREAD

**Issue by bwlng** [craftcms/commerce#526]
### Description

Attempting to require the dev-develop branch of Commerce fails because Sprout Reports, Retour, and FeedMe each require league/csv ^8.2.0. Is it possible for to lower Commerce’s version requirements for league/csv to accommodate working along side those plugins or will they each have to be updated to work on a Craft site that includes Commerce?

### Steps to reproduce

1. composer create-project craftcms/craft ./
2. composer require craftcms/commerce dev-development
3. composer require nystudio107/craft-retour

```
…
    - Conclusion: remove league/csv 9.1.4
    - Installation request for nystudio107/craft-retour ^3.0 -> satisfiable by nystudio107/craft-retour[3.0.0, 3.0.1, 3.0.10, 3.0.11, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9].
    - Conclusion: don't install league/csv 9.1.4
    - nystudio107/craft-retour 3.0.0 requires league/csv ^8.2 -> satisfiable by league/csv[8.2.0, 8.2.1, 8.2.2, 8.2.3].
    - Can only install one of: league/csv[8.2.0, 9.1.4].
```

(Note step 2 conflicts w/ Craft’s create-project command as well because the platform is set to 7.0 and the dev-development branch has dependencies that require 7.1)

### Additional info

- Craft version: 3.0.27.1
- PHP version: 7.1.20
- Database driver & version: MySQL
- Plugins & versions: craftcms/commerce dev-develop, craftcms/cms 3.0.27.1

**Comment by lukeholder** [comment]
We will be replacing league/csv with a different package for CSV export in the next dev-develop release.

**Comment by lukeholder** [comment]
updating to the latest develop branch will now use a different csv package. You can now also export in xls/xlsx and ods formats.
