### ISSUE TITLE
FR: Add Customer Addresses as a field type

### ISSUE THREAD

**Issue by bwlng** [craftcms/commerce#527]
### Description

It'd be helpful to have Customer Addresses as a field type. I’m building out subscriptions that require customer addresses. The customer can add an address while purchasing a subscription and it's associated with their user in Craft, but it's not possible to display the address on their subscription.

I'd like to add an "Address" field to the Subscription’s fields and pass the address ID when creating the subscription plan. Then the selected address would display on the subscription plan in the CP — same way its displayed as Customer Info on the User in the CP would be perfect. 

### Additional info

- Craft version: 3.0.27.1
- PHP version: 7.1.20
- Database driver & version: MySQL
- Plugins & versions: craftcms/commerce 2.0.0-beta.11

**Comment by lukeholder** [comment]
We planned to make plans purchasables, so that you can add a plan to an order to start the subscription. This would solve the address relationship requirement. Should be out in the next week or so.
