### ISSUE TITLE
PDF won't render on PHP 7.1+ when using remote images

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce#537]
### Description

This is the dompdf error:

https://github.com/dompdf/dompdf/issues/1781

TO get around this it is best to use a local volume and put the full path to the image as the image path:

```
{% set asset = craft.assets.one() %}
<img src="{{ asset.volume.rootPath ~ '/' ~ asset.path}}" width="300"/>
```

This is not need the remote images setting set to true.

**Comment by lukeholder** [comment]
Will wait for dompdf to resolve upstream.

**Comment by benface** [comment]
Hopefully this will accelerate it: https://github.com/dompdf/dompdf/pull/1821

**Comment by benface** [comment]
@lukeholder They merged it 🎉, but they also said that "notices really shouldn't break execution of the code". I don't know why it does in the Craft Commerce context (I tested my fix and it works).

**Comment by nfourtythree** [comment]
Have just verified this fix and remote images are working as expected with dompdf version `0.8.3`
