### ISSUE TITLE
In the "Tax Rate" form, the "Tax Category" field should disappear if "Taxable Subject" is not line item price and/or shipping cost

### ISSUE THREAD

**Issue by benface** [craftcms/commerce#538]
### Steps to reproduce

1. Create a Tax Rate
2. Set the "Taxable Subject" to "Order total shipping cost" or "Order total taxable price"
3. Notice the "Tax Category" field is still visible. According to @lukeholder on Slack, "If you set [Taxable Subject] to the order total the tax category option should disappear."

**Comment by nfourtythree** [comment]
@benface code has been pushed up to fix this.

Should be available in the next release.
