### ISSUE TITLE
Cancelling a subscription only gives it an 'Expired' status

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce#539]
### Description

When using the cancel a subscription form (https://github.com/craftcms/commerce-docs/blob/v2/en/subscription-templates.md#canceling-the-subscription) it seems that it doesn't give it a 'Cancelled' status, but an 'Expired'. 

Looking in the database theres also no date in the `dateCancelled` or a value in `isCancelled`.

This means when doing `{% if subscription.isCanceled %}` it doesn't pick up on it.

### Additional info

- Craft version: Craft CMS 3.0.27.1
- PHP version:  PHP 7.1
- Database driver & version: MySQL
- Plugins & versions: Commerce 2.0.0-beta.11

**Comment by andris-sevcenko** [comment]
Some subscription stuff has changed since Commerce 2.0.0-beta.11. The statuses were simplified and this whole canceling thing was fixed, too, in beta 12.
