### ISSUE TITLE
Error when canceling and reactivating Subscripton 

### ISSUE THREAD

**Issue by johnnyhawley** [craftcms/commerce#541]
### Description
Using my templates and commerce shop templates - when trying to cancel a subscription (immediately or on period end), and when reactivating a subscription via front-end, i'm getting the following error:

`Call to undefined method craft\commerce\stripe\responses\SubscriptionResponse::isScheduledForCancelation()`

I can reload the page and see that the subscription has been canceled. and if not canceled immediately i can reactivate it but I get the same error. 

### Additional info

- Craft version: 3.0.28
- PHP version: 7.2
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
Amazon SES-1.0.1
AsyncQueue-dev-master
Commerce Widgets-2.0.8
Control Panel Nav-2.0.8
CP Field Inspect-1.0.5
Craft Commerce-2.0.0-beta.12.1
Eager Beaver-1.0.4
Feed Me-3.0.0-beta.25
ImageOptimize-1.4.42
Minify-1.2.9
Order Notes-2.0.1
Retour-3.0.14
Store Hours-2.1.1
Stripe for Craft Commerce-1.0.8
Super Table-2.0.11
Typogrify-1.1.15

**Comment by brandonkelly** [comment]
Commerce 2 Beta 13 is out now with a fix for this.
