### ISSUE TITLE
Export button working intermittently

### ISSUE THREAD

**Issue by andrewcgregory** [craftcms/commerce#543]
### Description
Multiple people at our client had an issue with exporting orders. I was able to reproduce the issue on my end as well after further testing. It does not occur consistently. However, if I repeatedly try to export orders I do see the issue intermittently. When the Export dropdown is clicked and then CSV is selected, it will sometime download the file and sometimes nothing at all will happen. This has been verified in both Chrome and Firefox on Mac and PC.

### Steps to reproduce

1. Go to Commerce > Orders > All Orders
2. Click Export 
3. Select CSV

### Additional info

- Craft version: Craft Pro 3.0.28
- PHP version: 7.0.32
- Database driver & version: MySQL 5.7.24

**Comment by lukeholder** [comment]
Looks like the click event is not being triggered on some clicks on the drop down.

**Comment by lukeholder** [comment]
Did you end up having an idea @benjamindavid ?

**Comment by DiederikVanHoorebeke** [comment]
Hi @lukeholder.

I'm having the same issue. The download links only work the first time after page refresh. Trying a second time, or changing the date range, disables the download functionality. So it seems to be an JS issue.

**Comment by DiederikVanHoorebeke** [comment]
Hi @lukeholder @benjamindavid 

It looks like the `handleClickExport` isn't being called on line:
https://github.com/craftcms/commerce/blob/develop/src/web/assets/commercecp/dist/js/CommerceOrderTableView.js#L82

**Comment by DiederikVanHoorebeke** [comment]
Just found out a way to make it work. If you right click on an option, followed by a left click, it does work: https://diederikvanhoorebeke.stackstorage.com/s/vhuuLSbldsMVDNY

**Comment by lukeholder** [comment]
Thanks! Merged.
