### ISSUE TITLE
Explain relationship between subscriptions, payment sources, and addresses

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#545]
How does a customer update their address for a specific subscription? Are they able to change the address for a subscription without affecting other subscriptions?

Same question for payment sources... Let's say a users credit card expires or they just want to change the payment source. How do they go about updating it for a specific subscription? And, can they make this update without affecting the payment source of other subscriptions?

Thank you!

**Comment by dustinwalker** [comment]
I’ve also run into this question, any guidance or samples I could reference? Thanks!

**Comment by KhaledGabr** [comment]
I was able to find some code sample related to adding and deleting payment sources here:

https://github.com/craftcms/commerce/blob/aa3811bd0becfd248bbcf055ea7fc156ecfce232/templates/shop/customer/cards.html

**Comment by bryantAXS** [comment]
@andris-sevcenko any updates or documentation on this question? Thank you!

**Comment by andris-sevcenko** [comment]
> How do they go about updating it for a specific subscription? And, can they make this update without affecting the payment source of other subscriptions?

Stripe charges the default payment source for the customer. There's no way to specify a specific payment source for different subscriptions.

In the same vein, there's no address tied to a subscription. Not until we make subscriptions purchasables. Maybe some changes (such as attaching addresses to payment sources) will come to this when I'm done with https://github.com/craftcms/commerce-stripe/issues/56, but there are no guarantees.

**Comment by lukeholder** [comment]
Commerce 2.2 will address some of the questions in this issue. Please keep an eye out for the release. Hoping to also add to the docs at the same time. Closing this for now as it's not specific.
