### ISSUE TITLE
Type Error when subscribing

### ISSUE THREAD

**Issue by ryanirelan** [craftcms/commerce#547]
### Description

Error when subscribing. Customer is created in Stripe but subscription is not.

`TypeError: Argument 4 passed to craft\commerce\services\Subscriptions::createSubscription() must be of the type array, null given, called in vendor/craftcms/commerce/src/controllers/SubscriptionsController.php on line 162 and defined in vendor/craftcms/commerce/src/services/Subscriptions.php:312`

My quick and dirty work-around while developing was to set `$fieldValues` to an empty array so it would at least pass the type check. Subscriptions go through now but eh. :)

### Steps to reproduce

1. Attempt to create new subscription on front-end via similar code as in sample Shop templates
2. Get error

### Additional info

- Craft version: 3.0.29
- PHP version: 7.1.16
- Database driver & version: 5.7.22
- Plugins & versions: Commerce 2.0.0-beta.12.1

**Comment by andris-sevcenko** [comment]
This was resolved in 4d56d1b.

The new version should be out pretty soon.
