### ISSUE TITLE
Undefined Method error when canceling subscription

### ISSUE THREAD

**Issue by ryanirelan** [craftcms/commerce#549]
### Description

When attempting to cancel an order from the front-end, I get a `Call to undefined method craft\commerce\stripe\responses\SubscriptionResponse::isScheduledForCancelation()` error. The cancelation goes through on Stripe but it not reflected as canceled in Commerce. 

### Steps to reproduce

1. Subscribe to a plan
2. Attempt to cancel immediately.
3. Commerce show subscription as active while Stripe shows as cancelled. 

### Additional info

- Craft version: 3.0.29
- PHP version: 7.1.16
- Database driver & version: 5.7.22
- Plugins & versions: Commerce 2.0.0-beta.12.1

**Comment by ryanirelan** [comment]
Dupe of #541 ?

**Comment by andris-sevcenko** [comment]
Resolved in 2e637f3

**Comment by brandonkelly** [comment]
Commerce 2 Beta 13 is out now with a fix for this.
