### ISSUE TITLE
Saving element within product field error

### ISSUE THREAD

**Issue by billythekid** [craftcms/commerce#551]
### Description
I have a product field in an entry's fieldlayout. When I double-click a selected product from within the field in the entry cpEdit page and attempt to resave the product(with or without alterations) it errors out with: `error: "Call to a member function getTimestamp() on array"` in the console.

### Additional info

- Craft version: Pro 3.0.29
- Commerce version: 2.0.0-beta.13
- PHP version: 7.2.11
- Database driver & version: MySQL 5.7.24
- Plugins & versions:  

Amazon S3	1.0.8
Craft Commerce	2.0.0-beta.13
Empty Coalesce	1.0.2
Feed Me	3.0.0-beta.25
Feed Me Pro	3.0.4
Field Manager	2.0.4
Gift Voucher	2.0.2
Mandrill	1.2.0
Minify	1.2.9
Navigation	1.0.12
Redactor	2.1.6
SagePay for Craft Commerce	1.1.0
SEO	3.4.4
Video Embedder	1.1.0

**Comment by lukeholder** [comment]
And the error does not appear if you remove the product field from the entry field layout?

**Comment by lukeholder** [comment]
Let is know if this issue has persisted and I can re-open. Thanks.

**Comment by billythekid** [comment]
> And the error does not appear if you remove the product field from the entry field layout?

Apologies Luke I was sure I responded to this the other day.

If I remove the product field from the layout I won't be able to save the product through that field. It's the saving of the product after double-clicking the product in the product field that's failing for me. (I'm "in" the entry saving the product via the product field)

Hope that clears that up.
