### ISSUE TITLE
Custom shipping method with $0 value not being applied

### ISSUE THREAD

**Issue by sjelfull** [craftcms/commerce#554]
### Description

I’m having a problem with a custom shipping method that is set to $0 not being applied. Any custom shipping method with non-zero values get applied without problem.

When checking `Order->orderAdjustments`, I see that it's empty with the free shipping method, but contains an `OrderAdjustment` with a non-free one.

### Steps to reproduce

1. Create a custom shipping method with amount set to 0.00
2. Try to set order to the custom shipping method
3. Adjustment will not show up

### Additional info

- Craft version: 3.0.29
- PHP version: 7.2
- Plugins & versions: Commerce 2.0.0-beta.12.1

**Comment by sjelfull** [comment]
After digging into this further, it looks like the built in Shipping adjustment won't be applied if the amount is 0.

Is this intended? How does it handle built-in free shipping?

**Comment by lukeholder** [comment]
If no shipping costs are added to the cart, there is no adjustment made, that is correct.

It's probably not right that we aren't showing the shipping method selection in the order edit page.

You can see the selection made with `{{order.shippingMethod.name}}`. I have gone ahead and added this information to the sidebar of the order:

![image](https://user-images.githubusercontent.com/133571/48263077-da485680-e45f-11e8-9e6b-0a422a1a894f.png)

**Comment by sjelfull** [comment]
If you remove the shipping method later, will it still be saved in the order snapshot?
