### ISSUE TITLE
Default Subnav page

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce#555]
### Description

Just a minor feature request, but when you click 'Commerce' it would be good to set which sub page to go to. Currently it goes to 'Orders' by default, but a site I'm running currently only has subscriptions and no products. 

So it would be good to set 'Subscriptions' as the default view.

(Freeform do this in their settings called 'Default View')

**Comment by nfourtythree** [comment]
This has now been added and will be in the `2.2` release
