### ISSUE TITLE
Tax rate is always excluded, even without a valid Business Tax ID

### ISSUE THREAD

**Issue by rjgux** [craftcms/commerce#562]
### Description

If I go through the checkout process and add a valid Business Tax ID to the shipping address, the tax rate I have set up is taken off of the price (as expected). However, if I go through the checkout process again in same order and leave the Business Tax ID field empty, the tax rate is still taken off the price, when it should be applied.

### Steps to reproduce

1. Add item to basket, go through checkout process
2. Add valid Business Tax ID to then remove a tax rate
3. Go through the checkout process again, leave Business Tax ID empty, the tax rate is still exempt.

### Additional info

- Craft version: 3.0.30.2
- Commerce version: 2.0.0-beta.13.1

**Comment by rjgux** [comment]
Sorry, I closed this thinking that it was an issue with my templating, but this is still happening.

**Comment by lukeholder** [comment]
Please let me know if this is still happening on the latest release and I will reopen the ticket, thanks @rjgux
