### ISSUE TITLE
Should `plan.gateway.getPaymentFormHtml({})` return errors?

### ISSUE THREAD

**Issue by ryanirelan** [craftcms/commerce#564]
### Description

When using `plan.gateway.getPaymentFormHtml({})` I'm not getting any errors back when entered payment information fails. Should that method also return errors as part of the form HTML or is there something additional needed? The sample form doesn't show anything additional.

### Steps to reproduce

1. Load up the `plan.gateway.getPaymentFormHtml({})` and attempt a charge.
2. No errors returned

### Additional info

- Craft version: 3.0.29
- PHP version: 7.2
- Database driver & version: MySQL
- Plugins & versions: Commerce 2.0.0-beta.13.1

**Comment by bymayo** [comment]
I'm using the example code in the docs and it seems to be working fine - https://docs.craftcms.com/commerce/v2/subscription-templates.html#subscribing

One thing I did hit though, is that if a user exists under 'Test / Development' mode in Stripe, and you try to subscribe to a subscription that is 'Live' with the same user then the payment fails.

I got around this by checking the logs as it logged that the customer already existed in test mode. Maybe see if this is a similar issue?

**Comment by ryanirelan** [comment]
Are you using the payment form for a new subscriber and getting error messages back when the payment fails?

I’ll test again on a new template. I’m just getting a blank form back.

**Comment by bymayo** [comment]
@ryanirelan Yeah i'm including `{{ plan.getGateway().getPaymentFormHtml()|raw }}` similar to the example with no issues.

Just double check the 'customer' issue. I'd suspect it would be logged in the log though if this was the cause.

**Comment by andris-sevcenko** [comment]
Any errors will be stored as a flash error message, similar how errors are stored when paying by card.

Here's a reference: https://github.com/craftcms/commerce/blob/develop/templates/shop/_layouts/main.html#L56-L64
