### ISSUE TITLE
Server error when viewing (in)active carts in CP

### ISSUE THREAD

**Issue by DiederikVanHoorebeke** [craftcms/commerce#567]
### Description
When clicking on a (in)active cart in the CP, an Internal Server Error is triggered:

```TypeError: Argument 1 passed to craft\commerce\services\Countries::getCountryById() must be of the type integer, null given, called in /craft/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1619 and defined in /craft/vendor/craftcms/commerce/src/services/Countries.php:60```

### Steps to reproduce

1. View cart detail in CP

### Additional info

- Craft version: 3.0.29
- Craft commerce version: 2.0.0-beta.13.1
- PHP version: 7.2.10
- Database driver & version: MySQL 5.5.5

**Comment by lukeholder** [comment]
Please send your db backup/dump to support@craftcommerce.com 

Also include the number/id of the order.

**Comment by lukeholder** [comment]
Please send DB backup/dump with a reference to this issue and we can re-open. Thanks.
