### ISSUE TITLE
Add template tags for add to cart / clear cart / remove item, for speed of testing checkout

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#568]
### Description

One thing the old MultiAdd plugin did was supply some extra template tags - these are super useful to speed up the process of testing a Commerce site (e.g. checkout/regression testing).

Basically they make it super easy to set up a template that auto-fills a cart and starts you at your checkout...which is just a whole lot quicker than filling the cart by hand each time etc.

(There are other potential uses - can be used with a basic link to add bonus items to a cart in an easy way for example  - although of course there are other ways with plugins etc for that too).

Any chance you want to add these to core (since the code is pretty trivial!)

Here's the old code

```
<?php
namespace Craft;

class MultiAddVariable
{

    public function multiAddToCart($cart, $items){
    
        $error = "";

        //Must be an array of items, each being a purchasable ID and a qty
        if(!is_array($items)){
            return "Must supply an array of items, each with a purchasableId and a qty (and optionally note, options)";
        }
        else {
            craft()->multiAdd_cart->multiAddToCart($cart, $items, $error);
        }

        if($error){
            return $error;
        }
        else {
            return "Items added to cart";
        }

    }

    public function removeAllLineItems($cart){

        craft()->commerce_cart->clearCart($cart);

    }

    public function removeLineItem($cart, $lineItemId){

        craft()->commerce_cart->removeFromCart($cart, $lineItemId);

    }


}
```

....and the super simple template to make it happen:

```
{% set cart = craft.commerce.cart %}
{% set items = [] %}

{{ craft.multiAdd.removeAllLineItems(cart) }}

{% set items = items|merge([{"purchasableId":854,"qty":2, "options": {"note":"Test note"} }]) %}

{{ craft.multiAdd.multiAddToCart(cart, items) }}

{% redirect "/cart/start" %}
```

...then you just bookmark that template and forever more you can speed up your testing (and in reality I have a bunch of templates to test various different things of course - e.g. different product types get added to test different shipping methods or whatever).

**Comment by lukeholder** [comment]
```twig
{% do cart.setLineItems([]) %}

{% set lineItem = craft.commerce.lineitems.resolveLineItem(cart.id, purchasableId, options, qty, note) %}

{% do cart.addLineItem(lineItem) %}

// or if you have an array of line items:
{% do cart.setLineItems(lineItems) %}

```

**Comment by bossanova808** [comment]
See I'm not used to all these things being exposed like that. 

Sweet!  Thanks Luke!

**Comment by bossanova808** [comment]
(and you should add that to the docs somewhere!)
