### ISSUE TITLE
Disabled discounts are still applied

### ISSUE THREAD

**Issue by benface** [craftcms/commerce#576]
### Steps to reproduce

1. Create a discount that applies to any purchasable, but don't check "Enable this discount".
2. Add a product to the cart.
3. Notice the discount is being applied even though it is disabled.

### Additional info

- Craft version: 3.0.31
- PHP version: 7.2.8
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Craft Commerce 2.0.0-beta.13.1

**Comment by lukeholder** [comment]
Thanks for reporting, this has been fixed for the next release.
