### ISSUE TITLE
PHP documentation

### ISSUE THREAD

**Issue by TheFox** [craftcms/commerce#582]
Where do I find the PHP documentation, examples, best practices? It seems there is a lack of PHP documentation for this project. I don't mean the PHP API to classes or functions rather than code examples, how to achieve something.

For example here: https://docs.craftcms.com/commerce/v2/making-payments.html

This is the documentation for the frontend, but where do I find the corresponding documentation doing the same using PHP?

**Comment by andris-sevcenko** [comment]
This is a plugin for Craft CMS, not a stand-alone PHP package. You wouldn't need to write any PHP to use it.

**Comment by TheFox** [comment]
@theskyfloor But I have to use PHP, because I write a Craft module. So there is no documentation?

What do you mean by

> not a stand-alone PHP package

?

[craftcms/commerce](https://packagist.org/packages/craftcms/commerce) is a separate package, so?

**Comment by andris-sevcenko** [comment]
Right, I was not sure you were using it for Craft.

As a rule of thumb, if you want to interact with Commerce, you should be using the Service classes provided by Commerce, so the class reference is actually a good place to go to.

For more specific tips on how to accomplish certain things, Craft Slack or Stack Exchange would probably be your best bet: https://craftcms.com/community
