### ISSUE TITLE
Item notes causing table layout issues

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/commerce#583]
### Description

The item note column compresses the item title column (pictured) - this could cause friction when managing orders. I'd suggest placing the item note in it's own full-width row.

![image](https://user-images.githubusercontent.com/24975058/49011389-24bf1800-f16e-11e8-8567-02644a26a77a.png)

**Comment by lukeholder** [comment]
Fixed in Commerce 3 Alpha
