### ISSUE TITLE
Partial Payments

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce#585]
Allow partial payments on a completed order that is unpaid.

**Comment by sjcallender** [comment]
@lukeholder Per our support conversation, here's the existing FR.

**Comment by theskyfloor** [comment]
Is this not available yet in Commerce? I thought it was based on this chat from Brad in Discord:

<img width="420" alt="Screen Shot 2019-05-16 at 3 32 04 PM" src="https://user-images.githubusercontent.com/8887839/57885620-f652f900-77f0-11e9-9019-5e285dda157c.png">

**Comment by lukeholder** [comment]
Only support partial refunds at the moment. On the list for Commerce 3.

**Comment by samuelbirch** [comment]
Hey guys, 

Will this be included as part of 3.1, and if so when do you think it may get released?

We have a client requesting this feature :)

Cheers

**Comment by ryanmasuga** [comment]
Is this possible (yet)? We are upgrading a client site from Craft 2 to Craft 3 and are weighing our options between using Craft Commerce going forward for subscriptions and partial payments (vs. a service like Snipcart).

There was a comment in Discord #commerce channel around 09/07/2020: "Yeah commerce can handle multiple transactions for an order" - but I can't find any evidence that is a fact or how that works.

Partial payments and multiple transactions sound very similar, but there is no specific mention in the [Commerce CHANGELOG](https://github.com/craftcms/commerce/blob/master/CHANGELOG.md).

**Comment by samuelbirch** [comment]
I've created a PR for this feature: https://github.com/craftcms/commerce/pull/1903

**Comment by lukeholder** [comment]
@samuelbirch Thanks. This will be in Commerce 4 https://github.com/craftcms/commerce/pull/1918

**Comment by samuelbirch** [comment]
@lukeholder Would it be possible to add this into Commerce 3? or do you have an estimate when Commerce 4 will be released? - Cheers

**Comment by ivarsbariss** [comment]
@lukeholder We also have a client that would really love to see the feature added in Commerce 3 or know the estimate when Commerce 4 will be released.

Thanks for the PR @samuelbirch  - I pulled it and was able to confirm that that's exactly what we need.

**Comment by amici-infotech** [comment]
Hey @lukeholder  I have tried this with Stripe payment gateway. I can successfully pay the deposit. However, I can't pay remaining amount as that is throwing error from Stripe's endpoint. I guess because Stripe dashboard mark order succeeded. Is there any workaround for this:

![Screenshot at Mar 05 12-39-08](https://user-images.githubusercontent.com/20450552/110080422-6eb4f080-7db0-11eb-80ee-d74679aa40d3.png)

**Comment by BrandKits** [comment]
@lukeholder Just upgraded to Commerce 3.3.0-beta.1 to try this as my client has been after partial payments for ages. First payment succeeded, but I ran into the same PaymentIntent's payment_method issue. Really hope this can be resolved. Thanks.

![image](https://user-images.githubusercontent.com/38166209/114018881-a6a6cc00-9865-11eb-863e-99e69681c3e0.png)

**Comment by cole007** [comment]
Echoing this issue with Stripe (2.3.2.1) and Commerce 3 (3.2.17.3)

PHP 7.3.27

Same error/response on subsequent payment attempts (which fail):

```
This PaymentIntent’s payment_method could not be updated because it has a status of succeeded. You may only update the payment_method of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action.
```

The only solution I can think of at this stage would be to delete the specific order/transaction record from the stripe_paymentintents table but that is obviously not very sustainable/practicable long term.

**Comment by lukeholder** [comment]
Thanks everyone, looking at it now on the stripe gateway plugin: https://github.com/craftcms/commerce-stripe/issues/147

**Comment by lukeholder** [comment]
Closing this issue since partial payments is now supported in commerce core.
