### ISSUE TITLE
Save transactions so they have an ID before passing it to the gateway.

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce#586]
Transactions don't have an ID when passed to the gateway for payment processing.

**Comment by lukeholder** [comment]
The transaction hash might be enough to identify the order, but some gateways don't support such a large string.

**Comment by andris-sevcenko** [comment]
Transactions currently are intentionally immutable - once saved they cannot be modified - for the purposes of keeping an audit trail. For identifying options it's safe to use the `hash` parameter.

If that's too long, for example, I'm open to figuring out a different hash, perhaps, by using the combination of order id and microtime, but I'm against having mutable transactions.

**Comment by lukeholder** [comment]
Thanks for the input @andris-sevcenko, I agree.

If a hash is too long for the gateway we will let the gateway decide what to do.

Options include using a short version of the hash, or sending their own ID that is compatible with the gateway API.
