### ISSUE TITLE
Inactive Cart Shows Paid Date as Current Day

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#588]
### Description

Before a cart is complete, it shows up under Active and Inactive Carts. This is probably my favorite feature of Commerce because we can see how many carts are being abandoned, what is in them, etc. and possibly take action (by personally emailing a customer, etc.)

However, cosmetically it could be improved.

Paid Status shows ``Unpaid`` as expected but Paid Date is showing as the current day. That's pretty confusing. I would suggest removing it and putting in "Last Updated" .

I constantly find myself going back to the index screen wondering "when did they abandon again?" to double check the date.

It would also be great if the email address could be hyperlinked for easy outreach.

![screen shot 2018-11-26 at 4 20 59 pm](https://user-images.githubusercontent.com/3707869/49045919-0ec64d00-f198-11e8-99d2-d89d8b3ed7de.png)

### Steps to reproduce

1. View Active or Inactive Carts in Commerce -> Orders

### Additional info

- Craft version: 3.0.32
- PHP version: 7.0+

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
