### ISSUE TITLE
Misuse of `Db::parseParam(…)`?

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#591]
### Description

I'm getting an SQL error when trying to query orders by the `isPaid` and `isUnpaid` params.

It looks like the call to `Db::parseParam(…)` is actually trying to compare the string `'commerce_orders.totalPaid'`, instead of the value of another column…

```
Exception: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type numeric: "commerce_orders.totalPrice"
```

### Steps to reproduce

1. Create an `OrderQuery` via `craft\commerce\elements\Order::find()`
2. Set some properties, specifically `$orderQuery->isPaid(true)` or `$orderQuery->isUnpaid(true)`
3. Execute query

For example, this blows up in PHP:

```php
$orders = Order::find()
               ->isCompleted(true)
               ->orderBy('dateOrdered desc')
               ->isPaid(true)
               ->limit(2)
               ->ids();
```

### Additional info

- Craft version: 3.0.33
- PHP version: 7.1.22
- Database driver & version: PostgreSQL 10.5
- Plugins & versions: Commerce 2.0.0-beta.13.1

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
