### ISSUE TITLE
Ability to add a product to an already existing sale from product edit and overview

### ISSUE THREAD

**Issue by stevenvandemoortele** [craftcms/commerce#594]
At the moment you can only add a product to an existing sale by going to that sale and adding the variants. 

It would be nice if you could also add a product to a sale from the product edit page 
Clicking on the button "add a sale" automaticly creates a new sale.

Same for products on the overview page, you can select multiple products and create a new sale / discount, but there is no option to add them to an existing sale.

**Comment by lukeholder** [comment]
Thanks for the idea. It's tagged as an enhancement.

**Comment by nfourtythree** [comment]
Closed by #1177
