### ISSUE TITLE
Emails BCC not optional

### ISSUE THREAD

**Issue by TheFox** [craftcms/commerce#596]
### Description

The BCC field in Emails is actually not optional. But in the CP it is.

```
Argument 1 passed to craft\web\View::renderString() must be of the type string, null given, called in /app/vendor/craftcms/commerce/src/services/Emails.php on line 246
```

### Steps to reproduce

1. To to Settings, Emails, Create new Email and leave BCC empty.
2. Finish a new Order.

### Additional info

- Craft version: 3.0.34
- PHP version: 7.2.12
- Database driver & version: MySQL 5.5.54

**Comment by lukeholder** [comment]
Thanks for reporting the issue.
