### ISSUE TITLE
PDF Template Option variable should be mixed

### ISSUE THREAD

**Issue by TheFox** [craftcms/commerce#599]
In PdfEvent.php the $option variable should not be string. Also in Pdf.php, `renderPdfForOrder(...)` the $option variable should not be string. You can put in whatever you want to put in. Most of the time I use it as an array because I'm not using only one variable in the template.

**Comment by lukeholder** [comment]
There is now a $variables param added to 

`craft\commerce\services\Pdf::renderPdfForOrder(Order $order, $option = '', $templatePath = null, $variables = [])`

and the `variables` can also be modified before pdf render with `craft\commerce\services\Pdf::EVENT_BEFORE_RENDER_PDF`
