### ISSUE TITLE
The Attempted Payments tab is showing the same order multiple times

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#602]
### Description

When an order has multiple transactions that are not ending up in a "Paid" status, the order shows up multiple times in the Attempted Payments listing, once for each transaction.  This should most likely be a "distinct" listing.

### Steps to reproduce

1.  Make multiple failed attempts to pay an order.

### Additional info

- Craft version: Craft Pro 3.0.34
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins & versions: 2.0.0-beta.14
![2018-12-10 09_59_37-window](https://user-images.githubusercontent.com/4933333/49740907-4a1a4e80-fc63-11e8-9ec5-23d7f811c719.png)
![2018-12-10 09_59_28-window](https://user-images.githubusercontent.com/4933333/49740912-4c7ca880-fc63-11e8-885a-0fff3685f54c.png)

**Comment by lukeholder** [comment]
This looks like payment has just been attempted multiple times, as for creating new orders, could the Moneris gateway plugin be dropping the order ID before re-saving it?

**Comment by eric-chantigny** [comment]
@lukeholder @andris-sevcenko  

I think you are misunderstanding the issue.  The "attempted payment" listing seems to show the same order multiple times when there's multiple tries to pay for that same order.  I'm just saying that the listing should not show an order for each failed attempt, just display it once and it will be less confusing for the admin.  I don't want to see a listing of failed attempt, I just want to see orders with (one or +) failed attempts if not paid for.

**Comment by lukeholder** [comment]
@eric-chantigny is this still an issue?

**Comment by eric-chantigny** [comment]
@lukeholder I will do some testing and I will get back to you soon

**Comment by echantigny** [comment]
@lukeholder Yes, it is still an issue as of 2.1.2.

Each one of these entries link to the exact same detail page, in which you can see both transactions.  I really think that the listing query just needs a Distinct on it. 

![2019-03-13 14_52_40-Orders - Commerce - Great Boardgames](https://user-images.githubusercontent.com/4933333/54306492-cd6b7900-459f-11e9-95b4-64b49047441d.png)
![2019-03-13 14_52_56-Cart 440648aa6ecc0f866a64865bc2e103e7 - Great Boardgames](https://user-images.githubusercontent.com/4933333/54306494-cd6b7900-459f-11e9-943a-6638ee018983.png)

**Comment by andris-sevcenko** [comment]
@eric-chantigny  Agreed. As with all things, it's just a tad more complicated than it would appear at a glance :)
(https://github.com/craftcms/commerce/blob/develop/src/elements/db/OrderQuery.php#L810)

**Comment by andris-sevcenko** [comment]
Looking into this.

**Comment by echantigny** [comment]
@andris-sevcenko Thank you!  I confirm that this change fixes the issue.
