### ISSUE TITLE
Order Info Template not found

### ISSUE THREAD

**Issue by TheFox** [craftcms/commerce#603]
### Description

I get the following error, when editing an Order:

> craft\web\twig\TemplateLoaderException: Unable to find the template "commerce/orders/_orderInfo" in "commerce/orders/_edit" at line 54. in /app/vendor/craftcms/cms/src/web/twig/TemplateLoader.php:122

This is, for example, at http://localhost:8080/admin/commerce/orders/1

And also `commerce/orders/_addresses` is missing. And `_includes/tabs`, and `commerce/orders/_ordersDetails`, and `commerce/orders/_customFields`, and `commerce/orders/_transactions`, and `commerce/orders/_history`.

But the files exist at `vendor/craftcms/commerce/src/templates/orders`.

### Additional info

- Commerce version: 2.0.0-beta.14
- Craft version: 3.0.35
- PHP version: 7.2.13
- Database driver & version: MySQL 5.5.54

**Comment by TheFox** [comment]
Ok, I found it. The problem is this code:

```php
$view = \Craft::$app->getView();
$oldTemplateMode = $view->getTemplateMode();
$view->setTemplateMode(View::TEMPLATE_MODE_SITE);

// Render something here //
$html = $view->renderTemplate(...);

// Restore the original template mode.
$view->setTemplateMode($oldTemplateMode);
```

In my case `// Render something here //` is some PDF rendering stuff. Because this whole thing is in a `Pdf::EVENT_BEFORE_RENDER_PDF` event. When a template fails to render, the `$view->renderTemplate(...)` does not return because of the Exception. In this case `$view->setTemplateMode($oldTemplateMode);` will not restore the original mode.

**This is a design issue.**

Reading the original mode, then changing it, do something, and then restoring the mode to the original is **bad design.** This is not what you should do. You can do better. Why not using Classes instead of several if-else blocks (where template mode will be checked)?

(Ref: https://docs.craftcms.com/v3/extend/updating-plugins.html#rendering-templates)

**Comment by lukeholder** [comment]
The template mode switching is the way Craft switches between twig template rendering just as you have linked to in the docs.

If you have a new suggestion on how the rendering switch happens, please submit a ticket on the craftcms/cms repo.

But, specifically you are referring to this code:

```php
        $view = Craft::$app->getView();
        $oldTemplateMode = $view->getTemplateMode();
        $view->setTemplateMode(View::TEMPLATE_MODE_SITE);

        if (!$templatePath || !$view->doesTemplateExist($templatePath)) {
            // Restore the original template mode
            $view->setTemplateMode($oldTemplateMode);

            throw new Exception('PDF template file does not exist.');
        }

        try {
            $html = $view->renderTemplate($templatePath, compact('order', 'option'));
        } catch (\Exception $e) {
            // Set the pdf html to the render error.
            Craft::error('Order PDF render error. Order number: ' . $order->getShortNumber() . '. ' . $e->getMessage());
            Craft::$app->getErrorHandler()->logException($e);
            $html = Craft::t('commerce', 'An error occurred while generating this PDF.');
        }

        // Restore the original template mode
        $view->setTemplateMode($oldTemplateMode);
```
Found in: https://github.com/craftcms/commerce/blob/develop/src/services/Pdf.php#L74-L95

The code catches any exceptions during template render so an exception shouldn't cause the template mode to not be restored.

What are you using the `EVENT_AFTER_RENDER_PDF` to do?

**Comment by TheFox** [comment]
> But, specifically you are referring to this code

No. I referring to the official documentation: https://docs.craftcms.com/v3/extend/updating-plugins.html#rendering-templates

Not even the documentation says use try-catch.

```php
use craft\web\View;

$oldMode = \Craft::$app->view->getTemplateMode();
\Craft::$app->view->setTemplateMode(View::TEMPLATE_MODE_CP);
$html = \Craft::$app->view->renderTemplate('plugin-handle/path/to/template');
\Craft::$app->view->setTemplateMode($oldMode);
```

Why do you even have an outdated documentation at all? And if you link to some code, use at least a permanent link like https://github.com/craftcms/commerce/blob/09007fd5043806191f9070de1830a195fac3124d/src/services/Pdf.php#L74-L95

---

**Read this if you are a Craft developer from Pixel & Tonic:**

Please use more classes instead of if-else blocks. Update you documentation, then write more documentation.

**Read this if you are a Craft user or PHP developer, who relys on Craft/Craft Commerce:**

(You are fucked.)

Suppose you use this line to render a template, and everything else is like I wrote it in my second post (above):

```php
$html = $view->renderTemplate(...);
```

I would use this instead:

```php
try {
    $html = $view->renderTemplate(...);
} catch (\Throwable $exception) {
    throw $exception;
} finally {
    // Restore the original template mode.
    $view->setTemplateMode($oldTemplateMode);
}
```

This also renders your template. But when something is going wrong the Exception will first be catched and then forwarded. The `finally` block guarantees that the old template mode will be restored *before* the Exception will be forwarded using `throw $exception;`.
