### ISSUE TITLE
[Feature request] for plugins to modify lineItem object when calling saveLineItem()

### ISSUE THREAD

**Issue by xhuang9** [craftcms/commerce#608]
### Description
This is a feature request. 
Is that possible to leave a back door for plugins to programatically modify detail of lineItem Modal when calling onBeforeSaveLineItem() event. 

The event is called on: 
commerce->services->Commerce_LineItemsService.php: line 132

My situation: 
My client want to have a wholesale price that is only used for certain user group (wholesale users). The price will be totally different for every product and every client. So its literally impossible to manage it through commerce sale or discount. 

And I need to still have the retail part of the comemrce having normal price, and sales. 

### Additional info

- Craft version: 2.6.3019
- PHP version: 7.1
- Database driver & version: mysql 5.7
- Plugins & versions: craft commerce 1.2.1362

**Comment by lukeholder** [comment]
@xhuang9 

You can use the onPopulateLineitem event:

```php
use craft\commerce\events\LineItemEvent;
use craft\commerce\services\LineItems;
use yii\base\Event;

Event::on(LineItems::class, LineItems::EVENT_POPULATE_LINE_ITEM, function(LineItemEvent $e) {
    // Do something - perhaps modify the price or saleAmount of a line item , salePrice will always be price - saleAmount so you can not modify salePrice
  $lineItem->price = 2;
});
```
https://docs.craftcms.com/commerce/v2/events.html#the-populatelineitem-event

**Comment by xhuang9** [comment]
Thanks!
