### ISSUE TITLE
Payment form redirect input not used, redirected to siteUrl/homepage instead

### ISSUE THREAD

**Issue by MetaDevelopment** [craftcms/commerce#609]
### Description
I am using the default products and default dummy payment gateway, as well as the example payment form: https://docs.craftcms.com/commerce/v2/making-payments.html (only changed to use the dummy payment method).
When submitting the payment, instead of using the provided URL in the redirect-input, I am being redirected to the homepage. If I use {{ redirectInput([URL]) }} instead of an input-field with the "redirect"-name it will work (the correct redirect URL is used), so if someone could provide me with the same method for the "cancelUrl" I will be happy to use that (although the docs would need to be updated then I think).

### Steps to reproduce

1. Set up a new Craft installation and install the Craft Commerce plugin
2. Set up a checkout procedure using the examples in the Craft Commerce docs
3. Submit a payment via the dummy payment gateway

**Comment by lukeholder** [comment]
Using the redirect input is just a helper for using the hash filter:

```twig
{{ redirectInput('/shop/customer/order?number='~cart.number) }}
<!-- same as: -->
<input type="hidden" name="redirect" value="{{ '/shop/customer/order?number='~cart.number|hash }}"/>
```

You will also need to hash the cancelUrl:

```twig
<input type="hidden" name="cancelUrl" value="{{ '/shop/checkout/payment'|hash }}"/>
```

This stops people changing the urls on the front end.

**Comment by MetaDevelopment** [comment]
Thanks for your input Luke, I was able to resolve the issue using the hashed inputs. However, I did have to use {number} instead of {cart.number} in your example in the redirect URL ({cart.number} returned empty).
