### ISSUE TITLE
Missing documentation on upgrading the hooks from Craft 2

### ISSUE THREAD

**Issue by mklishevych** [craftcms/commerce#615]
### Description

There is a following line in `Changelog-v2.md`

```
- The `commerce_modifyOrderSources`, `commerce_getOrderTableAttributeHtml`, `commerce_getProductTableAttributeHtml`, `commerce_defineAdditionalOrderTableAttributes`, `commerce_defineAdditionalProductTableAttributes` hooks have been replaced by more generic Craft 3 hooks.
```

I would really appreciate if someone could tell me what hooks specifically should I use to mimic the `commerce_defineAdditionalProductTableAttributes` from Craft 2.

**Comment by andris-sevcenko** [comment]
Here's the overview for the element hooks that got converted to events, which also includes examples for your specific hook: https://docs.craftcms.com/v3/extend/updating-plugins.html#element-hooks
