### ISSUE TITLE
Product variant stock with unlimited stock becomes negative

### ISSUE THREAD

**Issue by MetaDevelopment** [craftcms/commerce#616]
### Description
When a product variant is set to have unlimited stock, the purchasable.stock property is set to 0. However, subsequent purchases of this variant are subtracted from its stock amount. Therefore, after one purchase the purchasable.stock property becomes -1, after another -2, etc.. I would expect this to remain 0.

### Steps to reproduce

1. Create a product variant with unlimited stock
2. Buy the product variant
3. Check the purchasable.stock property

### Additional info

- Craft version: 3.0.36
- PHP version: 7.1.14
- Database driver & version: MySQL 5.7.12
- Plugins & versions: Commerce 2.0.0-beta.15

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
