### ISSUE TITLE
Ability to bypass or defer consolidateOrdersToUser on login

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/commerce#617]
### Description

Currently when users login there's an event handler that assigns any previous guest orders to the user. This is superfluous for us as we don't ever have guest orders.

Could you add a config setting e.g. `consolidateOrdersToUserOnLogin` (could default to true) allowing us to conditionally bypass the feature or possibly defer it to a background task?

You added the `resaveAllCustomerOrdersOnCustomerSave` to Commerce 1 for similar reasons (which I think needs to be added to Commerce 2).

**Comment by lukeholder** [comment]
We no longer automatically consolidate orders automatically on login. Developers need to call `commerce.carts.getMergedCart()` in their templates if they want to do so. Let me know if it's working for you.
