### ISSUE TITLE
pdfPaperSize config setting not being honoured

### ISSUE THREAD

**Issue by matt-adigital** [craftcms/commerce#618]
### Description
I've set the pdfPaperSize to 'a4' and also tried 'A4' in my commerce.php config file and the pdf it's generating is still a letter size. Tried it in the '*' array and also the 'dev' array but both haven't worked. I need dimensions of 8.27 x 11.69 in but I'm still getting 8.50 x 11.00 in when opening in Adobe Acrobat Reader DC and selecting Actual Size on the dropdown.

### Additional info

- Craft version: 3.0.36
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Commerce 2.0.0-beta.15

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.

**Comment by matt-adigital** [comment]
Perfect, thank you Luke.
