### ISSUE TITLE
Fractional Quantities Feature

### ISSUE THREAD

**Issue by patryk-smc** [craftcms/commerce#619]
It would be nice to be able to sell in 1.25 and so on especially when it comes to selling items by length or weight.

**Comment by Mosnar** [comment]
Having worked on a similar scenario, I think it may make more sense to put parameters like length and width elsewhere, maybe even in an auxiliary table as a plugin. My reasoning is that someone may want to order more than one quantity of a particular length (and/or width). For example, I worked with a client who manufactured a particular piece of cut-to-length construction hardware. There were multiple models with multiple pricing configurations and there were often sets of hardware sold such that you would get a 2 of a particular length and 1 of another length (2 line items in total). We ended up building a completely custom solution in this case; however, with modern Craft principles, I think it would be relatively trivial to augment Commerce 2 to do what we needed it to do.

**Comment by patryk-smc** [comment]
I'd say it depends. I work in industry where products are sold only by length and all industry-specific POS systems track quantities with few decimal points. For use-case that you mentioned, using parameters sounds like the right thing to do.

**Comment by lukeholder** [comment]
This will be solved with #1042
