### ISSUE TITLE
customer_discountuse Table does not exist

### ISSUE THREAD

**Issue by TheFox** [craftcms/commerce#621]
In src/services/Discounts.php, line 535, `commerce_customer_discountuse` is wrong. This tables doesn't exist.

**Comment by TheFox** [comment]
Did you even test this? This is wrong since over one year. There is no table called commerce_customer_discountuse. Why do you not use `CustomerDiscountUse::tableName()` instead of writing `'{{%commerce_customer_discountuse}}'`?

Why even writing the table name from scratch when you could use the `tableName()` from each class.

**Comment by lukeholder** [comment]
Thanks for the Pull Request, we will be consistent for now and use the string version of the table name. If Craft CMS core switches to the `tableName()` we also will do so.

Fixed in 8ba233150
