### ISSUE TITLE
Duplicate Code

### ISSUE THREAD

**Issue by TheFox** [craftcms/commerce#623]
Why do you use so much duplicate code?

- For example, you always use each table name as a string, and not the `tableName()` function of each record. Why not calling this function instead of writing the same table name over and over again? Beside the mirgrations, you call `tableName()` only on 5 different places. You could reuse `tableName()` from the record classes at least at over 90 places in the code.
- Why do you not use traits? For example, you have properties in Product Record, the same properties in Product Element and the same properties in the Product Query.
- For example, in ProductQuery, function `beforePrepare()`, you have at least 20 `'commerce_products'` strings in 20 lines. Even more. You could just reuse one string for all places.

And those are just some parts I looked at. I could probably write here another 90 examples..

When writing code you shouldn't repeat yourself ([DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)). It seems like your main business is not programming. I don't want to teach you programming, but this code looks like it's written by some interns and you even sell this product.

**Comment by lukeholder** [comment]
@TheFox 

Doing a search of all table name strings yields:

- 60 occurrences within the `src/migrations` folder.

It is not good practice to put references to the `tableName()` function in any migration file, as migrations should not rely on something that might change - if we ever changes the table name in a Record, it would break old migrations.

Some of the remainder you reference could be updated to reference the `Record::tableName()` function but we are also following convention in Craft CMS core, for example: 

https://github.com/craftcms/cms/blob/882a87247f64a7f6a14c7e1924912e26300fce24/src/services/Sites.php#L1084-L1090

You will notice in most cases we are not using Record anyway, and instead write the query outselves which we found is a performance improvement.

You are welcome to use the `tableName()` in your own code, but the cost of doing a find and replace if we ever rename a table is so insignificant it is not worth making it any DRYer.

Thanks for the feedback.

**Comment by lukeholder** [comment]
BTW, I just made a commit to be consistent and use the table name string for those places with used `tableName()`

956d3632d8cc70a30710f2c25c53ca4c2c104992

Thanks :)

**Comment by brandonkelly** [comment]
@TheFox Please stop posting issues here and other Craft CMS repos if you are unable to follow the [code of conduct](https://docs.craftcms.com/v3/coc.html).
