### ISSUE TITLE
Commerce 2 Upgrade Loses Sale Variant

### ISSUE THREAD

**Issue by tokersey** [craftcms/commerce#626]
### Description

After upgrading to Commerce 2, sale associations no longer exist. A product with a related sale loses the sale connection. The sale still exists in the Promotions, but on the product "Related Sale" is empty. It requires the user to go into the promotions and reselect products. Basically, the commerce_sale_purchasables doesn't get migrated data and is empty.

### Steps to reproduce

1. Upgrade Craft from 2->3
2. Install Commerce 2 from Plugin Store

### Additional info

- Craft version: 3.0.37
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Commerce 2.0.0-beta.15

**Comment by lukeholder** [comment]
Can you send your pre-updated database to support@craftcms.com thanks.

**Comment by lukeholder** [comment]
I can reproduce this issue, and I am working on a fix.

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
