### ISSUE TITLE
Commerce Reference Tags Not Parsed

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#627]
Wasn't sure whether to stick this in the commerce repo or here, but we are in the process of upgrading a Craft 2 + commerce site to Craft 3, and I'm noticing that both the old style product reference tags (`{commerce_product:28389:url}`) and the new style (`{craft\commerce\Product:28389:url}`) are not parsed in a redactor field.

PHP 7.1.20
MySQL 5.7.23
Craft Pro 3.0.35
Redactor 2.1.7
Commerce 2.0.0-beta.14

**Comment by andris-sevcenko** [comment]
Right. Commerce probably should have a migration that takes care of this.

**Comment by lukeholder** [comment]
Added a migration that does:

```
        \Craft::$app->getQueue()->push(new FindAndReplace([
            'find' => '{commerce_product:',
            'replace' => '{product:',
        ]));

        \Craft::$app->getQueue()->push(new FindAndReplace([
            'find' => '{commerce_variant:',
            'replace' => '{variant:',
        ]));
```
