### ISSUE TITLE
Allow for a Discount that only applies to one item in the cart

### ISSUE THREAD

**Issue by RandomJo** [craftcms/commerce#628]
We have a desire to create a discount code that, when applied, will take a percentage off of a single item in the cart. Currently, we can only apply a percentage off to all qualifying items in the cart. There is a Maximum Purchase Quantity field, but that limits the number of matching items the user can have in the cart, which is not ideal. We'd like them to continue buying everything else in the same cart at the normal price and only apply the discount to one of the qualifying items.

With this, you'd need some sort of logic to determine which 1 (or X) items to choose. In our scenario, we're looking to apply the discount to the most expensive item(s). But I could see someone else wanting to apply it to the least expensive item(s).

**Comment by lukeholder** [comment]
Yes, we need to separate the product conditions as separate from the item that will be chosen to discount. Adding this to the list for 2.1.

**Comment by bartrylant** [comment]
We'd like to offer a discount on some accessories when people buy certain products. The products must be in the cart for the discount to be applied, not to those products, but to other products.
E.g.: Buy a robot mower, get a spare battery for 50% off.

The request above is to apply a discount to certain products without conditions. We would like to add a condition (product x must be in the cart to get discount on product y) to this.

**Comment by lukeholder** [comment]
Moving discussion to https://github.com/craftcms/commerce/issues/47
