### ISSUE TITLE
FR: Indicate whether a payment method is on the cart in JSON response (paymentMethodId is null)

### ISSUE THREAD

**Issue by bwlng** [craftcms/commerce#631]
### Description

I’d like to check whether a payment source has been added to the cart so I can set the payment to a saved source on the same step as the final payment w/ JavaScript. In the example templates this is accomplished with a Twig conditional.

I'm updating the cart using JavaScript – submitting the saved payment source id to the `update-cart` controller when the page is initially loaded and then the submitting to the `pay` controller when the customer clicks to pay.

In my experience, submitting the payment source id in the same request as the final payment doesn’t work. Submitting it in two steps does work, but it'd be helpful to be able to verify that the saved source is on the cart in the JSON response before allowing the customer to attempt payment. 

### Steps to reproduce

1. Update the cart with a saved payment source and log the response

```
var params = new URLSearchParams()

params.append('action', 'commerce/cart/update-cart')
params.append('paymentSourceId', paymentSource.id);
axios.post('', params, {
  headers: {
    "X-CSRF-Token" : window.csrfTokenValue,
    "X-Requested-With": 'XMLHttpRequest',
  },
})
.then((response) => {
  console.log(response)
})
.catch((error) => {
  console.log(error);
});
```

Notice that `paymentMethodId` is null in the logged response (is there another param that indicates a payment is on the cart?)

2. Reload the checkout page  and use Twig to verify the payment source is saved to the order

```
{{ cart.paymentSourceId }}
```

### Additional info

- Craft version: 3.0.36
- Plugins & versions: Commerce 2.0.0-beta.15

**Comment by lukeholder** [comment]
Hi Stephen,

The `paymentSourceId` and `gatewayId` attributes were missing from the cart’s json response. I fixed that by adding them them in for the next release. Sorry about that.

As for not being able to set the payment source ID at the time of payment, I will take a look into that now.

**Comment by bwlng** [comment]
Thanks Luke — had a chance to test out dev-develop and that does the trick.
