### ISSUE TITLE
Custom order adjustments are converted to the Discount type after migration

### ISSUE THREAD

**Issue by mklishevych** [craftcms/commerce#633]
### Description
In the current craft 2 installation we have several custom adjustments to the orders. They were saved in database with their own `type`. After the migration all of them were converted to the Discount type. 

### Steps to reproduce

1. Implement custom order adjustment in craft 2
2. Migrate to craft 3

### Additional info

- Craft version: 3.0.16
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by lukeholder** [comment]
@mklishevych 

Could you send your Craft 2 database dump/backup to us?

We will migrate to Craft 3.0/Commerce 2 and we will take a look.

We did a large refactor on how adjusters work when the Beta came out 9 months ago. I am guessing you just tried upgrading for the first time?

Send here: support@craftcms.com

Please also reference this ticket in your email. Thanks.

**Comment by mklishevych** [comment]
Unfortunately I cannot send you the dump because it contains sensitive data. However I can run the migration again and try to debug the problem. I'll let you know once I know more.

**Comment by lukeholder** [comment]
Due to the way the whole system needs to know about the types for some calculations, we have decided that custom adjusters types are not supported, all adjustments need to be either `discount`, `shipping`, or `tax`. We are looking to add new generic `price` adjustment type in the future. Let me know if you have any questions.

**Comment by samhibberd** [comment]
Hi @lukeholder is the price adjustment type, mentioned above, something that is on the roadmap (i cant find an issue / feature for it). Or is there something else planned? 

We get the logic behind losing custom adjuster types, but an adjuster to add x to a line item would be great, we currently use a positive discount, which works fine, but it pains me to see DISCOUNT in the cp view against that adjuster amount :)
