### ISSUE TITLE
Craft import (use) missing in ShippingMethod class

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/commerce#634]
### Description
The Craft class import is missing in the new craft\commerce\base\ShippingMethod class.

### Steps to reproduce
1. Use the deprecated 'myShippingMethod.getAmount()' function.
2. Open the checkout shipping page.
3. Enjoy your error.

### Additional info

- Craft version: 3.1.1
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Craft Commerce 2.0.1

Error: Class 'craft\commerce\base\Craft' not found in /Applications/MAMP/htdocs/boilerplate-craftcommerce3/vendor/craftcms/commerce/src/base/ShippingMethod.php:180

**Comment by lukeholder** [comment]
Fixed for the next release. Thanks for reporting.
