### ISSUE TITLE
Field type change to Credit Card Expiry 

### ISSUE THREAD

**Issue by emilyfitton** [craftcms/commerce#636]
### Description
Default card-expiry field in the _creditCardFields.html template needs to be a text field and not a tel field. On iOS a tel field doesn't allow you to write a / character which is required when the format for expiry is MM/YYYY

### Steps to reproduce

1. Checkout on iOS
2. Try and type 12/2020 in the CC expiry field.

### Additional info

- Craft version: 3.0.37
- PHP version: 7.2.2
- Database driver & version: MySQL 5.7
- Plugins & versions: Commerce

**Comment by lukeholder** [comment]
Thanks fixed for the next release.
