### ISSUE TITLE
Tax zones and rates are not synced with Project Config

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#637]
### Description

Tax zones and Tax rates are not synced with Project Config.
Also, the default Product Type (clothing) is not removed when importing a project.yaml without it.

### Steps to reproduce

1. Install Craft 3.1 with Commerce 2
2. Add tax zones and rates
3. Remove clothing product type
4. See nothing changed in project.yaml

### Additional info

- Craft version: 3.1.2.2
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: Commerce 2.0.1

**Comment by lukeholder** [comment]
A project config can remove a product type if the product type in the database and is not in the project config. This works the same way as entry sections in the project config. The project config is the source of truth.

We are reviewing if default data should be created in the project config on install. Will get back to you soon on this.

**Comment by echantigny** [comment]
@lukeholder I'm running into this issue too, for both Taxes and Shipping.  The problem is that if allowAdminChanges is set to false, there's no way to get into the Commerce settings portion, so no ability to modify them.

**Comment by lukeholder** [comment]
@echantigny can you make a new ticket for this?

**Comment by echantigny** [comment]
@lukeholder Just in case people stumble on this one looking for answers, the new ticket is #701

**Comment by boboldehampsink** [comment]
> At the moment Shipping and Taxes are considered "content" as we expect store administrators to need to update tax rates and shipping rates without the need for a developer to modify the project config. 

@lukeholder @andris-sevcenko It would be very handy to support his in project config anyway. Can't the `allowAdminChanges` flag be of help here? Bumping this as I keep getting annoyed by the fact that I have to add a lot of these business ruels by hand all the time, in stead of having them synced by project config (that's what it's for?)
