### ISSUE TITLE
Coupon codes not applying discount

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#648]
### Description
I added a discount (with a coupon code) in Commerce. When entering the coupon code into the cart, the discount is not being applied. I tried this in the default commerce templates. The **Cart Updated** flash message appears, but no discount is applied.

### Steps to reproduce

1. Create a new discount 
1. Add a coupon code
1. Add a base discount
1. Add items to cart
1. Enter discount code on cart and update cart

### Additional info

- Craft version: Craft Pro 3.1.3
- Commerce version: 2.0.1
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23

**Comment by lukeholder** [comment]
HI @davist11 I am unable to reproduce. Could you look into this again and let me know?

**Comment by lukeholder** [comment]
Will re-open with new steps to reproduce.

**Comment by davist11** [comment]
@lukeholder hmm, here's a screencast of the issue I'm seeing:

https://drive.google.com/file/d/1RXT-MAxDHBRmFAgy96HLT4rBHxHzP36e/view?usp=sharing

Let me know if there is any other information I can provide to help diagnose.

**Comment by davist11** [comment]
Just wanted to check back on this because we are having issues with _any_ discount applying correctly
