### ISSUE TITLE
Can't save the orderReferenceFormat field

### ISSUE THREAD

**Issue by nordentwickler** [craftcms/commerce#655]
### Description

I installed the latest version of craft and craft commerce. After activating the commerce plugin i changed the orderReferenceFormat - which worked. But than i realised, that i need to change the commerce version from lite to pro. So i've done that. Going back to the commerce settings page and i can't change the orderReferenceFormat anymore. By the way the "CMD S" shortcut is not working in the settings section.

### Steps to reproduce

1. Install craft and commerce, active commerce as test-lite-version
2. Change from lite to pro
3. Try to change the orderReferenceFormat

### Additional info

- Craft version: 3.1.4
- Craft Commerce version: 2.0.2
- PHP version:  7.2
- Database driver & version: mysql 5.7
- Plugins & versions:

![orderreferenceformat_saving_issue](https://user-images.githubusercontent.com/26166873/51751226-a1aa3780-20b4-11e9-92b3-231863146dc3.gif)

**Comment by engram-design** [comment]
Can confirm this, and did work in previous beta's. Looks like its an issue with the Settings Model using `load()` (which I didn't know about - cool!). See example:

```
$settings = new SettingsModel();

var_dump($settings->orderReferenceFormat);
var_dump(Craft::$app->getRequest()->getBodyParam('settings.orderReferenceFormat'));

$settings->load(Craft::$app->getRequest()->getBodyParams(), 'settings');

var_dump($settings->orderReferenceFormat);
```

Produces (I try to change the number from 7 to 8):
```
string(14) "{{number[:7]}}"
string(14) "{{number[:8]}}"
string(14) "{{number[:7]}}"
```

What seems odd is that the other fields save just fine (filename format, etc)

**Comment by boboldehampsink** [comment]
Also seeing this

**Comment by lukeholder** [comment]
Thanks for reporting. This is fixed for the next release.
