### ISSUE TITLE
Can't update Gateway

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#656]
### Description

When updating a Gateway it says "That handle is already in use.". Seems like it wants to create a new gateway in stead of updating it.

### Steps to reproduce

1. Add Gateway
2. Try to resave gateway with no changes

### Additional info

- Craft version: 3.1.5
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: Craft Commerce 2.0.2 and Commerce Mollie 1.1.0

**Comment by lukeholder** [comment]
Hi @boboldehampsink 

Unfortunately I can't reproduce with both `useProjectConfigFile` turned on or off.

Any more info you can provide?

Thanks,

**Comment by andris-sevcenko** [comment]
Any chance of mixed up environments? Sounds like UIDs aren't matching.

**Comment by boboldehampsink** [comment]
I specifically imported the production database to prevent this type of error. I will try to find out some more.

**Comment by andris-sevcenko** [comment]
If you're stuck, you can always submit a ticket from the dashboard widget. That should also include plenty of information for us to go on from.
