### ISSUE TITLE
Can't delete product(s) on new install

### ISSUE THREAD

**Issue by beeldr** [craftcms/commerce#657]
### Description

Installed the latest Craft version via (composer create-project etc). Installed latest version of Craft Commerce Pro trial.  It's impossible to delete (dummy) products and product types. I have tried to install in different ways with/without project.yaml. Same issue.

BTW. I can create new producttypes or products, just can't remove these items... 

TL:DR  https://www.dropbox.com/s/u755r08niv8s5r8/craft-commerce.mp4?dl=0

### Steps to reproduce

1. Commerce > products 
2. Select products > delete 

### Additional info

- Craft version: 3.1.5
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Craft Commerce 2.0.2

**Comment by angrybrad** [comment]
This has been resolved in https://github.com/craftcms/commerce/commit/750f6458ce94a93afef903b7c367f15de88bbaeb and will be included in the next release.
