### ISSUE TITLE
Error on refund: Undefined index: payment

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#658]
### Description

I'm seeing the following error on refund: Undefined index: payment

### Steps to reproduce

1. Do a refund

### Additional info

- Craft version: 3.1.5
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: Commerce 2.0.2 and Commerce Mollie 1.1.0

**Comment by lukeholder** [comment]
Needing more information, is this related to #659 ?

**Comment by boboldehampsink** [comment]
No this is not related. The message appears when doing a refund or leaving the refund field empty. It appears in a flash message.
