### ISSUE TITLE
Internal server error on refund

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#659]
### Description

I'm seeing the following internal server error when doing a refund: 

```
yii\base\ErrorException: A non well formed numeric value encountered in /app/vendor/craftcms/commerce/src/services/Payments.php:535
```

The error appears in a flash message.

### Steps to reproduce

1. Do a refund
2. Enter payment value according to locale (in my case 29,78 in stead of 29.78)

### Additional info

- Craft version: 3.1.5
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: Commerce 2.0.2 and Commerce Mollie 1.1.0

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
