### ISSUE TITLE
Class 'craft\commerce\services\App' not found

### ISSUE THREAD

**Issue by MarcelWeidum** [craftcms/commerce#660]
### Description
When updating a product type url to {productCategory.inReverse().one().uri}/{slug} the error: `Class 'craft\commerce\services\App' not found`. Worked in previous craft commerce version.

### Steps to reproduce

1. Create category 'productCategory'
2. Bind products to the category
3. Change the product type url to: {productCategory.inReverse().one().uri}/{slug}

### Additional info

- Craft version: 3.1.5
- PHP version: 7.2.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: -

### Was working before update
https://craftcms.stackexchange.com/questions/353/how-do-i-add-a-subcategory-to-the-url-slug-for-a-channel-entry

### Screenshot
![schermafbeelding 2019-01-28 om 11 51 28](https://user-images.githubusercontent.com/9413586/51831787-46b25380-22f3-11e9-9c55-725380f5414d.jpg)

**Comment by lukeholder** [comment]
Fixed in ce684161da6a80727b580562e22f148f8281bf38 on the develop branch. Will be in next release soon.
