### ISSUE TITLE
Order fields missing after upgrade to Craft 3/Commerce 2

### ISSUE THREAD

**Issue by janhenckens** [craftcms/commerce#668]
### Description
We're in the process of upgrading a Craft 2/Commerce 1 site to all the new versions and the fields I had on my orders are not there anymore. Migrations seem to be running fine, all fields are basic Craft fields (2 dates, a dropdown, plain text)

What I think might possibly be the issue is that Commerce is installed in the Lite version (installed through composer before starting the upgrade), which might be why certain things are missing?

### Additional info

- Craft version: 3.1.5
- PHP version:  7.2.10
- Database driver & version: 5.7
- Plugins & versions: 
Craft Commerce | 2.0.2
Super Table | 2.1.5.3
Freeform Lite | 2.5.10

**Comment by lukeholder** [comment]
Your order field layout should not be missing, even in Lite. Can you send your DB backup before the update for me to test and reproduce. Send to support@craftcms.com and reference this ticket.

**Comment by janhenckens** [comment]
Done!

**Comment by janhenckens** [comment]
Thanks! By the way, I also ran into https://github.com/craftcms/commerce/issues/672 with this site

**Comment by lukeholder** [comment]
The missing order field layout missing migration bug has been fixed on the develop branch of commerce.

Thanks for reporting.
