### ISSUE TITLE
Incorrect line items length on failed add to cart

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#671]
### Description
If a product cannot be successfully added to the cart (example would be a larger quantity than stock), the number of line items in the cart is incorrect on the resulting page load.

Screencast: https://drive.google.com/file/d/1SkW7TnC8JK_h-vvaWCUTxXoacZ6pv1iM/view

### Steps to reproduce

1. Change the stock of a variant to a fixed number
2. Expose the qty field on the default commerce templates
3. Enter a number larger than the stock
4. Add to cart
5. See error flash, but the number of line items in the cart says 1

### Additional info

- Craft version: Craft Pro 3.1.3
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23
- Commerce version: 2.0.1

**Comment by lukeholder** [comment]
This is the expected behavior, see: https://github.com/craftcms/commerce/issues/714 for a developer solution.
