### ISSUE TITLE
Error after adding a site when Commerce is installed

### ISSUE THREAD

**Issue by janhenckens** [craftcms/commerce#672]
### Description
When I try to add a new site on a Craft install that has the Commerce plugin enabled, the following error is thrown after hitting save:

`yii\base\ErrorException: Undefined index: name in /Users/jhenckens/Sites/commerce/vendor/craftcms/commerce/src/services/ProductTypes.php:405`

The new site is created either way.

### Steps to reproduce

1. Install craftcms/commerce
2. Add a new site

### Additional info

- Craft version: 3.1.6.1
- PHP version: 7.2
- Database driver & version: 5.7
- Plugins & versions:
Commerce 2.0.2

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this locally. Can you get in touch via support@craftcms.com and send over a DB backup and your composer.json and composer.lock files?

**Comment by janhenckens** [comment]
You're got mail @andris-sevcenko!
