### ISSUE TITLE
The “localeEnabled” element query param has been deprecated. Use “enabledForSite” instead.

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#676]
### Description
The “localeEnabled” element query param has been deprecated. Use “enabledForSite” instead.
vendor/craftcms/commerce/src/elements/db/ProductQuery.php:144

### Steps to reproduce

1. A simple Product::find() in a plugin with enabledForSite set.

```
$query = Product::find();
$query->limit = null;
$query->status = null;
$query->enabledForSite = null;
$query->relatedTo = [
    'targetElement' => $element,
    'field' => $field,
];

return $query->all();
```

### Additional info

- Craft version: 3.1.6.1
- Commerce version: 2.0.2
- PHP version: 7.2.8
- Database driver & version: MySQL 5.7.22

**Comment by lukeholder** [comment]
There is no reference to `localEnabled` in the Commerce plugin.

The deprecation you reference on Line 144 in ProductQuery would be if you had used `localEnabled` in your query at one stage.
