### ISSUE TITLE
Coupon can be applied even if no line items match

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#680]
### Description

(Commerce 1) - Have recently noticed that it will accept a coupon code even if it does not apply to any line items (due to conditions - e.g. no products of the right type in the cart) - once applied,  the discount is then shown as $0.  

I presume this then prevents folks from later using that code again (if a limit of once per customer is set, for example).  

Pretty sure this used to not be the case...but can't be 100% sure

### Steps to reproduce

1. Create a coupon code (say for 10% off) and limit to one product type
2. Add no products of that type to your cart, but add some other products
3. Apply coupon code.  It is accepted with $0 discount.

### Additional info

- Craft version: V2, latest release
- PHP version: 7.0
- Database driver & version: MySQL 5.7
- Plugins & versions: Commerce1, latest release

**Comment by lukeholder** [comment]
Going to have leave this one as it is, as nothing changed super recently, and we won't be changing the behavior of Commerce 1 at this point. Thanks. 2/
