### ISSUE TITLE
Same to issue #417 but in commerce version 2.0.4

### ISSUE THREAD

**Issue by xhuang9** [craftcms/commerce#686]
### Description
Noticed a new feature, where you can see trashed products in control panel. They will still remain in the system as if you have deleted them. This created a same problem as the issue #417 .

I have a broken product, I can't restore it and I can't delete it as well. It prevent me from adding a new product with same sku.

**The reason my product is broken probably because:** 
I called event EVENT_BEFORE_SAVE_ELEMENT and ran some checks on it. However, my function throughs and exception so it breaks the process. Then the product becomes a pending product. I have no way to set it to live easily in control panel. I decide to delete it. Then it went into trash. 

### Steps to reproduce

1.  call event EVENT_BEFORE_SAVE_ELEMENT and make the event function throw an exception
2.  the product should be in pending status
3.  delete the product
4.  try to restore product, it should throw and unknown error
5.  Can't recreate the product since the sku is taken, and can't perminate delete the trashed product as well.

### Additional info

- Craft version: Craft Pro 3.1.8
- PHP version: 7.1.23
- Database driver & version: MySQL 5.7.24
- Plugins & versions: 2.0.4

**Comment by lukeholder** [comment]
Can you try to restore the product then send your logs and DB dump to support@craftcms.com thanks.

**Comment by lukeholder** [comment]
Should be fixed in the latest release due to variant validation and date published issues.
