### ISSUE TITLE
InvalidConfigException when disabling a product (with 2 or more sites)

### ISSUE THREAD

**Issue by klemenb** [craftcms/commerce#687]
### Description

We are unable to disable a product when Craft has more than 1 site. In production we have this issue on an instance with 3 sites, but the bug can be simulated easily with a fresh installation.

Saving fails with InvalidConfigException thrown at https://github.com/craftcms/commerce/blob/develop/src/elements/Variant.php#L314.

### Steps to reproduce

1. Install a fresh Craft CMS with Craft Commerce
2. Create a dummy secondary site
3. Try to disable one of the example products (toggle "Enabled" switch to off and press Save)

### Additional info

- Craft version: 3.1.7
- Craft Commerce version: 2.0.4
- PHP version: 7.2 / 7.3

**Comment by martinleveille** [comment]
We also have this issue with a 13 sites instance of Craft 3.1.8 / Commerce 2.0.4.

**Comment by AlanOne** [comment]
Pull request for #683 seems to fix the issue of disabling products with multiple sites.

But the same error is thrown when trying to disable the product per site when there are at least three sites and the product is globally enabled but is disabled on two sites.

 ### Steps to reproduce
* Install a fresh Craft CMS with Craft Commerce
* Apply the fix from #683
* Create at least 2 dummy secondary sites
* Try to disable one of the example products on two different sites (toggle "Enabled for site" switch to off and press Save)

### Additional info
* Craft version: 3.1.12
* Craft Commerce version: 2.0.4
* PHP version: 7.2 / 7.3

Additionally when a product is disabled on two or more sites the same error is thrown when trying to create a new discount tied to specific product variants (the UI displays "An unknown error occurred." after clicking the button "Choose").

**Comment by lukeholder** [comment]
Is this still an issue on 2.1.2 @AlanOne @martinleveille @klemenb ?

**Comment by martinleveille** [comment]
@lukeholder With the latest version of everything, things looking good.

In fact, my issue was resolved with your commit resolving #683 that was released in the 2.1.0 version.

**Comment by lukeholder** [comment]
Great, yes assumes it was in 2.1.x. 

Closing this ticket. @AlanOne please submit a new ticket if it is different.

**Comment by AlanOne** [comment]
Can confirm the issue was resolved.

Thanks.
