### ISSUE TITLE
Migration errors Craft 2 -> 3.1 with Product Type templates

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#691]
### Description

Migrating from Craft 2, Commerce 1 all the way to Craft 3.1, Commerce 2.

There is an error with migration of the product type templates.

Craft 2 tables before migration:

![image](https://user-images.githubusercontent.com/731309/52383584-1d9d7a00-2ace-11e9-9c7e-ad41a6bcd0c5.png)

Result after migration:

![image](https://user-images.githubusercontent.com/731309/52383603-2db55980-2ace-11e9-9364-81cf3a650bf0.png)

### Steps to reproduce

1. Use my db previously sent
2. Run migration
3. Check the tables :)

### Additional info

Composer update run this morning, so latest of all.

(Putting this here so it doesn't get lost - thanks Luke!)

**Comment by bossanova808** [comment]
The issue is specifically this migration:

`m170616_154500_productTypeSites_upgrade migration` 

I've traced it through...I _could_ do a fix but since I don't do any multi site stuff it is probably better if you look at it Luke :)

As it stands, the inner loop will cause all product types to get the template/hasUrls of whatever the last product type is...and indeed, this is precisely what happens with my migration.

A lot of folks won't have noticed this, because likely they use just one template for all products.

Here's the last iteration from the loop, where it is incorrectly setting the template to that of the last product type - caught red handed, as it were ;)

```
    > update in {{%commerce_producttypes_i18n}} ... done (time: 0.004s)
in inner loop with 4
About to update table for id 4 with: 
array(9) {
  ["id"]=>
  string(1) "4"
  ["productTypeId"]=>
  string(1) "4"
  ["siteId"]=>
  string(1) "1"
  ["urlFormat"]=>
  string(30) "products/epson-printers/{slug}"
  ["dateCreated"]=>
  string(19) "2015-11-05 05:56:06"
  ["dateUpdated"]=>
  string(19) "2019-02-07 06:24:59"
  ["uid"]=>
  string(36) "7e68aba7-01b4-4a32-83cd-e72f5847e23b"
  ["template"]=>
  string(10) "_site/page"
  ["hasUrls"]=>
  NULL
}
```

**Comment by lukeholder** [comment]
Thanks for looking into it. Working on the fix now.

**Comment by bossanova808** [comment]
If no one else ahs hit this, you can close.  I wrote some manual migration code to solve it, and have now migrated over, so no longer relevant to me at least...

**Comment by lukeholder** [comment]
Haven't had any other reports of this. I think it may have been fixed through another issue.
