### ISSUE TITLE
Error: Call to a member function getExtendedForeignKeys() on null when upgrading from Commerce 1 to 2

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#692]
### Description
I am upgrading a website from 2 to 3 and one of commerce's Migration fails saying this:
Error: Call to a member function getExtendedForeignKeys() on null
Migration: craft\commerce\migrations\m170725_130000_paymentmethods_are_now_gateways
Output:
Exception: Call to a member function getExtendedForeignKeys() on null 
### Steps to reproduce

1. Update Craft and Commerce

### Additional info
- Craft version: 3.1.8
- Commerce Version: 2.0.4

**Comment by Sam-Black-0013** [comment]
@lukeholder  please i need help

**Comment by andris-sevcenko** [comment]
Can you send the database dump to support@craftcms.com and reference this issue? You can dump only structure to avoid sending over some sensitive info.
