### ISSUE TITLE
Shipping Methods and Project Config

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#698]
### Description
We have enabled project config, but are unable to edit shipping methods and rules in the CP and received the following message when visiting the settings section of the CP:

```
Unauthorized
Administrative changes are disallowed in this environment.
```

But, based on the <a href="https://docs.craftcms.com/commerce/v2/project-config.html">documentation</a>, shipping methods and rules are considered content and should be editable in the control panel.

### Steps to reproduce

1. Enable project config
1. Visit Commerce > settings
1. See unauthorized error 

### Additional info

- Craft version: Craft Pro 3.1.7
- PHP version: 7.0.32
- Database driver & version: MySQL 5.7.25
- Commerce version: 2.0.4

**Comment by lukeholder** [comment]
Only admins or users with the `commerce-manageShipping` permissions can edit shipping method.

Do you have one of those permissions?

**Comment by davist11** [comment]
Yes, it is an admin account

**Comment by echantigny** [comment]
Issue #701 relates to this to, but also adds the taxes in the mix.  Basically, the whole Settings section is locked behind "adminChanges".

**Comment by lukeholder** [comment]
Marking as Duplicate #701
