### ISSUE TITLE
Integrity constraint violation after deleting order in CP and then customer attempts to add to cart

### ISSUE THREAD

**Issue by johndwells** [craftcms/commerce#700]
### Description

If a visitor's cart is deleted from the CP, and then the visitor attempts to add an item to their cart, An Integrity constraint violation is thrown, with a duplicate entry for key `commerce_orders_number_unq_idx`.

This is happening just after having updated from:

Craft: 3.0.40
Commerce: 2.0.0-beta.15

### Steps to reproduce

1. Visit front-end, add item to cart
2. Visit back-end, delete cart
3. Visit front-end, attempt to add item to cart
4. Exception is thrown

### Additional info

- Craft version: 3.1.8
- PHP version: 7.2.14
- Database driver & version: MySQL 5.5.5
- Commerce version: 3.0.4

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.

**Comment by portnull** [comment]
I have the same bug just now…
