### ISSUE TITLE
License downgraded from Pro to Lite after update

### ISSUE THREAD

**Issue by dozzed** [craftcms/commerce#706]
### Description

After updating from beta release to 2.0.4 the license automatically downgraded to the lite version. On the plugin page the status of the plugin is "Installed as trial" from the lite version. The Pro version has the status of "licensed". Whenever I click on "reactivate" the request just keeps hanging. The console then gives me the following errors:

```
/index.php/admin/actions/plugins/switch-edition:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

axios.js:909 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (axios.js:909)
    at e.exports (axios.js:879)
    at XMLHttpRequest.s.(anonymous function) (https://www.domain.com/cpresources/16df344e/axios/axios.js?v=1549968365:1:6183)
```

Currently no orders can be processed since shipping method is a requirement and the lite version doesn't allow it.

### Steps to reproduce

1. Update to Craft CMS 3.1.5 & Commerce 2 from Cms 3.0.40 and Commerce beta

### Additional info

- Craft version: 3.1.5
- PHP version: 7.0
- Database driver & version:
- Plugins & versions: 2.0.4

**Comment by lukeholder** [comment]
Are you using the project.yaml config? Try changing the edition to Pro there:

```yaml
plugins:
  commerce:
    edition: pro
```
