### ISSUE TITLE
Add code / handle to tax rates

### ISSUE THREAD

**Issue by leevigraham** [craftcms/commerce#707]
### Description

It would be great if tax rates had a code or handle in addition to name.  Why? Some integrations require a code when invoices are created.

Example: https://developer.xero.com/documentation/api/types#TaxTypes

![image](https://user-images.githubusercontent.com/25124/52633001-33b89980-2f17-11e9-9d24-de8deb289581.png)

**Comment by nfourtythree** [comment]
Have just pushed up code to allow tax rates to have a `code`. Will be included in the `2.2` release.
