### ISSUE TITLE
Abandoned Composer dependency "dannyvankooten/vat.php"

### ISSUE THREAD

**Issue by ccchapman** [craftcms/commerce#708]
`dannyvankooten/vat.php` is an abandoned composer dependency. Looks like it has been [renamed per the v2.0 release](https://github.com/ibericode/vat/pull/20).

Consider replacing with `ibericode/vat`.

https://github.com/craftcms/commerce/blob/db18a1bc734c7198c863b5a1e85d9e91cfdd425c/composer.json#L26

**Comment by lukeholder** [comment]
2.0 requires PHP 7.1, will need to leave as is for now. Will leave ticket open as enhancement.

**Comment by ccchapman** [comment]
@lukeholder We don't need to upgrade to 2.0 right this moment, the same `^1.1.2` releases are available under the new package name.

**Comment by lukeholder** [comment]
Ah, got it, thanks.

**Comment by boboldehampsink** [comment]
+1

**Comment by ccchapman** [comment]
This was fixed in https://github.com/craftcms/commerce/commit/08eed451fa868ff682fe944e3fa9da1056bae0d3.
