### ISSUE TITLE
Order elementIndex view

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#712]
When you show a lot of table columns on the orders elementindex view, more than the space of your screen will allow to be visible, then this pushes the width greater than the view and without the horizontal scrolling ability, you cant view the content. - It doesn not behave in the same way as the default elementIndex which stacks when run out of room.

**Comment by lukeholder** [comment]
I am unable to reproduce, I have all all available fields on, and it is stacking correctly:

https://jmp.sh/HwyIGtw

Let me know if I need to do anything special to reproduce.
