### ISSUE TITLE
LineItem validation during add to cart

### ISSUE THREAD

**Issue by johndwells** [craftcms/commerce#714]
### Description

We are attempting to add custom validation to a line item to prevent it from being added to the cart under certain circumstances. We are attempting this by hooking into the `LineItem::EVENT_BEFORE_VALIDATE` event:

```
Event::on(LineItem::class, LineItem::EVENT_BEFORE_VALIDATE, function(Event $event) {
   $lineItem = $event->sender;

   $lineItem->addError('customError', 'Unavailable for purchase');
   $event->isValid = false;
});
```

When this code is in place, and we submit an add to cart form from the product's page, we are brought back to the product, and there is a flash error "Unable to update cart".  Our error has also properly been added to the cart's array of errors. This is expected behavior.

Yet when the response comes back from the form POST, the item _appears on the cart_. It's only for this one request, because if you visit the cart page on another request, it will not contain the item.

I have seen this similarly if you attempt to add an item to the cart which is out of stock.  The user is redirected back to their previous page, with an error on the cart, and yet the product is still on the cart _for that one time_.

### Steps to reproduce

1. Put above code into a plugin/module `init()`
2.Visit single product page, click "add to cart"

### Additional info

- Craft version: Craft Pro 3.1.9.1
- PHP version: 7.2.14
- Database driver & version: MySQL 5.5.5
- Craft Commerce version: 2.0.4

**Comment by lukeholder** [comment]
I can see how this behavior would be confusing.

Let me explain using entries. When creating an entry in the control panel, if you created 5 NEW matrix blocks, and save, if the matrix blocks have errors, they are returned to the screen and you have a total of 5 matrix blocks still (just not saved to the database). If you close the page without saving those matrix blocks are gone.

It is the same way with line items.

If you update the qty of a line item to be above the available stock, the line item is returned with an error, but the qty field still has the wrong amount in it for the customer to fix based on the error.

This is probably the correct behavior for editing line items.

As for adding things to the cart, we should probably stop the item being added to the cart as a line item in the first place, I just need to think about how best to provide a hook into stopping that, and also if we place an error on the order model still.

**Comment by johndwells** [comment]
Thanks for the explanation - that definitely makes sense. And I can see how the right solution is a bit tricky! But right now the fact that a cart "momentarily" contains the item isn't right.

**Comment by lukeholder** [comment]
We have decided to leave the functionality as it is, but recommend if you want to see the `totalQty` or total line items of the cart in it's *non-error* state, simple use code like this to retrieve the order in it's original persisted state (where it makes sense):

```
<i class="fa fa-shopping-cart"></i> {{ "Cart"|t }} <span class="badge">{{ craft.orders.number(cart.number).one().totalQty }}</span>
```

**Comment by johndwells** [comment]
So if we want the persistent, non-error version of a user's cart, this seems to be the "best way" to set `cart`:

```
{% set cart = craft.orders.number(craft.commerce.carts.cart.number).one() ?? craft.commerce.carts.cart %}
```

Still feels awkward but I completely get what's going on.  This seems to be a case well worth documenting...

Thanks Luke.
