### ISSUE TITLE
Error thrown when trying to save a new product with the same SKU as a deleted one.

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#718]
### Description

I'm getting this issue when trying to create a new product with the same SKU as a deleted one:

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ANT-001' for key 'craft_commerce_variants_sku_unq_idx'
The SQL being executed was: INSERT INTO `craft_commerce_variants` (`id`, `productId`, `sku`, `price`, `width`, `height`, `length`, `weight`, `minQty`, `maxQty`, `stock`, `isDefault`, `sortOrder`, `hasUnlimitedStock`, `dateCreated`, `uid`, `dateUpdated`) VALUES (8982, 8981, 'ANT-001', '11', NULL, NULL, NULL, NULL, NULL, NULL, 11, 1, 1, 0, '2019-02-16 00:29:15', '26ea3657-ea58-4b1c-b638-1a3855e05a12', '2019-02-16 00:29:15')
```

### Steps to reproduce

1. Start with a fresh Commerce Install
2. Delete the `A New Toga` product - SKU `ANT-001`
3. Create a new product with any values, but with `ANT-001` as the SKU.
4. Error above thrown.

### Additional info

- Craft version: Craft CMS 3.1.6.1
- PHP version: 7.0
- Database driver & version: MySQL
- Plugins & versions: Commerce 2.0.4

**Comment by lukeholder** [comment]
Fixed for the next release.

**Comment by engram-design** [comment]
Thanks @lukeholder!
