### ISSUE TITLE
Include tax total and shipping total in Order export

### ISSUE THREAD

**Issue by RandomJo** [craftcms/commerce#719]
### Description

My client's accountant needs a way to reconcile all of the sales tax charged each year. Currently there is no built-in way to export that information for orders. It looks like the Order export feature that is built in does no joining of other tables so we don't get any information about how much of the order total was for tax and how much was for shipping.

We were able to solve this by writing custom queries with Sprout reports, but it feels like this should be a common need for any ecommerce business. For our purposes, we just need a shipping total and a tax total for each order, but others may need to see different types of taxes split out.

I know that we're running a bit behind with Craft Commerce, but I didn't see anything related to this in the release notes. If this has been addressed in a newer version, please let me know. We're about to upgrade shortly to take advantage of some of your recent changes.

### Additional info

- Craft version: Craft Pro 3.0.29
- Commerce version: 2.0.0-beta.13.1

**Comment by lukeholder** [comment]
@RandomJo Looks like we should add an order details CSV export that includes line items and adjustments. Add it to the list.

**Comment by boldenamsterdam** [comment]
Hi @lukeholder any status update on this topic when this can be expected?

**Comment by nfourtythree** [comment]
This has been completed and will be included in the next `2.2.x` release.
