### ISSUE TITLE
Order products/variants by salePrice

### ISSUE THREAD

**Issue by janhenckens** [craftcms/commerce#721]
### Description
It is currently not possible to order variants by salePrice.

Its would be useful when the customer the option to sort products by price and the view contains products on sale. When ordering by price, those show up on the position of their price but the actual price the customer has to pay is lower and is also displayed.

### Additional info

- Craft version: 3.1.12
- PHP version: 7.2.10
- Database driver & version: 
- Plugins & versions: Commerce 2.0.4

**Comment by nilsenpaul** [comment]
Any news/ETA on this? As of today, I have 3 shops waiting to use this function ;)

**Comment by lukeholder** [comment]
Added it to the 3.0 milestone.

**Comment by lukeholder** [comment]
This will be done with #1041
