### ISSUE TITLE
Expired subscription reports status as 'Trialing' if trial was in place

### ISSUE THREAD

**Issue by shornuk** [craftcms/commerce#723]
### Description

Setting up a new subscription with a free trial in place. After the free trial period, payment attempted and failed. After Stripes retries, the subscription is marked as expired. The subscription is Craft has `isExpired` set to `1` but `subscription.status` returns `Trialing` rather than `Expired`.

### Additional info

- Craft version: 3.1.10
- PHP version: 7.1.25
- Commerce: 2.0.4

**Comment by lukeholder** [comment]
Sounds like a bug, will look into it.

**Comment by lukeholder** [comment]
Commerce no longer has a Trialing status, and `Subscription::isOnTrial()` will now return false if it is expired.
