### ISSUE TITLE
Order screen does not load if a product is disabled

### ISSUE THREAD

**Issue by martywallace** [craftcms/commerce#726]
### Description

When attempting to load an order in the dashboard, it will 500 attempting to load a product associated with one of the variants attached to that order.

> yii\base\InvalidConfigException: Invalid product ID: XXXX in /.../vendor/craftcms/commerce/src/elements/Variant.php:314

Re-enabling a product resolves the problem.

### Steps to reproduce

1. Create an order.
2. Disable the product associated with the order.
3. Attempt to view the order.

### Additional info

- Craft version: 3.1.8
- Commerce version: 2.0.4
- PHP version: 7.2
- Database driver & version: Postgres 9.6

**Comment by lukeholder** [comment]
This has been fixed on the develop branch. if you update commerce in composer.json to `dev-develop` as the version and do a `composer update` on your project, you will get the latest code.

Or you can wait for the next release.

Thanks.
