### ISSUE TITLE
Trying to get disabled product from a variant throws error

### ISSUE THREAD

**Issue by i-just** [craftcms/commerce#727]
### Description

Trying to get disabled product from a variant throws error in both control panel and when trying to visit the page. Re-enabling a product resolves the problem.

### Steps to reproduce

1. I have some products with multiple variants
2. On one of the pages, I have a "commerce variants" field.
3. Variants of multiple products were added to the page and all worked as expected. 
4. After a while some products (which variants are added to the page) got disabled. 
5. Now, when trying to visit the page or edit it in the control panel the following exception is thrown: 

```
Invalid Configuration – yii\base\InvalidConfigException
Invalid product ID: XXXX
in vendor/craftcms/commerce/src/elements/Variant.php at line 314
```

### Additional info

- Craft version: 3.1.12
- PHP version: 7.1.23
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Craft Commerce Pro 2.0.4

I have been able to temporarly fix this issue for the front-end, by changing how I get the product information from the variant. 
The old way was: `$variant->product` (where `$variant` is `craft\commerce\elements\Variant`). 

The new/temporary way is:

    $product = Commerce::getInstance()->products->getProductById($variant->productId);

and then checking if the product is enabled (`$product->enabled`).

Most likely the same issue as [https://github.com/craftcms/commerce/issues/726](https://github.com/craftcms/commerce/issues/726)

**Comment by lukeholder** [comment]
This has been fixed on the develop branch. if you update commerce in composer.json to `dev-develop` as the version and do a `composer update` on your project, you will get the latest code.

Or you can wait for the next release.

Thanks.

**Comment by abrunovski** [comment]
Same error when trying to disable product for all sites on multi-site store.
You can disable product only for one site, then error appears when you trying disable same product but for other site
