### ISSUE TITLE
Product's "Available for purchase" checkbox state doesn't persist

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#728]
### Description

Product's "Available for purchase" checkbox state doesn't persist

### Steps to reproduce

1. Create a product
2. Go to product and tick of "Available for purchase"
3. Save
4. See checkbox checked again after page reloads

### Additional info

- Craft version: 3.1.12
- PHP version: 7.3.2
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: Commerce dev-develop

**Comment by lukeholder** [comment]
Unable to reproduce, see my video: https://jmp.sh/MQKXlBy

Let me know if there is anything special about your setup.

**Comment by boboldehampsink** [comment]
Ah. As stated in "Plugins & version", I use the development version of Commerce. This means the plugin version is stored as `dev-develop`. This is breaking the following code:

https://github.com/craftcms/commerce/blob/develop/src/elements/db/ProductQuery.php#L535

Which is the cause of this issue ;-) Eagerly awaiting Commerce 2.0.5
