### ISSUE TITLE
Cannot disable shipping rule

### ISSUE THREAD

**Issue by RandomJo** [craftcms/commerce#735]
### Description
When I try to disable a shipping rule, I get an error message saying the rule can't be saved. I see a "Couldn't save shipping rule" error message when I try to save the rule.

### Steps to reproduce

1. Go to Commerce Settings > Shipping Methods > [Shipping Rule] to edit an existing already enabled rule.
2. Uncheck "Enable this shipping rule."
3. Save the rule.
4. You should see the error message pop up.

### Additional info

- Craft version: Craft Pro 3.1.12
- PHP version: 7.2.15
- Database driver & version: MySQL 5.7.19
- Craft Commerce version: 2.0.4

**Comment by lukeholder** [comment]
Should be fixed in 2.1, let me know if not.
