### ISSUE TITLE
Shipping method number and total shipping adjustments don't match

### ISSUE THREAD

**Issue by RandomJo** [craftcms/commerce#736]
### Description

Screenshot: https://www.evernote.com/l/AT8xxaD63vJPtJBGQ6LbbZVQB7lm7b9OviA

We're using the following to get the shipping method amount:
`{{ method.amount|commerceCurrency(cart.currency) }}`

And we're using the following to get the order summary shipping total:
`{{ cart.adjustmentsTotalByType('shipping')|commerceCurrency(cart.currency) }}`

We are not using any custom adjuster, but the shipping adjustment total does not equal the chosen shipping method's amount. The system only ever picks one shipping rule, correct, so shouldn't these match up?

### Steps to reproduce

1. Create a shipping method.
2. For Rule 1, set Maximum Order Total Value to 100 and Base Rate to 10.
3. For Rule 2, set Minimum Order Total Value to 101 and Base Rate to 20.
4. Add over $100 worth of items to the cart and proceed to checkout.
5. Once on the payment step, check the shipping method amount versus the cart shipping adjustment total.

### Additional info

- Craft version: Craft Pro 3.1.12
- PHP version: 7.2.15
- Database driver & version: MySQL 5.7.19
- Craft Commerce version: develop branch at #8e192f50e1549d37a831266b412ae7c0dc792d9c

**Comment by lukeholder** [comment]
Can you try `{{ method.getPriceForOrder(cart)|commerceCurrency(cart.currency) }}` and let me know if that gives you the right amount. Thanks.

**Comment by glitchedmob** [comment]
I work with @RandomJo and she had me try your suggestion. We updated to the newly released Craft 2.1 and replaced `{{ method.amount|commerceCurrency(cart.currency) }}` with what you suggested and it works great now. You should be good to close this issue.
