### ISSUE TITLE
Editing a promotion containing a disabled product causes error

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#744]
### Description
If you attempt to edit a promotion that contains products which have since been disabled it yields a system error

### Steps to reproduce

1. Create a promotion and assign some products to it
2. Disable one of the products
3. Attempt to edit the promotion

### Additional info

- Craft version: Craft Pro 3.1.13
- PHP version: 7.1.26
- Database driver & version: MySQL 5.5.62
- Plugins & versions:
Colour Swatches	1.2.0
Contact Form	2.2.3
Contact Form Extensions	1.0.12
Craft Commerce	2.0.4
Feed Me	3.1.8
Feed Me Pro	3.0.4
Help	2.0.0
Imager	v2.1.4
Incognito Field	1.0.0
Many to Many Field Type	1.0.2.2
More Unleashed	1.0.0
PayPal for Craft Commerce	1.0.0.1
Recently Viewed	1.0.2
Redactor	2.1.7
Relabel	1.2.2
Retour	3.1.2
Schematic	4.1.0
SEOmatic	3.1.38
Similar	1.0.5
Smart Map	3.2.1
Stamp	2.1.0
Stripe for Craft Commerce	1.0.10
Super Table	2.1.9
Typed link field	1.0.17
Units	1.0.3

**Comment by lukeholder** [comment]
Should be fixed in 2.1, let me know if not.
