### ISSUE TITLE
Set shipping costs to zero for matching products for discounts does not work

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#745]
### Description
I created a discount coupon to set shipping costs to zero, but setting this "Set shipping costs to zero for matching products" does not work.
I checked the "Free Shipping" checkbox in the product page, and added that product only to the cart, but did not work.
I opened all conditions for the discount, but did not work.

**Comment by ccchapman** [comment]
Per our discussion on Discord, this appears to be resolved as an unreleased feature https://github.com/craftcms/commerce/commit/1c2ab411480ca1c3edda2521bc65b4f00bf9671e.

**Comment by lukeholder** [comment]
Please let me know if the issue persists after upgrading to Commerce 2.1
