### ISSUE TITLE
Products with expiration dates cause invalid product error

### ISSUE THREAD

**Issue by ajgaunt** [craftcms/commerce#749]
### Description

If a product has an expiration date in the past, it throws an error when trying to view an order containing that product. This error did not exist on Craft Commerce 1 site.

### Steps to reproduce

1. Set an expiration date on a product in the past
2. View an order containing that product.
3. Error returned "Invalid Configuration – yii\base\InvalidConfigException - Invaliid Product ID: { id of product}

### Additional info

- Craft version: 3.1.14
- CraftCommerce version: 2.0.4
- PHP version: 7.1.19
- Database driver & version: MySQL 5.7.21
- Plugins & versions:

**Comment by lukeholder** [comment]
This is fixed in the next release due out soon.
