### ISSUE TITLE
Transactions cannot be modified

### ISSUE THREAD

**Issue by smetje** [craftcms/commerce#750]
### Description
When capturing a transaction it says 'Transactions cannot be modified'.

### Steps to reproduce

1. Create new order with a gateways that requires authorization
2. capture the transaction.

### Additional info

- Craft version: 3.1.14
- PHP version: 7.2.14
- Database driver & version: MYSQL 5.7.24
- Plugins & versions: Craft Commerce 2.0.4

**Comment by andris-sevcenko** [comment]
Just verified locally that everything works as expected. What gateway are you using?

**Comment by smetje** [comment]
I'm using the 'Manual' gateway.

**Comment by smetje** [comment]
Solved. Problem came from another piece of code, triggered by the EVENT_AFTER_ORDER_PAID. That piece of code triggered an exception. Because of that saving the transaction was not possible, and that triggeren the 'Transactions cannot be modified' error.
