### ISSUE TITLE
Store Settings Blank Page

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce#757]
### Description

Since the settings have been split up - clicking "Store Settings" shows a blank page on the right. It ideally needs to go to the "Store Location".

<img width="1828" alt="screenshot 2019-02-27 at 13 35 37" src="https://user-images.githubusercontent.com/522877/53494020-ab98cf00-3a94-11e9-9c40-80bd0263621f.png">

**Comment by lukeholder** [comment]
Thanks fixed for the next release.
