### ISSUE TITLE
Shipping Item Rates are not being applied

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#759]
### Description
I set the shipping Item Rates for my shipping zones but it not being applied.
Base value gets applied, but not the Item Rates fields.

Craft version: 3.1.14
Commerce Version: 2.1.0.2

**Comment by 23d1** [comment]
I think I'm having the same issue(s) — #777.

**Comment by lukeholder** [comment]
Duplicate of #777 fixed in the next release.
