### ISSUE TITLE
Disabled products break sales pages

### ISSUE THREAD

**Issue by billythekid** [craftcms/commerce#760]
Possibly related to #726/#727? If a sale is set up and contains products which have been disabled the sale dashboard page won't load so you can't add or remove products from the sale. Re-enabling the products fixes this.

**Comment by lukeholder** [comment]
Are you in the latest Commerce 2.1 release?

**Comment by billythekid** [comment]
@lukeholder hah, well now I am! Hadn't updated in a while as I was talking with support about this, of course you fixed it already!

Apologies.
