### ISSUE TITLE
Mandatory variant fields not validated on save

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [craftcms/commerce#761]
### Description
We're having a commerce product with 30+ variants. Each variant has 2 custom mandatory fields and 3 not custom mandatory fields (SKU, Price & Stock not calculated).

No error is given on Product Save when one of the custom mandatory fields is empty

### Steps to reproduce

1. Leave custom mandatory field empty
2. Save
3. Variant saves successfully
4. Breaks element api (Trying to get property of non-object)

### Additional info

- Craft version: **Craft Pro** 3.1.9.1 && **Craft Commerce** 2.0.4
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7.25
- Plugins & versions: http://files.wild.as/hxzCZA

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
