### ISSUE TITLE
Custom Order Reference Number

### ISSUE THREAD

**Issue by ajgaunt** [craftcms/commerce#765]
### Description

While testing the Order Reference Number Format field I entered one of the samples from the docs. When trying to make a purchase I am now getting a 404 error Template charge not found (it is loading this as the first segment of the URL http://website.com/charge)

Now if I try to change the Order Reference Number Format back, it still tries to load this charge url.

### Steps to reproduce

1. Update Order Reference Number Format to {{ object.dateCompleted|d('Y') }}-{{ id }}
2. Attempt to place an order

### Additional info

- Craft version: Craft Pro 3.1.15 
- Craft Commerce version: 2.1.0.2
- PHP version: 7.1.19
- Database driver & version: MySQL 5.7.21
- Plugins & versions:

**Comment by lukeholder** [comment]
There is no `|d` filter. I have fixed the docs.

This should work:

`{{ object.dateCompleted|date('Y') }}-{{ id }}`
