### ISSUE TITLE
Project Config not being applied to Commerce on install

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#768]
### Description
I am starting a fresh DB with a project I'm working on to cleanup all the test data and products.  For some reason, the project configs are not beeing applied.

### Steps to reproduce

1. Pull git repo and create .env file
2. CLI (windows 10)  composer install
3. CLI craft install
4. CLI craft project-config/sync
5. All the entry types, fields and other Craft CMS settings are all set, but none of the Commerce ones are (ie: gateway, product types)

### Additional info

- Craft version: 3.1.15 PRO
- Commerce version: 2.1.0.2
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins & versions:

**Comment by echantigny** [comment]
My workaround for now:

Deleting the values (not the row) in the info table and rerunning the  `craft project-config/sync`

**Comment by lukeholder** [comment]
Not seeing where you installed commerce in your steps?

**Comment by echantigny** [comment]
@lukeholder The whole project already existed in git, including the composer.lock that has all the information for the CMS, Commerce, gateway...

It's basically setting up a new environment of an old project with a brand new DB.

**Comment by boboldehampsink** [comment]
This might be related to #752

**Comment by andris-sevcenko** [comment]
I'll try to take a look today.

**Comment by boboldehampsink** [comment]
@andris-sevcenko thanks, I added a PR for this #756
