### ISSUE TITLE
Allow to add html templates to orders' page

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#772]
### Description
Commerce will take my heart away if it allows me to add templates to orders page. just to display some extra stuff to the admins. I usually add them, but they get deleted with every update.

**Comment by lukeholder** [comment]
The order edit twig template has the following template hooks:

```
cp.commerce.order.edit
cp.commerce.order.edit.main-pane
```

See: https://docs.craftcms.com/v3/extend/template-hooks.html
