### ISSUE TITLE
`shippingAddressSameAsBilling` don’t work since the last Commerce update

### ISSUE THREAD

**Issue by jesuismaxime** [craftcms/commerce#773]
### Description

The `shippingAddressSameAsBilling` is not working anymore. I replace my template by the default Commerce `checkout/addresses` template and then comment/uncomment the right inputs.

When I get to the next step, the taxes aren’t applied.

Notes: 
1. Everything works fine with the unchange default `checkout/addresses` template (but with the shipping address first, but I need the Billing address first)
2. Everything works fine if I use `billingAddressSameAsShipping` on my own template

Craft version: 3.1.15
Craft Commerce: 2.1.0.2

**Comment by lukeholder** [comment]
Using the example templates, I was able to switch the billing and shipping address locations like so: https://gist.github.com/lukeholder/7136f91c36a81bc790237b89af00bce4

And was able to use  `shippingAddressSameAsBilling` successfully. Let me know if you have any further info and I can reopen if needed.

**Comment by jesuismaxime** [comment]
Did you try it with an actual user or a Guest ? 
I did'nt specify it, but the issue is when a guest checkout happens. 

I try your gist and can't make it works. I even remove all my redirections and custom behaviors in the shipping template. If I look at the active cart and the CP, I can see the adresses, the product line item(s), but nothing about the taxes.

I test with both Chrome autocomplete and manual fill. 

If you can't reproduce the issue with a Guest checkout, I guess its about my layout ¯\_(ツ)_/¯

**Comment by jesuismaxime** [comment]
@lukeholder any updates? Did you try with a guest checkout ?

**Comment by lukeholder** [comment]
I can confirm I can not reproduce as a guest with `shippingAddressSameAsBilling` and using this template: https://gist.github.com/lukeholder/7136f91c36a81bc790237b89af00bce4

screencast of me trying to reproduce: https://jmp.sh/MNK36gw

In chrome dev tool try looking at your posted data on your address page: https://datawookie.netlify.com/blog/2016/09/view-post-data-using-chrome-developer-tools/

See mine for example: https://jmp.sh/6qmvONe

Maybe you could post what your POST data looks like?

**Comment by jesuismaxime** [comment]
Did you try with one or more taxes ? As mentioned in my opening comment, the issue is about the taxes (not the address). When switching from Addresses step to the next step (whether its the Shipping or Payment step) the taxes wont apply. If I go back and send again the addresses, the taxes finally appear.

See a screencast of the issue : https://streamable.com/8yspe
Exemple of posted data : https://imgur.com/jQQDgC9

Details : not shown in the video, but if I go back again on the Facturation (Billing) tab, select 'Quebec' instead of 'Alberta' and process to the next step. I'm expecting a new taxe level for the Quebec province. But all I got is still the TPS (Canada level taxe). If I go back to the Billing step I can see that Quebec is selected. Submit the form again and then I got all my taxes. The data/settings seem to not send properly on every first change.

**Comment by jesuismaxime** [comment]
Hey @lukeholder don't want to bother but do you take the time to read my last comment about this issue ?

**Comment by lukeholder** [comment]
Getting a second report on this and will take another look.

**Comment by jesuismaxime** [comment]
Nice! Since I haven't figure it out be cause of the project deadline, I simply force user to have a Shipping page (even if the order didnt need some), since it re-post the order, the taxes are applied.

**Comment by lukeholder** [comment]
I think this has been fixed through: https://github.com/craftcms/commerce/issues/922
