### ISSUE TITLE
Deleting Commerce products does not delete products or variants from db

### ISSUE THREAD

**Issue by stianmandarin** [craftcms/commerce#775]
### Description
Deleting Commerce products does not delete products or variants from db. This is on a completely clean install of Craft. The only plugin present is Commerce. I haven't added any fields or done anything to modify anything.

This has been reported before, see [https://github.com/craftcms/commerce/issues/417](417) and [https://github.com/craftcms/commerce/issues/147](147)

I have tried deleting the db and installing everything again, but the problem persists.

### Steps to reproduce

1. Install Craft with Composer
2. Install Commerce with Composer
3. Delete example products automatically installed with Commerce
4. Check table `commerce_products` and `commerce_variants`, see that neither the product nor variants have been deleted.

### Additional info

- Craft version: 3.1.16
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Commerce 2.1.0.2

**Comment by lukeholder** [comment]
Fixed in 700bb31d13cbda444e214949f06f6fac9dacb0db
Will be in the next release. Use the develop branch if you need the fix sooner, thanks.

**Comment by stianmandarin** [comment]
So I just updated to 2.1.1, but this problem persists

**Comment by lukeholder** [comment]
Products and variants are soft deleted using the Craft CMS soft delete feature.

craftcms/cms#3500
https://craftcms.com/blog/craft-3-1
https://docs.craftcms.com/v3/extend/soft-deletes.html

You can force delete all items in the trash without waiting the 30 days with this command:

`./craft gc --delete-all-trashed=1`
