### ISSUE TITLE
Add (optional) Volume field to variant dimensions

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#783]
Having an optional "Volume" field for variants would be very useful when selling liquid products.

**Comment by lukeholder** [comment]
Sounds like something good for a custom field. Dimension fields are built in only for purposes of shipping.

Is volume ever useful for shipping?

**Comment by fantasticmachine** [comment]
No not for shipping. At least not in the case I was thinking.
I figured the dimension fields were there for shipping but for a site admin having the width, height, depth, and weight fields in one area then a Volume field elsewhere (as a custom field) doesn't make sense. To them "Volume" belongs with the other dimension fields.

I guess it's more a UI issue really.

**Comment by lukeholder** [comment]
Yeah I think it is an UI issue. 

In a future Craft version, being able to layout built-in fields with custom fields will be an option eventually.

I will keep this open as a Improvement request and see if others find it and upvote/comment.

**Comment by lukeholder** [comment]
Decided not to go with a volume field on the variants. Thanks for the input.
