### ISSUE TITLE
Apply the discount for each number of matched line items

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#784]
### Description
I think it would be awesome if i could apply the discount for each number of matched line items
for example: 
Get a 5$ for each 3 bottles of this product
So if i add 6 bottles, i get 10$ off
or 9 bottles i get 15$ off and so on. other than creating an adjuster for it. like a tiny miny little condition that accepts two values, a flat or a percent value and the number to apply too.

**Comment by lukeholder** [comment]
Moving discussion for this to #47
