### ISSUE TITLE
Commerce 2.02 -> 2.1.2 Upgrade/Migration Failed

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#785]
### Description

Somewhere along the line, the ``commerce_donations`` table is attempted to be created more than once, causing Craft to prompt you to downgrade then upgrade. 

If you attempt to update, of course, then the upgrade fails, then rinse and repeat.

I was able to remove the ``commerce_donations`` table with no issue and then run the updater again, which worked. This was on my local box, haven't tried it on production yet. 

``Migration: craft\commerce\migrations\m190131_000858_add_donation_purchasable``

### Steps to reproduce

1. Upgrade Commerce to 2.1.x

**Comment by lukeholder** [comment]
Hi, Could you post the actual error? 

The table can only be created in the install migration file or in the migration you reference for already installed plugins.

Not sure how this could happen.

**Comment by lukeholder** [comment]
I was able to upgrade from 2.0.2 to 2.1.2 without errors.

**Comment by RitterKnightCreative** [comment]
Closing this... my error, I had done a test upgrade and reverted back but the old table was there.
