### ISSUE TITLE
Cart object data returned after adding to cart is not on the current locale

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#789]
### Description
I use ajax to add to cart and i have a website with three languages, but the titles and descriptions i get from the reponse object are in the base site's language.

**Comment by lukeholder** [comment]
Could you be more specific on the titles and descriptions you are referring to?

**Comment by Sam-Black-0013** [comment]
I have a three languages websites, when i add a variant to the cart using ajax, the line item description (lineitem.description) i get back is from my primary website, not from the current locale. 
If i shop from my french website, after i update the cart the products' titles are in german(my primary website)

**Comment by nfourtythree** [comment]
Hey @Sam-Black-0013 

Just wondering if you are still having an issue with this?

If you are, can I ask when you were posting the data via ajax were you supplying the site ID and posting to that specific site's URL?

Thanks

**Comment by nfourtythree** [comment]
Hi @Sam-Black-0013 

I am going to close this issue for the moment, please feel free to re-open it if you have any further information.

Thanks
