### ISSUE TITLE
Cart / Order Currency

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#790]
Can we have the ability to change the order.currency not just the order.paymentCurrency.

When using with a payment gateway that accepts payment in multiple currencies, in the CP it will currently show the amount in the order currency not the payment currency.

**Comment by lukeholder** [comment]
Commerce doesn't work with multiple currencies yet, there is only one store currency.

Commerce supports additional payment currencies (for accepting payment for the order in a different currency). The transactions show the amount changed with the payment Currency.

Duplicate ticket of https://github.com/craftcms/commerce/issues/255

Hope to get multi-currency support added in the future.
