### ISSUE TITLE
Environment variables values in commerce-gateways.php should be hidden by default from phpinfo

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#791]
### Description

Gateway configuration variables (usually security keys etc) should be hidden from the php_info display like other sensitive data is automatically.

I think the best thing would be to mark all of these as sensitive data...or at least detect any with 'user', 'key' or 'password' in them...

### Steps to reproduce

1. Use env vars in commerce-gateways.php e.g.

```
        'eWayRapid' => [
            'testMode' => getenv('DEV_MODE'),
            'apiKey' => getenv('EWAY_APIKEY'),
            'password' => getenv('EWAY_PASSWORD'),
            'CSEKey' => getenv('EWAY_CSEKEY')
        ]
```

2. Visit Utilities -> PHPInfo - these values will be visible in plain text 
(whereas e.g. `S3_API_KEY` is shown as `••••••••••••••••••••`

![image](https://user-images.githubusercontent.com/731309/54500213-9960d100-496e-11e9-8c5e-ff908d3ed8c6.png)

### Additional info

All current versions as of this moment, composer update just run.

**Comment by brandonkelly** [comment]
The PHP Info utility will automatically redact any environment variables where the name contains a sensitive-sounding word like “key” or “password”. So if you rename `EWAY_APIKEY` to `EWAY_API_KEY`, and `EWAY_CSEKEY` to `EWAY_CSE_KEY`, they will get redacted. (`EWAY_PASSWORD` should already be getting redacted.)

**Comment by bossanova808** [comment]
Thanks Brandon - always one step ahead.  Might want to consider adding `token` `secret` and `signature` to the list of words you look for (if not already there), given those are all in common use with gateway configs...but I have just bunged `key` on the end of anything at all sensitive for now.
