### ISSUE TITLE
Allow to add a field layout to countries and states

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#794]
We get a lot of requests to add different conditions based on the shipping address's country or state.
For now we create many conditions and a lot of work just to do a simple check for a small task. For example, one time we had to add a flat value as an adjustment to the order based on the country we are shipping to, each country had it is own value. we just created a section for it and readded the countries to them with their ids just to add a flat value. So can you please please please allow to add a field layout to them?
And the enabling and disabling of countries and states we be most enormously appreciated.

**Comment by lukeholder** [comment]
I think you are asking for countries and states to be elements. Added it as a feature request. In the meantime, we could look to add a country and state custom field.

**Comment by Sam-Black-0013** [comment]
ok thank you so much @lukeholder

**Comment by lukeholder** [comment]
Moving discussion to #213
