### ISSUE TITLE
defaultVariantId not set on initial save

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#796]
### Description
Refer to https://github.com/verbb/feed-me/issues/493, but creating a brand new Product with multiple Variants, doesn't seem to set its `defaultVariantId` value. Subsequently re-saving the product will fix it right up. I'm ensuring that at least one variant has the 'default' switch on (near the matrix-like actions on the right-hand side).

I imagine its to do with the implementation [here](https://github.com/craftcms/commerce/blob/develop/src/elements/Product.php#L713), where you're indeed sending an SQL update to correctly update the product - but it'll do nothing if the variant has null for an ID - which is what happens for a new variant.

I can see shortly after this code you're saving the variant. Would it be prudent to move this SQL update after the variant has been saved, therefore has an ID?

### Additional info

- Craft version: 3.1.17
- PHP version: 7.0.31
- Database driver & version: MySQL
- Plugins & versions: Commerce 2.1.0.2

**Comment by lukeholder** [comment]
Thanks!
