### ISSUE TITLE
Shipping Method's Cost No Longer in `cartArray`

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce#798]
### Description
This could be just a misunderstanding on my end, but we're trying to update to Commerce 2.1 and found that the `amount` has been removed from `getAvailableShippingMethods`. We currently have a single page checkout flow which means we rely on the JSON responses from `CartController`.

If you look at `ShippingMethods::getAvailableShippingMethods` you'll notice that `price` renamed from `amount` is not being returned. This means we cannot display the cost of a shipping method after updating the cart without a custom endpoint that adds it in.

### Steps to reproduce

1. Make a XHR request to `/actions/commerce/cart/update-cart`
2. In the response view `availableShippingMethods` and you'll notice there's no `price` or `amount`

### Additional info

- Craft version: 3.1.19
- PHP version: 7.3
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Commerce 2.1.2 & Commerce-Stripe 1.2

**Comment by dhahn** [comment]
Hey @lukeholder, awesome y'all are working on a fix for this. Really appreciate it! 

Is there any sense of how long it'll take for this? Full clarity, this is the only thing preventing us from deploying our upgrade. We can do another call every time we update the cart to just get the prices if we need to, but we're trying to avoid that.

I'd be happy to push a PR up if that'd be helpful, but don't want to waste any of your time.

**Comment by RitterKnightCreative** [comment]
Noticed the same. Looks like some shipping refactoring was done as the [templates](https://github.com/craftcms/commerce/blob/622149b43949a18d10788b4ed2e739411b1f1070/templates/shop/checkout/shipping.html#L49) were updated recently as well.

FWIW [this](https://craftcms.stackexchange.com/a/29283/1016) worked for me: ``{{method.getPriceForOrder(cart)|commerceCurrency(cart.currency) }}``

**Comment by lukeholder** [comment]
I have just pushed an update to add the `price` attribute to the json cart data response.

The price attribute is not available in twig or on the shipping method generally, I have only added it to the json for convenience.

You should continue to use the `getPriceForOrder(cart)` method in twig and PHP.

**Comment by lukeholder** [comment]
Fix will be in the next release.

**Comment by dhahn** [comment]
This is perfect. Thank you @lukeholder!
