### ISSUE TITLE
Linking a Shipping Category to products

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/commerce#800]
### Description
We're trying to add a free shipping method on a couple of products (Gift Cards). In the documentation is written that it is possible like this:

> When defining a product type, you can choose the shipping categories that products of that type can belong to. When setting up individual products, an author can choose which shipping category that product belongs to.

![Screen Shot 2019-03-26 at 14 43 09](https://user-images.githubusercontent.com/42932673/55001709-82a52480-4fd5-11e9-9d2a-bd674e5d2a9b.png)

But on the Product Type settings we could not find this setting. Do we understand it wrong? Could you help us out?

### Steps to reproduce

1. Add a Shipping Categories with Available to Product Types checked for the product type.
2. Now we're looking in the Product Type settings where we can link it to the product?

### Additional info

- Craft version: 3.1.19
- PHP version: 7.1.12
- Database driver & version:
- Plugins & versions: Craft Commerce Pro: 2.1.2

**Comment by lukeholder** [comment]
@carolineboeykens As of Commerce 2.0 management of the shipping category‘s relationship to the product type was moved to the shipping category itself.

I have just pushed an update to the develop branch that makes this more clear, and shows links on the product type over to the shipping and tax category management screens (if that user has permissions)

See screenshot:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/133571/55128620-26661000-514f-11e9-86c1-e8076ab1128e.png">

Sorry for the confusion in the docs, those have also been updated.

Look out for the pictured changes in the next release due out soon.

**Comment by carolineboeykens** [comment]
> When setting up individual products, an author can choose which shipping category from the available shipping categories that product belongs to.

Where can we find this? Or is this available after the update?

**Comment by lukeholder** [comment]
Once you add more than one shipping category to be available to the product type, you should see the shipping category selector on the product edit screen. Even before this update.

**Comment by carolineboeykens** [comment]
Allright, we found it! Our general shipping category wasn't linked to our product type. So we had only one category linked to the products. Thanks!
