### ISSUE TITLE
using hasVariant hasSales in element-api results in error

### ISSUE THREAD

**Issue by fabianhijlkema** [craftcms/commerce#801]
### Description
I've restarted working on a project that will use Craft, Craft Commerce and Element API. Before I had an endpoint in my API to return all variants and products on sale and it worked. Now while revisiting the project I get an error message.

```
{
    "error": {
        "code": 0,
        "message": "Argument 3 passed to yii\\web\\NotFoundHttpException::__construct() must be an instance of Exception or null, instance of TypeError given, called in /Applications/MAMP/htdocs/MYDOMAIN/craft/vendor/craftcms/element-api/src/controllers/DefaultController.php on line 124"
    }
}
```
This is the beginning of the code element-api.php of this specific endpoint that results in this error...

```
'api/sale/products.json' => [
            'elementType' => Product::class,
            'resourceKey' => 'products',
            'criteria' => [
				'hasVariant' => ['hasSales' => true]
			],
			...
```

If I change my criteria to for example `'hasVariant' => ['price' => '30.0000']` it does work properly.

Everything in my setup is up to date.

### Additional info

- Craft version: 3.1.19
- Craft Commerce version 2.1.2
- PHP version: 7.1.8
- Element API version: 2.5.4

**Comment by fabianhijlkema** [comment]
[9311cb2](https://github.com/craftcms/commerce/commit/9311cb25b1c0007c2d88cfbcdce655ad71549072) actually solves the issue, so I'll just wait on that release...

**Comment by lukeholder** [comment]
Yeah hope to get the release out very soon, thanks!
