### ISSUE TITLE
Line Item level refunding

### ISSUE THREAD

**Issue by sjcallender** [craftcms/commerce#803]
With reporting, merchants often want to know specifically what order detail a refund is related to. Right now, refunding is on an order basis. It would be hugely helpful to be able to assign a refund to a particular line item, shipping cost, tax cost, or nothing. Adding a dropdown of custom "reasons" (like statuses) would be bonus (i.e., returned, damaged, incorrect shipping, etc). Then we can better evaluate refunding trends and uncover hidden operational problems.

**Comment by lukeholder** [comment]
Yes, definitely a consideration with back-end order editing that I am working on.

**Comment by mcclaskiem** [comment]
@lukeholder There might be another issue for this but are there plans to integrate returning specific line items as well and not just associate a refund amount to an order. Thanks!

**Comment by philipboomy** [comment]
I am working on a site where line item refund feature would be very useful. Here is a screenshot https://cl.ly/4c4420b02322 of WooCommerce which offers it. When selecting quantity it puts the line item back into stock.

Also, not sure if this is doable but an event where I can grab the specific line item would be very useful too. So if a partial refund has occurred then I can see for which line item in the event to run my code for that specific line item.

**Comment by pixelmachine** [comment]
@lukeholder is back-end order editing something that you foresee coming soon or is it a longer term addition?

**Comment by lukeholder** [comment]
Back end order editing will be out for alpha testing in the next week.

**Comment by lukeholder** [comment]
Closed as a FR in favor of a RMA feature planned. #1046
