### ISSUE TITLE
Feature Request: Ability to delete line item notes

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#805]
### Description
Unless I'm mistaken, it doesn't look like there is the ability to delete a line item note.

### Steps to reproduce

1. Create a line item note
2. Edit the note and submit a blank note
3. The existing note still appears

### Additional info

- Craft version: Craft Pro 3.1.20
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23
- Commerce version: 2.1.2

**Comment by lukeholder** [comment]
Duplicate of #45
