### ISSUE TITLE
Swiftmailer Error When 'Status Email Address' Field Populated

### ISSUE THREAD

**Issue by bfopma** [craftcms/commerce#806]
### Description
When attempting to complete the final step of checkout (completing order and initiating an order confirmation email), I receive the following error: "Address in mailbox given [] does not comply with RFC 2822, 3.6.2.", indicating that the sender email address is NULL.

It appears that this error only occurs when an email address has been populated in the Craft Commerce 'Status Email Address' field. When leaving the field blank (defaulting back to the system email address), the error does not occur. 

### Steps to reproduce

1. Settings -> Email -> Transport Type: SMTP (fill in SMTP connection details)
2. Commerce -> System Settings -> General Settings 
3. Enter any email into the 'Status Email Address' field
4. Attempt to check out
5. Error of 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' from Swiftmailer displays, indicating that the sender email is NULL

### Additional info

- Craft version: 3.1.20.1
- Commerce version: 2.1.2
- PHP version: 7.2
- Database driver & version: MySQL 5.6.10
- Plugins & versions:

  Amazon S3 | 1.2.2
  Asset Rev | 6.0.2
  Cookies | 1.1.11
  Craft Commerce | 2.1.2
  Feed Me | 3.1.16
  Feed Me Pro | 3.0.4
  Freeform Pro | 2.5.16
  Freeform Pro | 2.5.16
  Linkit | 1.1.10
  PayPal for Craft Commerce | 2.0.0
  PayPal Payflow | 2.0.0
  Redactor | 2.3.2
  Retour | 3.1.7
  SEOmatic | 3.1.46

**Comment by AlanOne** [comment]
I can confirm this issue. 

We had multiple orders under 'Inactive carts' that were actually fully paid for, but due to the above error, Order Status did not update and Payed Status was set to Partial.

Removing the email from 'Status Email Address' under Commerce General settings seems to be a workaround.

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
