### ISSUE TITLE
When setting paymentCurrency on the final payment form. Throw exeception

### ISSUE THREAD

**Issue by bighoho123** [craftcms/commerce#809]
### Description

So in the final step, I would like to charge user in a different currency from the primary one. Because the PaymentsController will always make sure the currency is up-to-date. The only way to do it seems to be that we have an input called 'paymentCurrency' in the final submission form.

However, it will throw exception

yii\base\UnknownMethodException: Calling unknown method: craft\commerce\services\Carts::setPaymentCurrency() in /vendor/yiisoft/yii2/base/Component.php:300

### Additional info

- Craft Commerce version: 2.1.2
- PHP version:  7.2.5

**Comment by lukeholder** [comment]
Thanks fixed for the next release.
