### ISSUE TITLE
Line item Snapshot remains JSON on cart error

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/commerce#817]
### Description
I am currently using `\craft\commerce\controllers\BaseFrontEndController::cartArray` for getting the contents of my cart. However when returning with an error (in my case an invalid coupon code) the `snapshot` value in the line items remains a JSON value instead of being casted to an array.

Little bit of (perhaps offtopic) context:
I have defined a controller which which extends the `\craft\commerce\controllers\BaseFrontEndController` so the `cartArray` method becomes accessible. Inside my own action I implemented
```php
$cart = CommercePlugin::getInstance()->getCarts()->getCart();
return $this->asJson($this->cartArray($cart));
```

This action I then run from my Twig template to inject the cart array into my Cart component:
```html
<v-checkout :cart="{{ craft.app.runAction('module/commerce/cart').data|json_encode }}"></checkout>
```

(It would be great if this would be accessible from a build in controller or perhaps or perhaps a Twig function so I don't have to run entire controller actions to access the `cartArray` method)

### Steps to reproduce

1. Apply invalid coupon code
2. Look at output from `\craft\commerce\controllers\BaseFrontEndController::cartArray` and check the value of `$lineItem->snapshot` (specifically at `vendor/craftcms/commerce/src/controllers/BaseFrontEndController.php:113`).

### Additional info

- Craft version: 3.1.21.1
- PHP version: 7.3.4
- Database driver & version: 
- Plugins & versions: Commerce 2.1.3

**Comment by lukeholder** [comment]
In the next version of Commerce, the `BaseFrontEndController::cartArray()` is being deprecated and will use the `$order->toArray()`

**Comment by lukeholder** [comment]
Will update this ticket and mark as closed once it is out.

**Comment by lukeholder** [comment]
You can use the now available `Plugin::getInstance()->getOrders()->cartArray($cart);`

**Comment by Wiejeben** [comment]
Finally updating my project! 

```html
<v-checkout :cart="{{  craft.commerce.orders.cartArray(cart)|json_encode }}"></checkout>
```

Works perfectly. Thanks!
