### ISSUE TITLE
Commerce 2 documentation typo

### ISSUE THREAD

**Issue by JayBox325** [craftcms/commerce#824]
### Description

There is a typo on the Commerce 2 Class Reference page, but there's no ability to edit it and submit a PR.

### Steps to reproduce

1. Visit this page: https://docs.craftcms.com/commerce/api/v2/craft-commerce-elements-order.html#public-methods
2. Find in the page "adjustmemnts". There are two instances.

**Comment by lukeholder** [comment]
Thanks. The class API docs are generated from the code and comments in this repo. See: https://github.com/craftcms/commerce/commit/cf4ccf4126bf626c2b87e266fd8826aebed49a04
