### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/commerce#825]
https://github.com/craftcms/commerce/blob/a4cdaea962d489191747b0391dcba016b28e0cb3/src/templates/settings/subscriptions/_editPlan.html#L52

![Screen Shot 2019-04-12 at 10 12 42 AM](https://user-images.githubusercontent.com/7085184/56043601-94900280-5d0b-11e9-847a-723e6d3e6cfc.png)

**Comment by lukeholder** [comment]
Thanks!! fixed.
