### ISSUE TITLE
Database Exception when updating from Commerce 2.1.2 => 2.1.3

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#829]
### Description
The error i get is this:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'commerce_orders.registerUserOnOrderComplete' in 'field list'

Craft is updated to the latest version, and other plugins as well.

### Additional info
- Craft version:3.1.23

**Comment by lukeholder** [comment]
Can you send your DB backups before and after update to support@craftcms.com thanks.

**Comment by lukeholder** [comment]
Fixed with 

867ef219620eee9b4513a10ebe158f8c2212b9f7  
Changelog 835968d29b3ff01a1d64c81d6916e6b5ed4bf090
