### ISSUE TITLE
Should the update-cart controller return an errors key like Craft?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#833]
### Description

Noticed that `commerce/cart/update-cart` controller does not return an array item with the cart errors like craft does:

https://github.com/craftcms/commerce/blob/1cac3347874108c0ac9281c82541f164baa08ac7/src/controllers/CartController.php#L321

https://github.com/craftcms/cms/blob/develop/src/controllers/EntriesController.php#L543

Be great if it could.

### Additional info

- Craft version: Craft Pro 3.1.23
- PHP version: 7.1.25
- Database driver & version: MySQL 5.5.5

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.

**Comment by samhibberd** [comment]
Amazing thanks @lukeholder
