### ISSUE TITLE
Null is being sent when disabling a sale

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#837]
### Description
When I try to disable a sale, i get this error
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'enabled' cannot be null
The SQL being executed was: UPDATE `craft_commerce_sales` SET `applyAmount`='-100', `allGroups`=1, `allPurchasables`=0, `allCategories`=1, `enabled`=NULL, `dateUpdated`='2019-04-29 19:50:58', `stopProcessing`=NULL, `ignorePrevious`=1 WHERE `id`=14

**Comment by lukeholder** [comment]
Fixed for the next release. Thanks.
