### ISSUE TITLE
Hashed redirect url not working with eway payment gateway

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#838]
### Description

cancelUrl is ignored when cancelling a Paypal payment, and user instead returned to main site url.
(have seen others report on Discord).

### Steps to reproduce

Submit a payment using Paypal Express with 
`<input type="hidden" name="cancelUrl" value="/cart/payment">`
...in there.  

Cancel the payment, it returns instead to the siteUrl with a token on the end:

https://siteurl.com.au/?token=EC-2R433694N94823928

### Additional info

- Craft version: 3.1.24, Commerce: 2.1.3.1
- PHP version: 7.2
- Database driver & version: MySQL 5.7.25
- Plugins & versions: a bunch...

**Comment by bossanova808** [comment]
I have confirmed the issue is the request data being sent to Paypal has the wrong cancel url...

```
        [VERSION] => 119.0
        [USER] => paypal_api1.siteurl.com.au
        [PWD] => XXXX
        [SIGNATURE] => XXXXX
        [SUBJECT] => 
        [BUTTONSOURCE] => ccommerce_SP
        [METHOD] => SetExpressCheckout
        [PAYMENTREQUEST_0_PAYMENTACTION] => Authorization
        [PAYMENTREQUEST_0_AMT] => 94.50
        [PAYMENTREQUEST_0_CURRENCYCODE] => AUD
        [PAYMENTREQUEST_0_INVNUM] => 98732dcb0009afae5906937533ec57ed
        [PAYMENTREQUEST_0_DESC] => Order #50032
        [SOLUTIONTYPE] => Sole
        [LANDINGPAGE] => Billing
        [RETURNURL] => https://siturl.com.au/index.php/actions/commerce/payments/complete-payment?commerceTransactionHash=XXXXXX
        [CANCELURL] => https://siturl.com.au/
        [HDRIMG] => 
        [BRANDNAME] => XXXXX
        [NOSHIPPING] => 1
        [ALLOWNOTE] => 0
        [ADDROVERRIDE] => 1
        [LOGOIMG] => 
        [CARTBORDERCOLOR] => 
        [LOCALECODE] => 
        [CUSTOMERSERVICENUMBER] => 
        [MAXAMT] => 
        [PAYMENTREQUEST_0_TAXAMT] => 
        [PAYMENTREQUEST_0_SHIPPINGAMT] => 
        [PAYMENTREQUEST_0_HANDLINGAMT] => 
        [PAYMENTREQUEST_0_SHIPDISCAMT] => 
        [PAYMENTREQUEST_0_INSURANCEAMT] => 
        [PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID] => 
```

**Comment by lukeholder** [comment]
Just like the `returnUrl`, it needs to me hashed (encrypted) to stop people potentially messing with it. `<input type="hidden" name="cancelUrl" value="{{'/cart/payment'|hash}}">`

Let me know if that fixes it.

**Comment by bossanova808** [comment]
Hi Luke

Ok, I see where the issue actually lies now.

1. The docs are wrong - they don't actually show hashing the url:
https://docs.craftcms.com/commerce/v2/making-payments.html

2. For Paypal, you indeed need to hash the cancelUrl - that does fix this issue

3. However, hashing the url breaks the `redirect` (i.e. complete) url for eWay (just tested again) - (which is why - combined with mis-info in the docs - I took out hashing originally)

....so in fact the bug is with the eWay gateway (and also the docs should be updated - will PR that).

I've modified my forms for now to make things work (i..e submit hashed to Paypal/manual, unhashed to eWay), but maybe I should open an issue on the eWay gateway instead?

**Comment by andris-sevcenko** [comment]
> However, hashing the url breaks the redirect (i.e. complete) url for eWay (just tested again) - (which is why - combined with mis-info in the docs - I took out hashing originally)

Not seeing anything in the code that might cause this. Can you, please, post a specific example? Looking at code it seems like at all is required to be hashed.

**Comment by bossanova808** [comment]
I couldn't see anything either but this works with Paypal and Manual:

```
{% set completeUrl = '/cart/complete?number='~cart.number %}
<input type="hidden" name="redirect" value="{{ completeUrl|hash }}">
```
but same thing with eWay causes the re-direct to fail. 

So with eway I change it to:
```
<input type="hidden" name="redirect" value="{{ completeUrl }}">
```

and it works fine.  

In terms of a more specific example...um, not sure, that's the specific problem there :)

But happy to provide more info if I can?  Let me know whatever you need?

**Comment by andris-sevcenko** [comment]
@bossanova808 I'll see if I can reproduce this sometime in near future. Leaving this open as a reminder. Thanks for the information!

**Comment by lukeholder** [comment]
@bossanova808 The decryption of the `cancelUrl` is done in the `commerce/payments/pay` controller action. The gateway should be supplied the unencrypted URL so not sure how this is happening. Can you confirm this is still an issue?

**Comment by bossanova808** [comment]
@lukeholder It's the complete re-direct url actually, that is the issue.  

I can confirm that I am using the above code still and it works...so with Paypal and Manual I use:

```twig
{% set completeUrl = '/cart/complete?number='~cart.number %}
<input type="hidden" name="redirect" value="{{ completeUrl|hash }}">
```

but same thing with eWay causes the re-direct to fail.
So with eway I change it to:

```twig
<input type="hidden" name="redirect" value="{{ completeUrl }}">
```

I have not tried the other way, i.e. hashing the url, for eway in a while (as everything is working!).  I suppose you want me to try that?  Is just against the sandbox ok, or do you need it to be against live eWay?

**Comment by lukeholder** [comment]
What is really weird is that the `redirect` param is always expected in the `commerce/payments/pay` controller action that the `redirect` param is hashed:

https://github.com/craftcms/commerce/blob/develop/src/controllers/PaymentsController.php#L286-L287

I am not sure how it is working unless the eway gateway is looking at the post request directly somewhere?

**Comment by bossanova808** [comment]
Yeah I could not work it out at the time, just that I had to avoid hashing it.  Made me wonder if there was some double re-direct thing happening.  I haven't poked that deep, though - at the time I had my hands full with other launch V2 stuff,as I recall.  I'll try and do some digging when I find some time!

**Comment by lukeholder** [comment]
Let us know if this issue is persisting and we can take another look and re-open.
