### ISSUE TITLE
Purchasable-bound discount not applied if discount before it has 'stopProcessing' checked

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/commerce#839]
### Description
If you have two sales, of which the first in line has 'stopProcessing' checked, and the second one is related to one or more purchasables, the second sale will not be applied, even though the first sale doesn't apply to the purchasable of the second sale.

See also #836.

### Steps to reproduce

1. Create two sales
2. Check 'stopProcessing' for the first one
3. Limit the second one to a purchasable
4. No discount will be applied to the purchasable

### Additional info

- Craft version: 3.1.24
- PHP version: 7.2
- Plugins & versions: Commerce 2.1.3.1

**Comment by lukeholder** [comment]
You have said 'see also #836' but does that PR fix this issue?

**Comment by nilsenpaul** [comment]
For me, it does.

**Comment by nilsenpaul** [comment]
> You have said 'see also #836' but does that PR fix this issue?

For me, it does.
