### ISSUE TITLE
Adding multiple purchasables to the cart only adding last item in loop.

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#840]
### Description

I'm trying to get multiple purchasables adding to my sites cart but having a bit of trouble with it.  I have resorted to trying the example code in the docs (https://docs.craftcms.com/commerce/v2/adding-to-and-updating-the-cart.html#adding-multiple-purchasables-to-the-cart) but even when I submit that form, it's only the last variable in the variants loop that gets added to the basket. Any ideas why this would be happening?

### Steps to reproduce

I am just using the example code in the docs currently, so the following: 

```
<form method="POST">
    <input type="hidden" name="action" value="commerce/cart/update-cart">
    {{ redirectInput('shop/cart') }}
    {{ csrfInput() }}

    {% for variant in product.variants %}
        <input type="hidden" name="purchasables[{{loop.index}}][id]" value="{{ variant.id }}">
        <input type="hidden" name="purchasables[{{loop.index}}][qty]" value="1">
        <input type="hidden" name="purchasables[{{loop.index}}][note]" value="1">
    {% endfor %}

    <input type="submit" value="Add all variants to cart">
</form>
```

When I output this and submit the form, with the product I am testing, there are 5 variants set in the CMS, but when I submit that form for the product and go into my active cart, the price and name of the last variant only show up.

### Additional info

- Craft version: 3.1.24
- PHP version: 7.0.32
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Commerce 2.1.4

**Comment by lukeholder** [comment]
I attempted to reproduce and wasn't able to. Here is a screencast of me using the exact same form you gave in your github ticket:

https://jmp.sh/e22l9u4

The only change to the html form was the retrieving the product which I highlight in the code.

Let me know if I have missed something in trying to reproduce.

**Comment by lukeholder** [comment]
Are you running Commerce Lite? It only lets you have one item in the cart at a time: https://docs.craftcms.com/commerce/v2/editions.html
