### ISSUE TITLE
Issue with the manual payment method (Authorize Only) after upgrade Commerce 1 to Commerce

### ISSUE THREAD

**Issue by andrelopez** [craftcms/commerce#844]
### Description
After upgrading to Commerce 2 I got the following error when I try to capture the payment:

`Argument 2 passed to craft\commerce\gateways\Manual::capture() must be of the type string, null given, called in D:\server\craft3\vendor\craftcms\commerce\src\services\Payments.php on line 497` 

### Steps to reproduce

1. On commerce 1 create a Manual Payment method with Payment Type: Authorize Only
2. Create some orders with the Manual Payment method without capture
3. Upgrade the plugin to Commerce 2
4. Try to capture an Order with the Manual Payment gateway.
5. Got the error.

### Additional info

- Craft version: 3.1.25
- PHP version: 7.2
- Database driver & version: mysql
- Plugins & versions: Craft Commerce 2.1.5

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
