### ISSUE TITLE
Snapshot contains much less data after upgrading to commerce 2.1.5

### ISSUE THREAD

**Issue by stevenvandemoortele** [craftcms/commerce#846]
### Description
After upgrading to commerce 2.1.5 almost all the data that used to be in a line item snapshot is gone. 

### Steps to reproduce
1. Upgrade to 2.1.5
2. Add item to cart

### Snapshot data in 2.1.5
array:1 [▼
  0 => array:10 [▼
    "onSale" => false
    "cpEditUrl" => "#"
    "productFields" => []
    "fields" => []
    "price" => 99.5
    "sku" => "\t1509275"
    "description" => "Bocamp - Kooktafel"
    "purchasableId" => "1051"
    "options" => []
    "sales" => []
  ]
]

### Snapshot data in 2.1.4
array:1 [▼
  0 => array:50 [▼
    "productId" => "1050"
    "isDefault" => "1"
    "sku" => "\t1509275"
    "price" => 99.5
    "sortOrder" => "1"
    "width" => null
    "height" => null
    "length" => null
    "weight" => "6.0000"
    "stock" => "0"
    "hasUnlimitedStock" => "1"
    "minQty" => null
    "maxQty" => null
    "deletedWithProduct" => false
    "id" => "1051"
    "tempId" => null
    "uid" => "5f9aa5d6-7524-4897-af8d-9487794ff17c"
    "fieldLayoutId" => "41"
    "contentId" => "1828"
    "enabled" => "1"
    "archived" => "0"
    "siteId" => "1"
    "enabledForSite" => "1"
    "title" => "Bocamp - Kooktafel"
    "slug" => null
    "uri" => null
    "dateCreated" => array:3 [▶]
    "dateUpdated" => array:3 [▶]
    "trashed" => false
    "resaving" => false
    "duplicateOf" => null
    "hasDescendants" => false
    "ref" => null
    "status" => "enabled"
    "structureId" => null
    "totalDescendants" => 0
    "url" => "http://vanomobilshop.test/store/tafel/kooktafel?variant=1051"
    "isAvailable" => true
    "isPromotable" => true
    "shippingCategoryId" => 1
    "taxCategoryId" => 1
    "onSale" => false
    "cpEditUrl" => "#"
    "product" => array:51 [▶]
    "productFields" => []
    "fields" => []
    "description" => "Bocamp - Kooktafel"
    "purchasableId" => "1051"
    "options" => []
    "sales" => []
  ]
]

**Comment by lukeholder** [comment]
Thanks for reporting. Fixed on develop branch.

Moved to b4401a5af70d803720539bb8838a8a0edef903a5

If there are specific variant or product attributes missing please open a new ticket with specific requests.

thanks.
