### ISSUE TITLE
Total Revenue chart (upper left) always display .00 cents

### ISSUE THREAD

**Issue by PopaWeb** [craftcms/commerce#849]
### Description

When the total of the orders have cents, the total revenue don't show it. Always .00
In the screen shot the total suppose to be $688.90
![Screen Shot 2019-05-08 at 18 16 12](https://user-images.githubusercontent.com/28791029/57412517-e5860000-71be-11e9-91a1-402f6e9b0cd9.png)

### Steps to reproduce

1. Adding order with cents (EX 125.28)
2. Currency CAD

### Additional info

- Craft version: Craft Pro 3.1.25
- PHP version: 7.2.17
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Commerce 2.1.4

**Comment by echantigny** [comment]
@lukeholder Fixed this one in the cms repo
https://github.com/craftcms/cms/pull/4378
