### ISSUE TITLE
Too much data in snapshot, lineitems table is blown up

### ISSUE THREAD

**Issue by mklishevych** [craftcms/commerce#850]
### Description

Snapshot for most of the lineitems (but not all) contains way too much data, the size of the column reaches around 800kb which blows the size of the database tremendously. The reason for this is that product snapshot includes all of the heavyweight fields like relations with other entities, serialized versions of the join statements etc. If it's not a bug in Commerce, please point me in the right direction.

### Additional info

- Craft version: 3.1.26
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: Commerce 2.1.5.2

**Comment by bossanova808** [comment]
Gotta agree on this one, Luke, and feel it needs some soonish attention...as trying to work out why pulling in the production DB to local (for dev) was taking a lot longer and it seems to be the 350Mb of data in the linteItems table is the main cause.....(that and the `craft_templatecachequeries` is kinda massive too...)

**Comment by lukeholder** [comment]
This should now be fixed on the develop branch: acc17d3e3e794c897a04c234517ac214c861072e
