### ISSUE TITLE
Order Status Badges are counting soft deletes

### ISSUE THREAD

**Issue by matternow** [craftcms/commerce#852]
### Description

Order status badges are including soft deleted orders — per the below screenshot, "All Orders" is showing the proper badge count, while the individual statuses are including soft-deleted orders.

<img width="235" alt="image" src="https://user-images.githubusercontent.com/47116649/57468013-a5bc2880-7251-11e9-8505-b8adbb940c6a.png">

### Steps to reproduce

1. Have soft deleted as well as non-soft deleted orders in the system
2. Look at the badge counts

**Comment by lukeholder** [comment]
This has been fixed in the recent release. Can you confirm you are on the latest?

**Comment by lukeholder** [comment]
This should be fixed on the latest. Closing.
