### ISSUE TITLE
Data too long for column 'skuFormat'

### ISSUE THREAD

**Issue by circa1977** [craftcms/commerce#853]
### Description

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'skuFormat' at row 1

Here's what I'm trying to submit, concatenating values from 3 variant fields.

{product.slug|upper}-{product.synergyId|upper}-{hotBreakfastBuffetEggsChoice[0].synergyId|upper}E{hotBreakfastBuffetEggsChoice[0].id}-{hotBreakfastBuffetStarchChoice[0].synergyId|upper}E{hotBreakfastBuffetStarchChoice[0].id}-{hotBreakfastBuffetMeatChoice[0].synergyId|upper}E{hotBreakfastBuffetMeatChoice[0].id}

### Steps to reproduce

1. Create a new Product Type with the above as the SKU Format.

### Additional info

- Craft version: 3.1.26, Commerce 2.1.5.2
- PHP version: 7.1.26
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Commerce

**Comment by circa1977** [comment]
I altered the table to make this VARCHAR(512) to get past the error.

**Comment by lukeholder** [comment]
Yeah, we don't expect SKUs longer than 255 chars. Will think about changing the limit.

**Comment by lukeholder** [comment]
Decided to leave the limit at 255, and added a nicer validation error. Please consider a shorter SKU format strategy., thanks!

**Comment by circa1977** [comment]
If there's no limit to the number of variant fields, and SKUs are unique to variants, shouldn't we be able to add all the variants to the SKU?

**Comment by lukeholder** [comment]
SKUs are unique to variants, so not sure what you mean by `add all the variants to the SKU`?

**Comment by circa1977** [comment]
> not sure what you mean by add all the variants to the SKU?

The reason I'm hitting the field constraint is that I'm building up a SKU containing ID values from each of the variant fields.

The product has three variant fields. Each of those are a substitution or optional sub-product. (The products are catering menu items—with configurable options.) We're migrating them from a legacy system and most—but not all—of the migrated products have a legacy ID we want to be able to match on for future update imports.

So my variant SKUs are:

1. The main product's slug
2. + its legacy ID
3. + the legacy ID for each variant field's selected product
4. + because some of those don't have a legacy ID and I need unique values, each variant field's selected product's entry ID

All of which is to say: If I can add three variant fields to my product, I should be able to pluck ID values from each to build up my unique SKU for each variant in a meaningful way...

...and if I can add 20 variant fields to my product, the implication here is that the SKU field wouldn't accommodate concatenating values from all 20 variant fields in its formula.

I've tackled the most complex breakfast menu spread (three variant fields), but have been told that lunch & dinner are more complex. I've positioned the SKU as an identifier that will reflect the configured options.

If Craft is not imposing a limit on the number of variant fields, should it be imposing an implicit limit on how many variable field references I can include in the SKU, due to a character limit?

**Comment by circa1977** [comment]
Hey, @lukeholder!

I think my request still stands: If you can have `n` number of variants, you should be able to have enough space in your `skuFormat` to reference all of `n` variants, and 255 isn't enough.

HOWEVER, I think a good question back at me here would be "why so many variants?" :)

I was looking to put all those IDs in each variant SKU because I envisioned having a dropdown for each of the three variant options, and using JavaScript to map those selections to variant SKUs.

The [better answer](https://craftcms.stackexchange.com/questions/30364/get-and-display-a-products-variant-fields-in-twig/30366#30366) there is probably to use options.

**Comment by lukeholder** [comment]
The next Craft release (3.3.1) will make it possible for you to include a front-end template from the Automatic SKU Format setting (and other settings like it).

So you can change the value to something like:

{% include '_mySkuFormat' %}

And then create a _sku.twig file in your templates/ folder, which contains all of that Twig code.

If you want to get that change ahead of time, change your craftcms/cms requirement in composer.json to:

"require": {
"craftcms/cms": "dev-develop#db67c285b2c89d86a0a1bfc68b2cfdd199a54425 as 3.3.0.1",
"...": "..."
}
Then run composer update.
