### ISSUE TITLE
Integrity constraint violation (1062 Duplicate entry) after deleting order in CP and then customer attempts to add to cart

### ISSUE THREAD

**Issue by portnull** [craftcms/commerce#854]
### Description
I have the same issue as described here: https://github.com/craftcms/commerce/issues/700

> If a visitor's cart is deleted from the CP, and then the visitor attempts to add an item to their cart, An Integrity constraint violation is thrown, with a duplicate entry for key commerce_orders_number_unq_idx.

The issue first started today after I cleaned up old carts from testing. I do have "Verbb Events" installed to sell event tickets.

The cart counter also keeps showing a quantity of "1" after the order ist paid for and the cart should be empty - if I try to add a product now the error occurs.

I have deleted all orders from commerce_orders and all purchased tickets from events_purchasedtickets.

### Steps to reproduce

Visit front-end, add item to cart
Visit back-end, delete cart
Visit front-end, attempt to add item to cart
Exception is thrown

### Additional info

- Craft version: Craft: 3.1.36
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.25
- Commerce: 2.1.5.2
- Verbb Events: 1.0.2.1

**Comment by lukeholder** [comment]
I have fixed the issue for when adding to the cart - the new cart generated (after the deleted one is gone) was not being saved. 

Updating a line item passes in the line item ID, so a `Line item not found` exception is correct here. 

This should only really be happening in development. If a customer experiences the exception, a page refresh will fix the issue since a new cart will be generated.

**Comment by samhibberd** [comment]
@lukeholder I'm not sure this fix has worked for me :( We are getting the cart from our site module via the service, but no different and the exception is being thrown when trying to create / get any cart from within this following call, after deleting any order or cart within the cp:

`$cart = CommercePlugin::getInstance()->getCarts()->getCart(true);`
