### ISSUE TITLE
Integrity constraint violation when a user tries to add items to cart right after paying for an order

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#860]
### Description
`SQLSTATE[23000]: Integrity constraint violation: 
1062 Duplicate entry '0e4335ebc18a452d45794bab41aa1b53' for key 'commerce_orders_number_unq_idx'
The SQL being executed was: 
INSERT INTO `commerce_orders` (`id`, `number`, `reference`, `itemTotal`, `email`, `isCompleted`, `dateOrdered`, `datePaid`, `shippingMethodHandle`, `paymentSourceId`, `gatewayId`, `orderStatusId`, `couponCode`, `total`, `totalPrice`, `totalPaid`, `currency`, `lastIp`, `orderLanguage`, `paymentCurrency`, `customerId`, `registerUserOnOrderComplete`, `returnUrl`, `cancelUrl`, `message`, `paidStatus`, `dateCreated`, `uid`, `dateUpdated`) 
VALUES (307, '0e4335ebc18a452d45794bab41aa1b53', NULL, '0', 'ericchantigny@msn.com', 0, NULL, NULL, 'localPickup', NULL, NULL, NULL, NULL, '0', '0', '0', 'CAD', '::1', 'en-US', 'CAD', 1, NULL, NULL, NULL, NULL, 'unpaid', '2019-05-13 13:22:29', 'ae81b4df-6bd4-4abe-bac7-52dca14f47cf', '2019-05-13 13:22:29')`

### Steps to reproduce

1.  Complete checkout of an order
2.  Right after, try to add items to the cart.  I'm using ajax and getting the error above.

### Additional info

- Craft version: Craft Pro 3.1.26
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins & versions:
Craft Commerce | 2.1.5.2
Moneris for Craft Commerce 2 | 1.0.2  (my own gateway)

**Comment by rob-baker-ar** [comment]
I have this exact same issue

(PHP 7.2.17, MySQL 5.7.26, Craft 3.1.26, Commerce 2.1.5.2 - WorldPay, PayPal, Stripe gateways).

**Comment by echantigny** [comment]
@rob-baker-ar I'll be digging in the code to see if I can't fix this quickly today.  I need it for a launch this week.  If you are doing the same, let me know.

**Comment by echantigny** [comment]
I think the issue is coming from
vendor/craftcms/commerce/src/services/Carts.php
Line 67

`$number = $this->getSessionCartNumber();`

and then, when the cart isCompleted:
```
$this->_cart = new Order();
$this->_cart->number = $number;
```

This looks like a piece of code that could affect quite a bit of other things.  I'm not sure how to fix this and make sure I don't break anything else.

**Comment by lukeholder** [comment]
Thanks for reporting everyone, fixed for the next release.
