### ISSUE TITLE
Order::EVENT_AFTER_ORDER_PAID not triggered for when paid status is partial?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#861]
It doesn't look like the `Order::EVENT_AFTER_ORDER_PAID` event is triggered under the following conditions:

- Order that has been both completed and paid 
- Order is subsequently updated with new line items (added by a module). 
- The order would have a paid status of Partial
- The order is then Paid in full

At this point the event is not triggered, but I think it should be, I think caused by `$justPaid` being false due to `$this->datePaid` value not being null:

https://github.com/craftcms/commerce/blob/a6a1c5d01008f978f0ea382b81cd5f5d2f2d1a58/src/elements/Order.php#L565

**Comment by andris-sevcenko** [comment]
I'll loop in @lukeholder on this, but my gut feeling would be that the module that is adding the new line item, should be setting the `datePaid` to `null` if you need the event to be triggered again.

I mean, in broad strokes, you can consider the property to indicate when the order became paid in full, so adding a new line item would void that.

Of course, that brings up the philosophical question of whether an order that is paid for and then partially refunded should be considered paid or not, but that's getting in weeds.

**Comment by lukeholder** [comment]
Agree, the event is only for when the order is paid in full and right now we have no concept order editing at the moment. Your module would need to put the cart back to `datePaid = null` if you want the event to trigger again.

**Comment by samhibberd** [comment]
Thanks @lukeholder @andris-sevcenko makes sense.
