### ISSUE TITLE
Shipping adjustments of value 0 are not shown (e.g. free shipping/pickup)

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#864]
### Description

In the order details view, shipping adjustments of $0 value are not shown in any way.

This means we can no longer distinguish between Free Shipping and Pick Up order in the back end when processing orders.

(We are using a custom shipping module, but there are various valid $0 options presented to users for various scenarios).

### Steps to reproduce

View orders.

Order should have a visible line for shipping even if the value of the shipping was $0...but the only show up if there is a > $0 value it seems

![image](https://user-images.githubusercontent.com/731309/57739097-8f9ce500-76f5-11e9-847b-a3f2dc6e3c04.png)

I have hacked this into the _orderDetails.html template for now:

```
                {%  if order.adjustmentsTotalByType("shipping") == 0 %}
                <tr>
                    <td>
                        <strong>Shipping Adjustment</strong><br>
                         {{ craft.imagescience.getShippingDescriptionFromHandle(order.shippingMethodHandle) }} <span class="info"><strong>{{ order.shippingMethodHandle }}</span>
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <span class="right">{{ order.adjustmentsTotalByType("shipping")|currency(order.currency)}}</span>
                    </td>
                    <td></td>
                </tr>
                {% endif %}
```
(and note I think I have to use my own function to get the description, which is another issue really!)

### Additional info

Commerce 2.1.4

**Comment by bossanova808** [comment]
(I just now note the shipping handle at least is in the right column, but this means there are two places to check for these details really, which is not ideal and I personally think they should be shown in the main order details view as that is where we are generally looking for them since most orders have a shipping cost...).  Also the shipping handle is not a great, human friendly value to use in that right column...

**Comment by lukeholder** [comment]
Shipping method handle is the best way to know the user's prefered shipping method for the order.

Zero is the default value for 'base shipping cost' on a shipping rule.

If we added an adjustment of zero for every base shipping cost it would appear on every order, even when the rule wanted to add shipping costs to the line items and had left the rule with a base shipping cost of zero on purpose.

Hope that makes sense.

We could look at adding an option (checkbox) to the shipping rule: "Add base shipping rate to order even if zero", but that would be a change to the interface. I will leave this ticket open as an enhancement.

**Comment by lukeholder** [comment]
If zero value shipping adjustments were being made in Commerce 1 it wasn't on purpose sorry.

**Comment by bossanova808** [comment]
I think I haven't explained myself well - I'm not looking for a change in behaviour at the adjustment level, just a change in display on that page...that is, if an order has a shipping method chosen on it, show it in that same spot, even if the value of that method happens to be $0.  Does that make sense?

**Comment by bossanova808** [comment]
Oh I think maybe it is me understanding.  Probably because I use a custom shipper entirely and bypass the rules system etc.

I see your point, sorry.  It would be great to have some method to display them without hacking the templates though (e.g. $0 are shown but hidden, then we could use come CP JS to show them?  Not great but it works...right now I have to protect this template on upgrades etc, which is a pain.

**Comment by lukeholder** [comment]
Would adding a `shippingMethodDescription` field to the order, placed below the handle in the right column be enough?

**Comment by bossanova808** [comment]
Well it would be an improvement, sure (I think that the description should be shown in the right column anyway, not the handle, just as a general thing) - but I personally would prefer the $0 shipping to be shown in the main bit too (obviously if shipping is not set on the order, then nothing needs to be shown, but if any shipping is set it's handy to have it there, whatever the cost, simply because that is the most logical place the order processing people will be looking).

It's really just a usability thing to make sure order processing goes as smoothly as possible...it's more consistent for any shipping method that is set to be shown there, even if the calculated cost is $0.

**Comment by bossanova808** [comment]
So looking at 3.1.4 - if you just put the description (instead of (or in addition to) the handle) - here - that would cover this fine:

![image](https://user-images.githubusercontent.com/731309/82520564-da063c80-9b67-11ea-8619-9505b5261651.png)

Thanks!

**Comment by lukeholder** [comment]
Added an issue for this here that is more clear: https://github.com/craftcms/commerce/issues/1472
