### ISSUE TITLE
Commerce's Order Index Errors on Full Name, etc.

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#876]
### Description

Not sure when this started happening but upgrading a client's site today revealed a couple of bugs.

When going to view incomplete orders, if I have certain fields enabled—most notably the Full Name fields—Commerce's display will break unceremoniously. 

It looks like it's expecting values where there are none. If someone abandoned cart, for example, these won't necessarily show up.

![Screen Shot 2019-05-21 at 12 25 55 PM](https://user-images.githubusercontent.com/3707869/58117188-9fb83700-7bc3-11e9-9b34-2b765760ccb8.png)

![Screen Shot 2019-05-21 at 12 26 51 PM](https://user-images.githubusercontent.com/3707869/58117280-d2622f80-7bc3-11e9-907a-89de9c2d29ea.png)

![Screen Shot 2019-05-21 at 12 32 41 PM](https://user-images.githubusercontent.com/3707869/58117593-8b286e80-7bc4-11e9-93e9-e181491ec101.png)

Errors raised:

```
{
    "error": "Call to a member function getFullName() on null"
}



{
    "error": "Call to a member function getLabelHtml() on null"
}
```

Also, getting:
``Failed to load resource: the server responded with a status of 500 ()``

When viewing the error:
``Request must accept JSON in response``

From: 
``/actions/element-indexes/get-elements``

### Steps to reproduce

1. Enable certain fields on the orders page (especially Active, Inactive, Attempted Panes)
2. Since users haven't completed checkout, Craft will break on those empty fields.

### Additional info

- Craft version: 3.1.27
- Commerce version: 2.1.6.1
- PHP version: 7
- Database driver & version: 5.7

**Comment by billythekid** [comment]
I found that Billing Full Name, Shipping Full Name and Billing Method etc will cause these errors in the tables.

Disabling those fields from the table makes it go away.

**Comment by RitterKnightCreative** [comment]
@billythekid yeh that's my workaround too...

**Comment by bossanova808** [comment]
Happening here, too

**Comment by lukeholder** [comment]
Thanks, fixed for next release.
