### ISSUE TITLE
Shipping and Billing addresses duplicated in DB on checkout

### ISSUE THREAD

**Issue by cimocimocimo** [craftcms/commerce#877]
### Description

When calling the pay action in the final step of checkout the addresses associated with the customer's order are duplicated in the database. This is NOT reflected in the customer's address list (in the default template) since the commerce_customer_addresses table is updated with the new address ids in commerce_addresses.

This is causing an issue since we sync new addresses to the Recurly Gateway for customer accounts. When the addresses are duplicated in Craft new Shipping Addresses are created in Recurly which has a 20 address limit. We are quickly hitting this limit in testing.

### Steps to reproduce

1. Setup a new default Craft Commerce install.
2. Copy the starter store templates to the new site's template folder.
3. Update the Dummy gateway to be type Manual to allow checking out without a CC.
4. Add a default shipping and billing address for your customer account at /shop/customer/addresses.
5. Add any of the default products to your cart and checkout but don't pay.
6. Check the commerce_addresses table to make sure you see the single address you created for your customer.
7. Complete the payment step to trigger the bug.
8. Check commerce_addresses table again and you should see two new copies of the original address.

### Additional info

- Craft version: 3.1.28
- PHP version: 7.3.4
- Database driver & version:
PDO Driver for PostgreSQL | enabled
PostgreSQL(libpq) | PostgreSQL 11.2 on x86_64-apple-darwin18.2.0, compiled by Apple LLVM version 10.0.0 (clang-1000.11.45.5), 64-bit

- Plugins & versions: 
craftcms/cms: 3.1.28
vlucas/phpdotenv: 2.6.1
craftcms/commerce: Current tip of GitHub devel branch.

**Comment by andris-sevcenko** [comment]
This behavior is on purpose to keep a record of the address that was used during the purchase. If there was a relation to a single billing or shipping address, the user could update their user preferences at a later point, changing the data of a completed order.

**Comment by cimocimocimo** [comment]
Yup, discovered that when I was doing some further investigation and was about to update/close the issue. Sorry for the trouble.

**Comment by andris-sevcenko** [comment]
No trouble at all.
