### ISSUE TITLE
Attempted payment listing shows orders without any transactions in it

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#880]
### Description
Title is self explanatory, but here's some screenshots:

![2019-05-23 11_22_56-Orders - Commerce - Great Boardgames](https://user-images.githubusercontent.com/4933333/58265176-2e0bf480-7d4d-11e9-9b55-179dbfded988.png)
![2019-05-23 11_23_08-Cart 9099dc73a7518c1dccfb1b405db7e820 - Great Boardgames](https://user-images.githubusercontent.com/4933333/58265177-2e0bf480-7d4d-11e9-89cf-b8123e1bc148.png)

### Steps to reproduce

1. Start creating a new cart.
2. I went all the way through the checkout process (addresses, shipping) but didn't hit the pay button. 
3. Go in the CP and the order is in the attempted payment list. 

### Additional info

- Craft version: Craft Pro 3.1.27
- Craft commerce: 2.1.6.1
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
