### ISSUE TITLE
Not able to use Manual gateway to make payment in CP

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#881]
### Description
I have a Moneris gateway that works for the front-end part of the site.

I also want the manual gateway in the backend because my client uses that sometimes for phone/onsite orders.  I am getting an error trying to make that transaction in the CP.

### Steps to reproduce

1. Have the Manual gateway in the Gateways, but do not enable for Customers during checkout
2. Create a front-end cart, but don't pay for it.
3. Go in the CP and try to "Make Payment" with the Manual gateway.
4. Gateway not allowed error

```
yii\base\InvalidConfigException: Gateway not allowed. in C:\wamp64\www\Great-Boardgames\vendor\craftcms\commerce\src\elements\Order.php:1546
Stack trace:
#0 C:\wamp64\www\Great-Boardgames\vendor\craftcms\commerce\src\controllers\PaymentsController.php(158): craft\commerce\elements\Order->getGateway()
#1 [internal function]: craft\commerce\controllers\PaymentsController->actionPay()
#2 C:\wamp64\www\Great-Boardgames\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#3 C:\wamp64\www\Great-Boardgames\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 C:\wamp64\www\Great-Boardgames\vendor\craftcms\cms\src\web\Controller.php(109): yii\base\Controller->runAction('pay', Array)
#5 C:\wamp64\www\Great-Boardgames\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('pay', Array)
#6 C:\wamp64\www\Great-Boardgames\vendor\craftcms\cms\src\web\Application.php(297): yii\base\Module->runAction('commerce/paymen...', Array)
#7 C:\wamp64\www\Great-Boardgames\vendor\craftcms\cms\src\web\Application.php(565): craft\web\Application->runAction('commerce/paymen...', Array)
#8 C:\wamp64\www\Great-Boardgames\vendor\craftcms\cms\src\web\Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 C:\wamp64\www\Great-Boardgames\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 C:\wamp64\www\Great-Boardgames\public_html\index.php(21): yii\base\Application->run()
#11 {main}
```

### Additional info

- Craft version: Craft Pro 3.1.27
- Craft commerce: 2.1.6.1
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins:  My own Moneris gateway

**Comment by bossanova808** [comment]
To piggy back on to this, even if the gateway IS enabled for the back end, and you _can_ therefore get the payment through, the order remains unpaid even after the successful transaction:

![image](https://user-images.githubusercontent.com/731309/58302052-6e8e6f80-7e2c-11e9-8e4e-454b2a05509f.png)

**Comment by lukeholder** [comment]
@bossanova808 you are looking at successful 'Authorization' transactions. You need to click 'Capture' to actually account for the money being received, and added towards the total paid.

**Comment by bossanova808** [comment]
LOL - ok, I am sure I should know that!  

But that language is...not great.  Should be 'Receive Payment' really.  To match what it is used in order processing/accounting.

**Comment by echantigny** [comment]
@bossanova808 I'm not sure if this is a regional thing, but authorize and capture are exactly what my payment provider uses too, Moneris.

Authorize means that you have checked if the credit card is valid and can accept the charge, but you did not take any money yet.

Capture means that you take the money right away if the card is valid.

**Comment by bossanova808** [comment]
Right - with credit card payments I know that is indeed used (it's still not great language, even if it is commonly used, though!)....but not with manual payments/gateways, which are usually used for things like direct fund transfers and cheques etc. - but I guess given the larger context...sure.

**Comment by echantigny** [comment]
@bossanova808. Ah, of course.  Forgot what this thread was about.  We'll, I didn't know that because I can't get to that point.  But the manual dummy gateway, the default one, doesn't have those distinctions.

**Comment by echantigny** [comment]
@lukeholder This looks like it's a configuration issue, but I'm not sure what that config is that's giving me issues.  I have the exact same DB on both local and prod servers and it works on prod but not locally.  I thought it was because of my commerce-gateways.php file, so I removed it, but the same issue is rising after.

If I pinpoint the issue, I'll update this.

**Comment by lukeholder** [comment]
Please let me know if you can reproduce and I will reopen.
