### ISSUE TITLE
Email Templates:  The date seems to think it's in a timezone, but still UTC

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#882]
### Description

I'm printing the full date and time in my email template and it's always displaying as UTC instead of the actual time my CP is set into.

Using:  `order.datePaid|date("l jS mm Y, h:i:s A")`

If I print it in a normal webpage (order detail), I get the correct time
Tuesday 28th May 2019, 02:07:08 PM

If I print it in a email twig template,  2:07:08 PM is the correct time:
No timezone: Tuesday 28th May 2019, 06:07:08 PM

Adding timezones to date()
 `order.datePaid|date("l jS mm Y, h:i:s A", 'timezone')`

Australia/Sydney: Wednesday 29th May 2019, 08:07:08 AM AEST 
America/Los_Angeles: Tuesday 28th May 2019, 03:07:08 PM PDT 
America/New_York: Tuesday 28th May 2019, 06:07:08 PM EDT 
Europe/London: Tuesday 28th May 2019, 11:07:08 PM BST 

America/New_York is my timezone, but it's 02:07:08PM here.  So, the datePaid think it's in the correct timezone, but it's not, making it impossible to adjust it by adding my timezone to it.

### Additional info

-Craft version: Craft Pro 3.1.27
-Craft commerce: 2.1.6.1
-PHP version: 7.2.4
-Database driver & version: MySQL 5.7.21

**Comment by timeverts** [comment]
@lukeholder, I am experiencing the same issue when trying to output `order.dateOrdered` in an email.

For instance, for this order in the CMS:
![image](https://user-images.githubusercontent.com/15150632/60157731-04e5f480-9822-11e9-8dbe-b5f07b16f42d.png)

Outputting the `order.dateOrdered` in an email template using `{{ order.dateOrdered|datetime('long') }}` outputs `26 June 2019 at 6:41:07 am AWST`, which is clearly incorrect.

**Comment by nfourtythree** [comment]
Hey @echantigny & @timeverts 

Just looking into this, assume it is still an issue?

Could you do me a favour and drop into the `orders` table in the DB and let me know what the `orderLanguage` is for those orders. Also, let me know if that matches up to what you expect.

Thanks.

**Comment by nfourtythree** [comment]
@echantigny and the `dateOrdered` date-time is the correct UTC time?

**Comment by nfourtythree** [comment]
Hi @echantigny & @timeverts 

I have looked into this further and I am unable to replicate the issue you mentioned. When I don't specify the timezone it defaults to the Craft timezone both in a template and when rendering an email.

If I then supply a different timezone I get the correct datetime returned that I would expect.

Trying to think of edge cases here, what are the timezones set to for your:
- Server
- PHP
- Craft

I am just wondering if this mismatching if happening elsewhere.

Thanks.

**Comment by timeverts** [comment]
Hi @nfourtythree 

It's been a while since I've looked into this, but I will take another look at this today and see if we can still replicate the issue here. I'll report back later.

**Comment by timeverts** [comment]
@nfourtythree ,

I've just run another test here and I am still seeing the same issue. Did a transaction at 9:18 AWST and it's coming out as `30 August 2019 at 1:18:11 am AWST` which is actually the UTC time of the date ordered.

Our date ordered is the correct UTC time in the database and the time zone is `en-AU` which is correct for us here in Perth, Australia. 

Here's some other details:
- PHP default timezone: `Australia/Perth`
- Server time zone: `Australia/Perth (AWST, +0800)`
- Craft time zone: `UTC+8 (AWST) – Australia/Perth`
- Commerce: 2.1.11
- Craft: 3.2.9




Here is

**Comment by nfourtythree** [comment]
Hey @timeverts 

I think I have tracked this down now! Have pushed up a fix that should be included in the next release.

The key, I believe, was it was only effecting emails for new orders. If an email was triggered by changing an order status in the CP they were working as expected.

Thanks for your help and patience with this.

**Comment by echantigny** [comment]
Thank you @nfourtythree !  Will check it out as soon as it's released (or maybe on the dev branch).
