### ISSUE TITLE
Subscription field layouts are not showing more than the first tab when viewing a specific subscription

### ISSUE THREAD

**Issue by ldennison-bsd** [craftcms/commerce#884]
### Description
When viewing a specific subscription (e.g. /admin/commerce/subscriptions/XXX), only the first tab of the "Subscription Fields" field layout is shown. This is evidenced by the code: https://github.com/craftcms/commerce/blob/develop/src/templates/subscriptions/_edit.html#L33 . Obviously, all tabs should be shown on the subscription details, unless there is some critical reason for this behavior.

### Additional info
Although likely unrelated, it may be important to note these subscriptions were created with the Stripe gateway.

- Craft version: 3.1.20.1
- PHP version: 7.3.3
- Database driver & version: MariaDB 10.1.38
- Plugins & versions: Stripe for Commerce

**Comment by lukeholder** [comment]
Thanks, fixed for the next release.
