### ISSUE TITLE
Trailing Whitespace not Trimmed from `couponCode` on Discount save

### ISSUE THREAD

**Issue by sbossarte** [craftcms/commerce#894]
### Description

If a discount has a coupon code that is entered with trailing whitespace, it can still be added to a cart, but the discount doesn't apply.

### Steps to reproduce

1. Create discount with the coupon code `ABCD `, note the space at the end
2. Attach coupon `abcd` to the cart
3. Cart says coupon is applied, but not the discount
4. Change coupon code to `ABCD`
5. Attach coupon `abcd` to the cart
6. Coupon is applied as well as the discount 

### Additional info

- Craft version: Craft Pro 3.1.29
- PHP version: 7.2.18
- Database driver & version: MySQL 5.7.19
- Plugins & versions: 2.1.6.1 pro

**Comment by lukeholder** [comment]
@sbossarte can you confirm in step 5 you meant to type `bcd`?

**Comment by sbossarte** [comment]
It was meant to be `abcd`.
