### ISSUE TITLE
Change "admin/commerce/orders" URL when filtering

### ISSUE THREAD

**Issue by j-greig** [craftcms/commerce#901]
If the slug changed to `admin/commerce/orders/new` or `admin/commerce/orders/shipped` it would then be possible to create bookmarks for these views, or use the Control Panel Nav plugin to add them to the sidebar.

Asking because of a client request for the latter.

Thanks :)

![image](https://user-images.githubusercontent.com/616194/59343200-367b9d80-8d03-11e9-9e5f-15656431d7a8.png)

**Comment by nfourtythree** [comment]
Code for this has been pushed and will be included in the `2.2` release
