### ISSUE TITLE
My address showing when I "login as" to another user / customer

### ISSUE THREAD

**Issue by kevadamson** [craftcms/commerce#903]
Not sure if it is my own code or a core issue (my code seems to be fine when comparing with templates), but when I "login as" as another user / customer my own delivery / billing address show's in their address list.

**Comment by Sam-Black-0013** [comment]
Yeah me too

**Comment by bossanova808** [comment]
Not happening here...how are you retrieving addresses?  Something like `{% set allAddresses = craft.commerce.customers.customer.addresses %}` ?

**Comment by kevadamson** [comment]
```
{% set customer = craft.commerce.customers.customer %}
{% set primaryBillingAddress = customer.getPrimaryBillingAddress() %}
{% set primaryShippingAddress = customer.getPrimaryShippingAddress() %}

{% if customer.addresses|length %}

{% for address in customer.addresses %}
```

Just to clarify: When I'm admin and have an address, and then "login as" to just a customer or someone with less admin permissions.

**Comment by lukeholder** [comment]
Hi, can you please type clear steps to reproduce. Thanks.

**Comment by kevadamson** [comment]
I log in. I then go to users, select a user, and then "login as" them. In the addresses section of their account it is showing my own address in with theirs. Make sense?

**Comment by Sam-Black-0013** [comment]
I posted about a while back @lukeholder  [here](https://github.com/craftcms/commerce/issues/755) 
Everytime we login as one of our customers, our addresses get saved to theirs. 
We followed everything in commerce's docs and templates

**Comment by bossanova808** [comment]
Luke I've just seen this happen today.  Logged in as admin, I go to users, select a customer, and then login as them.

Am up to date with Craft, Commerce and all addons (upto yesterday).

I expect it to clear my cart and only bring up the customer addresses.  My cart is NOT cleared, and as I go to checkout I see both their addresses and my own in the list of addresses we retrieve.

That's a definite issue - we like to 'login as' to guide customers through things, if they come in and want to know how something works.  It's not a good look for weird addresses (like 'Test McTesty who live on 1 Test Street etc) -to show up...

**Comment by lukeholder** [comment]
I have just been able to reproduce, my initial attempt to reproduce didn't work as I was no retrieving the cart: https://jmp.sh/UKYYUXL

I can see what the issue is and will make a fix soon.

**Comment by kevadamson** [comment]
@lukeholder Thank you :)
