### ISSUE TITLE
Active cart expected behaviour

### ISSUE THREAD

**Issue by kevadamson** [craftcms/commerce#906]
Is it an expected behaviour that when logged in the cart is shown as active, even though there is nothing in it? If so what is the reasoning for this? I would have thought active would have meant something in it? Thanks :)

**Comment by lukeholder** [comment]
Sorry can you please explain a little more. Unclear what you mean.

**Comment by kevadamson** [comment]
OK so I log in, click the commerce tab > orders > active carts. It then shows me as having an active cart with a value of 0.00. Is this correct? I would have thought active would mean "something in it" ...

**Comment by lukeholder** [comment]
If you had something in your cart at one stage and then removed it, it is still an active cart. We could make an option to hide empty active carts?

**Comment by kevadamson** [comment]
> We could make an option to hide empty active carts?

That would be awesome!

**Comment by RitterKnightCreative** [comment]
Noticed this as well. 

It seems a new cart is being created whenever my client logs into the website to harvest new orders, for example, even if there's nothing in it. 

I don't recall that happening before.

**Comment by lukeholder** [comment]
A cart no longer gets created unless they have previous orders we need to merge in.

**Comment by lukeholder** [comment]
Will be in the next release.
