### ISSUE TITLE
Bug - Following documentation throws fatal error

### ISSUE THREAD

**Issue by anchovy** [craftcms/commerce#909]
### Description
Following the documentation for EVENT_BEFORE_CAPTURE_PRODUCT_SNAPSHOT (& EVENT_BEFORE_CAPTURE_VARIANT_SNAPSHOT) 
https://docs.craftcms.com/commerce/v2/events.html#product-related-events throws a fatal error.

Expected behaviour is that if `$e->fields = null` no custom fields would be removed from the order snapshot for the product (& variant if using EVENT_BEFORE_CAPTURE_VARIANT_SNAPSHOT).

### Steps to reproduce

1. Subscribe to the event in a plugin and set the fields to null.
```
        Event::on(Variant::class, Variant::EVENT_BEFORE_CAPTURE_PRODUCT_SNAPSHOT, function(CustomizeProductSnapshotFieldsEvent $e) {
            $product = $e->product;
            $e->fields = null;
        });
```
2. Fatal error is thrown:
```
"Invalid argument supplied for foreach(), .../vendor/craftcms/commerce/src/elements/Variant.php(491)#0
```

### Additional info

Craft version: Craft Pro 3.1.29
PHP version: 7.2.14
Database driver & version: MySQL 5.7.22
Plugins & versions:
Asset Rev	6.0.2
Button Box	2.0.3
Contact Form	2.2.5
Contact Form Extensions	1.1.6
Contact Form Validation	0.0.1
Control Panel CSS	2.1.0
CP Field Inspect	1.0.5
Craft Commerce	2.1.7
Field Manager	2.1.0
Migration Manager	3.0.22
Position Fieldtype	1.0.14
Redactor	2.3.3.2
SEO	3.5.4
Spoon	3.3.7
Super Table	2.1.20
Typed link field	1.0.19
Width Fieldtype	1.0.6

**Comment by lukeholder** [comment]
Thanks for reporting. The docs were wrong, only an array can be set. I have updated the docs and set an example of setting all custom fields back on the snapshot. https://docs.craftcms.com/commerce/v2/events.html#product-related-events
