### ISSUE TITLE
Tax removed as discount

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/commerce#910]
Showing the removed tax as a discount does not play well with customers, could we have it as a tax type rather than a discount type so it all show as total tax rather than a mixture?

user case:

default tax is uk and prices entered include tax. When a customer from another country adds something to their cart, showing all the discounts applied includes a UK tax removed. So there is no easy way to keep discounts and tax seperate.

**Comment by lukeholder** [comment]
What if we introduces a new 'price' adjustment type?

**Comment by samuelbirch** [comment]
what do you seeing being in that "price" adjustment type?

In my mind, it makes sense to have all tax related adjustments in a "tax" type.

**Comment by lukeholder** [comment]
The removal of tax from the price of a product is not a tax though, it is a discount (or a price adjustment) that reduces the price of the product.

 If we called this price reduction a negative tax wouldn't that be incorrect?

**Comment by samuelbirch** [comment]
you are correct, 

i guess in my case it's removing one tax and then applying another one, and it looks strange showing a tax discount in discounts and then a tax amount applied within the tax section.

would a discount type work? - where you could get all tax discounts, get all shipping discounts, get all product discounts? - this could also allow 3rd party adjusters to register discount types?

**Comment by lukeholder** [comment]
Moving discussion to #983
