### ISSUE TITLE
Zero Value Manual Gateway Accepts Priced Order

### ISSUE THREAD

**Issue by JustJarethB** [craftcms/commerce#911]
### Description
It seems that the `Only allow this gateway to be used for zero value orders` does not work. It accepts non-zero orders. 

### Steps to reproduce

1. Create Manual Gateway with `Only allow this gateway to be used for zero value orders` enabled.
2. Set gatewayId to said gateway using action `commerce/cart/update-cart`
3. Process order with `totalPrice` > 0 using action `commerce/payments/pay`

### Additional info

- Craft version: 3.1.13
- Commerce version: 2.0.4

**Comment by lukeholder** [comment]
This should be fixed in e59ae30debd5fe0c9ed706cbf0856424d94d4e96 Once the update comes up, let me know.
