### ISSUE TITLE
Disabled Gateway is still usable

### ISSUE THREAD

**Issue by JustJarethB** [craftcms/commerce#912]
### Description
Due to a problem encountered, I switched off a Manual gateway (disabled `Enabled for customers to select during checkout?`) but upon further inspection, this simply removed the gateway from the `allCustomerEnabledGateways` list, but its ID is still usable in a payment action, which causes a security concern regarding form manipulation.

### Steps to reproduce

1. Create `Manual` gateway
2. Disable Manual Gateway
3. POST a `commerce/cart/update-cart` form with `gatewayId` set to above gateway
4. POST a `commerce/payments/pay` form

### Additional info

- Craft version: 3.1.13
- Commerce version: 2.0.4

**Comment by lukeholder** [comment]
I have a fix ready for this which will be published very soon.
