### ISSUE TITLE
Manual Gateway error

### ISSUE THREAD

**Issue by hegrobler** [craftcms/commerce#914]
### Description
Receiving the following error when selecting the Manual Gateway that I configured: 
`Gateway doesn’t support purchase`

In Commerce 1 Manual Gateway worked out the box, so just trying to clarify whether I'm supposed to be implementing a Purchase method in a custom plugin or something? 

### Steps to reproduce

1. Go to Commerce > System Settings > Gateways > New Gateway
2. Set values as follows: Name = EFT, Gateway = Manual, Credit Card Payment Type = Authorize Only (Manually Capture), Enabled for customers to select during checkout ? = true
3. From the front end, add a product to cart & upon checkout select the EFT gateway 

### Additional info

- Craft version: Craft Pro 3.1.29
- PHP version: 7.2.19
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
Calendar 2.0.20
Craft Commerce 2.1.7
Imager v2.1.10
Redactor 2.3.3.2
Site Switcher 2.1.0

**Comment by lukeholder** [comment]
I couldn't reproduce the error, did you maybe check the box that only makes the gateway usable with zero value orders?

**Comment by lukeholder** [comment]
@hegrobler Please let us know if the issue persists and we can look to re-open the issue. Thanks.
