### ISSUE TITLE
Deleted subscription plans appearing in template

### ISSUE THREAD

**Issue by cliveportman** [craftcms/commerce#916]
### Description
{% set plans = craft.commerce.getPlans().getAllEnabledPlans() %}
{% set plans = craft.commerce.getPlans().getAllPlans() %}

Both return plans that I've deleted and are no longer anywhere to be seen in the backend. Currently having to do this to hide them:
{% for plan in plans %}
       {% if plan.id != 4 and plan.id != 1 and plan.id != 3 %}

### Steps to reproduce

1. Delete a plan from within the store's settings.
2. View template.

### Additional info

- Craft version: Craft Pro 3.1.30
- PHP version: 7.3.6
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Craft Commerce 2.1.7

**Comment by satcreative** [comment]
Also having this issue when calling:
{% for plan in subscription.alternativePlans %}

Plans were deleted in the CP but still display in the template.

**Comment by lukeholder** [comment]
Looks like a bug. Will look into it now.

**Comment by lukeholder** [comment]
In your database, so you see your plans in the `commerce_plans` table with `isArchived` set to true?

**Comment by satcreative** [comment]
Yeah, the deleted items have `isArchived` set to true and a `dateArchived` has been assigned.

**Comment by lukeholder** [comment]
Not able to reproduce, could you send your DB to support@craftcms.com thanks.

**Comment by satcreative** [comment]
I've sent that across.

**Comment by satcreative** [comment]
Was this resolved in the end or could you not replicate it?

**Comment by lukeholder** [comment]
Just pushed a fix https://github.com/craftcms/commerce/commit/19b4f63dd220a7ef95f583c998d0db8b2f553073 will be in the next release in next couple hours.

**Comment by satcreative** [comment]
Oh great. Cheers Luke!
