### ISSUE TITLE
Error when the cart is created

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#917]
### Description
When i open the website and not logged in, an error occurs when getting the cart. 
The error comes from this file:

\vendor\craftcms\commerce\src\services\Carts.php ---> line 79 ---> Creating default object from empty value.

After i refresh the page, the website opens without any errors.

### Additional info

- Craft version: 3.1.30
- Commerce version: 2.1.7

**Comment by lukeholder** [comment]
Could you post more of the stack trace or more information? That line in the Carts service shouldn't be raising that error.

**Comment by Sam-Black-0013** [comment]
yii\base\ErrorException: Creating default object from empty value in C:\xampp\htdocs\project\vendor\craftcms\commerce\src\services\Carts.php:85
Stack trace:
#0 C:\xampp\htdocs\project\vendor\craftcms\cms\src\web\ErrorHandler.php(81): yii\base\ErrorHandler->handleError(2, 'Creating defaul...', 'C:\\xampp\\htdocs...', 85)
#1 C:\xampp\htdocs\project\vendor\craftcms\commerce\src\services\Carts.php(85): craft\web\ErrorHandler->handleError(2, 'Creating defaul...', 'C:\\xampp\\htdocs...', 85, Array)
#2 C:\xampp\htdocs\project\projectplugin\projectplugin\src\Projectplugin.php(394): craft\commerce\services\Carts->getCart(true)
#3 C:\xampp\htdocs\project\vendor\yiisoft\yii2\base\BaseObject.php(109): projectplugin\projectplugin\projectplugin->init()
#4 C:\xampp\htdocs\project\vendor\yiisoft\yii2\base\Module.php(158): yii\base\BaseObject->__construct(Array)
#5 C:\xampp\htdocs\project\vendor\craftcms\cms\src\base\Plugin.php(127): yii\base\Module->__construct('projectplugin', Object(craft\web\Application), Array)
#6 [internal function]: craft\base\Plugin->__construct('projectplugin', Object(craft\web\Application), Array)
#7 C:\xampp\htdocs\project\vendor\yiisoft\yii2\di\Container.php(384): ReflectionClass->newInstanceArgs(Array)
#8 C:\xampp\htdocs\project\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('projectplugin\\projectplugin\\One...', Array, Array)
#9 C:\xampp\htdocs\project\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('projectplugin\\projectplugin\\One...', Array, Array)
#10 C:\xampp\htdocs\project\vendor\craftcms\cms\src\services\Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#11 C:\xampp\htdocs\project\vendor\craftcms\cms\src\services\Plugins.php(230): craft\services\Plugins->createPlugin('projectplugin', Array)
#12 C:\xampp\htdocs\project\vendor\craftcms\cms\src\base\ApplicationTrait.php(1239): craft\services\Plugins->loadPlugins()
#13 C:\xampp\htdocs\project\vendor\craftcms\cms\src\web\Application.php(112): craft\web\Application->_postInit()
#14 C:\xampp\htdocs\project\vendor\yiisoft\yii2\base\BaseObject.php(109): craft\web\Application->init()
#15 C:\xampp\htdocs\project\vendor\yiisoft\yii2\base\Application.php(206): yii\base\BaseObject->__construct(Array)
#16 C:\xampp\htdocs\project\vendor\craftcms\cms\src\web\Application.php(100): yii\base\Application->__construct(Array)
#17 [internal function]: craft\web\Application->__construct(Array)
#18 C:\xampp\htdocs\project\vendor\yiisoft\yii2\di\Container.php(384): ReflectionClass->newInstanceArgs(Array)
#19 C:\xampp\htdocs\project\vendor\yiisoft\yii2\di\Container.php(156): y'craft\\web\\Appli...', Array, Array)
#20 C:\xampp\htdocs\project\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->geii\di\Container->build(t('craft\\web\\Appli...', Array, Array)
#21 C:\xampp\htdocs\project\vendor\craftcms\cms\bootstrap\bootstrap.php(248): yii\BaseYii::createObject(Array)
#22 C:\xampp\htdocs\project\vendor\craftcms\cms\bootstrap\web.php(52): require('C:\\xampp\\htdocs...')
#23 C:\xampp\htdocs\project\web\index.php(24): require('C:\\xampp\\htdocs...')
#24 {main}

**Comment by lukeholder** [comment]
@Sam-Black-0013 Can you update to the latest release of commerce? I think fixes have been made in the Carts service. If the issue persists on the latest release, we can re-open the ticket. Thanks.
