### ISSUE TITLE
Declined cards when creating a subscription cause a TypeError

### ISSUE THREAD

**Issue by cliveportman** [craftcms/commerce#918]
### Description
Creating a new subscription using even the example templates: if the card is declined, the result is:

```Return value of craft\commerce\controllers\SubscriptionsController::actionSubscribe() must be an instance of yii\web\Response, null returned```

### Steps to reproduce

1. Install Craft, install Commerce, install Commerce-Stripe
2. Setup test subscription linked to either test or live Stripe gateway.
3. Use example templates and go to create a subscription.
3. Enter "4000000000000002" (card declined) if test gateway. Pay.

### Additional info

- Craft version: 3.1.31
- PHP version: 7.2.4 (dev), 7.3.6 (production)
- Database driver & version: 5.7.21 (dev), 5.7.26 (production)
- Plugins & versions: Commerce 2.1.7, Commerce Stripe: 2.0.1.1

**Comment by lukeholder** [comment]
Thanks for reporting, fixed for the next release.
