### ISSUE TITLE
SubscriptionData not being supplied consistently

### ISSUE THREAD

**Issue by cliveportman** [craftcms/commerce#919]
### Description
I'm using my own module to send various emails in response to Commerce subscription events. previewing the email template in the browser was working fine but the email sending was failing. Turns out the subscriptionData doesn't need to be json decoded before use when the email template requests it but when viewed in a browser it does.

Workaround:

```
// Used in the preview template (subscriptionId comes from the route)
// Otherwise subscription is already defined, coming fro the subscription event
{% if subscription is not defined and subscriptionId | length %}
    {% set subscription = craft.subscriptions().id(subscriptionId).one() %}
{% endif %}

{% if subscription.subscriptionData is iterable %}
    {% set subscriptionData = subscription.subscriptionData %}
{% else %}
    {% set subscriptionData = subscription.subscriptionData | json_decode() %}
{% endif %}
```

### Steps to reproduce

1. Build a an email template that's sent in response to a subscription event.
2. Try and populate the email using the subscription object.
3. Also view the email in the browser with a route configured.

### Additional info

- Craft version: 3.1.31
- PHP version: 7.2.4 (dev), 7.3.6 (production)
- Database driver & version: 5.7.21 (dev), 5.7.26 (production)
- Plugins & versions: Commerce 2.1.7, Commerce Stripe: 2.0.1.1

**Comment by lukeholder** [comment]
I believe this was fixed in a recent release. The data should now always be an array, and should not need json decoding. Let me know if you have any other issues related to this.
