### ISSUE TITLE
Suggested Enhancement: Product canBePurchased()

### ISSUE THREAD

**Issue by JustJarethB** [craftcms/commerce#923]
### Description

There's quite often a use for knowing if a product can be bought or not (via stock and min-max limitations) but to my knowledge there is no built in function for this. 
Proposition is for a method assigned to 
craft\commerce\elementsProduct which will check all requirements for a product to be bought.
Non-exhaustive list that I can think of: any variant unlimited stock or stock > 0, "availableForPurchase", any variant max qty not breached.

**Comment by lukeholder** [comment]
On the Variant element there is a `getIsAvailable()` method that should check everything you reference:

```
    public function getIsAvailable(): bool
    {
        if ($this->getProduct() && !$this->getProduct()->availableForPurchase) {
            return false;
        }

        if ($this->getStatus() !== Element::STATUS_ENABLED) {
            return false;
        }

        return $this->stock >= 1 || $this->hasUnlimitedStock;
    }
```
https://github.com/craftcms/commerce/blob/develop/src/elements/Variant.php#L817-L828

**Comment by JustJarethB** [comment]
Thanks @lukeholder for the information, it looks like a good function. What about a method on the product in addition to variant, which essentially loops each variant and calls this function? 
PHP is not my strong suit but something like this?
```
for($variant in $product->getVariants()) {
    if ($variant->getIsAvailable()) {
        return true;
    }
    return false;
}
```

**Comment by lukeholder** [comment]
@JustJarethB your code would only return the availability of last variant (belonging to the product) is available or not. if some are available and some are not, what do you want it to return?

**Comment by JustJarethB** [comment]
Whoops, my bad @lukeholder . If at least one variant is available (i.e. can I buy this product?) then return true. That is the idea I was going for. I expect it to be handy in product listing pages, so you can alter rendering/hide unavailable products. It may be a niche use case in which case fair enough, I don't know how many people list products vs variants etc..
