### ISSUE TITLE
Clone product incl. variants

### ISSUE THREAD

**Issue by skoften** [craftcms/commerce#924]
Before Craft we used WooCommerce and we really don't regret migrating to Craft Commerce, but there is one feature that we really miss: the possibility to clone or duplicate a product with all variants. Would be really nice to have and is a hell of of time saver.

**Comment by lukeholder** [comment]
Thanks added this to the list for the next release!

**Comment by lukeholder** [comment]
You can open a product and "Save as a new product" in the save dropdown. 

![image](https://user-images.githubusercontent.com/133571/66620609-f257b700-eb95-11e9-9835-b310d4d63c03.png)

**Comment by skoften** [comment]
Hm, this feature doesn't cover it exactly. When saving a product as a new product, you manually need to change all product variant SKU's. In my case, a very disturbing job as some products have 250+ variants.

The idea of cloning/duplicating a product (just like WooCommerce does), is to generate a new product, with all variants, but automatically increasing the SKU for this new product. Or, even better would be if we could clone a product by entering a new SKU value, so these variants get added properly :-)

![Screenshot 2019-11-04 at 16 00 13](https://user-images.githubusercontent.com/1286410/68131612-a2160f80-ff1d-11e9-87ab-073894bab460.jpg)

**Comment by wmdhosting** [comment]
Is this posiblle to duplicate variant.. in any way..

**Comment by arifje** [comment]
Not to my knowledge, we're still using a custom PHP scripts to generate a XML structure with all variants (sizes, colors), combined with the Feed Me plugin to import them.

**Comment by masiorama** [comment]
Was cloning a product at some point involving also variants? I just upgraded to Craft 5 and my client is disappointed by the fact that variants are not transferred to the cloned product. My client says on version 4 was possible to clone variants, but I have no easy way to check now. @brandonkelly any hints?

**Comment by lukeholder** [comment]
@masiorama We are looking into this at the moment and will give you an update soon.

**Comment by nfourtythree** [comment]
Hi

Commerce `5.0.16` has now been released which includes a fix for cloning products including their variants.

Thanks!

**Comment by masiorama** [comment]
Tested, id works, thank you.
