### ISSUE TITLE
Duplicate Registration?

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#925]
### Description

I'm not sure if this is a Commerce issue or Craft in general or something we did but I noticed on a Commerce install of ours, we're getting multiple registrations for the same email address.

See the screengrab:

![duplicate-users](https://user-images.githubusercontent.com/3707869/60773547-d511d900-a0cc-11e9-88b2-1c8923a08ce0.jpg)

Looks like they had attempted to register and then do it again.

I was under the impression that users in a ``Pending``  state couldn't "register" multiple times?  That's pretty odd. It's also curious that it's only happening twice and not more. 

After someone places an order, we ask to register them at that point. We are getting successful registrations.

### Additional info

- Craft version:  3.1.33
- PHP version: 7+
- Database driver & version:
- Plugins & versions: Commere 2.1.7

**Comment by lukeholder** [comment]
Haven't had anyone else report this. Are you using the `registerUserOnOrderComplete` order setting? https://docs.craftcms.com/commerce/v2/update-cart-customer.html#registering-a-guest-customer-as-a-user

**Comment by RitterKnightCreative** [comment]
@lukeholder No. Might be worth trying though?  

On this particular site, we haven't touched the registration process as it was pre 2.1 and we just show them the standard registration form.

**Comment by lukeholder** [comment]
@RitterKnightCreative Send in a support ticket with your DB backup/dump for us to take a look. support@craftcms.com

**Comment by lukeholder** [comment]
Any update on this @RitterKnightCreative ? Please reference this ticket number when you send in your DB.
