### ISSUE TITLE
Queue Error Serialization failure: 1213 Deadlock Saving Product Type

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#927]
### Description
While this issue is specifically related to Commerce, I wasn't sure if this was actually a Craft problem under the hood. We have a very large multi-lingual Commerce site:

* ~3 million rows in the`craft_elements_sites` table
* ~3 thousand rows in the `craft_commerce_products` table

I added a new field to a Commerce product type, and it kicked off a bunch of queue jobs to re-save the product type elements for each site. A lot of these queue jobs are failing with errors like:

```
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
The SQL being executed was: UPDATE `craft_commerce_products` SET `typeId`=3, `taxCategoryId`=1, `shippingCategoryId`=1, `promotable`=1, `freeShipping`=0, `defaultPrice`='0', `defaultHeight`='0', `defaultLength`='0', `defaultWidth`='0', `defaultWeight`='0', `dateUpdated`='2019-06-30 09:00:07', `availableForPurchase`=1 WHERE `id`=48009
```

### Steps to reproduce

1. Have a Craft + Commerce site with **lots** of records
2. Add a field to a product type and save

### Additional info

- Craft version: Craft Pro 3.0.41.1
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.26
- Commerce version: `dev-develop` on commit 8e917fd271f0cc45092e363f2dfb706b5d4b27fb

**Comment by angrybrad** [comment]
Can you try updating to the latest Craft 3.2 release and see if you can replicate? There have been several performance improvements to the element saving pipeline on the 3.2 branch.

**Comment by davist11** [comment]
Interestingly, when I add a new field to a product type in craft 3.2.0 and commerce 2.1.9, it doesn't even trigger any queue jobs. Is this expected behavior now?

**Comment by angrybrad** [comment]
Yeah, see the discussion here: https://github.com/craftcms/cms/issues/3482

Going to go ahead and close this out.
