### ISSUE TITLE
'Gateway is not allowed' via AdminCP.

### ISSUE THREAD

**Issue by DomLip94** [craftcms/commerce#928]
### Description

A recent change to the code of how gateways are handled has killed the ability to make a payment via the admin portal. In stead we're met with 'Gateway not allowed'.

https://github.com/craftcms/commerce/commit/e59ae30debd5fe0c9ed706cbf0856424d94d4e96#diff-02bedf78409387c516bf2d73726b47d8

Specifically Line 169 - 
            `$gatewayAllowed = ($isSiteRequest && $gateway->isFrontendEnabled) && $gateway->availableForUseWithOrder($order);`

I've had to go around the world to make a work around for this, so could do with you implementing a fix as soon as possible.

### Steps to reproduce

1. Create order via front-end or back-end plugin - DO NOT PAY
2. Go to the order's page on Commerce admin portal
4. Click Transactions tab
4. Click 'Make payment' then 'Make Payment Now'

### Additional info

- Craft version: 
- PHP version: 7.3.6
- Database driver & version: MySQL 
- Plugins & versions:

**Comment by lukeholder** [comment]
Thanks for reporting, this has been fixed. Please update to 2.1.10 

 https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#2110---2019-07-12
