### ISSUE TITLE
Issue Sending Multiple Emails with an Order PDF attached

### ISSUE THREAD

**Issue by gvwarrior** [craftcms/commerce#930]
### Description
- When an order gets completed, my intention is to use the event **Order::EVENT_AFTER_ORDER_PAID** and within that event, send two emails. One email to our customer with the order PDF attached. The second email to an admin with the order PDF attached. 

- I can successfully send two emails WITHOUT the order PDF attached within the event described above... I am able to send two emails with the order PDF attached to ONLY ONE of the two emails....however, I am UNABLE to send both emails if I attach the order PDF to BOTH of the emails.

### Steps to reproduce

- With the code below in my application, I created an order, navigated through the checkout process and clicked 'Pay now'.... I am faced with an infinite loading screen. I Checked my email and see that the email with the subject "Email # 1" is in my inbox.

- It seems that the order is completed successfully, the FIRST email is sent successfully, BUT the second email gets hung up while attempting to attach the second PDF.

- I have tried to insert sleep() between the emails sending and many...many...many variations, but what I described is always the issue I encounter. Please... S.O.S

```
       Event::on(Order::class, Order::EVENT_AFTER_ORDER_PAID, function(Event $e)
        {
            /** @var Order $order */
            $order = $e->sender;
            // Get URL to PDF
            $receiptUrl = $order->getPdfUrl('customer');

            // First Email Parameters
            $targetEmail = 'TEST@gmail.com';
            $attachment['url'] = $receiptUrl;
            $attachment['params'] =
                [
                    'fileName' => 'Receipt',
                    'contentType' => 'application/pdf',
                ];

            // Second Email Parameters
            $targetEmail2 = 'TEST@gmail.com';

            $Mailer = Craft::$app->getMailer();

            // Create First Email
            $message = $Mailer->compose()
                ->setTo($targetEmail)
                ->setSubject('Email # 1')
                ->attach($attachment['url'], $attachment['params']);
            $message->send();

            sleep(2);
            // Create Second Email
            $message2 = $Mailer->compose()
                ->setTo($targetEmail2)
                ->setSubject('Email # 2')
                ->attach($attachment['url'], $attachment['params']);
            $message2->send();

        });
```

### Additional info

- Craft version: 
-- craftcms/cms: 3.2.1 (I ran into this same error on earlier versions as well)
-- craftcms/commerce: 2.1.1
- PHP version: 7.2.1

**Comment by RitterKnightCreative** [comment]
Not sure if this will make a difference but have you tried making a new mailer instance, ie ``$Mailer2 = Craft::$app->getMailer();`` and use that instance before sending the second email?

**Comment by gvwarrior** [comment]
Thanks for the suggestion. I attempted using a new mailer instance (i.e.
$Mailer2) to send the second email with the same error as described on
GitHub. The first email was sent successfully, but the second email does
not send and results in an infinite loading screen.

**Comment by angrybrad** [comment]
I just tested this on a fresh Craft and Commerce install on the latest versions using the stock Commerce templates and your exact code and wasn't able to reproduce.  I successfully received both emails at two different email addresses with the order PDFs attached.

My guess is either:

1.  Your mail server is blocking/rejecting the 2nd email based on the fact that it looks identical and happens nearly instantaneously after the first.

2.  There are some other plugins or template code that is interfering in the process.  I'd try to simplify variables to see if you can narrow it down.
