### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded. In product slug.

### ISSUE THREAD

**Issue by PopaWeb** [craftcms/commerce#937]
### Description
If the slug content accent in a product (EX: tasse-à-café) a got this error: Malformed UTF-8 characters, possibly incorrectly encoded.

Even if: 
'allowUppercaseInSlug' => false,
'limitAutoSlugsToAscii' => true,

### Steps to reproduce

1. Enter 'tasse-à-café' in a new/existing product slug or any other words containing accent.
2. Save it.

### Additional info

- Craft version: Craft Pro 3.2.5.1
- PHP version: 7.2.17
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Craft Commerce Pro 2.1.10

**Comment by nfourtythree** [comment]
Hi @PopaWeb 

Are you still getting an issue with this? 

Have just tried to replicate your issue with Craft `3.2.10` and Commerce `2.1.12.1` and everything seems to work fine.

If you are still having an issue it would be great if you could provide me with the logs/stack trace.

Thanks

**Comment by PopaWeb** [comment]
Hi @nfourtythree
The problem is gone since Commerce 2.1.10

Thanks for asking!
