### ISSUE TITLE
Commerce not using the From Name setting

### ISSUE THREAD

**Issue by nickcobley** [craftcms/commerce#939]
### Description

I'm seeing an issue where the setting in Craft Commerce > General Settings > From Name, is not being used. 

The notes for this field suggest it should be using the Site Name from General Settings, however, for me it's taking the Sender Name from Email Settings. However note I'm using the MailGun plugin, I'm not able to easily test right now if this problem goes away when not using a mail handler plugin. 

For me this is identical to #535 just in case this is a regression

### Steps to reproduce

1. Change From Name setting
2. Trigger status email

### Additional info

- Craft version: 3.2.6
- Commerce: 2.1.10
- PHP version: 7.3
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Mailgun 1.4.2

**Comment by lukeholder** [comment]
Can you try overriding the email too and let me know if it then picks up the override from name?

**Comment by nickcobley** [comment]
Sorry can you clarify that a bit more, do you mean try overriding the email address?

**Comment by lukeholder** [comment]
Try setting BOTH the 'From Email' AND the 'From Name'.

**Comment by nickcobley** [comment]
Sorry for the late reply on this one, just found time to test it.

Your spot on, if you set a value in both fields it works.

**Comment by nfourtythree** [comment]
Hi @nickcobley 

An update for this has been pushed and will be included in the next release.

Thanks!
