### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by kevadamson** [craftcms/commerce#940]
Are there any plugins for creating a sitemap.xml file of all products in Commerce?

**Comment by Mosnar** [comment]
You have a few options:

[SEO](https://plugins.craftcms.com/seo) Free
[SEOmate](https://plugins.craftcms.com/seomate) Free
[SEOmatic](https://plugins.craftcms.com/seomatic) Paid
[Sprout SEO](https://plugins.craftcms.com/sprout-seo) Paid
[Sprout Sitemap](https://plugins.craftcms.com/sprout-sitemaps) Paid

**Comment by kevadamson** [comment]
Many thanks :)
