### ISSUE TITLE
Show "Refund due" indicator when paid amount exceeds order amount.

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#945]
### Description
Currently when an order's paid amount is less than the value of the order the "Paid" indicator shows "Partial". But when the paid amount is greater than the value of the order, the "Paid" indicator shows "Paid".

It would be nice if there was some more noticeable indication that a refund was due on that order.

Admittedly this is an edge case but a current project has a requirement for the owner to be able to add to an already paid order. The orders are for a series of delivery drops. The orders only really close after the final drop has been made. But the customer may add to the series of drops during the lifecycle of of the order.

**Comment by lukeholder** [comment]
We could have an 'overPaid` status? Would that work?

**Comment by fantasticmachine** [comment]
Yes having an over paid status works fine for me and seems logical.

**Comment by lukeholder** [comment]
Fixed in #1015
