### ISSUE TITLE
Add refunded item back to available quantity

### ISSUE THREAD

**Issue by DomLip94** [craftcms/commerce#952]
### Description

As far as I'm aware, refunding an order doesn't increase the available quantity by re-adding that quantity back to the product.

If this is a bug please let me know. 

I am happy to make the changes myself and submit a PR if you wish.

Cheers

**Comment by lukeholder** [comment]
This for the PR, does this take into account partial refunds? Partial refunds is possible in the current refund feature.

**Comment by lukeholder** [comment]
You are right, we don't have a current restock ability when refunding.

**Comment by DomLip94** [comment]
Unfortunately not at the minute, I do intend to add it down the line though. Although it probably means a re-write of some functionality to avoid second guessing what's actually being refunded

**Comment by DomLip94** [comment]
If it is easier I can just create a plugin to release. I'd need to have a serious look at the code before starting something like this

**Comment by lukeholder** [comment]
Closed in favor of #1406
