### ISSUE TITLE
Malformed prices produce empty error details

### ISSUE THREAD

**Issue by jhicksrowmark** [craftcms/commerce#953]
### Description

Receiving nondescript model errors when product / variant pricing is malformed.

### Steps to reproduce

1. Provide a non-numeric price when creating a variant like in the example code below:
```
#partial code example from console controller

use craft\commerce\elements\Product;
use craft\commerce\elements\Variant;

#...... set $productTypeId

$product = new Product();
$product->title = 'Hello world';
$product->typeId = $productTypeId;
$product->enabled = true;
$variants = [];

$variant = new Variant();
$variant->title = 'example';
$variant->sku = 'asdf';
$variant->price = '$123';    #example malformed price, provides currency characters - same result if characters follow the numbers
$variant->hasUnlimitedStock = true;
$variants[] = $variant;

$product->setVariants($variants);
$success = Craft::$app->elements->saveElement($product);

echo var_export($success, true)."\n";
echo var_export($product->getErrors(), true)."\n";
return ExitCode::OK;
```
2. Receive empty error details
```
false
array (
  '' =>
  array (
    0 => '',
  ),
)
```
3. Comparison, output expected like:
```
false
array (
  'variants' =>
  array (
    0 => 'Not all SKUs are unique.',
  ),
)
```

### Additional info

- **Craft version: 3.2.8**
- PHP version: 7.3.6
- Database driver & version: MySQL 5.7.27
- Plugins & versions: **Commerce 2.1.10**, Redactor 2.3.3.2

**Comment by jhicksrowmark** [comment]
Modifying my example above, you *can* get the error details from the variants like below:
```
$product->setVariants($variants);
$success = Craft::$app->elements->saveElement($product);

echo var_export($success, true)."\n";
echo var_export($product->getErrors(), true)."\n";
foreach($variants as $variant){
	echo var_export($variant->getErrors(), true)."\n";
}
return ExitCode::OK;
```
**However**, I am leaving this open so someone can correct the issue where the product object is providing empty errors - it should at least describe that it could not save the variants.

**Comment by nfourtythree** [comment]
Hey @jhicksrowmark 

An update for this has been pushed and will be included in the next release of Commerce.

A generic error message is now created at the top level to inform that the variants could not be saved. You can obviously still check the variant error message for specific issues, in your original case, it would be that the `price` field is non-numeric.

Thanks!
