### ISSUE TITLE
Editing the customer on order edit screen raises error

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#956]
Getting the following JS error on Commerce 3 when typing `test` in the Customer dropdown when editing an order.

`{,…}
error: "SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'commerce3_craft.customers.id'; this is incompatible with sql_mode=only_full_group_by↵The SQL being executed was: SELECT `customers`.`id` AS `customerId`, `orders`.`email` AS `email`, count(`orders`.`id`) AS `totalOrders`, `customers`.`userId` AS `userId`, `users`.`firstName` AS `firstName`, `users`.`lastName` AS `lastName`↵FROM `commerce_customers` `customers`↵LEFT JOIN `commerce_orders` `orders` ON `customers`.`id` = `orders`.`customerId`↵LEFT JOIN `users` `users` ON `customers`.`userId` = `users`.`id`↵LIMIT 30"`

**Comment by lukeholder** [comment]
Does it work if you type a valid email? or just not work at all?

**Comment by lukeholder** [comment]
Also, what version of mysql?

**Comment by engram-design** [comment]
Seems like typing anything in triggers this - each time I type in the field. Probably due to enabling `sql_mode=only_full_group_by` on my setup.

Version 5.7.25

**Comment by engram-design** [comment]
@brandonkelly I have this enabled by default on my MySQL setup, and also have this set for plugin development debugging. Some people's installs (servers) can't change this setting, so its a good idea to cater for this use-case. You can't expect people to always be able to edit a my.cnf on every environment.

To be clear, I'm **not** doing this https://craftcms.stackexchange.com/a/12106/632

**Comment by engram-design** [comment]
@lukeholder FYI, this can be fixed by adding `->groupBy(['[[orders.id]]', '[[customers.id]]'])` to the [query](https://github.com/craftcms/commerce/blob/3.0/src/controllers/OrdersController.php#L382)
