### ISSUE TITLE
Can't Edit Product from Related Entry Popover

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce#958]
### Description
Not sure when this started happening, but we have a product field on a related entry. 

Trying to edit the product from that entry throws a 400 bad request error:

``Request must accept JSON in response``

### Steps to reproduce

1. Set a product field on an entry
2. Add a product on that entry to relate back
3. Edit the product from the entry
4. Save the product
5. Product won't save from the popover

Product will save just fine though by going into the product directly.

### Stack trace

``yii\web\BadRequestHttpException: Request must accept JSON in response in /site/vendor/craftcms/cms/src/web/Controller.php:345
Stack trace:
#0 /site/vendor/craftcms/cms/src/controllers/BaseElementsController.php(35): craft\web\Controller->requireAcceptsJson()
#1 /site/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\controllers\BaseElementsController->init()
#2 /site/vendor/yiisoft/yii2/base/Controller.php(86): yii\base\BaseObject->__construct(Array)
#3 [internal function]: yii\base\Controller->__construct('elements', Object(craft\web\Application), Array)
#4 /site/vendor/yiisoft/yii2/di/Container.php(376): ReflectionClass->newInstanceArgs(Array)
#5 /site/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\controlle...', Array, Array)
#6 /site/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('craft\\controlle...', Array)
#7 /site/vendor/yiisoft/yii2/base/Module.php(642): yii\BaseYii::createObject('craft\\controlle...', Array)
#8 /site/vendor/yiisoft/yii2/base/Module.php(596): yii\base\Module->createControllerByID('elements')
#9 /site/vendor/yiisoft/yii2/base/Module.php(522): yii\base\Module->createController('save-element')
#10 /site/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('elements/save-e...', Array)
#11 /site/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('elements/save-e...', Array)
#12 /site/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#13 /site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#14 /site/public_html/index.php(21): yii\base\Application->run()
#15 {main}
``

### Additional info

- Craft version: Craft CMS 3.2.8
- PHP version: 7+

**Comment by lukeholder** [comment]
Possibly related to https://github.com/craftcms/commerce/issues/418

**Comment by nfourtythree** [comment]
Hey @RitterKnightCreative 

As Luke mentioned, this may be related to another issue. I have pushed up a fix for that issue that should be included in the next release.

Let me know if you are still having issues after that and we can look into it further.

Thanks!

**Comment by lukeholder** [comment]
Fixed in 6d03be53d885395400a80e4caa298c378c835825 #418
