### ISSUE TITLE
Time period for an active cart to become inactive

### ISSUE THREAD

**Issue by matt-adigital** [craftcms/commerce#959]
### Description
In the [docs](https://docs.craftcms.com/commerce/v2/cart.html) it is specified that an active cart becomes inactive after 24 hours without an update. However in the code it is specified as only 1 hour when displayed in the cms.
https://github.com/craftcms/commerce/blob/e6ce3a1c533d8066a017109474a99a21c40c2db2/src/elements/Order.php#L1920

A client of ours would prefer to have this set back to 24 hours like it was in commerce 1, is it possible to have this added as a config setting which we can define going forwards? This would be a lot like the current purgeInactiveCartsDuration setting which is already available to us.

### Additional info

- Craft version: 3.2.9
- Commerce version: 2.1.11
- PHP version: 7.2.19
- Database driver & version: MySQL 5.5.5

**Comment by lukeholder** [comment]
Fixed in Commerce 3 alpha
