### ISSUE TITLE
Should PDFs be rendered upon viewing orders in CP/generating PDF url?

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/commerce#962]
### Description
PDFs are being rendered upon visiting the order details screen in the control panel or by calling `order.pdfUrl` in a template. Is this right?

https://github.com/craftcms/commerce/blob/f17c5e3153d5e18569cbfb2afbeb39b0fb4bd66b/src/elements/Order.php#L1044

Looks like it's doing as a method of validation, but seems odd. PDF generation isn't even an optional setting so shouldn't the assumption be that there will always be a PDF to render, given the correct number?

It may not be such a huge deal since domPdf can generate PDF's quite fast, but using other means of PDF generation could be timely.

I'm hooking into the `EVENT_BEFORE_RENDER_PDF` to render our own PDF via Browsershot, which uses node/puppeteer, so it takes a few seconds to complete. It's very noticeable when trying to browse orders or generate a URL.

I'm able to bypass it, for now at least, while browsing orders in control panel with this snippet below in the `EVENT_BEFORE_RENDER_PDF` event which will still output a working Download PDF button, and valid PDF url.
```
if (empty($request->queryParams['number'])) {
    return;
}
```

### Additional info

- Craft version: 3.2.10
- Commerce version: 2.1.11

**Comment by lukeholder** [comment]
Thank @chasegiunta, you are correct, it is rendering the PDF to know whether to show the button or not. It's not ideal. 

I just removed the pre-render for next release but added basic validation of the on the existence of the pdf template.

**Comment by chasegiunta** [comment]
@lukeholder FYI, while your fix did address the PDF rendering on every order page (and anything that uses `order.pdfUrl`) for me, it it also prevented the "Download PDF" button showing up on any order. 

It's not showing up due to, literally _any_ template path I pass into **Order PDF Template** not passing `$view->doesTemplateExist($file)`
https://github.com/craftcms/commerce/blob/79c1bc9d8227c8fdb5df83f64fc4b436e115305f/src/elements/Order.php#L1046

It passes if it's just checking `$file` existence.

I believe since the request is coming from the Control Panel, `resolveTemplate()` method is trying to resolve the template relative to `vendor/craftcms/cms/src/templates/` as described here: https://github.com/craftcms/cms/blob/55bc94128257ebf6d444c8fa5adfb8a06f45a0df/src/web/View.php#L672

**Comment by nfourtythree** [comment]
Hi @chasegiunta 

Thanks for the info, I believe it is, as you mentioned, not looking in the proper templating scope. It needs to be looking in the site scope.

Will look to get a fix for this pushed out.

Thanks.

**Comment by MichaelWheldon** [comment]
@nfourtythree hey just checking on when this was getting released?
