### ISSUE TITLE
Paid logo in order view can block product link on small screens

### ISSUE THREAD

**Issue by nickcobley** [craftcms/commerce#985]
### Description

In some circumstances, if viewing an order in the control panel that's been paid, the paid logo can block the link to the product that's been ordered. 

![Screenshot 2019-08-29 14 52 23](https://user-images.githubusercontent.com/70206/63917324-fc51aa80-ca6c-11e9-9793-6d34284a3166.png)

In this screenshot, the variant title, in this case, is quite short, combined with this particular screen resolution the paid logo overlays the link making it non-clickable. 

Bit of an edge case really, can't see many cases where this would be an issue but just letting you know. 

### Steps to reproduce

1. Set screen resolution to approx 400xp wide in my case all or part of the link will be covered.

### Additional info

- Craft version: 3.2.6
- Plugins & versions: 2.1.10

**Comment by lukeholder** [comment]
The stamp is removed in Commerce 3 Alpha. Position fixed in Commerce 2.x in the next release.
