### ISSUE TITLE
Stripe Payment Intents on Commerce 1

### ISSUE THREAD

**Issue by Tam** [craftcms/commerce#986]
### Description
We've got a stingy client who's refusing to pay for an upgrade to Craft 3 / Commerce 2, so we're stuck trying to get Stripe Payment Intents working on Commerce 1.

On our Commerce 2 sites we're using the `stripe.createPaymentMethod` JS function to get a Stripe Payment Method ID, and setting a hidden `paymentMethodId` field to this ID.  Obviously this won't work in Commerce 1 since `paymentMethodId` is already in use by Commerce. I've tried naming the field `token` (as it was for Stripe Charge) and `stripeToken` but neither of them work, usually erroring with:

```
Omnipay Gateway Communication Error: Client error response
[status code] 400
[reason phrase] Bad Request
[url] https://api.stripe.com/v1/payment_intents
```

So, how do we use the Stripe Payment Intents gateway on Commerce 1? I've checked the docs for Stripe Omnipay, but haven't managed to get anywhere.

### Additional info

- Craft version: 2.7.10
- Commerce version: 1.2.1369

**Comment by lukeholder** [comment]
Take a look at the example templates in Commerce 1 which were updated for the payment intents gateway. You should still be submitting the token, stripeToken which should work. Let us know how you go after looking at the example templates.

**Comment by Tam** [comment]
We keep getting that same error when trying to post the payment:
```
2019/08/27 11:01:56 [info] [plugin] Omnipay Gateway Communication Error: Client error response
[status code] 400
[reason phrase] Bad Request
[url] https://api.stripe.com/v1/payment_intents
in /var/www/html/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/html/craft/plugins/commerce/services/Commerce_PaymentsService.php (464)
in /var/www/html/craft/plugins/commerce/services/Commerce_PaymentsService.php (100)
```

The Stripe token is being generated successfully and posted to the server. I've tested this on both local and staging environments (with local and public domains respectively).

Here's the (condensed) JS we're using:

```js
const stripeElem = document.getElementById('stripe');

// ...

this.stripe = Stripe(window.stripePk);
const elements = this.stripe.elements();
this.card = elements.create('card');
this.card.mount(stripeElem);

// ...

onStripeSubmit = async e => {
	e.preventDefault();

	const {token, error} = await this.stripe.createToken(this.card);

	if (error) {
		this.showStripeError(error);
		return;
	}

	const hiddenInput = document.createElement('input');
	hiddenInput.setAttribute('type', 'hidden');
	hiddenInput.setAttribute('name', 'stripeToken');
	hiddenInput.setAttribute('value', token.id);
	this.form.appendChild(hiddenInput);

	this.onFormSubmit(e);
};
```
