### ISSUE TITLE
Cannot sort products by date updated or created

### ISSUE THREAD

**Issue by mdunbavan** [craftcms/commerce#987]
### Description
I have just updated to most stable release of commerce 2 and I cannot use the above to sort products by those columns. I used to be able to but now it isn't possible.

### Steps to reproduce

1. Go to hit the cog icon both of product types
2. Click checkboxes for Date update/date created
3. reload products index page
4. Hit the Date Updated row column header and it doesn't allow sort by asc or desc

### Additional info

- Craft version: 3.3
- PHP version: 7.1
- Database driver & version: mysql 5+
- Plugins & versions: commerce 2.1.12.1

Heres what I mean in the screenshot

![Screenshot 2019-08-29 at 16 09 58](https://user-images.githubusercontent.com/671281/63952704-f0b7b100-ca77-11e9-887e-641e89d8e850.png)

**Comment by lukeholder** [comment]
This has been fixed in the new commerce 2 release. Thanks.
