### ISSUE TITLE
Discounts based on cart contents

### ISSUE THREAD

**Issue by 23d1** [craftcms/commerce#988]
Would there be any interest in implementing a third discount category (besides Sales and Promotions/Codes) in the way of reducing price on cart/order or per line item if certain criteria are met? Could be at a product category, product level, variant level. For example; customer adds a pillow case, a duvet cover and a sheet. That combo (for each instance) would apply a discount based on the fact that they are related in a set.

I realize this isn't extremely hard to accomplish by adding adjusters via a module or plugin, but seems like a common enough practice that it could be added to the core functionality.

I have a basic (not finished) implementation of this in the form of a module, using categories with fields that define the discount, what products need to be in the cart and what variants are available in relation.

Any thoughts? If this is not on the radar or not deemed worth pursuing, I have some follow-up questions. ;)

**Comment by 23d1** [comment]
Just saw there's a "Commerce Bundles" plugin. Might be just that. Will close out for now.

**Comment by lukeholder** [comment]
Please comment on #260 for this feature going forward.
