### ISSUE TITLE
Commerce 3 - New order and Mark as completed

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#991]
Just trying out a few things when creating a new order from scratch. Its a bit jarring when creating a brand new order and hitting "Update Order", which kicks you out to the Order index screen. The user then has to navigate to the "Active Carts" to find the order just created.

Likewise behaviour for when clicking "Mark as completed", but to a lesser degree, as this would be expected behaviour (you're moving it from a draft to a completed order)

**Comment by nfourtythree** [comment]
Hi @engram-design 

I have just tried this and both "Update Order" and "Mark as Complete" keeps you on the order edit page.

Will close this issue but please let me know if you are still having this issue.

Thanks!
