### ISSUE TITLE
Checkout.js used for Stripe Payment Intents will be supported after 14 September?

### ISSUE THREAD

**Issue by DidoMarchet** [craftcms/commerce#994]
Hi,
i've upgrade my Craft Commerce 1 with the new release of Omnipay that support Stripe Payments Intents.

I've see the plugin now use stripe/checkout.js.

The Stripe support said checkout.js will not be supported after 14 September.
https://stripe.com/docs/legacy-checkout

I don't know what mean: the script will not work? Or it will still work but they will don't give support?

I'm sorry for my question but I want to know if you have heard about that.

Thanks in advance and kind regards,

Davide

**Comment by lukeholder** [comment]
Responded over support:

Hi Davide,

The page you linked does not mention a date for the closing down of the checkout.js system, just that it is now legacy and they have a recommended new system.

The existing checkout.js will continue to work.

The new payment intents gateway supports redirecting offsite if needed for the strong customer authentication (SCA) if the customer requires it. That is where the 14th Sept. changeover day comes from.

Recommend testing your checkout.js implementation with an SCA required test card (stripe lists them in their docs).

Hope that helps.

-Luke
