### ISSUE TITLE
Orders with no "Order Details" and with total price "£0.00"

### ISSUE THREAD

**Issue by kevadamson** [craftcms/commerce#996]
Since June, my client's website using Craft Commerce has had 6 orders (from about 4500) that have no order details and a total price of 0. Is this a bug or an oversight in my code that can cause this to happen?

**Comment by lukeholder** [comment]
Do they have any payment transactions on them?

**Comment by kevadamson** [comment]
Think I've found a possible process that can cause someone to be able to buy nothing for nothing:

If I add a product, go through steps to add shipping, then remove product, then go back to /store/checkout/payment, no products are there but shipping is, so user can buy just free shipping.

Order in admin shows no transactions.

**Comment by lukeholder** [comment]
As a start, you might want to hide the checkout/payment form if the order has nothing in it. We could look to add a setting to disallow attempted payment on empty carts.

**Comment by kevadamson** [comment]
Yeah that'd be handy, save me adding logic to the page.

**Comment by 23d1** [comment]
Just ran into this issue for the first time. No order details, no costs, nothing. And we do indeed hide payment and so forth for empty carts.

**Comment by nfourtythree** [comment]
The recommendation here would be to use the config setting `allowEmptyCartOnCheckout` and set it to `false` in your `commerce.php` config file.

This will stop people with no items in their cart being able to checkout.
